### PR TITLE
Fix e2e tests

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/278)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/278)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`cypress/pageObjects/MapEditor.ts` line 1 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XB_gL7jg_oqWdAsKV:-N8XB_gL7jg_oqWdAsKW:b-vtqnr4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/cypress/pageObjects/MapEditor.ts#L1)):*
> ```XML
> function positionStringToCoordinates(value: string | null) {
> ```

Maybe we should have documentation (comment) about what kind of "position strings" this does parse. And having small test suite for this wouldn't hurt either, reading (and possibly editing in the future) regexes is a bit tricky.
___
*[`ui/src/components/map/stops/Stop.tsx` line 21 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XB0Hl0zsK5GpQoK9-:-N8XB0Hl0zsK5GpQoK90:b-ucvwpy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/ui/src/components/map/stops/Stop.tsx#L21)):*
> ```XML
> 
> export const Stop = ({
>   testId,
> ```

I think we should have default value ("") for this to avoid "undefined" being ending up to DOM if this is not given. OK, now this is not optional but maybe it should be..?
___
*[`ui/src/components/map/stops/Stop.tsx` line 54 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XBQxg6qGSXmCFfA64:-N8XBQxg6qGSXmCFfA65:bnzcksk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/ui/src/components/map/stops/Stop.tsx#L54)):*
> ```XML
>       draggable={draggable}
>       onDragEnd={onDragEnd}
>       className={`${testId} map:stopMarker rounded-full`} // the Marker component does not have testid property, neither does data-testid work, so have to use className
> ```

Why "map:stopMarker" class?

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/278)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`ui/src/components/map/stops/Stop.tsx` line 54 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XBQxg6qGSXmCFfA64:-N8XD5jt86D0IxjJ--Xl:b-vx10cb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/ui/src/components/map/stops/Stop.tsx#L54)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why "map:stopMarker" class?
</blockquote></details>

If it is supposed to be testId, then I would rather at least define local variable `const testIds = `map:stopMarker ${testId}`` to make it self-evident that it is supposed to be test id and not css class name.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/278)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`cypress/pageObjects/MapEditor.ts` line 1 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XB_gL7jg_oqWdAsKV:-N8XKwDW7aZlZ3U1UGjT:bnhvl77) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/cypress/pageObjects/MapEditor.ts#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Maybe we should have documentation (comment) about what kind of "position strings" this does parse. And having small test suite for this wouldn't hurt either, reading (and possibly editing in the future) regexes is a bit tricky.
</blockquote></details>

actually, I found that cypress's jquery can get the position of this element just fine, so no need to mess around with this unreliable method
___
*[`ui/src/components/map/stops/Stop.tsx` line 21 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XB0Hl0zsK5GpQoK9-:-N8XGLt56ejSiT5x-iO7:bb60mde) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/ui/src/components/map/stops/Stop.tsx#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I think we should have default value ("") for this to avoid "undefined" being ending up to DOM if this is not given. OK, now this is not optional but maybe it should be..?
</blockquote></details>

I don't think we should allow undefined values or empty strings as test ids. Not for stop markers neither for any other interactive elements... It's always a bigger hassle to track and fill the missing test ids down when creating e2e tests than already filling them in at the first place.
___
*[`ui/src/components/map/stops/Stop.tsx` line 54 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XBQxg6qGSXmCFfA64:-N8XGtgD32sRhrpTVXJg:b-5ill21) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/ui/src/components/map/stops/Stop.tsx#L54)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If it is supposed to be testId, then I would rather at least define local variable `const testIds = `map:stopMarker ${testId}`` to make it self-evident that it is supposed to be test id and not css class name.
</blockquote></details>

good point! I don't actually think I need the `map:stopMarker` here, so I'll just remove it. Then the testId parameter will be obvious in the template string

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/278)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[`cypress/pageObjects/MapEditor.ts` line 1 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XB_gL7jg_oqWdAsKV:-N8XO8Wu64OoXH6ZnvsK:b-83sjoh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/cypress/pageObjects/MapEditor.ts#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually, I found that cypress's jquery can get the position of this element just fine, so no need to mess around with this unreliable method
</blockquote></details>

Nice!
___
*[`ui/src/components/map/stops/Stop.tsx` line 21 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/278#-N8XB0Hl0zsK5GpQoK9-:-N8XNql6CPvyGn5WG7sY:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b9a9931adcd5c141f638f747f02d0531fd3c5b4e/ui/src/components/map/stops/Stop.tsx#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think we should allow undefined values or empty strings as test ids. Not for stop markers neither for any other interactive elements... It's always a bigger hassle to track and fill the missing test ids down when creating e2e tests than already filling them in at the first place.
</blockquote></details>

OK

**Pull request merged**
