### PR TITLE
Visualize stop areas on map

### PR DESCRIPTION
**Pull request by Huulivoide**
### Improve LineRenderLayer
* Allow rendering of MultiLineStrings
* Allow overriding paint and layout settings partially

### Map: Open Stop details when clicking Area member

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)

### CODE REVIEW

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: 0 of 33 files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

___
*[`ui/src/graphql/stopAreas.ts` line 63 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0KK87C67U65LyT6nPA:-O0KK87C67U65LyT6nPB:b1e12zj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/21f3474bed056bfd2afb798138fa7c8c64b7d0c6/ui/src/graphql/stopAreas.ts#L63)):*
> ```XML
>     service_pattern_scheduled_stop_point(
>       where: { stop_place_ref: { _eq: $stopPlaceRef } }
>       limit: 1 # TODO: How to deal with versioning 🤔
> ```

The best solution for this is probably to use a database view which only contains the newest version of each group of stop places, similar which has been made for stop places.

**Review by Leitsi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 19 of 19 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: 22 of 33 files reviewed, 6 unresolved discussions (waiting on @culka and @Huulivoide)

___
*[`ui/src/components/map/markers/StopAreaMarker.tsx` line 62 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NJSjr9R1BSRvSmgiE:-O0NJSjr9R1BSRvSmgiF:bkwz6l) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/markers/StopAreaMarker.tsx#L62)):*
> ```XML
>       />
> 
>       {secondaryCirclesAtAngles.map((atAngle) => (
> ```

This is rather neat, but TBH I think I would've just slapped the SVG image here as is, instead of doing any calculations. I'd imagine that would be faster to render as well.
___
*[`ui/src/components/map/stop-areas/StopArea.tsx` line 12 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0K5TnoAsQm1EpPQXyk:-O0K5Tnp2ISe26blzWAx:b-p72bsd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/stop-areas/StopArea.tsx#L12)):*
> ```XML
> 
> type StopAreaProps = {
>   readonly area: StopAreaMinimalShowOnMapFieldsFragment;
> ```

We haven't been using `readonly` with Props, so this goes against code conventions of the project.
We do have a lint rule that already seems to (largely?) prevent modifying props passed as parameters. Does `readonly` bring any extra guarantees?

I'd rather we stick to one consistent practice.
If we want to enforce `readonly` for props, I'd investigate if this can be done with a linter rule (= autofix it to all existing props). And perhaps `Readonly` utility type, that is `type Props = Readonly<{...}>;` could be used with these?

Also, usually we just name the props `Props`, though I see this hasn't been a consistent practice.
___
*[`ui/src/components/map/stop-areas/StopAreaPopup.tsx` line 67 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NLc0X2fjbDjvQKHRB:-O0NLc0YE45RN6Bq4D4M:b-6etfe8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/stop-areas/StopAreaPopup.tsx#L67)):*
> ```XML
> 
>         <Row>
>           <Row className="items-center gap-1.5 text-sm">
> ```

Two nested rows seems weird?
___
*[`ui/src/components/map/stop-areas/StopAreas.tsx` line 55 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NLqbMAXVbCfanMFii:-O0NLqbMAXVbCfanMFij:b6fz50d) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/stop-areas/StopAreas.tsx#L55)):*
> ```XML
>     <>
>       {stopAreasResult.data?.stops_database?.areas
>         ?.filter(notNullish)
> ```

I'd maybe slap these filtered areas into a variable.
Could then skip the nullish coalescing from `editedArea` initialization as well.
___
*[`ui/src/utils/localizedString.ts` line 9 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NNgoaCZdK3CJSUWG1:-O0NNgoaCZdK3CJSUWG2:bbf5ecr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/utils/localizedString.ts#L9)):*
> ```XML
> });
> 
> type AlternativeName = {
> ```

I don't think these alternative names belong here. This file feels more like for just handling stuff with `LocalizedString` type. Rather just put them in a separate file.

Maybe under utils/stop-registry since this is a stop registry specific type, I suppose?
___
*[`ui/src/utils/localizedString.ts` line 43 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NNzt8A4Pxufn9a2gi:-O0NNzt8A4Pxufn9a2gj:b-7dynr2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/utils/localizedString.ts#L43)):*
> ```XML
>   defaultLang: string | null | undefined,
>   alternatives: ReadonlyArray<AlternativeName> | null | undefined,
> ): string | null {
> ```

Could maybe unit test this.

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: 0 of 37 files reviewed, 6 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`ui/src/components/map/markers/StopAreaMarker.tsx` line 62 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NJSjr9R1BSRvSmgiE:-O0OcTeb5aJ1Ze0ukit-:b-ol8yac) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/markers/StopAreaMarker.tsx#L62)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This is rather neat, but TBH I think I would've just slapped the SVG image here as is, instead of doing any calculations. I'd imagine that would be faster to render as well.
</blockquote></details>

Vaihdettu generoitu SVG koodi tilalle
___
*[`ui/src/components/map/stop-areas/StopArea.tsx` line 12 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0K5TnoAsQm1EpPQXyk:-O0OcZaZCCywp2WQwGYB:b-v71yct) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/stop-areas/StopArea.tsx#L12)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

We haven't been using `readonly` with Props, so this goes against code conventions of the project.
We do have a lint rule that already seems to (largely?) prevent modifying props passed as parameters. Does `readonly` bring any extra guarantees?

I'd rather we stick to one consistent practice.
If we want to enforce `readonly` for props, I'd investigate if this can be done with a linter rule (= autofix it to all existing props). And perhaps `Readonly` utility type, that is `type Props = Readonly<{...}>;` could be used with these?

Also, usually we just name the props `Props`, though I see this hasn't been a consistent practice.
</blockquote></details>

Vaihdettu laittomat, mutta konvention mukaset tyypitykset.
___
*[`ui/src/components/map/stop-areas/StopAreaPopup.tsx` line 67 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NLc0X2fjbDjvQKHRB:-O0OcjwT4oo5bAGKJvlN:b-e11cw1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/stop-areas/StopAreaPopup.tsx#L67)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Two nested rows seems weird?
</blockquote></details>

Tuli kopipastana StopPopupin puolelta
___
*[`ui/src/components/map/stop-areas/StopAreas.tsx` line 55 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NLqbMAXVbCfanMFii:-O0Ocodh8FYGuXn9QaDN:bu8zpw3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/stop-areas/StopAreas.tsx#L55)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I'd maybe slap these filtered areas into a variable.
Could then skip the nullish coalescing from `editedArea` initialization as well.
</blockquote></details>

Siirretty kamaa muuttujaan
___
*[`ui/src/graphql/stopAreas.ts` line 63 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0KK87C67U65LyT6nPA:-O0OcrrIB85KlJYWYAEW:b-ucdhkz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/21f3474bed056bfd2afb798138fa7c8c64b7d0c6/ui/src/graphql/stopAreas.ts#L63)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

The best solution for this is probably to use a database view which only contains the newest version of each group of stop places, similar which has been made for stop places.
</blockquote></details>

Kommentti muutettu, tässä ei ollutkaan mitään ongelmaa
___
*[`ui/src/utils/localizedString.ts` line 9 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NNgoaCZdK3CJSUWG1:-O0Ocylg9Yr85XSEO0RU:b2h5not) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/utils/localizedString.ts#L9)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I don't think these alternative names belong here. This file feels more like for just handling stuff with `LocalizedString` type. Rather just put them in a separate file.

Maybe under utils/stop-registry since this is a stop registry specific type, I suppose?
</blockquote></details>

Siirretty stop-registry kansion alle
___
*[`ui/src/utils/localizedString.ts` line 43 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0NNzt8A4Pxufn9a2gi:-O0Od1EpEG9VNra7oRmJ:bhkszhn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/utils/localizedString.ts#L43)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could maybe unit test this.
</blockquote></details>

Ja rustattu läjä testejä.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 34 files at r8, 5 of 7 files at r9, 16 of 23 files at r10, 1 of 3 files at r11, 2 of 5 files at r12, 2 of 4 files at r13, 9 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: all files reviewed, 5 unresolved discussions (waiting on @culka and @Huulivoide)

___
*[`jore4-hasura` line 1 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0P2iJmEBJbP0bgf1bC:-O0P2iJu5Sd8OIuFobz2:bkd8v4m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/jore4-hasura#L1)):*
> ```
> Subproject commit 567bbdaa11db06cf0dd4844b8a988b4d12d2d328
> ```

In addition to this the pinned Hasura docker images need to be updated. See eg. commit `30e8ed82ce7d0a497ed122bf6dbd6f5aaa72e9ad`. The setup scripts use whatever image is pinned in the docker compose files, so without updating those an old image will be used.
For Hasura you can find the images from https://hub.docker.com/r/hsldevcom/jore4-hasura/tags , once the Hasura repository PR has been merged the image should be something like `hsldevcom/jore4-hasura:hsl-main--...`
___
*[`ui/src/components/map/stop-areas/MemberStops.tsx` line 45 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0PA4fH8e3GNnsb4I4o:-O0PA4fH8e3GNnsb4I4p:b-fwn896) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/ui/src/components/map/stop-areas/MemberStops.tsx#L45)):*
> ```XML
>   return (
>     <>
>       {area.members
> ```

Could move this to variable as well, like we did in `ui/src/components/map/stop-areas/StopAreas.tsx`
___
*[`ui/src/components/map/stop-areas/StopArea.tsx` line 12 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0K5TnoAsQm1EpPQXyk:-O0P79UPE-Qblm-UJGpH:by4ey6k) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0c56e54893b47f7792ab494edba4cb2b88065c88/ui/src/components/map/stop-areas/StopArea.tsx#L12)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Vaihdettu laittomat, mutta konvention mukaset tyypitykset.
</blockquote></details>

:heavy_check_mark: 

Conventions can and should be changed when there is a good reason. This case can further be discussed in Slack, for example.
___
*[`ui/src/hooks/stop-areas/useResolveScheduledStopPointByStopPlaceRef.ts` line 35 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0PPslW5SNIWkk9_b8Y:-O0PPslW5SNIWkk9_b8Z:b-mmfdd8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/ui/src/hooks/stop-areas/useResolveScheduledStopPointByStopPlaceRef.ts#L35)):*
> ```XML
>         }
> 
>         return stop as ServicePatternScheduledStopPoint;
> ```

This should maybe type cast to `StopWithLocation`, to match `ResolveScheduledStopPointByStopPlaceRefFn` return value definition.

Actually it is of type `ScheduledStopPointAllFieldsFragment`, but using that would require a bit more changes it feels like, and probably wouldn't even improve things really.
___
*[`ui/src/locales/fi-FI/common.json` line 120 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0PKyFfCNjhqoSbo-Bp:-O0PKyFfCNjhqoSbo-Bq:b-93k4hb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/ui/src/locales/fi-FI/common.json#L120)):*
> ```JSON
>     "delete": "Poista pysäkkialue",
>     "errors": {
>       "failed_to_resolve_scheduled_stop_point": "Pysäkin tietojen selvitys epäonnistui! Syy"
> ```

Typically camel case is used in translation keys here.

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: 3 of 42 files reviewed, 5 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`jore4-hasura` line 1 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0P2iJmEBJbP0bgf1bC:-O1GSeTk4YHxR81wtAms:brf5q5z) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/jore4-hasura#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

In addition to this the pinned Hasura docker images need to be updated. See eg. commit `30e8ed82ce7d0a497ed122bf6dbd6f5aaa72e9ad`. The setup scripts use whatever image is pinned in the docker compose files, so without updating those an old image will be used.
For Hasura you can find the images from https://hub.docker.com/r/hsldevcom/jore4-hasura/tags , once the Hasura repository PR has been merged the image should be something like `hsldevcom/jore4-hasura:hsl-main--...`
</blockquote></details>

Docker files updated
___
*[`ui/src/components/map/stop-areas/MemberStops.tsx` line 45 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0PA4fH8e3GNnsb4I4o:-O1GTzPbC7z7wEJZYpqN:bevsic7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/ui/src/components/map/stop-areas/MemberStops.tsx#L45)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could move this to variable as well, like we did in `ui/src/components/map/stop-areas/StopAreas.tsx`
</blockquote></details>

:heavy_check_mark: 
___
*[`ui/src/hooks/stop-areas/useResolveScheduledStopPointByStopPlaceRef.ts` line 35 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0PPslW5SNIWkk9_b8Y:-O1GTvo15w1StRPRzNkT:bevsic7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/ui/src/hooks/stop-areas/useResolveScheduledStopPointByStopPlaceRef.ts#L35)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This should maybe type cast to `StopWithLocation`, to match `ResolveScheduledStopPointByStopPlaceRefFn` return value definition.

Actually it is of type `ScheduledStopPointAllFieldsFragment`, but using that would require a bit more changes it feels like, and probably wouldn't even improve things really.
</blockquote></details>

:heavy_check_mark: 
___
*[`ui/src/locales/fi-FI/common.json` line 120 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O0PKyFfCNjhqoSbo-Bp:-O1GTVCG2Xwh75wxtqki:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/145d8bf56022657a0044c57fe07ab80b3ade9a03/ui/src/locales/fi-FI/common.json#L120)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Typically camel case is used in translation keys here.
</blockquote></details>

Done.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 36 files at r15.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: 5 of 42 files reviewed, 1 unresolved discussion (waiting on @culka and @Huulivoide)

___
*[`ui/src/graphql/stopAreas.ts` line 1 at r22](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O1GgrZ_BOQaVqqDeonI:-O1GgrZ_BOQaVqqDeonJ:b-kimbuy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ba7525800b0ee77d2203d9fa16b2b7365cf132c3/ui/src/graphql/stopAreas.ts#L1)):*
> ```XML
> /* eslint-disable @typescript-eslint/no-unused-vars */
> ```

This eslint disable won't be needed if you slap a `GQL_` prefix to the query variables. This is due to `'@typescript-eslint/no-unused-vars': [ 'error', { varsIgnorePattern: '^GQL' }, ]` in `.eslintrc.js`
So:
```
const GQL_QUERY_GET_STOP_AREAS_BY_LOCATION = gql`
const GQL_GET_SCHEDULED_STOP_POINT_BY_STOP_PLACE_REF = gql`
```

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: 5 of 45 files reviewed, 1 unresolved discussion (waiting on @culka and @Leitsi)

___
*[`ui/src/graphql/stopAreas.ts` line 1 at r22](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O1GgrZ_BOQaVqqDeonI:-O1HJNzOEJ-To6sb3akZ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ba7525800b0ee77d2203d9fa16b2b7365cf132c3/ui/src/graphql/stopAreas.ts#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This eslint disable won't be needed if you slap a `GQL_` prefix to the query variables. This is due to `'@typescript-eslint/no-unused-vars': [ 'error', { varsIgnorePattern: '^GQL' }, ]` in `.eslintrc.js`
So:
```
const GQL_QUERY_GET_STOP_AREAS_BY_LOCATION = gql`
const GQL_GET_SCHEDULED_STOP_POINT_BY_STOP_PLACE_REF = gql`
```
</blockquote></details>

Done.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847)* status: 5 of 45 files reviewed, 1 unresolved discussion (waiting on @culka and @Huulivoide)

___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 28 at r29](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-O1LIdIq1obQn1Luxmcb:-O1LIdIr4uOfold0jTpy:bj9gnhw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4e38e25995b79d3e6b003272d16f12a866708379/ui/src/uiComponents/LoadingOverlay.tsx#L28)):*
> ```XML
> 
>     const setVisibleTimeout = setTimeout(() => setVisible(true), delay);
>     return clearTimeout(setVisibleTimeout);
> ```

I don't think this works as intended. Because `clearTimeout` is called immediately, the callback on setTimeout will never be called. I think we can just leave the `clearTimeout` call out altogether.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/847#-:-O1Lvvk-4IFrd4HmQWdo:bnfp4nl)* status: 5 of 45 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
