### PR TITLE
Add line editing test

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#576

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/348)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/348)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDSBOzM8kdtpBmlc1nl):*
Sounds like this would belong to its own commit.
___
*[`cypress/e2e/editLineInfo.cy.ts` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDS8am-C-MNcdFeZXLj:-NDS8am-C-MNcdFeZXLk:b-5r4r58) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5e00dab0b06e6bafe5b40508b77cb517d59e7221/cypress/e2e/editLineInfo.cy.ts#L10)):*
> ```XML
> import { insertToDbHelper, removeFromDbHelper } from '../utils';
> 
> const testLine1 = {
> ```

This object does not have all the fields that line should have, but it has properties that lines can't have, such as "id", "newLabel" and "newName" and "newPriority". 
In fact "label" is the only field that is only valid property for RouteLine, but its not needed here.

Maybe rather do something like this:

```
import { Priority } from '@hsl/jore4-test-db-manager';

const testInputs = {
   newLabel: 'Muokattu label 1999',
  newName: 'Muokattu nimi Testilinja FI',
  newPriority: Priority.Draft,
}

const lines: LineInsertInput[] = [
  {
    ...buildLine({ label: '1999' }),
    line_id: '9e800038-3fbb-11ed-b878-0242ac120002',
    ...
}

```
___
*[`cypress/e2e/editLineInfo.cy.ts` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDSBdS06r-Dl37oHXIr:-NDSBdS06r-Dl37oHXIs:b-oe6h8s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5e00dab0b06e6bafe5b40508b77cb517d59e7221/cypress/e2e/editLineInfo.cy.ts#L22)):*
> ```XML
>     ...buildLine({ label: testLine1.label }),
>     line_id: testLine1.id,
>     priority: 10,
> ```

You could avoid this magic number value: `Priority.Standard`
___
*[`cypress/e2e/editLineInfo.cy.ts` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDSBnUk36tVdczrrBgC:-NDSBnUk36tVdczrrBgD:b-bmj9d1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5e00dab0b06e6bafe5b40508b77cb517d59e7221/cypress/e2e/editLineInfo.cy.ts#L23)):*
> ```XML
>     line_id: testLine1.id,
>     priority: 10,
>     primary_vehicle_mode: ReusableComponentsVehicleModeEnum.Bus,
> ```

Is this relevant for the test? Does the test fail if this is something else than bus? If not, please remove this.
___
*[`cypress/e2e/editLineInfo.cy.ts` line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDS6juw0hIYoWKhdAmB:-NDS6juxAi2fu6oT97ms:bev0krx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5e00dab0b06e6bafe5b40508b77cb517d59e7221/cypress/e2e/editLineInfo.cy.ts#L24)):*
> ```XML
>     priority: 10,
>     primary_vehicle_mode: ReusableComponentsVehicleModeEnum.Bus,
>     validity_start: DateTime.fromISO('2020-05-02 23:11:32Z'),
> ```

This is not valid ISO timestamp and luxon can't parse this:
```
invalid: 
Invalid
explanation: 
"the input \"2020-05-02 23:11:32Z\" can't be parsed as ISO 8601"
```
So, how does this even work?

If validity_start and/or validity_end are not relevant for the test, you can just delete these.



_Code quote:_
```XML
DateTime.fromISO('2020-05-02 23:11:32Z')
```
___
*[`cypress/e2e/editLineInfo.cy.ts` line 59 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDS7YoS4ROzAvYxgv2b:-NDS7IQ78itGh6p5RFPd:b-883kep) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5e00dab0b06e6bafe5b40508b77cb517d59e7221/cypress/e2e/editLineInfo.cy.ts#L59)):*
> ```XML
> 
>   it("Edits a line's name, label, validity period and priority", () => {
>     lineDetailsPage.editLine();
> ```

What does this command do? That is not self-evident from the command name so this function just obfuscates things. I would just remove this function and call `lineDetailsPage.getEditLineButton().click();` directly here.
___
*[`cypress/pageObjects/MapFooter.ts` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDS5k8I6miDGPONzQgJ:-NDS5k8I6miDGPONzQgK:b-d2pt9v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5e00dab0b06e6bafe5b40508b77cb517d59e7221/cypress/pageObjects/MapFooter.ts#L19)):*
> ```XML
> 
>   save() {
>     return cy.getByTestId('MapFooter::saveButton').click({ timeout: 15000 });
> ```

Default command timeout seems to be 4000ms, so this is quite generous increase to that. Maybe I would rather start at slightly shorter value, e.g. 8000 or 10000 and go longer only if that is not enough.

https://docs.cypress.io/guides/references/configuration#Timeouts

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/348)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDWceuG4q6xvqzEdbBe):*
This change is not anymore included in this PR so this row should be also removed from commit message :wink:

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/348)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/348#-NDWceuG4q6xvqzEdbBe):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This change is not anymore included in this PR so this row should be also removed from commit message :wink: 
</blockquote></details>

Done.

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/348)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
