### PR TITLE
Allow setting observation date in map view

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/ObservationDateOverlay.tsx, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMWdgd0TNnvKj-e1Mu:-MyMWdgd0TNnvKj-e1Mv:brsr0z5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/components/map/ObservationDateOverlay.tsx#L3)):*
> ```XML
> import { useTranslation } from 'react-i18next';
> import { MdLayers } from 'react-icons/md';
> import { useFilterStops } from '../../hooks/useFilterStops';
> ```

could group these hooks as well in `hooks/index.ts` and then the import would simplify a tiny bit
___
*[src/context/MapFilterReducer.ts, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMX-1u3fkPnU-OyKmb:-MyMX-1u3fkPnU-OyKmc:b140oj0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/context/MapFilterReducer.ts#L17)):*
> ```XML
>   showStopFilterOverlay: boolean;
>   stopFilters: Filter[];
>   observationDate: string;
> ```

this should rather have a luxon `DateTime` type
___
*[src/hooks/useFilterStops.ts, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMY1bv-PTwiUvBixfd:-MyMY1bv-PTwiUvBixfe:b4xgz40) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/hooks/useFilterStops.ts#L20)):*
> ```XML
> const isFutureStop: (date: string) => StopFilterFunction = (date) => (stop) =>
>   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>   mapToISODate(stop.validity_start)! > date;
> ```

IMHO all these comparisons would work and look better if you used the luxon `DateTime` type instead of comparing strings

Also, those eslint warnings are there for a reason ;) should handle the undefined/null cases properly
___
*[src/hooks/useObservationDate.ts, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMYrmE1bdqIgJ9968b:-MyMYrmF187ving3vyuN:b-gdowjy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/hooks/useObservationDate.ts#L4)):*
> ```XML
> import { MapFilterContext } from '../context/MapFilterContext';
> 
> export const useObservationDate = () => {
> ```

I don't really see the use of this hook, there's no actual business logic here. If you want to simplify the use of the context, you could create a new 'setObservationDate' action in `MapFilterReducer`

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[src/components/map/ObservationDateOverlay.tsx, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMWdgd0TNnvKj-e1Mu:-MyMakA13uRQlSzOyyB8:b7r7d3v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/components/map/ObservationDateOverlay.tsx#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could group these hooks as well in `hooks/index.ts` and then the import would simplify a tiny bit
</blockquote></details>

Ahh this one again. I will fix it.
___
*[src/context/MapFilterReducer.ts, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMX-1u3fkPnU-OyKmb:-MyR-DiGAxP1-drmsaqn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/context/MapFilterReducer.ts#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should rather have a luxon `DateTime` type
</blockquote></details>

Done.
___
*[src/hooks/useFilterStops.ts, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMY1bv-PTwiUvBixfd:-MyR-G201LU6Pnk87-wQ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/hooks/useFilterStops.ts#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

IMHO all these comparisons would work and look better if you used the luxon `DateTime` type instead of comparing strings

Also, those eslint warnings are there for a reason ;) should handle the undefined/null cases properly
</blockquote></details>

Done.
___
*[src/hooks/useObservationDate.ts, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMYrmE1bdqIgJ9968b:-MyR-Ge9BNmW48jPThm1:bw5l68m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/hooks/useObservationDate.ts#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't really see the use of this hook, there's no actual business logic here. If you want to simplify the use of the context, you could create a new 'setObservationDate' action in `MapFilterReducer`
</blockquote></details>

After considering this again and chatting with Tuomas at the office, I decided to make the (future) hook related to routes and observation date separate and leave this functionality to the context.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/context/MapFilterActions.ts, line 8 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyR7AwB4NcNtTwRmzqj:-MyR7AwB4NcNtTwRmzqk:b-qy73ig) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e99ea98908ea1768e89d22a01f2782c741cb9e72/src/context/MapFilterActions.ts#L8)):*
> ```XML
> };
> 
> export const setObservationDate = (
> ```

hmm, interesting solution... I like it!

You should decide however if you'd like to keep all your actions in this separate file or within the reducer file. Currently SetOvervationDateAction is here while the SetStateAction is in the reducer. I'm fine with both solutions but let's make it consistent!

I *think* you could also simplify your life drastically by defining your actions like this:
```
export const setObservationDate = (date: DateTime) => ({type: 'setObservationDate', payload: date});
export const setState = (state: Partial<IMapFilterContext>) => ({type: 'setState', payload: state});
export type MapFilterActions = ReturnType<typeof setObservationDate> | ReturnType<typeof setState>;
```
___
*[src/hooks/useFilterStops.ts, line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyR9aw783ewR1QN6CZL:-MyR9aw783ewR1QN6CZM:b-ucgg5m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e99ea98908ea1768e89d22a01f2782c741cb9e72/src/hooks/useFilterStops.ts#L29)):*
> ```XML
> const isPastStop: (date: DateTime) => StopFilterFunction = (date) => (stop) =>
>   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>   stop.validity_end && DateTime.fromISO(stop.validity_end)! < date;
> ```

why the `!` marks here? You've already validated the existence of stop.validity_end so DateTime.fromISO should also be valid
___
*[src/hooks/useObservationDate.ts, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyMYrmE1bdqIgJ9968b:-MyR9ofx5F452NoEaH6P:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7eb4ad0d43126c3c456cd9fbb6fc0345f0141db/src/hooks/useObservationDate.ts#L4)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

After considering this again and chatting with Tuomas at the office, I decided to make the (future) hook related to routes and observation date separate and leave this functionality to the context.
</blockquote></details>

OK

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[src/hooks/useFilterStops.ts, line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyR9aw783ewR1QN6CZL:-MyRXOx47ojjYafRlnDL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e99ea98908ea1768e89d22a01f2782c741cb9e72/src/hooks/useFilterStops.ts#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

why the `!` marks here? You've already validated the existence of stop.validity_end so DateTime.fromISO should also be valid
</blockquote></details>

Done.
___
*[src/context/MapFilterActions.ts, line 8 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyR7AwB4NcNtTwRmzqj:-MyRXQBOEf-F1uJOKiAl:bxog7l2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e99ea98908ea1768e89d22a01f2782c741cb9e72/src/context/MapFilterActions.ts#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

hmm, interesting solution... I like it!

You should decide however if you'd like to keep all your actions in this separate file or within the reducer file. Currently SetOvervationDateAction is here while the SetStateAction is in the reducer. I'm fine with both solutions but let's make it consistent!

I *think* you could also simplify your life drastically by defining your actions like this:
```
export const setObservationDate = (date: DateTime) => ({type: 'setObservationDate', payload: date});
export const setState = (state: Partial<IMapFilterContext>) => ({type: 'setState', payload: state});
export type MapFilterActions = ReturnType<typeof setObservationDate> | ReturnType<typeof setState>;
```
</blockquote></details>

Done. I didn't implement the last suggestion though, because it breaks the types for actions. Reducer will not recognize the type of the payload for different action types if done that way.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[src/context/MapFilter/types.ts, line 9 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyRgQtsE8riXIRj65UP:-MyRgQtsE8riXIRj65UQ:b-r3zebx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7452d5a7daea5d8d81b693d1f821f8fb96d9cebc/src/context/MapFilter/types.ts#L9)):*
> ```XML
> }
> 
> export interface Filter {
> ```

this is growing to a bigger and bigger mess, let's just use some more standardized solutions instead of trying to reinvent the wheel... E.g. here's a good looking one: https://github.com/reduxjs/redux/issues/992#issuecomment-191152574

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/ObservationDateOverlay.tsx, line 6 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-Myf6JuI1S2VmTMLBlqq:-Myf6JuI1S2VmTMLBlqr:bvscw0o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7452d5a7daea5d8d81b693d1f821f8fb96d9cebc/src/components/map/ObservationDateOverlay.tsx#L6)):*
> ```XML
> import { MdLayers } from 'react-icons/md';
> import { setObservationDate } from '../../context/MapFilter/actions';
> import { MapFilterContext } from '../../context/MapFilter/context';
> ```

let's follow the current pattern and group all the MapFilter* files for export in a `context/MapFilter/index.ts` file!

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/116)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[src/components/map/ObservationDateOverlay.tsx, line 6 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-Myf6JuI1S2VmTMLBlqq:-MyfWoE10CE2TvepX3ZE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7452d5a7daea5d8d81b693d1f821f8fb96d9cebc/src/components/map/ObservationDateOverlay.tsx#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's follow the current pattern and group all the MapFilter* files for export in a `context/MapFilter/index.ts` file!
</blockquote></details>

Done.
___
*[src/context/MapFilter/types.ts, line 9 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/116#-MyRgQtsE8riXIRj65UP:-MyfWs4nC3tysfBHx5uy:bsqssy5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7452d5a7daea5d8d81b693d1f821f8fb96d9cebc/src/context/MapFilter/types.ts#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is growing to a bigger and bigger mess, let's just use some more standardized solutions instead of trying to reinvent the wheel... E.g. here's a good looking one: https://github.com/reduxjs/redux/issues/992#issuecomment-191152574
</blockquote></details>

Let's have a look at this issue later and consider whether to use Redux or something like that to manage state.

**Pull request merged**
