### PR TITLE
Display stop area member labels on confirm delete dialog

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888)

### CODE REVIEW

**Review by Huulivoide — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 277 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888#-O4jG3qh52nthaOk43XU:-O4jG3qh52nthaOk43XV:b-vwtb8k) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb23320f73b328a606fd3a8647eed20b53441042/ui/src/hooks/stop-registry/useGetStopDetails.ts#L277)):*
> ```XML
>   const stopPoint = result.data?.service_pattern_scheduled_stop_point[0];
>   let stopDetails = null;
>   if (stopPoint) {
> ```

Tän jos ottais ulos erilliseen funktioon, niin ei tarvis käyttää `let` muuttujaa. Niitä on ikävä seurailla ku kokoajan pitää pitää ne mielessä ja kattoo että missä kaikkialla niitä mutatoidaan.
___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 47 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888#-O4jGlj-9W7xc3DfPir4:-O4jGlj-9W7xc3DfPir5:b-iaho6z) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb23320f73b328a606fd3a8647eed20b53441042/ui/src/utils/stop-registry/stopPlace.ts#L47)):*
> ```XML
> 
>   const filtered: Array<T> = [];
>   stopPlaces.forEach((sp) => {
> ```

Mielummin ihan vaan `return stopPlaces.filter...` tämmösen for-push looppauksen sijaan.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888)* status: all files reviewed, 2 unresolved discussions (waiting on @Huulivoide and @Leitsi)

___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 277 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888#-O4jG3qh52nthaOk43XU:-O4jHtrJ8ERC7kedRFWH:b-elv1ub) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb23320f73b328a606fd3a8647eed20b53441042/ui/src/hooks/stop-registry/useGetStopDetails.ts#L277)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tän jos ottais ulos erilliseen funktioon, niin ei tarvis käyttää `let` muuttujaa. Niitä on ikävä seurailla ku kokoajan pitää pitää ne mielessä ja kattoo että missä kaikkialla niitä mutatoidaan.
</blockquote></details>

Was about to comment the same as Jesse, so with a helper function we can avoid using let.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @Huulivoide)

___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 277 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888#-O4jG3qh52nthaOk43XU:-O4jo2BBErBcuqG22-Fw:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb23320f73b328a606fd3a8647eed20b53441042/ui/src/hooks/stop-registry/useGetStopDetails.ts#L277)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Was about to comment the same as Jesse, so with a helper function we can avoid using let.
</blockquote></details>

Done.
___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 47 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888#-O4jGlj-9W7xc3DfPir4:-O4jqPvg8tZzu3l8hL_1:b-93pxil) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb23320f73b328a606fd3a8647eed20b53441042/ui/src/utils/stop-registry/stopPlace.ts#L47)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Mielummin ihan vaan `return stopPlaces.filter...` tämmösen for-push looppauksen sijaan.
</blockquote></details>

Had ended up with this approach due to difficulties with typings. But managed to find correct syntax and get this working with just filter after all, :heavy_check_mark:

**Review by Huulivoide — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/888#-:-O4nuOtSE5u189CaKd1j:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

**Pull request merged**
