### PR TITLE
UI: Prefer Nullish Coalescing operator to OR operator

### PR DESCRIPTION
**Pull request by Huulivoide**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 90 of 92 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)* status: all files reviewed, 6 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/time.ts` line 48 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1X3Key0m5U_KrMqnnx:-O1X3Key0m5U_KrMqnny:b76sp1w) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9de222c9b60cd9d655732bc6e33347f6c407de49/ui/src/time.ts#L48)):*
> ```XML
> 
>   // if not explicitly defined, the i18n locale is used
>   const dateLocale = locale ?? i18n.language;
> ```

I think here `||` might be desired since an empty string hardly is a valid locale.
___
*[`ui/src/components/routes-and-lines/line-details/FieldValue.tsx` line 20 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1X7f663MXglwE-h8oZ:-O1X7f663MXglwE-h8o_:b-7bgfrc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9de222c9b60cd9d655732bc6e33347f6c407de49/ui/src/components/routes-and-lines/line-details/FieldValue.tsx#L20)):*
> ```XML
>     <Column className={className}>
>       <span className="text-3xl font-semibold" data-testid={testId}>
>         {value ?? '-'}
> ```

I think here we might want to see a `-` in case of an empty string, so `||` would be more suitable.
___
*[`ui/src/components/stop-registry/stops/stop-details/StopTitleRow.tsx` line 21 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDzdhAEictsofOMck:-O1XDzdhAEictsofOMcl:b-itknzf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/components/stop-registry/stops/stop-details/StopTitleRow.tsx#L21)):*
> ```XML
>       </h2>
>       <div className="text-xl" data-testid={testIds.names}>
>         <span>{stopDetails?.stop_place?.nameFin || '-'}</span>
> ```

Placeholder `-` would be preferrable to empty strings, thus `||`.
___
*[`ui/src/hooks/routes/useEditRouteMetadata.ts` line 64 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1X9NX6DV9_m7b6jp3T:-O1X9NX6DV9_m7b6jp3U:brpjmmk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/hooks/routes/useEditRouteMetadata.ts#L64)):*
> ```XML
>   label: route.label,
>   onLineId: route.on_line_id,
>   variant: route.variant || null,
> ```

Am not sure if an empty string is a valid variant. `||` makes sense here.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 48 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XCxwc5dYOJB6abyDH:-O1XCxwc5dYOJB6abyDI:bqy3nt2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9de222c9b60cd9d655732bc6e33347f6c407de49/ui/src/uiComponents/DialogWithButtons.tsx#L48)):*
> ```XML
>         <div
>           className={`w-full rounded-md bg-white p-5 shadow-md ${
>             widthClassName ?? 'max-w-sm'
> ```

This doesn't really work as it did before, with `= ''` default values for `widthClassName`. Those are used at least in this component and `ConfirmationDialog`.
___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 229 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDa_j7re3F8L87J1c:-O1XDa_j7re3F8L87J1d:bopmkxz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/utils/stop-registry/stopPlace.ts#L229)):*
> ```XML
> ): StopPlaceEnrichmentProperties => {
>   return {
>     nameFin: stopPlace.name?.value || undefined,
> ```

The `||` in this mapper were intentional: would rather use a single falsy value instead of having to deal with empty strings etc and undefineds.

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)* status: 87 of 95 files reviewed, 6 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/time.ts` line 48 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1X3Key0m5U_KrMqnnx:-O1XP9vb08LeDL6p-c_T:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9de222c9b60cd9d655732bc6e33347f6c407de49/ui/src/time.ts#L48)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think here `||` might be desired since an empty string hardly is a valid locale.
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/line-details/FieldValue.tsx` line 20 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1X7f663MXglwE-h8oZ:-O1XPAcoBu5SR80j-ESw:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9de222c9b60cd9d655732bc6e33347f6c407de49/ui/src/components/routes-and-lines/line-details/FieldValue.tsx#L20)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think here we might want to see a `-` in case of an empty string, so `||` would be more suitable.
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/StopTitleRow.tsx` line 21 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDzdhAEictsofOMck:-O1XPBD-EHLI1JRh4YRK:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/components/stop-registry/stops/stop-details/StopTitleRow.tsx#L21)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Placeholder `-` would be preferrable to empty strings, thus `||`.
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useEditRouteMetadata.ts` line 64 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1X9NX6DV9_m7b6jp3T:-O1XPEzF7iun6dwt7SA5:b847gbn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/hooks/routes/useEditRouteMetadata.ts#L64)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Am not sure if an empty string is a valid variant. `||` makes sense here.
</blockquote></details>

Variant is of a type number, not string. At quick glance, 0 seems like a valid value
___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 229 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDa_j7re3F8L87J1c:-O1XQQs-85BuH4k4TX1M:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/utils/stop-registry/stopPlace.ts#L229)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

The `||` in this mapper were intentional: would rather use a single falsy value instead of having to deal with empty strings etc and undefineds.
</blockquote></details>

Done.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 48 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XCxwc5dYOJB6abyDH:-O1XQRcR3f879EbWI9yR:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9de222c9b60cd9d655732bc6e33347f6c407de49/ui/src/uiComponents/DialogWithButtons.tsx#L48)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This doesn't really work as it did before, with `= ''` default values for `widthClassName`. Those are used at least in this component and `ConfirmationDialog`.
</blockquote></details>

Done.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r3, 2 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)* status: 89 of 95 files reviewed, 2 unresolved discussions (waiting on @Huulivoide)

___
*[`.eslintrc.js` line 37 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1_Uiyt2oA8FsM9c5_U:-O1_Uiyu3FVrYVXTZL3p:b1xmdh9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6e0913a86d144a606619193bd56e74f959f8e7b5/.eslintrc.js#L37)):*
> ```JavaScript
>       },
>       rules: {
>         '@typescript-eslint/prefer-nullish-coalescing': 'error',
> ```

Just curious, why is the override needed, instead of just adding these to the normal `rules` and `parserOptions`?
___
*[`ui/src/components/stop-registry/stops/stop-details/layout/LabeledDetail.tsx` line 19 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1_RGf90CKH00wkEGrL:-O1_RGf90CKH00wkEGrM:b-911v49) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6e0913a86d144a606619193bd56e74f959f8e7b5/ui/src/components/stop-registry/stops/stop-details/layout/LabeledDetail.tsx#L19)):*
> ```XML
>         {
>           // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
>           detail || '-'
> ```

This change causes E2E test failures currently. `0` is a valid value for some fields (altitude).
Maybe we can just revert this and go with `??`? At least all E2E tests in stopDetails suite seem to pass then.
___
*[`ui/src/hooks/routes/useEditRouteMetadata.ts` line 64 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1X9NX6DV9_m7b6jp3T:-O1_Ox3z7i4XPXHGW60a:bwxosob) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/hooks/routes/useEditRouteMetadata.ts#L64)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Variant is of a type number, not string. At quick glance, 0 seems like a valid value
</blockquote></details>

:heavy_check_mark: yep, true, should probably be restricted by the form validation anyway if it wasn't, :ok_hand: 
___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 229 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDa_j7re3F8L87J1c:-O1_NvHK4k4-fiMlyeE1:b2fzy7o) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/utils/stop-registry/stopPlace.ts#L229)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant all of the fields in this function, actually. They all use the same pattern.

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)* status: 89 of 95 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`.eslintrc.js` line 37 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1_Uiyt2oA8FsM9c5_U:-O1_w-g19mnIrZZdHXR7:bb5ia85) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6e0913a86d144a606619193bd56e74f959f8e7b5/.eslintrc.js#L37)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Just curious, why is the override needed, instead of just adding these to the normal `rules` and `parserOptions`?
</blockquote></details>

Moved block to end and added comments. Short answer: else linting JSON files breaks.
___
*[`ui/src/components/stop-registry/stops/stop-details/layout/LabeledDetail.tsx` line 19 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1_RGf90CKH00wkEGrL:-O1_xQORDhJ2l2xW_GrE:b-7r4wve) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6e0913a86d144a606619193bd56e74f959f8e7b5/ui/src/components/stop-registry/stops/stop-details/layout/LabeledDetail.tsx#L19)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This change causes E2E test failures currently. `0` is a valid value for some fields (altitude).
Maybe we can just revert this and go with `??`? At least all E2E tests in stopDetails suite seem to pass then.
</blockquote></details>

Made an extra special function for this 😌
___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 229 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDa_j7re3F8L87J1c:-O1_yfMB8JDqtSmlPBXL:b-7ruwbv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/utils/stop-registry/stopPlace.ts#L229)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I meant all of the fields in this function, actually. They all use the same pattern.
</blockquote></details>

|| used for all string props now

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)* status: 87 of 95 files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 229 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDa_j7re3F8L87J1c:-O1aI8EOEMVKxkpyGdGT:b-swe4tg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/utils/stop-registry/stopPlace.ts#L229)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

|| used for all string props now
</blockquote></details>

Missed a couple, ` abbreviationFin` and `abbreviationSwe` that is. Could still fix those, since other alternative names here already use `?.value || undefined`.

**Review by Huulivoide — COMMENTED** [review]
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)* status: 93 of 95 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/utils/stop-registry/stopPlace.ts` line 229 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864#-O1XDa_j7re3F8L87J1c:-O1apHaBE4aNvuIXrFDn:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/99dd84c7c3c75f5e485eb475bc7a68334fbd4bdd/ui/src/utils/stop-registry/stopPlace.ts#L229)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Missed a couple, ` abbreviationFin` and `abbreviationSwe` that is. Could still fix those, since other alternative names here already use `?.value || undefined`.
</blockquote></details>

Done.

**Review by Huulivoide — COMMENTED** [review]
> Reviewed 1 of 7 files at r3, 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/864)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

**Pull request merged**
