### PR TITLE
Add loading indicator to map view

### PR DESCRIPTION
**Pull request by eleksi**
Show loading indicator on map-matching calls and mutations.

Resolves https://github.com/HSLdevcom/jore4/issues/877

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/277)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/277)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`ui/src/styles/globals.css` line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8SmC7e1QjtbdUylqbc:-N8SmC7e1QjtbdUylqbd:b-qn4x3x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/83e6c5422cd58efa8ac5af27db6c7c28e086ae4b/ui/src/styles/globals.css#L24)):*
> ```CSS
> }
> 
> .center-in-view {
> ```

Why to introduce css when we are using tailwind? I guess this could be written as: `top-2/4 left-2/4` and then somehow with translate: https://tailwindcss.com/docs/translate#arbitrary-values ( `translate-x-[-50%] translate-y-[-50%] ?)
___
*[`ui/src/styles/loading-indicator.css` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8Snvdk7no813OZ4GNf:-N8Snvdk7no813OZ4GNg:ba2p5tt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/83e6c5422cd58efa8ac5af27db6c7c28e086ae4b/ui/src/styles/loading-indicator.css#L1)):*
> ```CSS
> .loading-indicator,
> ```

Where did this css came from? If it was written by you it should be in tailwind class names instead.
Please also note that we have `react-spinners` library as dependency so probably we don't want to do this manually.
___
*[`ui/src/uiComponents/LoadingIndicator.tsx` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8SnY-m5v7rnpSE3wZG:-N8SnY-m5v7rnpSE3wZH:b-rna7x5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/83e6c5422cd58efa8ac5af27db6c7c28e086ae4b/ui/src/uiComponents/LoadingIndicator.tsx#L8)):*
> ```XML
> }
> 
> export const LoadingIndicator: React.FC<Props> = ({
> ```

We also have `ui/src/uiComponents/Spinner.tsx`. Do we need also this and if yes, in which case we want to use one or another?

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/277)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/styles/globals.css` line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8SmC7e1QjtbdUylqbc:-N8Ssubm5BMHeyZvAsM_:b-p96xu1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/83e6c5422cd58efa8ac5af27db6c7c28e086ae4b/ui/src/styles/globals.css#L24)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why to introduce css when we are using tailwind? I guess this could be written as: `top-2/4 left-2/4` and then somehow with translate: https://tailwindcss.com/docs/translate#arbitrary-values ( `translate-x-[-50%] translate-y-[-50%] ?)
</blockquote></details>

Thanks, somehow didn't expect tailwind to support translate.
___
*[`ui/src/styles/loading-indicator.css` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8Snvdk7no813OZ4GNf:-N8St1O97tIX-tr9BBE3:b66mxpy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/83e6c5422cd58efa8ac5af27db6c7c28e086ae4b/ui/src/styles/loading-indicator.css#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Where did this css came from? If it was written by you it should be in tailwind class names instead.
Please also note that we have `react-spinners` library as dependency so probably we don't want to do this manually.
</blockquote></details>

Oh, `react-spinners` will do the trick, should be close enough to the designed indicator. Didn't realize we had that dependency as I don't think we have any spinners used yet.
___
*[`ui/src/uiComponents/LoadingIndicator.tsx` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8SnY-m5v7rnpSE3wZG:-N8StdaO0asb4HUogbiT:b6jt9wd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/83e6c5422cd58efa8ac5af27db6c7c28e086ae4b/ui/src/uiComponents/LoadingIndicator.tsx#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We also have `ui/src/uiComponents/Spinner.tsx`. Do we need also this and if yes, in which case we want to use one or another?
</blockquote></details>

I don't know what that component is for, I can't find any usages of it. Now that we can use `PulseLoader` from `react-spinners` I don't think `LoadingIndicator` is even needed anymore.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/277)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 14 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8SwkXWB55oQUGRq2YY:-N8SwkXWB55oQUGRq2YZ:b-aq6403) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/1d4e64fee7a95294822da91b126edd52d30c7c7e/ui/src/uiComponents/LoadingOverlay.tsx#L14)):*
> ```XML
>     <Column
>       className="fixed top-1/2 left-1/2 z-50 -translate-y-1/2 -translate-x-1/2 cursor-wait"
>       data-testid={testId}
> ```

Does this cause`data-testid="undefined"` to end up into DOM? If yes, then please at least give default value "" to testId property.

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/277)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`ui/src/components/map/Map.tsx` line 229 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8SyiJT936xOq5WjSa3:-N8SyiJT936xOq5WjSa4:b-q2zcw4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2baf6b2c866d2aaad05a6d6e657dc780b02b53c1/ui/src/components/map/Map.tsx#L229)):*
> ```XML
>         ref={routeEditorRef}
>       />
>       {isLoading && <LoadingOverlay />}
> ```

This might be matter of personal preference, but I would rather refactor props API of LoadingOverlay to have `show`/`isVisible` prop so that that it could be used in JSX like `<LoadingOverlay visible={myFlag} />` instead of `{myFlag && <LoadingOverlay />`.
___
*[`ui/src/components/map/routes/RouteEditor.tsx` line 169 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8SzVHLBHZka7K4L5nU:-N8SzVHLBHZka7K4L5nV:bf5rwh2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2baf6b2c866d2aaad05a6d6e657dc780b02b53c1/ui/src/components/map/routes/RouteEditor.tsx#L169)):*
> ```XML
>   const onSave = async () => {
>     try {
>       startLoading();
> ```

Naming of this function is not very descriptive. Start loading what? How about writing these somehow like this:
```
const setIsLoading = (loading: boolean) => dispatch(setMapEditorLoadingAction(loading));
setIsLoading(true)
setIsLoading(false)
```
___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 2 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8T-u2Y8-3EUI-EB_ZE:-N8T-u2Y8-3EUI-EB_ZF:b-t09k3q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2baf6b2c866d2aaad05a6d6e657dc780b02b53c1/ui/src/uiComponents/LoadingOverlay.tsx#L2)):*
> ```XML
> import React from 'react';
> import { PulseLoader } from 'react-spinners';
> ```

`import PulseLoader from 'react-spinners/PulseLoader'` to avoid importing all the spinners for nothing.
___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 12 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8T-L5QDqJEzuyv6gfj:-N8T-L5R-5V8nEz4ztqG:buihwgx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2baf6b2c866d2aaad05a6d6e657dc780b02b53c1/ui/src/uiComponents/LoadingOverlay.tsx#L12)):*
> ```XML
> export const LoadingOverlay: React.FC<LoadingOverlayProps> = ({ testId }) => {
>   return (
>     <Column
> ```

Does it make semantic sense to have Overlay implemented from Column?

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/277)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 5 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/277#-N8TA_WnEcMrsDUJyYxC:-N8TA_WnEcMrsDUJyYxD:bsn1e8d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/1deb1a509648088e1a94f70b4a77f119b52c06c9/ui/src/uiComponents/LoadingOverlay.tsx#L5)):*
> ```XML
> import { theme } from '../generated/theme';
> 
> interface LoadingOverlayProps {
> ```

Convention has been to call these just "Props" :wink:

**Pull request merged**
