### PR TITLE
Add validations to route/line edit/create

### PR DESCRIPTION
**Pull request by eleksi**
- Check that route's first stop resides on first infrastructure link and final stop on final infrastructure link
- Check that route's validity period is inside line's validity period when editing / creating a route
- Check that edited line's validity period contains all contained routes' validity periods

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/182)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/182)* status: 0 of 11 files reviewed, 11 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/graphql/route.ts` line 180 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2G9P9mA4hYVMLwZ0em:-N2G9P9mA4hYVMLwZ0en:b-mq728r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/graphql/route.ts#L180)):*
> ```XML
> export const mapLineDetailsResult = (
>   result:
>     | ReturnType<typeof useGetLineDetailsByIdQuery>
> ```

there's already a wrapper type for this:
`GqlQueryResult<GetLineDetailsByIdQuery>`
___
*[`src/hooks/useEditLine.ts` line 41 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2G9add67LvgSoiuBCI:-N2G9add67LvgSoiuBCJ:b255loy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L41)):*
> ```XML
>   const { checkIsRouteValidityInsideLineValidity } = useValidateRoute();
> 
>   const [getLineWithRoutesById] = useAsyncQuery<
> ```

there's already a typed hook generated for this:
`useGetLineDetailsWithRoutesByIdAsyncQuery`
___
*[`src/hooks/useEditLine.ts` line 45 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GCpSnDOwYAWjHYMyZ:-N2GCpSnDOwYAWjHYMy_:bl2kkom) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L45)):*
> ```XML
>     GetLineDetailsWithRoutesByIdQueryVariables
>   >(GetLineDetailsWithRoutesByIdDocument);
> ```

you could move this function to its own hook as you did with the route validation. E.g.
`src/hooks/lines/useLineValidation.ts`
___
*[`src/hooks/useEditLine.ts` line 46 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GATqIEcQ0NrEAahCV:-N2GATqIEcQ0NrEAahCW:b-eb8q80) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L46)):*
> ```XML
>   >(GetLineDetailsWithRoutesByIdDocument);
> 
>   const validateLine = async ({ lineId, form }: EditParams) => {
> ```

this should have a more descriptive name, like `checkIsLineValidityOutsideRouteValidity`
___
*[`src/hooks/useEditLine.ts` line 51 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GAj5P1AOtArJb2wH1:-N2GAj5P1AOtArJb2wH2:b-1nbn7u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L51)):*
> ```XML
> 
>     const routes = line?.line_routes;
>     const conflictinRoutes: string[] = [];
> ```

typo: `conflictingRoute`
___
*[`src/hooks/useEditLine.ts` line 53 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GB3xlETmklZ5OgveO:-N2GB3xlETmklZ5OgveP:b-hpi6wq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L53)):*
> ```XML
>     const conflictinRoutes: string[] = [];
> 
>     const lineValidityStart = mapDateInputToValidityStart(form.validityStart);
> ```

these conversions are already done in the `mapFormToInput` function. Instead of running the validation on the formState, you could just run them on the input
___
*[`src/hooks/routes/types.ts` line 4 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GBWreApdyFxDItDmE:-N2GBWreApdyFxDItDmF:bpuaop5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/routes/types.ts#L4)):*
> ```XML
> 
> export interface RouteGeometry {
>   stopIdsWithinRoute: UUID[];
> ```

I'd just move this to `src/graphql/route.ts`, this is where we've been dumping these helper types
___
*[`src/hooks/routes/useValidateRoute.ts` line 33 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GBl-U1OOznLxYj2Zf:-N2GBl-U1OOznLxYj2Zg:b-72q0v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/routes/useValidateRoute.ts#L33)):*
> ```XML
>   const { t } = useTranslation();
> 
>   const [getStopsByIds] = useAsyncQuery<
> ```

there are typed hooks already generated for this
___
*[`src/hooks/routes/useValidateRoute.ts` line 38 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GBnam20U6_7OQgx-k:-N2GBnam20U6_7OQgx-l:b-72q0v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/routes/useValidateRoute.ts#L38)):*
> ```XML
>   >(GetStopsByIdsDocument);
> 
>   const [getLineById] = useAsyncQuery<
> ```

there are typed hooks already generated for this
___
*[`src/locales/en-US/common.json` line 36 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GC3qt8M6wI6_x7bHR:-N2GC3qt8M6wI6_x7bHS:bexb6t2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/locales/en-US/common.json#L36)):*
> ```JSON
>     "finalStopNotOnFinalInfraLink": "Route's final stop must reside on route's final infrastructure link.",
>     "startNotInsideLineValidity": "Route's validity period cannot start before line's validity period.",
>     "endNotInsideLineValidity": "Route's validity period cannot exceed line's validity period."
> ```

exceed the line's
___
*[`src/locales/en-US/common.json` line 60 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GC9AUAyFfnKjC_v78:-N2GC9AV0doDOOkmcxmu:bexb6t2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/locales/en-US/common.json#L60)):*
> ```JSON
>     "noDrafts": "No drafts",
>     "showDraftDetails": "Show draft details",
>     "routesOutsideValidity": "The following routes' validity period exceed line's new validity period"
> ```

exceed the line's

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/182)* status: 0 of 15 files reviewed, 10 unresolved discussions (waiting on @pallost)

___
*[`src/graphql/route.ts` line 180 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2G9P9mA4hYVMLwZ0em:-N2KxFpY1o7OWRaUj2uQ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/graphql/route.ts#L180)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there's already a wrapper type for this:
`GqlQueryResult<GetLineDetailsByIdQuery>`
</blockquote></details>

Done.
___
*[`src/hooks/routes/useValidateRoute.ts` line 33 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GBl-U1OOznLxYj2Zf:-N2Kv7As2ZeUbRnpRAEt:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/routes/useValidateRoute.ts#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there are typed hooks already generated for this
</blockquote></details>

Done.
___
*[`src/hooks/routes/useValidateRoute.ts` line 38 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GBnam20U6_7OQgx-k:-N2Kv7vm5hEo-TGyrp19:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/routes/useValidateRoute.ts#L38)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there are typed hooks already generated for this
</blockquote></details>

Done.
___
*[`src/locales/en-US/common.json` line 36 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GC3qt8M6wI6_x7bHR:-N2KwZjs5_u6cpBvzeQs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/locales/en-US/common.json#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

exceed the line's
</blockquote></details>

Done.
___
*[`src/locales/en-US/common.json` line 60 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GC9AUAyFfnKjC_v78:-N2Kw_2n4CR-43qcfx_n:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/locales/en-US/common.json#L60)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

exceed the line's
</blockquote></details>

Done.
___
*[`src/hooks/routes/types.ts` line 4 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GBWreApdyFxDItDmE:-N2KzRdg38xrBmBFhz_F:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/routes/types.ts#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd just move this to `src/graphql/route.ts`, this is where we've been dumping these helper types
</blockquote></details>

Done.
___
*[`src/hooks/useEditLine.ts` line 41 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2G9add67LvgSoiuBCI:-N2KrVqf4Bn9ac9_p1mN:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L41)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there's already a typed hook generated for this:
`useGetLineDetailsWithRoutesByIdAsyncQuery`
</blockquote></details>

Done.
___
*[`src/hooks/useEditLine.ts` line 45 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GCpSnDOwYAWjHYMyZ:-N2KtP9mBvJYrZvNmcCn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L45)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could move this function to its own hook as you did with the route validation. E.g.
`src/hooks/lines/useLineValidation.ts`
</blockquote></details>

Done.
___
*[`src/hooks/useEditLine.ts` line 46 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GATqIEcQ0NrEAahCV:-N2KtXec7keSJaH61eKn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L46)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should have a more descriptive name, like `checkIsLineValidityOutsideRouteValidity`
</blockquote></details>

Done.
___
*[`src/hooks/useEditLine.ts` line 53 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2GB3xlETmklZ5OgveO:-N2KuwdFAwwDnJE2-2jg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/42b32a2ca50f13bcc8215ed6476998b323ba8346/src/hooks/useEditLine.ts#L53)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

these conversions are already done in the `mapFormToInput` function. Instead of running the validation on the formState, you could just run them on the input
</blockquote></details>

Done.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/182)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[`src/hooks/routes/useValidateRoute.ts` line 97 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2L5Q177WpvEL5aqIMy:-N2L5Q177WpvEL5aqIMz:bhg6g6q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71b15b6ca1b0e89fe8dc016b0870df90a33775f2/src/hooks/routes/useValidateRoute.ts#L97)):*
> ```XML
> 
>   const checkIsRouteValidityInsideLineValidity = (
>     route: RouteRoute | ValidityPeriodParams,
> ```

This doesn't actually need the RouteRoute and RouteLine types here, both route and line could just have the type ValidityPeriod

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/182)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`src/hooks/routes/useValidateRoute.ts` line 97 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2L5Q177WpvEL5aqIMy:-N2LcNIpBUol67VlMTBk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71b15b6ca1b0e89fe8dc016b0870df90a33775f2/src/hooks/routes/useValidateRoute.ts#L97)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This doesn't actually need the RouteRoute and RouteLine types here, both route and line could just have the type ValidityPeriod
</blockquote></details>

Done.
___
*[`src/hooks/routes/useValidateRoute.ts` line 68 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2LcOtK8QvZ-9-jSCoC:-N2LcOtK8QvZ-9-jSCoD:b-mmv8ab) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3524451148b15e88cfab81ae59de33f29163fb5d/src/hooks/routes/useValidateRoute.ts#L68)):*
> ```XML
> 
>     // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>     const startingStop = stops.find(
> ```

There was a bug here. Stops are not in order in the response, so getting them from response by index will not work.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/182)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[`src/hooks/routes/useValidateRoute.ts` line 68 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/182#-N2LcOtK8QvZ-9-jSCoC:-N2PnZW87Ip5lOtz0KGq:b-ni995w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3524451148b15e88cfab81ae59de33f29163fb5d/src/hooks/routes/useValidateRoute.ts#L68)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

There was a bug here. Stops are not in order in the response, so getting them from response by index will not work.
</blockquote></details>

Good catch! But this function is written overly complicated... but as this check is going to be removed soon, no need to fix it...

**Pull request merged**
