### PR TITLE
Implement timing place creation

### PR DESCRIPTION
**Pull request by eleksi**
Resolves HSLdevcom/jore4#1031

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/405)

### CODE REVIEW

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 9 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/405)* status: 9 of 14 files reviewed, all discussions resolved

___
*[`ui/src/locales/fi-FI/common.json` line 99 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/405#-NHPH6vh9ySxwK4DrUKH:-NHPH6vh9ySxwK4DrUKI:bz1wwpr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f8f644db472688eb9651b31069667fa203e3e0/ui/src/locales/fi-FI/common.json#L99)):*
> ```JSON
>     "chooseTimingPlace": "Ei Hastus-paikkaa valittuna",
>     "noTimingPlace": "Ei Hastus-paikkaa",
>     "createTimingPlace": "Luo uusi",
> ```

This _could_ be generic "createNew", but I think we don't currently have a consistent style for these translations anyway, so this isn't wrong like this either.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/405)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/forms/stop/CreateTimingPlaceForm.tsx` line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/405#-NHPISDH8Ly2FQPFgv6m:-NHPISDH8Ly2FQPFgv6n:b5pq9h4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f8f644db472688eb9651b31069667fa203e3e0/ui/src/components/forms/stop/CreateTimingPlaceForm.tsx#L49)):*
> ```XML
>   const { t } = useTranslation();
>   const formRef = useRef<ExplicitAny>(null);
>   const { setIsLoading } = useLoader(Operation.SaveTimingPoint);
> ```

This should be `TimingPlace`.
___
*[`ui/src/redux/slices/loader.ts` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/405#-NHPIaksDU8BEukMNz0D:-NHPIaksDU8BEukMNz0E:b5pq9h4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f8f644db472688eb9651b31069667fa203e3e0/ui/src/redux/slices/loader.ts#L11)):*
> ```XML
>   MatchRoute = 'matchRoute',
>   CheckBrokenRoutes = 'checkBrokenRoutes',
>   SaveTimingPoint = 'saveTimingPoint',
> ```

This should be `TimingPlace`.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/405)* status: 9 of 16 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/forms/stop/CreateTimingPlaceForm.tsx` line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/405#-NHPISDH8Ly2FQPFgv6m:-NHUM7y24jlSQDckxleO:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f8f644db472688eb9651b31069667fa203e3e0/ui/src/components/forms/stop/CreateTimingPlaceForm.tsx#L49)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This should be `TimingPlace`.
</blockquote></details>

Done.
___
*[`ui/src/redux/slices/loader.ts` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/405#-NHPIaksDU8BEukMNz0D:-NHUM9nr9SIgJUmNzoaH:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f8f644db472688eb9651b31069667fa203e3e0/ui/src/redux/slices/loader.ts#L11)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This should be `TimingPlace`.
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/405)* status: all files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`ui/src/components/forms/stop/TimingPlaceSelector.tsx` line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/405#-NHUQvyw9KPltC5-zNX9:-NHUQvyw9KPltC5-zNXA:b-jycosh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/656020e77deb14fb31d96363ce4e611b9ff23d95/ui/src/components/forms/stop/TimingPlaceSelector.tsx#L14)):*
> ```XML
> };
> 
> export const TimingPlaceSelector = (): JSX.Element => {
> ```

I first thought that this was the ChooseTimingPlaceDropdown and was about to comment that should this be actually named `ChooseTimingPlaceDropdown`, like the other similarly working components (when reviewable was doing its hiding magic).

But now I realised that this contains both actions: choosing and creating timing place, I think this should be named "TimingPlaceActions", etc., because `Selector` indicates to a single component, but we are having two different functionalities here: Choosing the timing place and creating new timing place.

**Review by HenrikHartiala — APPROVED** [review]
Great work!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/405#-:-NHYQynx2fq2ZB0gcTpj:b-9dwnzc)* status: all files reviewed, 1 unresolved discussion (waiting on @eleksi)

**Pull request merged**
