### PR TITLE
Add tests for Hastus export error cases

### PR DESCRIPTION
**Pull request by sr-vala**
Add test that tries to export a route whose first and last stops are not timing points

Resolves HSLdevcom/jore4#1341

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)

### CODE REVIEW

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @jarkkoka)

___
*[`cypress/e2e/hastusExport.cy.ts` line 176 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTqj7wA3YfOH7q_Rt8:-NbXrWtc9LNCdtY96xnM:b-9ypxh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L176)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

By looking at this code file, these three variables seem uninitialised. Does the code work if these are dropped?
</blockquote></details>

All of the code in this file is in the same scope, I think. So these are initialized in the beginning of the file.
___
*[`cypress/e2e/hastusExport.cy.ts` line 267 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTnu5l-YcO4MA-N4r6:-NbXrMssBe3jd9bTFLTb:bpqw6zo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L267)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Why `2` in the variable name? Confuses me since I don't see where is the `1`in this specific test or context. I'd rather drop those numbers if there were actually no naming clashes.
</blockquote></details>

Added '1' to the first stopsInJourneyPattern.
___
*[`cypress/e2e/hastusExport.cy.ts` line 295 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTpZ0t5az7e9W5_XqY:-NbXrie197W00WOZ6wme:b-jn6hmb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L295)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

By looking at this code file, these three variables seem uninitialised. Does the code work if these are dropped?
</blockquote></details>

These are initialized in the beginning of the file.
___
*[`cypress/e2e/hastusExport.cy.ts` line 383 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTpi2aAocfUsAv4b7Q:-NbXrnkD5ZoSFRZhbyMC:b-jn6hmb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L383)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

By looking at this code file, these three variables seem uninitialised. Does the code work if these are dropped?
</blockquote></details>

These are initialized in the beginning of the file.
___
*[`cypress/e2e/hastusExport.cy.ts` line 472 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTppGZ4QjRc0pIsrZj:-NbXroOIB5Oym69bsZMO:b-jn6hmb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L472)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

By looking at this code file, these three variables seem uninitialised. Does the code work if these are dropped?
</blockquote></details>

These are initialized in the beginning of the file.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/hastusExport.cy.ts` line 176 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTqj7wA3YfOH7q_Rt8:-NbmWPEX4YDXCAwtvYVp:bmrzbur) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L176)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

All of the code in this file is in the same scope, I think. So these are initialized in the beginning of the file.
</blockquote></details>

Ok, you're right. Sorry, I wasn't looking closely and missed it.
___
*[`cypress/e2e/hastusExport.cy.ts` line 267 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTnu5l-YcO4MA-N4r6:-NbmWnEP7WdqER4rEGbC:b-g4ggs0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L267)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Added '1' to the first stopsInJourneyPattern.
</blockquote></details>

Ok, but my point was actually if those number suffixes are needed at all, because I believe they don't appear (or don't need to appear) on the same function scopes. Well, it's a minor issue in terms of readability, though.
___
*[`cypress/e2e/hastusExport.cy.ts` line 142 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbmc0uLD_kbkLNGoxOx:-Nbmc0uLD_kbkLNGoxOy:biplet8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3272824225b92112524a9769fb20aea5de51ba2c/cypress/e2e/hastusExport.cy.ts#L142)):*
> ```XML
> ];
> 
> const stopsInJourneyPattern1: StopInJourneyPatternInsertInput[] = [
> ```

I think `stopsInJourneyPattern1` array should be moved into "Success cases" context because it is is used/referenced only there.
___
*[`cypress/e2e/hastusExport.cy.ts` line 156 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbma1J50xEhm8tXoiws:-Nbma1J50xEhm8tXoiwt:bwrzs5e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3272824225b92112524a9769fb20aea5de51ba2c/cypress/e2e/hastusExport.cy.ts#L156)):*
> ```XML
>   }),
>   buildStopInJourneyPattern({
>     journeyPatternId: journeyPatterns[0].journey_pattern_id,
> ```

This array creation code appears 4 times in this file, and the only difference between the occurrences is the boolean value assigned for the `isUsedAsTimingPoint`property for first and the last stop point (in journey pattern). To make the code more concise, I would decompose the creation of this array into a common function that takes two parameters: the first and the last `isUsedAsTimingPoint`.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[`cypress/e2e/hastusExport.cy.ts` line 176 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTqj7wA3YfOH7q_Rt8:-NbnM3cB7XTwM9hByq7z:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L176)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, you're right. Sorry, I wasn't looking closely and missed it.
</blockquote></details>

Done.
___
*[`cypress/e2e/hastusExport.cy.ts` line 267 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbTnu5l-YcO4MA-N4r6:-NbnMVkfB0mqTTLcBGdl:bw0bkba) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/344d65a484a5527164dc4c3c613b6d6e5d83f4a9/cypress/e2e/hastusExport.cy.ts#L267)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, but my point was actually if those number suffixes are needed at all, because I believe they don't appear (or don't need to appear) on the same function scopes. Well, it's a minor issue in terms of readability, though.
</blockquote></details>

The numbers can be removed now that there is no stopsInJourneyPattern at the top scope.
___
*[`cypress/e2e/hastusExport.cy.ts` line 142 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbmc0uLD_kbkLNGoxOx:-NbnMf6M69WhPxahwscG:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3272824225b92112524a9769fb20aea5de51ba2c/cypress/e2e/hastusExport.cy.ts#L142)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think `stopsInJourneyPattern1` array should be moved into "Success cases" context because it is is used/referenced only there.
</blockquote></details>

Done.
___
*[`cypress/e2e/hastusExport.cy.ts` line 156 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbma1J50xEhm8tXoiws:-NbnbxB4A4QcbUFQ4zMt:b-h3dwf5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3272824225b92112524a9769fb20aea5de51ba2c/cypress/e2e/hastusExport.cy.ts#L156)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This array creation code appears 4 times in this file, and the only difference between the occurrences is the boolean value assigned for the `isUsedAsTimingPoint`property for first and the last stop point (in journey pattern). To make the code more concise, I would decompose the creation of this array into a common function that takes two parameters: the first and the last `isUsedAsTimingPoint`.
</blockquote></details>

Not sure if I did exactly what you described, but tried to do something.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: all files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/hastusExport.cy.ts` line 156 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbma1J50xEhm8tXoiws:-Nbnf63k2ZPA001QBfc4:boe017b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3272824225b92112524a9769fb20aea5de51ba2c/cypress/e2e/hastusExport.cy.ts#L156)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Not sure if I did exactly what you described, but tried to do something.
</blockquote></details>

Yes, you did! Thanks! :+1: 
___
*[`cypress/e2e/hastusExport.cy.ts` line 195 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbngF0I6NcWNz1ZS4VQ:-NbngF0I6NcWNz1ZS4VR:b-t52iyo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L195)):*
> ```XML
>         const infraLinkIds = extractInfrastructureLinkIdsFromResponse(res);
>         const stops = buildStopsOnInfrastrucureLinks(infraLinkIds);
>         const infraLinksAlongRoute = buildInfraLinksAlongRoute(infraLinkIds);
> ```

This function body is repeated 4 times. IMO you should also decompose this into a common function to reduce code duplication.

The decomposed function could take `baseDbResources` as a parameter.
___
*[`cypress/e2e/hastusExport.cy.ts` line 207 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnh4lp5fF5q9neQgtg:-Nbnh4lp5fF5q9neQgth:b98oa33) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L207)):*
> ```XML
>     beforeEach(() => {
>       removeFromDbHelper(dbResources);
>       insertToDbHelper(dbResources);
> ```

This function body is repeated 4 times. IMO you should also decompose this into a common function to reduce code duplication.

The decomposed function could take `dbResources` as a parameter.
___
*[`cypress/e2e/hastusExport.cy.ts` line 394 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnhsf5DhlFsukQgXjA:-Nbnhsf5DhlFsukQgXjB:b-n7uyrh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L394)):*
> ```XML
>         // Skip searching via UI
>         cy.visit('/routes/search?label=99&priorities=10&displayedType=routes');
>         routesAndLinesPage.exportToolBar.getToggleSelectingButton().click();
> ```

This function body is repeated 3 times in this file. IMO you should also decompose this into a common function to reduce code duplication.

The decomposed function could take `routesAndLinesPage` as a parameter.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`cypress/e2e/hastusExport.cy.ts` line 195 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbngF0I6NcWNz1ZS4VQ:-NbrhRMkC5zpynDijZ5u:b3cbspi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L195)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This function body is repeated 4 times. IMO you should also decompose this into a common function to reduce code duplication.

The decomposed function could take `baseDbResources` as a parameter.
</blockquote></details>

I did not find a way to move this to a common function. cy.task cannot be called outside a running test. Tried to extract the contents of the .tnen to a function, but could not find a working solution.
___
*[`cypress/e2e/hastusExport.cy.ts` line 207 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnh4lp5fF5q9neQgtg:-NbsUxSJ1PlQxhfkP_V8:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L207)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This function body is repeated 4 times. IMO you should also decompose this into a common function to reduce code duplication.

The decomposed function could take `dbResources` as a parameter.
</blockquote></details>

Done.
___
*[`cypress/e2e/hastusExport.cy.ts` line 394 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnhsf5DhlFsukQgXjA:-NbsV2h318PXCRcnKtqY:bu0pn9n) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L394)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This function body is repeated 3 times in this file. IMO you should also decompose this into a common function to reduce code duplication.

The decomposed function could take `routesAndLinesPage` as a parameter.
</blockquote></details>

This was a bit unclear to me. Do you mean the cy.visit function?

**Review by jarkkoka — CHANGES_REQUESTED** [review]
2/3 done from the previous round. I left one solution for the remaining problem, wihch you can still try. if that doesn't work, this will complete.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-:-Nbslkfc1H__B662Ho-K:b-1au1ok)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/hastusExport.cy.ts` line 195 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbngF0I6NcWNz1ZS4VQ:-NbsbmmQAh0ltmnt66l_:b-aafys9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L195)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I did not find a way to move this to a common function. cy.task cannot be called outside a running test. Tried to extract the contents of the .tnen to a function, but could not find a working solution.
</blockquote></details>

I see. Maybe the problem is that the function moved to common scope should also return a function like in an example below.

```javascript
const runTestExpectingFailure = (parameter: ParameterType) => {
  return () => {
      // Skip searching via UI
      cy.visit('/routes/search?label=99&priorities=10&displayedType=routes');
      routesAndLinesPage.exportToolBar.getToggleSelectingButton().click();
      //...
  };
};
```
___
*[`cypress/e2e/hastusExport.cy.ts` line 394 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnhsf5DhlFsukQgXjA:-Nbsc3jcDRhqbkjm5AeI:b49nlzv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L394)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This was a bit unclear to me. Do you mean the cy.visit function?
</blockquote></details>

No, I mean't like this.

```javascript
  it(
    'Should show an error when trying to export a route whose first stop is not a timing point',
    { tags: [Tag.Routes, Tag.HastusExport] },
    callCommonFunctionReturningAFunction());
```

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`cypress/e2e/hastusExport.cy.ts` line 195 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-NbngF0I6NcWNz1ZS4VQ:-Nbx2kVhEwRCcwhXIDjK:b-bteh79) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L195)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I see. Maybe the problem is that the function moved to common scope should also return a function like in an example below.

```javascript
const runTestExpectingFailure = (parameter: ParameterType) => {
  return () => {
      // Skip searching via UI
      cy.visit('/routes/search?label=99&priorities=10&displayedType=routes');
      routesAndLinesPage.exportToolBar.getToggleSelectingButton().click();
      //...
  };
};
```
</blockquote></details>

Found a working solution to this. Does not look very pretty, though.
___
*[`cypress/e2e/hastusExport.cy.ts` line 394 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnhsf5DhlFsukQgXjA:-Nbx2t_d7ZbPoE6n6ik5:bohmmkg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L394)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

No, I mean't like this.

```javascript
  it(
    'Should show an error when trying to export a route whose first stop is not a timing point',
    { tags: [Tag.Routes, Tag.HastusExport] },
    callCommonFunctionReturningAFunction());
```
</blockquote></details>

Do you mean extracting the whole test body to a function?

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/hastusExport.cy.ts` line 394 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnhsf5DhlFsukQgXjA:-NbxAXu63seFyH8y-hgS:ba4zj8n) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L394)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Do you mean extracting the whole test body to a function?
</blockquote></details>

Actually I meant extracting the whole function and returning that extracted function from a new common function (a function that returns a function). Or something similar, because you need to pass a function to the 3rd parameter of `it` anyway.
___
*[`cypress/e2e/hastusExport.cy.ts` line 218 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbx94xs6JESG2ty5vTF:-Nbx94xs6JESG2ty5vTG:brjny2e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5273d5253807f3494c6846cce98245a2eabf3abb/cypress/e2e/hastusExport.cy.ts#L218)):*
> ```XML
>       ...baseDbResources(stopsInJourneyPattern),
>       timingPlaces,
>       stops,
> ```

Hmmm...It indeed does not look elegant that you have now added `dbResources` in test global scope.

Can we use the return value of the `cy.task(...)` function? If that's possible, then I guess the global variables are not needed.

What about this kind of solution below?

```javascript
  const buildTestResources = (
    stopsInJourneyPattern: StopInJourneyPatternInsertInput[],
  ): SupportedResources => {
    return cy.task<GetInfrastructureLinksByExternalIdsResult>(

    //...

    ).then((res) => {

      //...

      return {
        ...baseDbResources(stopsInJourneyPattern),
        timingPlaces,
        stops,
        infraLinksAlongRoute,
      };
    };
  });
```
___
*[`cypress/e2e/hastusExport.cy.ts` line 362 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbx8maY0FkD7rhE3qa8:-Nbx8maY0FkD7rhE3qa9:b-oh1iwn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5273d5253807f3494c6846cce98245a2eabf3abb/cypress/e2e/hastusExport.cy.ts#L362)):*
> ```XML
> 
>     before(() => {
>       buildTestResources(stopsInJourneyPattern);
> ```

I liked more the previous version where `dbResources` was not in global scope.

What I would like to see here is something like this (using modified `buildTestResources` from above suggestion):

```javascript
let dbResources: SupportedResources;

before(() => {
  dbResources = buildTestResources(stopsInJourneyPattern);
});
```

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/hastusExport.cy.ts` line 218 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbx94xs6JESG2ty5vTF:-NbxDyz41UqxJU_GcS4K:bryv80c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5273d5253807f3494c6846cce98245a2eabf3abb/cypress/e2e/hastusExport.cy.ts#L218)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Hmmm...It indeed does not look elegant that you have now added `dbResources` in test global scope.

Can we use the return value of the `cy.task(...)` function? If that's possible, then I guess the global variables are not needed.

What about this kind of solution below?

```javascript
  const buildTestResources = (
    stopsInJourneyPattern: StopInJourneyPatternInsertInput[],
  ): SupportedResources => {
    return cy.task<GetInfrastructureLinksByExternalIdsResult>(

    //...

    ).then((res) => {

      //...

      return {
        ...baseDbResources(stopsInJourneyPattern),
        timingPlaces,
        stops,
        infraLinksAlongRoute,
      };
    };
  });
```
</blockquote></details>

Note the added `return` keyword before `cy.task(...)`

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[`cypress/e2e/hastusExport.cy.ts` line 394 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbnhsf5DhlFsukQgXjA:-NbxoFrACnEltu7tA19z:b-wxkiqn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/82f8b8938c365dc6ce734bce6336ded40722f01e/cypress/e2e/hastusExport.cy.ts#L394)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Actually I meant extracting the whole function and returning that extracted function from a new common function (a function that returns a function). Or something similar, because you need to pass a function to the 3rd parameter of `it` anyway.
</blockquote></details>

For me that would be too much abstraction at the cost of test readability. I like to see what a test does by looking at it directly, and not having to search for extracted parts of the test.
___
*[`cypress/e2e/hastusExport.cy.ts` line 218 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbx94xs6JESG2ty5vTF:-Nbxi_zjBVmMQ0S1CKas:b-eb9kvp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5273d5253807f3494c6846cce98245a2eabf3abb/cypress/e2e/hastusExport.cy.ts#L218)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Note the added `return` keyword before `cy.task(...)`
</blockquote></details>

"Type 'Chainable<{ timingPlaces: TimingPatternTimingPlaceInsertInput\[\]; stops: StopInsertInput\[\]; infraLinksAlongRoute: InfraLinkAlongRouteInsertInput\[\]; lines?: LineInsertInput\[\] | undefined; routes?: RouteInsertInput\[\] | undefined; journeyPatterns?: JourneyPatternInsertInput\[\] | undefined; stopsInJourneyPattern?: StopInJ...' has no properties in common with type 'SupportedResources'.ts(2559)"

Also I think this does not work in Cypress at all: "You cannot assign or work with the return values of any Cypress command. Commands are enqueued and run asynchronously." https://docs.cypress.io/guides/core-concepts/variables-and-aliases
___
*[`cypress/e2e/hastusExport.cy.ts` line 362 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbx8maY0FkD7rhE3qa8:-NbxuA4HDwzozAvkg0ar:b8plae0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5273d5253807f3494c6846cce98245a2eabf3abb/cypress/e2e/hastusExport.cy.ts#L362)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I liked more the previous version where `dbResources` was not in global scope.

What I would like to see here is something like this (using modified `buildTestResources` from above suggestion):

```javascript
let dbResources: SupportedResources;

before(() => {
  dbResources = buildTestResources(stopsInJourneyPattern);
});
```
</blockquote></details>

Is dbResources in global scope already when it is declared? dbResources can be assigned in the before block in the current implementation, but I'm getting a bit confused what the right way would be here.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/hastusExport.cy.ts` line 218 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbx94xs6JESG2ty5vTF:-NbyIPwOBkSyVcOzbFke:b-sl5t7c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5273d5253807f3494c6846cce98245a2eabf3abb/cypress/e2e/hastusExport.cy.ts#L218)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

"Type 'Chainable<{ timingPlaces: TimingPatternTimingPlaceInsertInput\[\]; stops: StopInsertInput\[\]; infraLinksAlongRoute: InfraLinkAlongRouteInsertInput\[\]; lines?: LineInsertInput\[\] | undefined; routes?: RouteInsertInput\[\] | undefined; journeyPatterns?: JourneyPatternInsertInput\[\] | undefined; stopsInJourneyPattern?: StopInJ...' has no properties in common with type 'SupportedResources'.ts(2559)"

Also I think this does not work in Cypress at all: "You cannot assign or work with the return values of any Cypress command. Commands are enqueued and run asynchronously." https://docs.cypress.io/guides/core-concepts/variables-and-aliases
</blockquote></details>

I refactored Cypress call out from this function and moved it to another place.
___
*[`cypress/e2e/hastusExport.cy.ts` line 362 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-Nbx8maY0FkD7rhE3qa8:-NbyIpHn4ShXhBnxbPWj:bagf9pp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5273d5253807f3494c6846cce98245a2eabf3abb/cypress/e2e/hastusExport.cy.ts#L362)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Is dbResources in global scope already when it is declared? dbResources can be assigned in the before block in the current implementation, but I'm getting a bit confused what the right way would be here.
</blockquote></details>

Made a new commit on top of the existing one.

**Review by jarkkoka — COMMENTED** [review]
From my part, this is now complete.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-:-NbyTuMg-fjsP3YaMwbY:bdcybm5)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sr-vala)

**Review by jarkkoka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @sr-vala)

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/642#-:-Nc18OxF1zTSJLULAxXy:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jarkkoka)

**Pull request merged**
