### PR TITLE
Refactor ModalMap

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
This is definitely going to the right direction! :+1: 
Put all comments as blocking, but as this is WIP I guess it doesn't mean anything yet...

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-:-N1mayCyBF4q4jm6iIUn:bjyqa98)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`src/components/map/ModalMap.tsx` line 102 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mMfMKE6JVUTWSKTxv:-N1mMfMKE6JVUTWSKTxw:bpp9kbw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L102)):*
> ```XML
> 
>     if (!infraLinks || !stopIdsWithinRoute || stopIdsWithinRoute.length < 2) {
>       throw new Error();
> ```

We need error message at some point :)
___
*[`src/components/map/ModalMap.tsx` line 106 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mZn4Q3zRXQ-GicsxV:-N1mZn4Q3zRXQ-GicsxW:bxhqkn9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L106)):*
> ```XML
> 
>     const variables = mapRouteDetailsToUpdateMutationVariables(
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
> ```

Why we previously didn't need this check but now we do? Should also this be in the previous check?
___
*[`src/components/map/ModalMap.tsx` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1m_70pBB8drUzHDG_3:-N1m_70pBB8drUzHDG_4:b-kuqjhx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L138)):*
> ```XML
>     if (changes.conflicts?.length) {
>       setConflicts(changes.conflicts);
>       return undefined;
> ```

`return;` is same as `return undefined;`
___
*[`src/components/map/ModalMap.tsx` line 148 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1m_FR4-PV3mvMohQco:-N1m_FR4-PV3mvMohQcp:b-n0mspa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L148)):*
> ```XML
>   };
> 
>   const onSuccessfulRouteCreate = (
> ```

onRouteCreated :wink: 
___
*[`src/components/map/ModalMap.tsx` line 174 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1m__ZcAxVXoq-jmHVE:-N1m__ZcAxVXoq-jmHVF:b1kaf82) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L174)):*
> ```XML
>   };
> 
>   useEffect(() => {
> ```

It makes more sense to have hooks before local function definitions, so I would keep this where this originally was.
Also this should be moved out of here at some point, or at least extracted to own file.

(Haven't done that yet as this needs a bit manual testing, or rather e2e test but thats requires a bit more work...)
___
*[`src/components/map/ModalMap.tsx` line 213 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1maCps5tFrrXiPnFMd:-N1maCps5tFrrXiPnFMe:b568p2q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L213)):*
> ```XML
>         showSuccessToast(t('routes.saveSuccess'));
> 
>         if (createdRoute) {
> ```

If we need this if statement, then showSuccesToast should probably also be there.

But not sure if we need this, as editRoute doesn't have similar condition. We have bug or inconsistency in either one of these.

(Since these are inside try catch block, maybe this could be written somehow like this:
```
try { 
if editedRouteId
await editRoute()
else
await createRoute()
}
showSuccessToast()
catch {
defaultErrorHandler()
}
```
)

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`src/components/map/ModalMap.tsx` line 163 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mec_d6FtPlAg0Be-v:-N1mec_d6FtPlAg0Be-w:bmmyorc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/components/map/ModalMap.tsx#L163)):*
> ```XML
> 
>     // If created route is not valid at the selected observation date,
>     // change observation data to created route's validity start date
> ```

typo? data -> date.

Good documentation, but could maybe also mention _why_ we do this. (In order to show freshly created route to the user, I assume)
___
*[`src/components/map/ModalMap.tsx` line 175 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mesJH1VxZcticUS8F:-N1mesJH1VxZcticUS8G:bbnqk7g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/components/map/ModalMap.tsx#L175)):*
> ```XML
>     }
> 
>     // Reset map editor drap mode and remove draft route
> ```

"...remove draft route as it is now saved"?
___
*[`src/redux/slices/mapEditor.ts` line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mf66s4rxKYXyvYt5N:-N1mf66s4rxKYXyvYt5O:b1bchre) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/redux/slices/mapEditor.ts#L21)):*
> ```XML
>   displayedRouteIds?: UUID[];
>   /**
>    * New route creation is in progress
> ```

"Is new route creation in progress" ?
___
*[`src/redux/slices/mapEditor.ts` line 25 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mfBeH1TVcd9U38iNk:-N1mfBeH1TVcd9U38iNl:bcaq8bz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/redux/slices/mapEditor.ts#L25)):*
> ```XML
>   creatingNewRoute: boolean;
>   /**
>    * Map editor's draw mode (Draw, Edit, undefined)
> ```

Not sure if we want to repeat enum values (Draw, Edit) here as they might be changed at some point and then this comment will be outdated

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @tk-vincit)

___
*[`src/components/map/ModalMap.tsx` line 102 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mMfMKE6JVUTWSKTxv:-N1mfB99DaYz08PEFiSe:bn8klpk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L102)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We need error message at some point :)
</blockquote></details>

It is there in the latest version. :)
___
*[`src/components/map/ModalMap.tsx` line 106 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mZn4Q3zRXQ-GicsxV:-N1mdTm61ycBCm14obuP:bdann7o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L106)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why we previously didn't need this check but now we do? Should also this be in the previous check?
</blockquote></details>

Now that we don't have if condition `if(editedRouteId)` in this function, ts doesnt know it is not null. But it never is null as it has been checked before this function call.
___
*[`src/components/map/ModalMap.tsx` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1m_70pBB8drUzHDG_3:-N1mdfbP-K1eJMTWzNkT:b-o6yovp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L138)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`return;` is same as `return undefined;`
</blockquote></details>

For some reason eslint is not happy with return;

`Async arrow function expected no return value.`

https://stackoverflow.com/questions/65460465/async-arrow-function-expected-no-return-value
___
*[`src/components/map/ModalMap.tsx` line 148 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1m_FR4-PV3mvMohQco:-N1mdmYG-N1v2bkv7NSx:b-c9tiyz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L148)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

onRouteCreated :wink: 
</blockquote></details>

Sounds simpler :D Changed
___
*[`src/components/map/ModalMap.tsx` line 174 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1m__ZcAxVXoq-jmHVE:-N1me26n0qbJ01V6EV2N:b-ly97zz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L174)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

It makes more sense to have hooks before local function definitions, so I would keep this where this originally was.
Also this should be moved out of here at some point, or at least extracted to own file.

(Haven't done that yet as this needs a bit manual testing, or rather e2e test but thats requires a bit more work...)
</blockquote></details>

Good point, moved the functions after useEffect.
___
*[`src/components/map/ModalMap.tsx` line 213 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1maCps5tFrrXiPnFMd:-N1meHKaCkvKavLld7RV:byob38s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L213)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If we need this if statement, then showSuccesToast should probably also be there.

But not sure if we need this, as editRoute doesn't have similar condition. We have bug or inconsistency in either one of these.

(Since these are inside try catch block, maybe this could be written somehow like this:
```
try { 
if editedRouteId
await editRoute()
else
await createRoute()
}
showSuccessToast()
catch {
defaultErrorHandler()
}
```
)
</blockquote></details>

When creating a new route, we need to update map editor state to show that new route as well, also update observation date if new route validity is outside observation date. When editing a route, the route is already displayed in map editor, there is no need to change any state after editing. So the functionality really is different when creating and editing a route.

SuccessToast is like this, because onRouteCreated will also show a toast, which should be displayed after initial "save successful" toast.
___
*[`src/components/map/ModalMap.tsx` line 163 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mec_d6FtPlAg0Be-v:-N1mg5mqDv05R9yUtUjc:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/components/map/ModalMap.tsx#L163)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

typo? data -> date.

Good documentation, but could maybe also mention _why_ we do this. (In order to show freshly created route to the user, I assume)
</blockquote></details>

Done.
___
*[`src/components/map/ModalMap.tsx` line 175 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mesJH1VxZcticUS8F:-N1mgCs_7KYZY2_yzU9w:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/components/map/ModalMap.tsx#L175)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"...remove draft route as it is now saved"?
</blockquote></details>

Done.
___
*[`src/redux/slices/mapEditor.ts` line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mf66s4rxKYXyvYt5N:-N1mgE7h2AhbPhX7REIG:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/redux/slices/mapEditor.ts#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"Is new route creation in progress" ?
</blockquote></details>

Done.
___
*[`src/redux/slices/mapEditor.ts` line 25 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mfBeH1TVcd9U38iNk:-N1mgM0D5eKnzfKpzDFP:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b027ac6a4ce9fdcd103f33e0b5f73b83b58c2cfc/src/redux/slices/mapEditor.ts#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if we want to repeat enum values (Draw, Edit) here as they might be changed at some point and then this comment will be outdated
</blockquote></details>

Done.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`src/components/map/ModalMap.tsx` line 102 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mMfMKE6JVUTWSKTxv:-N1mhleqDupiZvoQtx2R:b-g5yh1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L102)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

It is there in the latest version. :)
</blockquote></details>

Reviewable :disappointed: :roll_eyes:

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @eleksi and @tk-vincit)

___
*[`src/components/map/ModalMap.tsx` line 106 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mZn4Q3zRXQ-GicsxV:-N1mkFsIAIf80I1iTtkE:b-wu0i1y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L106)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Now that we don't have if condition `if(editedRouteId)` in this function, ts doesnt know it is not null. But it never is null as it has been checked before this function call.
</blockquote></details>

Damn, it would be nice if TS compiler would notice that... Because now it would be nice to do check also here or then comment within eslint disable _why_ this is safe to do.

One trick could be passing this as (non-optional) parameter to this function so that TS compiler would be make sure that it exists. Thats maybe not the most elegant solution ever, but neither is this, and it would improve type safety so maybe I could go with it unless you find it confusing?
___
*[`src/components/map/ModalMap.tsx` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1m_70pBB8drUzHDG_3:-N1mjjYO8QSUMupZ3JkK:b-7w0eyk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L138)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

For some reason eslint is not happy with return;

`Async arrow function expected no return value.`

https://stackoverflow.com/questions/65460465/async-arrow-function-expected-no-return-value
</blockquote></details>

Thats interesting... But well, this doesn't decrease readability much so maybe its not worth it to investigate this further then.
___
*[`src/components/map/ModalMap.tsx` line 213 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1maCps5tFrrXiPnFMd:-N1mlaxLDLp74dlq55vo:bbl31ei) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L213)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

When creating a new route, we need to update map editor state to show that new route as well, also update observation date if new route validity is outside observation date. When editing a route, the route is already displayed in map editor, there is no need to change any state after editing. So the functionality really is different when creating and editing a route.

SuccessToast is like this, because onRouteCreated will also show a toast, which should be displayed after initial "save successful" toast.
</blockquote></details>

Ok... This is a bit confusing, but well, this is still better than this was before so I'll accept this if we don't easily come up with a better solution.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[`src/components/map/ModalMap.tsx` line 106 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-N1mZn4Q3zRXQ-GicsxV:-N1n7liyApX3yBt6AJgy:bo1wmj2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c8c5c002a1cfae8d8f5f715ba946065a628e47c2/src/components/map/ModalMap.tsx#L106)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Damn, it would be nice if TS compiler would notice that... Because now it would be nice to do check also here or then comment within eslint disable _why_ this is safe to do.

One trick could be passing this as (non-optional) parameter to this function so that TS compiler would be make sure that it exists. Thats maybe not the most elegant solution ever, but neither is this, and it would improve type safety so maybe I could go with it unless you find it confusing?
</blockquote></details>

I made it function parameter, looks like a little better solution.

**Review by tk-vincit — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/173#-:-N1r7bS1-GhB9I_DDNTA:bg7igkv)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
