### PR TITLE
Add asserts to createLine test

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#1116

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/createLine.cy.ts` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5gt1D3M_UZ-tzqSp8:-NN5gt1D3M_UZ-tzqSp9:b-fq64fc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b7eb24f3067f21ddc848711c36ef8cdc5c1c8c83/cypress/e2e/createLine.cy.ts#L5)):*
> ```XML
> import { deleteLineByLabel } from './utils';
> 
> const testLabel = '7327';
> ```

let's do leave this variable here instead of copy-pasting the magical number '7327' everywhere
___
*[`cypress/e2e/createLine.cy.ts` line 44 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5haJc49dTprLDT_sg:-NN5haJc49dTprLDT_sh:bshd9on) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/76b061a80a4961a1b69eeb08ff0ecdcb9ac08698/cypress/e2e/createLine.cy.ts#L44)):*
> ```XML
>     changeValidityForm.setPriority(Priority.Standard);
>     changeValidityForm.setStartDate('2022-01-01');
>     changeValidityForm.setEndDate('2032-12-31');
> ```

this will again break in 10 years :) to avoid issues like this, just use DateTime.MAX :)
___
*[`cypress/e2e/createLine.cy.ts` line 49 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5iWuWCISBY8NWrnWv:-NN5iWuWCISBY8NWrnWw:b-gu0ucv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/76b061a80a4961a1b69eeb08ff0ecdcb9ac08698/cypress/e2e/createLine.cy.ts#L49)):*
> ```XML
>     lineForm.checkLineSubmitSuccess();
> 
>     cy.visit('/routes');
> ```

this doesn't belong here. This is a separate test that checks that if there's an existing line with number 7327 then the search finds it

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @sr-vala)

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`cypress/e2e/createLine.cy.ts` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5gt1D3M_UZ-tzqSp8:-NNBYl8m4o7xxFDJOWY4:bky9jna) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b7eb24f3067f21ddc848711c36ef8cdc5c1c8c83/cypress/e2e/createLine.cy.ts#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's do leave this variable here instead of copy-pasting the magical number '7327' everywhere
</blockquote></details>

The magical number is a test argument that is instantly readable when looking at the test. My job is to stare at these tests 37,5 hours a week, so I would leave it there.
___
*[`cypress/e2e/createLine.cy.ts` line 44 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5haJc49dTprLDT_sg:-NNBZCov23D6B71tCLoR:bg61zb2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/76b061a80a4961a1b69eeb08ff0ecdcb9ac08698/cypress/e2e/createLine.cy.ts#L44)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this will again break in 10 years :) to avoid issues like this, just use DateTime.MAX :)
</blockquote></details>

Hopefully at least the test framework is something different by then. I would rather use remotely realistic dates when the date is not indefinite. I set this to 2050 now.
___
*[`cypress/e2e/createLine.cy.ts` line 49 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5iWuWCISBY8NWrnWv:-NNBeZIjBKYr5-8iE1Pa:b-ysh2s3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/76b061a80a4961a1b69eeb08ff0ecdcb9ac08698/cypress/e2e/createLine.cy.ts#L49)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this doesn't belong here. This is a separate test that checks that if there's an existing line with number 7327 then the search finds it
</blockquote></details>

This asserts that the created line exists by using the search, like a real user would. Nothing else asserted that in the test before.

**Review by pallost — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/createLine.cy.ts` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5gt1D3M_UZ-tzqSp8:-NNFxiiW6LibQscOPKIy:bo8in) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b7eb24f3067f21ddc848711c36ef8cdc5c1c8c83/cypress/e2e/createLine.cy.ts#L5)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

The magical number is a test argument that is instantly readable when looking at the test. My job is to stare at these tests 37,5 hours a week, so I would leave it there.
</blockquote></details>

It's not only your job to stare at these tests 37.5 hours a week but also others have to work with it. Writing the actual number as plain text does not give additional value but makes the code much harder to maintain in the future. Keep your code clean!
Here's a link if you wanna learn more on magic numbers in code: https://letmegooglethat.com/?q=why+I+shouldn%27t+use+magic+numbers+in+code
___
*[`cypress/e2e/createLine.cy.ts` line 44 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5haJc49dTprLDT_sg:-NNFvosA-4mKEkGVoL0F:b32w0x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/76b061a80a4961a1b69eeb08ff0ecdcb9ac08698/cypress/e2e/createLine.cy.ts#L44)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Hopefully at least the test framework is something different by then. I would rather use remotely realistic dates when the date is not indefinite. I set this to 2050 now.
</blockquote></details>

OK
___
*[`cypress/e2e/createLine.cy.ts` line 49 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5iWuWCISBY8NWrnWv:-NNFvqYCEv4Sq2quWUAv:byyz1iv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/76b061a80a4961a1b69eeb08ff0ecdcb9ac08698/cypress/e2e/createLine.cy.ts#L49)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This asserts that the created line exists by using the search, like a real user would. Nothing else asserted that in the test before.
</blockquote></details>

As a Test Engineer, you're probably familiar with the concept "atomic tests". If not, you should probably ready about it:
https://letmegooglethat.com/?q=why+should+automated+tests+be+atomic

Also, you do already have tests that check searching, they are in `searchRoutesAndLines`. So it's pointless to test that again.

In the end of the createLine test, if you want to verify that the line was created and the UI sees it, you should either:
1. go to the line details view directly
2. or rather just check its existence in the database by doing a query

It _could_ make sense to test longer flows that verify the all the parts of the user interaction are intact. This test suite however is not the place for that, these long flows should be separated into their own test suites to enable parallel execution in the future.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pallost and @sr-vala)

___
*[`cypress/e2e/createLine.cy.ts` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5gt1D3M_UZ-tzqSp8:-NNFzheK0YV2XxsOp4je:b-obcb7t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b7eb24f3067f21ddc848711c36ef8cdc5c1c8c83/cypress/e2e/createLine.cy.ts#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

It's not only your job to stare at these tests 37.5 hours a week but also others have to work with it. Writing the actual number as plain text does not give additional value but makes the code much harder to maintain in the future. Keep your code clean!
Here's a link if you wanna learn more on magic numbers in code: https://letmegooglethat.com/?q=why+I+shouldn%27t+use+magic+numbers+in+code
</blockquote></details>

I'm with Samuli in this one. @pallost it is absolutely true that you shouldn't use magic numbers in *production* code, but tests are a different thing and I would say that they are not magic numbers, they are the input of the test. In tests most important thing is that they are easy to read and follow. Variables will make the readability of the *test* much lower.

We already went through this conversation once in a different PR with Tuomas and Samuli, but I will link this article again:
https://medium.com/@erik.sacre/on-tdd-literals-versus-constants-in-tests-8ac992c7873f

Also, I've been debugging these tests for quite some time now and I must say that it is VERY frustrating that you need to navigate and search for what happens where and what are the inputs. For example: Test error says that something failed when the input was: "This is some input" and then I open the test code and can't find that same input ANYWHERE because it is masked behind constants that are not in the test, maybe not even in the whole test file.

When tests are not failing, yes it is nice that the tests are easy to change and maintain, but that is not the point of the tests. When a test fails, the important thing is to see *what broke and why* as easy and fast as possible, and the maintainability of the test give no value in this and all the constants that are keeping the maintainability high, are actually fighting against the readability of the test by masking all the inputs and asserts.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`cypress/e2e/createLine.cy.ts` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5gt1D3M_UZ-tzqSp8:-NNG0AW21Kf7KDVkNQRv:b-7xtei2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b7eb24f3067f21ddc848711c36ef8cdc5c1c8c83/cypress/e2e/createLine.cy.ts#L5)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I'm with Samuli in this one. @pallost it is absolutely true that you shouldn't use magic numbers in *production* code, but tests are a different thing and I would say that they are not magic numbers, they are the input of the test. In tests most important thing is that they are easy to read and follow. Variables will make the readability of the *test* much lower.

We already went through this conversation once in a different PR with Tuomas and Samuli, but I will link this article again:
https://medium.com/@erik.sacre/on-tdd-literals-versus-constants-in-tests-8ac992c7873f

Also, I've been debugging these tests for quite some time now and I must say that it is VERY frustrating that you need to navigate and search for what happens where and what are the inputs. For example: Test error says that something failed when the input was: "This is some input" and then I open the test code and can't find that same input ANYWHERE because it is masked behind constants that are not in the test, maybe not even in the whole test file.

When tests are not failing, yes it is nice that the tests are easy to change and maintain, but that is not the point of the tests. When a test fails, the important thing is to see *what broke and why* as easy and fast as possible, and the maintainability of the test give no value in this and all the constants that are keeping the maintainability high, are actually fighting against the readability of the test by masking all the inputs and asserts.
</blockquote></details>

Yeah.
___
*[`cypress/e2e/createLine.cy.ts` line 49 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-NN5iWuWCISBY8NWrnWv:-NNbDEHQ4kZMrzbfVZVt:b-sey9yf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/76b061a80a4961a1b69eeb08ff0ecdcb9ac08698/cypress/e2e/createLine.cy.ts#L49)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

As a Test Engineer, you're probably familiar with the concept "atomic tests". If not, you should probably ready about it:
https://letmegooglethat.com/?q=why+should+automated+tests+be+atomic

Also, you do already have tests that check searching, they are in `searchRoutesAndLines`. So it's pointless to test that again.

In the end of the createLine test, if you want to verify that the line was created and the UI sees it, you should either:
1. go to the line details view directly
2. or rather just check its existence in the database by doing a query

It _could_ make sense to test longer flows that verify the all the parts of the user interaction are intact. This test suite however is not the place for that, these long flows should be separated into their own test suites to enable parallel execution in the future.
</blockquote></details>

I went with the database approach now, but I have to note that we do not have a test that creates a line and verifies that it is available to the user via the GUI. We are only covering the creation and search separately, which leaves blind spots in our "e2e" tests.

**Review by HenrikHartiala — APPROVED** [review]
Great! Looks good to me!

> Reviewed 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/471#-:-NNuINbn4i1p6uQ9NaqC:b-lx5pgs)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost)

**Pull request merged**
