### PR TITLE
Add support for special days to timetables import

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)

### CODE REVIEW

**Review by Perholehto — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 4 of 4 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)* status: all files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 25 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhBbhHEDp3d_us_aP06):*
typo
___
*[`package.json` line 29 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhBNxwR8DxpkIY4TJsA:-NhBNxwS51TgysC_UQOR:b4aey6u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/02792bb4584c56e84089e0d8933cc6e6674e05da/package.json#L29)):*
> ```JSON
>     "qa": "yarn --frozen-lockfile && yarn ws:db build && yarn ws:tdi  timetables-data-inserter:build && yarn ts:check && yarn prettier:check && yarn lint && yarn test && yarn test:integration && yarn test:e2e",
>     "qa:fast": "yarn qa --config-file cypress.config.fast.ts",
>     "qa:fix": "yarn lint --fix --cache && yarn prettier --loglevel warn --cache"
> ```

could `--cache` also be added to `qa:fast` command or `qa` ?
___
*[`ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx` line 34 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhBS86aCimbaHGiCH0L:-NhBS86aCimbaHGiCH0M:b-4v34zf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/02792bb4584c56e84089e0d8933cc6e6674e05da/ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx#L34)):*
> ```XML
>  * Component for selecting priority.
>  * Can be merged with other forms.
>  *
> ```

I'm not a fan of these jsdocs(?), at least that example usage is just noise here.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)* status: all files reviewed, 2 unresolved discussions (waiting on @Perholehto)

___
*[`package.json` line 29 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhBNxwR8DxpkIY4TJsA:-NhBd-4d3rEBLo2twaaL:bpf7u0w) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/02792bb4584c56e84089e0d8933cc6e6674e05da/package.json#L29)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

could `--cache` also be added to `qa:fast` command or `qa` ?
</blockquote></details>

The `qa` is used in CI so would leave caching out of it _just in case_. Or rename it to `qa:ci` or something but not worth the hassle IMO.

For `qa:fast`, I don't see the problem, but I don't think `"qa:fast": "yarn qa --cache --config-file cypress.config.fast.ts",` would work since it looks like the parameters are passed to `yarn test:e2e` command.

The e2e tests that are being ran are a lot slower than prettier + lint without caching anyways.

So won't change anything for now, I think.
___
*[`ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx` line 34 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhBS86aCimbaHGiCH0L:-NhBfEnM7UfisKk6o-CC:b48c2fo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/02792bb4584c56e84089e0d8933cc6e6674e05da/ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx#L34)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I'm not a fan of these jsdocs(?), at least that example usage is just noise here.
</blockquote></details>

:shrug:  was just moving existing code around.

Looks like these are not really widely used though. Just 2 occurrences in the code base (well, 3 after this refactor). I'll just remove them, :ok_hand:

**Review by Perholehto — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)* status: 21 of 25 files reviewed, 6 unresolved discussions (waiting on @Leitsi)

___
*[`package.json` line 29 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhBNxwR8DxpkIY4TJsA:-NhR4AViBVu2P59UrhiX:bn9n2ik) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/02792bb4584c56e84089e0d8933cc6e6674e05da/package.json#L29)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

The `qa` is used in CI so would leave caching out of it _just in case_. Or rename it to `qa:ci` or something but not worth the hassle IMO.

For `qa:fast`, I don't see the problem, but I don't think `"qa:fast": "yarn qa --cache --config-file cypress.config.fast.ts",` would work since it looks like the parameters are passed to `yarn test:e2e` command.

The e2e tests that are being ran are a lot slower than prettier + lint without caching anyways.

So won't change anything for now, I think.
</blockquote></details>

this is fine :)
___
*[`ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx` line 77 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR4Fx8-NsO2sEbpjNF:-NhR4Fx8-NsO2sEbpjNG:brqz6q5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx#L77)):*
> ```XML
> >(ConfirmPreviewedTimetablesImportFormComponent);
> 
> export type { FormState };
> ```

This is already exported in `TimetablesImportFormSchema` 
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx` line 86 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR5aH83MybOsnWuSaM:-NhR5aH83MybOsnWuSaN:brqz6q5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx#L86)):*
> ```XML
> };
> 
> export type { FormState };
> ```

This is already exported in `TimetablesImportFormSchema` 
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 53 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR5kn17ovTXUrbsPq7:-NhR5kn17ovTXUrbsPq8:b-s92061) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L53)):*
> ```XML
>       />
>       <ModalBody>
>         {formReadyForRender && (
> ```

This could use `<Visible>` component. Sorry that I gave you advice to use this in telco, but I didn't remember that we have that visible thingy.
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 113 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR69Zw9Nw_wl8Bz_tX:-NhR69Zw9Nw_wl8Bz_tY:bc1i08t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L113)):*
> ```XML
>           <Row className="items-center space-x-14">
>             <h3>{t('timetablesPreview.contentUsage')}</h3>
>             {formReadyForRender && (
> ```

This could use `<Visible>` 
___
*[`ui/src/components/timetables/import/TimetablesImportFormSchema.tsx` line 0 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR5HRaDEqxZrVffIFz:-NhR5HRaDEqxZrVffIG-:b-d6dr0t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/TimetablesImportFormSchema.tsx#L0)):*
Should be `.ts` instead of `.tsx`. Content is not React
___
*[`ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx` line 34 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhBS86aCimbaHGiCH0L:-NhR6FlV9_zTMoENtFax:b-87j11d) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/02792bb4584c56e84089e0d8933cc6e6674e05da/ui/src/components/timetables/import/TimetablesImportPriorityForm.tsx#L34)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

:shrug:  was just moving existing code around.

Looks like these are not really widely used though. Just 2 occurrences in the code base (well, 3 after this refactor). I'll just remove them, :ok_hand:
</blockquote></details>

Good!

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)* status: 21 of 25 files reviewed, 8 unresolved discussions (waiting on @Leitsi and @Perholehto)

___
*[`cypress/pageObjects/TimetablesImportPriorityForm.ts` line 32 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR9fCK9r211pW-Ygfh:-NhR9fCL8F4WPHagSJTe:b-6xjd24) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/cypress/pageObjects/TimetablesImportPriorityForm.ts#L32)):*
> ```XML
>   }
> 
>   setPriority = (priority: TimetablePriority) => {
> ```

Should this method have a case like setAsSpecial, or is it different from the rest of the cases? And should the setAsSpecial method exist in the first place?
___
*[`cypress/pageObjects/TimetablesImportPriorityForm.ts` line 72 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhRA60b7tCz1j6nRnpi:-NhRA60b7tCz1j6nRnpj:b-outzmc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/cypress/pageObjects/TimetablesImportPriorityForm.ts#L72)):*
> ```XML
>         break;
>       case TimetablePriority.Special:
>         cy.getByTestId(
> ```

There is a getter for this button, so that could be used here.

**Review by Perholehto — COMMENTED** [review]
> Reviewed 1 of 4 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)* status: all files reviewed, 6 unresolved discussions (waiting on @Leitsi)

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)* status: 23 of 25 files reviewed, 4 unresolved discussions (waiting on @Perholehto)

___
*[`cypress/pageObjects/TimetablesImportPriorityForm.ts` line 32 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR9fCK9r211pW-Ygfh:-NhRNAo5E3IhabldOsel:bky6nf7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/cypress/pageObjects/TimetablesImportPriorityForm.ts#L32)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Should this method have a case like setAsSpecial, or is it different from the rest of the cases? And should the setAsSpecial method exist in the first place?
</blockquote></details>

Works differently: the special priority input is always either set automatically and disabled, or hidden. So no need for `setPriority` method because it wouldn't work.
___
*[`cypress/pageObjects/TimetablesImportPriorityForm.ts` line 72 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhRA60b7tCz1j6nRnpi:-NhRO6PwBlZ5yTwd8klH:b-a2ujfl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/cypress/pageObjects/TimetablesImportPriorityForm.ts#L72)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

There is a getter for this button, so that could be used here.
</blockquote></details>

Changed.
___
*[`ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx` line 77 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR4Fx8-NsO2sEbpjNF:-NhRdfyEBXt22gaeHTfo:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx#L77)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This is already exported in `TimetablesImportFormSchema`
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx` line 86 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR5aH83MybOsnWuSaM:-NhRdhPB7bV-atrQ9BW2:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/ConfirmTimetablesImportForm.tsx#L86)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This is already exported in `TimetablesImportFormSchema`
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 53 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR5kn17ovTXUrbsPq7:-NhRf_INBAiptzYd1b6V:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L53)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This could use `<Visible>` component. Sorry that I gave you advice to use this in telco, but I didn't remember that we have that visible thingy.
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 113 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR69Zw9Nw_wl8Bz_tX:-NhRf_7H95wZPoiI6_yf:b3y2iem) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L113)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This could use `<Visible>`
</blockquote></details>

Done. Changed in separate commit to avoid rebase hassle.
___
*[`ui/src/components/timetables/import/TimetablesImportFormSchema.tsx` line  at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687#-NhR5HRaDEqxZrVffIFz:-NhRgq408gbbQIzdIC4m:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4f6e85b274879a3674ce893801c8d5086286de66/ui/src/components/timetables/import/TimetablesImportFormSchema.tsx#L)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Should be `.ts` instead of `.tsx`. Content is not React
</blockquote></details>

Done.

**Review by Perholehto — COMMENTED** [review]
> Reviewed 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/687)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

**Pull request merged**
