### PR TITLE
Add passing time and departure time tests

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#1329

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)

### CODE REVIEW

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)* status: all files reviewed, 8 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY37P0E5jiTRm7_EjTf):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

A minor description of the changes would be appreciated in the commit body.
</blockquote></details>

Done.
___
*[`README.md` line 80 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2mxTU2I8ZC-GyR1tY:-NYrSdet60nZ7hlx3mXQ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/README.md#L80)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Good addition!
Though I think this deserves it's own commit, since it is not particularly related to passing time and departure time tests.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 244 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2s-TWBji_B8IUAJ0e:-NYrSemc6BmeG1e17Blv:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/e2e/timetableImport.cy.ts#L244)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You are modifying an existing test here, which is not part of the arrival times and departure times tests. So it would again be nice to have these modiy's in their own commit.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 250 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2s1KyAkbViX0brvnU:-NYrF6Fb1G5_UcuR4YpQ:b-ykfmb1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/e2e/timetableImport.cy.ts#L250)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The name `assertStopHasDepartureTime` indicates that we just check that a stop has departure time existing,, so maybe use something like `assertStopDepartureTime` (new name suggestion below).

Also, now I kind of have no idea what these parameter values are and need to check the assertStopHasDepartureTime changes to understand these
I think a more clear way of doing this is to give the parameters as one object, so you can clearly see the parameters.

If I understood the `assertStopHasDepartureTime` function correctly, we check that a stop with label (`stopLabels[1]`) first departuretime (index `0`) is 7:13?
So maybe actually the name for the function could be `assertStopNthDepartureTime` and then the parameter would be an object of 
```
{
  stopLabel: string,
  nthDeparture: number, // Might need to also rethink this name, because it is not nth, it is index. 
  hour: number,
  minute: number, // 'minute' should be enough here
}
```
</blockquote></details>

Tried to change this to a clearer direction now. 'nth' is more convenient for naming, and does not imply starting from 0 or 1. At least I don't know how to work 'Index' into the function names.
___
*[`cypress/e2e/timetableImport.cy.ts` line 266 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2rhIV8WTiFMq8x01Q:-NYqTc_xDtH7yb9ZlwNK:bj99hmf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/e2e/timetableImport.cy.ts#L266)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Judging by the title here, I don't understand how this is this related to timetableImport? So should this actually be in its own test file, maybe `passingTimes.cy.ts` etc.?
Although you are importing a timetable here instead of inserting data straight in to database, so I could also misundertsand something, so what is the case here?
</blockquote></details>

Separated this to its own file. This does mean duplicating setup code again.
___
*[`cypress/e2e/timetableImport.cy.ts` line 288 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY31GDo-QlXe6nmLciN:-NYrSkTM5AL2I9_mybdW:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/e2e/timetableImport.cy.ts#L288)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Same comments applies to this as the `assertStopHasDepartureTime`
</blockquote></details>

Done.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY32T6xADsiC4DgTg6s:-NYrEWUZ3Gk4p6j4514M:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/pageObjects/PassingTimesByStopTable.ts#L15)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

These two functions (assertStopHasDepartureTime and assertStopHasArrivalTime) have only one line of code that differs from each other, so you could make these more generic with couple of helper functions.

And as said earlier, would be more readable to pass these parameters as an object
</blockquote></details>

Done.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 45 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY35Uhq6wXB2MhayL6D:-NYrSqP1-vlHNkPEJHi-:bx1hbpz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/pageObjects/PassingTimesByStopTable.ts#L45)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

`nthArrival`*, although like mentioned earlier, maybe we need to think of another name (or subtract 1 from the value to get index)
</blockquote></details>

'nth' is quite commonly used in test automation frameworks even with zero-based indexing.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, 1 of 1 files at r3, 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)* status: 3 of 11 files reviewed, 12 unresolved discussions (waiting on @sr-vala)

___
*[`README.md` line 80 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2mxTU2I8ZC-GyR1tY:-NYvhBW72ChmzQ_ODNqF:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/README.md#L80)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`cypress/e2e/timetableImport.cy.ts` line 266 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2rhIV8WTiFMq8x01Q:-NYveRtp-IDmNM1tNMXv:b-2l6240) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/e2e/timetableImport.cy.ts#L266)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Separated this to its own file. This does mean duplicating setup code again.
</blockquote></details>

Yes. It does mean duplicating setup code for now, but since it is not related to importing timetables, it does not belong in this file. Also optimally in the future we want to change the data seeding in this test so that the needed timetable data is seeded straight to database instead of using the import functionality in the UI.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY32T6xADsiC4DgTg6s:-NYvkcQN9mOsU6VUskR7:b-fgh2rx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/pageObjects/PassingTimesByStopTable.ts#L15)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Okay so now the two functions are combined completely and now there is one function doing two different things with a bit awkward "or" in the name and "isDepartureTime" flag. I think the original separate functions were quite nice, because they were clear in the test that what we were asserting. 
But since they had nearly the same contents (only one line was different) you could create helper functions to reduce the duplicate code. But there is also a new suggestion related to this, which I will continue in the new thread, where the code is now.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 45 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY35Uhq6wXB2MhayL6D:-NYvfWXfEhGmsrPPDXen:bkaxnxp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/pageObjects/PassingTimesByStopTable.ts#L45)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

'nth' is quite commonly used in test automation frameworks even with zero-based indexing.
</blockquote></details>

Thats okay, we can retain the nth, but could maybe add some JSDoc comments for the function and mention there that the nth starts from index 0.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 13 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwDvb2E2J3uuz5gnoI:-NYwDvb2E2J3uuz5gnoJ:b-l0b489) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L13)):*
> ```XML
> 
> export class PassingTimesByStopTable {
>   passingTimesByStopTableRowPassingMinute =
> ```

These two were a bit confusing at first, but then I realised that this PassingMinute should probably be within the PassingTime, right?

So if you move this PassingMinute inside the PassingTime, the structure should be fine. Kind of "Find the nth passing time, then find the minutes within this passing time".
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 55 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYvhjwHETr91WyaaLrY:-NYvhjwHETr91WyaaLrZ:b-h7c1sk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L55)):*
> ```XML
>   }
> 
>   assertStopNthDepartureOrArrivalTime(values: StopArrivalOrDepartureTime) {
> ```

This function (and the dependencies for this function) is already called in the refactoring commit, so it should be added there already to retain the integrity of the commit. 
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 57 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYw4DajAfZRUNHUfUiB:-NYw4Dak2fLAeyvP0XrW:b-w13fvj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L57)):*
> ```XML
>   assertStopNthDepartureOrArrivalTime(values: StopArrivalOrDepartureTime) {
>     this.assertStopNthHour(values);
>     this.assertStopNthDepartureOrArrivalMinute(values);
> ```

A couple of new thoughts risen here. Like said in earlier comment, first I was thinking that you could retain the "assertArrivalTime..." and "assertDepartureTime..." functions, and have the contents in helper functions to reduce the duplicate code. 

But, now I realised also that we could just have "assertNthPassingTime" and then assert all the passingTimes at once. So hour, departureTime and arrivalTime in the same function. What do you think?

So something like 
```
assertNthPassingTimeOnStop({
    stopLabel,
    nthPassingTime,
    hour,
    arrivalTime,
    departureTime,
  }: {
    stopLabel: string;
    nthPassingTime: number;
    hour: number;
    arrivalTime?: string;
    departureTime: string;
  }) {
    this.getTableRow(stopLabel).within(() => {
      this.passingTimesByStopTableRowPassingTime
        .getTimeContainer()
        .eq(nthPassingTime)
        .within(() => {
          this.passingTimesByStopTableRowPassingTime
            .getHour()
            .should('contain', hour);
          this.passingTimesByStopTableRowPassingMinute
            .getDepartureTime()
            .should('contain', departureTime);
          if (arrivalTime) {
            this.passingTimesByStopTableRowPassingMinute
              .getArrivalTime()
              .should('contain', arrivalTime);
          }
        });
    });
  }
```
This is just a rough example and can (and should) be modified. For example we should still move the passingMinute inside passingTime (as said in an earlier comment) and I think that will also make this function simpler.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 60 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwKec0BexVPl5l2IPV:-NYwKec0BexVPl5l2IPW:b-q3h8tt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L60)):*
> ```XML
>   }
> 
>   highlightNthDepartureOnStopRow(stopLabel: string, nthDeparture: number) {
> ```

I think this could/should be named "clickNthPassingTimeOnStopRow" etc. because that describes more what we functionally do. The highlight of the vehicle journey passing times is a consequence. (Notice that also the nthDeparture should be nthPassingTime, or nthPassingTimes, because it includes the departure and arrival time)
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 73 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwNV7F3fy9qGPfwazC:-NYwNV7F3fy9qGPfwazD:bk7n2c3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L73)):*
> ```XML
>   }
> 
>   assertNthDepartureHighlightOnStopRow(values: {
> ```

Same here, nthPassingTime or nthPassingTimes.

Btw, no need to have this "values" wrapper, you can just use destructured parameters, without the "values.parameter"



_Suggestion:_
```XML
  assertNthDepartureHighlightOnStopRow({
    stopLabel: string;
    nthDeparture: number;
    isHighlighted: boolean;
  }) {
```
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 75 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwN_-_A4NcoG_zgErG:-NYwN_-a6P0e4YVguP3k:bji28bi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L75)):*
> ```XML
>   assertNthDepartureHighlightOnStopRow(values: {
>     stopLabel: string;
>     nthDeparture: number;
> ```

and here

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)* status: 3 of 11 files reviewed, 12 unresolved discussions (waiting on @HenrikHartiala)

___
*[`README.md` line 80 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2mxTU2I8ZC-GyR1tY:-NZ-md-sBz3pN4K6LVVr:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/README.md#L80)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 266 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NY2rhIV8WTiFMq8x01Q:-NZ-mtOb1XN4U9FwmWRe:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65fbed24cfabdac5aca8a8b725e7988ee9661c5e/cypress/e2e/timetableImport.cy.ts#L266)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes. It does mean duplicating setup code for now, but since it is not related to importing timetables, it does not belong in this file. Also optimally in the future we want to change the data seeding in this test so that the needed timetable data is seeded straight to database instead of using the import functionality in the UI.
</blockquote></details>

Done.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 13 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwDvb2E2J3uuz5gnoI:-NZ-MFPHDCAdjhNCdy_n:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L13)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

These two were a bit confusing at first, but then I realised that this PassingMinute should probably be within the PassingTime, right?

So if you move this PassingMinute inside the PassingTime, the structure should be fine. Kind of "Find the nth passing time, then find the minutes within this passing time".
</blockquote></details>

Done.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 55 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYvhjwHETr91WyaaLrY:-NZ07v-065o2992smlYA:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L55)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This function (and the dependencies for this function) is already called in the refactoring commit, so it should be added there already to retain the integrity of the commit. 
</blockquote></details>

Done.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 57 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYw4DajAfZRUNHUfUiB:-NZ-mP_ECCqS-bx4Z72G:b-9tf43m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L57)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

A couple of new thoughts risen here. Like said in earlier comment, first I was thinking that you could retain the "assertArrivalTime..." and "assertDepartureTime..." functions, and have the contents in helper functions to reduce the duplicate code. 

But, now I realised also that we could just have "assertNthPassingTime" and then assert all the passingTimes at once. So hour, departureTime and arrivalTime in the same function. What do you think?

So something like 
```
assertNthPassingTimeOnStop({
    stopLabel,
    nthPassingTime,
    hour,
    arrivalTime,
    departureTime,
  }: {
    stopLabel: string;
    nthPassingTime: number;
    hour: number;
    arrivalTime?: string;
    departureTime: string;
  }) {
    this.getTableRow(stopLabel).within(() => {
      this.passingTimesByStopTableRowPassingTime
        .getTimeContainer()
        .eq(nthPassingTime)
        .within(() => {
          this.passingTimesByStopTableRowPassingTime
            .getHour()
            .should('contain', hour);
          this.passingTimesByStopTableRowPassingMinute
            .getDepartureTime()
            .should('contain', departureTime);
          if (arrivalTime) {
            this.passingTimesByStopTableRowPassingMinute
              .getArrivalTime()
              .should('contain', arrivalTime);
          }
        });
    });
  }
```
This is just a rough example and can (and should) be modified. For example we should still move the passingMinute inside passingTime (as said in an earlier comment) and I think that will also make this function simpler.
</blockquote></details>

Sounds ok to me.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 60 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwKec0BexVPl5l2IPV:-NZ-fH2sEw7A7mrEbOr0:b-gubowg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L60)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this could/should be named "clickNthPassingTimeOnStopRow" etc. because that describes more what we functionally do. The highlight of the vehicle journey passing times is a consequence. (Notice that also the nthDeparture should be nthPassingTime, or nthPassingTimes, because it includes the departure and arrival time)
</blockquote></details>

I added 'click' to the name, but I think it should also be clear why it is clicked.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 73 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwNV7F3fy9qGPfwazC:-NZ-fFFl33RqgPcy4rbn:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L73)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Same here, nthPassingTime or nthPassingTimes.

Btw, no need to have this "values" wrapper, you can just use destructured parameters, without the "values.parameter"
</blockquote></details>

Done.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 75 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwN_-_A4NcoG_zgErG:-NZ-fF078hjv9C4kB8uT:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L75)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r5, 4 of 4 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 234 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NZPxiLS2GQ1_wxjnHXn:-NZPxiLS2GQ1_wxjnHXo:buqy853) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ebc1b1f549d49ff7856c45629bd280087b295435/cypress/e2e/timetablePassingTimes.cy.ts#L234)):*
> ```XML
>           nthPassingTime: 0,
>           hour: 7,
>           arrivalTime: '12',
> ```

As said in the other comment, this now looks a bit odd when the other one is a string and the other one is a number.
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 60 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NYwKec0BexVPl5l2IPV:-NZPfxmZ4W2LWsPuIAPm:bdo29hu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/51f2fc866031974d3b967410fa3095012a22ede4/cypress/pageObjects/PassingTimesByStopTable.ts#L60)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I added 'click' to the name, but I think it should also be clear why it is clicked.
</blockquote></details>

Yeah, that sounds good :+1: 
___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 50 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NZPqFFX-K_2Koj3eQlO:-NZPqFFX-K_2Koj3eQlP:b5yu07) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/98df61fb02ca9f91c4ddce5b05e72d67ce1c6b00/cypress/pageObjects/PassingTimesByStopTable.ts#L50)):*
> ```XML
>     nthPassingTime: number;
>     hour: number;
>     // arrivalTime is a string because it can contain
> ```

This is a good explanation and all, but I think for consistency, they could both (arrivalTime and departureTime) be strings (in the example they are already both strings) (maybe the hour as well?). I believe in the end it is a string comparison anyway, when cypress compares the result with the expectation. 

Also the explanation of the case "if at earlier hour blaablaa, it shows the whole time '08:59' instead of just minutes", would be nice in the JSDoc comment, so the developer can see it via intellisense.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 75 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NZQ1tSuDMkBXOmN4Axm:-NZQ1tSuDMkBXOmN4Axn:b-ifarr5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ebc1b1f549d49ff7856c45629bd280087b295435/cypress/pageObjects/PassingTimesByStopTable.ts#L75)):*
> ```XML
>   }
> 
>   assertNthPassingTimeHighlightOnStopRow({
> ```

These other functions would benefit from JSDoc comment as well

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)* status: all files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 50 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NZPqFFX-K_2Koj3eQlO:-NZQDOMc0SCCM66RSa3d:b-nc5trt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/98df61fb02ca9f91c4ddce5b05e72d67ce1c6b00/cypress/pageObjects/PassingTimesByStopTable.ts#L50)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is a good explanation and all, but I think for consistency, they could both (arrivalTime and departureTime) be strings (in the example they are already both strings) (maybe the hour as well?). I believe in the end it is a string comparison anyway, when cypress compares the result with the expectation. 

Also the explanation of the case "if at earlier hour blaablaa, it shows the whole time '08:59' instead of just minutes", would be nice in the JSDoc comment, so the developer can see it via intellisense.
</blockquote></details>

Changed all the times to strings now. Having feature documentation in test JSDOCs is not really a good sign of how things are documented in this project.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sr-vala)

___
*[`cypress/pageObjects/PassingTimesByStopTable.ts` line 50 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/621#-NZPqFFX-K_2Koj3eQlO:-NZQGx451-8BVOFmr2H1:b2ntall) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/98df61fb02ca9f91c4ddce5b05e72d67ce1c6b00/cypress/pageObjects/PassingTimesByStopTable.ts#L50)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Changed all the times to strings now. Having feature documentation in test JSDOCs is not really a good sign of how things are documented in this project.
</blockquote></details>

That is actually true, and I nearly came back and commented that if you just change them to strings, that should be enough (no further explanation needed).
My flow of thought was more like that IF you need to comment the behaviour, then it would be better in the JSDoc. But since now they are all consistent, I don't think that the explanation is needed at all.

**Pull request merged**
