### PR TITLE
Refactor map query params

### PR DESCRIPTION
**Pull request by HenrikHartiala**
This PR removes the isMapOpen attribute from redux store, since this is kept in queryParameters. There is no need to keep this in two places and then synchronise the states all the time.

This also renames and refactors useMapUrlQuery to match the earlier queryparameter hooks

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8cf2WYE2IqNHI3zsuf:-N8cf2WZAZodF9oe1q2Z:b12soxk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ac555de854f4221750210f1fe53c4712ca5fbe4f/ui/src/hooks/useMapOpenQueryParam.ts#L16)):*
> ```XML
> 
>   const setIsMapOpen = (value: boolean) => {
>     value ? addMapOpenQueryParameter() : deleteMapOpenQueryParameter();
> ```

Im not completely sure if this is better than using `addMapOpenQueryParameter()` and `deleteMapOpenQueryParameter()` directly.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8cf2WYE2IqNHI3zsuf:-N8gz6rSEPcw-OWOYV-o:br6w6gw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ac555de854f4221750210f1fe53c4712ca5fbe4f/ui/src/hooks/useMapOpenQueryParam.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Im not completely sure if this is better than using `addMapOpenQueryParameter()` and `deleteMapOpenQueryParameter()` directly.
</blockquote></details>

Okay, so I came in to the decision that I do not want to keep this `setIsMapOpen()` function, because 
1) it is a bit misleading with the `false` value, because it does not set it to false, it deletes the query parameters.
2) I need to extend this file to useMapQueryParams in the next PR where I add mapPosition query parameters as well. And If this is called "setIsMapOpen" it will not serve the purpose anymore when I want to close the map and remove all the map related parameters.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/hooks/index.ts` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8h-6NTAZ2ALkohRtxT:-N8h-6NTAZ2ALkohRtxU:b-21iq4f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/02a8df74d10c976563a2077c2cc6699e75ddbc21/ui/src/hooks/index.ts#L17)):*
> ```XML
> export * from './useExtractRouteFromFeature';
> export * from './useFilterStops';
> export * from './useMapOpenQueryParam';
> ```

let's move these query related hooks to their own folder (at least useUrlQuery, useMapOpenQueryParam, useObservationDateQueryParam. It's a shame that usePagination in its current form is not qualifying for this category as it's also mixing in some business logic there...)

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 7 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8h0Hg_6lIP9-6Wr0WE:-N8h0Hg_6lIP9-6Wr0WF:b-pv70cd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/02a8df74d10c976563a2077c2cc6699e75ddbc21/ui/src/hooks/useMapOpenQueryParam.ts#L7)):*
> ```XML
>   const { queryParams, setToUrlQuery, deleteFromUrlQuery } = useUrlQuery();
> 
>   const addMapOpenQueryParameter = () => {
> ```

this addMapOpenQueryParameter and deleteMapOpenQueryParameter should be removed. Instead, let's create some generic conversion functions in useUrlQuery:
- setBooleanToUrlQuery(paramName: string, value: boolean?, replace?: boolean): void;
- setDateToUrlQuery(paramName: string, value: DateTime?, replace?: boolean): void;
^ these would do conversion and then call setToUrlQuery within

- getBooleanParam(paramName: string): boolean?;
- getDateParam(paramName: string): DateTime?;
^ these would retrieve the query parameter's value (if exists) and convert it to the given type

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/components/map/routes/RouteEditor.tsx` line 247 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8h2N6h8NafVHV-yh63:-N8h2N6h8NafVHV-yh64:bfev8i3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/02a8df74d10c976563a2077c2cc6699e75ddbc21/ui/src/components/map/routes/RouteEditor.tsx#L247)):*
> ```XML
>       showSuccessToast(t('routes.deleteSuccess'));
> 
>       setIsDeleting(false);
> ```

didn't you forget to call `setIsMapOpen(false)` here?
___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8cf2WYE2IqNHI3zsuf:-N8h1qYQ6fK8mrdEEBt6:b-7m9qbo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ac555de854f4221750210f1fe53c4712ca5fbe4f/ui/src/hooks/useMapOpenQueryParam.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Okay, so I came in to the decision that I do not want to keep this `setIsMapOpen()` function, because 
1) it is a bit misleading with the `false` value, because it does not set it to false, it deletes the query parameters.
2) I need to extend this file to useMapQueryParams in the next PR where I add mapPosition query parameters as well. And If this is called "setIsMapOpen" it will not serve the purpose anymore when I want to close the map and remove all the map related parameters.
</blockquote></details>

at least in the scope of this PR, I think this is all fine. It's enough if you iterate on this later...
___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 7 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8h0Hg_6lIP9-6Wr0WE:-N8h1aBB2HJv6abqJ3t9:bgh0kjo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/02a8df74d10c976563a2077c2cc6699e75ddbc21/ui/src/hooks/useMapOpenQueryParam.ts#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this addMapOpenQueryParameter and deleteMapOpenQueryParameter should be removed. Instead, let's create some generic conversion functions in useUrlQuery:
- setBooleanToUrlQuery(paramName: string, value: boolean?, replace?: boolean): void;
- setDateToUrlQuery(paramName: string, value: DateTime?, replace?: boolean): void;
^ these would do conversion and then call setToUrlQuery within

- getBooleanParam(paramName: string): boolean?;
- getDateParam(paramName: string): DateTime?;
^ these would retrieve the query parameter's value (if exists) and convert it to the given type
</blockquote></details>

oh yeah, I wonder if we should also use useMemo with those getters...?

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/components/map/routes/RouteEditor.tsx` line 247 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8h2N6h8NafVHV-yh63:-N8hQP2DDMEK5ePsxhUh:bjtctqh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/02a8df74d10c976563a2077c2cc6699e75ddbc21/ui/src/components/map/routes/RouteEditor.tsx#L247)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

didn't you forget to call `setIsMapOpen(false)` here?
</blockquote></details>

Removed it because I thought that the user might want to stay in the map view. But currently it is not handled correctly and the route geometry stays visible after removing the route. This needs a separate PR and until then I think I'll put back this behaviour of closing the map after route delete.
___
*[`ui/src/hooks/index.ts` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8h-6NTAZ2ALkohRtxT:-N8h5Kx59IrP1DFssv75:b7zes7f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/02a8df74d10c976563a2077c2cc6699e75ddbc21/ui/src/hooks/index.ts#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's move these query related hooks to their own folder (at least useUrlQuery, useMapOpenQueryParam, useObservationDateQueryParam. It's a shame that usePagination in its current form is not qualifying for this category as it's also mixing in some business logic there...)
</blockquote></details>

Yep, was also thinking that after couple we should move these to own folder. :+1:. I will do this in a separate PR
___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 7 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8h0Hg_6lIP9-6Wr0WE:-N8h8EgBAxru5iB92oHq:btfys0l) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/02a8df74d10c976563a2077c2cc6699e75ddbc21/ui/src/hooks/useMapOpenQueryParam.ts#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

oh yeah, I wonder if we should also use useMemo with those getters...?
</blockquote></details>

These generic conversions are good idea! But I am not sure why we should remove `deleteMapOpenQueryParam`?
I'll do the setBoolean and getBoolean, but with the Date, I would again like to do it in a separate PR, because it is not in scope of this initial PR.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 11 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8hfzwz3sBwDVukCupD:-N8hfzwz3sBwDVukCupE:ba7igo4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0a24fe2cf2a47ffcad6a3889d52303e645e39eda/ui/src/hooks/useMapOpenQueryParam.ts#L11)):*
> ```XML
>   } = useUrlQuery();
> 
>   const addMapOpenQueryParameter = () => {
> ```

I'd consider renaming these functions to represent what they are actually doing...
addMapOpenQueryParameter -> openMapModal
deleteMapOpenQueryParameter -> closeMapModal
___
*[`ui/src/hooks/useUrlQuery.ts` line 51 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8hhC3-2Jrw1_bRGFs7:-N8hhC3-2Jrw1_bRGFs8:bycjwle) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0a24fe2cf2a47ffcad6a3889d52303e645e39eda/ui/src/hooks/useUrlQuery.ts#L51)):*
> ```XML
>     value,
>     replace,
>   }: {
> ```

I'd consider creating own types for these, instead of using inline types:

```
type QueryParameter<TValue> = {paramName: string, value: TValue};
type ParameterWriteOptions = {replace?: boolean};
```

and then:

```
const setBooleanToUrlQuery = ({paramName, value}: QueryParameter<boolean>, {replace}: ParameterWriteOptions?) => {...}
```

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 11 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8hfzwz3sBwDVukCupD:-N8hk9dMAyK0F3QWjLqr:b-wjapx1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0a24fe2cf2a47ffcad6a3889d52303e645e39eda/ui/src/hooks/useMapOpenQueryParam.ts#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd consider renaming these functions to represent what they are actually doing...
addMapOpenQueryParameter -> openMapModal
deleteMapOpenQueryParameter -> closeMapModal
</blockquote></details>

Yeah, this is where my brain went to infinite loop :D. Because I wanted to call them "openMap" or "openMapModal", but is it then the right name for "useMapOpenQueryParam"? Will it be confusing that a queryParam controlling hook has functions named by the cause of the action rather than the action.
Or should we add yet another hook which is called `useMapModal` which has `openMapModal` and `closeMapModal` which then calls these "addMapOpenQueryParameter" and `deleteMapOpenQueryParameter`.
What do you think?

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`ui/src/hooks/useUrlQuery.ts` line 51 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8hhC3-2Jrw1_bRGFs7:-N8hppeO1dewztryEeF4:bp8b7dh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0a24fe2cf2a47ffcad6a3889d52303e645e39eda/ui/src/hooks/useUrlQuery.ts#L51)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd consider creating own types for these, instead of using inline types:

```
type QueryParameter<TValue> = {paramName: string, value: TValue};
type ParameterWriteOptions = {replace?: boolean};
```

and then:

```
const setBooleanToUrlQuery = ({paramName, value}: QueryParameter<boolean>, {replace}: ParameterWriteOptions?) => {...}
```
</blockquote></details>

Nice, I'll do these. Also had to give a default value of `{}`for the replace. Like so:
```
const setBooleanToUrlQuery = (
    { paramName, value }: QueryParameter<boolean>,
    { replace }: ParameterWriteOptions = {},
  ) => {
    setToUrlQuery({ paramName, value: value.toString(), replace });
  };
```
https://stackoverflow.com/questions/56969950/optional-typed-immediately-destructured-parameters

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/282)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`ui/src/hooks/useMapOpenQueryParam.ts` line 11 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8hfzwz3sBwDVukCupD:-N8hrwpcBIMI9EUMXJrS:b-jal9iz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0a24fe2cf2a47ffcad6a3889d52303e645e39eda/ui/src/hooks/useMapOpenQueryParam.ts#L11)):*
> cause of the action 

consequence* of the action
___
*[`ui/src/hooks/useUrlQuery.ts` line 51 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/282#-N8hhC3-2Jrw1_bRGFs7:-N8hqGFS0K2A-kfhi246:b-jaz5c8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0a24fe2cf2a47ffcad6a3889d52303e645e39eda/ui/src/hooks/useUrlQuery.ts#L51)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Nice, I'll do these. Also had to give a default value of `{}`for the replace. Like so:
```
const setBooleanToUrlQuery = (
    { paramName, value }: QueryParameter<boolean>,
    { replace }: ParameterWriteOptions = {},
  ) => {
    setToUrlQuery({ paramName, value: value.toString(), replace });
  };
```
https://stackoverflow.com/questions/56969950/optional-typed-immediately-destructured-parameters
</blockquote></details>

Not the most readable code like this, but at least it is extendable and reusable.

**Pull request merged**
