### PR TITLE
Avoid defining absolute url's on client side

### PR DESCRIPTION
**Pull request by tk-vincit**
Resolves https://github.com/HSLdevcom/jore4/issues/474

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/31)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/31)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @tk-vincit)

___
*[server.js, line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiHcSp1L5rkV8tnInV:-MjiHcSp1L5rkV8tnInW:b-ggvayh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L7)):*
> ```JavaScript
> // custom dev server for being able to proxy websocket traffic from
> // relative url to local dev server
> // based on https://github.com/vercel/next.js/blob/master/examples/with-custom-reverse-proxy/server.js
> ```

thanks for marking the source as well!
___
*[server.js, line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiHjkH7f9SRvC3rQqr:-MjiHjkH7f9SRvC3rQqs:b-k7knec) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L14)):*
> ```JavaScript
> const devProxy = {
>   // http traffic is proxied through native `next.js` tooling in `next.config.js`
>   '/api/hasura': {
> ```

in kubernetes environment, this is `/api/graphql`. This won't work with `/api/hasura`
___
*[server.js, line 24 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiHzxA3h87vygqeUKT:-MjiHzxA3h87vygqeUKU:b-a35131) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L24)):*
> ```JavaScript
> };
> 
> const port = parseInt(process.env.PORT, 10) || 3000;
> ```

Did you know that you could just write `+(process.env.PORT)` to convert it to a number? No need to fix this, just FYI
___
*[server.js, line 26 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiIckZBR0O00dcw7br:-MjiIckZBR0O00dcw7bs:bqp0qa6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L26)):*
> ```JavaScript
> const port = parseInt(process.env.PORT, 10) || 3000;
> const env = process.env.NODE_ENV;
> const dev = env !== 'production';
> ```

From now on, this docker image will need a mandatory `NODE_ENV=production` environment variable to be set in docker compose / kubernetes. This should be documented somewhere... Or is this dev server even used in the docker compose / kubernetes environments? Don't they just host the bundle.js in nginx? Then you could just delete this nv !== 'production' stuff...

Anyhow, it's pretty crucial to document all changes to the software interface (so mostly the used environment variables...). You don't seem to have a Docker reference section in your README at all, could you please draft quickly something like this: https://github.com/HSLdevcom/jore4-mssql-testdb#docker-reference
___
*[server.js, line 32 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiJc7V5W0ahh3b2hPN:-MjiJc7W1HJ5mlWS7f4j:b531egf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L32)):*
> ```JavaScript
> });
> 
> const handle = app.getRequestHandler();
> ```

maybe rather name this as "defaultNextJsHandler" or similar to clarify "who" is the handler
___
*[server.js, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiKI5FEsL1fTESzYQD:-MjiJvcS5H-xGHyYXKqe:b-lz3f0y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L46)):*
> ```JavaScript
>       Object.keys(devProxy).forEach((context) => {
>         const proxy = createProxyMiddleware(devProxy[context]);
>         server.use(context, proxy);
> ```

is there a reason that you don't just define the proxy rules directly, like this:

```
server.use('/api/graphql', createProxyMiddleware({
    pathRewrite: {
      '^/api/hasura': '', // remove path.
    },
    target: 'http://localhost:8080',
    changeOrigin: true,
    ws: true,
  }),
);
...
server.use('...', {})
```
Instead of extracting it to its own variable? There's no need to refactor this, but to me this was pretty hard to understand first... it seems like an additional layer of abstraction that I don't really see the need for
___
*[src/components/map/Filters.tsx, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiKwDPEHA9pK0rll2Z:-MjiKwDPEHA9pK0rll2_:bbrslw3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/src/components/map/Filters.tsx#L19)):*
> ```XML
> const drDynamicInfraLinksUrl = '/api/martin/digiroad.dr_linkki/{z}/{x}/{y}.pbf';
> const drStopsUrl = '/api/mbtiles/services/dr_pysakki/tiles/{z}/{x}/{y}.pbf';
> const drDynamicStopsUrl = '/api/martin/digiroad.dr_pysakki/{z}/{x}/{y}.pbf';
> ```

looks nice!
___
*[src/components/mapgl-map/Map.tsx, line 77 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiL10S2uM1saPZ3Ora:-MjiL10S2uM1saPZ3Orb:b-dtxvxi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/src/components/mapgl-map/Map.tsx#L77)):*
> ```XML
>           // we can make those url's non-relative by prepending those with
>           // window.location.origin
>           // https://github.com/mapbox/mapbox-gl-js/issues/10407
> ```

well documented!

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/31)* status: 0 of 15 files reviewed, 8 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[server.js, line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiHjkH7f9SRvC3rQqr:-Mjj6DLK3j62Za-JBW1K:bmny48e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

in kubernetes environment, this is `/api/graphql`. This won't work with `/api/hasura`
</blockquote></details>

Okay. I made this according to `next.config.js`, then we have typo in there too. I'll fix also it :)
___
*[server.js, line 24 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiHzxA3h87vygqeUKT:-MjiyZqLDrZSMLE7gUr-:b9ljycg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L24)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Did you know that you could just write `+(process.env.PORT)` to convert it to a number? No need to fix this, just FYI
</blockquote></details>

Cool trick!
___
*[server.js, line 26 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiIckZBR0O00dcw7br:-MjiybV-EJQe2Ot4wH__:b-g1axvk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

From now on, this docker image will need a mandatory `NODE_ENV=production` environment variable to be set in docker compose / kubernetes. This should be documented somewhere... Or is this dev server even used in the docker compose / kubernetes environments? Don't they just host the bundle.js in nginx? Then you could just delete this nv !== 'production' stuff...

Anyhow, it's pretty crucial to document all changes to the software interface (so mostly the used environment variables...). You don't seem to have a Docker reference section in your README at all, could you please draft quickly something like this: https://github.com/HSLdevcom/jore4-mssql-testdb#docker-reference
</blockquote></details>

This server is used only in dev environment. 

Dev/prod stuff here cames from the original source of this file, but I'll remove those as it seems like you find those confusing.

I'll add docker reference.
___
*[server.js, line 32 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiJc7V5W0ahh3b2hPN:-Mjj-UCp5IRdwDyIsuK-:bsp6uca) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe rather name this as "defaultNextJsHandler" or similar to clarify "who" is the handler
</blockquote></details>

`requestHandler` it is then.
___
*[server.js, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiKI5FEsL1fTESzYQD:-Mjj57lq3ObUlC4TYQFM:b-96r2pe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L46)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

is there a reason that you don't just define the proxy rules directly, like this:

```
server.use('/api/graphql', createProxyMiddleware({
    pathRewrite: {
      '^/api/hasura': '', // remove path.
    },
    target: 'http://localhost:8080',
    changeOrigin: true,
    ws: true,
  }),
);
...
server.use('...', {})
```
Instead of extracting it to its own variable? There's no need to refactor this, but to me this was pretty hard to understand first... it seems like an additional layer of abstraction that I don't really see the need for
</blockquote></details>

Did you noticed that there could be more than one path to be proxied? Current solution might be a bit clearer in that kind of case, as it keeps "configuration" in its own data structure and separated from the implementation.

Anyway, removed a bit code around this so maybe this is clearer now?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/31)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[README.md, line 62 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjmtsHCE5-kqcFJ9ZSd:-MjmtsHD2SOb6R3P5XQK:b5w0et) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/62b1fa9e68fbffac6076094d27698e04cf44d1eb/README.md#L62)):*
> ```Markdown
> 
> **Docker image doesn't expect any environment variables from outside.**
> Docker image expects that it is served from same host as our backend services which it uses.
> ```

`host` is a bit misleading term here. The backends could be hosted anywhere, it doesn't matter. The UI expects that the backend calls are routed under the same baseurl as it references them via a relative path.
___
*[server.js, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjiKI5FEsL1fTESzYQD:-Mjmum3F05F_kOre7eCH:b-gbxqjo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4fd2766ddea1b58b780af4285be63e86617cb4ce/server.js#L46)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Did you noticed that there could be more than one path to be proxied? Current solution might be a bit clearer in that kind of case, as it keeps "configuration" in its own data structure and separated from the implementation.

Anyway, removed a bit code around this so maybe this is clearer now?
</blockquote></details>

Yeah, it doesn't matter... DONE

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/31)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/31)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[README.md, line 62 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/31#-MjmtsHCE5-kqcFJ9ZSd:-Mjn9Rf_D__uJZhRc1zq:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/62b1fa9e68fbffac6076094d27698e04cf44d1eb/README.md#L62)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`host` is a bit misleading term here. The backends could be hosted anywhere, it doesn't matter. The UI expects that the backend calls are routed under the same baseurl as it references them via a relative path.
</blockquote></details>

Done

**Pull request merged**
