### PR TITLE
Check stops for priority/validity conflicts before save

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 118 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo7zJC3lOVyqc2d3DH:-Mzo7zJC3lOVyqc2d3DI:b-ew1x98) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/useCheckValidityAndPriorityConflicts.ts#L118)):*
> ```XML
>     const isDraft = params.priority === Priority.Draft;
>     if (isDraft) {
>       // Resources marked as "draft" are allowed to have conflicts
> ```

maybe would be a better way to say that "...are allowed to overlap"
___
*[src/hooks/stops/useCreateStop.ts, line 31 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo8pqBCGNMOII92eO7:-Mzo8pqCC02k5CoRCwwJ:bkdajxq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useCreateStop.ts#L31)):*
> ```XML
>       // these form values always exist
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>       label: input.label!,
> ```

would it be smart to just override these types in schema-loader.js to actually force the required parameters not to have undefined or null values? This works properly for other types but scheduled stop points are implemented as an SQL VIEW, so the generated type is invalid
___
*[src/hooks/stops/useCreateStop.ts, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9Ljx-CUZKp0tGjP9:-Mzo9Ljx-CUZKp0tGjPA:b1gwuae) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useCreateStop.ts#L35)):*
> ```XML
>       priority: input.priority!,
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>       validityStart: input.validity_start!,
> ```

actually, we could allow validity_start to be null / undefined as stops imported from jore3 don't necessarily have a validity start
___
*[src/hooks/stops/useEditStop.ts, line 101 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9iXy2WkhUrG7cloL:-Mzo9iXy2WkhUrG7cloM:b-s29r7v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L101)):*
> ```XML
>         // these form values always exist
>         // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>         label: patch.label!,
> ```

for now we only edit stops through the StopForm, so all the values are present. In my PR however I need to allow moving the stops, which means only the `measured_location` field is present in the patch.

So here you have to do some fall-back value handling:
```
// null values are valid for patches, so here checking for undefined values only
const defaultTo = (value: unknown, defaultValue: unknown) => (value === undefined ? defaultValue : value);

let conflicts = [];
if (patch.label !== undefined || patch.priority !== undefined || ...) {
  conflicts = await getConflictingStops({
    label: defaultTo(patch.label, oldStop.label),
    priority: defaultTo(patch.priority, oldStop.priority),
    ...
  })
}
```
___
*[src/hooks/stops/useEditStop.ts, line 105 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-MzoCOVJ9vaFgqCdhINA:-MzoCOVJ9vaFgqCdhINB:b-dmd2uo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L105)):*
> ```XML
>         priority: patch.priority!,
>         // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>         validityStart: patch.validity_start!,
> ```

we should allow validity_start to be null/undefined as well

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @pallost)

___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 118 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo7zJC3lOVyqc2d3DH:-MzoIyFz-kA3mNBMBJQl:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/useCheckValidityAndPriorityConflicts.ts#L118)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe would be a better way to say that "...are allowed to overlap"
</blockquote></details>

Done.
___
*[src/hooks/stops/useCreateStop.ts, line 31 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo8pqBCGNMOII92eO7:-MzoK-hc7EdtrAKXHE5c:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useCreateStop.ts#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

would it be smart to just override these types in schema-loader.js to actually force the required parameters not to have undefined or null values? This works properly for other types but scheduled stop points are implemented as an SQL VIEW, so the generated type is invalid
</blockquote></details>

Done.
___
*[src/hooks/stops/useCreateStop.ts, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9Ljx-CUZKp0tGjP9:-MzpCkbP9lMSxHImoSEk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useCreateStop.ts#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually, we could allow validity_start to be null / undefined as stops imported from jore3 don't necessarily have a validity start
</blockquote></details>

Done.
___
*[src/hooks/stops/useEditStop.ts, line 101 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9iXy2WkhUrG7cloL:-MzpFc5JDdpuiSGqNVvL:bb7bt09) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L101)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

for now we only edit stops through the StopForm, so all the values are present. In my PR however I need to allow moving the stops, which means only the `measured_location` field is present in the patch.

So here you have to do some fall-back value handling:
```
// null values are valid for patches, so here checking for undefined values only
const defaultTo = (value: unknown, defaultValue: unknown) => (value === undefined ? defaultValue : value);

let conflicts = [];
if (patch.label !== undefined || patch.priority !== undefined || ...) {
  conflicts = await getConflictingStops({
    label: defaultTo(patch.label, oldStop.label),
    priority: defaultTo(patch.priority, oldStop.priority),
    ...
  })
}
```

</blockquote></details>

Was this `if` statement needed for some reason or can we just default to use `defaultTo` function in this case? :)
___
*[src/hooks/stops/useEditStop.ts, line 105 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-MzoCOVJ9vaFgqCdhINA:-MzpD4KoAi6xyUlC7suQ:beqx4up) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L105)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we should allow validity_start to be null/undefined as well
</blockquote></details>



Then we have to modify `useCheckValidityAndPriorityConflicts` hook accordingly. And then we should probably also allow creating/editing stops without validityStart from UI, as currently that is not allowed e.g. on form validation side. So if that is requirement then maybe we should create ticket for that.

What do you want to do at this point?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/forms/StopForm.tsx, line 168 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NCuc7DiNgwQPC8hQ4:-N-NCuc88IYbvAZdGVve:bw37681) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/88d5b542c3d8607cd9d9fb494c38b65e7e5b6ff9/src/components/forms/StopForm.tsx#L168)):*
> ```XML
>         onSubmit={handleSubmit(onFormSubmit)}
>         ref={ref}
>       >
> ```

all this kind of wizard-like interaction and confirmation dialogs have already been moved to EditStopLayer. Let's not include the resolver modal here but handle this interaction as well in the EditStopLayer!
___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 108 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NDC3-96woRIuky_ml:-N-NDC3-96woRIuky_mm:briv5n9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/88d5b542c3d8607cd9d9fb494c38b65e7e5b6ff9/src/hooks/useCheckValidityAndPriorityConflicts.ts#L108)):*
> ```XML
>     GetLinesByValidityQueryVariables
>   >(GetLinesByValidityDocument);
>   const [getStopValidity] = useAsyncQuery<
> ```

you could start using the new nice and shiny `useGetStopsByValidityAsyncQuery` hook ;)
___
*[src/hooks/stops/useCreateStop.ts, line 57 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NDu3n0lweuC2ejPDT:-N-NDu3n0lweuC2ejPDU:bcgsq2k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/88d5b542c3d8607cd9d9fb494c38b65e7e5b6ff9/src/hooks/stops/useCreateStop.ts#L57)):*
> ```XML
>       priority: input.priority,
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>       validityStart: input.validity_start!,
> ```

you just added some filter for this, so should allow:

`input.validity_start || undefined`
___
*[src/hooks/stops/useEditStop.ts, line 101 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9iXy2WkhUrG7cloL:-N-NEo7v8kf7v7aEZf7y:b8qsi0h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L101)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Was this `if` statement needed for some reason or can we just default to use `defaultTo` function in this case? :)
</blockquote></details>

yeah, if label, priority or validity fields are not touched, then there's no need to even do the getConflictingStops backend call. See how it was done with `onStopLocationChanged` 
___
*[src/hooks/stops/useEditStop.ts, line 105 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-MzoCOVJ9vaFgqCdhINA:-N-NF35h1qF6gjdQ1oOA:b-ern468) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L105)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>



Then we have to modify `useCheckValidityAndPriorityConflicts` hook accordingly. And then we should probably also allow creating/editing stops without validityStart from UI, as currently that is not allowed e.g. on form validation side. So if that is requirement then maybe we should create ticket for that.

What do you want to do at this point?
</blockquote></details>

I think you've already modified the hook to include cases where validity_start could be null...?
___
*[src/hooks/stops/useEditStop.ts, line 135 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NETHHDV7Y7Tix3DZf:-N-NETHHDV7Y7Tix3DZg:b-7kl0fw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/88d5b542c3d8607cd9d9fb494c38b65e7e5b6ff9/src/hooks/stops/useEditStop.ts#L135)):*
> ```XML
>   const prepareEdit = async ({ stopId, patch }: EditParams) => {
>     const stopResult = await getStopById({ stopId });
>     const oldStop = mapGetStopByIdResult(stopResult);
> ```

this `oldStop` is actually the same entity as the `stopWithRouteGraphData` below, no need to request it multiple times

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 108 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NDC3-96woRIuky_ml:-N-NGO2L7qum--KbMyP9:bcyd8zn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/88d5b542c3d8607cd9d9fb494c38b65e7e5b6ff9/src/hooks/useCheckValidityAndPriorityConflicts.ts#L108)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could start using the new nice and shiny `useGetStopsByValidityAsyncQuery` hook ;)
</blockquote></details>

Nice! Done
___
*[src/hooks/stops/useEditStop.ts, line 101 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9iXy2WkhUrG7cloL:-N-NRFmQDvAK7wSqMY8q:b-trsnrh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L101)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yeah, if label, priority or validity fields are not touched, then there's no need to even do the getConflictingStops backend call. See how it was done with `onStopLocationChanged` 
</blockquote></details>

Added condition to avoid potentially unneeded api call...
___
*[src/hooks/stops/useEditStop.ts, line 105 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-MzoCOVJ9vaFgqCdhINA:-N-NO3OYBsDELhx8Sp-O:b-4x9n8q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L105)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think you've already modified the hook to include cases where validity_start could be null...?
</blockquote></details>

So no further changes needed at this point?

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/map/stops/EditStopLayer.tsx, line 210 at r16](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NXr4s-Ie4GMbD1UbN:-N-NXr4s-Ie4GMbD1UbO:b8owqm5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30f88d01a36da41eeab21140d6a95bf9267b09ee/src/components/map/stops/EditStopLayer.tsx#L210)):*
> ```XML
> 
>   const onStopFormSubmit = async (changes: EditChanges | CreateChanges) => {
>     if (changes.conflicts?.length) {
> ```

maybe let's not create a separate state variable for this: conflicts are already stored within the editChanges state
___
*[src/components/map/stops/EditStopLayer.tsx, line 275 at r16](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NYLfmCF58MKewguTe:-N-NYLfmCF58MKewguTf:bx89lmu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30f88d01a36da41eeab21140d6a95bf9267b09ee/src/components/map/stops/EditStopLayer.tsx#L275)):*
> ```XML
>         />
>       )}
>       <ConflictResolverModal
> ```

it would be clearer if this was also behind a conditional render:
```
{editChanges.conflicts && <ConflictResolverModal/>}
```
___
*[src/hooks/stops/useEditStop.ts, line 101 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9iXy2WkhUrG7cloL:-N-NZUYf2e6xdVHrBJLq:bbo24j7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L101)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Added condition to avoid potentially unneeded api call...
</blockquote></details>

looks good!
___
*[src/hooks/stops/useEditStop.ts, line 105 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-MzoCOVJ9vaFgqCdhINA:-N-NZYAS0n_ZH2v2VpiU:b-45hj3x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L105)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

So no further changes needed at this point?
</blockquote></details>

nope, I just didn't get your point
___
*[src/hooks/stops/useEditStop.ts, line 158 at r16](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NZmqq-WdII7xKziQp:-N-NZmqq-WdII7xKziQq:b2trv0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30f88d01a36da41eeab21140d6a95bf9267b09ee/src/hooks/stops/useEditStop.ts#L158)):*
> ```XML
>               patch.validity_start,
>               stopWithRouteGraphData?.validity_start,
>             )!,
> ```

validityStart can be undefined as well, let's not have a no-non-null-assertion here

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/136)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @pallost)

___
*[src/components/map/stops/EditStopLayer.tsx, line 210 at r16](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NXr4s-Ie4GMbD1UbN:-N-RPsHTAnsBHLulAa_3:bdcv6l8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30f88d01a36da41eeab21140d6a95bf9267b09ee/src/components/map/stops/EditStopLayer.tsx#L210)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe let's not create a separate state variable for this: conflicts are already stored within the editChanges state
</blockquote></details>

Good point.
___
*[src/components/map/stops/EditStopLayer.tsx, line 275 at r16](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NYLfmCF58MKewguTe:-N-RPuQfE0oh-Q_y-WHs:b-qrjabz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30f88d01a36da41eeab21140d6a95bf9267b09ee/src/components/map/stops/EditStopLayer.tsx#L275)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it would be clearer if this was also behind a conditional render:
```
{editChanges.conflicts && <ConflictResolverModal/>}
```
</blockquote></details>

As you wish
___
*[src/hooks/stops/useEditStop.ts, line 101 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-Mzo9iXy2WkhUrG7cloL:-N-RKQ6gD27wgbxnVZKR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L101)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

looks good!
</blockquote></details>

Done.
___
*[src/hooks/stops/useEditStop.ts, line 105 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-MzoCOVJ9vaFgqCdhINA:-N-RKRgC5Qodx1CTLMAL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6785602dfb39366cad9c278f46cad5cb4cd64592/src/hooks/stops/useEditStop.ts#L105)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

nope, I just didn't get your point
</blockquote></details>

Done.
___
*[src/hooks/stops/useEditStop.ts, line 158 at r16](https://reviewable.io/reviews/hsldevcom/jore4-ui/136#-N-NZmqq-WdII7xKziQp:-N-RQ4Af9dmNJuw9K75Q:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30f88d01a36da41eeab21140d6a95bf9267b09ee/src/hooks/stops/useEditStop.ts#L158)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

validityStart can be undefined as well, let's not have a no-non-null-assertion here
</blockquote></details>

Done.

**Comment by tk-vincit** [comment]
Related e2e tests fixed in https://github.com/HSLdevcom/jore4-robot/pull/22

**Pull request merged**
