### PR TITLE
Visual link stop to road

### PR DESCRIPTION
**Pull request by culka**
Create a visual link between stop when selecting it and when adding a new stop on the map.

#Resolves HSLdevcom/jore4#698

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/315)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/315)* status: 0 of 10 files reviewed, 13 unresolved discussions (waiting on @culka and @tk-vincit)

___
*[`ui/src/components/map/mapUtils.ts` line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAhyWlX36GB4QWmUQyK:-NAhyWlX36GB4QWmUQyL:b-4957rp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/mapUtils.ts#L11)):*
> ```XML
>     map.removeLayer(id);
>   }
>   // when route is created with map.addLayer, corresponding
> ```

Does this comment belong now to new "removeRoute" function?
___
*[`ui/src/components/map/mapUtils.ts` line 55 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAhyhGX8BRzUSN3EeM0:-NAhyhGY4Vrgvh0kZP2j:b-vn6uhx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/mapUtils.ts#L55)):*
> ```XML
> 
> export const geometryLineBetweenPoints = (
>   first: number[],
> ```

I guess we rather want to type these as `GeoJSON.Position`. Currently it was difficult to understand meaning of these parameters.
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi-rLf08ZYhyIVUXzb:-NAi-rLf08ZYhyIVUXzc:b1gxeew) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/CreateStopMarker.tsx#L10)):*
> ```XML
> 
> interface Props {
>   cursorLocation?: (x: number, y: number) => void;
> ```

Maybe better function signature would be: `(coords: Coords) => void`. Then it would be self-evident which is  x and which y.
See:
`cursorLocation(10, 15)` vs `cursorLocation({ x: 10, y: 15 })`
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAhyq5A3AQ6VK_beJ_p:-NAhyq5A3AQ6VK_beJ_q:b-lr7c49) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/CreateStopMarker.tsx#L13)):*
> ```XML
> }
> export const CreateStopMarker = ({
>   cursorLocation = undefined,
> ```

No need to pass explicit `= undefined` default value as it is default behaviour anyway.
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi-EvA-QHPCcEefRRI:-NAi-EvA-QHPCcEefRRJ:bi7hsx2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/CreateStopMarker.tsx#L27)):*
> ```XML
>     const y = e.clientY - (containerBoundingBox?.top || 0);
> 
>     cursorLocation?.(x, y);
> ```

I don't understand name of this prop. This seems to be callback function and react convention would be to call it **on**Something, e.g. `onMouseMove`. `onMouseMove` is already used, but maybe this could be `onMouseMoved` or `onCursorMove` or something like that.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi4Qtj23HK5HE8fk1P:-NAi4Qtj23HK5HE8fk1Q:b-a1pas7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L1)):*
> ```XML
> import { point, Feature, LineString } from '@turf/helpers';
> ```

This file is named like component (starts with capital letter) and locatid inside `components` directory, but I don't see any component definitions in this file. I think this should rather be e.g. in `ui/src/utils/map/stopToInfraConnection` or something like that. OK, seems like we also have `ui/src/components/map/mapUtils.ts` but it doesn't belong under `components` either...
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi1CpL5-wjnUsJSHWD:-NAi1CpL5-wjnUsJSHWE:bvpn6r3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L20)):*
> ```XML
> const findFeaturesForLayerWithRadius = (
>   map: MaplibreGLMap,
>   layer: string,
> ```

Don't understand this parameter. Should this be `layerId` or `layerName` or  something like that? I have no idea, but at least it is clear that layer itself is something else than `string`
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi0_rG9-RERcTSHS5C:-NAi0_rG9-RERcTSHS5D:b-1e31kv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L21)):*
> ```XML
>   map: MaplibreGLMap,
>   layer: string,
>   x: number,
> ```

`x` and `y` are logically bound together so they should be passed inside object.

You can move `Coords` type definition from `ui/src/components/map/stops/CreateStopMarker.tsx` to `ui/src/types/index.ts` and import it where needed.



_Code quote:_
```XML
  x: number,
  y: number,
```
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi1qY55j5YCUhreVcu:-NAi1qY55j5YCUhreVcv:b-nvzhry) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L37)):*
> ```XML
> };
> 
> export const removeStopToInfraConnection = (map: MaplibreGLMap) => {
> ```

`removeStopFromInfraConnection`?
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 80 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi3TL96W5SwwT_wcHL:-NAi3TL96W5SwwT_wcHM:b-v7gm05) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L80)):*
> ```XML
> export const drawConnectionToClosestRoad = (
>   map: MaplibreGLMap,
>   x: number,
> ```

x and y are logically coupled and should be passed inside object



_Code quote:_
```XML
  x: number,
  y: number,
```
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 83 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi3ZIu76FddixxYA1s:-NAi3ZIu76FddixxYA1t:bb1xfh5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L83)):*
> ```XML
>   y: number,
> ) => {
>   const searchRadius = 100;
> ```

If you know what unit this is, please mention it in variable name: `searchRadiusInMeters` or at least with comment `// meters`. I assumed that this is meters, but have no idea
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 84 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi2Azs0ZWmQopMihTc:-NAi2Azs0ZWmQopMihTd:bwf52sr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L84)):*
> ```XML
> ) => {
>   const searchRadius = 100;
>   const roadLayer = 'digiroad_r_links';
> ```

roadLayerId? roadLayerName?
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 93 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi3qx913O4Xh4vGP10:-NAi3qx913O4Xh4vGP11:biztr58) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L93)):*
> ```XML
>   );
> 
>   if (features.length > 0) {
> ```

JS protip: `>0` is not needed, is more idiomatic JS and avoid potential bug where `>` might be the wrong way around: `<`. Anyway, if you find this more readable this is OK for me.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 94 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi2Mmx5_XdY5GWLxVJ:-NAi2Mmx5_XdY5GWLxVK:b-u2xaq8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L94)):*
> ```XML
> 
>   if (features.length > 0) {
>     // convert cursor location from pixel coordinates to lon/lat
> ```

lon -> lng
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 105 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi2bCr5O-YMB3NeTbv:-NAi2bCr5O-YMB3NeTbw:bwpnmcq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L105)):*
> ```XML
>     // find the nearest network connection
>     const nearestLine = linesWithDistance.reduce((prev, next) => {
>       return prev.distance < next.distance ? prev : next;
> ```

`{ return ...; } ` -> `( ... )` to be consistent with previous `linesWithDistance` definition

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/315)* status: 0 of 13 files reviewed, 13 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi-rLf08ZYhyIVUXzb:-NApaMT8-nKnxiaI7Rl8:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/CreateStopMarker.tsx#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Maybe better function signature would be: `(coords: Coords) => void`. Then it would be self-evident which is  x and which y.
See:
`cursorLocation(10, 15)` vs `cursorLocation({ x: 10, y: 15 })`
</blockquote></details>

Done.
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAhyq5A3AQ6VK_beJ_p:-NApaGcJ0IUF-ykwXeFR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/CreateStopMarker.tsx#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

No need to pass explicit `= undefined` default value as it is default behaviour anyway.
</blockquote></details>

Done.
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi-EvA-QHPCcEefRRI:-NApaGyxEZ_p-UeFGRMK:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/CreateStopMarker.tsx#L27)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand name of this prop. This seems to be callback function and react convention would be to call it **on**Something, e.g. `onMouseMove`. `onMouseMove` is already used, but maybe this could be `onMouseMoved` or `onCursorMove` or something like that.
</blockquote></details>

Done.
___
*[`ui/src/components/map/mapUtils.ts` line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAhyWlX36GB4QWmUQyK:-NApZqpL4DimuT3G1ncC:brx2wlh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/mapUtils.ts#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Does this comment belong now to new "removeRoute" function?
</blockquote></details>

No, but it is not strictly correct currently, replaced word 'route' with 'layer'
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi4Qtj23HK5HE8fk1P:-NApfgkU37AU2zXhqkMo:bw3kejh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This file is named like component (starts with capital letter) and locatid inside `components` directory, but I don't see any component definitions in this file. I think this should rather be e.g. in `ui/src/utils/map/stopToInfraConnection` or something like that. OK, seems like we also have `ui/src/components/map/mapUtils.ts` but it doesn't belong under `components` either...
</blockquote></details>

This file was indeed split from mapUtils.ts when it grew beyond one function to draw the line. Moved them both to a better place.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi1CpL5-wjnUsJSHWD:-NApfPnGAFzkU4UHpMdX:b-mhqh3n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Don't understand this parameter. Should this be `layerId` or `layerName` or  something like that? I have no idea, but at least it is clear that layer itself is something else than `string`
</blockquote></details>

Yes, this is indeed the id of the layer. Clarified.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi0_rG9-RERcTSHS5C:-NApfKre12gyuDopKdFC:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`x` and `y` are logically bound together so they should be passed inside object.

You can move `Coords` type definition from `ui/src/components/map/stops/CreateStopMarker.tsx` to `ui/src/types/index.ts` and import it where needed.
</blockquote></details>

Done.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi1qY55j5YCUhreVcu:-NApb9bo7zKgUydfRygB:b-eia3s9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L37)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`removeStopFromInfraConnection`?
</blockquote></details>

StopToInfraConnection is what I imagined the line to be called, so it's what this function removes.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 80 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi3TL96W5SwwT_wcHL:-NApcKDMC9jAPcs6P8Gc:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L80)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

x and y are logically coupled and should be passed inside object
</blockquote></details>

Done.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 83 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi3ZIu76FddixxYA1s:-NApcbZJBS_8tnaYxmGY:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L83)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If you know what unit this is, please mention it in variable name: `searchRadiusInMeters` or at least with comment `// meters`. I assumed that this is meters, but have no idea
</blockquote></details>

Done.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 84 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi2Azs0ZWmQopMihTc:-NApd4bb8-lAY6RwuLOu:b-epxkx6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L84)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

roadLayerId? roadLayerName?
</blockquote></details>

Checking from the data, it's actually ID. Clarifried.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 93 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi3qx913O4Xh4vGP10:-NApdEQt-ZeZcw15ruF5:b7iqdjs) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L93)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

JS protip: `>0` is not needed, is more idiomatic JS and avoid potential bug where `>` might be the wrong way around: `<`. Anyway, if you find this more readable this is OK for me.
</blockquote></details>

It does actually pretty weird to cast existence, null and size > 0 into boolean by default.
___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 94 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi2Mmx5_XdY5GWLxVJ:-NApdn241FGYhzKUbE2D:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L94)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

lon -> lng
</blockquote></details>

Done.

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/315)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @culka and @tk-vincit)

___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi4Qtj23HK5HE8fk1P:-NBMPR6N1Vc0by0-65vd:b-vj25w7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L1)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

This file was indeed split from mapUtils.ts when it grew beyond one function to draw the line. Moved them both to a better place.
</blockquote></details>

This file doesn't include component definitions nor JSX(/TSX), so it should end with `.ts`, not `.tsx`.
___
*[`ui/src/utils/map/mapUtils.ts` line 54 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NBMR7lg8zN-kl6-RYmB:-NBMR7lg8zN-kl6-RYmC:b1ayj1p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2fdcda0af7f503660e98640b0f644eaf1bf47014/ui/src/utils/map/mapUtils.ts#L54)):*
> ```XML
> };
> 
> export const geometryLineBetweenPoints = (
> ```

"create(Geometry)LineBetweenPoints"? :shrug: Your choice, don't know what this should be called but now this sounds more like variable name than function name.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/315)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/map/stops/StopToInfraConnection.tsx` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NAi4Qtj23HK5HE8fk1P:-NBMg8Cb7kDSWgZGSbbR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/663f2c12be70b417bc56c1bacc350fcd3d4f55c9/ui/src/components/map/stops/StopToInfraConnection.tsx#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This file doesn't include component definitions nor JSX(/TSX), so it should end with `.ts`, not `.tsx`.
</blockquote></details>

Done.
___
*[`ui/src/utils/map/mapUtils.ts` line 54 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/315#-NBMR7lg8zN-kl6-RYmB:-NBMgMOf2ta3rWYGrM16:b-90gqlz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2fdcda0af7f503660e98640b0f644eaf1bf47014/ui/src/utils/map/mapUtils.ts#L54)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"create(Geometry)LineBetweenPoints"? :shrug: Your choice, don't know what this should be called but now this sounds more like variable name than function name.
</blockquote></details>

That's a valid point.

**Pull request merged**
