### PR TITLE
Add vehicle type to timetables

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`test-db-manager/src/queries/timetables.ts` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574#-NSAr7Oz4EjuqmtPAx8F:-NSAr7Oz4EjuqmtPAx8G:bilcpyi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0128c434f01af9975814f530e8a144b19d220237/test-db-manager/src/queries/timetables.ts#L10)):*
> ```XML
>     timetables {
>       timetables_vehicle_type_vehicle_type {
>         vehicle_type_id
> ```

Should we add the `hsl_id` to the query, so it can be used to choose precise vehicle_types when generating seed if needed.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx` line 79 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574#-NSAugt-EXK9RI3WBFLv:-NSAugt-EXK9RI3WBFLw:b17ydzn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9cf5fb059df3a71401e272a22ddedb786267670f/ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx#L79)):*
> ```XML
>           passingTime={passing}
>           vehicleTypeDescription={parseI18nField(
>             passingTime.vehicle_journey.block.vehicle_type?.description_i18n,
> ```

Shouldn't this `parseI18nField` be in VehicleJourneyPopover component?

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx` line 79 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574#-NSAugt-EXK9RI3WBFLv:-NSAwTY_AwSqmHRqYSFe:b-5in26k) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9cf5fb059df3a71401e272a22ddedb786267670f/ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx#L79)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Shouldn't this `parseI18nField` be in VehicleJourneyPopover component?
</blockquote></details>

Although I think I do understand also the reason for it to be here :D So actually up to you

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test-db-manager/src/queries/timetables.ts` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574#-NSAr7Oz4EjuqmtPAx8F:-NSFFOsrCVSQfAs7oKS5:b-r0ekxt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0128c434f01af9975814f530e8a144b19d220237/test-db-manager/src/queries/timetables.ts#L10)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should we add the `hsl_id` to the query, so it can be used to choose precise vehicle_types when generating seed if needed.
</blockquote></details>

We can add it at some point if we need to pick a specific vehicle type. Now that we just pick one random, I don't think there is a reason to add it as it is not used.
___
*[`ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx` line 79 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574#-NSAugt-EXK9RI3WBFLv:-NSFFazaAtfeChLdizd3:bj36w51) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9cf5fb059df3a71401e272a22ddedb786267670f/ui/src/components/timetables/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx#L79)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Although I think I do understand also the reason for it to be here :D So actually up to you
</blockquote></details>

I just thought vehicle journey popover is just a stupid component which does not need to know anything about translations, just display what it gets. So I would leave it like it is.

**Review by HenrikHartiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/574)* status: 0 of 9 files reviewed, all discussions resolved

**Pull request merged**
