### PR TITLE
Add tests that add timing places to stops

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#1046

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/createStop.cy.ts` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFAe4n8ROCWxNGzCxz:-NJFAe4n8ROCWxNGzCy-:b-oq9eur) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/createStop.cy.ts#L17)):*
> ```XML
>   manualCoordinatesLabel: 'TManual',
>   endDateLabel: 'TEndDate',
>   timingPlaceStopLabel: 'Timing place stop label',
> ```

"timingPlaceStopLabel" -> "timingPlaceLabel" for consistency with rest of these.
It is self-evident that it is "stop label" as this object is already called "testStopLabels".
___
*[`cypress/e2e/createStop.cy.ts` line 190 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFBbgh7BLje88h-aTZ:-NJFBbgh7BLje88h-aT_:b-x0sl8v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/createStop.cy.ts#L190)):*
> ```XML
>   );
> 
>   it(
> ```

Is this worth having own test case? Could we just fill`timingPlace` field in basic stop creation test?
___
*[`cypress/e2e/createStop.cy.ts` line 195 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFB4VA2rmBiNfCGjDk:-NJFB4VA2rmBiNfCGjDl:b-pvchw3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/createStop.cy.ts#L195)):*
> ```XML
>     { scrollBehavior: 'bottom', defaultCommandTimeout: 10000 },
>     () => {
>       const testTimingPlace = '1ALPKY';
> ```

I would add comment explaining where this comes from, as it seems like this can't be replaced with arbitrary string value.

Something like this?
`const testTimingPlace = '1ALPKY'; // This value comes from timing places sql seed data? 
___
*[`cypress/e2e/editStop.cy.ts` line 230 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFC03pCoAbx1YNrdHe:-NJFC03pCoAbx1YNrdHf:b-i9vv02) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/editStop.cy.ts#L230)):*
> ```XML
>     { scrollBehavior: 'bottom', defaultCommandTimeout: 10000 },
>     () => {
>       const testTimingPlace = '1ALATI';
> ```

It would be nice to have also here explanation about where this does come from. 

By the way, this test looks pretty much same as "Should move a stop on the map by changing the coordinates" test. Should we just add also this timing place input & corresponding assertion there?
___
*[`cypress/pageObjects/StopForm.ts` line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFCQ4ACYgqSB5nRjKD:-NJFCQ4ACYgqSB5nRjKE:b-gnnrxt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/pageObjects/StopForm.ts#L29)):*
> ```XML
>     this.getTimingPlaceDropdown()
>       .find('li')
>       .contains(`${timingPlaceName}`)
> ```

Same as `.contains(timingPlace)`, no need for template string

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

___
*[`cypress/e2e/createStop.cy.ts` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFAe4n8ROCWxNGzCxz:-NJFUrYQCpbttFSkTBBs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/createStop.cy.ts#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"timingPlaceStopLabel" -> "timingPlaceLabel" for consistency with rest of these.
It is self-evident that it is "stop label" as this object is already called "testStopLabels".
</blockquote></details>

Done.
___
*[`cypress/e2e/createStop.cy.ts` line 190 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFBbgh7BLje88h-aTZ:-NJFUtHa7Yvn177VUuYZ:bjl9ed3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/createStop.cy.ts#L190)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is this worth having own test case? Could we just fill`timingPlace` field in basic stop creation test?
</blockquote></details>

I think I would rather have this as a separate test for now at least just so that it is immediately clear what breaks if the test breaks. I don't think there will be a huge mass of similar tests.
___
*[`cypress/e2e/createStop.cy.ts` line 195 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFB4VA2rmBiNfCGjDk:-NJFVsa2138sgLz3f-gm:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/createStop.cy.ts#L195)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I would add comment explaining where this comes from, as it seems like this can't be replaced with arbitrary string value.

Something like this?
`const testTimingPlace = '1ALPKY'; // This value comes from timing places sql seed data? 
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 230 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFC03pCoAbx1YNrdHe:-NJFVxEC1PPxT06PCt6W:b61bexr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/editStop.cy.ts#L230)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

It would be nice to have also here explanation about where this does come from. 

By the way, this test looks pretty much same as "Should move a stop on the map by changing the coordinates" test. Should we just add also this timing place input & corresponding assertion there?
</blockquote></details>

I would prefer to have this as a separate test. Mashing several checks into one test feels too dirty.
___
*[`cypress/pageObjects/StopForm.ts` line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFCQ4ACYgqSB5nRjKD:-NJFWF0fB5EKqHvoBq6x:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/pageObjects/StopForm.ts#L29)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same as `.contains(timingPlace)`, no need for template string
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`cypress/e2e/editStop.cy.ts` line 230 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFC03pCoAbx1YNrdHe:-NJPqojTEzWmw9B7Yrqw:bahz59d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/editStop.cy.ts#L230)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I would prefer to have this as a separate test. Mashing several checks into one test feels too dirty.
</blockquote></details>

Now that this is a "edit stop info", I also think that we could combine this with the coordinate change test. 
___
*[`cypress/pageObjects/ChangeValidityForm.ts` line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJPpPCL7e0D4ug2UOrL:-NJPpPCL7e0D4ug2UOrM:b7hib9u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e82c7088c1ff2113961573436c83a15c5b86cbef/cypress/pageObjects/ChangeValidityForm.ts#L29)):*
> ```XML
>         cy.getByTestId('ChangeValidityForm::draftPriorityButton').should(
>           'have.class',
>           'text-white',
> ```

Hmm, not in the scope of this PR and this is fine for now, but I think we need to change the determination of this a little bit. Maybe add some 'selected' value to the options.
___
*[`cypress/pageObjects/ChangeValidityForm.ts` line 54 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJPqDz-7umS_86V4Ef-:-NJPqDz-7umS_86V4Ef0:biqug01) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e82c7088c1ff2113961573436c83a15c5b86cbef/cypress/pageObjects/ChangeValidityForm.ts#L54)):*
> ```XML
>     return cy
>       .getByTestId('ChangeValidityForm::startDateInput')
>       .clear()
> ```

What does this `clear()` addition do / why do we need it?

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/pageObjects/ChangeValidityForm.ts` line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJPpPCL7e0D4ug2UOrL:-NJPtwBdCQkKWOGbW2Si:b-vyby4l) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e82c7088c1ff2113961573436c83a15c5b86cbef/cypress/pageObjects/ChangeValidityForm.ts#L29)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, not in the scope of this PR and this is fine for now, but I think we need to change the determination of this a little bit. Maybe add some 'selected' value to the options.
</blockquote></details>

Yes, this was a bit hacky and unreliable way of getting the currently selected value. I'll add a TODO for this.
___
*[`cypress/pageObjects/ChangeValidityForm.ts` line 54 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJPqDz-7umS_86V4Ef-:-NJPu9e61PpKbpiQyvQr:b-tbjf4o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e82c7088c1ff2113961573436c83a15c5b86cbef/cypress/pageObjects/ChangeValidityForm.ts#L54)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

What does this `clear()` addition do / why do we need it?
</blockquote></details>

It clears the existing value from the field. Without clearing the field this would only work on an empty input field. When editing a stop there is already a value in the field and typing into it would append to that existing value.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/e2e/editStop.cy.ts` line 230 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJFC03pCoAbx1YNrdHe:-NJeH3gK5nqD7mYtHRK-:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4d8aee6b9b10e83328dda8b5cfb61a3070636995/cypress/e2e/editStop.cy.ts#L230)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Now that this is a "edit stop info", I also think that we could combine this with the coordinate change test. 
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`cypress/pageObjects/ChangeValidityForm.ts` line 54 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJPqDz-7umS_86V4Ef-:-NJQ-JuH0RnD1f9yvxdl:b5tk9wj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e82c7088c1ff2113961573436c83a15c5b86cbef/cypress/pageObjects/ChangeValidityForm.ts#L54)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

It clears the existing value from the field. Without clearing the field this would only work on an empty input field. When editing a stop there is already a value in the field and typing into it would append to that existing value.
</blockquote></details>

Ah right. Thanks
___
*[`cypress/pageObjects/Map.ts` line 57 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJidATf81Qz53N-TTjA:-NJidATf81Qz53N-TTjB:bvs80m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f7500ef78b6a44e8bf06154bf83a344f84556c72/cypress/pageObjects/Map.ts#L57)):*
> ```XML
>   }
> 
>   getStopByStopLabel(testStopLabel: string, priority = 'Standard') {
> ```

We don't need to use the string values, if we read the enum value with the priority value like so:
`Priority[priority]`. 

So this function can be changed to 
```
getStopByStopLabel(testStopLabel: string, priority = Priority.Standard) {
    return cy.getByTestId(
      `Map::Stops::stopMarker::${testStopLabel}_${Priority[priority]}`,
    );
  }
```
(Then you can call this for example like this: `.getStopByStopLabel(updatedStopInfo.label, updatedStopInfo.priority)`
And now that it also has priority as parameter, I would maybe change the name of this function in to `getStopByLabelAndPriority(...)`

We could also debate if we want to give this function a default value, or should we enforce the priority parameter as well? What do you think? Would it be more clear if it is also enforced?

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/pageObjects/Map.ts` line 57 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJidATf81Qz53N-TTjA:-NJj2-hSCU7PcRIIsusd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f7500ef78b6a44e8bf06154bf83a344f84556c72/cypress/pageObjects/Map.ts#L57)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

We don't need to use the string values, if we read the enum value with the priority value like so:
`Priority[priority]`. 

So this function can be changed to 
```
getStopByStopLabel(testStopLabel: string, priority = Priority.Standard) {
    return cy.getByTestId(
      `Map::Stops::stopMarker::${testStopLabel}_${Priority[priority]}`,
    );
  }
```
(Then you can call this for example like this: `.getStopByStopLabel(updatedStopInfo.label, updatedStopInfo.priority)`
And now that it also has priority as parameter, I would maybe change the name of this function in to `getStopByLabelAndPriority(...)`

We could also debate if we want to give this function a default value, or should we enforce the priority parameter as well? What do you think? Would it be more clear if it is also enforced?
</blockquote></details>

Done.

**Review by HenrikHartiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`cypress/e2e/editStop.cy.ts` line 139 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJna8hh9GlncggEgpcG:-NJna8hh9GlncggEgpcH:b-yjuy2e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ede46a2b4e4a662a336e857107147370d85e172f/cypress/e2e/editStop.cy.ts#L139)):*
> ```XML
> 
>       map
>         .getStopByStopLabelAndPriority(stops[0].label, Priority.Standard)
> ```

`stops[0].priority`? Same goes for all in this file

**Review by HenrikHartiala — APPROVED** [review]
Nice! Looks good to me :+1: 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-:-NJniRbN0Ss-omL0r-Om:b5svmbx)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @sr-vala and @tk-vincit)

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 1 of 13 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @sr-vala)

___
*[`cypress/e2e/createStop.cy.ts` line 192 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtDcswC-D9RS5MHb-I:-NJtDcswC-D9RS5MHb-J:b-63rgpt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L192)):*
> ```XML
>     { scrollBehavior: 'bottom', defaultCommandTimeout: 10000 },
>     () => {
>       // This value comes from timing places sql seed data
> ```

This comment is not needed anymore. :slightly_smiling_face: 
___
*[`cypress/e2e/createStop.cy.ts` line 196 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtBwTp84CAmeg2k9og:-NJtBwTp84CAmeg2k9oh:b-maehuf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L196)):*
> ```XML
>         stopFormInfo: {
>           label: testStopLabels.timingPlaceLabel,
>           timingPlace: String(timingPlaces[0].label),
> ```

`String()` casting shouldn't be needed. That breaks type safety and well, is just wrong way to do this here. If the reason to do this was because timingPlaces[0].label can be undefined too, you can refactor this to this:

```
// seed timing places should always have label defined
          // eslint-disable-next-line @typescript-eslint/no-non-null-assertion 
          timingPlace: timingPlaces[0].label!,
```
This breaks type safety too, but at least explains what is going on here.
___
*[`cypress/e2e/createStop.cy.ts` line 221 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtCTRA5SIxwsvUUnUt:-NJtCTRA5SIxwsvUUnUu:b-x45hdn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L221)):*
> ```XML
>       stopForm
>         .getTimingPlaceDropdown()
>         .should('contain', String(timingPlaces[0].label));
> ```

String casting not needed.
___
*[`cypress/e2e/editStop.cy.ts` line 201 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtDSI26x6sfKq6R9vk:-NJtDSI26x6sfKq6R9vl:b-qpbhw2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/editStop.cy.ts#L201)):*
> ```XML
>         label: 'Add timing place stop label',
>         // This timing place value comes from timing places sql seed data
>         timingPlace: String(timingPlaces[0].label),
> ```

Same here, string casting shouldn't be used as a workaround for non-null assertion. Please also remove expired comment above.
___
*[`cypress/e2e/editStop.cy.ts` line 231 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtESLPD3boNwkqfv0v:-NJtESLPD3boNwkqfv0w:bdvapgt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/editStop.cy.ts#L231)):*
> ```XML
>         .getStopByStopLabelAndPriority(
>           updatedStopInfo.label,
>           updatedStopInfo.priority as Priority,
> ```

Also this "as" casting is wrong way to do non-null assertion. Tried if this could be fixed "easily" and it starts bit of domino effect of changes that would need to be done in order to fix this, so you can just use non-null assertion `!` here  (`updatedStopInfo.priority!`), disable eslint and add short comment explaining why it had to be done.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 1 of 13 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/e2e/createStop.cy.ts` line 192 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtDcswC-D9RS5MHb-I:-NJtOCNP73_89hNaf1ic:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L192)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This comment is not needed anymore. :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[`cypress/e2e/createStop.cy.ts` line 196 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtBwTp84CAmeg2k9og:-NJtOBcF0PQxCjQ8oaxj:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L196)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`String()` casting shouldn't be needed. That breaks type safety and well, is just wrong way to do this here. If the reason to do this was because timingPlaces[0].label can be undefined too, you can refactor this to this:

```
// seed timing places should always have label defined
          // eslint-disable-next-line @typescript-eslint/no-non-null-assertion 
          timingPlace: timingPlaces[0].label!,
```
This breaks type safety too, but at least explains what is going on here.
</blockquote></details>

Done.
___
*[`cypress/e2e/createStop.cy.ts` line 221 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtCTRA5SIxwsvUUnUt:-NJtOARG85QoEcKBDpkT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L221)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

String casting not needed.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 139 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJna8hh9GlncggEgpcG:-NJtO9Tl8vf6fDiNTYOr:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ede46a2b4e4a662a336e857107147370d85e172f/cypress/e2e/editStop.cy.ts#L139)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

`stops[0].priority`? Same goes for all in this file
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 201 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtDSI26x6sfKq6R9vk:-NJtO6vx1oNGtNm6dbdd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/editStop.cy.ts#L201)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same here, string casting shouldn't be used as a workaround for non-null assertion. Please also remove expired comment above.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 231 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtESLPD3boNwkqfv0v:-NJtO5ZVD5ATGykJxsEX:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/editStop.cy.ts#L231)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Also this "as" casting is wrong way to do non-null assertion. Tried if this could be fixed "easily" and it starts bit of domino effect of changes that would need to be done in order to fix this, so you can just use non-null assertion `!` here  (`updatedStopInfo.priority!`), disable eslint and add short comment explaining why it had to be done.
</blockquote></details>

Done.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

___
*[`cypress/e2e/createStop.cy.ts` line 192 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtDcswC-D9RS5MHb-I:-NJtiHp54yebfeftXJKF:bjkq5lj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L192)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not sure if my reviewable is doing reviewable things, but for me it seems like the comment is still in place.
___
*[`cypress/e2e/editStop.cy.ts` line 231 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtESLPD3boNwkqfv0v:-NJtiguJDrURHfUFWLYc:bsq3h72) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/editStop.cy.ts#L231)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This comment seems to be a copy pasta. Here we are non-null-asserting priority, because it is definitely defined above.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/e2e/createStop.cy.ts` line 192 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtDcswC-D9RS5MHb-I:-NJtmBQo2m4Ms6GYYHOm:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/createStop.cy.ts#L192)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Not sure if my reviewable is doing reviewable things, but for me it seems like the comment is still in place.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 231 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/425#-NJtESLPD3boNwkqfv0v:-NJtmCQQ842EaaVQTSOF:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6694d5127422fedbdabb5b037a98fb0e4ffc324e/cypress/e2e/editStop.cy.ts#L231)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This comment seems to be a copy pasta. Here we are non-null-asserting priority, because it is definitely defined above.
</blockquote></details>

Done.

**Review by HenrikHartiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/425)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

**Pull request merged**
