### PR TITLE
Display error toast if route geometry is too far from infralinks

### PR DESCRIPTION
**Pull request by eleksi**
Resolves HSLdevcom/jore4#963

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/336)

### CODE REVIEW

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/336)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 139 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NBuOx3U0RugWY5eOisG:-NBuOx3U0RugWY5eOisH:b-2pxag0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7763b9204b4ca83806296d24975283c925f74c3/ui/src/components/map/routes/DrawRouteLayer.tsx#L139)):*
> ```XML
>   const onUpdateRouteGeometry = useCallback(
>     async (snappingLineFeature: LineStringFeature) => {
>       try {
> ```

It feels stupid wrapping this whole thing in try-catch. Any better ideas?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/336)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 139 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NBuOx3U0RugWY5eOisG:-NCdyIa80QTpFXUXRBkz:b-wtesuz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7763b9204b4ca83806296d24975283c925f74c3/ui/src/components/map/routes/DrawRouteLayer.tsx#L139)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

It feels stupid wrapping this whole thing in try-catch. Any better ideas?
</blockquote></details>

well, you should only wrap code here that CAN throw exceptions. If I understand correctly, here it's only the getInfraLinksWithStopsForGeometry function
___
*[`ui/src/locales/en-US/common.json` line 211 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NCdzBum20T12t5XWE2M:-NCdzBun-J0Z0i6HOMyS:bnzw13q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/13e6791d14ffee38956196773feca661068b8799/ui/src/locales/en-US/common.json#L211)):*
> ```JSON
>     "saveFailed": "Something went wrong",
>     "leaveMultipleHandles": "Cannot delete snap point(s)! You should leave at least two of them.",
>     "tooFarFromInfrastructureLink": "Make sure each point in route geometry is close enough to the road network. Check coverage of the road network along the route, if necessary."
> ```

Wouldn't it be enough if you just said: "Drawn route is too far from infrastructure network"?

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/336)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 139 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NBuOx3U0RugWY5eOisG:-NCtitDSAbfCUVsjuBgX:bdrsl4q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7763b9204b4ca83806296d24975283c925f74c3/ui/src/components/map/routes/DrawRouteLayer.tsx#L139)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

well, you should only wrap code here that CAN throw exceptions. If I understand correctly, here it's only the getInfraLinksWithStopsForGeometry function
</blockquote></details>

Yes, but if pretty much all the code below the throwing code depends on that line, we have to wrap them as well?

Tried to go around wrapping the almost the entire onUpdateRouteGeometry function by using lets and returning if they are empty. Not pretty, but is it better than wrapping the entire thing in try-catch? At least diff is cleaner.
___
*[`ui/src/locales/en-US/common.json` line 211 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NCdzBum20T12t5XWE2M:-NCthv5nDfuVvukvsoT5:b-6vynbr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/13e6791d14ffee38956196773feca661068b8799/ui/src/locales/en-US/common.json#L211)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Wouldn't it be enough if you just said: "Drawn route is too far from infrastructure network"?
</blockquote></details>

Error message is from design.

I guess in case the selected point is inside infrastructure network but too far from any single link, your suggestion would not be too clear.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/336)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 139 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NBuOx3U0RugWY5eOisG:-NCyB-s18IWDCQelHzZG:b-ubj6d6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7763b9204b4ca83806296d24975283c925f74c3/ui/src/components/map/routes/DrawRouteLayer.tsx#L139)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Yes, but if pretty much all the code below the throwing code depends on that line, we have to wrap them as well?

Tried to go around wrapping the almost the entire onUpdateRouteGeometry function by using lets and returning if they are empty. Not pretty, but is it better than wrapping the entire thing in try-catch? At least diff is cleaner.
</blockquote></details>

you should just return from the function as you did so, that's a good way to handle it :+1: 
___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 180 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NCyBJsa8sSeXS97ToIS:-NCyBJsa8sSeXS97ToIT:br7knf3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/87e04d7398184f3f7bf1bacb1fa6043675ff9098/ui/src/components/map/routes/DrawRouteLayer.tsx#L180)):*
> ```XML
>       }
> 
>       if (!infraLinksWithStops) return;
> ```

just put the return directly into the catch block, and move the loading indicator to the finally block, like this:

```
      } catch (err) {
        if (err instanceof MapMatchingNoSegmentError) {
          showDangerToast(t('errors.tooFarFromInfrastructureLink'));
        }
        return;
      } finally {
        setIsLoading(false);
      }
```
___
*[`ui/src/locales/en-US/common.json` line 211 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/336#-NCdzBum20T12t5XWE2M:-NCyBoI5ElzTF0sIfZvD:b-nilsg4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/13e6791d14ffee38956196773feca661068b8799/ui/src/locales/en-US/common.json#L211)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Error message is from design.

I guess in case the selected point is inside infrastructure network but too far from any single link, your suggestion would not be too clear.
</blockquote></details>

sure, let's go with this then :+1:

**Pull request merged**
