### PR TITLE
Add line and route search tests and resources

### PR DESCRIPTION
**Pull request by sr-vala**
Simple line and route search tests, resources and testIds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @pallost and @sr-vala)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkMCiF-A6hxy91A9Rm):*
This should be squashed to previous commit
___
*[`cypress/pageObjects/RouteAndLineSearchForm.ts` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkOJ1w-GTACCEjq2oK:-NBkOJ1w-GTACCEjq2oL:bma2rmu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/pageObjects/RouteAndLineSearchForm.ts#L1)):*
> ```XML
> export class RouteAndLineSearchForm {
> ```

We don't have component called `RouteAndLineSearchForm` and this doesn't focus on `SearchInput` component itself as this has also getters for results tables.

I would either:
- Split this into two PageObjects, `SearchResultsPage` and `RoutesAndLinesPage` so that this could have clear real-world counterpart and clear responsibilites
- Remove "Form" from the name of this component to make naming clearer
___
*[`ui/src/components/routes-and-lines/main/LinesList.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkNBOf0LuC0VpHUNFI:-NBkNBOf0LuC0VpHUNFJ:be5hl04) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/ui/src/components/routes-and-lines/main/LinesList.tsx#L10)):*
> ```XML
> 
> const testIds = {
>   table: 'LinesTable',
> ```

Please see our guideline for naming test id's: https://github.com/HSLdevcom/jore4-ui#test-ids
According to that testId of given element should be something like `LinesList::table`
___
*[`ui/src/components/routes-and-lines/main/RoutesList.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkNbxM5eIhTYSWg4PY:-NBkNbxM5eIhTYSWg4PZ:b4iw6i2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/ui/src/components/routes-and-lines/main/RoutesList.tsx#L10)):*
> ```XML
> 
> const testIds = {
>   table: 'RoutesTable',
> ```

`RoutesList::table`?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @pallost, @sr-vala, and @tk-vincit)

___
*[`cypress/e2e/searchRoutesAndLines.cy.ts` line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkX3dW7gUj0i9R4jbJ:-NBkX3dW7gUj0i9R4jbK:b-2moeu1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/e2e/searchRoutesAndLines.cy.ts#L6)):*
> ```XML
>   let routeSearchForm: RouteAndLineSearchForm;
>   beforeEach(() => {
>     routeSearchForm = new RouteAndLineSearchForm();
> ```

would be nice if instead of relying on the pre-existing seed data, you'd actually set up the data yourself. There's an example in routeStops.ts
___
*[`cypress/e2e/searchRoutesAndLines.cy.ts` line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkXNmM7Aj8PHF1d1V9:-NBkXNmM7Aj8PHF1d1VA:bur0tib) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/e2e/searchRoutesAndLines.cy.ts#L12)):*
> ```XML
>   });
>   it('Searches line with exact ID', () => {
>     routeSearchForm.getRouteSearchFormSearchField().type('1{enter}');
> ```

you should have at least 3 lines pre-entered to the database for this test: line 1, line 10, line 2.
this test should check that only line 1 is found from the search results, 10 and 2 are not
___
*[`cypress/e2e/searchRoutesAndLines.cy.ts` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkXbXV1DczbiQ7pWD0:-NBkXbXV1DczbiQ7pWD1:b-4mjvi2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/e2e/searchRoutesAndLines.cy.ts#L20)):*
> ```XML
> 
>   it('Searches line with asterisk', () => {
>     routeSearchForm.getRouteSearchFormSearchField().type('1*{enter}');
> ```

you should have at least 3 lines pre-entered to the database for this test: line 1, line 10, line 2.
this test should check that both line 1 and 10 are found from the search results, 2 is not

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkMCiF-A6hxy91A9Rm):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This should be squashed to previous commit
</blockquote></details>

Done.
___
*[`cypress/e2e/searchRoutesAndLines.cy.ts` line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkX3dW7gUj0i9R4jbJ:-NBq572P9d0CqVCptPLY:b-6vlf8v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/e2e/searchRoutesAndLines.cy.ts#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

would be nice if instead of relying on the pre-existing seed data, you'd actually set up the data yourself. There's an example in routeStops.ts
</blockquote></details>

Used the same test data generation as in routeStops.cy.ts
___
*[`cypress/e2e/searchRoutesAndLines.cy.ts` line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkXNmM7Aj8PHF1d1V9:-NBq5ff8CDcoLhz_7wGT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/e2e/searchRoutesAndLines.cy.ts#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should have at least 3 lines pre-entered to the database for this test: line 1, line 10, line 2.
this test should check that only line 1 is found from the search results, 10 and 2 are not
</blockquote></details>

Done.
___
*[`cypress/e2e/searchRoutesAndLines.cy.ts` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkXbXV1DczbiQ7pWD0:-NBq5gXMC0ubmTByoK14:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/e2e/searchRoutesAndLines.cy.ts#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should have at least 3 lines pre-entered to the database for this test: line 1, line 10, line 2.
this test should check that both line 1 and 10 are found from the search results, 2 is not
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteAndLineSearchForm.ts` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkOJ1w-GTACCEjq2oK:-NBq5hqN9fAe1Sidy7Qk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/cypress/pageObjects/RouteAndLineSearchForm.ts#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We don't have component called `RouteAndLineSearchForm` and this doesn't focus on `SearchInput` component itself as this has also getters for results tables.

I would either:
- Split this into two PageObjects, `SearchResultsPage` and `RoutesAndLinesPage` so that this could have clear real-world counterpart and clear responsibilites
- Remove "Form" from the name of this component to make naming clearer

</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/main/LinesList.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkNBOf0LuC0VpHUNFI:-NBq5lKJ1Z6qDBoGXw02:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/ui/src/components/routes-and-lines/main/LinesList.tsx#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please see our guideline for naming test id's: https://github.com/HSLdevcom/jore4-ui#test-ids
According to that testId of given element should be something like `LinesList::table`
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/main/RoutesList.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBkNbxM5eIhTYSWg4PY:-NBq5mDa2sM5ztUqkdWr:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c1421ad94bfbb8d9b3e486df45e05b46a72dc755/ui/src/components/routes-and-lines/main/RoutesList.tsx#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`RoutesList::table`?
</blockquote></details>

Done.

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @pallost, @sr-vala, and @tk-vincit)

___
*[`cypress/e2e/searchRoutesAndLines.cy.ts` line 32 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBv3q-D7qoQu_zRc7Pz:-NBv3q-EBw3EQwljkZsc:bcddq83) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/627f1e05e971c5b15f80b6c7ef54771076d828d2/cypress/e2e/searchRoutesAndLines.cy.ts#L32)):*
> ```XML
> };
> 
> describe('Verify route and line search works', () => {
> ```

Not 100% sure about my english, but maybe "Verify _that_ route ..."? 
___
*[`cypress/pageObjects/RoutesAndLinesSearchResultsPage.ts` line 1 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBv3Jq34saN8EgCKUbR:-NBv3Jq49Rdf-9m7qWVS:b-tkfxif) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/627f1e05e971c5b15f80b6c7ef54771076d828d2/cypress/pageObjects/RoutesAndLinesSearchResultsPage.ts#L1)):*
> ```XML
> export class RoutesAndLinesSearchResultsPage {
> ```

I think this PageObject corresponds component called `SearchResultPage`, so let's call this that (without RoutesAndLines prefix) to make it self-evident which page this models.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`cypress/pageObjects/RoutesAndLinesSearchResultsPage.ts` line 1 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBv3Jq34saN8EgCKUbR:-NBvUHsK5nPyjmYuIsM-:b2fzba6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/627f1e05e971c5b15f80b6c7ef54771076d828d2/cypress/pageObjects/RoutesAndLinesSearchResultsPage.ts#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I think this PageObject corresponds component called `SearchResultPage`, so let's call this that (without RoutesAndLines prefix) to make it self-evident which page this models.
</blockquote></details>

The component is located in components/routes-and-lines/search/, and that gives it context which does not exist in the Cypress folder structure. Either we should have similar structure in Cypress or use more specific naming. SearchResultPage is too vague in the Cypress context.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`cypress/pageObjects/RoutesAndLinesSearchResultsPage.ts` line 1 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-NBv3Jq34saN8EgCKUbR:-NC-pM-18jsUzJYvvM-Y:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/627f1e05e971c5b15f80b6c7ef54771076d828d2/cypress/pageObjects/RoutesAndLinesSearchResultsPage.ts#L1)):*
<details><summary><i>Previously, sr-vala wrote…</i></summary><blockquote>

The component is located in components/routes-and-lines/search/, and that gives it context which does not exist in the Cypress folder structure. Either we should have similar structure in Cypress or use more specific naming. SearchResultPage is too vague in the Cypress context.
</blockquote></details>

Done.

**Review by tk-vincit — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 11 files at r5, 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332#-:-NC4msGyCpfYiJCT5uPa:b-uwkowd)* status: 13 of 14 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/332)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

**Pull request merged**
