### PR TITLE
Add stop place state and types to seed data and basic details

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795)

### CODE REVIEW

**Review by culka — COMMENTED** [review]
Data model looks exactly as it was discussed :+1: 

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-:-NtRI3V6C8tqF0DeKf4h:b-1vhaht)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`test-db-manager/src/datasets/stopRegistry/stopPlaces.ts` line 153 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-Ntoakce3YK_rwWR1ljw:-Ntoakce3YK_rwWR1ljx:b-rspq31) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f0a7ada0830df03038b5046eded594da971c0ff/test-db-manager/src/datasets/stopRegistry/stopPlaces.ts#L153)):*
> ```XML
>         },
>         seedStopPlace.stopState && {
>           key: 'state',
> ```

I was just wondering if the more precise "stopState" would be better key here. Just to distinguish it from the address conxtext. I mean we do have `postalCode` and `address` coming in the keyValues as well, so next to those `state` is ambiguous
___
*[`test-db-manager/src/datasets/stopRegistry/stopPlaces.ts` line 214 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-Ntobnob7r-G4XSQJu-g:-Ntobnob7r-G4XSQJu-h:bvz6b64) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f0a7ada0830df03038b5046eded594da971c0ff/test-db-manager/src/datasets/stopRegistry/stopPlaces.ts#L214)):*
> ```XML
>     interchangeWeighting:
>       StopRegistryInterchangeWeightingType.RecommendedInterchange,
>     stopState: 'OutOfOperation',
> ```

This doesnt matter that much, but would probably use InOperation here, since our software logic does not yet support this `out of operation` state by any means, and might be confusing.
___
*[`ui/src/components/stop-registry/stops/stop-details/utils.spec.ts` line 3 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-Ntodn0a6MpBV74gBBPt:-Ntodn0a6MpBV74gBBPu:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4b198cd381f50a12c3a4b7d6bf5c3e9989381904/ui/src/components/stop-registry/stops/stop-details/utils.spec.ts#L3)):*
> ```XML
> import { translateStopTypes } from './utils';
> 
> describe('Stop registry utils', () => {
> ```

:+1:

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`test-db-manager/src/datasets/stopRegistry/stopPlaces.ts` line 153 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-Ntoakce3YK_rwWR1ljw:-NtokopBCTRaiw87fe1k:bs8ndxj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f0a7ada0830df03038b5046eded594da971c0ff/test-db-manager/src/datasets/stopRegistry/stopPlaces.ts#L153)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I was just wondering if the more precise "stopState" would be better key here. Just to distinguish it from the address conxtext. I mean we do have `postalCode` and `address` coming in the keyValues as well, so next to those `state` is ambiguous
</blockquote></details>

Ping @culka

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`test-db-manager/src/datasets/stopRegistry/stopPlaces.ts` line 214 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-Ntobnob7r-G4XSQJu-g:-NtolhaFBwV2SeJLitrA:b8najx7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f0a7ada0830df03038b5046eded594da971c0ff/test-db-manager/src/datasets/stopRegistry/stopPlaces.ts#L214)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This doesnt matter that much, but would probably use InOperation here, since our software logic does not yet support this `out of operation` state by any means, and might be confusing.
</blockquote></details>

I've been using same values as we have in Figma for all fields in this stop, thus `OutOfOperation`.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @culka and @HenrikHartiala)

___
*[`test-db-manager/src/datasets/stopRegistry/stopPlaces.ts` line 153 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-Ntoakce3YK_rwWR1ljw:-NtpWbxj72lA6Reb_5M2:b-f9zopo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f0a7ada0830df03038b5046eded594da971c0ff/test-db-manager/src/datasets/stopRegistry/stopPlaces.ts#L153)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Ping @culka
</blockquote></details>

Discussed elsewhere, renamed.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`test-db-manager/src/datasets/stopRegistry/stopPlaces.ts` line 153 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/795#-Ntoakce3YK_rwWR1ljw:-NtpnNVXDF4L6N2JKiqt:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f0a7ada0830df03038b5046eded594da971c0ff/test-db-manager/src/datasets/stopRegistry/stopPlaces.ts#L153)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Discussed elsewhere, renamed.
</blockquote></details>

Thanks!

**Pull request merged**
