### PR TITLE
Add digitransit api key

### PR DESCRIPTION
**Pull request by culka**
Add a digitransit api key which is needed to display map tiles

Resolves https://github.com/HSLdevcom/jore4/issues/1241

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
I think it would be helpful if you added a subsection about map tiles (as a dependency and how it is obtained) to the `README.md` file, because to a new member of the team this might look like wizardry what you're doing here.

Map tiles are usually not that complicated, but installing them now involves quite a few little pieces here and there.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-:-NXOmW0zEC2G_BLjFiEk:b3vlm0n)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`ui/package.json` line 38 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NXOluws9LfnNrrqnSai:-NXOluws9LfnNrrqnSaj:b8smwdt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/de5d0a3d80e50ea3ad87609136d49779bff69811/ui/package.json#L38)):*
> ```JSON
>     "axios": "1.3.4",
>     "graphql": "^16.6.0",
>     "hsl-map-style": "git+https://github.com/HSLdevcom/hsl-map-style#843f305",
> ```

Why does this fragment part exist? Tried to find information about it but found nothing.
___
*[`ui/src/types/hsl-map-style.d.ts` line 8 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NXOl8Qb1xeAQHOEOGFe:-NXOl8Qb1xeAQHOEOGFf:buddhrn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/de5d0a3d80e50ea3ad87609136d49779bff69811/ui/src/types/hsl-map-style.d.ts#L8)):*
> ```XML
>   };
>   type QueryParams = {
>     url?: string; // Url pattern where the parameter should be added
> ```

Acronyms are in capital letters in code comments.

**Review by culka — COMMENTED** [review]
Good point, will do

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-:-NXOtdl5BIAz8LMgIO1b:bglg1hv)* status: all files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`ui/package.json` line 38 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NXOluws9LfnNrrqnSai:-NXOrPm1AUcW1avl4TzS:b4xkock) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/de5d0a3d80e50ea3ad87609136d49779bff69811/ui/package.json#L38)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Why does this fragment part exist? Tried to find information about it but found nothing.
</blockquote></details>

`hsl-map-style` was consistently version 1.0.0 and updating it via yarn did nothing, I had to specify the newest commit in the main branch in order to get it to update
___
*[`ui/src/types/hsl-map-style.d.ts` line 8 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NXOl8Qb1xeAQHOEOGFe:-NXOsog4CShqExvMxUr3:bt7xmku) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/de5d0a3d80e50ea3ad87609136d49779bff69811/ui/src/types/hsl-map-style.d.ts#L8)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Acronyms are in capital letters in code comments.
</blockquote></details>

The comments are all directly copied from the `hsl-map-style` javascript file definition. Seems like URL, Url and url are all used

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`ui/package.json` line 38 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NXOluws9LfnNrrqnSai:-NXUASbI9FMK1intHcSS:beuajdn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/de5d0a3d80e50ea3ad87609136d49779bff69811/ui/package.json#L38)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

`hsl-map-style` was consistently version 1.0.0 and updating it via yarn did nothing, I had to specify the newest commit in the main branch in order to get it to update
</blockquote></details>

Alright. Maybe then the fragment part needs to be updated from time to time to get the latest changes?

**Review by jarkkoka — CHANGES_REQUESTED** [review]
I couldn't get the map tiles to appear when I tested locally. Executed the following sequence on shell:

```sh
yarn install
./scripts/setup-dependencies-and-seed.sh
yarn dev
```

> Reviewed 2 of 6 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-:-NbTGtws3_spTT5noXAr:b-okiuo2)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`Dockerfile` line 24 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NbTCx_62qXZXhRPqAS3:-NbTCx_62qXZXhRPqAS4:bbl1n3i) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c01e1ddeff76bb8284e7dd883b5e52f4ebfb516d/Dockerfile#L24)):*
> ```Dockerfile
> COPY scripts/docker/replace-environment-variables.sh /tmp
> RUN curl -o /tmp/read-secrets.sh "https://raw.githubusercontent.com/HSLdevcom/jore4-tools/main/docker/read-secrets.sh"
> CMD /bin/sh -c "source /tmp/read-secrets.sh && /tmp/replace-environment-variables.sh && nginx -g \"daemon off;\""
> ```

Maybe the outermost double quotes could be replaced by single quotes since there are no environment variables to be inserted here. Then you could remove the escaping characters for the `"daemon off"`.



_Code quote:_
```Dockerfile
"
```
___
*[`scripts/docker/replace-environment-variables.sh` line 3 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NbTC-pO0lLi3SkXr-5G:-NbTC-pO0lLi3SkXr-5H:bxfupj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c01e1ddeff76bb8284e7dd883b5e52f4ebfb516d/scripts/docker/replace-environment-variables.sh#L3)):*
> ```Shell
> #!/bin/sh
> if [ -n "$NEXT_PUBLIC_DIGITRANSIT_API_KEY" ]; then
> sed -i -e "s/[[:alnum:]_]\+\.env\.NEXT_PUBLIC_DIGITRANSIT_API_KEY/\"$NEXT_PUBLIC_DIGITRANSIT_API_KEY\"/g" /usr/share/nginx/html/_next/static/chunks/pages/*.js
> ```

indent missing

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617)* status: all files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`Dockerfile` line 24 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NbTCx_62qXZXhRPqAS3:-NbmqTn37sSVsaWBepGL:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c01e1ddeff76bb8284e7dd883b5e52f4ebfb516d/Dockerfile#L24)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Maybe the outermost double quotes could be replaced by single quotes since there are no environment variables to be inserted here. Then you could remove the escaping characters for the `"daemon off"`.
</blockquote></details>

Done.
___
*[`scripts/docker/replace-environment-variables.sh` line 3 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-NbTC-pO0lLi3SkXr-5G:-NbmUuht2Qkhs0UQHpoW:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c01e1ddeff76bb8284e7dd883b5e52f4ebfb516d/scripts/docker/replace-environment-variables.sh#L3)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

indent missing
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
`yarn.lock` issue still present. Otherwise looks good.

> Reviewed 1 of 3 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-:-NbnDhpE39iBgxdtbtBi:b-93hysb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @culka)

**Review by culka — COMMENTED** [review]
`yarn.lock` update was found to not be the cause here. The fix is to manually clean yarn cache and remove the next build directory to also clear the map style library from there.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-:-NcRAHQI1DvsUAs9FJpS:b-sijc0y)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @jarkkoka)

**Review by HenrikHartiala — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-:-NcS9Aih-OqcFOUEe9dY:bnfp4nl)* status: 2 of 9 files reviewed, all discussions resolved (waiting on @jarkkoka)

**Review by culka — COMMENTED** [review]
Nevermind previous comment, `hsl-map-style` updated the version number and everything should work properly now.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/617#-:-NcSAuG54zpsJPVBxr70:byh6eiz)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @HenrikHartiala and @jarkkoka)

**Pull request merged**
