### PR TITLE
Add search criteria address

### PR DESCRIPTION
**Pull request by Perholehto**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823)* status: all files reviewed, 5 unresolved discussions (waiting on @Perholehto)

___
*[`cypress/e2e/stop-registry/stopSearch.cy.ts` line 69 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVi6DH19M2INmuDyG2:-NyVi6DH19M2INmuDyG3:b-rfyw1t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/cypress/e2e/stop-registry/stopSearch.cy.ts#L69)):*
> ```XML
>     name: { lang: 'fin', value: 'Tuusulanväylä' },
>     quays: [{ publicCode: 'H2233' }],
>     keyValues: [{ key: 'streetAddress', values: ['Tuusulanväylä 10-16'] }],
> ```

Would be good to have addresses for some other stops as well.
___
*[`cypress/e2e/stop-registry/stopSearch.cy.ts` line 161 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVizUoE2QwtkF0N3NT:-NyVizUoE2QwtkF0N3NU:b-fk52om) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/cypress/e2e/stop-registry/stopSearch.cy.ts#L161)):*
> ```XML
>     stopSearchBar = new StopSearchBar();
>     stopSearchResultsPage = new StopSearchResultsPage();
>     searchCriteriaRadioButtons = new SearchCriteriaRadioButtons();
> ```

If this is tightly coupled with the search bar, would it make sense to instantiate and expose this page object inside StopSearchBar? And access it like `stopSearchBar.searchCriteriaRadioButtons`.
___
*[`cypress/pageObjects/stop-registry/SearchCriteriaRadioButtons.ts` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyViXoF7sdrjMtQeNqs:-NyViXoF7sdrjMtQeNqt:bryngnx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/cypress/pageObjects/stop-registry/SearchCriteriaRadioButtons.ts#L2)):*
> ```XML
> export class SearchCriteriaRadioButtons {
>   getAddressRadioButton() {
> ```

Not used yet but could've added the `label? button as well.

And then could  sneak a check in some test that it is checked by default.
___
*[`ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx` line 11 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVaUbK9CSD0x4ZN1aa:-NyVaUbK9CSD0x4ZN1ab:b-sb3t2r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx#L11)):*
> ```XML
> };
> 
> const labelStyle =
> ```

This is only used in one place so could just inline the style?
___
*[`ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx` line 36 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVdUZ6CAUfFsdVZv4F:-NyVdUZ6CAUfFsdVZv4G:b-jup7jg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx#L36)):*
> ```XML
>   return (
>     <>
>       {searchByOptions.map((option) => (
> ```

I feel like it's a slight issue that you can't submit search with `Enter` when radio buttons (or rather, anything else than the search term input) is focused. Eg. this workflow feels annoying:
- type search term
- select `address` mode because you forgot to do that in the beginning
- now you must click search input again so you can actually submit the search

Doesn't help that the submit button is hidden behind an expand by default.
Should maybe check with design (and possibly Niki for accessibility opinion) what to do with this.
Would it eg. make sense that changing the search mode would trigger search?
___
*[`ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx` line 41 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVcnkT0-hD688zVcjQ:-NyVcnkT0-hD688zVcjR:bwst223) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx#L41)):*
> ```XML
>             className={labelStyle}
>             type="radio"
>             id={option.name}
> ```

Ids could be more specific than label / address. But doesn't cause issues at the moment so maybe not worth fixing :shrug: 
___
*[`ui/src/components/stop-registry/search/StopSearchBar.tsx` line 72 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVbtem6goBjzv2Jqoa:-NyVbtem6goBjzv2Jqob:b-uztxiq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/StopSearchBar.tsx#L72)):*
> ```XML
>       }
>     });
>     // eslint-disable-next-line react-hooks/exhaustive-deps
> ```

Could the lint rule just be removed along with the dependency array? Seems to pass lint at least.
___
*[`ui/src/components/stop-registry/search/StopSearchBar.tsx` line 98 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVfNcJ3B9Lp0OZEtM3:-NyVfNcJ3B9Lp0OZEtM4:bm1e1rm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/StopSearchBar.tsx#L98)):*
> ```XML
>             />
>           </Row>
>           <Row className="space-x-4 py-4">
> ```

The `space-x-4` here controls the space between the elements _inside_ the `SearchCriteriaRadioButtons` component, which feels a bit weird to me :thinking: Should it just be inside that component itself? :shrug: 
___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 97 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVgNe68TZyvnApURx9:-NyVgNe68TZyvnApURxA:bir1jhe) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L97)):*
> ```XML
>     StopsDatabaseStopPlaceNewestVersionBoolExp
>   >(
>     mapToSqlLikeValue(searchConditions.address),
> ```

To me it would feel more natural if this address search would automatically include `*` at the end. For labels it might be common for the users to type out the whole label, but maybe less so for addresses. Eg. when searching something on Mannerheimintie, like our test stop, I would maybe like to type `manner` and hit enter and expect all of them to show up, instead of having to type `manner*`.
On the other hand this would mean that these search modes have different behavior on this regard, which might be confusing.
Maybe check with design if this would make sense.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823)* status: all files reviewed, 5 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/stop-registry/search/StopSearchBar.tsx` line 72 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVbtem6goBjzv2Jqoa:-NyVjTRT6aZXrqnpjyng:bomxgu1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/StopSearchBar.tsx#L72)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could the lint rule just be removed along with the dependency array? Seems to pass lint at least.
</blockquote></details>

Except I just noticed this would cause some error spam in UI, so no can do. :heavy_check_mark:

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/stop-registry/stopSearch.cy.ts` line 69 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVi6DH19M2INmuDyG2:-NyZL3zm3CzuITmn8Pfo:b-8b11j9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/cypress/e2e/stop-registry/stopSearch.cy.ts#L69)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would be good to have addresses for some other stops as well.
</blockquote></details>

Added
___
*[`cypress/e2e/stop-registry/stopSearch.cy.ts` line 161 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVizUoE2QwtkF0N3NT:-NyZKUnF4pMXeDIrf5do:bod4wp3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/cypress/e2e/stop-registry/stopSearch.cy.ts#L161)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

If this is tightly coupled with the search bar, would it make sense to instantiate and expose this page object inside StopSearchBar? And access it like `stopSearchBar.searchCriteriaRadioButtons`.
</blockquote></details>

Yeah, not seen that this will be used without the search bar, so moved it
___
*[`cypress/pageObjects/stop-registry/SearchCriteriaRadioButtons.ts` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyViXoF7sdrjMtQeNqs:-NyZKut-5dYdykiw9k0N:b-23u3pp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/cypress/pageObjects/stop-registry/SearchCriteriaRadioButtons.ts#L2)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not used yet but could've added the `label? button as well.

And then could  sneak a check in some test that it is checked by default.
</blockquote></details>

Added label and sneaked a check to one test
___
*[`ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx` line 11 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVaUbK9CSD0x4ZN1aa:-NyZLMI95HLxjzJx_P1q:b52se6q) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx#L11)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This is only used in one place so could just inline the style?
</blockquote></details>

Sure, removed the extra variable . I prefer to extract along inline style even when it's used only once.
___
*[`ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx` line 36 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVdUZ6CAUfFsdVZv4F:-NyZglC_AgR0gOMA9rYG:b-llhvlj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx#L36)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I feel like it's a slight issue that you can't submit search with `Enter` when radio buttons (or rather, anything else than the search term input) is focused. Eg. this workflow feels annoying:
- type search term
- select `address` mode because you forgot to do that in the beginning
- now you must click search input again so you can actually submit the search

Doesn't help that the submit button is hidden behind an expand by default.
Should maybe check with design (and possibly Niki for accessibility opinion) what to do with this.
Would it eg. make sense that changing the search mode would trigger search?
</blockquote></details>

This is now changed to trigger search when changing a search term if there is text in input
___
*[`ui/src/components/stop-registry/search/StopSearchBar.tsx` line 72 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVbtem6goBjzv2Jqoa:-NyZMVqy-2bBhZfcc3Ng:b-huhrwa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/StopSearchBar.tsx#L72)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Except I just noticed this would cause some error spam in UI, so no can do. :heavy_check_mark:
</blockquote></details>

If there is no dependency array it will re-render every time, with empty array it will run only on the initial render.
___
*[`ui/src/components/stop-registry/search/StopSearchBar.tsx` line 98 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVfNcJ3B9Lp0OZEtM3:-NyZOCXc42JYWfPKQtwp:b-e7n027) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/StopSearchBar.tsx#L98)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

The `space-x-4` here controls the space between the elements _inside_ the `SearchCriteriaRadioButtons` component, which feels a bit weird to me :thinking: Should it just be inside that component itself? :shrug:
</blockquote></details>

Good catch, moved it to inside of the`SearchCriteriaRadioButtons`
___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 97 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-NyVgNe68TZyvnApURx9:-NyZe2dkDfLW8vx2NRK_:b-bjbswc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L97)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

To me it would feel more natural if this address search would automatically include `*` at the end. For labels it might be common for the users to type out the whole label, but maybe less so for addresses. Eg. when searching something on Mannerheimintie, like our test stop, I would maybe like to type `manner` and hit enter and expect all of them to show up, instead of having to type `manner*`.
On the other hand this would mean that these search modes have different behavior on this regard, which might be confusing.
Maybe check with design if this would make sense.
</blockquote></details>

There is a user story for changing the address search to have auto completion feature and IIRC it's part of MVP. If label and address search were different inputs then I would maybe think including `*`automatically for address, but now that it's one input, it would be really confusing or at least there should be some kind of indicator that it's happening...

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx` line 3 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/823#-Nyxvp9AB4Of6SXelKnc:-NyyHJn556_EpSXetyf3:bqhida7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47fc8ea40948691fd0855901d24f6b50b5f42d91/ui/src/components/stop-registry/search/SearchCriteriaRadioButtons.tsx#L3)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Why these couldn't work anymore? Shame to have the searchBy be passed only as a string between components.
</blockquote></details>

Brought back `SearchBy` as Enum

**Pull request merged**
