### PR TITLE
41501 - Added copying for stop shelters

### PR DESCRIPTION
**Pull request by villepynttari**
Testing:

1. Go to /stop-registry/stops/E1423?observationDate=2024-11-02
2. Click technical features
3. Click add shelter
4. Modify some values
5. Click copy

New shelter should appear with same values as above

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937)

### CODE REVIEW

**Review by Huulivoide — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @villepynttari)

___
*[`ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx` line 56 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937#-OAqPwvXCmxEIo_YvGxI:-OAqPwvY7CypPbiLOamz:bhu7sgp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/07100a5dbac11d702afe4755d90a1bc33b8a381f/ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx#L56)):*
> ```XML
>   const copyToNewShelter = useCallback(
>     (shelterIndex: number) => {
>       updateShelterCount();
> ```

Tässä vaiheessa ei olla vielä tehty mitään muutoksia, niin ei pitäs olla tarvetta päivittää tätä 
___
*[`ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx` line 63 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937#-OAqQ2G23LskDxQUNY9B:-OAqQ2G23LskDxQUNY9C:b-ucdiux) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/07100a5dbac11d702afe4755d90a1bc33b8a381f/ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx#L63)):*
> ```XML
>       } as ShelterEquipmentDetailsFragment;
> 
>       if (newShelter) {
> ```

newShelter on aina truthy sen nykysen määrittelyn perusteella. Se voi tosin olla tyhjä.

Piitäs olla ylempänä varmaan että:
```typesctipt
const shelterToCopy = currentShelters?.at(shelterIndex);
const newShelter = shelterToCopy ? { ...shelterToCopy, id: null } : null;
if (newShelter) ....
```

**Review by Huulivoide — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @villepynttari)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937#-OAqR6m12BGqxUe5uvI3):*
Tän fiksi kommitin vois sulauttaa tohon varsinaiseen kommittiin. Ei kommitoida tietoisesti bugista koodia masteriin.

**Review by villepynttari — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @Huulivoide)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937#-OAqR6m12BGqxUe5uvI3):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tän fiksi kommitin vois sulauttaa tohon varsinaiseen kommittiin. Ei kommitoida tietoisesti bugista koodia masteriin.
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx` line 56 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937#-OAqPwvXCmxEIo_YvGxI:-OB-GRfW7_MYpZrHBuHC:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/07100a5dbac11d702afe4755d90a1bc33b8a381f/ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx#L56)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tässä vaiheessa ei olla vielä tehty mitään muutoksia, niin ei pitäs olla tarvetta päivittää tätä
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx` line 63 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937#-OAqQ2G23LskDxQUNY9B:-OB-GRM9DfWB-Femc9BA:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/07100a5dbac11d702afe4755d90a1bc33b8a381f/ui/src/components/stop-registry/stops/stop-details/shelters/SheltersForm.tsx#L63)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

newShelter on aina truthy sen nykysen määrittelyn perusteella. Se voi tosin olla tyhjä.

Piitäs olla ylempänä varmaan että:
```typesctipt
const shelterToCopy = currentShelters?.at(shelterIndex);
const newShelter = shelterToCopy ? { ...shelterToCopy, id: null } : null;
if (newShelter) ....
```
</blockquote></details>

Done.

**Review by Huulivoide — DISMISSED** [review]
> Reviewed 2 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/937)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @villepynttari)

**Comment by Huulivoide** [comment]
Auts, nyt on mennyt merge committi tonne mukaan. Käytetään rebase flowta, merget on kiellettyjä.

**Review by Huulivoide — APPROVED** [review]

**Pull request merged**
