### PR TITLE
Persist accessibility level to Tiamat

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 8 of 8 files at r2, 3 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831)* status: all files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-NzSh0zTAoJYm74Ffe2d):*
Would throw in the word "enum" there (Use accessibility level enum from Tiamat). For a moment I thought that the logic change was in this commit.
___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 783 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-NzSeunA0zBQsCZrm_cF:-NzSeunA0zBQsCZrm_cG:b-l2d04g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/988307f03760cc77b19e6c69c30733b0b14ddad2/cypress/e2e/stop-registry/stopDetails.cy.ts#L783)):*
> ```XML
>             .shouldHaveText('Osittain esteellinen');
> 
>           cy.wait('@gqlUpdateStopPlace')
> ```

I personally don't like the network waits in e2e tests at all, but do we even need this? We already check that the UI changes above.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx` line 19 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-NzSiVJj8059mIM-GgIs:-NzSiVJj8059mIM-GgIt:bhx3iqx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/08d485ceae1680c95923eed250eb1172acf7c1c5/ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx#L19)):*
> ```XML
>   const [isModalOpen, toggleIsModalOpen] = useToggle();
>   const accessibilityLevel =
>     stop.stop_place?.accessibilityLevel || defaultAccessibilityLevel;
> ```

Hmm, not sure why we need this default value, shouldn't this value always be present in the database?

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831)* status: all files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-NzSh0zTAoJYm74Ffe2d):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Would throw in the word "enum" there (Use accessibility level enum from Tiamat). For a moment I thought that the logic change was in this commit.
</blockquote></details>

:thumbsup: 
___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 783 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-NzSeunA0zBQsCZrm_cF:-NzT3sio6LrxkvNvYO0b:b-jh9t6u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/988307f03760cc77b19e6c69c30733b0b14ddad2/cypress/e2e/stop-registry/stopDetails.cy.ts#L783)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I personally don't like the network waits in e2e tests at all, but do we even need this? We already check that the UI changes above.
</blockquote></details>

I suppose these aren't strictly necessary with UI using the value, removed.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx` line 19 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-NzSiVJj8059mIM-GgIs:-NzSmbSK8YCKqS77pbHS:bgh3yj0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/08d485ceae1680c95923eed250eb1172acf7c1c5/ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, not sure why we need this default value, shouldn't this value always be present in the database?
</blockquote></details>

Because the stop_place itself can be null, eg. for a new stop. Slightly annoying.

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx` line 19 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-NzSiVJj8059mIM-GgIs:-NzT5Nt6C2ll57G7o8e_:bc1yhip) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/08d485ceae1680c95923eed250eb1172acf7c1c5/ui/src/components/stop-registry/stops/stop-details/measurements/AccessibilityLevelInfo.tsx#L19)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Because the stop_place itself can be null, eg. for a new stop. Slightly annoying.
</blockquote></details>

Ah right yeah :+1:

**Review by culka — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, 8 of 8 files at r2, 3 of 3 files at r3, 5 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-:-NzT63EsDhLGFpdRMb9Z:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Review by HenrikHartiala — APPROVED** [review]
:shipit: 

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/831#-:-NzT6Rl92NmVuGfSoeyl:bizlbj6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
