### PR TITLE
Manage db for e2e tests from cypress

### PR DESCRIPTION
**Pull request by tk-vincit**
- Update graphql-codegen config to generate TS code also from
  test-db-manager
- Add example test (`cypress/e2e/routeStops.cy.ts`) to show
  how db contents can be handled in e2e testing. Resolves HSLdevcom/jore4[#703](https://github.com/HSLdevcom/jore4-ui/issues/703)
- Files in `test-db-manager/src/datasets/` are based on similar dataset
  from `jore4-hasura` repository

Resolves HSLdevcom/jore4[#776](https://github.com/HSLdevcom/jore4-ui/issues/776)

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/318)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> Reviewed 1 of 34 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/318)* status: 1 of 36 files reviewed, 15 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`codegen/codegen.js` line 76 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd58Tm2nWOQrdt6xv1:-NAd58Tm2nWOQrdt6xv2:bq9hyyp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/codegen/codegen.js#L76)):*
> ```JavaScript
>   hooks: {
>     afterAllFileWrite:
>       'prettier --write ../ui/src/generated/graphql.tsx && prettier --write ../ui/src/generated/graphql.tsx',
> ```

you probably meant `../test-db-manager/src/` for one of these calls

but I think it should also enough to just write `prettier --write` without the files as it substitutes the glob for the command
___
*[`cypress/e2e/routeStops.cy.ts` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd6ICsCDJOEjYoh0RO:-NAd6ICsCDJOEjYoh0RP:b-ph1vba) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/cypress/e2e/routeStops.cy.ts#L17)):*
> ```XML
> import { LineDetailsPage } from '../pageObjects';
> import { LineInsertInput, StopInsertInput } from '../types';
> import { InfraLinkInsertInput, RouteInsertInput } from '../types/inputs';
> ```

should be imported also from '../types'
___
*[`cypress/e2e/routeStops.cy.ts` line 20 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd6PhC6yQ_b5M__gjP:-NAd6PhC6yQ_b5M__gjQ:btvwkjo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/cypress/e2e/routeStops.cy.ts#L20)):*
> ```XML
> import { insertToDbHelper, removeFromDbHelper } from '../utils';
> 
> const infraLinks: InfraLinkInsertInput[] = [
> ```

this initialization is fine for now, but we should try to think how this setup could be built sensibly within like 5-10 lines of code
___
*[`cypress/e2e/routeStops.cy.ts` line 120 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd6pLs-f4Ixou-zl_O:-NAd6pLs-f4Ixou-zl_P:b-3wcq8b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/cypress/e2e/routeStops.cy.ts#L120)):*
> ```XML
> 
> const populateDb = () => {
>   insertToDbHelper(dbResources);
> ```

I don't think we should to create a function separately for this one-liner, it could very well just go directly to the before/after blocks.

Especially e.g. if we create some resource within a test, we could also try to remove that using the `removeFromDbHelper` function... maybe. I don't know
___
*[`cypress/e2e/routeStops.cy.ts` line 136 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd7IWK0M2yRTUbBSSC:-NAd7IWL7_ZKnLqtzb4f:b-3t2n6b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/cypress/e2e/routeStops.cy.ts#L136)):*
> ```XML
>     lineDetailsPage = new LineDetailsPage();
>     cy.mockLogin();
>     cy.visit(`/lines/${lines[0].line_id}`);
> ```

this is fine, but might be nicer to have this cy.visit function implemented within the LineDetailsPage page object that would only need to take e.g. the line id as parameter
___
*[`test-db-manager/src/hasuraApi.ts` line 13 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBF5L18D6fAd3U3vX:-NAdBF5L18D6fAd3U3vY:btx671i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/hasuraApi.ts#L13)):*
> ```XML
>     },
>   };
>   return fetch('http://localhost:3201/v1/graphql', req).then((response) =>
> ```

`fetch(process.env.GRAPHQL_API_URL || 'http://...')`
___
*[`test-db-manager/src/index.ts` line 5 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBWvVD4of9eFl6uvV:-NAdBWvVD4of9eFl6uvW:b-3un7yd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/index.ts#L5)):*
> ```XML
> export * from './datasets';
> export * from './DbManager';
> export * from './generated/graphql';
> ```

should this generated/graphql really be exported here?
___
*[`test-db-manager/src/builders/mutations.ts` line 76 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBqfeEoDiMtF9xUXv:-NAdBqfeEoDiMtF9xUXw:b-8awn34) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L76)):*
> ```XML
> 
> const GQL_DELETE_ROUTES = gql`
>   mutation DeleteRoute($route_id: [uuid!]!) {
> ```

For all the mutations in this file. We don't need to use underscores in parameter names, we could avoid linter errors by just calling them e.g. as `$routeIds`, `$lineIds`

Also, let these mutations have the plural form in the name: DeleteRoutes, etc. as they do delete multiple resources
___
*[`test-db-manager/src/builders/mutations.ts` line 94 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCGGTB8K2Pn-MxhFV:-NAdCGGTB8K2Pn-MxhFW:bba1oqt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L94)):*
> ```XML
> // ...line_all_fields
> const GQL_DELETE_LINES = gql`
>   mutation RemoveLines($line_ids: [uuid!]!) {
> ```

$lineIds
___
*[`test-db-manager/src/builders/mutations.ts` line 112 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCIIjDOyOTTeXuLco:-NAdCIIjDOyOTTeXuLcp:bd4s7de) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L112)):*
> ```XML
> const GQL_INSERT_STOPS = gql`
>   mutation InsertStops(
>     $object: [service_pattern_scheduled_stop_point_insert_input!]!
> ```

$stops
___
*[`test-db-manager/src/builders/mutations.ts` line 140 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCNSg0W-T6q8jo4BQ:-NAdCNSg0W-T6q8jo4BR:b-mt5rux) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L140)):*
> ```XML
> 
> const GQL_DELETE_STOPS = gql`
>   mutation RemoveStops($stop_ids: [uuid!]!) {
> ```

$stopIds
___
*[`test-db-manager/src/builders/mutations.ts` line 160 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCPweAkOkFCd0Lt2g:-NAdCPweAkOkFCd0Lt2h:bcg5xhk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L160)):*
> ```XML
> const GQL_INSERT_INFRA_LINKS = gql`
>   mutation InsertInfraLinks(
>     $object: [infrastructure_network_infrastructure_link_insert_input!]!
> ```

$infraLinks
___
*[`test-db-manager/src/builders/mutations.ts` line 216 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCjGxChwzkV9J6rHP:-NAdCjGxChwzkV9J6rHQ:b-b74ll7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L216)):*
> ```XML
> // Thus we have to use raw sql connection for handling those.
> // (Other solution could be renaming the tables.)
> export const insertVehicleSubmodeOnInfraLink = (
> ```

I'd rather move these from `mutations.ts` to some other file, like `dbQueries.ts`
___
*[`test-db-manager/src/builders/objects.ts` line 1 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdD15W3vYPIQeGAl09:-NAdD15W3vYPIQeGAl0A:bg9uddq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/objects.ts#L1)):*
> ```XML
> import { DateTime } from 'luxon';
> ```

objects.ts -> entities.ts ?
___
*[`test-db-manager/src/builders/objects.ts` line 31 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdDHGP4cGuS6aVTP5T:-NAdDHGP4cGuS6aVTP5U:bxbx4jm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/objects.ts#L31)):*
> ```XML
> });
> 
> export const buildLine = (postfix: string): RouteLineInsertInput => ({
> ```

if you have time/energy... instead of taking `postfix: string` as a parameter, you could have a similar `requiredFields` parameter for this with 'label' required as for the buildStop() function

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/318)* status: 0 of 36 files reviewed, 15 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`codegen/codegen.js` line 76 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd58Tm2nWOQrdt6xv1:-NAdak_xBjP_yzBCJQrI:bktexis) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/codegen/codegen.js#L76)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you probably meant `../test-db-manager/src/` for one of these calls

but I think it should also enough to just write `prettier --write` without the files as it substitutes the glob for the command
</blockquote></details>

Gotta admit that I don't remember why this ended up here twice, but now I think it was just a mistake. Removed the latter one.

Yes, we could prettify also `test-db-manager/src/generated/graphql.ts`if we want and I can add it here if needed. 
Anyway, I think we don't want to run just `prettier --write` without specifying paths for two reasons:
- it makes this command slower
- it might interfere with someone's workflow as then it would prettify all files
___
*[`cypress/e2e/routeStops.cy.ts` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd6ICsCDJOEjYoh0RO:-NAdLt4J9XMaQMKRtBTI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/cypress/e2e/routeStops.cy.ts#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should be imported also from '../types'
</blockquote></details>

Done.
___
*[`cypress/e2e/routeStops.cy.ts` line 120 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd6pLs-f4Ixou-zl_O:-NAdM50N4xs2lqv6jJfq:b-9lbg35) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/cypress/e2e/routeStops.cy.ts#L120)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think we should to create a function separately for this one-liner, it could very well just go directly to the before/after blocks.

Especially e.g. if we create some resource within a test, we could also try to remove that using the `removeFromDbHelper` function... maybe. I don't know
</blockquote></details>

Yeah, this was more than one line but then I ended up refactoring it like this. :smile:  One could argue that this improves readability a bit, but... Done.

The next one is used twice so maybe it merits its own function.
___
*[`cypress/e2e/routeStops.cy.ts` line 136 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd7IWK0M2yRTUbBSSC:-NAdMODi58_x5CfDzhJR:b-miriul) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/cypress/e2e/routeStops.cy.ts#L136)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is fine, but might be nicer to have this cy.visit function implemented within the LineDetailsPage page object that would only need to take e.g. the line id as parameter
</blockquote></details>

Hmm... Interesting idea. Why not, I'll do it. Done.
___
*[`test-db-manager/src/hasuraApi.ts` line 13 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBF5L18D6fAd3U3vX:-NAdQW2O6PPSprwosALu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/hasuraApi.ts#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`fetch(process.env.GRAPHQL_API_URL || 'http://...')`
</blockquote></details>

Done.
___
*[`test-db-manager/src/index.ts` line 5 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBWvVD4of9eFl6uvV:-NAdQXAM1j8QN7w1zx4t:b-op9bqy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/index.ts#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should this generated/graphql really be exported here?
</blockquote></details>

Do you have better ideas? Generated graphql is generated from this workspace, but we are using generated types also in cypress workspace.

If we have neat way of exporting these from something like `@hsl/jore4-test-db-manager/generated` then we could consider that, but with current setup the imports would end up to be `@hsl/jore4-test-db-manager/dist/types/generated/graphql.d.ts` (IIRC) if I remove this, and I think it is worse situation than current one.
___
*[`test-db-manager/src/builders/mutations.ts` line 76 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBqfeEoDiMtF9xUXv:-NAdRTJv47e0CmmO7igI:bhj4itc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L76)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

For all the mutations in this file. We don't need to use underscores in parameter names, we could avoid linter errors by just calling them e.g. as `$routeIds`, `$lineIds`

Also, let these mutations have the plural form in the name: DeleteRoutes, etc. as they do delete multiple resources
</blockquote></details>

I'm not seeing much linter errors in this file, so not sure what do you mean. These are inside gql code fragments and refed to fields in db, so not gonna refactor these to non-camelcase.

Also seems like all other mutations than this had plurar forms in their names, and this was mistake/forgotten from the first version of this.
___
*[`test-db-manager/src/builders/mutations.ts` line 94 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCGGTB8K2Pn-MxhFV:-NAdS6eDE267nwpJhe0x:b36xpvn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L94)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

$lineIds
</blockquote></details>

Not going to comment on each of these yet, but maybe let's discuss about this in the previous comment thread and then close all or fix all as we decide.
___
*[`test-db-manager/src/builders/mutations.ts` line 216 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCjGxChwzkV9J6rHP:-NAd_eMW4j3Ix9fT93VL:b-kd72r7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L216)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather move these from `mutations.ts` to some other file, like `dbQueries.ts`
</blockquote></details>

Well, I was thinking that now they're where one would first go looking for them - among other mutations even though they're not technically mutations.
___
*[`test-db-manager/src/builders/objects.ts` line 1 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdD15W3vYPIQeGAl09:-NAdXVz6-1UuZ78GaHHz:b-9fmn3c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/objects.ts#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

objects.ts -> entities.ts ?
</blockquote></details>

Good suggestion. Done.
___
*[`test-db-manager/src/builders/objects.ts` line 31 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdDHGP4cGuS6aVTP5T:-NAdZ6Jc7-S0PuZzNuOS:ba07eo6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/objects.ts#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if you have time/energy... instead of taking `postfix: string` as a parameter, you could have a similar `requiredFields` parameter for this with 'label' required as for the buildStop() function
</blockquote></details>

Done, and same for buildRoute.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/318)* status: 0 of 37 files reviewed, 6 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`.github/workflows/ci.yml` line 26 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmSZDn8WZRqCuzfq2q:-NAmSZDn8WZRqCuzfq2r:b-vhhutn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/.github/workflows/ci.yml#L26)):*
> ```YAML
> 
>       - name: Build common modules
>         run: yarn ws:db build
> ```

we're already doing this a few steps later. Which one should we keep?
Also, we could make a common `yarn build` script that builds all the individual modules (not necessarily in this PR though)
___
*[`codegen/codegen.js` line 76 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAd58Tm2nWOQrdt6xv1:-NAmT3cy1XdabGLToU4B:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/codegen/codegen.js#L76)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Gotta admit that I don't remember why this ended up here twice, but now I think it was just a mistake. Removed the latter one.

Yes, we could prettify also `test-db-manager/src/generated/graphql.ts`if we want and I can add it here if needed. 
Anyway, I think we don't want to run just `prettier --write` without specifying paths for two reasons:
- it makes this command slower
- it might interfere with someone's workflow as then it would prettify all files
</blockquote></details>

OK
___
*[`cypress/types/inputs.ts` line 9 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmTeRQ0TvK2a6TCdb-:-NAmTeRQ0TvK2a6TCdb0:bcv502w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/cypress/types/inputs.ts#L9)):*
> ```XML
> import { RequiredKeys } from './types';
> 
> export type StopInsertInput = RequiredKeys<
> ```

Nice :+1: 
___
*[`test-db-manager/src/index.ts` line 5 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBWvVD4of9eFl6uvV:-NAmUGxaBsRTiKSYwKlX:b5r1ona) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/index.ts#L5)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do you have better ideas? Generated graphql is generated from this workspace, but we are using generated types also in cypress workspace.

If we have neat way of exporting these from something like `@hsl/jore4-test-db-manager/generated` then we could consider that, but with current setup the imports would end up to be `@hsl/jore4-test-db-manager/dist/types/generated/graphql.d.ts` (IIRC) if I remove this, and I think it is worse situation than current one.

</blockquote></details>

I see, so these types are also supposed to be used outside of this module, e.g. in cypress? well, then this is fine :+1: 
___
*[`test-db-manager/src/builders/mutations.ts` line 216 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdCjGxChwzkV9J6rHP:-NAmV7wT7Bhm_aRTpkZ8:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/builders/mutations.ts#L216)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, I was thinking that now they're where one would first go looking for them - among other mutations even though they're not technically mutations.
</blockquote></details>

OK
___
*[`test-db-manager/src/builders/mutations.ts` line 205 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmVEZq-D3pzvdzds8R:-NAmVEZq-D3pzvdzds8S:b-3rag92) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/mutations.ts#L205)):*
> ```XML
> }
> 
> // Vehicle submodes on infra links can't be handled with hasura api because
> ```

thanks for the comment!
___
*[`test-db-manager/src/builders/entities.ts` line 22 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmUZXj0iEU5yPJDaPf:-NAmUZXj0iEU5yPJDaPg:b9ncpb2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/entities.ts#L22)):*
> ```XML
>   requiredFields: Pick<RouteRouteInsertInput, 'label'>,
> ): RouteRouteInsertInput => ({
>   name_i18n: buildLocalizedString(`route ${requiredFields.label}`),
> ```

one could say you could destructure `label` from `requiredFields` in the first line of the body of this function as it's so extensively used in it ;)
___
*[`test-db-manager/src/builders/entities.ts` line 40 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmUt2rEFrF-v6AAi3a:-NAmUt2rEFrF-v6AAi3b:b9ncpb2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/entities.ts#L40)):*
> ```XML
>   requiredFields: Pick<RouteLineInsertInput, 'label'>,
> ): RouteLineInsertInput => ({
>   name_i18n: buildLocalizedString(`line ${requiredFields.label}`),
> ```

one could say you could destructure `label` from `requiredFields` in the first line of the body of this function as it's so extensively used in it ;)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/318)* status: 0 of 37 files reviewed, 6 unresolved discussions (waiting on @pallost)

___
*[`.github/workflows/ci.yml` line 26 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmSZDn8WZRqCuzfq2q:-NAmWY7B0-FRZOGi6ttu:b407zj5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/.github/workflows/ci.yml#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we're already doing this a few steps later. Which one should we keep?
Also, we could make a common `yarn build` script that builds all the individual modules (not necessarily in this PR though)
</blockquote></details>

Excellent catch! We should keep this one as TS types from the build are needed in the next step. Agree also about the common build command, but let's do it a bit later.
___
*[`cypress/types/inputs.ts` line 9 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmTeRQ0TvK2a6TCdb-:-NAmWsau7ftw_ssDOtYh:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/cypress/types/inputs.ts#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Nice :+1: 
</blockquote></details>

Done.
___
*[`test-db-manager/src/index.ts` line 5 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAdBWvVD4of9eFl6uvV:-NAmWwKG-RtYXkhyXQ5X:b-x0paxf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d074342feb1d8728de2aa7c0afa6c94b384de921/test-db-manager/src/index.ts#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I see, so these types are also supposed to be used outside of this module, e.g. in cypress? well, then this is fine :+1: 
</blockquote></details>

Yes :)
___
*[`test-db-manager/src/builders/mutations.ts` line 205 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmVEZq-D3pzvdzds8R:-NAmXMjk9_Pse732yl9E:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/mutations.ts#L205)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

thanks for the comment!
</blockquote></details>

Done.
___
*[`test-db-manager/src/builders/entities.ts` line 22 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmUZXj0iEU5yPJDaPf:-NAmX2hL4Uz0NSCcjNmq:b28pzj9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/entities.ts#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

one could say you could destructure `label` from `requiredFields` in the first line of the body of this function as it's so extensively used in it ;)
</blockquote></details>

Yeah, maybe. In the other hand then we would have to add explicit return statement. Maybe not touching this one now, someone can easily refactor it later if they want. :smile: 
___
*[`test-db-manager/src/builders/entities.ts` line 40 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmUt2rEFrF-v6AAi3a:-NAmXHwQ1dzDvnm42wHp:buo9nmt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/entities.ts#L40)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

one could say you could destructure `label` from `requiredFields` in the first line of the body of this function as it's so extensively used in it ;)
</blockquote></details>

Same here

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/318)* status: 0 of 38 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`test-db-manager/src/builders/entities.ts` line 22 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmUZXj0iEU5yPJDaPf:-NAmaj6wDWmVv5mXcS69:b-mkqz8q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/entities.ts#L22)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Yeah, maybe. In the other hand then we would have to add explicit return statement. Maybe not touching this one now, someone can easily refactor it later if they want. :smile: 
</blockquote></details>

Or whatever, done. :smile: 
___
*[`test-db-manager/src/builders/entities.ts` line 40 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/318#-NAmUt2rEFrF-v6AAi3a:-NAmbnkd5EbCorxYgM-8:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ec4ca48d5106223fbdcafcfcaf04920cf3dd5a74/test-db-manager/src/builders/entities.ts#L40)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

**Pull request merged**
