### PR TITLE
Add welcome page and fix routes and lines page

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/216)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/216)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`cypress/integration/login.spec.ts` line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b-2S5CDdwo54YdTxl:-N4b-2S5CDdwo54YdTxm:b2xwcgb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/cypress/integration/login.spec.ts#L4)):*
> ```XML
>   it('User is not logged in by default', () => {
>     cy.visit('/');
>     cy.getByTestId('userNavMenu:loginButton').should('contain', '');
> ```

Wtf? 

Ok, please read my comment below and add explaining comment here.
___
*[`cypress/integration/login.spec.ts` line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b2SJn6ESNvaXok1_e:-N4b2SJn6ESNvaXok1_f:bciug39) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/cypress/integration/login.spec.ts#L9)):*
> ```XML
>     cy.mockLogin();
>     cy.visit('/');
>     cy.getByTestId('userNavMenu:toggleDropdown').should('contain', 'Test');
> ```

Wtf? This test doesn't make any sense anymore.

Ok, after figuring this out for a while I assume "Test" is name of e2e user and you're checking if user name is visible in navbar. But that is now impossible for the reader of this test case to know. Please add explaining comments about this. 

Or even better, you could read "Test" from `cypress/fixtures/users/e2e.json` (see example about using fixture from docs or from `cypress/support/commands.ts`) so that this test wouldn't be tied to magical 'Test' string coming from nowhere.
___
*[`src/locales/fi-FI/common.json` line 233 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b1Eo26N1fom9Pabq3:-N4b1Eo26N1fom9Pabq4:b-2udvn9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/locales/fi-FI/common.json#L233)):*
> ```JSON
>   "version": "Versio: {{ version }}",
>   "hide": "Piilota",
>   "welcomePage": {
> ```

Now fi and en translation files wont match anymore.
I would suggest copypasting these also there.
___
*[`src/pages/Main.tsx` line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b1fm84u2JXiVu6OzK:-N4b1fm84u2JXiVu6OzL:b-wrhwhm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L14)):*
> ```XML
>   return (
>     <div data-testid="main" className="h-screen bg-brand bg-opacity-50 p-20">
>       <div className="mx-auto w-4/5 space-y-6 rounded-lg bg-white p-10 text-xl leading-8 shadow-2xl">
> ```

This div doesn't have text content as direct children.  So does it make sense to define text-xl here and then override it on children elements? I would rather pass it directly to the text elements that actually use it, so it would be easier to see why certain text has certain styles without having to figure out where they are inherited and why.
___
*[`src/pages/Main.tsx` line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b1ph51ctNrp11dfAj:-N4b1ph51ctNrp11dfAk:bri008w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L19)):*
> ```XML
>         </h1>
>         <h2 className="font-bold">{t('welcomePage.subheading1')}</h2>
>         <div>{t('welcomePage.paragraph1')}</div>
> ```

FYI, html has a tag for paragraphs and that is not a div: https://www.w3schools.com/tags/tag_p.asp
___
*[`src/pages/Main.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b0sI_-UqUKhZ6AXSq:-N4b0sI_-UqUKhZ6AXSr:b-bgstb8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L25)):*
> ```XML
>         {!userInfo?.permissions && (
>           <SimpleButton
>             // Workaround, because SimpleButton href does not seem to
> ```

If that is an issue, SimpleButton should check if link is relative (starts with "/") or not and then choose used tag accordingly. This is quite an hack. Or then you could use <a> tag here straight away. But well, maybe this is ok here as this is hopefully temporary solution.
___
*[`src/pages/Main.tsx` line 32 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b0Uli9TY4kiRe9p7T:-N4b0Uli9TY4kiRe9p7U:b6w99sk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L32)):*
> ```XML
>             }}
>             containerClassName="w-full justify-center"
>             className="!px-6 !py-3 text-sm"
> ```

Why important classes?

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/216)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

___
*[`src/locales/fi-FI/common.json` line 233 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b1Eo26N1fom9Pabq3:-N4bLaCa9IDtawEfraqr:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/locales/fi-FI/common.json#L233)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Now fi and en translation files wont match anymore.
I would suggest copypasting these also there.
</blockquote></details>

Done.
___
*[`src/pages/Main.tsx` line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b1fm84u2JXiVu6OzK:-N4bLe3u4Bxk7NEm0V5-:b3j8lva) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L14)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This div doesn't have text content as direct children.  So does it make sense to define text-xl here and then override it on children elements? I would rather pass it directly to the text elements that actually use it, so it would be easier to see why certain text has certain styles without having to figure out where they are inherited and why.
</blockquote></details>

I thought it is easier to just give all the text on this page default size (as all but one use this size). I added additional div container that has `text-xl` and all of it children use that size.
___
*[`src/pages/Main.tsx` line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b1ph51ctNrp11dfAj:-N4bMgLM9LnFLa6sWN-h:b-qprtyf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

FYI, html has a tag for paragraphs and that is not a div: https://www.w3schools.com/tags/tag_p.asp
</blockquote></details>

Makes not much difference here, but I changed it anyway.
___
*[`src/pages/Main.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b0sI_-UqUKhZ6AXSq:-N4bMlo5DqOVnZZOnkXH:b-ctdli9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If that is an issue, SimpleButton should check if link is relative (starts with "/") or not and then choose used tag accordingly. This is quite an hack. Or then you could use <a> tag here straight away. But well, maybe this is ok here as this is hopefully temporary solution.
</blockquote></details>

I don't think relative check works, as this is relative as well and I expect pretty much every other use case is relative as well.

Didn't want to spent that much time playing with this as it is supposed to be a temporary solution.
___
*[`src/pages/Main.tsx` line 32 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b0Uli9TY4kiRe9p7T:-N4bNA7g2_uePIT4ttj2:b-a8efqa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/src/pages/Main.tsx#L32)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why important classes?
</blockquote></details>

Because `SimpleButton` has paddings by default that we want to adjust a little bit.
___
*[`cypress/integration/login.spec.ts` line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b-2S5CDdwo54YdTxl:-N4bEkT1DOjKCdhnqt-i:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/cypress/integration/login.spec.ts#L4)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Wtf? 

Ok, please read my comment below and add explaining comment here.
</blockquote></details>

Done.
___
*[`cypress/integration/login.spec.ts` line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4b2SJn6ESNvaXok1_e:-N4bHto3-iFv74H4dP8z:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/91c018a4d7bee4c45bb5a9935c4d28055baef374/cypress/integration/login.spec.ts#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Wtf? This test doesn't make any sense anymore.

Ok, after figuring this out for a while I assume "Test" is name of e2e user and you're checking if user name is visible in navbar. But that is now impossible for the reader of this test case to know. Please add explaining comments about this. 

Or even better, you could read "Test" from `cypress/fixtures/users/e2e.json` (see example about using fixture from docs or from `cypress/support/commands.ts`) so that this test wouldn't be tied to magical 'Test' string coming from nowhere.
</blockquote></details>

Done.

**Review by pallost — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/216)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`cypress/e2e/login.cy.ts` line 5 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4f9HiY--Adc_8TH4a_:-N4f9HiY--Adc_8TH4aa:b5amn82) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/395e4684db718506d04f92e5f4303db0f106481c/cypress/e2e/login.cy.ts#L5)):*
> ```XML
> /* eslint-disable func-names */
> before(function () {
>   cy.fixture('users/e2e.json').then(function (userInfo) {
> ```

umm, where did you see this pattern? This is really not intuitive: you create a (global) function in row 5 and attach some attribute to it. Then you create another (global) function in row ~11 and access that attribute. This is only working because these functions are in the global scope. This is how you do it in tests:

describe('Verify that login mocking works', () => {
  let userInfo;

  before(async () => {
    userInfo = await cy.fixture('users/e2e.json');
  });

  it('...', () => {
    cy.getByTestId('userNavMenu:toggleDropdown').should('contain', userInfo.givenName);
  });
})

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/216)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`cypress/e2e/login.cy.ts` line 5 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4f9HiY--Adc_8TH4a_:-N4fAgaZ2Q1xACXIQiD2:bubrjau) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/395e4684db718506d04f92e5f4303db0f106481c/cypress/e2e/login.cy.ts#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

umm, where did you see this pattern? This is really not intuitive: you create a (global) function in row 5 and attach some attribute to it. Then you create another (global) function in row ~11 and access that attribute. This is only working because these functions are in the global scope. This is how you do it in tests:

describe('Verify that login mocking works', () => {
  let userInfo;

  before(async () => {
    userInfo = await cy.fixture('users/e2e.json');
  });

  it('...', () => {
    cy.getByTestId('userNavMenu:toggleDropdown').should('contain', userInfo.givenName);
  });
})


</blockquote></details>

Saw it here
https://docs.cypress.io/api/commands/fixture#this-context

But I can still change it

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/216)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`cypress/e2e/login.cy.ts` line 5 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/216#-N4f9HiY--Adc_8TH4a_:-N4fHk4T2-a8JkJc5Q-f:bgycdkf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/395e4684db718506d04f92e5f4303db0f106481c/cypress/e2e/login.cy.ts#L5)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Saw it here
https://docs.cypress.io/api/commands/fixture#this-context

But I can still change it
</blockquote></details>

I would have suggested this same thing. Much better now.

**Pull request merged**
