### PR TITLE
Add assertions to make tests more stable

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#1096

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452)

### CODE REVIEW

**Review by eleksi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/pageObjects/ModalMap.ts` line 83 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NL_z8RV7dXqLXdfPgSK:-NL_z8RV7dXqLXdfPgSL:b-wd12ce) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/ModalMap.ts#L83)):*
> ```XML
>     omittedStops?: string[];
>   }) => {
>     cy.intercept('/api/mapmatching/api/route/v1/bus/').as('mapMatching');
> ```

Please remove this and add in commands as in here
https://github.com/HSLdevcom/jore4-ui/pull/456/files
___
*[`cypress/pageObjects/ModalMap.ts` line 102 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NL_z9iJ24t_yoG4sKFL:-NL_z9iJ24t_yoG4sKFM:bkuldhy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/ModalMap.ts#L102)):*
> ```XML
>     }
> 
>     cy.wait('@mapMatching');
> ```

This could probably be few lines above as in here
https://github.com/HSLdevcom/jore4-ui/pull/456/files
___
*[`cypress/pageObjects/RouteEditor.ts` line 51 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NL_ymkR0BQkDFZnz9h9:-NL_ymkR0BQkDFZnz9hA:b-wd12ce) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/RouteEditor.ts#L51)):*
> ```XML
>    */
>   editOneRoutePoint(values: MoveRouteEditHandleInfo) {
>     cy.intercept('/api/mapmatching/api/route/v1/bus/').as('mapMatching');
> ```

Please remove this and add in commands as in here
https://github.com/HSLdevcom/jore4-ui/pull/456/files

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452)* status: all files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/editStop.cy.ts` line 184 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NL_zqRoEbOdPvDx-TrI:-NL_zqRoEbOdPvDx-TrJ:b-acownm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/e2e/editStop.cy.ts#L184)):*
> ```XML
>       mapFilterPanel.toggleShowStops(ReusableComponentsVehicleModeEnum.Bus);
> 
>       map.getLoader().should('not.exist');
> ```

Great :+1: 
___
*[`cypress/pageObjects/Map.ts` line 17 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NLa-1YW3VCxE_-W9Ch7:-NLa-1YXD7HmwuyHPePq:b-uetxpu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/Map.ts#L17)):*
> ```XML
>     times(n, () => cy.getByTestId('modalMap').type('+'));
>     this.getLoader().should('not.exist');
>     cy.wait('@gqlGetStopsByLocation');
> ```

This might make multiple zoom's in a row a bit slow, but no need to change this now. Just a note.

**Review by eleksi — COMMENTED** [review]
After my comments are fixed this is approved. Fixing them is not critical but if that can be done now, then rather do it. After fixing them (or deciding not to) just merge this asap.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-:-NLa3hoN0Ntv9HhA6_WR:bctymot)* status: all files reviewed, 3 unresolved discussions (waiting on @sr-vala)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452)* status: all files reviewed, 4 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/pageObjects/Map.ts` line 70 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NLa8I5f7R0cW4zTEHY0:-NLa8I5f7R0cW4zTEHY1:bfu6x24) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/Map.ts#L70)):*
> ```XML
>   visit(params?: { zoom?: number; lat: number; lng: number }) {
>     if (params) {
>       return [
> ```

Why we are returning array of statements here..? Is the return value used somewhere? If we want to return multiple values (which I doubt in this case) we probably want rather return object so that each value can be given name.


Should we rather:

```
cy.visit (...);
this.getLoader(...);

return;
 ```

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`cypress/pageObjects/Map.ts` line 17 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NLa-1YW3VCxE_-W9Ch7:-NLdNyRFBJtC9rHyxx6E:b8ill15) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/Map.ts#L17)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This might make multiple zoom's in a row a bit slow, but no need to change this now. Just a note.
</blockquote></details>

I't s a trade-off between speed and stability. At least I noticed some operations happening too fast after the zoom, and failing because of it. Hopefully the request is made in every case that the zoom happens.
___
*[`cypress/pageObjects/Map.ts` line 70 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NLa8I5f7R0cW4zTEHY0:-NLdRjPVEhuLJfK1Jz37:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/Map.ts#L70)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why we are returning array of statements here..? Is the return value used somewhere? If we want to return multiple values (which I doubt in this case) we probably want rather return object so that each value can be given name.


Should we rather:

```
cy.visit (...);
this.getLoader(...);

return;
 ```

</blockquote></details>

Done.
___
*[`cypress/pageObjects/ModalMap.ts` line 83 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NL_z8RV7dXqLXdfPgSK:-NLdRO3k87GcauNc-QC5:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/ModalMap.ts#L83)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Please remove this and add in commands as in here
https://github.com/HSLdevcom/jore4-ui/pull/456/files
</blockquote></details>

Done.
___
*[`cypress/pageObjects/ModalMap.ts` line 102 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NL_z9iJ24t_yoG4sKFL:-NLdRQfJ4wkDWbrIsy3Z:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/ModalMap.ts#L102)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This could probably be few lines above as in here
https://github.com/HSLdevcom/jore4-ui/pull/456/files
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteEditor.ts` line 51 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452#-NL_ymkR0BQkDFZnz9h9:-NLdRSTH5tIVExiQSWT4:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a98fceff7f3d0931f6b1e19cd73666f09fa6c839/cypress/pageObjects/RouteEditor.ts#L51)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Please remove this and add in commands as in here
https://github.com/HSLdevcom/jore4-ui/pull/456/files
</blockquote></details>

Done.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/452)* status: 6 of 11 files reviewed, 4 unresolved discussions (waiting on @eleksi and @tk-vincit)

**Pull request merged**
