### PR TITLE
Implement language selection in Navbar

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)

### CODE REVIEW

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)* status: all files reviewed, 4 unresolved discussions (waiting on @tk-vincit)

___
*[src/components/navbar/LanguageDropdown.tsx, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX1s_T5NWKdWeUubeA:-MZX1s_T5NWKdWeUubeB:b-b65ry3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L21)):*
> ```
> puprose
> ```

_purpose_
___
*[src/components/navbar/LanguageDropdown.tsx, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX29WN-78PBggG65pQ:-MZX29WN-78PBggG65pR:bsy5xya) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L34)):*
> ```
>   
> ```

Two spaces between `px-3` and `focus:outline-none`
___
*[src/components/navbar/LanguageDropdown.tsx, line 39 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX472CAP8S9gFwljBv:-MZX472CAP8S9gFwljBw:b-d1mvyo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L39)):*
> ```XML
>               {currentLanguageText}
>             </Menu.Button>
>             <Transition
> ```

A question rather than a complaint: how much content should there be in a component before we split it up? For example here I might have created a separate (local) component of the menu button (and perhaps the item list too). On the other hand I don't really know how this `headlessui` menu even works so I guess this might be ok.
___
*[src/components/navbar/Navbar.tsx, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX2uKl5bCOQxS_IskX:-MZX2uKl5bCOQxS_IskY:b-qybui5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L38)):*
> ```XML
>         style={{ borderLeftWidth: '1px' }}
>       />
>     </nav>
> ```

Should we perhaps have some sort of a `Header`-component, whose purpose is to just wrap the `Navbar` and `LanguageDropdown` (and any other such components we create in the future) instead of injecting the`LanguageDropdown` within the `Navbar`?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)* status: all files reviewed, 8 unresolved discussions (waiting on @lassemaatta and @tk-vincit)

___
*[src/components/navbar/LanguageDropdown.tsx, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX7H7c83Cw1R8kP5xc:-MZX7H7c83Cw1R8kP5xd:b1zolzc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L5)):*
> ```XML
> import { i18n } from '../../i18n';
> 
> export const testIds = {
> ```

it's a great idea to collect test ids like this!
___
*[src/components/navbar/LanguageDropdown.tsx, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX7bk82vVOQsikBIP1:-MZX7bk82vVOQsikBIP2:bxv4vh4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L11)):*
> ```XML
> interface Props {
>   className?: string;
>   style?: React.CSSProperties;
> ```

as we are using tailwind, shouldn't that be enough for defining the style through `className`? Is there a special reason you allow `style` parameters aswell? Not a mistake, just interested...
___
*[src/components/navbar/LanguageDropdown.tsx, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX29WN-78PBggG65pQ:-MZXANgkALsNCcvL6LXG:bd2j9p1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L34)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
>   
> ```

Two spaces between `px-3` and `focus:outline-none`
</blockquote></details>

there are actually quite a few whitespace "errors" in this PR in the DOM, is prettier doing its job properly?
___
*[src/components/navbar/LanguageDropdown.spec.tsx, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX8qF46BTD_RD-EtAx:-MZX8qF46BTD_RD-EtAy:b8d5pa2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.spec.tsx#L9)):*
> ```XML
>   const finnishTitle = 'FI';
>   const englishTitle = 'EN';
>   // Example tes suite. Maybe not the most useful test to have, but this
> ```

well, it'd be great to test that changing the language through this button actually does something and translations change ;) If translations are disabled in tests, then could check at least that `i18n.currentLanguage` has changed to something else
___
*[src/components/navbar/Navbar.tsx, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX9YKD0ZzWPZv2AY17:-MZX9YKD0ZzWPZv2AY18:bkef9mq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L36)):*
> ```XML
>       <LanguageDropdown
>         className="ml-auto border-black border-opacity-20 "
>         style={{ borderLeftWidth: '1px' }}
> ```

why not just use the tailwind definition for this? `border-l`
___
*[src/components/navbar/Navbar.tsx, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX2uKl5bCOQxS_IskX:-MZX9un49wWNnTyfUM2L:b-sy4x5j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L38)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Should we perhaps have some sort of a `Header`-component, whose purpose is to just wrap the `Navbar` and `LanguageDropdown` (and any other such components we create in the future) instead of injecting the`LanguageDropdown` within the `Navbar`? 
</blockquote></details>

Yeah, might be smart to separate <Logo/>. <Navbar/> and <LanguageDropdown/> into their own components and combine them within a <Header/>

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)* status: all files reviewed, 8 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[src/components/navbar/LanguageDropdown.tsx, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX7H7c83Cw1R8kP5xc:-MZXU2axBzttweOGQu3q:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's a great idea to collect test ids like this!
</blockquote></details>

Done.
___
*[src/components/navbar/LanguageDropdown.tsx, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX7bk82vVOQsikBIP1:-MZXPDTEAFjgVJTeSao_:bz808ch) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as we are using tailwind, shouldn't that be enough for defining the style through `className`? Is there a special reason you allow `style` parameters aswell? Not a mistake, just interested...
</blockquote></details>

I had to use a little bit of inline stylings to get e.g. 1px border width just right. I wanted these to match 100% to HSL's "official" navbar, and with current config tailwind has only `border-0` which is 0px and`border-2` which is 2px.

If we need 1px borders in multiple places, we could add `border-1` variant to tailwind. Anyway, didn't done that yet as I don't know if we really need 1px borders in more places.
___
*[src/components/navbar/LanguageDropdown.tsx, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX1s_T5NWKdWeUubeA:-MZXQIw9A08-4-mzgqBP:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L21)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> puprose
> ```

_purpose_
</blockquote></details>

Done.
___
*[src/components/navbar/LanguageDropdown.tsx, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX29WN-78PBggG65pQ:-MZXQMQL5TA9wRp4GCyY:b-vra3rm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L34)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there are actually quite a few whitespace "errors" in this PR in the DOM, is prettier doing its job properly?
</blockquote></details>

Prettier isn't smart enough to trim whitespaces in `classNames`. I tried to look at that quikcly while implementing this, but dind't find any solutions. But maybe we could take a little bit more time to dig into this. Anyway, if we can't automate the formattings of these nor find linter rule then I guess that we'll just have to deal with the situation.

@pallost can you point about more whitespace errors? At least prettier is working as it should and this code is formatted according to it, and that is verified at CI.
___
*[src/components/navbar/LanguageDropdown.tsx, line 39 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX472CAP8S9gFwljBv:-MZXRTtq8oCwf6RRyjOl:bzgsmvb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.tsx#L39)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

A question rather than a complaint: how much content should there be in a component before we split it up? For example here I might have created a separate (local) component of the menu button (and perhaps the item list too). On the other hand I don't really know how this `headlessui` menu even works so I guess this might be ok.
</blockquote></details>

Well... This could be spil into components, yes. Anyway, didn't do that at this point as there is no code duplication so far. E.g. about menu items, we only have one of those. If there would be more languages, then I definitely would have extracted this to component or then generated each item inside a loop, so that we wouldn't have to duplicate component definitions and classNames and so on.
___
*[src/components/navbar/LanguageDropdown.spec.tsx, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX8qF46BTD_RD-EtAx:-MZXSHC68d24NAVmLvZm:bjynmly) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.spec.tsx#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

well, it'd be great to test that changing the language through this button actually does something and translations change ;) If translations are disabled in tests, then could check at least that `i18n.currentLanguage` has changed to something else
</blockquote></details>

I agree and spent at least two hours trying to do that yesterday. The problem was that dropdown didn't closed as it should have done in the test, and I dind't wanted to spent all day with it.

Anyway, I think that this test is as good example test as the previous one was, so this commit didn't make things any worse as they were. :) 
___
*[src/components/navbar/Navbar.tsx, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX9YKD0ZzWPZv2AY17:-MZXSxx813-YtMVshR6l:b-2tf61a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

why not just use the tailwind definition for this? `border-l`
</blockquote></details>

There's no `border-1` in default config: https://tailwindcss.com/docs/border-width
As mentioned in above comment, we could add it if we need this border in multiple places...
___
*[src/components/navbar/Navbar.tsx, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX2uKl5bCOQxS_IskX:-MZXTB1C0pmCLicYjrTV:b-sm832f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L38)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Yeah, might be smart to separate <Logo/>. <Navbar/> and <LanguageDropdown/> into their own components and combine them within a <Header/>
</blockquote></details>

within a?

What kind of abstraction would you like to have for header/navbar?
E.g. bootstrap, which could be used as a reference, has `navbar` which has e.g. brand section and dropdowns = exactly the same stuff as we have here right now.

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)* status: all files reviewed, 7 unresolved discussions (waiting on @lassemaatta, @pallost, and @tk-vincit)

___
*[src/components/navbar/Navbar.tsx, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX2uKl5bCOQxS_IskX:-MZYCc6g6ASabiXE9nfO:b-47o015) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L38)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

within a?

What kind of abstraction would you like to have for header/navbar?
E.g. bootstrap, which could be used as a reference, has `navbar` which has e.g. brand section and dropdowns = exactly the same stuff as we have here right now.
</blockquote></details>

I was thinking that if we have a) a bunch of components (with some non-trivial amount of internal logic/complexity), b) which only share their location on the screen (e.g. they're located in a header, footer, a menu etc), but c) don't really interact or now about each other => Perhaps there should be a common container component, which is only responsible in _composing_ the other components, instead of nesting the components within one another? 

```typescript
return render(
    <div class="header ...">
       <Navbar />
       <LanguageDropdown />
    </div>
);
```

Now I'm the first to admit that I know almost nothing about the whole "how are these components styled" aspect and there might be some CSS related thing that makes this impossible. But if I understand this correctly then the `Navbar` and the `LanguageDropdown` components seem to be independent from each other and I see no reason why they should be complected together.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)* status: all files reviewed, 7 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[src/components/navbar/Navbar.tsx, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX2uKl5bCOQxS_IskX:-MZkzC6nB74Ofochqn7t:b-j9nwel) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L38)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I was thinking that if we have a) a bunch of components (with some non-trivial amount of internal logic/complexity), b) which only share their location on the screen (e.g. they're located in a header, footer, a menu etc), but c) don't really interact or now about each other => Perhaps there should be a common container component, which is only responsible in _composing_ the other components, instead of nesting the components within one another? 

```typescript
return render(
    <div class="header ...">
       <Navbar />
       <LanguageDropdown />
    </div>
);
```

Now I'm the first to admit that I know almost nothing about the whole "how are these components styled" aspect and there might be some CSS related thing that makes this impossible. But if I understand this correctly then the `Navbar` and the `LanguageDropdown` components seem to be independent from each other and I see no reason why they should be complected together.
</blockquote></details>

I'm pretty confident that current Navbar abstraction makes more sense and is accessibility-wise better than this "header" thing, but how about now?

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)* status: 9 of 11 files reviewed, 7 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[src/components/navbar/Navbar.tsx, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX2uKl5bCOQxS_IskX:-MZl2Jgw8Muw4ag6ja5J:bu2q1fq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L38)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I'm pretty confident that current Navbar abstraction makes more sense and is accessibility-wise better than this "header" thing, but how about now?
</blockquote></details>

Ah, sorry. Fixed this in pr #5 as this belongs more in its scope.

**Review by lassemaatta — APPROVED** [review]
Looks ok to me, but @pallost should check this out.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-:-MZl5z3u0PH54_zliGml:bwm7s2p)* status: all files reviewed, 5 unresolved discussions (waiting on @lassemaatta and @pallost)

**Review by pallost — APPROVED** [review]
I'll approve this. There are no critical issues, but there are things that could be polished if you have the energy... Let's create a github issue about that interaction test that it does not get forgotten.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-:-MZls5Vl9VQUzkV1IUmY:b8suc9i)* status: all files reviewed, 5 unresolved discussions (waiting on @lassemaatta, @pallost, and @tk-vincit)

___
*[src/components/navbar/LanguageDropdown.tsx, line 27 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZlrk-t8iNkNTmbrKv9:-MZlrk-t8iNkNTmbrKvA:b-lz7fmq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/24716cf6376c24066e0b86b061bb2b7167c9b379/src/components/navbar/LanguageDropdown.tsx#L27)):*
> ```XML
>   return (
>     <div
>       className={` text-white self-stretch hover:bg-brand-darker ${className}`}
> ```

here's a whitespace error that prettier does not seem to care about ^
___
*[src/components/navbar/LanguageDropdown.spec.tsx, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX8qF46BTD_RD-EtAx:-MZlr-F2CriVFlaMvBXg:bz6w8k3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/LanguageDropdown.spec.tsx#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I agree and spent at least two hours trying to do that yesterday. The problem was that dropdown didn't closed as it should have done in the test, and I dind't wanted to spent all day with it.

Anyway, I think that this test is as good example test as the previous one was, so this commit didn't make things any worse as they were. :) 
</blockquote></details>

well, then let's bury this for now and create a FIXME ticket to github to return to this later
___
*[src/components/navbar/Navbar.tsx, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX9YKD0ZzWPZv2AY17:-MZlrHQ47mWW84BOv3cA:b-c8zps9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L36)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

There's no `border-1` in default config: https://tailwindcss.com/docs/border-width
As mentioned in above comment, we could add it if we need this border in multiple places...
</blockquote></details>

that's `border-l` with an `L` :)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/6)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @lassemaatta, @pallost, and @tk-vincit)

___
*[src/components/navbar/Navbar.tsx, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/6#-MZX9YKD0ZzWPZv2AY17:-MZqHhQjEyOSe_FuIZTY:bxh0a2q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81f508c33e5e688e85301e263938c42a7d9565e1/src/components/navbar/Navbar.tsx#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

that's `border-l` with an `L` :)
</blockquote></details>

Oh, I had completely missed `border-t, border-r, border-b, border-l` classes. Good point! Fixed (=removed) the remaining "1px border" inline style definition. Thanks!

**Pull request merged**
