### PR TITLE
Add timetable version new logic

### PR DESCRIPTION
**Pull request by HenrikHartiala**
First iteration of the new logic for timetable versions page. This PR should not be merged to main before the Hasura version is reviewed and merged to main there.

This logic will now support substitute days as well.
Now we first fetch distinct journey patterns by line label and then we fetch timetable versions related to those journey patterns. Currently the period is just a hard coded value from 2020-01-01 -> 2023-12-31, but in the next iteration there will be added the time range for the user to choose from.Also the same time range might be used to narrow down the journey pattern fetching, which is not there yet.

For reviewers, this is a draft PR, and I will continue with this a bit more, so not everything is in the final state yet.

Also there is already a branch which has enhanced the colours and sorting of this page, but I will do a PR of it after this or parallel.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588)

### CODE REVIEW

**Review by Leitsi — COMMENTED** [review]
> Reviewed 1 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588)* status: 6 of 22 files reviewed, 6 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`docker/docker-compose.custom.yml` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV-UeUn9yJ1jACRD1YN:-NV-UeUn9yJ1jACRD1YO:b-1vupsl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33635bd983c8cf954762f2bc8379dc4274d1966a/docker/docker-compose.custom.yml#L7)):*
> ```YAML
>     # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
>     # The :hsl-tag contains the desired version of hsl specific hasura.
>     image: &hasura-image 'hsldevcom/jore4-hasura:hsl-add-timetable-version-functions--20230508-1dd1dddfe52cb7751d8af68b4af9154671002e06'
> ```

Typically one would include the generated source updates in same commit as this. Maybe move those parts to this commit?
___
*[`scripts/start-dependencies.sh` line 60 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV-V8O22cOgp-p5PSs-:-NV-V8O22cOgp-p5PSs0:b-gkniyw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33635bd983c8cf954762f2bc8379dc4274d1966a/scripts/start-dependencies.sh#L60)):*
> ```Shell
> 
>   # start up only services that are needed in local ui development
>   $DOCKER_COMPOSE_CMD up -d jore4-hastus
> ```

How is this change related to the versions page logic? Should maybe be in separate commit, or provide some explanation in another way.
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 32 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NUQLdXy2BkCY0kBML5W:-NV-WIlHDqmhwxiQ4B_0:bdrhuxm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c35b12e370586e0cf78c5e8aee500d94be87868a/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L32)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah, after we get the time range components added, the situation might be different, but currently it seemed that the useMemo was a necessarity or otherwise there were infinite calls. I've struggled with these dateTimes and useEffects earlier as well.
</blockquote></details>

Nit, i would rather not split multi line comments like that (or is this Prettier's doing, hope not). Rather put it all in one line or move before the relevant line.



_Code snippet:_
```XML
  // TODO: Add timerange components and remove hardcoded values
  beginDate: useMemo(() => DateTime.fromISO('2020-01-01'), []),
  endDate: useMemo(() => DateTime.fromISO('2023-12-31'), []),
```
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 63 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV3QcEo2u1DijV01fZB:-NV3QcEo2u1DijV01fZC:b-sq4lrk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33635bd983c8cf954762f2bc8379dc4274d1966a/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L63)):*
> ```XML
>       <td className={statusClassName}>{statusText}</td>
>       <td className={dayTypeClassName}>
>         <span>{parseI18nField(data.dayType.nameI18n)}</span>
> ```

Nit, any reason to use `span` here, could just omit it instead? I feel that `span` elements without any classes etc are a bit silly.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588)* status: 6 of 23 files reviewed, 6 unresolved discussions (waiting on @eleksi and @Leitsi)

___
*[`docker/docker-compose.custom.yml` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV-UeUn9yJ1jACRD1YN:-NV3_RS8B_5NcTKqopqL:b-bqo0wt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33635bd983c8cf954762f2bc8379dc4274d1966a/docker/docker-compose.custom.yml#L7)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Typically one would include the generated source updates in same commit as this. Maybe move those parts to this commit?
</blockquote></details>

Good pick, this was just my negligence.
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 32 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NUQLdXy2BkCY0kBML5W:-NV3_r4dAJsnSHuHWgfR:brsaexk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c35b12e370586e0cf78c5e8aee500d94be87868a/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L32)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Nit, i would rather not split multi line comments like that (or is this Prettier's doing, hope not). Rather put it all in one line or move before the relevant line.
</blockquote></details>

I can change this. I think the point here was to make sure that it hits both affected lines, but yeah. Im going to add the timepicker components soon anyways.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 63 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV3QcEo2u1DijV01fZB:-NV3o3bBBJ3vzUmWTyc1:bkc0ec1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33635bd983c8cf954762f2bc8379dc4274d1966a/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L63)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Nit, any reason to use `span` here, could just omit it instead? I feel that `span` elements without any classes etc are a bit silly.
</blockquote></details>

Convinced, removed the span
___
*[`scripts/start-dependencies.sh` line 60 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV-V8O22cOgp-p5PSs-:-NV3_aSo-Y6tfZveqxiM:b731id) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33635bd983c8cf954762f2bc8379dc4274d1966a/scripts/start-dependencies.sh#L60)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

How is this change related to the versions page logic? Should maybe be in separate commit, or provide some explanation in another way.
</blockquote></details>

This also should not be changed at all, thanks!

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588)* status: 6 of 23 files reviewed, 4 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`ui/src/utils/graphql.ts` line 47 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV42V6778x6qeuypja2:-NV42V6778x6qeuypja3:bsto0l6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1105c64e6718a3c86acc47c1dc277ceefaceb6a0/ui/src/utils/graphql.ts#L47)):*
> ```XML
>     hasuraArrayString += `${index !== array.length - 1 ? ',' : ''}`;
>   });
>   hasuraArrayString += '}';
> ```

This might be slightly simpler with something like this:



_Suggestion:_
```XML
  const convertedItems = array.map((item, index) => {
    // If there is array inside of array, we need to do the same conversion to
    // the inner array by calling this function recursively
    if (Array.isArray(item)) {
      return convertArrayTypeForHasura(item);
    } else {
      return item;
    }
  });
  const hasuraArrayString = `{${convertedItems.join(','}}`;
```
___
*[`ui/src/utils/graphql.spec.ts` line 9 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV41rEs8MaEde9ftU_y:-NV41rEs8MaEde9ftU_z:bc817c2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1105c64e6718a3c86acc47c1dc277ceefaceb6a0/ui/src/utils/graphql.spec.ts#L9)):*
> ```XML
>     expect(output).toBe('{[first],second,third}');
>   });
>   test('Should convert array of arrays correctly', () => {
> ```

FYI, or `nested arrays`. Also maybe add an empty line between test cases.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588)* status: 6 of 23 files reviewed, 4 unresolved discussions (waiting on @eleksi and @Leitsi)

___
*[`ui/src/utils/graphql.ts` line 47 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV42V6778x6qeuypja2:-NV46NS0-Yr5Cr0KiyJA:b-ce3lxg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1105c64e6718a3c86acc47c1dc277ceefaceb6a0/ui/src/utils/graphql.ts#L47)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This might be slightly simpler with something like this:
</blockquote></details>

Nice, that's a lot simpler and I do hate using 'let' anywhere. Thanks!
___
*[`ui/src/utils/graphql.spec.ts` line 9 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-NV41rEs8MaEde9ftU_y:-NV47hcx7lAskZFk_X8K:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1105c64e6718a3c86acc47c1dc277ceefaceb6a0/ui/src/utils/graphql.spec.ts#L9)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

FYI, or `nested arrays`. Also maybe add an empty line between test cases.
</blockquote></details>

:+1:

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/588#-:-NWMcVzf2Bo-Qt-OqIvQ:bnfp4nl)* status: 4 of 23 files reviewed, 2 unresolved discussions (waiting on @eleksi)

**Pull request merged**
