### PR TITLE
Initial leaflet integration to project

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[next.config.js, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYGInCZcgp_V8Qe-h:-McnYGInCZcgp_V8Qe-i:b-cznsc4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/next.config.js#L1)):*
> ```JavaScript
> /* eslint-disable @typescript-eslint/no-var-requires */
> ```

let's not disable eslint rules like this, rather do it line-by-line. Or if there are many, could disable some sections with "off" and then reenable with "error"
___
*[src/components/map/CircleLayer.tsx, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYhEu4RFLm5cIY6WR:-McnYhEvDW9QmheWsN4v:b-fr4f9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/CircleLayer.tsx#L11)):*
> ```XML
>     <>
>       {data?.playground_points.map(
>         // eslint-disable-next-line camelcase
> ```

as we are going to have the data from the sql database coming in snake_case format, might be simplest to just disable this whole eslint camelcase rule...
___
*[src/components/map/EditLayer.tsx, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnZOwr4-3SWVDM7mR8:-McnZOwr4-3SWVDM7mR9:bzyq3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/EditLayer.tsx#L13)):*
> ```XML
>       coordinates: [event.latlng.lat, event.latlng.lng],
>     };
>     insertPoint({ variables: { geojson } });
> ```

this is gonna hurt very much if we start to call GraphQL mutations directly from components, no translation layer in between... Especially when the API will sometimes change. I see these mutation calls are working with hooks though just to make life as complicated as possible, so it does not seem to be possible to extract it to its own "api service"

How about making some kind of mapping function at least in between, something like this?
```
const mapInsertPointInput = (latitude: number, longitude: number) => {
  return { variables: { geojson: {
      type: 'Point',
      coordinates: [latitude, longitude],
    }}}
};

useMapEvent('click', (event: LeafletMouseEvent) => {
  insertPoint(mapInsertPointInput(event.latlng.lat, event.latlng.lng));
});
```

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

___
*[src/components/map/CircleLayer.tsx, line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-Mcn_rDx2iqG3VJhmH2J:-Mcn_rDx2iqG3VJhmH2K:bz98f08) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/CircleLayer.tsx#L14)):*
> ```XML
>         ({ point_id, point_geog: { coordinates } }) => (
>           // eslint-disable-next-line camelcase
>           <Marker key={point_id} position={coordinates} />
> ```

It makes me wonder that do we want to make a similar mapping function also to read the outputs of the subscriptions like I suggested below with the mutation input mapping? This might be a bigger work however and might not be as fruitful
___
*[src/generated/graphql.tsx, line 421 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnaDtIDGWzXOp2sGTl:-McnaDtIDGWzXOp2sGTm:bppi41p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/generated/graphql.tsx#L421)):*
> ```XML
> 
> 
> export const InsertPointDocument = gql`
> ```

Not strictly in scope of this pull request, but it's relatively fast to do: whenever you are having a generated resource in the repository, you are risking that updating it to the latest version is forgotten. To this however, you could create a simple github workflow that calls the generator script and checks the git repository status to be "up to date", meaning that it's fresh. Here's an example:

https://github.com/HSLdevcom/jore4-flux/blob/main/.github/workflows/doctoc.yml

This only needs to be extended with a docker call that downloads and runs jore4-hasura:latest docker container to be able to extract the latest graphql schema from

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[next.config.js, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYGInCZcgp_V8Qe-h:-McnatRTC2QHdNzLUs4u:b-4btb06) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/next.config.js#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's not disable eslint rules like this, rather do it line-by-line. Or if there are many, could disable some sections with "off" and then reenable with "error"
</blockquote></details>

I generally agree 100% with you, but this is kind of special file as this is next.js's config file and not our source file. 
I think that in this case it makes sense to disable these rules for this whole file.
___
*[src/components/map/CircleLayer.tsx, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYhEu4RFLm5cIY6WR:-McnbBrD4ckmWgsb7m9K:b-y7p39f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/CircleLayer.tsx#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as we are going to have the data from the sql database coming in snake_case format, might be simplest to just disable this whole eslint camelcase rule...
</blockquote></details>

Do we already know that? If that is the case, then you are probably right. I wans't sure about that, and didn't wanted to disable rule completely yet as I currently this uses dummy data and I wans't sure what the "real" data will look like.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/map/CircleLayer.tsx, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYhEu4RFLm5cIY6WR:-McnbeQZEtUnpDtRNqig:bjx0kg7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/CircleLayer.tsx#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we already know that? If that is the case, then you are probably right. I wans't sure about that, and didn't wanted to disable rule completely yet as I currently this uses dummy data and I wans't sure what the "real" data will look like.
</blockquote></details>

true... let's return to this later when we know!

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

___
*[next.config.js, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYGInCZcgp_V8Qe-h:-McnboEV9xKWPOVrn_gr:b-m79vui) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/next.config.js#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I generally agree 100% with you, but this is kind of special file as this is next.js's config file and not our source file. 
I think that in this case it makes sense to disable these rules for this whole file.
</blockquote></details>

I think this rule actually disables it for the entire project, no only for this file...?

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[next.config.js, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYGInCZcgp_V8Qe-h:-McncNA1-gvddB6v4_86:bpwhn0m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/next.config.js#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think this rule actually disables it for the entire project, no only for this file...?
</blockquote></details>

I'll check this, but IIRC this should disable these rules only for this file (and it makes more sense that way). Global rules are set in `.eslintrc.js`

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[next.config.js, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYGInCZcgp_V8Qe-h:-Mcne-7g16WVbn6bjRCs:b32wtd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/next.config.js#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I'll check this, but IIRC this should disable these rules only for this file (and it makes more sense that way). Global rules are set in `.eslintrc.js`
</blockquote></details>

ok

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[next.config.js, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnYGInCZcgp_V8Qe-h:-McnhI7t-dG_ddlz9K_R:b-6njv5s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/next.config.js#L1)):*
Yeah, (documentation)[https://eslint.org/docs/user-guide/configuring/rules#disabling-rules] says that
>You can also disable or enable specific rules for an entire file:
>`/* eslint-disable no-alert */`
I also tried to put 
`const withImages = require('next-images');` in another file and got eslint errors -> I think this is fine like this.
___
*[src/components/map/CircleLayer.tsx, line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-Mcn_rDx2iqG3VJhmH2J:-Mcnjtnj6SX_3Ie9qae7:b-b1d7ff) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/CircleLayer.tsx#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

It makes me wonder that do we want to make a similar mapping function also to read the outputs of the subscriptions like I suggested below with the mutation input mapping? This might be a bigger work however and might not be as fruitful
</blockquote></details>

Maybe we'll consider that if/when actual need for that arises.
___
*[src/components/map/EditLayer.tsx, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnZOwr4-3SWVDM7mR8:-Mcnib9-BuWRNAYQd9G7:b-6xcf6h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/EditLayer.tsx#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is gonna hurt very much if we start to call GraphQL mutations directly from components, no translation layer in between... Especially when the API will sometimes change. I see these mutation calls are working with hooks though just to make life as complicated as possible, so it does not seem to be possible to extract it to its own "api service"

How about making some kind of mapping function at least in between, something like this?
```
const mapInsertPointInput = (latitude: number, longitude: number) => {
  return { variables: { geojson: {
      type: 'Point',
      coordinates: [latitude, longitude],
    }}}
};

useMapEvent('click', (event: LeafletMouseEvent) => {
  insertPoint(mapInsertPointInput(event.latlng.lat, event.latlng.lng));
});
```
</blockquote></details>

Ok :+1: 
___
*[src/generated/graphql.tsx, line 421 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnaDtIDGWzXOp2sGTl:-McnkHhH6h6Zys6J7WPh:b-cc5p4j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/generated/graphql.tsx#L421)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Not strictly in scope of this pull request, but it's relatively fast to do: whenever you are having a generated resource in the repository, you are risking that updating it to the latest version is forgotten. To this however, you could create a simple github workflow that calls the generator script and checks the git repository status to be "up to date", meaning that it's fresh. Here's an example:

https://github.com/HSLdevcom/jore4-flux/blob/main/.github/workflows/doctoc.yml

This only needs to be extended with a docker call that downloads and runs jore4-hasura:latest docker container to be able to extract the latest graphql schema from
</blockquote></details>

Good idea, but `@graphql-codegen` script does 2 things
1. fetches graphql api schema from hasura
2. generates ts code based on schema (?) and based on graphql strings in our project

phase 1 naturally needs hasura server up & running somewhere, and we don't have that available in ui's CI - at least not right now. 

Not sure if `@graphql-codegen` could somehow be used for doing only phase 2 at CI. But I think that is something that could be done in the scope of different task.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[src/components/map/CircleLayer.tsx, line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-Mcn_rDx2iqG3VJhmH2J:-McsNgaZ2ddCpQ3pDnYg:bv6v6h7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/CircleLayer.tsx#L14)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Maybe we'll consider that if/when actual need for that arises.
</blockquote></details>

ok, let's not process outputs for now :+1: 
___
*[src/components/map/EditLayer.tsx, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnZOwr4-3SWVDM7mR8:-McsNYMMEyaD-HTwgAzN:bg493wm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/components/map/EditLayer.tsx#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Ok :+1: 
</blockquote></details>

could you refactor to this mapping function so that this translation layer thing does not get forgotten?
___
*[src/generated/graphql.tsx, line 421 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/16#-McnaDtIDGWzXOp2sGTl:-McsNqSB9aGQXnx_4y60:b-rmhbbz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f05303f5efa19210537d59080e654df0d030f74e/src/generated/graphql.tsx#L421)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Good idea, but `@graphql-codegen` script does 2 things
1. fetches graphql api schema from hasura
2. generates ts code based on schema (?) and based on graphql strings in our project

phase 1 naturally needs hasura server up & running somewhere, and we don't have that available in ui's CI - at least not right now. 

Not sure if `@graphql-codegen` could somehow be used for doing only phase 2 at CI. But I think that is something that could be done in the scope of different task.
</blockquote></details>

as discussed in Slack, let's not pull this CI job into this PR's scope

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/16)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
