### PR TITLE
Change stop search query target database

### PR DESCRIPTION
**Pull request by HenrikHartiala**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 36 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815#-Nw9iIB9DDj3s4WZ2AYL:-NwDfFu388zK5rr_LZpu:b-sk8vlh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/df5c4756649b392c1098faf5ac2c5429642439bc/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L36)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could we get rid of the `newest` in the naming here?
</blockquote></details>

Yeah true. I was thinking that it is the name of the view, but now that you say, it is irrelevant in the fragment name. Or at least I think you could use it on the table as well, since they have the same fields.
___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 89 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815#-Nw9lPu7DZzjuQgglios:-NwDflCtABxdtEeEw5nv:b-7wpxpb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/df5c4756649b392c1098faf5ac2c5429642439bc/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L89)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Lots of stuff going on here. Would introducing a helper function for mapping single row clarify things? Something like:
```
const mapResultRowToStopSearchRow = (
  stopPlace: StopTableRowStopPlaceNewestVersionFragment,
) => {
  return {
    ...(stopPlace.scheduled_stop_point_instance as StopTableRowFragment),
    stop_place: {
      nameFin: stopPlace.name_value,
      nameSwe: stopPlace.stop_place_alternative_names.find(
        (alternativeName) =>
          alternativeName.alternative_name.name_lang === 'swe' &&
          alternativeName.alternative_name.name_type === 'TRANSLATION',
      )?.alternative_name.name_value,
    },
  };
};

const mapQueryResultToStopSearchRows = (
  result: SearchStopsQueryResult,
): StopSearchRow[] => {
  return (
    result.data?.stops_database?.stops_database_stop_place_newest_version.map(
      mapResultRowToStopSearchRow,
    ) || []
  );
};
```

Still passable as is, but might get more bloated with more fields.
</blockquote></details>

:+1: Yep, will keep on bloating and at that point we can also keep splitting the helper function as well. But that can be done when needed. Anyway, added the helper

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 119 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815#-NwOjTz-C218EmBtyIEZ:-NwOjTz-C218EmBtyIE_:bmar11v) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/364210496bd0bf5da2526f7fc52ea64acc297441/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L119)):*
> ```XML
>   const parsedSearchQueryParameters = useStopSearchQueryParser();
> 
>   const newSearchQueryVariables = buildSearchStopsGqlQueryVariables(
> ```

Why is this `new`? Some development naming that got forgotten?

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 119 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815#-NwOjTz-C218EmBtyIEZ:-Nwcee2e9X3p21Rh0o8F:b-i7xbkv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/364210496bd0bf5da2526f7fc52ea64acc297441/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L119)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Why is this `new`? Some development naming that got forgotten?
</blockquote></details>

It's exactly that, good one. I did use _find_ to find all these, but seems that I somehow still managed to missed this one. Fixed.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/815#-:-NwcmTO2150bYSBcWEi7:bnfp4nl)* status: 4 of 11 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

**Pull request merged**
