### PR TITLE
Add generic graphql result mappers

### PR DESCRIPTION
**Pull request by pallost**
Only for route.route entities for now; to be extended and generalized with other types in the future

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/249)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/249)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/graphql/resultMappers.ts` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67jlW--k_FUIFYoYGp:-N67jlW--k_FUIFYoYGq:b-bupb4t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L14)):*
> ```XML
> type RouteQueryResult = QueryRootLike<{ route_route?: RouteLike[] }>;
> 
> function isRouteQueryResult(
> ```

This is a bit confusing, the function name "isRouteQueryResult" is pointing towards boolean result type, but this returns the result (?)
Also I think this should be arrow function.
___
*[`ui/src/graphql/resultMappers.ts` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67kaJq81f9UfrEE-3h:-N67kaJr2HnvnVpDnpfx:by9km1m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L17)):*
> ```XML
>   result: GqlQueryResult<GqlQueryResultData>,
> ): result is GqlQueryResult<RouteQueryResult> {
>   return (result.data || false) && 'route_route' in result.data;
> ```

I think this `(result.data || false)` should be `!!result.data`. Otherwise this is like "if result.data is falsy, return false". Or 
___
*[`ui/src/graphql/resultMappers.ts` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67mO8D8XQ2YE00sU4i:-N67mO8D8XQ2YE00sU4j:b-8rmmth) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L19)):*
> ```XML
>   return (result.data || false) && 'route_route' in result.data;
> }
> export const mapResultToRoute = (
> ```

What do you think if the name was `mapRouteResultToRoute`? Might be just a bit more readable.
___
*[`ui/src/graphql/resultMappers.ts` line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67n_YUE1t3iN60HlNN:-N67n_YUE1t3iN60HlNO:bro44gu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L26)):*
> ```XML
>     : result.data?.route_route_by_pk) as RouteRoute | undefined;
> 
> export const mapResultToRoutes = (result: GqlQueryResult<RouteQueryResult>) =>
> ```

Same as above, what do you think if the name was `mapRoutesResultToRoutes`

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/249)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/graphql/resultMappers.ts` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67jlW--k_FUIFYoYGp:-N67onFX60rF7yCYb2gn:b-1snrid) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L14)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is a bit confusing, the function name "isRouteQueryResult" is pointing towards boolean result type, but this returns the result (?)
Also I think this should be arrow function.
</blockquote></details>

I didn't know type guards can be arrow functions too, but now I found the syntax. Fixed it! Otherwise this actually returns always boolean.
___
*[`ui/src/graphql/resultMappers.ts` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67kaJq81f9UfrEE-3h:-N67p4kD6A3cvg-lnJDL:b-ny5ggx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L17)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this `(result.data || false)` should be `!!result.data`. Otherwise this is like "if result.data is falsy, return false". Or 
</blockquote></details>

well, it's actually always boolean, but I changed it to the `!!` syntax for clarity, good suggestion!
___
*[`ui/src/graphql/resultMappers.ts` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67mO8D8XQ2YE00sU4i:-N67pCU3321hqY9plvu0:b-91oon) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

What do you think if the name was `mapRouteResultToRoute`? Might be just a bit more readable.
</blockquote></details>

I don't think it adds any additional value to change the name to this. We only want to map "route"-typed queries' results to routes, cannot map any other to route type
___
*[`ui/src/graphql/resultMappers.ts` line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67n_YUE1t3iN60HlNN:-N67pRfv9_tZNsOyIoGj:b-91oon) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L26)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Same as above, what do you think if the name was `mapRoutesResultToRoutes`
</blockquote></details>

I don't think it adds any additional value to change the name to this. We only want to map "route"-typed queries' results to routes, cannot map any other to route type

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/249)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/graphql/resultMappers.ts` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67jlW--k_FUIFYoYGp:-N67vmBs3ecjr-Wak_Yu:bjt922n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I didn't know type guards can be arrow functions too, but now I found the syntax. Fixed it! Otherwise this actually returns always boolean.
</blockquote></details>

Ah okay. The result type that intellisense gives for this function is `result is GqlQueryResult<RouteQueryResult>`. But shouldn't it say `boolean`?
? Or is this correct return type for this type guard? I'm not that familiar with it so that is why it is confusing 
___
*[`ui/src/graphql/resultMappers.ts` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67mO8D8XQ2YE00sU4i:-N67sfAZ9UArZ3nOzzin:b8uke0a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L19)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think it adds any additional value to change the name to this. We only want to map "route"-typed queries' results to routes, cannot map any other to route type
</blockquote></details>

Yes exactly, that is why I was wondering that it could be in the name, because only routeResults can be mapped to routes. Not any other result type. Now the naming could imply that you can map any `result` to routes. Also in the future there might be many "mapResultTo..." and then the intellisense dropdown would have many choices, instead of just one or two when you type in "mapRou..".
But it's not that big of a deal and I'm also fine with this, so up to you.
___
*[`ui/src/graphql/resultMappers.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67vPMR9gjCHVR1nqpv:-N67vPMR9gjCHVR1nqpw:b-ikjaeo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/84d17179592c5d0cc8ab333747c66919987ccb48/ui/src/graphql/resultMappers.ts#L16)):*
> ```XML
> const isRouteQueryResult = (
>   result: GqlQueryResult<GqlQueryResultData>,
> ): result is GqlQueryResult<RouteQueryResult> => {
> ```

I think you can still remove the return clause and curly brackets.
```
const isRouteQueryResult = (
  result: GqlQueryResult<GqlQueryResultData>,
): result is GqlQueryResult<RouteQueryResult> =>
  !!result.data && 'route_route' in result.data;
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/249)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/graphql/resultMappers.ts` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67jlW--k_FUIFYoYGp:-N684zX8-rriIK60ADiJ:b3nx33c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L14)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah okay. The result type that intellisense gives for this function is `result is GqlQueryResult<RouteQueryResult>`. But shouldn't it say `boolean`?
? Or is this correct return type for this type guard? I'm not that familiar with it so that is why it is confusing 
</blockquote></details>

This is how type guards work ;)
___
*[`ui/src/graphql/resultMappers.ts` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67mO8D8XQ2YE00sU4i:-N684pS_03_fhGcLqS0z:btfjhzj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bbea7e32bc1d8712b315f3c4c936d867869f761b/ui/src/graphql/resultMappers.ts#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes exactly, that is why I was wondering that it could be in the name, because only routeResults can be mapped to routes. Not any other result type. Now the naming could imply that you can map any `result` to routes. Also in the future there might be many "mapResultTo..." and then the intellisense dropdown would have many choices, instead of just one or two when you type in "mapRou..".
But it's not that big of a deal and I'm also fine with this, so up to you.
</blockquote></details>

As you wish... I renamed it.
___
*[`ui/src/graphql/resultMappers.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67vPMR9gjCHVR1nqpv:-N6809Op39MAbfli9fQ9:bkc5ayc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/84d17179592c5d0cc8ab333747c66919987ccb48/ui/src/graphql/resultMappers.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think you can still remove the return clause and curly brackets.
```
const isRouteQueryResult = (
  result: GqlQueryResult<GqlQueryResultData>,
): result is GqlQueryResult<RouteQueryResult> =>
  !!result.data && 'route_route' in result.data;
```
</blockquote></details>

I could, but this is already pretty hard to read with the curly brackets :) I'd prefer to keep them

**Review by HenrikHartiala — APPROVED** [review]
Great! :+1: 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-:-N685M2K4L3P-JQ_1npW:b-y7mvi9)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

___
*[`ui/src/graphql/resultMappers.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/249#-N67vPMR9gjCHVR1nqpv:-N685C4V4wva5tmGV2YW:b-xjgu9s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/84d17179592c5d0cc8ab333747c66919987ccb48/ui/src/graphql/resultMappers.ts#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I could, but this is already pretty hard to read with the curly brackets :) I'd prefer to keep them
</blockquote></details>

True, check!

**Pull request merged**
