### PR TITLE
Test route stop handling

### PR DESCRIPTION
**Pull request by tk-vincit**
Resolves HSLdevcom/jore4[#714](https://github.com/HSLdevcom/jore4-ui/issues/714)

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/326)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 4 of 5 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/326)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @tk-vincit)

___
*[`cypress/e2e/routeStops.cy.ts` line 182 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLlA8E9Du7TYURIz5-:-NBLlA8E9Du7TYURIz50:b70sn1c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/e2e/routeStops.cy.ts#L182)):*
> ```XML
>     // Yes, it would be more elegant to split this test into 2, but running
>     // two test cases instead of one would take more than wait time here. :)
>     cy.wait(750); // eslint-disable-line cypress/no-unnecessary-waiting
> ```

You can add an assertion about the added stop instead of waiting a random amount of time, so that it waits until the stop is added. You can achieve this by checking the color of the background (not that viable), adding the `belongsToRoute` somehow to the testId, or simply by first toggling the `unused stops` and then checking that the row exists.
```
    lineDetailsPage.toggleUnusedStops();
    lineDetailsPage.getStopRow(stops[2].label).contains(stops[2].label);

```
Although in this case you need to add another `lineDetailsPage.toggleUnusedStops();` after these lines, or change the last assertion so that it doesn't find the removed stop.
___
*[`cypress/pageObjects/LineDetailsPage.ts` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLnuQfE5cBhKxtd2Qo:-NBLnuQfE5cBhKxtd2Qp:bcv502w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a93989edd753908baa475a349192fe8886dd8245/cypress/pageObjects/LineDetailsPage.ts#L25)):*
> ```XML
>     return cy.getByTestId(`RouteStopsRow::${stopId}`);
>   }
> ```

Nice :+1: 
___
*[`cypress/support/commands.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLo6jh08Qe5Cnu-_7v:-NBLo6jh08Qe5Cnu-_7w:b-fmgyeb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a93989edd753908baa475a349192fe8886dd8245/cypress/support/commands.ts#L31)):*
> ```XML
> });
> 
> Cypress.Commands.add(
> ```

Does this work when chained more than once?

So can I use this for example to find an element within an element within an element?

```
cy.findByTestId('FooContainer')
  .findByTestId('SomeElementInsideFooContainer')
  .findByTestId('Bar')
```
So does this find the `Bar` testId element _only_ if it is within those two other elements.
___
*[`ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLpnRe2t9iv4HOo7ch:-NBLpnRe2t9iv4HOo7ci:b-isp9w9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2cea2ae81096a022a2a78358adcd2f24b9da5cbc/ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L17)):*
> ```XML
>   routeId: UUID;
>   onAddToRoute: (stopLabel: string) => void;
>   onRemoveFromRoute: (stopLabel: string) => void;
> ```

Nice, thanks for this change!

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/326)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @tk-vincit)

___
*[`cypress/e2e/routeStops.cy.ts` line 149 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLrf5e7DAe6K_HAZgZ:-NBLrf5e7DAe6K_HAZg_:b-dmpxt4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/e2e/routeStops.cy.ts#L149)):*
> ```XML
>   });
>   it('Verify that stops of route are shown on its list view', () => {
>     // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
> ```

let's rather fix the route_route_insert_input type in schemaloader.ts to have the label as a required field
___
*[`cypress/pageObjects/LineDetailsPage.ts` line 12 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLs9f6BxDqdogouDUf:-NBLs9f6BxDqdogouDUg:bu6baup) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/pageObjects/LineDetailsPage.ts#L12)):*
> ```XML
>   }
> 
>   getRouteSection(routeLabel: string) {
> ```

getRouteHeaderByLabel would be a more fitting name..?

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/326)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`cypress/e2e/routeStops.cy.ts` line 149 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLrf5e7DAe6K_HAZgZ:-NBMlPJv7CGlr6VegtSi:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/e2e/routeStops.cy.ts#L149)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's rather fix the route_route_insert_input type in schemaloader.ts to have the label as a required field
</blockquote></details>

Done.
___
*[`cypress/e2e/routeStops.cy.ts` line 182 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLlA8E9Du7TYURIz5-:-NBMnnk9ELxIeM3lH3IM:bco4cm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/e2e/routeStops.cy.ts#L182)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You can add an assertion about the added stop instead of waiting a random amount of time, so that it waits until the stop is added. You can achieve this by checking the color of the background (not that viable), adding the `belongsToRoute` somehow to the testId, or simply by first toggling the `unused stops` and then checking that the row exists.
```
    lineDetailsPage.toggleUnusedStops();
    lineDetailsPage.getStopRow(stops[2].label).contains(stops[2].label);

```
Although in this case you need to add another `lineDetailsPage.toggleUnusedStops();` after these lines, or change the last assertion so that it doesn't find the removed stop.
</blockquote></details>

Excellent point! Didn't realized workaround for this arbitrary waiting is so easy. Re-worked this so should be fixed now.
___
*[`cypress/pageObjects/LineDetailsPage.ts` line 12 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLs9f6BxDqdogouDUf:-NBMw4tH8HXWMHLRQL2n:bglwk6u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/pageObjects/LineDetailsPage.ts#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

getRouteHeaderByLabel would be a more fitting name..?
</blockquote></details>

Improved name a bit. Do we want to add ByLabel postfix? If yes, then I guess it should be added to ~all member functions in this page object.
___
*[`cypress/support/commands.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLo6jh08Qe5Cnu-_7v:-NBMo9RvEcaLi_rd-KXD:b-us7w0t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a93989edd753908baa475a349192fe8886dd8245/cypress/support/commands.ts#L31)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Does this work when chained more than once?

So can I use this for example to find an element within an element within an element?

```
cy.findByTestId('FooContainer')
  .findByTestId('SomeElementInsideFooContainer')
  .findByTestId('Bar')
```
So does this find the `Bar` testId element _only_ if it is within those two other elements.
</blockquote></details>

Not 100% sure about all use cases, but I guess that it should work assuming those elements are nested as you suggested.

E.g. in the case of this pr:
```
lineDetailsPage
      .getStopRow(stops[1].label)
      .findByTestId('StopActionsDrowdown::menu')
      .click()
      .findByTestId('StopActionsDrowdown::removeStopFromRouteButton')
      .click();
```
Wont work but it fails like this:
```
Timed out retrying after 10000ms: Expected to find element: [data-testid="StopActionsDrowdown::removeStopFromRouteButton"], but never found it. Queried from element: <button#headlessui-menu-button-7.mx-auto.flex.items-center.px-3.focus:outline-none>
```

but in the other hand
```
lineDetailsPage
      .getStopRow(stops[1].label)
      .findByTestId('StopActionsDrowdown::menu')
      .click()
      .getByTestId('StopActionsDrowdown::removeStopFromRouteButton')
      .click();
``` 
works. Actually second getByTestId finds _all_ buttons with given test id from the dom, but because only one of those exists that is OK.

**Review by HenrikHartiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/326)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`cypress/e2e/routeStops.cy.ts` line 182 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLlA8E9Du7TYURIz5-:-NBRFSLJ8P1n8-3HvV2k:bcv502w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/e2e/routeStops.cy.ts#L182)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Excellent point! Didn't realized workaround for this arbitrary waiting is so easy. Re-worked this so should be fixed now.
</blockquote></details>

Nice :+1: 
___
*[`cypress/support/commands.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLo6jh08Qe5Cnu-_7v:-NBREicfDiReWQpHFfPp:bm4s58h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a93989edd753908baa475a349192fe8886dd8245/cypress/support/commands.ts#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not 100% sure about all use cases, but I guess that it should work assuming those elements are nested as you suggested.

E.g. in the case of this pr:
```
lineDetailsPage
      .getStopRow(stops[1].label)
      .findByTestId('StopActionsDrowdown::menu')
      .click()
      .findByTestId('StopActionsDrowdown::removeStopFromRouteButton')
      .click();
```
Wont work but it fails like this:
```
Timed out retrying after 10000ms: Expected to find element: [data-testid="StopActionsDrowdown::removeStopFromRouteButton"], but never found it. Queried from element: <button#headlessui-menu-button-7.mx-auto.flex.items-center.px-3.focus:outline-none>
```

but in the other hand
```
lineDetailsPage
      .getStopRow(stops[1].label)
      .findByTestId('StopActionsDrowdown::menu')
      .click()
      .getByTestId('StopActionsDrowdown::removeStopFromRouteButton')
      .click();
``` 
works. Actually second getByTestId finds _all_ buttons with given test id from the dom, but because only one of those exists that is OK.
</blockquote></details>

Yeah, so that is something that needs to be kept in mind. So if the second getByTestId finds all buttons with the given test Id from DOM, it means that chaining these won't exclude the ones that are found but not within the first getByTestId.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/326)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`cypress/pageObjects/LineDetailsPage.ts` line 12 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/326#-NBLs9f6BxDqdogouDUf:-NBR_zh8BMwVfu3WJfgV:bpqbyow) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0dfa72ad7710f5965425753ec33599ea173690f9/cypress/pageObjects/LineDetailsPage.ts#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Improved name a bit. Do we want to add ByLabel postfix? If yes, then I guess it should be added to ~all member functions in this page object.
</blockquote></details>

I could live with this... :)

**Pull request merged**
