### PR TITLE
Use same role headers for Hasura & Hastus requests

### PR DESCRIPTION
**Pull request by culka**
Create one auth setup for requests to both Hasura and Hastus converter

Resolves https://github.com/HSLdevcom/jore4/issues/1370

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`ui/src/api/hastus.ts` line 49 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641#-NazuOsP1QVvi3hKgN3Z:-NazuOsP1QVvi3hKgN3_:b-yyq7ab) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f1c6e1a2180ff99848af2a39056d98f9989736a9/ui/src/api/hastus.ts#L49)):*
> ```XML
>       'Content-Type': 'text/csv',
>       // TODO: Authenticate properly
>       'x-hasura-admin-secret': 'hasura',
> ```

This is not fixed yet. Admin secret still exposed.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`ui/src/api/hastus.ts` line 49 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641#-NazuOsP1QVvi3hKgN3Z:-Nb-GVt-0s_nX4ky8WUo:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f1c6e1a2180ff99848af2a39056d98f9989736a9/ui/src/api/hastus.ts#L49)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This is not fixed yet. Admin secret still exposed.
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`ui/src/api/hastus.ts` line 48 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641#-Nb-QnMC8WdpcEeaf58p:-Nb-QnMC8WdpcEeaf58q:bnq7mkj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1263f32aaa25a26d0333b5ad380475c3b0cf7265/ui/src/api/hastus.ts#L48)):*
> ```XML
>     headers: {
>       ...roleHeaderMap(userHasuraRole),
>       ...{ 'Content-Type': 'text/csv' },
> ```

Is `...{ }` wrapping really needed`.

It looks to me that it could be unnecessary.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
