### PR TITLE
Add type of line field to line

### PR DESCRIPTION
**Pull request by eleksi**
Resolves  HSLdevcom/jore4#523

This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/135)

### CODE REVIEW

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/135)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[src/components/forms/EnumDropdown.tsx, line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MznkOt39gNeVIPDoDnT:-MznkOt39gNeVIPDoDnU:b-4maerf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/eb5085482f537a270a56c7e197c7080ea64ea66c/src/components/forms/EnumDropdown.tsx#L15)):*
> ```XML
> }
> 
> export const EnumDropdown = ({
> ```

If this seems like a weird abstraction, I can try to come up with something better. Ideas are welcome on how general dropdown component we want to make out of this.

**Review by pallost — CHANGES_REQUESTED** [review]
E2E tests are broken. You should comment on the PR why/where and notify Joonas that the tests will need fixing

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-:-MzsmKBA5VjhdQr7m6-a:b4hj9zs)* status: 0 of 13 files reviewed, 10 unresolved discussions (waiting on @eleksi and @pallost)

___
*[docker/docker-compose.custom.yml, line 6 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzsmcP_0qLu9WpwgaIy:-MzsmcP_0qLu9WpwgaIz:bkgeujy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/docker/docker-compose.custom.yml#L6)):*
> ```YAML
>     # Link to available jore4-hasura images in Docker Hub:
>     # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
>     image: 'hsldevcom/jore4-hasura:seed-type-of-line--20220404-3b57b12f69ce7725318834714699f9d4554d9d4c'
> ```

it's usually a good practice to do the hasura updates and the related graphql code generation in its own commit. Not needed to do for this PR but let's try to do this in the future!
___
*[src/components/forms/EnumDropdown.tsx, line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MznkOt39gNeVIPDoDnT:-Mzsn6ruBm81E8xc4qJk:b-3k4wxw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/eb5085482f537a270a56c7e197c7080ea64ea66c/src/components/forms/EnumDropdown.tsx#L15)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

If this seems like a weird abstraction, I can try to come up with something better. Ideas are welcome on how general dropdown component we want to make out of this.
</blockquote></details>

I know, javascript/typescript doesn't handle enums too well... If you want to have this with slightly better typing, then you could do the following:
```
// add this function to src/utils/enum.ts
export function getEnumValues(inputEnum: Object): string[] {
  return Object.values(inputEnum).filter(
    (value) => typeof value === 'string',
  ) as string[];
}

then:
export interface EnumDropdownProps<TEnum> extends FormInputProps {
  testId?: string;
  enumType: TEnum,
...
}

then: (jepp, Enums are Objects...)
export const EnumDropdown<TEnum extends Object> = ({testId, enumType, ...}: EnumDropdownProps<TEnum>) => {
  const values = getEnumValues(enumType);
}
```
___
*[src/components/forms/EnumDropdown.tsx, line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzsn0u27CGNC7EjSW5e:-Mzsn0u30OCyNkjUQwja:b-69rqbi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/EnumDropdown.tsx#L9)):*
> ```XML
> 
> export interface EnumDropdownProps extends FormInputProps {
>   id?: string;
> ```

there's no point using 'id' for reusable components. Let's rather use "testId"
___
*[src/components/forms/EnumDropdown.tsx, line 11 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzsprNVDdjxApvQ_Fov:-MzsprNVDdjxApvQ_Fow:bntqbqi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/EnumDropdown.tsx#L11)):*
> ```XML
>   id?: string;
>   values: string[];
>   translationPrefix: string;
> ```

this translationPrefix is actually a pretty nice idea! :) On the other hand, you'll anyway need a mapping function at various places that prints the enum value in a human readable format... See e.g. `mapPriorityToUiName()` that should be used all around the codebase, but currently every place that wants to print the name of the priority, implements it itself...

Anyhow, it'd be better to have specific (but more reusable) mapVehicleModeToUiName, mapLineTypeToUiName, etc functions in `uiNameMappings.ts` and this component could take a `uiNameMapper` function instead of the `translationPrefix` string
___
*[src/components/forms/LinePropertiesForm.tsx, line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzsoh4X1Fu6hVjPSBUX:-Mzsoh4Y5BJd2IC-hWO3:b3prryy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/LinePropertiesForm.tsx#L12)):*
> ```XML
>   finnishName: z.string().min(1),
>   primaryVehicleMode: z.string().nonempty(),
>   typeOfLine: z.string().nonempty(),
> ```

this should rather be `z.enum()` or `z.nativeEnum()`
See:
https://github.com/colinhacks/zod#zod-enums
https://github.com/colinhacks/zod#native-enums
___
*[src/components/forms/LineTypeDropdown.tsx, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzspNdIEHxsuHUu3-T7:-MzspNdIEHxsuHUu3-T8:b354zw7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/LineTypeDropdown.tsx#L7)):*
> ```XML
> 
> interface Props extends FormInputProps {
>   id?: string;
> ```

we've rather been using testIds instead of HTML ids
___
*[src/components/forms/LineTypeDropdown.tsx, line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzspTjI95jsWUDuuGnz:-MzspTjI95jsWUDuuGo-:b-4l330e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/LineTypeDropdown.tsx#L17)):*
> ```XML
>       // eslint-disable-next-line react/jsx-props-no-spreading
>       {...props}
>       values={Object.values(RouteTypeOfLineEnum)}
> ```

the Object.values() for an enum by default also returns the numeric labels if I remember correctly. Should rather use the `getEnumValues()` util function I pasted before ^
___
*[src/components/forms/VehicleModeDropdown.tsx, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzspiZZ7VTvRbPz9_RU:-MzspiZZ7VTvRbPz9_RV:bg1cgyg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/VehicleModeDropdown.tsx#L7)):*
> ```XML
> 
> interface Props extends FormInputProps {
>   id?: string;
> ```

shouldn't we also use testIds here...?
___
*[src/components/forms/VehicleModeDropdown.tsx, line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzspm325-BJCLlYwGqW:-Mzspm325-BJCLlYwGqX:bg1x5sl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/VehicleModeDropdown.tsx#L17)):*
> ```XML
>       // eslint-disable-next-line react/jsx-props-no-spreading
>       {...props}
>       values={Object.values(ReusableComponentsVehicleModeEnum)}
> ```

getEnumValues()
___
*[src/components/routes-and-lines/AdditionalInformation.tsx, line 43 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzsqNc94koMQj52b0Df:-MzsqNc94koMQj52b0Dg:b-gm7sji) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/routes-and-lines/AdditionalInformation.tsx#L43)):*
> ```XML
>           className="w-1/4"
>           fieldName={t('lines.linesType')}
>           value={t(`lineTypeEnum.${line.type_of_line}`)}
> ```

let's rather refactor this to its own function instead of writing it inline. Otherwise it'll be easily forgotten here... Also, I'm pretty sure that that function is going to be globally reused whenever we want to print the line type to other places too. See example: `mapPriorityToUiName`

**Comment by eleksi** [comment]
@jpeuralinna This PR breaks e2e tests. New required field `type_of_line` has been added to line.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/135)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[src/components/forms/EnumDropdown.tsx, line 2 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzth5z8BrDQrK0gyQAR:-Mzth5z8BrDQrK0gyQAS:bxjtkzi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/45da594556787d62a56ee5be5e816763ccc8e8cb/src/components/forms/EnumDropdown.tsx#L2)):*
> ```XML
> import { FormInputProps, Listbox } from '../../uiComponents';
> import { getEnumValues } from '../../utils/enum';
> ```

could put it to utils/index.ts

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/135)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[docker/docker-compose.custom.yml, line 6 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzsmcP_0qLu9WpwgaIy:-Mzt1VMHAEzJ6Bm4coy4:b-ob61y0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/docker/docker-compose.custom.yml#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's usually a good practice to do the hasura updates and the related graphql code generation in its own commit. Not needed to do for this PR but let's try to do this in the future!
</blockquote></details>

I was considering it, but then I thought that these changes are so closely related to the changed graphql schema that they are part of the same change. I will do it in the future.
___
*[src/components/forms/EnumDropdown.tsx, line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzsn0u27CGNC7EjSW5e:-Mzt1yav1Vw8vM3QCcSl:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/EnumDropdown.tsx#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there's no point using 'id' for reusable components. Let's rather use "testId"
</blockquote></details>

Done.
___
*[src/components/forms/EnumDropdown.tsx, line 11 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzsprNVDdjxApvQ_Fov:-MztEBl627P3pmMP3Azn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/EnumDropdown.tsx#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this translationPrefix is actually a pretty nice idea! :) On the other hand, you'll anyway need a mapping function at various places that prints the enum value in a human readable format... See e.g. `mapPriorityToUiName()` that should be used all around the codebase, but currently every place that wants to print the name of the priority, implements it itself...

Anyhow, it'd be better to have specific (but more reusable) mapVehicleModeToUiName, mapLineTypeToUiName, etc functions in `uiNameMappings.ts` and this component could take a `uiNameMapper` function instead of the `translationPrefix` string
</blockquote></details>

Done.
___
*[src/components/forms/EnumDropdown.tsx, line 2 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzth5z8BrDQrK0gyQAR:-MztnZxl2UACiyv_yJyj:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/45da594556787d62a56ee5be5e816763ccc8e8cb/src/components/forms/EnumDropdown.tsx#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could put it to utils/index.ts
</blockquote></details>

Done.
___
*[src/components/forms/LinePropertiesForm.tsx, line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzsoh4X1Fu6hVjPSBUX:-MztEkR1-wwlWL6HNZXL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/LinePropertiesForm.tsx#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should rather be `z.enum()` or `z.nativeEnum()`
See:
https://github.com/colinhacks/zod#zod-enums
https://github.com/colinhacks/zod#native-enums
</blockquote></details>

Done.
___
*[src/components/forms/LineTypeDropdown.tsx, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzspNdIEHxsuHUu3-T7:-MztEova69IWMZqe7EMo:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/LineTypeDropdown.tsx#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we've rather been using testIds instead of HTML ids
</blockquote></details>

Done.
___
*[src/components/forms/LineTypeDropdown.tsx, line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzspTjI95jsWUDuuGnz:-MztEqTR3_SXpyt7JmMD:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/LineTypeDropdown.tsx#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the Object.values() for an enum by default also returns the numeric labels if I remember correctly. Should rather use the `getEnumValues()` util function I pasted before ^
</blockquote></details>

Done.
___
*[src/components/forms/VehicleModeDropdown.tsx, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzspiZZ7VTvRbPz9_RU:-MztEtbB0TUQXibcuqx1:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/VehicleModeDropdown.tsx#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

shouldn't we also use testIds here...?
</blockquote></details>

Done.
___
*[src/components/forms/VehicleModeDropdown.tsx, line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-Mzspm325-BJCLlYwGqW:-MztEvOZ07WeIXe_zP6r:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/forms/VehicleModeDropdown.tsx#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

getEnumValues()
</blockquote></details>

Done.
___
*[src/components/routes-and-lines/AdditionalInformation.tsx, line 43 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/135#-MzsqNc94koMQj52b0Df:-MztI7kB4qRRB4LeriRc:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b8e4c0d7104688db4c7b52ed6ec707e982bb2187/src/components/routes-and-lines/AdditionalInformation.tsx#L43)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's rather refactor this to its own function instead of writing it inline. Otherwise it'll be easily forgotten here... Also, I'm pretty sure that that function is going to be globally reused whenever we want to print the line type to other places too. See example: `mapPriorityToUiName`
</blockquote></details>

Done.

**Pull request merged**
