### PR TITLE
Add stop types to stop details page header

### PR DESCRIPTION
**Pull request by Leitsi**
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-Nu35ThaA1XZc0RM34ax:-Nu35ThaA1XZc0RM34ay:b5lrn51) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/29e838c8015c2a9b911c64c01a6368c01be1bb66/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L12)):*
> ```XML
>   const { t } = useTranslation();
>   return (
>     <div className="my-2 flex items-center">
> ```

Even though this is probably a "one time used component", I'd still give the margin as props from outside of the component. Component should only be responsible for its inner layout. 
The other benefit of this pattern is that when you define the margins in the parent component, you might see a pattern there and then instead of giving margin to each component separately, you could probably give one "space-y-<number>" for the parent component. The simpler the styles are, the easier it is to make changes also.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-Nu35ThaA1XZc0RM34ax:-NuiNX057eEun_iaOkr9:b-7l7jpg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/366bc17e2238d361728f3ee8b5603b3b3cca1f16/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L12)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Even though this is probably a "one time used component", I'd still give the margin as props from outside of the component. Component should only be responsible for its inner layout. 
The other benefit of this pattern is that when you define the margins in the parent component, you might see a pattern there and then instead of giving margin to each component separately, you could probably give one "space-y-<number>" for the parent component. The simpler the styles are, the easier it is to make changes also.
</blockquote></details>

Done. Kept as margin for now.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797)* status: all files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 20 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-NuxdcLh8uIT4yKWJ5Im:-NuxdcLh8uIT4yKWJ5In:b-yn63jn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7190050202a11d96503cb89b8131c63e1c02b235/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L20)):*
> ```XML
> 
>   return (
>     <div className={`flex items-center ${className}`}>
> ```

btw, here the `items-center` does nothing here

(also these comments related to the comment below)
___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 21 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-Nuxdx0mAmKAbMw-VSZO:-Nuxdx0nC5SM4HMiEW7o:banrkp1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7190050202a11d96503cb89b8131c63e1c02b235/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L21)):*
> ```XML
>   return (
>     <div className={`flex items-center ${className}`}>
>       <div className="flex gap-5">
> ```

but if you add it here, it should solve the problem what is being fixed below with the negative margin.
___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 39 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-NuxdEQA23zR8BU2VCZF:-NuxdEQB6I__zib0lfqO:b-26ufaw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7190050202a11d96503cb89b8131c63e1c02b235/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L39)):*
> ```XML
>         />
>         {stopState && stopState !== StopPlaceState.InOperation && (
>           <div className="-mt-1 rounded-md bg-dark-grey py-1 px-4 text-center text-sm uppercase leading-normal text-white">
> ```

This negative margin feels like a hack. I think by giving `items-center` to parent div  probably achieves the thing you were after.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 21 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-Nuxdx0mAmKAbMw-VSZO:-Nv0MgKR722J0m6TveOW:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7190050202a11d96503cb89b8131c63e1c02b235/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L21)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

but if you add it here, it should solve the problem what is being fixed below with the negative margin.
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 39 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-NuxdEQA23zR8BU2VCZF:-Nv0Mhv9-BJTYWIs1NjB:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7190050202a11d96503cb89b8131c63e1c02b235/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L39)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This negative margin feels like a hack. I think by giving `items-center` to parent div  probably achieves the thing you were after.
</blockquote></details>

Done.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx` line 21 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/797#-Nuxdx0mAmKAbMw-VSZO:-Nv0RXEU1sTwu4UZUQd1:b-7m36bf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7190050202a11d96503cb89b8131c63e1c02b235/ui/src/components/stop-registry/stops/stop-details/StopHeaderSummaryRow.tsx#L21)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

noice

**Pull request merged**
