### PR TITLE
Add testing frameworks + example tests for frontend

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/4)

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
I understood very little of this, but at least I didn't find anything to complain about. Someone else should check this out too.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 7 of 7 files at r4, 7 of 7 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-:-MYiHXpwELD09DEO0TSk:b33opcm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tk-vincit)

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/4)* status: all files reviewed, 7 unresolved discussions (waiting on @tk-vincit)

___
*[package.json, line 6 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiGrBKBkHzaJhQkzbQ:-MYiGrBKBkHzaJhQkzbR:b459fni) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/package.json#L6)):*
> ```JSON
>   "private": true,
>   "scripts": {
>     "dev": "next dev",
> ```

shouldn't this script be called `start` instead to follow the npm standard?
___
*[package.json, line 13 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiGduBDuc3Ox1m7qeo:-MYiGduBDuc3Ox1m7qep:b3zfthr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/package.json#L13)):*
> ```JSON
>     "lint": "eslint './src/**/*.{ts,tsx}' --max-warnings=0",
>     "test": "jest --ci",
>     "qa": "yarn --forzen-lockfile && yarn ts:check && yarn prettier:check && yarn lint && yarn test",
> ```

frozen-lockfile
___
*[README.md, line 29 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiHDG864O3tWOE8pZk:-MYiHDG864O3tWOE8pZl:b-bvjn9j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/README.md#L29)):*
> ```Markdown
> This way code magically stays neatly formatted and you don't have to do anything about it by yourself.
> If you want to run prettier manually for some reason you can run `yarn prettier` (for writing changes) or `yarn prettier:check` (for making sure that code is formatted as prettier wants, but without modifying anything).
> ```

could mention that the vscode `esbenp.prettier-vscode` plugin works well to do this automatically
___
*[README.md, line 33 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiHLpM8sqXBEqgTkAG:-MYiHLpM8sqXBEqgTkAH:b-q2pdqb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/README.md#L33)):*
> ```Markdown
> 
> We have enabled `eslint` with opionated rulesets for keeping code style clean & consistent and for avoiding certain mistakes. Eslint can be run with `yarn lint`. It is highly recommended for developers to use eslint extension with their editors so that they can see linting errors instantly when writing code.
> ```

could mention that the vscode `dbaeumer.vscode-eslint` plugin works well to do this automatically
___
*[tsconfig.json, line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiG5K91-vrDrpkg3gW:-MYiG5K91-vrDrpkg3gX:bixt4il) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/tsconfig.json#L22)):*
> ```jsonc
>     "jsx": "preserve",
>     "paths": {
>       "test-utils": ["utils/test-utils"]
> ```

this only belongs to `tsconfig.test.json`, doesn't it? Actually it makes me wonder that as this is already included in `jest.config.js`, does this need to be included in a `tsconfig` at all?
___
*[tsconfig.test.json, line 4 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiFfZQ7NJETsuILfW4:-MYiFfZR8m9wDN0l_DeU:b-eie4zb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/tsconfig.test.json#L4)):*
> ```JSON
>   "extends": "./tsconfig",
>   "compilerOptions": {
>     "jsx": "react-jsx"
> ```

why is there a different way of compiling jsx for tests? Can't `react-jsx` or `react` be used in the general `tsconfig.json` as well?
___
*[src/utils/test-utils.tsx, line 6 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiI7Wq6nRaf4wA0-G8:-MYiI7Wq6nRaf4wA0-G9:b-4pfyd2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/src/utils/test-utils.tsx#L6)):*
> ```XML
> import React, { FunctionComponent } from 'react';
> 
> const AllTheProviders: FunctionComponent = ({ children }) => {
> ```

should add a comment here that this is to be used to include providers that are to be generally used in all DOM render tests. And could find the providers used by the application from `_app.tsx`

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/4)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[package.json, line 6 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiGrBKBkHzaJhQkzbQ:-MYiaLqN9GwjNd7UkCGK:b-44qh5h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/package.json#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

shouldn't this script be called `start` instead to follow the npm standard?
</blockquote></details>

No.
- This is default behaviour of next.js
- `start` script is generally ambigious. It could e.g. start node server for production, or then it could start app in development mode...
I'd stick to this.
___
*[package.json, line 13 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiGduBDuc3Ox1m7qeo:-MYib0pu65wcbs8-kc8g:b-rdvp80) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/package.json#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

frozen-lockfile
</blockquote></details>

Good catch. Weird that yarn didn't complained about this. :smile: 
___
*[README.md, line 29 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiHDG864O3tWOE8pZk:-MYicSwG9uzhVD3C8Ie7:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/README.md#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could mention that the vscode `esbenp.prettier-vscode` plugin works well to do this automatically
</blockquote></details>

Done.
___
*[README.md, line 33 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiHLpM8sqXBEqgTkAG:-MYicTiu5UAv2k3sfX2U:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/README.md#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could mention that the vscode `dbaeumer.vscode-eslint` plugin works well to do this automatically
</blockquote></details>

Done.
___
*[tsconfig.json, line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiG5K91-vrDrpkg3gW:-MYicVxw5EgX6ukRnbZP:bbuwo8f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/tsconfig.json#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this only belongs to `tsconfig.test.json`, doesn't it? Actually it makes me wonder that as this is already included in `jest.config.js`, does this need to be included in a `tsconfig` at all?
</blockquote></details>

Yes, I would have liked to write this in `tsconfig.test.json`, BUT then `yarn ts:check` complains about TS in .spec files... Of course we could ignore `*.spec.ts/tsx` files in this tsconfig and then include those in `tsconfig.test.json` and then have `ts:check` command to check both cases, but not sure if that is worth the added complexity...
___
*[tsconfig.test.json, line 4 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiFfZQ7NJETsuILfW4:-MYidIYB2O1a7UDV5Z5t:b-yefzzl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/tsconfig.test.json#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

why is there a different way of compiling jsx for tests? Can't `react-jsx` or `react` be used in the general `tsconfig.json` as well?
</blockquote></details>

https://www.typescriptlang.org/docs/handbook/jsx.html
IIRC `preserve` was default for next.js and I wouldn't change it (see the docs). Don't know why it didn't worked with jest...
___
*[src/utils/test-utils.tsx, line 6 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiI7Wq6nRaf4wA0-G8:-MYiffEN1DtQ4gsmsPhU:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/src/utils/test-utils.tsx#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should add a comment here that this is to be used to include providers that are to be generally used in all DOM render tests. And could find the providers used by the application from `_app.tsx`
</blockquote></details>

Done.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/4)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @lassemaatta and @tk-vincit)

___
*[package.json, line 6 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiGrBKBkHzaJhQkzbQ:-MYizNJC1dqOsytwCwX3:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/package.json#L6)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

No.
- This is default behaviour of next.js
- `start` script is generally ambigious. It could e.g. start node server for production, or then it could start app in development mode...
I'd stick to this.
</blockquote></details>

OK
___
*[tsconfig.json, line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiG5K91-vrDrpkg3gW:-MYizietBkzeyRY3JvWV:blpfrqp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/tsconfig.json#L22)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Yes, I would have liked to write this in `tsconfig.test.json`, BUT then `yarn ts:check` complains about TS in .spec files... Of course we could ignore `*.spec.ts/tsx` files in this tsconfig and then include those in `tsconfig.test.json` and then have `ts:check` command to check both cases, but not sure if that is worth the added complexity...
</blockquote></details>

true, not worth it... I just wonder how come the `src/utils/test-utils` then are not in the scope when compiling everything under baseUrl `src`. But if `ts:check` does not work without this addition, leave it be...
___
*[tsconfig.test.json, line 4 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/4#-MYiFfZQ7NJETsuILfW4:-MYj-9WM8e7VXMTu7DPr:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5f515f01bc243876926ae335b3145c1a15303019/tsconfig.test.json#L4)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

https://www.typescriptlang.org/docs/handbook/jsx.html
IIRC `preserve` was default for next.js and I wouldn't change it (see the docs). Don't know why it didn't worked with jest...
</blockquote></details>

OK

**Pull request merged**
