### PR TITLE
Use e2e docker images for tests

### PR DESCRIPTION
**Pull request by culka**
Use e2e docker images for tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`docker/docker-compose.custom.yml` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NsgHeJTCab0sVTiHHtD:-NsgHeJTCab0sVTiHHtE:b-vljae8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/63627f4b9e2a5566930b58bef6e66dd2cf5c8dec/docker/docker-compose.custom.yml#L12)):*
> ```YAML
>     # The :hsl-tag contains the desired version of hsl specific hasura.
>     # Waiting for merging feature-branch to main in hasura-repo
>     image: 'hsldevcom/jore4-hasura:hsl-main--20240307-bd3cfaf806979363d9ecaa74c1631bdf3677e377'
> ```

Could update the hasura submodule as well. Even though nothing changed there, I think it's a good idea to keep it in the same commit as the docker.
___
*[`docker/docker-compose.e2e.yml` line 44 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NsgHkNG7Li9MWD9RDci:-NsgHkNH90TKAsYLoAKq:b7m3jwn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/63627f4b9e2a5566930b58bef6e66dd2cf5c8dec/docker/docker-compose.e2e.yml#L44)):*
> ```YAML
>       file: docker-compose.base.yml
>       service: jore4-hasura-base
>     image: 'hsldevcom/jore4-hasura:hsl-main--20240307-bd3cfaf806979363d9ecaa74c1631bdf3677e377'
> ```

Would be very nice to have some kind of mechanism to ensure we have same docker for dev and test, or at least some warning if they're not. Won't be long otherwise before we forget about this and run into some problems.
___
*[`scripts/start-dependencies.sh` line 75 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NsgHBUxE_oNP6Hr18BX:-NsgHBUxE_oNP6Hr18BY:blme0ch) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/63627f4b9e2a5566930b58bef6e66dd2cf5c8dec/scripts/start-dependencies.sh#L75)):*
> ```Shell
>     e2eServices="jore4-testdb-e2e jore4-hasura-e2e jore4-tiamat-e2e jore4-timetablesapi-e2e"
>   fi
>   echo $DOCKER_COMPOSE_CMD
> ```

This echo is a bit weird by itself, could add some `Running docker compose command: ...` or something?

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`docker/docker-compose.custom.yml` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NsgHeJTCab0sVTiHHtD:-Nsh47JU7AZdbJWwjYSv:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/63627f4b9e2a5566930b58bef6e66dd2cf5c8dec/docker/docker-compose.custom.yml#L12)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could update the hasura submodule as well. Even though nothing changed there, I think it's a good idea to keep it in the same commit as the docker.
</blockquote></details>

Done.
___
*[`docker/docker-compose.e2e.yml` line 44 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NsgHkNG7Li9MWD9RDci:-Nsh4-Rx1EDBIK8MggTc:b97gczu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/63627f4b9e2a5566930b58bef6e66dd2cf5c8dec/docker/docker-compose.e2e.yml#L44)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would be very nice to have some kind of mechanism to ensure we have same docker for dev and test, or at least some warning if they're not. Won't be long otherwise before we forget about this and run into some problems.
</blockquote></details>

Added a script and a github workflow to test this.
___
*[`scripts/start-dependencies.sh` line 75 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NsgHBUxE_oNP6Hr18BX:-Nsh3z859odvUZ93h_3t:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/63627f4b9e2a5566930b58bef6e66dd2cf5c8dec/scripts/start-dependencies.sh#L75)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This echo is a bit weird by itself, could add some `Running docker compose command: ...` or something?
</blockquote></details>

Done.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NshN5Bp8Gl1FnrJVmYi):*




_Suggestion:_
```
checking
```
___
*[`scripts/verify-image-versions-match.sh` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NshOLd60sBGLKce6vQW:-NshOLd60sBGLKce6vQX:bov72ge) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90f34e7800e3056de9c9c4a1187978ff1e491e8d/scripts/verify-image-versions-match.sh#L10)):*
> ```Shell
> do
>   # Find version in custom yml
>   image1=$(grep $item docker/docker-compose.custom.yml | grep 'image:' | sed -r "s/^[[:space:]]*image:[[:space:]]*['\"]${item//\//\\/}--(.*)['\"]/\1/")
> ```

NIT: could name the variables something else than 1 & 2, eg. customImage and e2eImage. Probably wouldn't need the comments then.
___
*[`scripts/verify-image-versions-match.sh` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NshNPyR1HgZZ37UUq5a:-NshNPyR1HgZZ37UUq5b:b2nlfzs) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90f34e7800e3056de9c9c4a1187978ff1e491e8d/scripts/verify-image-versions-match.sh#L19)):*
> ```Shell
>     exit 1
>   fi 
> done
> ```

NIT: Looks like a missing newline at end.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NshN5Bp8Gl1FnrJVmYi):*
:sweat_smile: 
___
*[`scripts/verify-image-versions-match.sh` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NshOLd60sBGLKce6vQW:-NshUqzK2nxpu5TTiIce:b-n9tkhd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90f34e7800e3056de9c9c4a1187978ff1e491e8d/scripts/verify-image-versions-match.sh#L10)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

NIT: could name the variables something else than 1 & 2, eg. customImage and e2eImage. Probably wouldn't need the comments then.
</blockquote></details>

changed
___
*[`scripts/verify-image-versions-match.sh` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-NshNPyR1HgZZ37UUq5a:-NshUsLg4BzCPX7WH6Bv:b-wf0mzx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90f34e7800e3056de9c9c4a1187978ff1e491e8d/scripts/verify-image-versions-match.sh#L19)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

NIT: Looks like a missing newline at end.
</blockquote></details>

:arrow_down:

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/788#-:-NshY_DA4nB3dZ0Kww7m:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved

**Pull request merged**
