### PR TITLE
Add indicator for is used as timing point

### PR DESCRIPTION
**Pull request by Perholehto**
Added indicator for hastus point. Green dot when it's active, when not active text is grey. First commit is refactoring, I noticed that design has no "-" (dash) rendered and UI had those. Now it doesn't render dashes, column is just empty

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 56 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686#-Nh0dkdU9zR4_ZtEO3iG:-Nh0dkdU9zR4_ZtEO3iH:be2jnsd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/20eb8e3d7613227549d9148a2e200070bc240ce1/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L56)):*
> ```XML
>   const hastusCode = stop.timing_place?.label ?? '-';
> 
>   const noHastusCode = '-';
> ```

I would maybe remove the whole `-` from here altogether...



_Suggestion:_
```XML
  const hastusCode = stop.timing_place?.label;
```
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 105 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686#-Nh0drVt7RjKd1ixPHZ6:-Nh0drVt7RjKd1ixPHZ7:b-wrnbwm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/20eb8e3d7613227549d9148a2e200070bc240ce1/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L105)):*
> ```XML
>           <Visible visible={hastusCode !== noHastusCode}>
>             <span>{hastusCode}</span>
>           </Visible>
> ```

... and then we don't need the `noHastusCode` check here.



_Suggestion:_
```XML
          <Visible visible={hastusCode}>
            <span>{hastusCode}</span>
          </Visible>
```

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 56 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686#-Nh0dkdU9zR4_ZtEO3iG:-Nh0hukMEPO-cZwSnljG:be7proh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/20eb8e3d7613227549d9148a2e200070bc240ce1/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L56)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I would maybe remove the whole `-` from here altogether...
</blockquote></details>

Removed this change.
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 105 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686#-Nh0drVt7RjKd1ixPHZ6:-Nh0hzD84wh_GhnSZi2A:be7proh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/20eb8e3d7613227549d9148a2e200070bc240ce1/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L105)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

... and then we don't need the `noHastusCode` check here.
</blockquote></details>

Removed this change.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 56 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686#-Nh0dkdU9zR4_ZtEO3iG:-NhBF7Ce6NtVyt-xxa9x:bdo7x9x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/20eb8e3d7613227549d9148a2e200070bc240ce1/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L56)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Removed this change.
</blockquote></details>

Didn't mean that this change should be removed: was just trying to suggest a different approach on how to omit the `-`.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686#-:-NhBFaOCDsn4JK8FRUdS:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 56 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/686#-Nh0dkdU9zR4_ZtEO3iG:-NhBJC8P09Ubwn96RhOT:bcjyrqv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/20eb8e3d7613227549d9148a2e200070bc240ce1/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L56)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Didn't mean that this change should be removed: was just trying to suggest a different approach on how to omit the `-`.
</blockquote></details>

Yeah, I think there was some communication problems with this. Let's leave this as it was and check with design or maybe just throw it to backlog :smile:

**Pull request merged**
