### PR TITLE
Add UI for canceling timetables import

### PR DESCRIPTION
**Pull request by Leitsi**
Resolves https://github.com/HSLdevcom/jore4/issues/1467

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679)

### CODE REVIEW

**Review by Perholehto — COMMENTED** [review]
Looks good, nothing major to fix

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 3 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679#-:-NgST1U50dbKZHSNUBY0:b-jk0el0)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 26 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679#-NgSR7dJ1QFl3kPyKc27:-NgSR7dJ1QFl3kPyKc28:bu3oy9r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/888e3cc27ea7c031165f07f8cc736597537a2380/ui/src/uiComponents/DialogWithButtons.tsx#L26)):*
> ```XML
>   className?: string;
>   // This should be a Tailwind max-width class: https://tailwindcss.com/docs/max-width
>   widthClassName?: string;
> ```

For me, this name is missing something, maybe something related to that comment. Still, I can't suggest anything better. 
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 43 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679#-NgSP0smBGOss1CUZyFD:-NgSP0sn-TtgXGNAMAbC:b-llfy7u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/888e3cc27ea7c031165f07f8cc736597537a2380/ui/src/uiComponents/DialogWithButtons.tsx#L43)):*
> ```XML
>       open={isOpen}
>       onClose={onCancel}
>       className={`fixed inset-0 z-10 overflow-y-auto bg-black bg-opacity-50 ${className} $`}
> ```

extra `$` ?

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679)* status: all files reviewed, 1 unresolved discussion (waiting on @Perholehto)

___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 26 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679#-NgSR7dJ1QFl3kPyKc27:-NgYF9o_5YMrIfRARPgT:bz5w5or) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/888e3cc27ea7c031165f07f8cc736597537a2380/ui/src/uiComponents/DialogWithButtons.tsx#L26)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

For me, this name is missing something, maybe something related to that comment. Still, I can't suggest anything better.
</blockquote></details>

Don't feel like adding a `tailwind` prefix at least. Nothing really prevents you from using a non-Tailwind class here, though it works best with those, thus the comment.

Think I'll just keep it like this since we don't have a clearly better candidate.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 43 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679#-NgSP0smBGOss1CUZyFD:-NgYFdeZ20cCxRER_O-Y:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/888e3cc27ea7c031165f07f8cc736597537a2380/ui/src/uiComponents/DialogWithButtons.tsx#L43)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

extra `$` ?
</blockquote></details>

:thumbsup:

**Review by Perholehto — COMMENTED** [review]
> Reviewed 7 of 9 files at r8, 4 of 4 files at r9, 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679)* status: 8 of 14 files reviewed, all discussions resolved (waiting on @Leitsi)

**Review by Perholehto — APPROVED** [review]
> Reviewed 3 of 6 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/679)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
