### PR TITLE
Change vehicle schedule frame validity

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 10 of 10 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602)* status: all files reviewed, 5 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/components/timetables/common/ChangeTimetablesValidityForm.tsx` line 93 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVoUkdpAIr2iU3Suc6J:-NVoUkdpAIr2iU3Suc6K:b-khd3lw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/components/timetables/common/ChangeTimetablesValidityForm.tsx#L93)):*
> ```XML
>           </div>
>         </div>
>         <div className="pt-10">
> ```

Not sure if this pt-10 is required, but either way is fine
___
*[`ui/src/components/timetables/common/ChangeTimetablesValidityModal.tsx` line 4 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVoWeXH0niyMe9F5L2g:-NVoWeXH0niyMe9F5L2h:b4arigi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/components/timetables/common/ChangeTimetablesValidityModal.tsx#L4)):*
> ```XML
> import { useTranslation } from 'react-i18next';
> import { useAppDispatch, useAppSelector } from '../../../hooks';
> import { useVehicleScheduleFrameValidity } from '../../../hooks/vehicle-schedule-frame/useVehicleScheduleFrameValidity';
> ```

Probably was already missing when you started working on this branch, but we've been adding these `index.ts` files to export all the files, and then we can just import them all from for example `hooks`

So to do this: add `hooks/vehicle-schedule-frame/index.ts` file containing: `export * from './useVehicleScheduleFrameValidity';`

Then add `export * from './vehicle-schedule-frame'` to `hooks/index.ts`



_Suggestion:_
```XML
import { useAppDispatch, useAppSelector, useVehicleScheduleFrameValidity } from '../../../hooks';
```
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 114 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVo_7d1CD9qXDy2cIgw:-NVo_7d1CD9qXDy2cIgx:b-lqdour) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L114)):*
> ```XML
>       <ChangeTimetablesValidityModal
>         isOpen={changeTimetableValidityModalState.isOpen}
>         onClose={() => dispatch(closeChangeTimetableValidityModalAction())}
> ```

At least at some point we tried to avoid using inline function calls, so my suggestion would be to have separate which then calls the dispatch.
`onCloseTimetableValidityModal`
But, what do you think?



_Suggestion:_
```XML
        onClose={onCloseTimetableValidityModal}
```
___
*[`ui/src/locales/fi-FI/common.json` line 330 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVodOej6kC2xZ-rUBMN:-NVodOej6kC2xZ-rUBMO:b-37d4s4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/locales/fi-FI/common.json#L330)):*
> ```JSON
>     "priority": "Aikataulujen prioriteetti"
>   },
>   "changeTimetablesValidityModal": {
> ```

The english translations seem to be missing from: `ui/src/locales/en-US/common.json`
___
*[`ui/src/redux/slices/modals.ts` line 19 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVoepSM3sgLQ5ArOgbO:-NVoepSM3sgLQ5ArOgbP:bhfw6u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33be999214d7ca42cc5772db940c17b61c12d495/ui/src/redux/slices/modals.ts#L19)):*
> ```XML
>   isOpen: boolean;
>   vehicleScheduleFrameId?: UUID;
>   lastModifiedVehicleScheduleFrameId?: {
> ```

This is now an object containing the Id, validityStart and validityEnd, so would leave out the Id.



_Suggestion:_
```XML
  lastModifiedVehicleScheduleFrame?: {
```

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602)* status: all files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/timetables/common/ChangeTimetablesValidityForm.tsx` line 93 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVoUkdpAIr2iU3Suc6J:-NW7R51Y1y0rIeFK26LJ:b-tiemdx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/components/timetables/common/ChangeTimetablesValidityForm.tsx#L93)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Not sure if this pt-10 is required, but either way is fine
</blockquote></details>

Looks better without, removed.
___
*[`ui/src/components/timetables/common/ChangeTimetablesValidityModal.tsx` line 4 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVoWeXH0niyMe9F5L2g:-NW1nukE5yzNj8HZcbRa:b-fzpbwz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/components/timetables/common/ChangeTimetablesValidityModal.tsx#L4)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Probably was already missing when you started working on this branch, but we've been adding these `index.ts` files to export all the files, and then we can just import them all from for example `hooks`

So to do this: add `hooks/vehicle-schedule-frame/index.ts` file containing: `export * from './useVehicleScheduleFrameValidity';`

Then add `export * from './vehicle-schedule-frame'` to `hooks/index.ts`
</blockquote></details>

:thumbsup: fixed.
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 114 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVo_7d1CD9qXDy2cIgw:-NW2J7omBQjmTR23PWSO:bhj8ngn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L114)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

At least at some point we tried to avoid using inline function calls, so my suggestion would be to have separate which then calls the dispatch.
`onCloseTimetableValidityModal`
But, what do you think?

</blockquote></details>

Yep, sounds good, changing.
___
*[`ui/src/locales/fi-FI/common.json` line 330 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVodOej6kC2xZ-rUBMN:-NW2FAsK5RcC5F4q7Sq_:b-iqkwn8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/locales/fi-FI/common.json#L330)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The english translations seem to be missing from: `ui/src/locales/en-US/common.json`
</blockquote></details>

Fixed. Also added lint for this, in separate PR.
___
*[`ui/src/redux/slices/modals.ts` line 19 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVoepSM3sgLQ5ArOgbO:-NW2IZAO4lGR0KyK_QIs:b-da5vv1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33be999214d7ca42cc5772db940c17b61c12d495/ui/src/redux/slices/modals.ts#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is now an object containing the Id, validityStart and validityEnd, so would leave out the Id.
</blockquote></details>

Yep, forgot to change this. :thumbsup:

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r6, 1 of 1 files at r7, 8 of 13 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/locales/fi-FI/common.json` line 330 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NVodOej6kC2xZ-rUBMN:-NWByWGMAOEtJXD0Zuys:bmd355p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/58ebdfe187e13716ed9f67db8e346bee29d4b99a/ui/src/locales/fi-FI/common.json#L330)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Fixed. Also added lint for this, in separate PR.
</blockquote></details>

That lint addition was a really nice one, thanks!
___
*[`ui/src/redux/slices/modals.ts` line 19 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NWC1viL941ARCU6LYbF:-NWC1viMDbELUtiraXb2:bq4a832) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9bc27e8c545e8c0bc6bb3f23f2f794e5001f108b/ui/src/redux/slices/modals.ts#L19)):*
> ```XML
>   isOpen: boolean;
>   vehicleScheduleFrameId?: UUID;
>   lastModifiedVehicleScheduleFrameId?: {
> ```

If my reviewable isn't working it's magic, this `Id` seems to be still here

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/redux/slices/modals.ts` line 19 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602#-NWC1viL941ARCU6LYbF:-NWC5BZ3CkkIozfCbTK1:b9iv7hl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9bc27e8c545e8c0bc6bb3f23f2f794e5001f108b/ui/src/redux/slices/modals.ts#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

If my reviewable isn't working it's magic, this `Id` seems to be still here
</blockquote></details>

Fixed, again. :thumbsup:

**Review by HenrikHartiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/602)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

**Pull request merged**
