### PR TITLE
Add `redux-toolkit` for state management

### PR DESCRIPTION
**Pull request by tk-vincit**
Minimal implementation in order to be able to continue work
based on this. Refactoring current state management from
React Context Api to redux can be done in later commits.

Related to HSLdevcom/jore4#707

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/132)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/132)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/map/Stops.tsx, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPSDTi95j2BlOz3dZ0:-MzPSDTi95j2BlOz3dZ1:bbkm4wq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/components/map/Stops.tsx#L26)):*
> ```XML
> } from '../../hooks';
> import { useFilterStops } from '../../hooks/useFilterStops';
> import { setSelectedStopId as setSelectedStopIdAction } from '../../redux';
> ```

maybe let's rather do this renaming already within the slice. I bet we'll have lots of code with such pattern:
```
const setX = () => {dispatch(setXAction);}
```
___
*[src/hooks/redux.ts, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPSfHi6QiWzyc0GcBx:-MzPSfHi6QiWzyc0GcBy:b-38ufxn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/hooks/redux.ts#L4)):*
> ```XML
> import { AppDispatch, RootState } from '../redux';
> 
> export const useAppDispatch = () => useDispatch<AppDispatch>();
> ```

I don't see where these are used...? Are they needed at all?
___
*[src/redux/slices/map.ts, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPRzxlCpieufXypKp-:-MzPRzxlCpieufXypKp0:b-prvl7d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/redux/slices/map.ts#L21)):*
> ```XML
> });
> 
> export const { setSelectedStopId } = slice.actions;
> ```

oh, you can generate actions like this? Nice!

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/132)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/redux/store.ts, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPTAkiEwUFeIh_hyUL:-MzPTAkiEwUFeIh_hyUM:b-28h45p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/redux/store.ts#L12)):*
> ```XML
> export type RootState = ReturnType<typeof store.getState>;
> 
> export type AppDispatch = typeof store.dispatch;
> ```

do we need this AppDispatch type anywhere...?

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/132)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[src/components/map/Stops.tsx, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPSDTi95j2BlOz3dZ0:-MzPUSbp1S41BS00gpGZ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/components/map/Stops.tsx#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe let's rather do this renaming already within the slice. I bet we'll have lots of code with such pattern:
```
const setX = () => {dispatch(setXAction);}
```
</blockquote></details>

Done.
___
*[src/hooks/redux.ts, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPSfHi6QiWzyc0GcBx:-MzPT1r5BxTNx0wqhGSF:by0klaf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/hooks/redux.ts#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't see where these are used...? Are they needed at all?
</blockquote></details>

Oh yeah, good point, I guess these should be used in favor or generic `useDispatch` or `useSelector` but seems like I missed that already. :smile: Will update this PR to use these.
___
*[src/redux/store.ts, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPTAkiEwUFeIh_hyUL:-MzPTmqG7LmAvXkx2U_O:btaavjq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/redux/store.ts#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

do we need this AppDispatch type anywhere...?
</blockquote></details>

Well, this was included in quickstart guide so I assume we want to keep this: https://redux-toolkit.js.org/tutorials/quick-start#add-slice-reducers-to-the-store
___
*[src/redux/slices/map.ts, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPRzxlCpieufXypKp-:-MzPUUgl1mZXOX1GkHAx:be5ck22) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/redux/slices/map.ts#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

oh, you can generate actions like this? Nice!
</blockquote></details>

:star_struck:

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/132)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/hooks/redux.ts, line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPSfHi6QiWzyc0GcBx:-MzPVKX46EdsfMSpBHwn:b-19a8dc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/hooks/redux.ts#L4)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Oh yeah, good point, I guess these should be used in favor or generic `useDispatch` or `useSelector` but seems like I missed that already. :smile: Will update this PR to use these.
</blockquote></details>

sure, let's do that then :thumbsup: 
___
*[src/redux/store.ts, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/132#-MzPTAkiEwUFeIh_hyUL:-MzPVFCvEl9ekUQSzZM5:bhcxsv6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/15a47b7213efdf3f24c7e8714e8c3605285dc4a9/src/redux/store.ts#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, this was included in quickstart guide so I assume we want to keep this: https://redux-toolkit.js.org/tutorials/quick-start#add-slice-reducers-to-the-store
</blockquote></details>

yeah and you'll also need this for the custom hook

**Pull request merged**
