### PR TITLE
Create e2e tests for info spot views

### PR DESCRIPTION
**Pull request by suvikankare**
Import and build stop V1562 to tests and import info spot seed data.
Create test for viewing info spots.

This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925)

### CODE REVIEW

**Review by Huulivoide — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @suvikankare)

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925)* status: all files reviewed, 3 unresolved discussions (waiting on @suvikankare)

___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 1504 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-O8qQUB-7n73q7c2shgU:-O8qQUB-7n73q7c2shgV:bqi61bs) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b832591e7735d62d12982387bdb229c6305d1ad0/cypress/e2e/stop-registry/stopDetails.cy.ts#L1504)):*
> ```XML
>         infoSpotView.getLatitude().shouldHaveText('60.16490775039894');
>         infoSpotView.getLongitude().shouldHaveText('24.92904198486008');
>         infoSpotView.getDisplayType().shouldHaveText('Patteri, monirivi');
> ```

In addition to fields that are shown, you should also check that the fields that are conditionally hidden are _not_ shown. Currently these tests would be passing if everthing was just always shown.
So eg. for this info spot 1, check backlight / PosterPlaceSize / maintenance / and so on.
Basically each info spot her eshould have some expect for each `InfoSpotViewCard` page object get field method.
___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 1517 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-O8qOzIR-lVcM7ZIV_d3:-O8qOzIR-lVcM7ZIV_d4:bv6pzws) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b832591e7735d62d12982387bdb229c6305d1ad0/cypress/e2e/stop-registry/stopDetails.cy.ts#L1517)):*
> ```XML
>         infoSpotView.getLabel().shouldHaveText('JP1234569');
>         infoSpotView.getInfoSpotType().shouldHaveText('Äänimajakka');
>         infoSpotView.getPurpose().shouldHaveText('Äänimajakka');
> ```

It might be good if the `purpose` field for this info spot had some other text than the hard coded translation of info spot type just before it. Was wondering why they were the same and had to check that there's no bug here or something.
___
*[`cypress/e2e/utils/tasks.ts` line 217 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-O8qNuQw4Y7xnOPpWcPp:-O8qNuQw4Y7xnOPpWcPq:bez5hz4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b832591e7735d62d12982387bdb229c6305d1ad0/cypress/e2e/utils/tasks.ts#L217)):*
> ```XML
> };
> 
> export const resetStopRegistryDb = async () => {
> ```

Info spots should be cleaned up here as well. Unless they're cascade deleted via stop places (don't think so)?
___
*[`cypress/pageObjects/stop-registry/stop-details/InfoSpotSection.ts` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-O8qMPd4300-QCDuYSSf:-O8qMPd4300-QCDuYSSg:b-whw2u6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b832591e7735d62d12982387bdb229c6305d1ad0/cypress/pageObjects/stop-registry/stop-details/InfoSpotSection.ts#L7)):*
> ```XML
> 
>   getTitle() {
>     return cy.getByTestId('InfoSpotsSection::title');
> ```

Note, the title seems to be a bit broken. It is translated with `title\={t('stopDetails.detailTabs.info', { count: infoSpots.length })}` but the actual text has no count.

Not really part of this PR though.

**Review by suvikankare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @Huulivoide and @Leitsi)

___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 1504 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-O8qQUB-7n73q7c2shgU:-O8v5cAI03NyNKVx7wKR:b-b41ees) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b832591e7735d62d12982387bdb229c6305d1ad0/cypress/e2e/stop-registry/stopDetails.cy.ts#L1504)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

In addition to fields that are shown, you should also check that the fields that are conditionally hidden are _not_ shown. Currently these tests would be passing if everthing was just always shown.
So eg. for this info spot 1, check backlight / PosterPlaceSize / maintenance / and so on.
Basically each info spot her eshould have some expect for each `InfoSpotViewCard` page object get field method.
</blockquote></details>

Added should.('not.exist') in fields that are not shown.
___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 1517 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-O8qOzIR-lVcM7ZIV_d3:-O8v5lyw9btWmMb8jsla:b-7vt4en) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b832591e7735d62d12982387bdb229c6305d1ad0/cypress/e2e/stop-registry/stopDetails.cy.ts#L1517)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

It might be good if the `purpose` field for this info spot had some other text than the hard coded translation of info spot type just before it. Was wondering why they were the same and had to check that there's no bug here or something.
</blockquote></details>

Changed the text in seed data
___
*[`cypress/e2e/utils/tasks.ts` line 217 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-O8qNuQw4Y7xnOPpWcPp:-O8v5pb60qMvEitsZZBm:b-12t65y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b832591e7735d62d12982387bdb229c6305d1ad0/cypress/e2e/utils/tasks.ts#L217)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Info spots should be cleaned up here as well. Unless they're cascade deleted via stop places (don't think so)?
</blockquote></details>

Added todo comment

**Review by Leitsi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/925#-:-O8v9VSNAabMKASGBFk0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @suvikankare)

**Pull request merged**
