### PR TITLE
Automatically serialize all dates from/to graphql to luxon DateTime format

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/118)

Closes https://github.com/HSLdevcom/jore4/issues/612

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
Really nice work!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-:-MyqrGJIENmWPupKGcpW:b-6ptsg3)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[codegen.js, line 43 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqnbxpDm4kgi9Pw78B:-MyqnbxpDm4kgi9Pw78C:b-jth5na) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/codegen.js#L43)):*
> ```JavaScript
>           geography_point: 'GeoJSON.Point',
>           geography_linestring: 'GeoJSON.LineString',
>           timestamptz: 'luxon.DateTime',
> ```

Nice, I was previously wondering how to do this but didn't figured out how. :+1: 
___
*[src/time.ts, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqoTmTDkhlUvPMeyoS:-MyqoTmTDkhlUvPMeyoT:b-b1friq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/time.ts#L8)):*
> ```XML
> Settings.defaultZone = 'Europe/Helsinki';
> 
> export type DateLike = DateTime | string | null;
> ```

I planned to comment "How null is DateLike?", but after reading through this PR I think this is ok...
___
*[src/time.ts, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-Myqoed_0pxqcGU-7CYq:-Myqoed_0pxqcGU-7CYr:bo7dxcv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/time.ts#L11)):*
> ```XML
> 
> export function isDateLike(input?: unknown): input is DateLike {
>   return DateTime.isDateTime(input) || isString(input) || isNil(input);
> ```

isNil seems to return true for `undefined` but that is not covered by `DateLike` type. Is that on purpose or should that be handled separately?

https://lodash.com/docs/4.17.15#isNil
___
*[src/graphql/client.ts, line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqqUl79dFCMa4PeDtW:-MyqqUl79dFCMa4PeDtX:bdt3cjb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/graphql/client.ts#L56)):*
> ```XML
> 
>   const scalarMappingLink = buildScalarMappingLink();
>   const apolloLink = concat(
> ```

Unlucky that we cant `concat(first, second, third)`. Anyway, seems like `concat(first, second).concat(third)`is allowed (but didin't verified if it actually works...). Would that be easier to read?
___
*[src/hooks/useEditLine.ts, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqpjSV14KjQ9ZPqIwf:-MyqpjSV14KjQ9ZPqIwg:ba56jro) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/hooks/useEditLine.ts#L33)):*
> ```XML
>         label: form.label,
>         priority: form.priority,
>         // this form value always exists
> ```

Just pointing out that VSCode intellisense shows following comment for validity_start, I assume it comes from hasura:
`The point in time when the line becomes valid. If NULL, the line has been always valid.`
So is there a change that this still could be null or is this mistake in documentation?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/118)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @tk-vincit)

___
*[codegen.js, line 43 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqnbxpDm4kgi9Pw78B:-MyulFZm7yE-8htjBSJ2:b-1bjpmn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/codegen.js#L43)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Nice, I was previously wondering how to do this but didn't figured out how. :+1: 
</blockquote></details>

thanks :)
___
*[src/time.ts, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqoTmTDkhlUvPMeyoS:-MyulJzeDMwKY_-7Ce5s:biqpoce) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/time.ts#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I planned to comment "How null is DateLike?", but after reading through this PR I think this is ok...
</blockquote></details>

yeah, removed null in the end
___
*[src/time.ts, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-Myqoed_0pxqcGU-7CYq:-MyvRHMyD2r-EPRgUKKQ:b-sl9cp2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/time.ts#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

isNil seems to return true for `undefined` but that is not covered by `DateLike` type. Is that on purpose or should that be handled separately?

https://lodash.com/docs/4.17.15#isNil
</blockquote></details>

removed `null` from the DateLik type in the end...
___
*[src/graphql/client.ts, line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqqUl79dFCMa4PeDtW:-MyunM328NmPhTXDaOsK:bkbb3de) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/graphql/client.ts#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Unlucky that we cant `concat(first, second, third)`. Anyway, seems like `concat(first, second).concat(third)`is allowed (but didin't verified if it actually works...). Would that be easier to read?
</blockquote></details>

actually found a function called `from` to just concatenate them all. Also moved the scalarMappingLink to its own file for clarity
___
*[src/hooks/useEditLine.ts, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqpjSV14KjQ9ZPqIwf:-MyvRYSODVgn-T7h91SV:bb6obum) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/hooks/useEditLine.ts#L33)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Just pointing out that VSCode intellisense shows following comment for validity_start, I assume it comes from hasura:
`The point in time when the line becomes valid. If NULL, the line has been always valid.`
So is there a change that this still could be null or is this mistake in documentation?
</blockquote></details>

well, I'll now set it to default to 1970, no better idea...

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/118)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/time.ts, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-Myqoed_0pxqcGU-7CYq:-Myv_VNz6OLVgNOFSw27:bsxwy2d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/time.ts#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

removed `null` from the DateLik type in the end...
</blockquote></details>

now e.g. `"invalid"` is datelike. Should we also validate that string is either empty (is that needed?) or something that can be parsed as a date?
___
*[src/components/routes-and-lines/LineDetailsPage.tsx, line 99 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-Myva3oH6QxNGGj-T0lC:-Myva3oH6QxNGGj-T0lD:b-ttdjdw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7048b291ca3e60429295daafa0145319f20a6dc4/src/components/routes-and-lines/LineDetailsPage.tsx#L99)):*
> ```XML
> 
>   const buildValidityPeriod = (
>     validityStart?: DateLike | null,
> ```

Asking same thing as in slack today: can validityStart be null? :) 
___
*[src/graphql/client.ts, line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqqUl79dFCMa4PeDtW:-Myvb5XEBfMRAq8LiTA2:b-wkez58) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/graphql/client.ts#L56)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually found a function called `from` to just concatenate them all. Also moved the scalarMappingLink to its own file for clarity
</blockquote></details>

scalarMappingLink seems to be in this file, so did you forgot to move it?
___
*[src/hooks/useEditLine.ts, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqpjSV14KjQ9ZPqIwf:-MyvauVvAsG8XscVFM1C:bhnjnd0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/hooks/useEditLine.ts#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

well, I'll now set it to default to 1970, no better idea...
</blockquote></details>

Not sure if default value is good or bad thing to have here, but ok :shrug:

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/118)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[src/time.ts, line 11 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-Myqoed_0pxqcGU-7CYq:-Myvcyy_2AcKpgjPIch8:b-esq4s6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/time.ts#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

now e.g. `"invalid"` is datelike. Should we also validate that string is either empty (is that needed?) or something that can be parsed as a date?
</blockquote></details>

unfortunately can't know if the input is a valid date before actually doing the parsing... I'd keep it like this for now, the aim is just to have a type for inputs that could be possibly parsed into dates...
___
*[src/components/routes-and-lines/LineDetailsPage.tsx, line 99 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-Myva3oH6QxNGGj-T0lC:-MyvdVqICfz0maO53R1V:b-lo9l1o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7048b291ca3e60429295daafa0145319f20a6dc4/src/components/routes-and-lines/LineDetailsPage.tsx#L99)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Asking same thing as in slack today: can validityStart be null? :) 
</blockquote></details>

I honestly don't know anymore, I'll just prepare for the worst :P
___
*[src/graphql/client.ts, line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqqUl79dFCMa4PeDtW:-MyvdaD43Bw7RL8hdIGs:b-apjnvh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/graphql/client.ts#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

scalarMappingLink seems to be in this file, so did you forgot to move it?
</blockquote></details>

actually decided to move it back here, sorry :D
___
*[src/hooks/useEditLine.ts, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/118#-MyqpjSV14KjQ9ZPqIwf:-MyvdlA5Cnw_NtuoK7pC:b-k6cl0g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e14f35776bf907e87fba8d06e239d11e6533d9d/src/hooks/useEditLine.ts#L33)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if default value is good or bad thing to have here, but ok :shrug: 
</blockquote></details>

checkLineValidity doesn't allow undefined or null values for now... I don't have the bandwidth to fix this now

**Pull request merged**
