### PR TITLE
Add warnings about duplicate journeys when importing timetables by combining

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754)

### CODE REVIEW

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/locales/fi-FI/common.json` line 419 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754#-NmogBUt0VdVP8KnQGjz:-NmogBUt0VdVP8KnQGk-:bbmhyg2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f5c8ced4e6767504f2c552ff6b81adce0d24fb3d/ui/src/locales/fi-FI/common.json#L419)):*
> ```JSON
>       "validityStarts": "Alkaa",
>       "validityEnds": "Päättyy",
>       "contractNumber": "Sopimusnumero"
> ```

Should this be "kohdetunnus"?

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`ui/src/locales/fi-FI/common.json` line 419 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754#-NmogBUt0VdVP8KnQGjz:-NmolQPADQ8SMkD4dcQo:b-mmtt4w) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f5c8ced4e6767504f2c552ff6b81adce0d24fb3d/ui/src/locales/fi-FI/common.json#L419)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Should this be "kohdetunnus"?
</blockquote></details>

Was `Sopimusnumero` in Figma. Need to check with Juha.

**Review by Perholehto — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 4 of 4 files at r3, 7 of 7 files at r4, 2 of 2 files at r5, 9 of 9 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

**Review by culka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`ui/src/locales/fi-FI/common.json` line 419 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754#-NmogBUt0VdVP8KnQGjz:-Nn8py6s1N0fmePO8uJ_:bwqe8oy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f5c8ced4e6767504f2c552ff6b81adce0d24fb3d/ui/src/locales/fi-FI/common.json#L419)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Was `Sopimusnumero` in Figma. Need to check with Juha.
</blockquote></details>

Sopimusnumero is fine, as discussed

**Review by Perholehto — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/754)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
