### PR TITLE
Add initial routing for stop registry views and base for stop details view

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 13 of 13 files at r3, 7 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764)* status: all files reviewed, 5 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqRrZmn1_XXuxxQwtAl):*
This could (should?) probably be squashed with the first commit, since if I understood right, this generated code is due to the changes in the earlier commit. The first commit wouldn't probably pass CI checks separately.
___
*[`ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx` line 18 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqRse3eDMpN4xeV9E9_:-NqRse3eDMpN4xeV9E9a:b12r7uz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a9968cf04a5de97a6de9cb4f4cc218dbfa63b05/ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx#L18)):*
> ```XML
>     <Container>
>       <StopTitleRow stopDetails={stopDetails} />
> ```

NIT, some extra empty lines inside JSX. I think usually all the elements are written without any empty lines
___
*[`ui/src/graphql/stop-registry/stop-place.ts` line 32 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSJoHQ-qrigLBvowse:-NqSJoHQ-qrigLBvowsf:b-vrgw37) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0e29a7cb426605c0fcdb16f1ac0f6cd018548262/ui/src/graphql/stop-registry/stop-place.ts#L32)):*
> ```XML
> `;
> 
> const GQL_GET_STOP_PLACE_BY_LABEL = gql`
> ```

At some point we started to only put GQL queries on components / hooks, can't precisely remember if there were any cases that we used these graphql -folder for new queries. This maybe could be a hook (?). What do you think?

Another point was that I think we also stopped using the default-fields and all_fields and just hooks and components just always ask what they need, since that is one of the main advantages of GQL.

But that said, I did not yet see if these all_fields are actually needed / used here (other than that currently the default_fields = all_fields).
___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 33 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqS_KV59lOB_vduHdty:-NqS_KV59lOB_vduHdtz:b-yqit61) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60a696ba938d05240b580b5124c5efbcec90f281/ui/src/hooks/stop-registry/useGetStopDetails.ts#L33)):*
> ```XML
>   return matchingName?.name || null;
> };
> export type EnrichedStopPlaceDetails = {
> ```

NIT,
This type definition could be before `findAlternativeName` (so practiaclly on top of file, but maybe(?) after the GQL.)
___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 33 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSbM1A31rOTkxg0F2O:-NqSbM1A31rOTkxg0F2P:b-6mhik1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60a696ba938d05240b580b5124c5efbcec90f281/ui/src/hooks/stop-registry/useGetStopDetails.ts#L33)):*
> ```XML
>   return matchingName?.name || null;
> };
> export type EnrichedStopPlaceDetails = {
> ```

Hmm. But also something feels off with the naming. What I mean is that the `EnrichedStopPlaceDetails` implies that this type includes the stopPlaceDetails and also something extra. Now this type only has finnishName and swedishName. Maybe this type could be `stopPlaceNameTranslations`? 
What do you think?
___
*[`ui/src/router/routeDetails.ts` line 22 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqRw2lcDzafq5hOtqEN:-NqRw2lcDzafq5hOtqEO:b-63gh8g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a9968cf04a5de97a6de9cb4f4cc218dbfa63b05/ui/src/router/routeDetails.ts#L22)):*
> ```XML
> 
>   // Stop registry
>   // stopSearch = '/stop-registry/stops/search',
> ```

BTW, the search also kind of covers terminal and stop area searching (https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1680-78174&mode=design&t=TbR5emRNm4sWDaN2-4), so we might have this on upper level. But this is not very important now and its nice that you added folder structure sketching here as well :+1:

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764)* status: 14 of 21 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqRrZmn1_XXuxxQwtAl):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This could (should?) probably be squashed with the first commit, since if I understood right, this generated code is due to the changes in the earlier commit. The first commit wouldn't probably pass CI checks separately.
</blockquote></details>

Squashed, :ok_hand: 
___
*[`ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx` line 18 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqRse3eDMpN4xeV9E9_:-NqWyObj80jZTkCyxn84:bejmcmh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a9968cf04a5de97a6de9cb4f4cc218dbfa63b05/ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx#L18)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, some extra empty lines inside JSX. I think usually all the elements are written without any empty lines
</blockquote></details>

Not sure if I agree with this practice, since empty lines are a basic tool for improving readability. And this wasn't blocked by any linter or other tool. But removed.
___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 33 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSbM1A31rOTkxg0F2O:-NqWzYrB8f92yjvFfSFS:b4fft38) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60a696ba938d05240b580b5124c5efbcec90f281/ui/src/hooks/stop-registry/useGetStopDetails.ts#L33)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm. But also something feels off with the naming. What I mean is that the `EnrichedStopPlaceDetails` implies that this type includes the stopPlaceDetails and also something extra. Now this type only has finnishName and swedishName. Maybe this type could be `stopPlaceNameTranslations`? 
What do you think?
</blockquote></details>

The idea was that as we add new fields to the schema (there's going to be a ton, looking at the designs), can just add them here to this same methods. Thus the generic `enrich` naming.
___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 33 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqS_KV59lOB_vduHdty:-NqX-Q2O8MPVdSfyrzXh:b-vf88x5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60a696ba938d05240b580b5124c5efbcec90f281/ui/src/hooks/stop-registry/useGetStopDetails.ts#L33)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT,
This type definition could be before `findAlternativeName` (so practiaclly on top of file, but maybe(?) after the GQL.)
</blockquote></details>

Feels better, moved.
___
*[`ui/src/router/routeDetails.ts` line 22 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqRw2lcDzafq5hOtqEN:-NqX-ZzXBw-4Q-FZd7D2:bwjw9q4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a9968cf04a5de97a6de9cb4f4cc218dbfa63b05/ui/src/router/routeDetails.ts#L22)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

BTW, the search also kind of covers terminal and stop area searching (https://www.figma.com/file/dsNMixsO1558hCX0XzRDrc/Bus-stops-%7C-JORE-4.0-UX?type=design&node-id=1680-78174&mode=design&t=TbR5emRNm4sWDaN2-4), so we might have this on upper level. But this is not very important now and its nice that you added folder structure sketching here as well :+1:
</blockquote></details>

:ok_hand: yep, let's adjust as needed. Will leave as is for now.
___
*[`ui/src/graphql/stop-registry/stop-place.ts` line 32 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSJoHQ-qrigLBvowse:-NqWz8C6EbMYZfjnW7TL:b1fk5ca) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0e29a7cb426605c0fcdb16f1ac0f6cd018548262/ui/src/graphql/stop-registry/stop-place.ts#L32)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

At some point we started to only put GQL queries on components / hooks, can't precisely remember if there were any cases that we used these graphql -folder for new queries. This maybe could be a hook (?). What do you think?

Another point was that I think we also stopped using the default-fields and all_fields and just hooks and components just always ask what they need, since that is one of the main advantages of GQL.

But that said, I did not yet see if these all_fields are actually needed / used here (other than that currently the default_fields = all_fields).
</blockquote></details>

I copied this pattern from elsewhere, didn't know it was considered deprecated. The `all_fields` version isn't used indeed at the moment.

Guess I will just delete this and move to the hook. The structure is a bit messed up at the moment anyway, since this file talks about the `details` query which is defined in the hook.

Note, this will get some rewrite treatment soon, when we change the linking to be done by stop place id instead of label.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx` line 18 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqRse3eDMpN4xeV9E9_:-NqamZl8Ez3PGlofKePi:bv8cn9i) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a9968cf04a5de97a6de9cb4f4cc218dbfa63b05/ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx#L18)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not sure if I agree with this practice, since empty lines are a basic tool for improving readability. And this wasn't blocked by any linter or other tool. But removed.
</blockquote></details>

I nearly added another comment to say that one might use these to make the JSX more readable. I think that there were some trade offs to this, but since I can't rembember them precisely, I think it's okay to use empty lines for readability, as long as we keep the amount of empty lines minimal. 
___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 33 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSbM1A31rOTkxg0F2O:-NqayWrw6AUZRN4KB1EF:b-fdhd97) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60a696ba938d05240b580b5124c5efbcec90f281/ui/src/hooks/stop-registry/useGetStopDetails.ts#L33)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

The idea was that as we add new fields to the schema (there's going to be a ton, looking at the designs), can just add them here to this same methods. Thus the generic `enrich` naming.
</blockquote></details>

Ah right, well then my suggestion can be forgotten. But in my opinion the naming still feels like it is the enriched version of stop place details, not the details that are used to enrich, if you catch my breath.
So for me `EnrichedStopPlaceDetails` implies 
```
EnrichedStopPlaceDetails = {
  ...stopPlaceDetails
  ...extraDetailsThatAreUsedToEnrichStopDetails
}
```
So we have StopPlace details and then we have attributes we use to enrich the stopPlace. After the enrichment we have EnrichedStopPlaceDetails

Or at least this is the way I view it :D How about you?
___
*[`ui/src/graphql/stop-registry/stop-place.ts` line 32 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSJoHQ-qrigLBvowse:-Nqb-Td7CL1xtEJP9iNe:b-6mhyx0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0e29a7cb426605c0fcdb16f1ac0f6cd018548262/ui/src/graphql/stop-registry/stop-place.ts#L32)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I copied this pattern from elsewhere, didn't know it was considered deprecated. The `all_fields` version isn't used indeed at the moment.

Guess I will just delete this and move to the hook. The structure is a bit messed up at the moment anyway, since this file talks about the `details` query which is defined in the hook.

Note, this will get some rewrite treatment soon, when we change the linking to be done by stop place id instead of label.
</blockquote></details>

Great, thanks!

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764)* status: all files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 33 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSbM1A31rOTkxg0F2O:-Nqb3B9F70RNCTRhBFoF:bktbq36) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60a696ba938d05240b580b5124c5efbcec90f281/ui/src/hooks/stop-registry/useGetStopDetails.ts#L33)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah right, well then my suggestion can be forgotten. But in my opinion the naming still feels like it is the enriched version of stop place details, not the details that are used to enrich, if you catch my breath.
So for me `EnrichedStopPlaceDetails` implies 
```
EnrichedStopPlaceDetails = {
  ...stopPlaceDetails
  ...extraDetailsThatAreUsedToEnrichStopDetails
}
```
So we have StopPlace details and then we have attributes we use to enrich the stopPlace. After the enrichment we have EnrichedStopPlaceDetails

Or at least this is the way I view it :D How about you?
</blockquote></details>

Sounds reasonable, changed the naming :ok_hand:

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`ui/src/hooks/stop-registry/useGetStopDetails.ts` line 33 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/764#-NqSbM1A31rOTkxg0F2O:-NqgaM878xSfOL0iO_PP:bwjq27e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60a696ba938d05240b580b5124c5efbcec90f281/ui/src/hooks/stop-registry/useGetStopDetails.ts#L33)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Sounds reasonable, changed the naming :ok_hand:
</blockquote></details>

Thanks, looks good!

**Pull request merged**
