### PR TITLE
Insert vehicle_submode_on_infrastructure_link data

### PR DESCRIPTION
**Pull request by sr-vala**
HSLdevcom/jore4#1217

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558)

### CODE REVIEW

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558)* status: all files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/routeStops.cy.ts` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85VvZCGt4tP5hfigk:-NR85VvZCGt4tP5hfigl:b-otclfu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/e2e/routeStops.cy.ts#L21)):*
> ```XML
> const testInfraLinks = [
>   {
>     id: '73bc2df9-f5af-4c38-a1dd-5ed1f71c90a8',
> ```

Why are these links different to the ones that we used earlier?
___
*[`cypress/e2e/routeStops.cy.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85jhj2ynfMKj5PlPD:-NR85jhj2ynfMKj5PlPE:bj4pu5e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/e2e/routeStops.cy.ts#L22)):*
> ```XML
>   {
>     id: '73bc2df9-f5af-4c38-a1dd-5ed1f71c90a8',
>     coordinates: [24.926699622176628, 60.164181083308065, 10.0969999999943],
> ```

Why are coordinates here? Are they used somewhere?
___
*[`cypress/fixtures/infraLinks/infraLinks.sql` line 5607 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85r7Y8iLR7VEVfhOr:-NR85r7Y8iLR7VEVfhOs:b-83sjoh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/fixtures/infraLinks/infraLinks.sql#L5607)):*
> ```TSQL
>   '7c6efe88-cbec-4f8d-9e56-0ea42b8d5e6a'
> );
> ```

Nice!

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @eleksi)

___
*[`cypress/e2e/routeStops.cy.ts` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85VvZCGt4tP5hfigk:-NR86bw984tEkJSgkFZv:b-16xr6n) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/e2e/routeStops.cy.ts#L21)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Why are these links different to the ones that we used earlier?
</blockquote></details>

The previous ones were inserted in this test file by the test-db-manager. I haven't checked if they exist in the infraLinks.sql file, but at least they were located somewhere in Africa, so not the best test data in that sense. The testInfraLinks listed here do exist in the infraLinks.sql file and are located in Finland.
___
*[`cypress/e2e/routeStops.cy.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85jhj2ynfMKj5PlPD:-NR87yzv8Owfx0Hghtv4:buytvhy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/e2e/routeStops.cy.ts#L22)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Why are coordinates here? Are they used somewhere?
</blockquote></details>

These can be removed. They are not used in this test suite. The same infralinks are used in other test suites where the coordinates are needed, and this was a copy-paste from createRoute.cy.ts probably.

**Review by eleksi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/routeStops.cy.ts` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85VvZCGt4tP5hfigk:-NR8KNWK-KWiki2VNIPF:bm3ar0g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/e2e/routeStops.cy.ts#L21)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

The previous ones were inserted in this test file by the test-db-manager. I haven't checked if they exist in the infraLinks.sql file, but at least they were located somewhere in Africa, so not the best test data in that sense. The testInfraLinks listed here do exist in the infraLinks.sql file and are located in Finland.
</blockquote></details>

Ok fair enough, but maybe we should fix other tests that use Africa links also, maybe in future PRs, not part of this PR I think.



_Code quote:_
```XML
infraLinks
```
___
*[`cypress/e2e/routeStops.cy.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85jhj2ynfMKj5PlPD:-NR8KjkTBKSVxDC4OQ1f:bn359cz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/e2e/routeStops.cy.ts#L22)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

These can be removed. They are not used in this test suite. The same infralinks are used in other test suites where the coordinates are needed, and this was a copy-paste from createRoute.cy.ts probably.
</blockquote></details>

Maybe make this infraLinkIds: UUID[] (array of UUIDs instead of array of objecst), or do we need these to be objects? Usage would be simpler later



_Code snippet:_
```XML
// ...later
infraLinkIds[0]
```

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`cypress/e2e/routeStops.cy.ts` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/558#-NR85VvZCGt4tP5hfigk:-NRBrhve2AAuiHMHgCd5:bfld8m9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/674ec68b6176a57e2955948336a153ca7f2027ea/cypress/e2e/routeStops.cy.ts#L21)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Ok fair enough, but maybe we should fix other tests that use Africa links also, maybe in future PRs, not part of this PR I think.
</blockquote></details>

I don't think they are used anywhere else anymore. Other tests with infralinks are performed on the map, so they need to be in Finland. But should we also remove the infrastructureLinks.ts file and its references from test-db-manager?

**Pull request merged**
