### PR TITLE
Ensure edited / created stop is visible in map

### PR DESCRIPTION
**Pull request by eleksi**
- Add warning toast
- Show warning toast when observation date is adjusted
- Adjust observation date after stop edit / create if new stop would not be visible

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/328)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/328)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @eleksi and @tk-vincit)

___
*[`ui/tailwind.config.js` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRVAXa3KOTk5aoeVQ1:-NBRVAXa3KOTk5aoeVQ2:b-qyay8m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/tailwind.config.js#L25)):*
> ```JavaScript
>         'hsl-red': colors.hslRed,
>         'city-bicycle-yellow': colors.cityBicycleYellow,
>         'hsl-warning-yellow': colors.warningYellow,
> ```

Please be consistent with naming: if color comes from hsl theme and is prefixed with "hsl-", then that should be reflected also in `theme.js` file. See hsl-red as reference. And if the color is not from hsl, don't add hsl prefix.
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 47 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRVxwyEBnvnNrakULb:-NBRVxwyEBnvnNrakULc:b-tpeqpm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L47)):*
> ```XML
>   const ensureVisibilityByValidityPeriod = ({
>     // eslint-disable-next-line camelcase
>     validity_start,
> ```

Non-blocking protip: you could save 2 lines and keep comments on relevant lines like this:
```
validity_start, // eslint-disable-line camelcase
```

Same for same lines on type definition.



_Code quote:_
```XML
    // eslint-disable-next-line camelcase
    validity_start,
    // eslint-disable-next-line camelcase
    validity_end,
```

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/328)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 45 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRT_vY-c3iJFMfvnSk:-NBRT_vY-c3iJFMfvnSl:b-3u9z7z) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L45)):*
> ```XML
>   }, [defaultDate, getDateTimeFromUrlQuery]);
> 
>   const ensureVisibilityByValidityPeriod = ({
> ```

let's change the function name to tell about what it does, not that what it is going to be used for. Maybe `ensureObservationDateWithinValidityPeriod`? Or do you have an idea for something shorter?
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRSdBs0Tl5SeLnQFA6:-NBRSdBs0Tl5SeLnQFA7:b-v7t8zt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L50)):*
> ```XML
>     // eslint-disable-next-line camelcase
>     validity_end,
>   }: {
> ```

There's an existing `ValidityPeriod` graphql generated type for this
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 58 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRTArW6Kb6-bzRa3fL:-NBRTArW6Kb6-bzRa3fM:b-wg9u1n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L58)):*
> ```XML
>     if (!isDateInRange(observationDate, validity_start, validity_end)) {
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, camelcase
>       setObservationDateToUrl(validity_start!);
> ```

warning! The validity_start *could* be actually null. The proper logic would be
`setObservationDateToUrl(validity_start || validity_end!)`
(as both validity_start and validity_end cannot be null, otherwise they would've intersected with the validity_end)
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 59 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRSzMc0Sh50fP8uO1S:-NBRSzMc0Sh50fP8uO1T:btsamkg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L59)):*
> ```XML
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, camelcase
>       setObservationDateToUrl(validity_start!);
>       showWarningToast(t('filters.observationDateAdjusted'));
> ```

there should be a parameter for this function whether it should show the toast message notification or not. It could default to true

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/328)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`ui/tailwind.config.js` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRVAXa3KOTk5aoeVQ1:-NBlOjceCjUX00TmwwHs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/tailwind.config.js#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please be consistent with naming: if color comes from hsl theme and is prefixed with "hsl-", then that should be reflected also in `theme.js` file. See hsl-red as reference. And if the color is not from hsl, don't add hsl prefix.
</blockquote></details>

Done.
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 45 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRT_vY-c3iJFMfvnSk:-NBlQt2B9SE4I5wGl_ni:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L45)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's change the function name to tell about what it does, not that what it is going to be used for. Maybe `ensureObservationDateWithinValidityPeriod`? Or do you have an idea for something shorter?
</blockquote></details>

Done.
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRSdBs0Tl5SeLnQFA6:-NBlQrmJCNKwgpMIic0s:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L50)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

There's an existing `ValidityPeriod` graphql generated type for this
</blockquote></details>

Done.
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 58 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRTArW6Kb6-bzRa3fL:-NBlQr9-5YWSJLUl9of6:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L58)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

warning! The validity_start *could* be actually null. The proper logic would be
`setObservationDateToUrl(validity_start || validity_end!)`
(as both validity_start and validity_end cannot be null, otherwise they would've intersected with the validity_end)
</blockquote></details>

Done.
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 59 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NBRSzMc0Sh50fP8uO1S:-NBlQqut0nwQHTFqosc2:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c74c96fa73c986d39717f01a8d3ee731ef165562/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L59)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there should be a parameter for this function whether it should show the toast message notification or not. It could default to true
</blockquote></details>

Done.

**Review by tk-vincit — COMMENTED** [review]
Resolved comment by me, Tamas can chech his comments and approve if they're OK.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-:-NBqnhsT3W1H2afczm1J:b-mfp767)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @pallost and @tk-vincit)

**Review by tk-vincit — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 4 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/328)* status: all files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 45 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/328#-NC-Y0sSEQfzbLVG-wuq:-NC-Y0sSEQfzbLVG-wur:baziazu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/802ec148ae5f0be6338b449542e6b01abc3dbe77/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L45)):*
> ```XML
>   }, [defaultDate, getDateTimeFromUrlQuery]);
> 
>   const ensureObservationDateWithinValidityPeriod = ({
> ```

`updateObservationDateWithinValidityPeriod` could be more descriptive ?

**Pull request merged**
