### PR TITLE
Map rewrite

### PR DESCRIPTION
**Pull request by Perholehto**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 12 of 12 files at r11, 6 of 6 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 4 of 4 files at r15, 4 of 4 files at r16, 4 of 4 files at r17, 11 of 11 files at r18, 3 of 3 files at r19, 7 of 7 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808)* status: all files reviewed, 4 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/map/CustomOverlay.tsx` line 67 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-NxlVAWi1SsBRD4Y8LeT:-NxlVAWi1SsBRD4Y8LeU:beo4kc2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ab720d874e373c39f5ad254db615dbc1c46d43fc/ui/src/components/map/CustomOverlay.tsx#L67)):*
> ```XML
> }: {
>   children: React.ReactElement;
>   position: ControlPosition;
> ```

Above we have default value `position = 'top-left` but this position prop is not optional. So either change this as optional or remove the default.
___
*[`ui/src/components/map/CustomOverlay.tsx` line 84 at r18](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-Nxlvs1b70QgYPLnCAJm:-Nxlvs1c53gAfXbX-k5k:bss2za3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f6e9fa7ea1d9807b914cafbe0946893cdbf55f1/ui/src/components/map/CustomOverlay.tsx#L84)):*
> ```XML
>   return (
>     // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>     map && createPortal(cloneElement(children, { map }), ctrl.getElement()!)
> ```

Could this be checked beforehand if its falsy, and then do e.g. an early return if it's not. Then we can get rid of the non-null-assertion?
___
*[`ui/src/components/map/DrawControl.tsx` line 18 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-Nxla7Nt2HDr-mzJksmM:-Nxla7Nt2HDr-mzJksmN:b-v8bdw0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6ecc6d4add111db728fac69aa7cca94b0061783b/ui/src/components/map/DrawControl.tsx#L18)):*
> ```XML
> ) => {
>   const { onCreate, onUpdate, position } = props;
>   const drawRef = useControl<MapboxDraw>(
> ```

_If_ there is a possibility to make this more understandable with some intermediate variables or some other low effort, then would be nice, but not sure if needed (?)
___
*[`ui/src/components/map/DrawRouteLayer.tsx` line 1 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-Nxlb9iy4348ZXRU72nn:-Nxlb9iy4348ZXRU72no:b-1tli86) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6ecc6d4add111db728fac69aa7cca94b0061783b/ui/src/components/map/DrawRouteLayer.tsx#L1)):*
> ```XML
> import debounce from 'lodash/debounce';
> ```

This file was removed in another commit and added here, so hard to see if something actually changed. I'll check this again after probable squash of commits.
___
*[`ui/src/components/map/Map.tsx` line 219 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-NxlbPfO0ak2_EdP7npi:-NxlbPfO0ak2_EdP7npj:b-84dbqw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6ecc6d4add111db728fac69aa7cca94b0061783b/ui/src/components/map/Map.tsx#L219)):*
> ```XML
>         ref={routeEditorRef}
>       />
>       <Visible visible={drawingMode !== undefined}>
> ```

NIT, 



_Suggestion:_
```XML
      <Visible visible={!!drawingMode}>
```

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808)* status: 1 of 32 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/map/CustomOverlay.tsx` line 67 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-NxlVAWi1SsBRD4Y8LeT:-NyJeRsi87Trr9nIEhTa:beym9sc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ab720d874e373c39f5ad254db615dbc1c46d43fc/ui/src/components/map/CustomOverlay.tsx#L67)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Above we have default value `position = 'top-left` but this position prop is not optional. So either change this as optional or remove the default.
</blockquote></details>

There is no real reason to use optional property here so I removed default value.
___
*[`ui/src/components/map/CustomOverlay.tsx` line 84 at r18](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-Nxlvs1b70QgYPLnCAJm:-NyJgWh5DzhPgASA5U9x:bqp6660) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f6e9fa7ea1d9807b914cafbe0946893cdbf55f1/ui/src/components/map/CustomOverlay.tsx#L84)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Could this be checked beforehand if its falsy, and then do e.g. an early return if it's not. Then we can get rid of the non-null-assertion?
</blockquote></details>

Didn't add an early return but still got rid of the non-null-assertion
___
*[`ui/src/components/map/Map.tsx` line 219 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-NxlbPfO0ak2_EdP7npi:-NyJdBQCCSflok2bj436:b-1vf137) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6ecc6d4add111db728fac69aa7cca94b0061783b/ui/src/components/map/Map.tsx#L219)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT,
</blockquote></details>

Double bang operator does not work here. `drawingMode` is an enum and I think `!!` converts `0` to `true` here

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 2 of 3 files at r22, 1 of 1 files at r28, 1 of 2 files at r29, 3 of 12 files at r31, 2 of 6 files at r32, 1 of 4 files at r35, 1 of 4 files at r36, 3 of 4 files at r37, 7 of 11 files at r38, 3 of 3 files at r39, 7 of 7 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808)* status: all files reviewed, 2 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/map/Map.tsx` line 219 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-NxlbPfO0ak2_EdP7npi:-NyKwgM28eeFqmR9b_rV:busq1c1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6ecc6d4add111db728fac69aa7cca94b0061783b/ui/src/components/map/Map.tsx#L219)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Double bang operator does not work here. `drawingMode` is an enum and I think `!!` converts `0` to `true` here
</blockquote></details>

Nope, 0 is falsy value. It will be converted to false.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 3 of 3 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Perholehto)

___
*[`ui/src/components/map/DrawRouteLayer.tsx` line 1 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-ui/808#-Nxlb9iy4348ZXRU72nn:-NyVduQe3jn364pMMS7R:b185b5f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6ecc6d4add111db728fac69aa7cca94b0061783b/ui/src/components/map/DrawRouteLayer.tsx#L1)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This file was removed in another commit and added here, so hard to see if something actually changed. I'll check this again after probable squash of commits.
</blockquote></details>

Oh, didn't help. It seems that Reviewable doesn't recognise these as the same file. Well, skimmed it through with a side by side view with the removed file.

**Pull request merged**
