### PR TITLE
Push Docker images to Docker Hub

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)

### CODE REVIEW

**Review by jpeuralinna — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tk-vincit)

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)* status: all files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[.github/workflows/cd.yml, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/3#-MYJ9NHh0oxFa2oWK34G:-MYJ9NHh0oxFa2oWK34H:bfod0qw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9eed4823e739db92da41de6e3f1b24676d790908/.github/workflows/cd.yml#L35)):*
> ```YAML
> 
>       - name: Build docker image for distribution
>         run: docker build --cache-from=$IMAGE_NAME:builder --cache-from=$IMAGE_NAME:dev -t $IMAGE_NAME:dev --build-arg NEXT_PUBLIC_GIT_HASH=$GITHUB_SHA .
> ```

The deployment strategy that we have agreed on does not use the `:dev` docker image tag. Instead it'll always use the docker images versioned with the git hash or the package.json version attribute.

My suggestion: 
- don't build a `:dev` image here, you could just build e.g. a `:latest` image
- do build an image with the `:$COMMIT_ID` tag and always push to docker hub
- do build an image with the version retrieved from package.json `:$PACKAGE_JSON_VERSION` tag and push to docker hub if this was the `main` branch
- do push the `:builder` and the `:latest` images to docker hub if this was to `main` branch.

How does this sound?

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)* status: all files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[.github/workflows/cd.yml, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/3#-MYJAdikECbPUP315HnI:-MYJAdikECbPUP315HnJ:b-slu3wl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9eed4823e739db92da41de6e3f1b24676d790908/.github/workflows/cd.yml#L13)):*
> ```
> # TODO
> ```

Perhaps there ought to be some description of this TODO issue, e.g. what exactly should be fixed here and when.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)* status: all files reviewed, 2 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[.github/workflows/cd.yml, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/3#-MYJAdikECbPUP315HnI:-MYJBu7T68QZVsAJgAfR:bg6qkjm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9eed4823e739db92da41de6e3f1b24676d790908/.github/workflows/cd.yml#L13)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> # TODO
> ```

Perhaps there ought to be some description of this TODO issue, e.g. what exactly should be fixed here and when.
</blockquote></details>

Good catch. This was meant for me only (I was going to lock ubuntu version as Henri wanted that in some PR in another repo), but I forgot to do that and also forgot this comment here... Will fix this.
___
*[.github/workflows/cd.yml, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/3#-MYJ9NHh0oxFa2oWK34G:-MYJQeHK2yM9wyoY3dUx:b-5uwt8g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9eed4823e739db92da41de6e3f1b24676d790908/.github/workflows/cd.yml#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

The deployment strategy that we have agreed on does not use the `:dev` docker image tag. Instead it'll always use the docker images versioned with the git hash or the package.json version attribute.

My suggestion: 
- don't build a `:dev` image here, you could just build e.g. a `:latest` image
- do build an image with the `:$COMMIT_ID` tag and always push to docker hub
- do build an image with the version retrieved from package.json `:$PACKAGE_JSON_VERSION` tag and push to docker hub if this was the `main` branch
- do push the `:builder` and the `:latest` images to docker hub if this was to `main` branch.

How does this sound?
</blockquote></details>

- OK, I won't publish `:dev` image. How would that work?
- We're already building `:branch name-commit hash` tag and always publishing it. We can omit branch name part if we decide so.
- Tagging images based on package.json's version and publishing those every time when we push something to main branch is not a good idea, especially if we don't force users to bump version in package.json in every PR. And even if we would do that, that would make working with multiple PR's PITA.
- We're doing that already.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jpeuralinna and @lassemaatta)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jpeuralinna and @lassemaatta)

___
*[.github/workflows/cd.yml, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/3#-MYJAdikECbPUP315HnI:-MYJUh-4364Ok9xJzpHZ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9eed4823e739db92da41de6e3f1b24676d790908/.github/workflows/cd.yml#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Good catch. This was meant for me only (I was going to lock ubuntu version as Henri wanted that in some PR in another repo), but I forgot to do that and also forgot this comment here... Will fix this.
</blockquote></details>

Done.

**Review by lassemaatta — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
