### PR TITLE
Fix stop creation

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)

### CODE REVIEW

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[src/locales/fi-FI/common.json, line 48 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx4jbjMAwHBSkFGFPJi:-Mx4jbjN3iLM_kBKJ6NX:bmpv0aq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a4a43558059836663b86e8d0d48f68d2c045910/src/locales/fi-FI/common.json#L48)):*
> ```JSON
>     "finnishName": "Nimi (Suomi)",
>     "saveSuccess": "Pysäkki luotu",
>     "fetchClosestLinkFailed": "Infrastruktuuri linkkiä ei löytynyt pysäkille",
> ```

Infrastruktuuri linkkiä -> Infrastruktuurilinkkiä
___
*[src/utils/errors.ts, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx4iR6M1eHOvETDlJ-b:-Mx4iR6M1eHOvETDlJ-c:b-bhloyw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71ed0bba5c3eb59e755e3c57029c195ac1d2e1b2/src/utils/errors.ts#L24)):*
> ```XML
> }
> 
> class GraphqlError extends ExtendableError {
> ```

Rename to GraphQLError?

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)* status: all files reviewed, 5 unresolved discussions (waiting on @pallost)

___
*[src/utils/errors.ts, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx8st4J6aYFRj3X9ic0:-Mx8st4J6aYFRj3X9ic1:bltl5l3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71ed0bba5c3eb59e755e3c57029c195ac1d2e1b2/src/utils/errors.ts#L27)):*
> ```XML
>   graghqlError?: ApolloError;
> 
>   protected constructor(graghqlError?: ApolloError, errorMessage?: string) {
> ```

Typo: => `graphql`



_Code quote:_
```XML
graghql
```
___
*[src/utils/errors.ts, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx8tDsKEw-e-8dAvcT8:-Mx8tDsKEw-e-8dAvcT9:b-hk75vr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71ed0bba5c3eb59e755e3c57029c195ac1d2e1b2/src/utils/errors.ts#L37)):*
> ```XML
> 
> export class LinkNotFoundError extends GraphqlError {
>   constructor(graghqlError?: ApolloError, errorMessage?: string) {
> ```

Typo: => graphql



_Code quote:_
```XML
graghql
```
___
*[src/utils/errors.ts, line 46 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx8tG7L3WbRRCyQngYU:-Mx8tG7L3WbRRCyQngYV:b-hk75vr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71ed0bba5c3eb59e755e3c57029c195ac1d2e1b2/src/utils/errors.ts#L46)):*
> ```XML
> 
> export class DirectionNotFoundError extends GraphqlError {
>   constructor(graghqlError?: ApolloError, errorMessage?: string) {
> ```

Typo: => graphql



_Code quote:_
```XML
graghql
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[src/locales/fi-FI/common.json, line 48 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx4jbjMAwHBSkFGFPJi:-Mx9NgVy2qidhJo0xRbz:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a4a43558059836663b86e8d0d48f68d2c045910/src/locales/fi-FI/common.json#L48)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Infrastruktuuri linkkiä -> Infrastruktuurilinkkiä
</blockquote></details>

Done.

**Review by eleksi — APPROVED** [review]
> Reviewed 10 of 10 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

**Review by jarkkoka — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[src/locales/en-US/common.json, line 49 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx9bGmyBIuAYgg-iZc3:-Mx9bGmyBIuAYgg-iZc4:bshq64e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dee8fce874cba657ff1f9c5f66ad3db5aa2f4b19/src/locales/en-US/common.json#L49)):*
> ```JSON
>     "saveSuccess": "Stop created",
>     "fetchClosestLinkFailed": "Could not find infrastructure link for the stop",
>     "fetchDirectionFailed": "Could not find direction for the stop's infrastructure link"
> ```

"find" -> "resolve"

Since the direction may be need to be algorithmically determined in case of bidirectional infrastructure links.



_Code quote:_
```JSON
find
```
___
*[src/locales/fi-FI/common.json, line 49 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx9bCKiBYNqf84wNbjY:-Mx9bCKiBYNqf84wNbjZ:b-9y9v97) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dee8fce874cba657ff1f9c5f66ad3db5aa2f4b19/src/locales/fi-FI/common.json#L49)):*
> ```JSON
>     "saveSuccess": "Pysäkki luotu",
>     "fetchClosestLinkFailed": "Infrastruktuurilinkkiä ei löytynyt pysäkille",
>     "fetchDirectionFailed": "Suuntaa ei löytynyt pysäkin infrastruktuurilinkille"
> ```

More accurate: "löytynyt" -> "pystytty päättelemään"



_Code quote:_
```JSON
löytynyt
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/100)* status: 1 of 11 files reviewed, 2 unresolved discussions (waiting on @eleksi and @jarkkoka)

___
*[src/locales/en-US/common.json, line 49 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx9bGmyBIuAYgg-iZc3:-MxDmI2D4sSqn70h0syv:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dee8fce874cba657ff1f9c5f66ad3db5aa2f4b19/src/locales/en-US/common.json#L49)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"find" -> "resolve"

Since the direction may be need to be algorithmically determined in case of bidirectional infrastructure links.
</blockquote></details>

Done.
___
*[src/locales/fi-FI/common.json, line 49 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/100#-Mx9bCKiBYNqf84wNbjY:-MxE1u3_DkIiSd9YJUjD:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dee8fce874cba657ff1f9c5f66ad3db5aa2f4b19/src/locales/fi-FI/common.json#L49)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

More accurate: "löytynyt" -> "pystytty päättelemään"
</blockquote></details>

Done.

**Pull request merged**
