### PR TITLE
Add origin and destination names to route

### PR DESCRIPTION
**Pull request by pallost**
Resolves HSLdevcom/jore4#676

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/192)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/192)* status: 9 of 12 files reviewed, 7 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`src/components/forms/route/RoutePropertiesForm.tsx` line 126 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2k_zCR2sYf65Lwtfrq:-N2k_zCR2sYf65Lwtfrr:b4oobfe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/RoutePropertiesForm.tsx#L126)):*
> ```XML
>             </p>
>           </Column>
>           {!creatingNewRoute && <TerminusNameInputs />}
> ```

I think we need the `TerminusNameInputs` even when creating a new route. Also currently it won't create new one because the TerminusNameInputs are required by the form submit, but can't be filled.
___
*[`src/components/forms/route/RoutePropertiesForm.types.ts` line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l1Xei9x-EO_0HaNis:-N2l1Xei9x-EO_0HaNit:b-jr4p3g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/RoutePropertiesForm.types.ts#L20)):*
> ```XML
>     on_line_id: z.string().uuid().min(1),
>     direction: z.nativeEnum(RouteDirection),
>     origin: namesSchema.optional(),
> ```

I think these need to be required.
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l1bCH-KY14qRiAJSs:-N2l1bCH-KY14qRiAJSt:b-83sjoh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L7)):*
> ```XML
> import { RouteFormState } from './RoutePropertiesForm.types';
> 
> const testIds = {
> ```

Nice!
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l1k3K8rjpAV3Gn80J:-N2l1k3K8rjpAV3Gn80K:b-l05wu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L32)):*
> ```XML
>       </h2>
>       <Row className="mt-5 flex-wrap">
>         <Column className="w-80 flex-auto">
> ```

Not sure about the precise widths. We could use `grid`,`grid-cols` etc. for the more precise layout. Then it would be scalable. Now it breaks a bit when changing the window size.
___
*[`src/graphql/route.ts` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l35ke8tG_UVrcnCPF:-N2l35ke8tG_UVrcnCPG:b-jp5ev6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/graphql/route.ts#L66)):*
> ```XML
>     label
>     direction
>     origin_name
> ```

Check these. (missing `_i18n` postfix) Also they should be `_short_name` instead of `_name_short`
I can see that the correct names are already in this query, so these seems to be extra.

Maybe use `find` to search for all extra or wrong named fields in this file.
___
*[`src/graphql/route.ts` line 415 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l3J-R5En621Ms-tX_:-N2l3J-R5En621Ms-tXa:bmpkrc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/graphql/route.ts#L415)):*
> ```XML
>       label
>       direction
>       origin_name
> ```

Check these. 
___
*[`src/locales/fi-FI/common.json` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l4cb349eRIwUf_s4N:-N2l4cb349eRIwUf_s4O:b951qf8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/locales/fi-FI/common.json#L31)):*
> ```JSON
>     },
>     "destination": {
>       "title": "Päätepaikka",
> ```

Not sure if this should be "Määränpää". Figma seems to be using both words. So maybe discuss with Juha which one it should be.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/192)* status: 9 of 12 files reviewed, 8 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l6h0o7B-FEw9P03Zc:-N2l6h0o7B-FEw9P03Zd:b-2fhofi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L35)):*
> ```XML
>           <StringInput<RouteFormState>
>             translationPrefix="routes"
>             fieldPath="origin.name.fi_FI"
> ```

hmm, this `translationPrefix` and  `fieldPath` is a nice idea, but these are not typed so this is pretty hard to maintain if the translation paths are changed.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/192)* status: 5 of 14 files reviewed, 8 unresolved discussions (waiting on @HenrikHartiala)

___
*[`src/components/forms/route/RoutePropertiesForm.tsx` line 126 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2k_zCR2sYf65Lwtfrq:-N34Jbk40gvJUERsJYW5:b8hqgfr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/RoutePropertiesForm.tsx#L126)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think we need the `TerminusNameInputs` even when creating a new route. Also currently it won't create new one because the TerminusNameInputs are required by the form submit, but can't be filled.
</blockquote></details>

Done, I added it as you suggested.
___
*[`src/components/forms/route/RoutePropertiesForm.types.ts` line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l1Xei9x-EO_0HaNis:-N34Jkf492NTbgBB9Y7_:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/RoutePropertiesForm.types.ts#L20)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think these need to be required.
</blockquote></details>

done
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l1bCH-KY14qRiAJSs:-N34LRLODUYhhr4U--pW:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L7)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Done.
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l1k3K8rjpAV3Gn80J:-N34PNCH8pUpasJer9-b:b9cz8pg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L32)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Not sure about the precise widths. We could use `grid`,`grid-cols` etc. for the more precise layout. Then it would be scalable. Now it breaks a bit when changing the window size.
</blockquote></details>

Grid is not really working here as it would force these textboxes to be in multiple columns. However if we have fixes widths here then they wrap nicely if you shrink the window to a smaller size. The glitch you saw was actually because the StringInput component was only a <div>. I made it into a <Column>, good finding!
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l6h0o7B-FEw9P03Zc:-N34KMhO0J9yiGzDJQ-5:bhyidv7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L35)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

hmm, this `translationPrefix` and  `fieldPath` is a nice idea, but these are not typed so this is pretty hard to maintain if the translation paths are changed.
</blockquote></details>

well, fieldPath is already matched with the type (hence the <RouteFormState> input)... the translationPrefix however has always been just a hard coded string, so I don't think it is an issue here that it's used as a hard-coded parameter
___
*[`src/graphql/route.ts` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l35ke8tG_UVrcnCPF:-N34L9GfBjZUtK-XIdCw:bz2w33q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/graphql/route.ts#L66)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Check these. (missing `_i18n` postfix) Also they should be `_short_name` instead of `_name_short`
I can see that the correct names are already in this query, so these seems to be extra.

Maybe use `find` to search for all extra or wrong named fields in this file.
</blockquote></details>

ha! Weird... I don't understand how the graphql codegen didn't throw an error before about this. Well, now it does :P Fixed it...
___
*[`src/graphql/route.ts` line 415 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l3J-R5En621Ms-tX_:-N34LGg0ErKU-2-kzW0p:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/graphql/route.ts#L415)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Check these. 
</blockquote></details>

Done.
___
*[`src/locales/fi-FI/common.json` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l4cb349eRIwUf_s4N:-N34LOx81SZKHHdwqoB4:b-c6rnfe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/locales/fi-FI/common.json#L31)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Not sure if this should be "Määränpää". Figma seems to be using both words. So maybe discuss with Juha which one it should be.
</blockquote></details>

Määränpää sounds better anyway, fixed it

**Review by HenrikHartiala — APPROVED** [review]
Nice work! Added couple of notes, but approved!

> Reviewed 1 of 12 files at r1, 5 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-:-N34cDot2pkcc8KXTTk3:bl43s31)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

___
*[`src/components/forms/common/StringInput.tsx` line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N34aOdY3gfbfFwoR9aw:-N34aOdY3gfbfFwoR9ax:be7xwym) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/36486b832aa89870fdcca3f47a3221b9d8739f41/src/components/forms/common/StringInput.tsx#L14)):*
> ```XML
> }
> 
> export function StringInput<FormState extends FieldValues>({
> ```

This could be arrow function.
___
*[`src/components/forms/common/StringInput.tsx` line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N34aW-2-UY77sqiWTyp:-N34aW-2-UY77sqiWTyq:b-i9btko) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/36486b832aa89870fdcca3f47a3221b9d8739f41/src/components/forms/common/StringInput.tsx#L18)):*
> ```XML
>   translationPrefix,
>   testId,
> }: Props<FormState>) {
> ```

Typing `: JSX.Element` is missing here. This is something that I've been informed to add. (Intellisense knows it even without the typing)
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l1k3K8rjpAV3Gn80J:-N34Yg0EEkl5gcsyXn6B:brmux6m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Grid is not really working here as it would force these textboxes to be in multiple columns. However if we have fixes widths here then they wrap nicely if you shrink the window to a smaller size. The glitch you saw was actually because the StringInput component was only a <div>. I made it into a <Column>, good finding!
</blockquote></details>

Check!
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l6h0o7B-FEw9P03Zc:-N34YrWW8YR0IPyxYpHR:b5q3mli) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

well, fieldPath is already matched with the type (hence the <RouteFormState> input)... the translationPrefix however has always been just a hard coded string, so I don't think it is an issue here that it's used as a hard-coded parameter
</blockquote></details>

yeah, I mean there might not even be a silver bullet for these. The one issue I can see here is that if you try to search for "routes.origin.shortName" you won't find anything because the "routes" prefix is added dynamically. But I think this is still a nice way to avoid repetition so its good :+1: 
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 24 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N34bCpG2a7TmOtDNTu4:-N34bCpG2a7TmOtDNTu5:b-pgwr22) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/36486b832aa89870fdcca3f47a3221b9d8739f41/src/components/forms/route/TerminusNameInputs.tsx#L24)):*
> ```XML
> }
> 
> export const TerminusNameInputs = ({ className }: Props): JSX.Element => {
> ```

I've been using the default parameter value for classNames. so `({className = ''})` but totally up to you, I think both are good.
___
*[`src/graphql/route.ts` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l35ke8tG_UVrcnCPF:-N34Zeg7D16lHm7wrzmM:b-bgpexn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/graphql/route.ts#L66)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

ha! Weird... I don't understand how the graphql codegen didn't throw an error before about this. Well, now it does :P Fixed it...
</blockquote></details>

Heh, yeah. Could be the good ol' cache desync :D
___
*[`src/locales/fi-FI/common.json` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l4cb349eRIwUf_s4N:-N34ZyvG0FyA1AinO4U1:b-y7mvi9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/locales/fi-FI/common.json#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Määränpää sounds better anyway, fixed it
</blockquote></details>

Great! :+1:

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/192)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N2l6h0o7B-FEw9P03Zc:-N3IY3lqCMU5hKjZ6Tsr:b-m5kpep) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a35f9a0b18e0ae89d84a8b156fccc55de2174b2c/src/components/forms/route/TerminusNameInputs.tsx#L35)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

yeah, I mean there might not even be a silver bullet for these. The one issue I can see here is that if you try to search for "routes.origin.shortName" you won't find anything because the "routes" prefix is added dynamically. But I think this is still a nice way to avoid repetition so its good :+1: 
</blockquote></details>

Added a type check for this ;)
___
*[`src/components/forms/route/TerminusNameInputs.tsx` line 24 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/192#-N34bCpG2a7TmOtDNTu4:-N3IVD4REt19EWABXHD8:b-vrjxnn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/36486b832aa89870fdcca3f47a3221b9d8739f41/src/components/forms/route/TerminusNameInputs.tsx#L24)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I've been using the default parameter value for classNames. so `({className = ''})` but totally up to you, I think both are good.
</blockquote></details>

oh, that's smart! Why didn't we do it like that before?

**Pull request merged**
