### PR TITLE
Check lines for priority/validity conflicts before save

### PR DESCRIPTION
**Pull request by tk-vincit**
Related to https://github.com/HSLdevcom/jore4/issues/636

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/115)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/115)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @pallost and @tk-vincit)

___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/115#-MyMTDl7-IjL_9qrBK2r:-MyMTDl7-IjL_9qrBK2s:bof1zud) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c7037a11de10b8d20561b06476bcc7ad23c18aed/src/hooks/useCheckValidityAndPriorityConflicts.ts#L26)):*
> ```XML
>   const validityFilter = isIndefinite
>     ? // case 1: this resource in indefinite
>       [
> ```

this would be easier to read if you also included the `_or` operator as well here, like: 
```
const validityFilter = isIndefinite ? {_or: [...}} : {_or: [...]}
```
... even if is causes a tiny bit of code duplication

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/115)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/115#-MyMVm8N0XOFYgMX1Hq8:-MyMVm8N0XOFYgMX1Hq9:bgzrdlp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c7037a11de10b8d20561b06476bcc7ad23c18aed/src/hooks/useCheckValidityAndPriorityConflicts.ts#L55)):*
> ```XML
>             { validity_end: { _gte: validityEnd } },
>           ],
>         },
> ```

you are missing the case where an existing resource's validity is spanning over the validity period (starts earlier and ends after)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/115)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/115#-MyMTDl7-IjL_9qrBK2r:-MyMdDXT6uz6HiOCr3Sk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c7037a11de10b8d20561b06476bcc7ad23c18aed/src/hooks/useCheckValidityAndPriorityConflicts.ts#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this would be easier to read if you also included the `_or` operator as well here, like: 
```
const validityFilter = isIndefinite ? {_or: [...}} : {_or: [...]}
```
... even if is causes a tiny bit of code duplication
</blockquote></details>

Done.
___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/115#-MyMVm8N0XOFYgMX1Hq8:-MyMdOLU331B_A2INbyq:byawitv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c7037a11de10b8d20561b06476bcc7ad23c18aed/src/hooks/useCheckValidityAndPriorityConflicts.ts#L55)):*
> you are missing the case where an existing resource's validity is spanning over the validity period (starts earlier and ends after)
Or the other way around? Anyway, both cases (existing resource starts earlier and ends after) or (existing resource starts after and ends before) should be covered now.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/115)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
