### PR TITLE
Add CI job for running cypress tests locally

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/187)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/187)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pallost and @tk-vincit)

___
*[`.github/workflows/cd.yml` line 114 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/187#-N2H0oCYDr2RvoExTaU_:-N2H0oCYDr2RvoExTaUa:b-1nqi4v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4bc3cac16f364285d826ed5f1db4f74bb75da8cc/.github/workflows/cd.yml#L114)):*
> ```YAML
>         uses: HSLdevcom/jore4-robot/github-actions/upload-results@actions-v1
> 
>   run_cypress_tests:
> ```

Its a bit misleading that these are inside `cd` file, but well, seems like running robot tests is also in this file (and it kind of makes sense to have those here as this expects to find docker images from docker hub), so no need to do anything unless you get good idea how to improve this.
___
*[`.github/workflows/cd.yml` line 142 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/187#-N2H0a6RASSVBIR5ffms:-N2H0a6RASSVBIR5ffmt:bim8sjk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4bc3cac16f364285d826ed5f1db4f74bb75da8cc/.github/workflows/cd.yml#L142)):*
> ```YAML
>       - name: Run cypress tests
>         run: |
>           curl http://localhost:3300
> ```

Why do we need this, does this wait that environment is up & running or what?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/187)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[`.github/workflows/cd.yml` line 114 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/187#-N2H0oCYDr2RvoExTaU_:-N2LQL9s3wgB8rLelHrS:b-h0s5e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7199bbb6b3208f77acbf4ba1ce84c2ec8b8df249/.github/workflows/cd.yml#L114)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Its a bit misleading that these are inside `cd` file, but well, seems like running robot tests is also in this file (and it kind of makes sense to have those here as this expects to find docker images from docker hub), so no need to do anything unless you get good idea how to improve this.
</blockquote></details>

Moved it to another workflow
___
*[`.github/workflows/cd.yml` line 142 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/187#-N2H0a6RASSVBIR5ffms:-N2LQNcFCkLKwVtzSeKG:bgvuf1z) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7199bbb6b3208f77acbf4ba1ce84c2ec8b8df249/.github/workflows/cd.yml#L142)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why do we need this, does this wait that environment is up & running or what?
</blockquote></details>

this was only for debugging, removing it :thumbsup:

**Comment by tk-vincit** [comment]
Will reopen this, initial plan was to include these in https://github.com/HSLdevcom/jore4-ui/pull/176 but seems like CI wasn't happy there so lets investigage this further here.

**Comment by tk-vincit** [comment]
Github won't let reopen this, but moved to https://github.com/HSLdevcom/jore4-ui/pull/191

**Pull request closed without merging**
