### PR TITLE
Show map model when the value mapOpen query param is true

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
Resolves HSLdevcom/jore4/issues/620

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pkainulainen-vincit, and @tk-vincit)

___
*[src/components/map/ModalMap.tsx, line 197 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoK8py7e_ZXZXTiH3K:-MzoK8py7e_ZXZXTiH3L:btqavqa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L197)):*
> ```XML
>     const queryParams = new URLSearchParams(history.location.search);
>     if (isMapOpen(queryParams)) {
>       dispatch(setIsModalMapOpenAction(true));
> ```

this could be simplified a bit:
```
const mapOpen = isMapOpen(queryParams);
dispatch(setIsModalOpenAction(mapOpen));
```

and could write a comment for this code block, like:
```
// on page load, synchronizing the redux "isModalMapOpen" state with the query parameter "mapOpen"
```
___
*[src/components/map/ModalMap.tsx, line 204 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoJcirENIPAvhFnyFn:-MzoJcirENIPAvhFnyFo:b-at6exu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L204)):*
> ```XML
> 
>   useEffect(() => {
>     return history.listen((location) => {
> ```

if I follow the logic correctly, then the aim is that:
- when the page is reloaded, based on isMapOpen, then modal should be set open/closed
- when the modal is opened/closed by hand, we should place the 'mapOpen' query parameter

but then why do you need to do a `history.listen` here? We should not listen on changes to the `mapOpen` query parameter
___
*[src/utils/url.ts, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoHdvG3CPH_Noagqy8:-MzoHdvG3CPH_Noagqy9:b1pzyue) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/utils/url.ts#L8)):*
> ```XML
>   history: RouteComponentProps['history'],
> ) => {
>   const queryParams = new URLSearchParams(history.location.search);
> ```

instead of implementing these as utils functions that take the history as a parameter, it's a better practice to make this into a hook with these add/delete/isOpen functions in it. Something like this:

```
const useMapQuery = () => {
  const history = useHistory();
  
  const addMapOpenQueryParameter = () => {
  ...
  }

  const deleteMapOpenQueryParameter = () => {
  }

  const isMapOpen = () => {
  }

  return {
    addMapOpenQueryParameter,
    deleteMapOpenQueryParameter,
    isMapOpen,
  }
}
```

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @pkainulainen-vincit)

___
*[src/components/map/ModalMap.tsx, line 193 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-Mzp6rmM6bmxB1UOhggq:-Mzp6rmM6bmxB1UOhggr:b-392uvm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L193)):*
> ```XML
>   };
> 
>   const history = useHistory();
> ```

Usually we have had useHook calls at the beginning of the component, before function definitions. This is due to "rule" required by react that useHook calls should be always called in same order when same component is rendered, and having all the hook calls in the beginning makes it less likely that we have conditional logic between useHook calls.
React logs warning about that to console if code brokes that rule.

So, if there are no warnings in the console this is OK for me, but could also consider moving this to the beginning of the component.
___
*[src/components/map/ModalMap.tsx, line 204 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoJcirENIPAvhFnyFn:-Mzp7xLe-swHSu3_YPlS:b-1xqzuw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L204)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if I follow the logic correctly, then the aim is that:
- when the page is reloaded, based on isMapOpen, then modal should be set open/closed
- when the modal is opened/closed by hand, we should place the 'mapOpen' query parameter

but then why do you need to do a `history.listen` here? We should not listen on changes to the `mapOpen` query parameter
</blockquote></details>

Yeah, I'm also wondering why we need to listen history? Also seems like this feature was not even documented: https://v5.reactrouter.com/web/api/history

If this is needed, please at least add comment explaining why.
___
*[src/components/map/ModalMap.tsx, line 206 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-Mzp6_qy7qoa5kxlhs46:-Mzp6_qy7qoa5kxlhs47:blyhxtk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L206)):*
> ```XML
>     return history.listen((location) => {
>       const queryParams = new URLSearchParams(location.search);
>       if (isMapOpen(queryParams)) {
> ```

This seems to be exactly same code block as the one above. Should be a function to avoid duplication (if this is needed at all).
___
*[src/utils/url.ts, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzpADPr8O_EHY9MnVLw:-MzpADPs3Si-5GZemqaG:bgtlkkc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/utils/url.ts#L3)):*
> ```XML
> import { RouteComponentProps } from 'react-router-dom';
> 
> const queryParameterNameMapOpen = 'mapOpen';
> ```

Doesn't make much difference, but if you want to be fancy this could be also defined as const:`const queryParameterNameMapOpen = 'mapOpen' as const;`
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions
___
*[src/utils/url.ts, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoHdvG3CPH_Noagqy8:-Mzp8ttu25HE34VG-2SY:b-4g64pa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/utils/url.ts#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

instead of implementing these as utils functions that take the history as a parameter, it's a better practice to make this into a hook with these add/delete/isOpen functions in it. Something like this:

```
const useMapQuery = () => {
  const history = useHistory();
  
  const addMapOpenQueryParameter = () => {
  ...
  }

  const deleteMapOpenQueryParameter = () => {
  }

  const isMapOpen = () => {
  }

  return {
    addMapOpenQueryParameter,
    deleteMapOpenQueryParameter,
    isMapOpen,
  }
}
```
</blockquote></details>

Was going to suggest the same. It makes this easier to be used in different components.
Maybe call the hook `useMapUrlQuery` to make naming a bit more clear.

And it should be located under `src/hooks/directory`

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @pkainulainen-vincit)

___
*[src/components/map/ModalMap.tsx, line 204 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoJcirENIPAvhFnyFn:-MzsPiX78oHial2K6Sjh:b-qz1ush) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L204)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Yeah, I'm also wondering why we need to listen history? Also seems like this feature was not even documented: https://v5.reactrouter.com/web/api/history

If this is needed, please at least add comment explaining why.
</blockquote></details>

The original problem of the issue #620 was that the modal map is still visible if the user clicks the back button. That's why I added the code which listens history and either shows or hides the map (depending on the presence of the `mapOpen` query parameter). Do you think that there is a batter way to solve that problem?

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[src/components/map/ModalMap.tsx, line 193 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-Mzp6rmM6bmxB1UOhggq:-Mzsd2zVAlAiqllBQ_6W:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L193)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Usually we have had useHook calls at the beginning of the component, before function definitions. This is due to "rule" required by react that useHook calls should be always called in same order when same component is rendered, and having all the hook calls in the beginning makes it less likely that we have conditional logic between useHook calls.
React logs warning about that to console if code brokes that rule.

So, if there are no warnings in the console this is OK for me, but could also consider moving this to the beginning of the component.
</blockquote></details>

This is now fixed.
___
*[src/components/map/ModalMap.tsx, line 197 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoK8py7e_ZXZXTiH3K:-Mzsd9RqEb1n5wxoGJz9:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L197)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this could be simplified a bit:
```
const mapOpen = isMapOpen(queryParams);
dispatch(setIsModalOpenAction(mapOpen));
```

and could write a comment for this code block, like:
```
// on page load, synchronizing the redux "isModalMapOpen" state with the query parameter "mapOpen"
```
</blockquote></details>

This is now fixed.
___
*[src/components/map/ModalMap.tsx, line 206 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-Mzp6_qy7qoa5kxlhs46:-MzsdAbs7Cr_QV7BTEhf:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L206)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This seems to be exactly same code block as the one above. Should be a function to avoid duplication (if this is needed at all).
</blockquote></details>

This is now fixed.
___
*[src/utils/url.ts, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoHdvG3CPH_Noagqy8:-MzsdE90AD_w4l5bP01L:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/utils/url.ts#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Was going to suggest the same. It makes this easier to be used in different components.
Maybe call the hook `useMapUrlQuery` to make naming a bit more clear.

And it should be located under `src/hooks/directory`
</blockquote></details>

This is now fixed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[src/utils/url.ts, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzpADPr8O_EHY9MnVLw:-MzseFu5AwT7czC2imxm:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/utils/url.ts#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Doesn't make much difference, but if you want to be fancy this could be also defined as const:`const queryParameterNameMapOpen = 'mapOpen' as const;`
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions
</blockquote></details>

This is now fixed.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/137)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pkainulainen-vincit, and @tk-vincit)

___
*[src/components/RoutesAndLinesPage.tsx, line 5 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-Mzst1RK-ErqL1mxo87L:-Mzst1RK-ErqL1mxo87M:b-dhrnfu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9fa8c713350fc367706a13627fa703be85ea3d10/src/components/RoutesAndLinesPage.tsx#L5)):*
> ```XML
> import { MapEditorContext } from '../context/MapEditor';
> import { useAppDispatch } from '../hooks';
> import { useMapUrlQuery } from '../hooks/useMapUrlQuery';
> ```

it's been a practice that we export all hooks from within `src/hooks/index.ts`. That allows us to group all `hook` imports under the same group and make them a bit more clear
___
*[src/components/map/ModalMap.tsx, line 204 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzoJcirENIPAvhFnyFn:-Mzsu-xgCjPwGnjOb4E4:b2gapzh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4121dc63253d193dff4a7534761cb9dcc2abe3aa/src/components/map/ModalMap.tsx#L204)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

The original problem of the issue #620 was that the modal map is still visible if the user clicks the back button. That's why I added the code which listens history and either shows or hides the map (depending on the presence of the `mapOpen` query parameter). Do you think that there is a batter way to solve that problem?
</blockquote></details>

I don't know how to handle browser history from react... if this is how it works, then fine by me ;)
___
*[src/components/map/ModalMap.tsx, line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzstIcuDGmGXzcmNIci:-MzstIcuDGmGXzcmNIcj:b-jdmgxh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9fa8c713350fc367706a13627fa703be85ea3d10/src/components/map/ModalMap.tsx#L12)):*
> ```XML
> } from '../../hooks';
> import { useEditRouteGeometry } from '../../hooks/useEditRouteGeometry';
> import { useMapUrlQuery } from '../../hooks/useMapUrlQuery';
> ```

it's been a practice that we export all hooks from within `src/hooks/index.ts`. That allows us to group all `hook` imports under the same group and make them a bit more clear

(actually same for `useEditRouteGeometry` hook above ;) )
___
*[src/components/map/ModalMap.tsx, line 79 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/137#-MzstjIG3AscZ_e_3TQ-:-MzstjIG3AscZ_e_3TQ0:b-yrgey2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9fa8c713350fc367706a13627fa703be85ea3d10/src/components/map/ModalMap.tsx#L79)):*
> ```XML
>   // This ensures that the map will be closed if the user
>   // clicks the back button and the 'mapOpen' query parameter
>   // isn't found from the url.
> ```

good to know! Thanks for commenting this! 

BTW, would be simpler if you just placed both code blocks into the same `useEffect` call, they anyway belong together.

**Pull request merged**
