### PR TITLE
Implement route selection in search results

### PR DESCRIPTION
**Pull request by eleksi**
Resolves https://github.com/HSLdevcom/jore4/issues/943

- Enable selecting routes in search results
- Selection can be enabled / disabled with a button
- All search results can be selected at once
- If line has no routes, disable checkbox

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)* status: 0 of 21 files reviewed, 16 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/routes-and-lines/main/LinesList.tsx` line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA-sLVCGRSN76eTg92:-NEA-sLVCGRSN76eTg93:b58b9ld) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LinesList.tsx#L7)):*
> ```XML
> type Props = {
>   lines?: LineTableRowFragment[];
>   isSelecting?: boolean;
> ```

What does `isSelecting` mean? Does this mean `isSelectable`?
___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0ORF3eLkQnFQMcAM:-NEA0ORG6o9q0qP7P6_7:b5zzlap) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L55)):*
> ```XML
> 
>   /**
>    * Entire line is selected for export, if it has routes
> ```

What if only subset of routes is selected?
___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 73 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0jj5DlKtRqIpm3pa:-NEA0jj5DlKtRqIpm3pb:b-p1jp3b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L73)):*
> ```XML
>       onSelectChanged={isSelectable ? onSetSelected : undefined}
>       isSelected={isSelected}
>       selectionDisabled={!hasRoutes}
> ```

Is this missing condition: `!isSelectable || !hasRoutes`?
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 29 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA10aVEA1M1O5GljGv:-NEA10aVEA1M1O5GljGw:b56943b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L29)):*
> ```XML
>   className = '',
>   onLocatorButtonClick,
>   onSelectChanged,
> ```

"Changed" postfix doesn't sound like idiomatic react nor doesn't give any additional information to user regarding this function or its responsibilities. Compare this e.g. to "onBlur", "onChange", "onDelete" etc. So how about `onSelect`?
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 44 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA1ck13Mn2gOjVLfIr:-NEA1ck23CAMqwq86Izc:b-1t4946) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L44)):*
> ```XML
>     <tr className={className}>
>       <Visible visible={!!onSelectChanged}>
>         <td className="w-14">
> ```

Once again I'm asking: why explicit width? If you want some whitespace around input element, it should be done with paddings and/or margins.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA29In3BrsAWcLp6qE:-NEA29In3BrsAWcLp6qF:bdm3ph2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L55)):*
> ```XML
>       </Visible>
>       <td
>         className={`${alertStyle.listItemBorder} w-0 border-y p-0 align-top`}
> ```

What is happening here? Is this `td` element existing only because we want to add visual border? Please rather define border to either one of sibling elements and don't introduce empty dom elements which are intented to be used for semantic purposes.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 57 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA24Dy2SBk2p4Cy-ST:-NEA24Dy2SBk2p4Cy-SU:b-o9wilc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L57)):*
> ```XML
>         className={`${alertStyle.listItemBorder} w-0 border-y p-0 align-top`}
>       />
>       <td className={`${yBorderClassnames} w-20 p-4`}>
> ```

Explicit width..?
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 81 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA2gzZ5lUO89VMVAXU:-NEA2gzZ5lUO89VMVAXV:bovtqrn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L81)):*
> ```XML
>         </Link>
>       </td>
>       <td className={`w-20 border-r p-6 align-middle ${yBorderClassnames}`}>
> ```

Explicit width? Ok, not part of this PR but could be refactored out same time as rest of the columns are fixed.
___
*[`ui/src/components/routes-and-lines/main/RoutesList.tsx` line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA2rK62FAM0ZLCGRcV:-NEA2rK62FAM0ZLCGRcW:b-w1o0s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RoutesList.tsx#L23)):*
> ```XML
>         key={item.route_id}
>         route={item}
>         isSelectable={isSelecting}
> ```

I don't understand why this prop is called "isSelecting" if it means "isSelectable". 
___
*[`ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx` line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA37uYDg25ysTlcmjL:-NEA37uYDg25ysTlcmjM:bkr7kg3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx#L60)):*
> ```XML
>             key={item.route_id}
>             route={item}
>             isSelectable={false}
> ```

This could be default value for the prop in RouteTableRow, so that we don't need to define it here (twice) in this file. Or are all instances of this component going to require isSelectable prop in the near future?
___
*[`ui/src/components/routes-and-lines/main/RouteTableRow.tsx` line 33 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA3S493t4rUWwkAclg:-NEA3S493t4rUWwkAclh:b-w6v91e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteTableRow.tsx#L33)):*
> ```XML
>   };
> 
>   const onSetSelected = (event: React.ChangeEvent<HTMLInputElement>) => {
> ```

Looks 1:1 like code I just saw above in this PR. If this is shared between two components that do just render RouteLineTableRow -> does this actually belong to RoutesTable? (which btw. has confusing name, as it seems to be used also for lines).

Also this function has a bit confusing name (what does onSetSelected mean? This seems to be bassed as "onSelectChanged", so should this be called "onSelectChanged"? Or actually just "onSelect" if you use my suggestion for naming from previous comment.)
___
*[`ui/src/components/routes-and-lines/search/ExportToolbar.tsx` line 49 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA5gOm3lKgu43_ec9s:-NEA5gOnCiN5SpZ03Du0:bay0r8k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/ExportToolbar.tsx#L49)):*
> ```XML
>   const toggleIsSelecting = () => {
>     dispatch(setIsSelectingAction(!isSelecting));
>     dispatch(resetSelectedRoutesAction());
> ```

So, this toggles "setIsSelectingAction" but does not actually toggle "resetSelectedRoutesAction"..? Is this potential source for error?
___
*[`ui/src/components/routes-and-lines/search/ExportToolbar.tsx` line 83 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA6nK28A9zQnJjZtFP:-NEA6nK28A9zQnJjZtFQ:bxb21pv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/ExportToolbar.tsx#L83)):*
> ```XML
>           inverted
>           onClick={exportRoutes}
>           label={t(`export.${isExportingAll ? 'exportAll' : 'exportSelected'}`)}
> ```

Definitely nitpicking and also a bit matter of personal opinion, but generally I would avoid building translation keys dynamically if that is easily prevented (as in this case: 
`t(isExportingAll ? 'export.exportAll' : 'export.exportSelected')`.
That way it is easier to see if the keys from translation file are used with global search:`'export.export`
___
*[`ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx` line 26 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA6Kxn7liXZmgixHRd:-NEA6Kxn7liXZmgixHRe:bd5u4h6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx#L26)):*
> ```XML
> 
>   return (
>     <div>
> ```

If I parsed these changes correctly in my head, you could define `className="space-x-2"` here and remove new classNames from SimpleSmallButtons.
___
*[`ui/src/redux/slices/export.ts` line 5 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA8K_98SyyEqKBDOJM:-NEA8K_98SyyEqKBDOJN:bs0i4dp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/redux/slices/export.ts#L5)):*
> ```XML
> 
> interface IState {
>   isSelecting: boolean;
> ```

Don't have good suggestion right now, but perhaps this sounds a bit vague. Is selecting what?
___
*[`ui/src/redux/slices/export.ts` line 52 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA87P24CyJmMgTeG3-:-NEA87P24CyJmMgTeG30:b-6evtxo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/redux/slices/export.ts#L52)):*
> ```XML
>     },
>     resetSelectedRoutes: (state) => {
>       state.selectedRouteLabels = [];
> ```

state.selectedRouteLabels = initialState.selectedRouteLabels :thinking:

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)* status: 0 of 21 files reviewed, 15 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/routes-and-lines/main/LinesList.tsx` line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA-sLVCGRSN76eTg92:-NEAMxuvAxkTGWZfbX0Z:b7csp9k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LinesList.tsx#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What does `isSelecting` mean? Does this mean `isSelectable`?
</blockquote></details>

Well, we cannot select the list, only the items, so I think `isSelectable` doesn't really fit. We agreed to go with `areItemsSelectable`
___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0ORF3eLkQnFQMcAM:-NEANfr8DxJVCyqKWCcd:bxsjcv6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L55)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What if only subset of routes is selected?
</blockquote></details>

We only support selecting from lines list or from routes list, so this case really doesn't even happen. This was design decision.
___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 73 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0jj5DlKtRqIpm3pa:-NEANmLS5iPdjFcYya-n:b5cy1x3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L73)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is this missing condition: `!isSelectable || !hasRoutes`?
</blockquote></details>

The entire checkbox is disabled if it is not selectable.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 29 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA10aVEA1M1O5GljGv:-NEAa-nABlh9enc8yfJY:bejh16c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L29)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"Changed" postfix doesn't sound like idiomatic react nor doesn't give any additional information to user regarding this function or its responsibilities. Compare this e.g. to "onBlur", "onChange", "onDelete" etc. So how about `onSelect`?
</blockquote></details>

As this event is fired for both select and deselect, we agreed in slack that this name is ok. `onSelect` kind of excludes deselect.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 44 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA1ck13Mn2gOjVLfIr:-NEAp4x07-bZdW0Zn2-P:basrdcs) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L44)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Once again I'm asking: why explicit width? If you want some whitespace around input element, it should be done with paddings and/or margins.
</blockquote></details>

Too little whitespace is not the problem, too much of it is, as the column automatically expands way too wide. This is something that has to be looked into separately.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA29In3BrsAWcLp6qE:-NEAaGeE3FNpRPIWZ2hV:b19rqd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L55)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What is happening here? Is this `td` element existing only because we want to add visual border? Please rather define border to either one of sibling elements and don't introduce empty dom elements which are intented to be used for semantic purposes.
</blockquote></details>

In the first iteration I didn't realize we can give different borders different colors, therefore it had to be implemented this way so border colors wouldn't conflict. After realizing that this could be implemented much better.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 57 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA24Dy2SBk2p4Cy-ST:-NEAhwvt8KBYTCSpF2ab:be1bjs0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L57)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Explicit width..?
</blockquote></details>

Width is defined to limit the amount of space this column is given. I can remove it, but this will result this view looking less like in the designs.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 81 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA2gzZ5lUO89VMVAXU:-NEAjKr05Jtvb3Q2sb3Q:ba9m3u1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L81)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Explicit width? Ok, not part of this PR but could be refactored out same time as rest of the columns are fixed.
</blockquote></details>

There could be some css trick to restrict columns width expanding beyond their content (`table-layout:fixed;`?) but requires more investigation.
___
*[`ui/src/components/routes-and-lines/main/RoutesList.tsx` line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA2rK62FAM0ZLCGRcV:-NEAqXzL4H4jPxv-v3aI:b-x6idlj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RoutesList.tsx#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand why this prop is called "isSelecting" if it means "isSelectable". 
</blockquote></details>

Single row is selectable, if we are selecting routes for export.
___
*[`ui/src/components/routes-and-lines/main/RouteTableRow.tsx` line 33 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA3S493t4rUWwkAclg:-NEAqpoy4c9euupQUYq0:bdjflr6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RouteTableRow.tsx#L33)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Looks 1:1 like code I just saw above in this PR. If this is shared between two components that do just render RouteLineTableRow -> does this actually belong to RoutesTable? (which btw. has confusing name, as it seems to be used also for lines).

Also this function has a bit confusing name (what does onSetSelected mean? This seems to be bassed as "onSelectChanged", so should this be called "onSelectChanged"? Or actually just "onSelect" if you use my suggestion for naming from previous comment.)
</blockquote></details>

Renamed the function.

Functionality is not quite the same. We dispatch different actions with different types of payload (string vs string[])
___
*[`ui/src/components/routes-and-lines/search/ExportToolbar.tsx` line 49 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA5gOm3lKgu43_ec9s:-NEAReZUEbqomsq1MtBk:bo10vkc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/ExportToolbar.tsx#L49)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

So, this toggles "setIsSelectingAction" but does not actually toggle "resetSelectedRoutesAction"..? Is this potential source for error?
</blockquote></details>

Shouldn't be. We just want to clear selection every time.
___
*[`ui/src/components/routes-and-lines/search/ExportToolbar.tsx` line 83 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA6nK28A9zQnJjZtFP:-NEAS8j4-n-2lWQ_TRrG:b99xxyq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/ExportToolbar.tsx#L83)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Definitely nitpicking and also a bit matter of personal opinion, but generally I would avoid building translation keys dynamically if that is easily prevented (as in this case: 
`t(isExportingAll ? 'export.exportAll' : 'export.exportSelected')`.
That way it is easier to see if the keys from translation file are used with global search:`'export.export`
</blockquote></details>

Sure! I was also considering between those and this is probably better.
___
*[`ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx` line 26 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA6Kxn7liXZmgixHRd:-NEASQzg2wVn4KmCKGrC:b-80bnw2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/filters/ResultSelector.tsx#L26)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If I parsed these changes correctly in my head, you could define `className="space-x-2"` here and remove new classNames from SimpleSmallButtons.
</blockquote></details>

True!
___
*[`ui/src/redux/slices/export.ts` line 5 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA8K_98SyyEqKBDOJM:-NEArLvE1mU2m_b2KVG2:b-jywbip) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/redux/slices/export.ts#L5)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Don't have good suggestion right now, but perhaps this sounds a bit vague. Is selecting what?
</blockquote></details>

Renamed to `isSelectingRoutesForExport`
___
*[`ui/src/redux/slices/export.ts` line 52 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA87P24CyJmMgTeG3-:-NEArS8T6EuWlIantvAh:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/redux/slices/export.ts#L52)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

state.selectedRouteLabels = initialState.selectedRouteLabels :thinking: 
</blockquote></details>

Done
___
*[`ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx` line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA37uYDg25ysTlcmjL:-NEAmqQb3q54RNb6KMq4:bew7jev) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/RoutesTable.spec.tsx#L60)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This could be default value for the prop in RouteTableRow, so that we don't need to define it here (twice) in this file. Or are all instances of this component going to require isSelectable prop in the near future?
</blockquote></details>

I added default value. All use cases have isSelectable prop so far, but still why not add default.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)* status: 0 of 21 files reviewed, 7 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0ORF3eLkQnFQMcAM:-NEFCbNS66EYNyMqJe8z:bncz98d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L55)):*
OK, but maybe that could have been clarified here in a comment then aswell.

Now we are explicitly checking that every route is selected, I assume there is a reason for that?

Perhaps something like this (or better wording by you as you're more familiar with this)? I'm not sure if this comment is actually true, since there is check that every route is selected.

>"Entile line is selected for export if it has routes and all each of those are selected. Selecting only subset of routes shouldn't be possible."
___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 73 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0jj5DlKtRqIpm3pa:-NEFgtikBGTqT_EWle6a:b-29p8s7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L73)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

The entire checkbox is disabled if it is not selectable.
</blockquote></details>

Well, OK, seems like RouteLineTableRow receives `line` as prop called `rowItem` and `hasRoutes` is defined like this: ` const hasRoutes = line.line_routes?.length > 0;`
Why is this `selectionDisabled" given as prop and related logic is implemented here, couldn't RouteLineTableRow figure this out by itself? Or is this more readable now? :shrug: 
___
*[`ui/src/components/routes-and-lines/search/ExportToolbar.tsx` line 49 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA5gOm3lKgu43_ec9s:-NEFBqMLEDJ9UE8ME9JO:b-vwnl5y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/ExportToolbar.tsx#L49)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Shouldn't be. We just want to clear selection every time.
</blockquote></details>

Well, I'm always a bit worried when function does something else than its name promises, but maybe this is safe enough to do here then.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)* status: 0 of 21 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 55 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0ORF3eLkQnFQMcAM:-NEG6WCdBQhEiCjR2qf3:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L55)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

OK, but maybe that could have been clarified here in a comment then aswell.

Now we are explicitly checking that every route is selected, I assume there is a reason for that?

Perhaps something like this (or better wording by you as you're more familiar with this)? I'm not sure if this comment is actually true, since there is check that every route is selected.

>"Entile line is selected for export if it has routes and all each of those are selected. Selecting only subset of routes shouldn't be possible."
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 73 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0jj5DlKtRqIpm3pa:-NEG6fPR2eFLmvOSSxbX:b-qnl1rd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L73)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, OK, seems like RouteLineTableRow receives `line` as prop called `rowItem` and `hasRoutes` is defined like this: ` const hasRoutes = line.line_routes?.length > 0;`
Why is this `selectionDisabled" given as prop and related logic is implemented here, couldn't RouteLineTableRow figure this out by itself? Or is this more readable now? :shrug: 
</blockquote></details>

As `RouteLineTableRoute` is also used by `RouteTableRow` and it can also take route as rowItem parameter, I figured there should not be line / route specific logic inside this common component.

I think `LineTableRow` is the correct location for line specific logic, `RouteLineTableRow` should only do things that are common for all rowItem types (route and line).
___
*[`ui/src/components/routes-and-lines/search/ExportToolbar.tsx` line 49 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA5gOm3lKgu43_ec9s:-NEG9s3-4XpTIHeFePHT:b-phd5qm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/search/ExportToolbar.tsx#L49)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, I'm always a bit worried when function does something else than its name promises, but maybe this is safe enough to do here then.
</blockquote></details>

I added a comment, idk if it adds any value though

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 73 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEA0jj5DlKtRqIpm3pa:-NEdpG015ZqcwMEmno7k:bapdlyb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/30a7ed9da67f9c32710b606173d93911547fa4b0/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L73)):*
> correct
OK
___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 55 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEdo65Y3xF6DjgPPneA:-NEdo65Y3xF6DjgPPneB:bgmo2ko) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7359d9ec3eef03654cd03520917bef07a4120e1b/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L55)):*
> ```XML
> 
>   /**
>    * Entile line is selected for export if it has routes and each of those is selected.
> ```

Typo: Entile -> Entire.
___
*[`ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx` line 61 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/357#-NEdpemx-gAFs6Q004Uf:-NEdpemx-gAFs6Q004Ug:bqa8ky2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7359d9ec3eef03654cd03520917bef07a4120e1b/ui/src/components/routes-and-lines/main/RouteLineTableRow.tsx#L61)):*
> ```XML
>       <td
>         /*
>           Hard coded width, because we need to reserve space for possibly missing icon, 
> ```

This sounds like case where (placeholder?) icon should be always rendered with `visiblility: hidden` so that this problem wouldn't exists in the first place.
https://www.w3schools.com/cssref/pr_class_visibility.asp



_Code quote:_
```XML
          Hard coded width, because we need to reserve space for possibly missing icon, 
          to keep table consistent regardless of if the icon exist in a row or not
```

**Review by tk-vincit — APPROVED** [review]
> Reviewed 3 of 19 files at r1, 2 of 13 files at r4, 3 of 15 files at r7, 3 of 12 files at r10, 1 of 1 files at r11, 3 of 5 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/357)* status: 18 of 23 files reviewed, 3 unresolved discussions (waiting on @eleksi)

**Pull request merged**
