### PR TITLE
Add E2E test for creating routes

### PR DESCRIPTION
**Pull request by culka**
Add E2E test for creating routes on the UI

Add pageobjects for accessing the relevant elements

Add support for testIds for Row types

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/240)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/240)* status: 0 of 19 files reviewed, 13 unresolved discussions (waiting on @culka and @pallost)

___
*[`cypress/e2e/createRoute.cy.ts` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5ExvU85N2Ofljt21VI:-N5ExvU85N2Ofljt21VJ:b-6yrfdk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/e2e/createRoute.cy.ts#L1)):*
> ```XML
> import { ConfirmSaveForm, MapEditor, MapFooter, RoutePropertiesForm, TerminusNameInputs } from '../pageObjects';
> ```

Please run prettier, so that the formatting is fixed
___
*[`cypress/e2e/createRoute.cy.ts` line 24 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Exz6m-goZfl5K50OG:-N5Exz6m-goZfl5K50OH:b-rb4wip) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/e2e/createRoute.cy.ts#L24)):*
> ```XML
> 
>     // Date input errenously inputs zoom out commands, these offset them
>     mapEditor.zoomIn();
> ```

this hack will surely introduce some flakyness to this test. Let's rather try to fix the date input itself!
___
*[`cypress/e2e/createRoute.cy.ts` line 34 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ey7947VhVyHKbOTdY:-N5Ey7947VhVyHKbOTdZ:bhpswze) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/e2e/createRoute.cy.ts#L34)):*
> ```XML
> 
>     // Force text inputs due to scrolling causing zoom out
>     terminusNameInputs.getTerminusOriginFinnishNameInput().type("Lähtöpaikka", { force: true });
> ```

same here, instead of trying to force the input, let's rather hunt down the issue itself, not to introduce flakyness to the test
___
*[`cypress/pageObjects/MapEditor.ts` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5F06it69Cm68XhAKsv:-N5F06it69Cm68XhAKsw:b-klejib) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/MapEditor.ts#L1)):*
> ```XML
> function positionStringToCoordinates(value: string | null) {
> ```

smart!
___
*[`cypress/pageObjects/MapEditor.ts` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5F-KLz6VvmOAA8tjDz:-N5F-KLz6VvmOAA8tjE-:boqt302) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/MapEditor.ts#L20)):*
> ```XML
>     // Uses css indexing which starts from 1
>     clickAtPositionFromNthMapMarker(xpos: number, ypos: number, markerNumber: number) {
>         cy.get(`.overlays>.mapboxgl-marker:nth-of-type(${markerNumber})`).then(mark => { 
> ```

this should be its own selector:
```
getNthMarker(markerNumber: number) => {
  return cy.get(`.overlays>.mapboxgl-marker:nth-of-type(${markerNumber})`).first();
}
```



_Code quote:_
```XML
cy.get(`.overlays>.mapboxgl-marker:nth-of-type(${markerNumber})`)
```
___
*[`cypress/pageObjects/RoutePropertiesForm.ts` line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Eza_77MK9A5XsSFZm:-N5Eza_77MK9A5XsSFZn:b-6gujc6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/RoutePropertiesForm.ts#L2)):*
> ```XML
> export class RoutePropertiesForm {
>     getLabelInput() {
> ```

it would be smart to introduce a single function that takes an object with all these values and feeds them to the form inputs
___
*[`cypress/pageObjects/RoutePropertiesForm.ts` line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5EzgLFEpN9eB1aQV-_:-N5EzgLFEpN9eB1aQV-a:btkxihn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/RoutePropertiesForm.ts#L3)):*
> ```XML
> export class RoutePropertiesForm {
>     getLabelInput() {
>       return cy.get('#label');
> ```

this should also have a testId
___
*[`cypress/pageObjects/RoutePropertiesForm.ts` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ezcqs098z174oUHy0:-N5Ezcqs098z174oUHy1:btkxihn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/RoutePropertiesForm.ts#L7)):*
> ```XML
>   
>     getFinnishNameInput() {
>       return cy.get('#finnishName');
> ```

this should also have a testId
___
*[`cypress/pageObjects/TerminusNameInputs.ts` line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Eyq27D-Zw3f4p_pXH:-N5Eyq27D-Zw3f4p_pXI:b-6gujc6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/TerminusNameInputs.ts#L2)):*
> ```XML
> export class TerminusNameInputs {
>     getTerminusOriginFinnishNameInput() {
> ```

it would be smart to introduce a single function that takes an object with all these values and feeds them to the form inputs
___
*[`ui/src/components/map/MapOverlay.tsx` line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5EzNc-5hQA-BPoMaZT:-N5EzNc-5hQA-BPoMaZU:b-vz4fbi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/components/map/MapOverlay.tsx#L13)):*
> ```XML
> }) => {
>   return (
>     <Column className={`w-72 bg-white shadow-md map-overlay ${className}`}>
> ```

such css classname does not exist. If you need to identity these kind of elements, use a testId instead
___
*[`ui/src/components/map/Modal.tsx` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5EzFiR9cnnDNprDoNq:-N5EzFiR9cnnDNprDoNr:b2ly1i9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/components/map/Modal.tsx#L28)):*
> ```XML
>           {t('cancel')}
>         </SimpleButton>
>         <SimpleButton testId='modal:saveButton' onClick={onSave}>{t('save')}</SimpleButton>
> ```

Modal:saveButton
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 103 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ez0w5C5fA6DC160mx:-N5Ez0w5C5fA6DC160my:b-36s5yg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/components/map/RouteStopsOverlay.tsx#L103)):*
> ```XML
>   return (
>     <MapOverlay className={className}>
>       <MapOverlayHeader testId='mapOverlayHeader'>
> ```

RouteStopsOverlay:mapOverlayHeader
___
*[`ui/src/layoutComponents/Row.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ez8In0L6J4paDnOdU:-N5Ez8In0L6J4paDnOdV:boqh4c2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/layoutComponents/Row.tsx#L10)):*
> ```XML
> export const Row: React.FC<Props> = ({ className, children, testId }) => {
>   if (testId) {
>     return <div className={`flex flex-row ${className}`} data-testId={`${testId}`}>{children}</div>;  
> ```

you don't need template string here, just write `data-testId={testId}`

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/240)* status: 0 of 19 files reviewed, 14 unresolved discussions (waiting on @culka, @pallost, and @tk-vincit)

___
*[`ui/src/layoutComponents/Row.tsx` line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5FGYtM1Dq5__4IrEUO:-N5FGYtND9mwsv-hIXOP:b-9optg6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc12a6079173d50e9d26dcb7a2d97c3b5e5df438/ui/src/layoutComponents/Row.tsx#L8)):*
> ```XML
> }
> 
> export const Row: React.FC<Props> = ({ className, children, testId }) => {
> ```

please add default value to testId: `testId = ''`. Otherwise we'll end up having multiple testIds in DOM with value "undefined"

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/240)* status: 0 of 19 files reviewed, 14 unresolved discussions (waiting on @culka, @pallost, and @tk-vincit)

___
*[`cypress/e2e/createRoute.cy.ts` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5ExvU85N2Ofljt21VI:-N5F3A3Z30UwGyjGJoUd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/e2e/createRoute.cy.ts#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Please run prettier, so that the formatting is fixed
</blockquote></details>

Done.
___
*[`cypress/e2e/createRoute.cy.ts` line 24 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Exz6m-goZfl5K50OG:-N5F39F23xMhoB0AqJc6:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/e2e/createRoute.cy.ts#L24)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this hack will surely introduce some flakyness to this test. Let's rather try to fix the date input itself!
</blockquote></details>

Done.
___
*[`cypress/e2e/createRoute.cy.ts` line 34 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ey7947VhVyHKbOTdY:-N5F3Cl21IlKGamkvksq:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/e2e/createRoute.cy.ts#L34)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

same here, instead of trying to force the input, let's rather hunt down the issue itself, not to introduce flakyness to the test
</blockquote></details>

Done.
___
*[`cypress/pageObjects/MapEditor.ts` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5F-KLz6VvmOAA8tjDz:-N5FFsbv8eDsmmkp_M05:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/MapEditor.ts#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should be its own selector:
```
getNthMarker(markerNumber: number) => {
  return cy.get(`.overlays>.mapboxgl-marker:nth-of-type(${markerNumber})`).first();
}
```
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RoutePropertiesForm.ts` line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Eza_77MK9A5XsSFZm:-N5FMoyRDYFrgs0hAbQV:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/RoutePropertiesForm.ts#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it would be smart to introduce a single function that takes an object with all these values and feeds them to the form inputs
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RoutePropertiesForm.ts` line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5EzgLFEpN9eB1aQV-_:-N5FMB_164sLe-Rrm71h:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/RoutePropertiesForm.ts#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should also have a testId
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RoutePropertiesForm.ts` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ezcqs098z174oUHy0:-N5FMCk39lMDD2s657Qm:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/RoutePropertiesForm.ts#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should also have a testId
</blockquote></details>

Done.
___
*[`cypress/pageObjects/TerminusNameInputs.ts` line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Eyq27D-Zw3f4p_pXH:-N5FPX876yktqf4FHw7C:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/cypress/pageObjects/TerminusNameInputs.ts#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it would be smart to introduce a single function that takes an object with all these values and feeds them to the form inputs
</blockquote></details>

Done.
___
*[`ui/src/components/map/MapOverlay.tsx` line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5EzNc-5hQA-BPoMaZT:-N5FG3BM1hIUpH7R-HFN:bn9y8zb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/components/map/MapOverlay.tsx#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

such css classname does not exist. If you need to identity these kind of elements, use a testId instead
</blockquote></details>

This one was not needed at all actually.
___
*[`ui/src/components/map/Modal.tsx` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5EzFiR9cnnDNprDoNq:-N5FGrjFBi53wcsuF6ap:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/components/map/Modal.tsx#L28)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Modal:saveButton
</blockquote></details>

Done.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 103 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ez0w5C5fA6DC160mx:-N5FHQ7PBN5ennbjPCqE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/components/map/RouteStopsOverlay.tsx#L103)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

RouteStopsOverlay:mapOverlayHeader
</blockquote></details>

Done.
___
*[`ui/src/layoutComponents/Row.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5Ez8In0L6J4paDnOdU:-N5FIrKQ6ftzdpcT4b1q:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dea7479788ea9a8651e24ebba3fad66e043a89e9/ui/src/layoutComponents/Row.tsx#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you don't need template string here, just write `data-testId={testId}`
</blockquote></details>

Done.
___
*[`ui/src/layoutComponents/Row.tsx` line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5FGYtM1Dq5__4IrEUO:-N5FIAnsDlaCzHe0nmv6:b-1ni7zv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc12a6079173d50e9d26dcb7a2d97c3b5e5df438/ui/src/layoutComponents/Row.tsx#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

please add default value to testId: `testId = ''`. Otherwise we'll end up having multiple testIds in DOM with value "undefined"
</blockquote></details>

```
if (testId)
```

Should filter undefined out

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/240)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @culka, @pallost, and @tk-vincit)

___
*[`cypress/e2e/createRoute.cy.ts` line 32 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N6CPOkB3gQKMceytg61:-N6CPOkB3gQKMceytg62:bbrslw3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0fe3e346c583d8efb67aeb2f84ad029e897ffa7b/cypress/e2e/createRoute.cy.ts#L32)):*
> ```XML
>       const routeName = 'Testilinja 1';
> 
>       routePropertiesForm.fillRouteProperties({
> ```

looks nice!
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 2 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N6CQ1UD8ulzp4KONafj:-N6CQ1UD8ulzp4KONafk:b-9ctfc4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0fe3e346c583d8efb67aeb2f84ad029e897ffa7b/cypress/pageObjects/ConfirmSaveForm.ts#L2)):*
> ```XML
> export class ConfirmSaveForm {
>   setAsStandard(forceAction = false) {
> ```

let's remove the forceAction parameters from here
___
*[`ui/src/layoutComponents/Row.tsx` line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/240#-N5FGYtM1Dq5__4IrEUO:-N6CQdi9BiuzEe-fnRLl:bhy568s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc12a6079173d50e9d26dcb7a2d97c3b5e5df438/ui/src/layoutComponents/Row.tsx#L8)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

```
if (testId)
```

Should filter undefined out
</blockquote></details>

Let's go with the `testId = ''` solution, instead of copy-pasting code. Or `testId = null` or whatever makes React not to render the attribute.

**Review by culka — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 7 of 12 files at r2, 1 of 10 files at r5, 6 of 9 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/240)* status: all files reviewed, 3 unresolved discussions (waiting on @culka, @pallost, and @tk-vincit)

**Pull request merged**
