### PR TITLE
Add or replace hastus point

### PR DESCRIPTION
**Pull request by Perholehto**
Closes HSLdevcom/jore4#1561

This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706)* status: all files reviewed, 6 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisXIswEitlegQHxQM7):*
Great commit descriptions! :tada: 
___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisXXRP0GZBwgbd4X5N):*
typo
___
*[`ui/src/components/forms/stop/ChooseTimingPlaceDropdown.tsx` line 32 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisY-v18F7cPGF26i7s:-NisY-v18F7cPGF26i7t:b-4o8w6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c5fd25106c53baa93a8c0a505eb2d9b5873dbb07/ui/src/components/forms/stop/ChooseTimingPlaceDropdown.tsx#L32)):*
> ```XML
>   onChange,
>   onBlur,
>   optionAmount,
> ```

Good one! This should be a prop for other dropdowns generally in our site as well, since I already know at least one UX issue with too long dropdown options, but  thats not part of this at all PR at all.

But actually in the commit message you say `If not limited, dropdown stretches modal` and that problem should be possible to avoid with correct styles. I'll continue on this on slack.
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 137 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisZSvZ3y3_xf_ly9Tl:-NisZSvZ3y3_xf_ly9Tm:bqdlxun) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c5fd25106c53baa93a8c0a505eb2d9b5873dbb07/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L137)):*
> ```XML
>             />
>           ) : (
>             <IconButton
> ```

NIT, This would probably be more readable if we had own component for this, but it is completely OK like it is as well. 

e.g.
```
{hastuscode ? (
  <HastusCode
    ...
  />
) : (
  <AddHastusCodeButton
    ...
  />
```
___
*[`ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 24 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisUcy29z33JEkoyuSF:-NisUcy29z33JEkoyuSG:b-xgozmj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/98eb8b481e47c54bafdfdf27ba93927ee2a293b7/ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L24)):*
> ```XML
>   stopLabel: string;
>   stopBelongsToJourneyPattern: boolean;
>   isViaPoint?: boolean;
> ```

I think we always need the viaPoint information, so this probably should not be optional. If there is a possibility that it is undefined / null, then it can be added as a type, but still keep the parameter as required. (Same question goes for the other optional parameters, is there a case where you could use this component without giving those values?)



_Suggestion:_
```XML
  isViaPoint: boolean | null | undefined;
```
___
*[`ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 53 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisW3cg513VOGyj4k3W:-NisW3cg513VOGyj4k3X:b-k73pa0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/98eb8b481e47c54bafdfdf27ba93927ee2a293b7/ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L53)):*
> ```XML
> 
>   const showTimingSettingsModal = () => {
>     if (journeyPatternId && scheduledStopPointSequence !== undefined) {
> ```

Hmm, I'm struggling to wrap my head around this. So to show the timingSettingsModal, why do we need to check if scheduledStopPointSequence is undefined? Im also not sure why we need to check journeyPatternId either. So what are the cases when these conditions are not met?
___
*[`ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx` line 88 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-Nis_bfXCFFDpycCFB7w:-Nis_bfXCFFDpycCFB7x:b-58sw94) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c5fd25106c53baa93a8c0a505eb2d9b5873dbb07/ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx#L88)):*
> ```XML
>       setValue('isUsedAsTimingPoint', false);
>     }
>   }, [setValue, timingPlaceId]);
> ```

NIT, the order of these are different in the above dependency arrays :D
___
*[`ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx` line 124 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisaHq55wv847F-EDDD:-NisaHq55wv847F-EDDE:b-h6oj3w) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c5fd25106c53baa93a8c0a505eb2d9b5873dbb07/ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx#L124)):*
> ```XML
>           <label
>             htmlFor="isUsedAsTimingPoint"
>             className="mt-6 inline-flex font-normal"
> ```

Instead of pixelplacing each of these "rows" on this modal, it should be accomplishable with more general styles, but since the problem is already on the existing code, I'm not going to request any changes in this PR and this is fine as it is :+1:

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @Perholehto)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisXIswEitlegQHxQM7):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Great commit descriptions! :tada:
</blockquote></details>

Thanks!
___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisXXRP0GZBwgbd4X5N):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 137 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisZSvZ3y3_xf_ly9Tl:-Nj6YUW35JoXUwBF3YyU:byl2cl7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c5fd25106c53baa93a8c0a505eb2d9b5873dbb07/ui/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L137)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, This would probably be more readable if we had own component for this, but it is completely OK like it is as well. 

e.g.
```
{hastuscode ? (
  <HastusCode
    ...
  />
) : (
  <AddHastusCodeButton
    ...
  />
```
</blockquote></details>

This will get some attention when refactoring `RouteStopsRow`
___
*[`ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 24 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisUcy29z33JEkoyuSF:-Nisx0sq80sCTLOLA5XU:b-dlopok) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/98eb8b481e47c54bafdfdf27ba93927ee2a293b7/ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L24)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think we always need the viaPoint information, so this probably should not be optional. If there is a possibility that it is undefined / null, then it can be added as a type, but still keep the parameter as required. (Same question goes for the other optional parameters, is there a case where you could use this component without giving those values?)
</blockquote></details>

Really good catch! change these to not be optional but have type eg. `boolean | undefined`
___
*[`ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 53 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisW3cg513VOGyj4k3W:-Nj6Y-Sq9m9xYL3_r-zZ:bkw2cz3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/98eb8b481e47c54bafdfdf27ba93927ee2a293b7/ui/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L53)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, I'm struggling to wrap my head around this. So to show the timingSettingsModal, why do we need to check if scheduledStopPointSequence is undefined? Im also not sure why we need to check journeyPatternId either. So what are the cases when these conditions are not met?
</blockquote></details>

This was discussed in telco and needs a refactor that will be done later in this sprint.
___
*[`ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx` line 88 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-Nis_bfXCFFDpycCFB7w:-Nj6Y6deEqJ7Orq_TK3r:bb6mt9b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c5fd25106c53baa93a8c0a505eb2d9b5873dbb07/ui/src/components/routes-and-lines/stop-timing-settings/TimingSettingsForm.tsx#L88)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, the order of these are different in the above dependency arrays :D
</blockquote></details>

:+1:

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisXIswEitlegQHxQM7):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Great commit descriptions! :tada:
</blockquote></details>

Thanks!
___
*[`-- commits` line 16 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-NisXXRP0GZBwgbd4X5N):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

typo
</blockquote></details>

done

**Review by HenrikHartiala — APPROVED** [review]
Great! 

> Reviewed 1 of 7 files at r4, 2 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/706#-:-Nj7A17t7nCbSG2N-lRX:b-39tvfd)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @Perholehto)

**Pull request merged**
