### PR TITLE
Show routes in map for selected observation date

### PR DESCRIPTION
**Pull request by eleksi**
- User selects observation date in the map view -> display correct validity version of the route
- If user selects a future / past route from the list view to be displayed in the map, adjust observation date so the route is shown
- Observation date input is disabled while creating / editing route geometry

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/121)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/121)* status: 0 of 19 files reviewed, 4 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[src/components/LineTableRow.tsx, line 31 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvPAzY3EYNIWDNK1Ui:-MyvPAzY3EYNIWDNK1Uj:b-ypug91) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/LineTableRow.tsx#L31)):*
> ```XML
>       lineRouteIds,
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>       parseISODateString(line.validity_start)!,
> ```

I think parseISODateString function calls are no longer needed after this is merged: https://github.com/HSLdevcom/jore4-ui/pull/118
Same also for other places with same function call.
___
*[src/components/map/Map.tsx, line 53 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvXJhY30s4qcA3jyzC:-MyvXJhY30s4qcA3jyzD:b-5shf69) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/map/Map.tsx#L53)):*
> ```XML
> 
>   const routeSelected = !!(
>     initiallyDisplayedRouteIds && initiallyDisplayedRouteIds.length > 0
> ```

`> 0` not needed. Also could be shorter: `!!initiallyDisplayedRouteIds?.length`
___
*[src/components/map/ModalMap.tsx, line 145 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvQBxe-SpaIWdpusQR:-MyvQBxe-SpaIWdpusQS:b-1zz1s0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/map/ModalMap.tsx#L145)):*
> ```XML
>           ) {
>             mapFilterDispatch(setObservationDate(validityStart));
>             showSuccessToast(t('filters.observationDateAdjusted'));
> ```

Is this really something that requires toast message? Seems like we are just setting local state of the app here, right? When can it fail?
___
*[src/hooks/useEditRouteGeometry.ts, line 200 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvRuZi8lnAE6PAA8Y8:-MyvRuZi8lnAE6PAA8Y9:b-kowm9o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useEditRouteGeometry.ts#L200)):*
> ```XML
> 
>   // TODO: Implement with selectors
>   const isInViewMode = drawingMode === undefined;
> ```

protip: `const isInViewMode = !!drawingMode`. Or can drawingMode be `null` or `""` or `0`? And if `drawingMode === null` should viewMode then be `false`? I think not, but now it is.
___
*[src/hooks/useEditRouteGeometry.ts, line 209 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvSOab3Ny3EL8AuIjp:-MyvSOab3Ny3EL8AuIjq:bnh4y83) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useEditRouteGeometry.ts#L209)):*
> ```XML
>     deleteStopFromJourneyPattern,
>     addStopToRouteJourneyPattern,
>     isInViewMode,
> ```

These don't belong under `// edit` section. Maybe create new "// selectors" section or implement these as selectors to some other place already :)
___
*[src/hooks/useShowRoutesOnModal.ts, line 18 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvYqGj9l9G18IADMOh:-MyvYqGj9l9G18IADMOi:b-rmcbn1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useShowRoutesOnModal.ts#L18)):*
> ```XML
>       type: 'setState',
>       payload: {
>         initiallyDisplayedRouteIds: routeIds,
> ```

Not sure if I understand meaning of this yet. If showing certains routes on modal also sets initiallyDisplayedRouteIds then what is the difference with displayedRouteIds?

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/121)* status: 0 of 19 files reviewed, 4 unresolved discussions (waiting on @tk-vincit)

___
*[src/components/LineTableRow.tsx, line 31 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvPAzY3EYNIWDNK1Ui:-MyvetrI5uDc9ony8wVf:b-rjmlxe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/LineTableRow.tsx#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I think parseISODateString function calls are no longer needed after this is merged: https://github.com/HSLdevcom/jore4-ui/pull/118
Same also for other places with same function call.
</blockquote></details>

Yep, I was aware that changes like that were coming, but they were not ready when I first implemented this. I will rebase this on those changes when they are merged or even before.
___
*[src/components/map/Map.tsx, line 53 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvXJhY30s4qcA3jyzC:-MyvfGzT7u3P9jJSSnqw:b74sutc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/map/Map.tsx#L53)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`> 0` not needed. Also could be shorter: `!!initiallyDisplayedRouteIds?.length`
</blockquote></details>

Sure. I just like to think length as a number, but I can change this if it looks cooler and 2 characters less :)
___
*[src/components/map/ModalMap.tsx, line 145 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvQBxe-SpaIWdpusQR:-MyvfXM4-wx_ItIID-8q:b-7j20ka) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/map/ModalMap.tsx#L145)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is this really something that requires toast message? Seems like we are just setting local state of the app here, right? When can it fail?
</blockquote></details>

I talked about this with design earlier. We change the value of a visible UI filter component, and to avoid confusion I (and the designer) think it is something the user needs to be informed about. It cannot fail thought. Do you think we should create a more neutral toast component (grey or blue or something)?
___
*[src/hooks/useEditRouteGeometry.ts, line 200 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvRuZi8lnAE6PAA8Y8:-Myvg8sL-NXdRwTh_aLq:b-s25zxf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useEditRouteGeometry.ts#L200)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

protip: `const isInViewMode = !!drawingMode`. Or can drawingMode be `null` or `""` or `0`? And if `drawingMode === null` should viewMode then be `false`? I think not, but now it is.
</blockquote></details>

Mode is enum and it could have value Draw which is 0. I'm not sure though if it counts as falsy value though..
___
*[src/hooks/useEditRouteGeometry.ts, line 209 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvSOab3Ny3EL8AuIjp:-MyvgNPQ-A8F-UBNnlVZ:b-4jync0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useEditRouteGeometry.ts#L209)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

These don't belong under `// edit` section. Maybe create new "// selectors" section or implement these as selectors to some other place already :)
</blockquote></details>

Sure, I can do it here already. The reason I just tossed them here with TODO comment is that I was expecting us to get some state management library pretty soon and it would automatically resolve this without having to think what to do with these temporarily.
___
*[src/hooks/useShowRoutesOnModal.ts, line 18 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvYqGj9l9G18IADMOh:-MyvgfCeCr_C-Se50CZ3:bpk4t6y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useShowRoutesOnModal.ts#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if I understand meaning of this yet. If showing certains routes on modal also sets initiallyDisplayedRouteIds then what is the difference with displayedRouteIds?
</blockquote></details>

We talked about this at the office last week. There very probably is a better way to do this, but here is the explanation what is the difference of those right now:

The ids we initially set are the ones we have chosen to view. E.g. a single route or all line's routes. The displayedRouteIds is the ids of all the route versions that need to be shown when taking into account observation date. When we change observation date, there could be a moment where any of the initiallyDisplayedRouteIds does not exist (out of validity period), so displayedRouteIds is empty. When we go back to the moment where the routes exist, we want to know what routes to show and for that we use initiallyDisplayedRouteIds.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/121)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[src/components/map/ModalMap.tsx, line 145 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvQBxe-SpaIWdpusQR:-MzE_eBB2e--x_m4Udv0:b-hf48vf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/map/ModalMap.tsx#L145)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I talked about this with design earlier. We change the value of a visible UI filter component, and to avoid confusion I (and the designer) think it is something the user needs to be informed about. It cannot fail thought. Do you think we should create a more neutral toast component (grey or blue or something)?
</blockquote></details>

:shrug: , if this was was agreed with design team then OK 
___
*[src/hooks/useEditRouteGeometry.ts, line 200 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvRuZi8lnAE6PAA8Y8:-MzEaSjj1lnsFSUgwU1Y:b-qsjfft) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useEditRouteGeometry.ts#L200)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Mode is enum and it could have value Draw which is 0. I'm not sure though if it counts as falsy value though..
</blockquote></details>

Maybe I would avoid having 0 as enum value so that this could be shortened (as 0 is falsy value). Now we would have bug if drawindMode would be `null`. But do as you want.
___
*[src/hooks/useShowRoutesOnModal.ts, line 18 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvYqGj9l9G18IADMOh:-MzEbOFy6QZQe2nnJ97_:b-h488lv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/hooks/useShowRoutesOnModal.ts#L18)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

We talked about this at the office last week. There very probably is a better way to do this, but here is the explanation what is the difference of those right now:

The ids we initially set are the ones we have chosen to view. E.g. a single route or all line's routes. The displayedRouteIds is the ids of all the route versions that need to be shown when taking into account observation date. When we change observation date, there could be a moment where any of the initiallyDisplayedRouteIds does not exist (out of validity period), so displayedRouteIds is empty. When we go back to the moment where the routes exist, we want to know what routes to show and for that we use initiallyDisplayedRouteIds.
</blockquote></details>

Should this then be something like "selectedRouteIds"? No idea, you're the best expert at this.

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/121)* status: 0 of 31 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[src/components/map/Map.tsx, line 53 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvXJhY30s4qcA3jyzC:-MzErip9-a0gqLG5jlo7:b-pdsxy3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/map/Map.tsx#L53)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Sure. I just like to think length as a number, but I can change this if it looks cooler and 2 characters less :)
</blockquote></details>

My suggestion would have fit in one line, this takes three. But whatever.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/121)* status: 0 of 31 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[src/components/map/Map.tsx, line 53 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/121#-MyvXJhY30s4qcA3jyzC:-MzEu03gAa785O4XuJoE:b3c9jzf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5492e23be0499bcec1b5d3691dedd4337701323c/src/components/map/Map.tsx#L53)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

My suggestion would have fit in one line, this takes three. But whatever.
</blockquote></details>

Oh I didn't realize you meant the entire thing. Sure I will fix it as well. My bad. I didn't really pay attention to this as it was just variable renaming diff.

**Pull request merged**
