### PR TITLE
Also update Stop Place when updating Stop Point

### PR DESCRIPTION
**Pull request by Huulivoide**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919)

### CODE REVIEW

**Comment by niknii-vincit** [comment]
*[`ui/src/components/forms/common/PriorityForm.tsx` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919#-O8B7rPV39D52krDxZl5:-O8B7rPW9q6POyqNdS8y:b26xvyf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8a6169d6525c34b6e4e7ab48f397f7432e66fd5b/ui/src/components/forms/common/PriorityForm.tsx#L67)):*
> ```XML
>     setValue('priority', value, {
>       shouldValidate: true,
>       shouldDirty: true,
> ```

I don't exactly understand these `shouldDirty` and `shouldTouch` params, could you explain a bit?

**Comment by niknii-vincit** [comment]
*[`ui/src/hooks/stops/useEditStop.ts` line 442 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919#-O8B8sg_CAdNBfduJ2at:-O8B8sg_CAdNBfduJ2au:bcjygnp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8a6169d6525c34b6e4e7ab48f397f7432e66fd5b/ui/src/hooks/stops/useEditStop.ts#L442)):*
> ```XML
>     };
> 
>     // Perform async tasks in parallel to speed things up.
> ```

Nice! :fire:

**Comment by niknii-vincit** [comment]
*[`ui/src/locales/en-US/common.json` line 114 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919#-O8B956x7hUoHSDAvQim:-O8B956x7hUoHSDAvQin:b-c30bl1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8a6169d6525c34b6e4e7ab48f397f7432e66fd5b/ui/src/locales/en-US/common.json#L114)):*
> ```JSON
>     "addToRoute": "Add to route",
>     "stopBreaksRoutes": "The stop to be added is not compatible with the following routes: ({{ routeLabels }})",
>     "timingPlaceRequired": "Pysäkkiä käytetään Hastus-paikkana seuraavilla reiteillä: {{ routeLabels }}. Aseta Hastus-paikka tai poista Hastus-paikka käytöstä reiteiltä.",
> ```

Did a copy&paste oopsie happen here? :smile:

**Comment by niknii-vincit** [comment]
*[`ui/src/locales/fi-FI/common.json` line 115 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919#-O8B9W5j3KLOnhaq18hc:-O8B9W5j3KLOnhaq18hd:bzjeyy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8a6169d6525c34b6e4e7ab48f397f7432e66fd5b/ui/src/locales/fi-FI/common.json#L115)):*
> ```JSON
>     "stopBreaksRoutes": "Lisättävä pysäkki ei ole yhteensopiva seuraavien reittien kanssa: ({{ routeLabels }})",
>     "timingPlaceRequired": "Pysäkkiä käytetään Hastus-paikkana seuraavilla reiteillä: {{ routeLabels }}. Aseta Hastus-paikka tai poista Hastus-paikka käytöstä reiteiltä.",
>     "tiamatUpdateFailed": "Pysäkien tiedot on päivitty linjastoon, mutta niiden vienti pysäkkirekisteriin epäonnistui! Tallennusta on syytä yrittää uudelleen!: Syy: {{ errorMessage }}"
> ```

Pysäkkien* ? 



_Code quote:_
```JSON
Pysäkien
```

**Review by niknii-vincit — COMMENTED** [review]
Left some comments about small things, please check them out 😄  I'm not that well versed in the Testing side of things, so I'm not sure if Teemu or Jarkko should check those just in case.. :sweat_smile: 

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919#-:-O8B9oAVEL7xwHSEldwt:b8bopjg)* status: all files reviewed, 3 unresolved discussions (waiting on @Huulivoide)

**Comment by niknii-vincit** [comment]
*[`ui/src/locales/fi-FI/common.json` line 115 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919#-O8B9W5j3KLOnhaq18hc:-O8GNO01BHCneA9dPhNH:b-wdj8zi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8a6169d6525c34b6e4e7ab48f397f7432e66fd5b/ui/src/locales/fi-FI/common.json#L115)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Pysäkkien* ?
</blockquote></details>

Nice, thanks!

**Comment by niknii-vincit** [comment]
*[`ui/src/locales/en-US/common.json` line 114 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919#-O8B956x7hUoHSDAvQim:-O8GNYfW3LmKVYjYpdfd:blcog2y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8a6169d6525c34b6e4e7ab48f397f7432e66fd5b/ui/src/locales/en-US/common.json#L114)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Did a copy&paste oopsie happen here? :smile:
</blockquote></details>

Nice, gj :saluting_face:

**Review by culka — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/919)* status: all files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

**Pull request merged**
