### PR TITLE
Search by priority

### PR DESCRIPTION
**Pull request by Huulivoide**
### StopSearch|E2E: Add test for priority filter

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955)

### CODE REVIEW

**Review by suvikankare — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

___
*[`ui/src/locales/en-US/common.json` line 421 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955#-OD5pDFm1wolLZIhcRXF:-OD5pDFnCptw8GusSHSa:b-da4km3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/650a70fd33bcd74247dcc979d47fa3bc9b10b61b/ui/src/locales/en-US/common.json#L421)):*
> ```JSON
>       "elyNumber": "ELY number",
>       "municipalities": "Municipality",
>       "priorities": "Priorities"
> ```

Suomeks yksikkö, englanniks monikko?

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @suvikankare)

___
*[`ui/src/locales/en-US/common.json` line 421 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955#-OD5pDFm1wolLZIhcRXF:-ODBa4UnDUNLC5C-FUwY:byqn41x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/650a70fd33bcd74247dcc979d47fa3bc9b10b61b/ui/src/locales/en-US/common.json#L421)):*
<details><summary><i>Previously, suvikankare wrote…</i></summary><blockquote>

Suomeks yksikkö, englanniks monikko?
</blockquote></details>

No nyt on enkkukin yksikössä

**Review by suvikankare — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955)* status: all files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

**Review by suvikankare — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Huulivoide)

**Pull request merged**
