### PR TITLE
Add tweaks to button styles

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/198)

### CODE REVIEW

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/198)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[`src/uiComponents/LocatorButton.tsx` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/198#-N2uKNOdEI5rh7jHhKL2:-N2uKNOdEI5rh7jHhKL3:bxbsucg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e4ab8f794663935a87653ee290157a4b5a36154c/src/uiComponents/LocatorButton.tsx#L10)):*
> ```XML
> }
> 
> const hoverStyle = 'hover:border-2 hover:border-tweaked-brand';
> ```

this hoverStyle belongs to the LocatorButton, so I think it should be moved to within the component definition

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/198)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx` line 63 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/198#-N3JAeyn2F4F3fl_F48T:-N3JAeyn2F4F3fl_F48U:bbt6amo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9b8412bc5b6a801f127252e12d12e33ab2742999/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx#L63)):*
> ```XML
>         </Row>
>       </td>
>       <td className="items-middle flex w-20 justify-center border-l-4 border-r-4 border-white">
> ```

this is a `<td>` element which is by default having `display: table-cell` in CSS. Don't overwrite it with `display: flex` as it might break functionality in browsers.

For `<td>`, it might work if you just used: `text-align: center; vertical-align: middle`. If you do need flex for some other reasons, then you could add a `<div>` wrapper for aligning the button to the middle
___
*[`src/uiComponents/LocatorButton.tsx` line 12 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/198#-N3JC7F40HxkQDp817e_:-N3JC7F40HxkQDp817ea:b-eqs9kq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9b8412bc5b6a801f127252e12d12e33ab2742999/src/uiComponents/LocatorButton.tsx#L12)):*
> ```XML
> const hoverStyle = 'hover:border-2 hover:border-tweaked-brand';
> 
> export const LocatorButton = ({ testId, onClick, className }: Props) => {
> ```

should set the default value for className: `{testId, onClick, className = ''}`, otherwise it'll print "undefined" as a CSS class
___
*[`src/uiComponents/LocatorButton.tsx` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/198#-N3JC_r0BnV-vgBJk6ZV:-N3JC_r0BnV-vgBJk6ZW:b-xeaqcy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9b8412bc5b6a801f127252e12d12e33ab2742999/src/uiComponents/LocatorButton.tsx#L17)):*
> ```XML
>       className={`h-10 w-10 rounded-full border border-grey bg-white text-tweaked-brand ${hoverStyle} ${className}`}
>       onClick={onClick}
>       icon={<MdPinDrop className="text-2xl" />}
> ```

You should choose where you do the sizing: first you set the container size to `h-10 w-10`, then you set the inner icon size to `text-2xl`. Decide which one you'd like to actually go with. If you want to have some outline around the icon for the button, rather do it with paddings or margins

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/198)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx` line 63 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/198#-N3JAeyn2F4F3fl_F48T:-N3JTGqu8e23aa9PzHL5:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9b8412bc5b6a801f127252e12d12e33ab2742999/src/components/routes-and-lines/line-details/RouteStopsHeaderRow.tsx#L63)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is a `<td>` element which is by default having `display: table-cell` in CSS. Don't overwrite it with `display: flex` as it might break functionality in browsers.

For `<td>`, it might work if you just used: `text-align: center; vertical-align: middle`. If you do need flex for some other reasons, then you could add a `<div>` wrapper for aligning the button to the middle
</blockquote></details>

Done.
___
*[`src/uiComponents/LocatorButton.tsx` line 12 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/198#-N3JC7F40HxkQDp817e_:-N3JTNyt84BPRfzjVT3D:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9b8412bc5b6a801f127252e12d12e33ab2742999/src/uiComponents/LocatorButton.tsx#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should set the default value for className: `{testId, onClick, className = ''}`, otherwise it'll print "undefined" as a CSS class
</blockquote></details>

Done.
___
*[`src/uiComponents/LocatorButton.tsx` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/198#-N3JC_r0BnV-vgBJk6ZV:-N3JTah7DXKATuaK61Kf:b-py0agg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9b8412bc5b6a801f127252e12d12e33ab2742999/src/uiComponents/LocatorButton.tsx#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

You should choose where you do the sizing: first you set the container size to `h-10 w-10`, then you set the inner icon size to `text-2xl`. Decide which one you'd like to actually go with. If you want to have some outline around the icon for the button, rather do it with paddings or margins
</blockquote></details>

`h-10 w-10` is there for two reasons. Aspect ration and pixel-perfect size. When checked with design, `EditButton`'s size was a few pixels off. With hard coded width and height we get it exactly right. Also the font size is there for the icon's size.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/198)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
