### PR TITLE
Display duplicate journeys in timetables combine

### PR DESCRIPTION
**Pull request by Leitsi**
Resolves https://github.com/HSLdevcom/jore4/issues/1566

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746)* status: all files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx` line 42 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXa-yMAgfy21zlR4Yr:-NlXa-yMAgfy21zlR4Ys:bxtgf54) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx#L42)):*
> ```XML
> 
>   useEffect(() => {
>     if (timetableImportStrategy === 'combine' && priority) {
> ```

Is there an enum for 'combine' and 'replace' you could use?
___
*[`ui/src/components/timetables/import/SummarySection.tsx` line 3 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXassMDpYK7EMsP8MK:-NlXassMDpYK7EMsP8ML:b-qyxz64) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/SummarySection.tsx#L3)):*
> ```XML
> import { useEffect, useState } from 'react';
> import { useTranslation } from 'react-i18next';
> import { VehicleJourneyDuplicate } from '../../../hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys';
> ```

If you don't want to show the precise import path, you can add the files to corrresponding `index.ts` files (if they are not there already) and just import from `../../../hooks`. Same goes for the already existing import below 
___
*[`ui/src/components/timetables/import/duplicate-journeys/duplicate-journeys-section.tsx` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXbRh81140vUQ6R-p3:-NlXbRh81140vUQ6R-p4:buo9nmt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/duplicate-journeys/duplicate-journeys-section.tsx#L2)):*
> ```XML
> import { useTranslation } from 'react-i18next';
> import { VehicleJourneyDuplicate } from '../../../../hooks/timetables-import/deviations/duplicate-journeys';
> ```

Same here
___
*[`ui/src/components/timetables/import/duplicate-journeys/duplicate-journeys-section.tsx` line 32 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXbp5-0QY3lOHhZt-q:-NlXbp5-0QY3lOHhZt-r:b-bvo594) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/duplicate-journeys/duplicate-journeys-section.tsx#L32)):*
> ```XML
>               {t('timetablesPreview.duplicateJourneys.label')}
>             </th>
>             <th className="">
> ```

empty classNames
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts` line 53 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXib0a3NkWYVDk0WBU:-NlXib0a3NkWYVDk0WBV:b-hk5ek7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts#L53)):*
> ```XML
>           ),
>         )
>         .flat()
> ```

You could use flatMap in both of the maps instead of using .flat() twice in the end, but to be honest, not sure if that is any better or worse :D 
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts` line 58 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXm3Nc43y1o5dGiMa1:-NlXm3Nc43y1o5dGiMa2:bw0zedv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts#L58)):*
> ```XML
>       const journeyInfos = compact(journeys)
>         .filter(
>           (item) => item.uniqueLabel !== undefined && item.lineId !== undefined,
> ```

So we do not want to filter out `null` values, as this is explicitly undefined?

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746)* status: 0 of 25 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx` line 42 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXa-yMAgfy21zlR4Yr:-NlYSfzt-jJpf4XieCOm:b-o4oj1e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx#L42)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Is there an enum for 'combine' and 'replace' you could use?
</blockquote></details>

Not quite, but close enough: the `timetableImportStrategy` here is a string union derived from zod enum.
https://github.com/HSLdevcom/jore4-ui/blob/065ba1f5e427cf4ac932e9f357f2503bdb5dd452/ui/src/components/timetables/import/TimetableImportStrategyForm.tsx#L15C1-L16C79
___
*[`ui/src/components/timetables/import/SummarySection.tsx` line 3 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXassMDpYK7EMsP8MK:-NlYTrWzEMgvUCgwFYkK:bprj9p7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/SummarySection.tsx#L3)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

If you don't want to show the precise import path, you can add the files to corrresponding `index.ts` files (if they are not there already) and just import from `../../../hooks`. Same goes for the already existing import below
</blockquote></details>

Thought of that, but it seemed that other nested folders didn't seem to do that, so chose not to.

Though, on a second look, some folders do follow that practice. I'll change these.
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts` line 53 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXib0a3NkWYVDk0WBU:-NlYWbyZ30H66yFtvXQK:b-9qk1bt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts#L53)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You could use flatMap in both of the maps instead of using .flat() twice in the end, but to be honest, not sure if that is any better or worse :D
</blockquote></details>

Changed these, seems fine.
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts` line 58 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXm3Nc43y1o5dGiMa1:-NlYWDAf8Xxy0bY7S65D:b-c1jmnc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts#L58)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

So we do not want to filter out `null` values, as this is explicitly undefined?
</blockquote></details>

This was actually copypasted from another similar hook. Don't think it matters here, removing.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 5 of 20 files at r4, 1 of 2 files at r5, 23 of 23 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746)* status: all files reviewed, 8 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 8 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4qjS5-nkqxYd8xSqT):*
Do we have a ticket to link this? #1566 perhaps
___
*[`ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx` line 42 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXa-yMAgfy21zlR4Yr:-NlwJjma1av9syqnVZoh:by1k68p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx#L42)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not quite, but close enough: the `timetableImportStrategy` here is a string union derived from zod enum.
https://github.com/HSLdevcom/jore4-ui/blob/065ba1f5e427cf4ac932e9f357f2503bdb5dd452/ui/src/components/timetables/import/TimetableImportStrategyForm.tsx#L15C1-L16C79
</blockquote></details>

Okay yeah. I was thinking if we could have an enum value instead of the hard coded string here. So "timetableImportStrategy === timetableImportStrategyFooBarEnum.Replace". Would it be worth adding something like that? 
Then we could also create the `const TimetableImportStrategy = z.enum(['combine', 'replace']);` using the created enum, instead of these hard coded strings. (Also disclaimer: I'm not that familiar with zod)
___
*[`ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx` line 32 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4vRVN-EKMhhqT8up2:-Nm4vRVN-EKMhhqT8up3:bn4kegu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx#L32)):*
> ```XML
>             <th>{t('timetablesPreview.duplicateJourneys.departureTime')}</th>
>             <th>{t('timetablesPreview.duplicateJourneys.dayType')}</th>
>             <th className="!pr-0">
> ```

Visually this doesn't seem to have any effect. 
___
*[`ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx` line 39 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nlx5xu1-YyIb2BRxXCQ:-Nlx5xu1-YyIb2BRxXCR:b45h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx#L39)):*
> ```XML
>               {t('timetablesPreview.duplicateJourneys.validityEnds')}
>             </th>
>             <th className="w-[100%]">{/* Filler */}</th>
> ```





_Suggestion:_
```XML
            <th className="w-full">{/* Filler */}</th>
```
___
*[`ui/src/components/timetables/import/duplicate-journeys/VehicleJourneyRow.tsx` line 11 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4xnsw3dLf58CH82fh:-Nm4xnsw3dLf58CH82fi:bx9uveh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/components/timetables/import/duplicate-journeys/VehicleJourneyRow.tsx#L11)):*
> ```XML
> export const VehicleJourneyRow = ({ vehicleJourneyInfo }: Props) => {
>   return (
>     <tr className="border odd:bg-white even:bg-hsl-neutral-blue [&>td]:border-light-grey [&>td]:px-8 [&>td]:py-2">
> ```

This could visually benefit from `text-center`.
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts` line 58 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXm3Nc43y1o5dGiMa1:-Nm4yYIpB2uJ_w3gcz91:b-w1pi47) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts#L58)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This was actually copypasted from another similar hook. Don't think it matters here, removing.
</blockquote></details>

check :+1: 
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts` line 16 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm51sqo7S22KnOleakb:-Nm51sqo7S22KnOleakc:bwkuzac) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts#L16)):*
> ```XML
>   dayTypeName: LocalizedString;
>   uniqueLabel: string;
>   lineId: string;
> ```

These IDs (lineId, routeId) could also be type UUID
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useDuplicateJourneyDeviations.spec.ts` line 111 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm51J8z4_aFUpxkCy2F:-Nm51J8z4_aFUpxkCy2G:b-uh0laj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useDuplicateJourneyDeviations.spec.ts#L111)):*
> ```XML
> );
> 
> describe('useDuplicateJourneyDeviations hook', () => {
> ```

Very nice to have these tests here! :muscle: 
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts` line 13 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm52sf55UiJ5bskSU7J:-Nm52sf55UiJ5bskSU7K:b3qos7j) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts#L13)):*
> ```XML
>     journeyA: VehicleJourneyInfo,
>     journeyB: VehicleJourneyInfo,
>   ) => {
> ```

NIT, You could drop the curly brackets and the return clause, but this is also completely fine.



_Suggestion:_
```XML
  ) =>
    // In addition, validity start and day type should be identical,
    // but we assume here that this method is only called for inputs where they are:
    // backend checks this when fetching the target frame.
    journeyA.routeId === journeyB.routeId && // Check that route and direction are same.
    journeyA.startTime.equals(journeyB.startTime);
    
```
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts` line 18 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm52L_e6HbUlcbNAXQK:-Nm52L_e6HbUlcbNAXQL:b-h57ndx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts#L18)):*
> ```XML
>       // but we assume here that this method is only called for inputs where they are:
>       // backend checks this when fetching the target frame.
>       journeyA.routeId === journeyB.routeId && // Check that route and direction are same.
> ```

The comment mentions about direction check. Is it missing, or do we not need it and the comment is off, or?
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts` line 37 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm53Y_z1DoEzmnRCtuf:-Nm53Y_z1DoEzmnRCtug:bwuhey8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts#L37)):*
> ```XML
>           });
>         })
>         .flat();
> ```

flatMap if wanted

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746)* status: 22 of 25 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 8 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4qjS5-nkqxYd8xSqT):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Do we have a ticket to link this? #1566 perhaps
</blockquote></details>

Is linked in the PR.
___
*[`ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx` line 42 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXa-yMAgfy21zlR4Yr:-Nm5M7az67t5e1qty8hK:bess4ty) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx#L42)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Okay yeah. I was thinking if we could have an enum value instead of the hard coded string here. So "timetableImportStrategy === timetableImportStrategyFooBarEnum.Replace". Would it be worth adding something like that? 
Then we could also create the `const TimetableImportStrategy = z.enum(['combine', 'replace']);` using the created enum, instead of these hard coded strings. (Also disclaimer: I'm not that familiar with zod)
</blockquote></details>

I think there was a reason I did it that way. Zod was a bit restrictive on defining the enum and/or infering the type. Could be resolved at least by not infering the enum from zod enum, but that would remove the "single source of truth" for possible values that we have her enow.

Don't think it's worth it to investigate this further. Current version is already type safe.
___
*[`ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx` line 32 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4vRVN-EKMhhqT8up2:-Nm5aV3W0JA5hhycMsq-:beef0oa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/components/timetables/import/duplicate-journeys/DuplicateJourneysSection.tsx#L32)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Visually this doesn't seem to have any effect.
</blockquote></details>

Hmm, true, it's only the matching `td` for which this matters. Removed.
___
*[`ui/src/components/timetables/import/duplicate-journeys/VehicleJourneyRow.tsx` line 11 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4xnsw3dLf58CH82fh:-Nm5bLJ44bMrzbG57VB4:b5ah4h2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/components/timetables/import/duplicate-journeys/VehicleJourneyRow.tsx#L11)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This could visually benefit from `text-center`.
</blockquote></details>

Is designed like this, with `text-left`. Also matches the other table in this view. Won't change.
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts` line 16 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm51sqo7S22KnOleakb:-Nm5bbEt8uqeIiOj0O9Z:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useCreateVehicleJourneyInfo.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

These IDs (lineId, routeId) could also be type UUID
</blockquote></details>

:thumbsup: 
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts` line 13 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm52sf55UiJ5bskSU7J:-Nm5cItA7PGDphyOgmL6:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts#L13)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, You could drop the curly brackets and the return clause, but this is also completely fine.
</blockquote></details>

:thumbsup: 
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts` line 18 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm52L_e6HbUlcbNAXQK:-Nm5LE0d7c8XaJnpY4jW:b118kha) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts#L18)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The comment mentions about direction check. Is it missing, or do we not need it and the comment is off, or?
</blockquote></details>

If the direction is different, then it will be a different row in route table = routeId is also different. So no need to check it separately.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`-- commits` line 8 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4qjS5-nkqxYd8xSqT):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Is linked in the PR.
</blockquote></details>

We have usually linked them in the commit body as well, so that the link is not lost with the pull request.
___
*[`ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx` line 42 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-NlXa-yMAgfy21zlR4Yr:-Nm6ecoH5K1e9qMkFMfh:b-4gpafr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5beedc92f4140f3a14eae6754e9975203858361b/ui/src/components/timetables/import/ConfirmPreviewedTimetablesImportForm.tsx#L42)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think there was a reason I did it that way. Zod was a bit restrictive on defining the enum and/or infering the type. Could be resolved at least by not infering the enum from zod enum, but that would remove the "single source of truth" for possible values that we have her enow.

Don't think it's worth it to investigate this further. Current version is already type safe.
</blockquote></details>

Check :+1: 
___
*[`ui/src/components/timetables/import/duplicate-journeys/VehicleJourneyRow.tsx` line 11 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm4xnsw3dLf58CH82fh:-Nm6fMHn0Tm9Hbk-GMJG:b-jce91c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/components/timetables/import/duplicate-journeys/VehicleJourneyRow.tsx#L11)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Is designed like this, with `text-left`. Also matches the other table in this view. Won't change.
</blockquote></details>

:selva: :D
___
*[`ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts` line 18 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/746#-Nm52L_e6HbUlcbNAXQK:-Nm6eo0VBuci2DWCpD1I:b-pt68r5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/535eacc9c200f75e6a10045d1d94cac3523f8f7a/ui/src/hooks/timetables-import/deviations/duplicate-journeys/useFindDuplicateJourneys.ts#L18)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

If the direction is different, then it will be a different row in route table = routeId is also different. So no need to check it separately.
</blockquote></details>

check :+1: also good addition

**Pull request merged**
