### PR TITLE
Implement stops modal in map view

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 153 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE7-Hw3w1HCdiA6CXa:-MxE7-HxCxZqPxiEpmhJ:b-soiep0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/DrawRouteLayer.tsx#L153)):*
> ```XML
>       dispatch({ type: 'setState', payload: { hasRoute: true } });
> 
>       const editingRouteId = editedRouteData.id;
> ```

unnecessary variable...?
___
*[src/components/map/StopsModal.tsx, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE8KtZ-3DYpV6et0Le:-MxE8KtZ-3DYpV6et0Lf:b-31iyi8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L14)):*
> ```XML
> interface Props {
>   className?: string;
>   route?: Partial<RouteRoute>;
> ```

if this component cannot work with undefined route or stopIds parameters, let's not allow them to be undefined and let the caller handle the errors instead of handling them internally in a funny way:
`{route && stopIds && <StopsModal route={route} stopIds={stopIds}/>`
___
*[src/components/map/StopsModal.tsx, line 46 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE7O7o233Kap4rMFm8:-MxE7O7o233Kap4rMFm9:b-1oonjk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L46)):*
> ```XML
>       </div>
>       <div className="text-tweaked-brand">
>         <DropdownMenu>
> ```

Let's reuse that EditJourneyPatternMenu that I mentioned in the previous PR
___
*[src/components/map/StopsModal.tsx, line 59 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE9kjG3TY5EoqU2IGR:-MxE9kjG3TY5EoqU2IGS:b-hojrwi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L59)):*
> ```XML
>   );
> };
> ```

maybe let's start calling these components are they are: overlays. This is not really a modal, it does not require immediate user attention.
How about e.g. `RouteStopsOverlay` or something similar?
___
*[src/components/map/StopsModal.tsx, line 67 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxECABJ2s1Yd0J5Tdlb:-MxECABJ2s1Yd0J5Tdlc:bp6r507) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L67)):*
> ```XML
>   const stopsResult = useGetStopsQuery({});
>   const stops = mapGetStopsResult(stopsResult);
> ```

This component is not behaving correctly. Currently it shows all the stops that are part of the edited route's journey pattern. Instead, it should list all the stops that are besides the edited route's geometry, allowing you to include or exclude some of them to the edited route's journey pattern. This should use its own query.
___
*[src/components/map/StopsModal.tsx, line 86 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxEAsKk6LP8P9Xuxads:-MxEAsKk6LP8P9Xuxadt:b-etm3na) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L86)):*
> ```XML
>           </div>
>         </div>
>         <div className="">
> ```

className is empty...?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/StopsModal.tsx, line 90 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxEDs5cCqpUOH0Of35R:-MxEDs5cCqpUOH0Of35S:bsn4uoa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L90)):*
> ```XML
>             const stop = stops?.find(
>               (item) => item.scheduled_stop_point_id === stopId,
>             );
> ```

please don't do business logic in the rendering code block
___
*[src/graphql/infrastructureNetwork.ts, line 79 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxEDTah6CMSgcv7LJvB:-MxEDTah6CMSgcv7LJvC:b-kx1vhy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/graphql/infrastructureNetwork.ts#L79)):*
> ```XML
>               stop.direction === InfrastructureNetworkDirectionEnum.Backward);
> 
>           const removedFromRoute =
> ```

this part of the business logic does not belong to the API. You should do this separately

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 153 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE7-Hw3w1HCdiA6CXa:-MxYKDrXBweLZ4vBzq_R:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/DrawRouteLayer.tsx#L153)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

unnecessary variable...?
</blockquote></details>

Done.
___
*[src/graphql/infrastructureNetwork.ts, line 79 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxEDTah6CMSgcv7LJvB:-MxYNsWe5Dzyk-iBCa0S:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/graphql/infrastructureNetwork.ts#L79)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this part of the business logic does not belong to the API. You should do this separately
</blockquote></details>

Done.
___
*[src/components/map/StopsModal.tsx, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE8KtZ-3DYpV6et0Le:-MxYKl8t0lQKeJATdoTg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if this component cannot work with undefined route or stopIds parameters, let's not allow them to be undefined and let the caller handle the errors instead of handling them internally in a funny way:
`{route && stopIds && <StopsModal route={route} stopIds={stopIds}/>`
</blockquote></details>

Done.
___
*[src/components/map/StopsModal.tsx, line 46 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE7O7o233Kap4rMFm8:-MxYKnOM43kXbHUYbUdJ:b2m952c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L46)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Let's reuse that EditJourneyPatternMenu that I mentioned in the previous PR
</blockquote></details>

Different functionality, I did not implement EditJourneyPatternManu.
___
*[src/components/map/StopsModal.tsx, line 59 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxE9kjG3TY5EoqU2IGR:-MxYLHG95GmWOCuRTYOp:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L59)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe let's start calling these components are they are: overlays. This is not really a modal, it does not require immediate user attention.
How about e.g. `RouteStopsOverlay` or something similar?
</blockquote></details>

Done.
___
*[src/components/map/StopsModal.tsx, line 67 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxECABJ2s1Yd0J5Tdlb:-MxYKzVa1Tb8v4eYVW9F:b-g805p0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L67)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This component is not behaving correctly. Currently it shows all the stops that are part of the edited route's journey pattern. Instead, it should list all the stops that are besides the edited route's geometry, allowing you to include or exclude some of them to the edited route's journey pattern. This should use its own query.
</blockquote></details>

It will be implemented in the next pr.
___
*[src/components/map/StopsModal.tsx, line 86 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxEAsKk6LP8P9Xuxads:-MxYLM6i83ooZfPfoNqX:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L86)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

className is empty...?
</blockquote></details>

Done.
___
*[src/components/map/StopsModal.tsx, line 90 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxEDs5cCqpUOH0Of35R:-MxYMazHBvaBzwOwh6pO:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/89aa6d04112c6279df8a1690df480103fa89bc60/src/components/map/StopsModal.tsx#L90)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please don't do business logic in the rendering code block
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 38 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxZA6EH8Zfh4BRw42kb:-MxZA6EH8Zfh4BRw42kc:b-u0snss) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8739c9e51cfbc339022c51c070ca8b31428f334a/src/components/map/DrawRouteLayer.tsx#L38)):*
> ```XML
> } from '../../graphql';
> import { useAsyncQuery } from '../../hooks';
> import { useEditRouteGeometry } from '../../hooks/useEditRouteGeometry';
> ```

-> hooks/index.ts
___
*[src/components/map/Map.tsx, line 70 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxZIKIfCoF8CkeDiRHM:-MxZIKIfCoF8CkeDiRHN:b-9nglu1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8739c9e51cfbc339022c51c070ca8b31428f334a/src/components/map/Map.tsx#L70)):*
> ```XML
>   const routes = mapRoutesDetailsResult(routesResult);
> 
>   const editedRouteMetadata = creatingNewRoute
> ```

should rather fetch/build the metadata within the RouteStopsOverlay
___
*[src/hooks/useEditRouteGeometry.ts, line 176 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxZJt2k04DmJwFQwdEy:-MxZJt2k04DmJwFQwdEz:bywl47) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8739c9e51cfbc339022c51c070ca8b31428f334a/src/hooks/useEditRouteGeometry.ts#L176)):*
> ```XML
>             const removedFromRoute =
>               // This link was part of the route before
>               oldLinks.find(
> ```

const partOfOldRoute = oldLinks.find(...)

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[src/components/map/DrawRouteLayer.tsx, line 187 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdOOeU3IAP46YHzYio:-MxdOOeU3IAP46YHzYip:b-pz4dh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/DrawRouteLayer.tsx#L187)):*
> ```XML
>         return;
>       }
> ```

I don't understand what we are doing in this code block.

Also to nitpick a little:
- `let` definition should be avoided in favor of `const`
- `if (array.length)` is IMO more idiomatic JS than `if (array.length === 0)`

Not 100% sure if I was able to refactor this correctly, but assuming I did, how about this if you change `descriptiveConditionName` to some better name?

```
const descriptiveConditionName = editedRouteData.stopIds?.length && !creatingNewRoute;
      const oldStopIds = descriptiveConditionName ? routes.flatMap((route) => getRouteStopIds(route)) : [];

```
___
*[src/components/map/Map.tsx, line 85 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdQHULD2jDUyXtjC_5:-MxdQHULD2jDUyXtjC_6:b-m71jnh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/Map.tsx#L85)):*
> ```XML
>             <Column className="items-start">
>               <FilterPanel
>                 className="ml-8 mt-8"
> ```

Should `ml-8` className be on Column element instead than here and on RouteStopsOverlay, or am I missing something here?
___
*[src/components/map/RouteStopsOverlay.tsx, line 75 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdRPRvCcY0dp_ww9MW:-MxdRPRvCcY0dp_ww9MX:bibup7x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/RouteStopsOverlay.tsx#L75)):*
> ```XML
> 
>   if (!route) {
>     return <></>;
> ```

return null?
___
*[src/components/map/RouteStopsOverlay.tsx, line 80 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdRZMDAz9lYmDwW_7q:-MxdRZMDAz9lYmDwW_7r:bjo5xyg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/RouteStopsOverlay.tsx#L80)):*
> ```XML
>   return (
>     <div className={`inline-block w-72 ${className}`}>
>       <div className="flex flex-col bg-white  shadow-md">
> ```

Trailing spaces after bg-white :wink:

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/map/DrawRouteLayer.tsx, line 187 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdOOeU3IAP46YHzYio:-MxhTWnuEQqWLHwg-D04:b40zxka) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/DrawRouteLayer.tsx#L187)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand what we are doing in this code block.

Also to nitpick a little:
- `let` definition should be avoided in favor of `const`
- `if (array.length)` is IMO more idiomatic JS than `if (array.length === 0)`

Not 100% sure if I was able to refactor this correctly, but assuming I did, how about this if you change `descriptiveConditionName` to some better name?

```
const descriptiveConditionName = editedRouteData.stopIds?.length && !creatingNewRoute;
      const oldStopIds = descriptiveConditionName ? routes.flatMap((route) => getRouteStopIds(route)) : [];

```
</blockquote></details>

This code block either takes selected stops from mapEditorState or extracts them from the selected route. If this route has been edited before, the mapEditorContext contains the stops that are part of the freshly edited route geometry. Otherwise, the mapEditorContext is empty and the stops have to be extracted from the original route object. Also, depending on whether we are creating a new route, we could want to make the stops array empty.

I suggest we leave this be for this pr, as these rows will be changed in the future PRs anyway. I will look into refactoring this later.
___
*[src/components/map/Map.tsx, line 85 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdQHULD2jDUyXtjC_5:-MxhSr9RAIjUsYCtYBNQ:b-kii98p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/Map.tsx#L85)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should `ml-8` className be on Column element instead than here and on RouteStopsOverlay, or am I missing something here?
</blockquote></details>

I didn't really change this part other than added indentation and didn't really pay attention to this.
___
*[src/components/map/RouteStopsOverlay.tsx, line 75 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdRPRvCcY0dp_ww9MW:-MxhSFy-0CZdvvWZsq3D:b23qp7u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/RouteStopsOverlay.tsx#L75)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

return null?
</blockquote></details>

It would work if the return type wasn't `JSX.Element`. I can remove that return type and return null if it seems better. Done.
___
*[src/components/map/RouteStopsOverlay.tsx, line 80 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdRZMDAz9lYmDwW_7q:-MxhSSAaBX8rmrPs7soN:br4qyif) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/RouteStopsOverlay.tsx#L80)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Trailing spaces after bg-white :wink: 
</blockquote></details>

Oh, I will fix that.

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/106)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/map/DrawRouteLayer.tsx, line 187 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdOOeU3IAP46YHzYio:-MxhnFzVAQ29_El2kKs-:b-b3ancq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/DrawRouteLayer.tsx#L187)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This code block either takes selected stops from mapEditorState or extracts them from the selected route. If this route has been edited before, the mapEditorContext contains the stops that are part of the freshly edited route geometry. Otherwise, the mapEditorContext is empty and the stops have to be extracted from the original route object. Also, depending on whether we are creating a new route, we could want to make the stops array empty.

I suggest we leave this be for this pr, as these rows will be changed in the future PRs anyway. I will look into refactoring this later.
</blockquote></details>

Ok, let's get back at this at later PR's as seems like this was changed million times later. 
___
*[src/components/map/Map.tsx, line 85 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdQHULD2jDUyXtjC_5:-MxhmuGvAeurHgftUxZT:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/Map.tsx#L85)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I didn't really change this part other than added indentation and didn't really pay attention to this.
</blockquote></details>

:+1: 
___
*[src/components/map/RouteStopsOverlay.tsx, line 75 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/106#-MxdRPRvCcY0dp_ww9MW:-MxhkqYj6UgU3dUiVGLe:b-xcjz35) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/519447af80b4118a3e8212d9210995e5a9011d95/src/components/map/RouteStopsOverlay.tsx#L75)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

It would work if the return type wasn't `JSX.Element`. I can remove that return type and return null if it seems better. Done.
</blockquote></details>

Ok, sorry. Returning null is recommended way of saying "I want to render nothing": https://reactjs.org/blog/2014/07/17/react-v0.11.html#rendering-to-null
Anyway, I think returning empty fragment instead of null sounds better than losing typings of component. :see_no_evil: 

Will approve this for now as this is not a big issue, but would keep this in mind in later steps.

**Pull request merged**
