### PR TITLE
Extend label search to include name

### PR DESCRIPTION
**Pull request by Perholehto**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)

### CODE REVIEW

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/utils/gql.ts` line 243 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#gh-1630831981:-O-K-OkGEfV6hhXEPcu8:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/80d99548426e70894358459ee94f9ba9644f7b38/ui/src/utils/gql.ts#L243)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Ja tässä sama
</blockquote></details>

Done.
___
*[`ui/src/utils/gql.ts` line 248 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#gh-1630840424:-O-K-VWK4hJPQuxefWWi:bt1spt1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/80d99548426e70894358459ee94f9ba9644f7b38/ui/src/utils/gql.ts#L248)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tää on kauheen löyhästi tyypitetty. En oo loppuja koodeja lukenut vielä, mutta kuitenkin aina pitäs olla tiedosssa ja generoituna tyypit noille GQL kysely muuttujille / where ehdoille.

```typescript
type LanguageFilterFields<FieldName extends string> = {
  readonly `${field}_value`: StringComparisonExp;
  readonly `${field}_lang`: StringComparisonExp;
};

function <FieldName extends string>)(label: NameType, lang: Lang, field: FieldName): LanguageFilterFields<FieldName> {
 return ...
 }
 ```
</blockquote></details>

Changed also the implementation here. Do you think that typing these with a `...BoolExp` type from generated types is enough?
___
*[`ui/src/utils/gql.ts` line 253 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#gh-1630841345:-O-K-QHM4yNUJKsI6HyA:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/80d99548426e70894358459ee94f9ba9644f7b38/ui/src/utils/gql.ts#L253)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Täälläkin vois olla kiva että ois tyypitettyä koodia, eikä vaan tämmöstä random objektin rakennusta 
</blockquote></details>

Done.

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/utils/gql.ts` line 238 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#gh-1630831824:-O-K14ux5czTIH47yzF9:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/80d99548426e70894358459ee94f9ba9644f7b38/ui/src/utils/gql.ts#L238)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Äkkiseltään huutasin että eiks tän kuuluis melkeempä olla enumi :thinking: 
```typescript
enum Lang {
  FIN = 'fin',
  SWE = 'swe'
}
  ```
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r6, 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)* status: all files reviewed, 14 unresolved discussions (waiting on @Huulivoide and @Perholehto)

___
*[`-- commits` line 8 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-LC0lsBWsavlyl2DmX):*
This could benefit from a bit more elaboration in commit body.
___
*[`cypress/e2e/stop-registry/stopSearch.cy.ts` line 463 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-LAsZe0J615z5p_mVa:-O-LAsZe0J615z5p_mVb:b-gqi9zq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/cypress/e2e/stop-registry/stopSearch.cy.ts#L463)):*
> ```XML
>           .should('be.checked');
>         stopSearchBar.getSearchInput().type(`Lapinrinne{enter}`);
>         cy.wait('@gqlSearchStops');
> ```

I would say that we should check the loading indicator instead of network waits, but this is already used in all of the other tests in this suite so no need to change here. Probably best to change all at once.
___
*[`ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts` line 26 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-Kc1bk2yJVqAMJICtG:-O-Kc1bl9fkF9o4oG-ke:b-uzkpam) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts#L26)):*
> ```XML
> const DEFAULT_MUNICIPALITIES = [
>   ...getEnumValues(StopRegistryMunicipality),
>   'all',
> ```

I think this change is unnecessary, probably some leftover or?
___
*[`ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts` line 44 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-KnSGTAGzx67gb-_wt:-O-KnSGTAGzx67gb-_wu:b-m28uur) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts#L44)):*
> ```XML
>     if (
>       municipalitiesFromURLQuery?.length ===
>       Object.keys(StopRegistryMunicipality).length / 2
> ```

NIT, This could probably benefit from a variable like "totalAmountOfMunicipalities".
Just to make it a bit more readable, I had to check that why are we dividing something in half.



_Suggestion:_
```XML
    const totalAmountOfMunicipalities = Object.keys(StopRegistryMunicipality.length / 2);
    if (
      municipalitiesFromURLQuery?.length ===
      totalAmountOfMunicipalities
    ) {
```
___
*[`ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts` line 46 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L1dGrDFmLKwevtX4A:-O-L1dGs3sMNg99MgSaL:b4c6gev) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts#L46)):*
> ```XML
>       Object.keys(StopRegistryMunicipality).length / 2
>     ) {
>       municipalitiesFromURLQuery.push(AllOptionEnum.All);
> ```

This comment may not target this particular line, but overall the municipalities url query:
I checked how municipality url query is now working in practice, and currently when we have the "all" option ticked, it seems that the urlQuery consists of all the municipalities separately and then on top of that the "all" is also there. So shouldn't the urlQuery be `municipalities=Vantaa,Espoo` when only VAntaa and Espoo is ticked and if all -choice is ticked, then we just have `municipalities=all`

I didn't put this comment as blocking, because it probably should be handled in it's own PR, if this particular commit did not change the initial behaviour.
___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 83 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L3GuP18txysTIl6eW:-O-L3GuP18txysTIl6eX:b-mj9ci8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L83)):*
> ```XML
> ): SearchStopsQueryVariables => {
>   const labelOrName = searchConditions.labelOrName ?? '';
>   const labelOrNameFilterToUse =
> ```

Also this could probably use a comment describing that by design, we only accept search by name when the input is at least 4 characters
___
*[`ui/src/utils/gql.ts` line 246 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-LACf39de5GxP4Hb5t:-O-LACf40Lsmi2dl19b-:blgt9yg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L246)):*
> ```XML
> }
> 
> enum NAME_TYPES {
> ```

NIT, I'd prefer this as singular vs plural 



_Suggestion:_
```XML
enum NAME_TYPE {
```
___
*[`ui/src/utils/gql.ts` line 268 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L5yHh3w9xfQD-U2Qb:-O-L5yHiBAySFzAluIN1:b-wzq89t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L268)):*
> ```XML
>   stop_place_alternative_names: {
>     alternative_name: {
>       name_type: { _ilike: nameType },
> ```

I think the `name_type` and `name_lang` could/should be `_eq` instead of `_ilike`. They are constants and do not use the asterisk
___
*[`ui/src/utils/gql.ts` line 280 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L6IGVAfndoLM99WP6:-O-L6IGVAfndoLM99WP7:bz7coxg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L280)):*
> ```XML
>   _or: [
>     buildTiamatStopQuayPublicCodeLikeGqlFilter(label),
>     buildLanguageFilter(label, LANG.SWE),
> ```

I think this `buildLanguageFilter (label, LANG.SWE)` is extra, because the Swedish name is stored in alternativeNames (translation)
___
*[`ui/src/utils/gql.ts` line 284 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L8XODEgKCkTP--bdw:-O-L8XODEgKCkTP--bdx:bfdcklr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L284)):*
> ```XML
>     buildAlternativeNameFilter(label, NAME_TYPES.TRANSLATION, LANG.SWE),
>     buildAlternativeNameFilter(label, NAME_TYPES.ALIAS, LANG.SWE),
>     buildAlternativeNameFilter(label, NAME_TYPES.ALIAS, LANG.FIN),
> ```

At least the Abbreviation filters seems to be missing. Not sure if the 5 character abbreviations were supposed to be included also. Not sure about 5 character abbreviations or the "location"

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)* status: all files reviewed, 11 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/utils/gql.ts` line 248 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#gh-1630840424:-O-LelyI2c_IaN2VGEIm:b-oz06vr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/80d99548426e70894358459ee94f9ba9644f7b38/ui/src/utils/gql.ts#L248)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Changed also the implementation here. Do you think that typing these with a `...BoolExp` type from generated types is enough?
</blockquote></details>

Seems good

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)* status: 5 of 8 files reviewed, 10 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 8 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-LC0lsBWsavlyl2DmX):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This could benefit from a bit more elaboration in commit body.
</blockquote></details>

Done.
___
*[`ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts` line 26 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-Kc1bk2yJVqAMJICtG:-O-_P7W91A4OSJqiNiDC:b-wg3o4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts#L26)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this change is unnecessary, probably some leftover or?
</blockquote></details>

Maybe from rebasing/stashing...
___
*[`ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts` line 44 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-KnSGTAGzx67gb-_wt:-O-_PDZLDAYYq_jc5Y1X:b-m8aupr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts#L44)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, This could probably benefit from a variable like "totalAmountOfMunicipalities".
Just to make it a bit more readable, I had to check that why are we dividing something in half.
</blockquote></details>

Added variable
___
*[`ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts` line 46 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L1dGrDFmLKwevtX4A:-O-_Q9Qd8IxqzFEs9mKj:b-ovcc9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts#L46)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This comment may not target this particular line, but overall the municipalities url query:
I checked how municipality url query is now working in practice, and currently when we have the "all" option ticked, it seems that the urlQuery consists of all the municipalities separately and then on top of that the "all" is also there. So shouldn't the urlQuery be `municipalities=Vantaa,Espoo` when only VAntaa and Espoo is ticked and if all -choice is ticked, then we just have `municipalities=all`

I didn't put this comment as blocking, because it probably should be handled in it's own PR, if this particular commit did not change the initial behaviour.
</blockquote></details>

I can take a look at this now, but not in this PR. 
___
*[`ui/src/hooks/stop-registry/search/useStopSearchResults.ts` line 83 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L3GuP18txysTIl6eW:-O-_PbMNCAjtrG8dayVS:b-bttoee) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchResults.ts#L83)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Also this could probably use a comment describing that by design, we only accept search by name when the input is at least 4 characters
</blockquote></details>

Added comment
___
*[`ui/src/utils/gql.ts` line 246 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-LACf39de5GxP4Hb5t:-O-LURvE114NuyNP1GHL:b-kq939s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L246)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, I'd prefer this as singular vs plural
</blockquote></details>

for sure!
___
*[`ui/src/utils/gql.ts` line 268 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L5yHh3w9xfQD-U2Qb:-O-LSYgKCucB6sXWiQkG:b-pxirb2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L268)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think the `name_type` and `name_lang` could/should be `_eq` instead of `_ilike`. They are constants and do not use the asterisk
</blockquote></details>

For `name_lang` it works but for `name_type` it doesn't work, nor does `_like` for `name_type`...
___
*[`ui/src/utils/gql.ts` line 280 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L6IGVAfndoLM99WP6:-O-LSE14CsCwsIaXviXu:b4ae2n7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L280)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this `buildLanguageFilter (label, LANG.SWE)` is extra, because the Swedish name is stored in alternativeNames (translation)
</blockquote></details>

Good catch, changed
___
*[`ui/src/utils/gql.ts` line 284 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L8XODEgKCkTP--bdw:-O-LSFmfD5VnzgsnGs2V:bpp0e23) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L284)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

At least the Abbreviation filters seems to be missing. Not sure if the 5 character abbreviations were supposed to be included also. Not sure about 5 character abbreviations or the "location"
</blockquote></details>

Yeah, I misread the user story.. Added short names and 5 character abbreviations.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)* status: all files reviewed, 2 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 8 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-LC0lsBWsavlyl2DmX):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts` line 44 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-KnSGTAGzx67gb-_wt:-O-_W9Sw-yfywIiGpr-n:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/hooks/stop-registry/search/useStopSearchQueryParser.ts#L44)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Added variable
</blockquote></details>

Thanks!
___
*[`ui/src/utils/gql.ts` line 268 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L5yHh3w9xfQD-U2Qb:-O-_WVfr7zkVa86fk5L6:ba3rjpc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L268)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

For `name_lang` it works but for `name_type` it doesn't work, nor does `_like` for `name_type`...
</blockquote></details>

Hmm, then the casing does not match. Fast check from database, the name types are all caps. So if you change the enum values to all caps name_type {
TRANSLATION = 'TRANSLATION'
...
}
then the _eq operator should work.
___
*[`ui/src/utils/gql.ts` line 284 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837#-O-L8XODEgKCkTP--bdw:-O-_Z2Tu8LSR5n1zQ16o:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b918f6817aa46e833609867c6ecf9b8eca25757c/ui/src/utils/gql.ts#L284)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Yeah, I misread the user story.. Added short names and 5 character abbreviations.
</blockquote></details>

:ok_hand:

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/837)* status: all files reviewed, 1 unresolved discussion (waiting on @Perholehto)

**Pull request merged**
