### PR TITLE
Add e2e tests for timetable replacement and combination

### PR DESCRIPTION
**Pull request by sr-vala**
Add test resources and basic tests for timetables' replace/combine functionality

Resolves HSLdevcom/jore4#1484

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 253 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtUckUDVAUyttNVgYU:-NgtUckUDVAUyttNVgYV:bya322c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L253)):*
> ```XML
>     cy.visit('/');
> 
>     const timetableDataInput = {
> ```

Would it make sense to move this outside the `describe` where route DB resources are as well?
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 358 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtXTA90KFH28OmakcN:-NgtXTA90KFH28OmakcO:b7qm1fs) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L358)):*
> ```XML
>       'downloadsFolder',
>     )}/jore4-export-${exportDate}.csv`;
>     cy.task('deleteFile', exportFilePath);
> ```

What is the purpose of this?

I see similar code in several other suites. Should we maybe create a small utility to do this? Would help explain the purpose as well.



_Code quote:_
```XML
    const exportDate = DateTime.now().toISODate();
    const exportFilePath = `${Cypress.config(
      'downloadsFolder',
    )}/jore4-export-${exportDate}.csv`;
    cy.task('deleteFile', exportFilePath);
```
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 387 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtZQnM9FKA8_1yjsuz:-NgtZQnM9FKA8_1yjsv-:b-8ngdx4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L387)):*
> ```XML
>       const routesAndLinesPage = new RoutesAndLinesPage();
> 
>       const IMPORT_FILENAME = 'timetablesReplace1.exp';
> ```

Perhaps this is in accordance to established practice in this repository, but just a thought: would it make sense to have these import file resource names near the top of the file? We define all other test data there as well, and these files definitely are test data.
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 391 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtYJ0p9Tp_67_f9zqK:-NgtYJ0p9Tp_67_f9zqL:b-z2xtph) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L391)):*
> ```XML
>       // Skip searching via UI
>       cy.visit('/routes/search?label=99&priorities=10&displayedType=routes');
>       // Export the route to enable timebtale import for it
> ```

Typo. 



_Suggestion:_
```XML
// Export the route to enable timetable import for it
```
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 409 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtZnTtExarnQwfWVjU:-NgtZnTtExarnQwfWVjV:b-xn0gb6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L409)):*
> ```XML
>       );
>       importTimetablesPage.clickPreviewButton();
>       previewTimetablesPage.priorityForm.setAsStandard();
> ```

Note, soon enough (when https://github.com/HSLdevcom/jore4/issues/1429 is implemented) we would probably add a check somewhere around here that "to be replaced" frames are shown correctly.
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 437 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtaTHi8q0lhU9WbU5d:-NgtaTHj6UlHP6yzs0Ae:b-snb1cx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L437)):*
> ```XML
>         .eq(2)
>         .should('contain', '99')
>         .and('contain', '2')
> ```

I take this checks the direction?  Would there be some more robust way of checking this, eg. from specifically the `DirectionBadge` element?

Currently it looks to me that this can fail very easily. We are just using `contain` assertions on the whole element, but in this case it also contains substring `2` elsewhere, as shown in check below `.and('contain', '10:21')`. So, wouldn't this direction assertion always pass, regardless what the direction actually is?

Maybe something similar to how this is done in `RouteStopsTable` methods `routeDirectionShouldBeOutbound` and `routeDirectionShouldBeInbound`?

More similar assertions in this file, but at least I couldn't find similar structure from other files :ok_hand: 
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 477 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-Ngtcwc_8anFGkUB51Nn:-Ngtcwc_8anFGkUB51No:b-468u7g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L477)):*
> ```XML
>         hour: '7',
>         departureTime: '27',
>       });
> ```

When importing timetables with replace mode, the replaced vehicle schedule frame validity end gets adjusted (to day before the new one starts). Validity range seems to be visible in this view, could maybe check it as well?

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682)* status: 1 of 7 files reviewed, 7 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 605 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtdkFV3RJy3-SjzEe_:-NgtdkFV3RJy3-SjzEea:b-z0kz5x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L605)):*
> ```XML
>         .should('contain', 'Lauantai');
> 
>       route99InboundSaturdayPassingTimesSection.assertNthPassingTimeOnStop({
> ```

This is rather verbose, especially with this many stops. But am not familiar enough with Cypress assertions to offer a more concise solution.

Also, these don't check that there are exactly these stops and nothing more. Though I don't see that as too big of a risk in this case.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682)* status: 1 of 14 files reviewed, 6 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 253 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtUckUDVAUyttNVgYU:-NhQAoVo7sAQOezRZCAQ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L253)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would it make sense to move this outside the `describe` where route DB resources are as well?
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 358 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtXTA90KFH28OmakcN:-NhQAsSTBDUO0Lnu2X6x:b-cv81xp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L358)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

What is the purpose of this?

I see similar code in several other suites. Should we maybe create a small utility to do this? Would help explain the purpose as well.
</blockquote></details>

This is just clean-up for the exported files. Other test suites do some comparisons that include these files, so we don't want to leave these here. I moved this clean-up to the after block from the afterEach, since it does not need to be done after every test in this suite. I guess this could be extracted to a helper function. 
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 387 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtZQnM9FKA8_1yjsuz:-NhQBoiE6js3WwuR5T0O:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L387)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Perhaps this is in accordance to established practice in this repository, but just a thought: would it make sense to have these import file resource names near the top of the file? We define all other test data there as well, and these files definitely are test data.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 409 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtZnTtExarnQwfWVjU:-NhQBz7n6iafztdZcYep:b-429iil) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L409)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Note, soon enough (when https://github.com/HSLdevcom/jore4/issues/1429 is implemented) we would probably add a check somewhere around here that "to be replaced" frames are shown correctly.
</blockquote></details>

Added a TODO for this.
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 437 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtaTHi8q0lhU9WbU5d:-NhQCKPbB5G9E6nfrcT1:b-xfj736) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L437)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I take this checks the direction?  Would there be some more robust way of checking this, eg. from specifically the `DirectionBadge` element?

Currently it looks to me that this can fail very easily. We are just using `contain` assertions on the whole element, but in this case it also contains substring `2` elsewhere, as shown in check below `.and('contain', '10:21')`. So, wouldn't this direction assertion always pass, regardless what the direction actually is?

Maybe something similar to how this is done in `RouteStopsTable` methods `routeDirectionShouldBeOutbound` and `routeDirectionShouldBeInbound`?

More similar assertions in this file, but at least I couldn't find similar structure from other files :ok_hand:
</blockquote></details>

Tried to make this a bit more robust.
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 477 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-Ngtcwc_8anFGkUB51Nn:-NhQClCU8lCZ7OfaEBsI:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L477)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

When importing timetables with replace mode, the replaced vehicle schedule frame validity end gets adjusted (to day before the new one starts). Validity range seems to be visible in this view, could maybe check it as well?
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 605 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtdkFV3RJy3-SjzEe_:-NhQCo2-CPDJ7ozlomCq:be9co0s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L605)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This is rather verbose, especially with this many stops. But am not familiar enough with Cypress assertions to offer a more concise solution.

Also, these don't check that there are exactly these stops and nothing more. Though I don't see that as too big of a risk in this case.
</blockquote></details>

Condensed this a bit. Open to suggestions as to how to make this check per stopLabel. Tried it, but the method got a bit too complicated.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682)* status: 4 of 20 files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 605 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NgtdkFV3RJy3-SjzEe_:-NhQix7i-StUDU3hPbE3:bmkhl43) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8f989998dd8876960309565083d681f359c794f2/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L605)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Condensed this a bit. Open to suggestions as to how to make this check per stopLabel. Tried it, but the method got a bit too complicated.
</blockquote></details>

Seems better already, good enough :thumbsup: 
___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 734 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NhQkzrl4Qfy_cc3M5Wt:-NhQkzrl4Qfy_cc3M5Wu:b-vqh4yk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6dcd31528aa539fb21176ea4e37d1f772ed8e2ef/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L734)):*
> ```XML
>       );
> 
>       // Check the timetable on a Saturday before the change date
> ```

There's some copypaste because the assertions between preview and without preview versions produce identical results. Could maybe refactor a little?

Also couple of assertions are missing from preview replace test, even though it should be the same as without previous version (I assume). This would also get fixed.

So could just move the assertions to helper functions, something like:
```
  const confirmTimetabelsAfterReplace = () => {
    // Check the timetable on a Saturday before the change date
    cy.visit(
      `timetables/lines/${lines[0].line_id}?observationDate=2023-06-24&routeLabels=${routes[0].label}`,
    );
    // ...

    // Check that the timetable has changed on the first Saturday after the validity start date of the new timetable
    cy.visit(
      `timetables/lines/${lines[0].line_id}?observationDate=2023-07-01&routeLabels=${routes[0].label}`,
    );
    // ...
  };

  const confirmTimetablesAfterCombine = () => {
    // Check that the previous timetable data and imported timetable data both exist
    cy.visit(
      `timetables/lines/${lines[0].line_id}?observationDate=2023-01-07&routeLabels=${routes[0].label}`,
    );
    // ...
  };
```
___
*[`cypress/pageObjects/PassingTimesByStopSection.ts` line 165 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NhQmSlz2RnFKstCNNUw:-NhQmSlz2RnFKstCNNUx:b-5tdtlv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6dcd31528aa539fb21176ea4e37d1f772ed8e2ef/cypress/pageObjects/PassingTimesByStopSection.ts#L165)):*
> ```XML
>         .getTimeContainerByHour(passingTimeInfo.hour)
>         .within(() => {
>           cy.wrap(passingTimeInfo.departureMinutes).each((minute: string) => {
> ```

Would it be possible to check that there are no extra departure minutes? Just by length. Same for arrival times. Currently tests will pass if DOM actually has more passing times than test assertions expect, I think.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682)* status: 3 of 20 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/timetablesReplaceAndCombine.cy.ts` line 734 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NhQkzrl4Qfy_cc3M5Wt:-NhRLk2EAipCgr87Doxb:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6dcd31528aa539fb21176ea4e37d1f772ed8e2ef/cypress/e2e/timetablesReplaceAndCombine.cy.ts#L734)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

There's some copypaste because the assertions between preview and without preview versions produce identical results. Could maybe refactor a little?

Also couple of assertions are missing from preview replace test, even though it should be the same as without previous version (I assume). This would also get fixed.

So could just move the assertions to helper functions, something like:
```
  const confirmTimetabelsAfterReplace = () => {
    // Check the timetable on a Saturday before the change date
    cy.visit(
      `timetables/lines/${lines[0].line_id}?observationDate=2023-06-24&routeLabels=${routes[0].label}`,
    );
    // ...

    // Check that the timetable has changed on the first Saturday after the validity start date of the new timetable
    cy.visit(
      `timetables/lines/${lines[0].line_id}?observationDate=2023-07-01&routeLabels=${routes[0].label}`,
    );
    // ...
  };

  const confirmTimetablesAfterCombine = () => {
    // Check that the previous timetable data and imported timetable data both exist
    cy.visit(
      `timetables/lines/${lines[0].line_id}?observationDate=2023-01-07&routeLabels=${routes[0].label}`,
    );
    // ...
  };
```
</blockquote></details>

Done.
___
*[`cypress/pageObjects/PassingTimesByStopSection.ts` line 165 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-NhQmSlz2RnFKstCNNUw:-NhRLo_yCa88j63GgrSd:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6dcd31528aa539fb21176ea4e37d1f772ed8e2ef/cypress/pageObjects/PassingTimesByStopSection.ts#L165)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would it be possible to check that there are no extra departure minutes? Just by length. Same for arrival times. Currently tests will pass if DOM actually has more passing times than test assertions expect, I think.
</blockquote></details>

Done.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/682#-:-NhRzxB-A4yor-zdTurJ:bnfp4nl)* status: 3 of 20 files reviewed, all discussions resolved

**Pull request merged**
