### PR TITLE
Route details view

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/73)

Closes https://github.com/HSLdevcom/jore4/issues/469

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/73)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/time.ts, line 31 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujCDjbAi9IO_tn6sf_:-MujCDjbAi9IO_tn6sfa:b9dw7hb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/time.ts#L31)):*
> ```XML
>   formatDate(DateTime.DATETIME_SHORT, date, locale);
> 
> export const MIN_DATE = DateTime.fromISO('1970-01-01');
> ```

Should this be `.startOfDay()` or something like that? Now both MIN_DATE and MAX_DATE are either startOf or endOf day, which might be confusing.
___
*[src/components/routes-and-lines/RouteStopsHeaderRow.tsx, line 64 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujApDp2LupGIbYjS1_:-MujApDp2LupGIbYjS1a:biy6m58) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/components/routes-and-lines/RouteStopsHeaderRow.tsx#L64)):*
> ```XML
>           className="h-full w-full text-center"
>           onClick={onToggle}
>           data-testid="toggleAccordion" // warning: this test ID is not globally unique
> ```

You could also prefix test id's with component name: 'RouteStopsHeaderRow::toggleAccordion" if those have to be globally unique
___
*[src/components/routes-and-lines/RouteStopsSection.tsx, line 23 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujBLEs7EkUx3D_GE9L:-MujBLEs7EkUx3D_GE9M:bnvyik5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/components/routes-and-lines/RouteStopsSection.tsx#L23)):*
> ```XML
> 
>   return (
>     // setting a fake "height: 1px" so that "height: 100%" would work for the table cells
> ```

I don't understand this comment as I don't see style where `height: 1px` is set

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/73)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[src/time.ts, line 31 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujCDjbAi9IO_tn6sf_:-MujCwJI4NXkMKF8sQNy:b-g5rz4j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/time.ts#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should this be `.startOfDay()` or something like that? Now both MIN_DATE and MAX_DATE are either startOf or endOf day, which might be confusing.
</blockquote></details>

I don't understand... could you elaborate?

the mapping functions are basically just printing the input date in the given format, they should not modify the date.

the MIN_DATE and MAX_DATE are just constant dates that are displayed in case e.g. some validity period is NULL
___
*[src/components/routes-and-lines/RouteStopsHeaderRow.tsx, line 64 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujApDp2LupGIbYjS1_:-MujDcZBDURVhWOZzxeQ:bvgtiqc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/components/routes-and-lines/RouteStopsHeaderRow.tsx#L64)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You could also prefix test id's with component name: 'RouteStopsHeaderRow::toggleAccordion" if those have to be globally unique
</blockquote></details>

they don't have to be globally unique... I just wonder what should be our standard when trying to access elements like this. Here, I just want to access this button for a specific table row. The row itself is unique. Should the testId be always globally unique? If yes, then should we access these repetitive buttons within a table through e.g. CSS className, is that any prettier?
___
*[src/components/routes-and-lines/RouteStopsSection.tsx, line 23 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujBLEs7EkUx3D_GE9L:-MujDUzJ70beLCPTdsC2:b-85e0u6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/components/routes-and-lines/RouteStopsSection.tsx#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand this comment as I don't see style where `height: 1px` is set
</blockquote></details>

good point, copy-paste error! Fixed.

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/73)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @pallost and @tk-vincit)

___
*[src/time.ts, line 31 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujCDjbAi9IO_tn6sf_:-MujFB31EmbMhl4IL1SL:b-hbqc9u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/time.ts#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't understand... could you elaborate?

the mapping functions are basically just printing the input date in the given format, they should not modify the date.

the MIN_DATE and MAX_DATE are just constant dates that are displayed in case e.g. some validity period is NULL
</blockquote></details>

Seems like this comment jumped on wrong line, I tried to comment this on following lines:

```
export const MIN_DATE = DateTime.fromISO('1970-01-01');
export const MAX_DATE = DateTime.fromISO('2050-12-31');
```
___
*[src/components/routes-and-lines/RouteStopsHeaderRow.tsx, line 64 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujApDp2LupGIbYjS1_:-MujEznB5ZXsnogBnags:b3egthj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/components/routes-and-lines/RouteStopsHeaderRow.tsx#L64)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

they don't have to be globally unique... I just wonder what should be our standard when trying to access elements like this. Here, I just want to access this button for a specific table row. The row itself is unique. Should the testId be always globally unique? If yes, then should we access these repetitive buttons within a table through e.g. CSS className, is that any prettier?
</blockquote></details>

I would just prefix these with component name if needed. Anyway, if there is not (currently) need for that then we can just leave this like this.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/73)* status: 0 of 22 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[src/time.ts, line 31 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujCDjbAi9IO_tn6sf_:-MujGjWOCdraN4BOyb78:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/time.ts#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems like this comment jumped on wrong line, I tried to comment this on following lines:

```
export const MIN_DATE = DateTime.fromISO('1970-01-01');
export const MAX_DATE = DateTime.fromISO('2050-12-31');
```

</blockquote></details>

done
___
*[src/components/routes-and-lines/RouteStopsHeaderRow.tsx, line 64 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/73#-MujApDp2LupGIbYjS1_:-MujHKZa9AAVveza42mm:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/98c5e0835c046d70c96b84ccc927c4c709347353/src/components/routes-and-lines/RouteStopsHeaderRow.tsx#L64)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I would just prefix these with component name if needed. Anyway, if there is not (currently) need for that then we can just leave this like this.
</blockquote></details>

OK

**Review by tk-vincit — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r9, 3 of 3 files at r10, 2 of 2 files at r11, 8 of 13 files at r12, 1 of 1 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
