### PR TITLE
Use custom checkbox and radio button components in priority forms

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785)* status: all files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/components/forms/common/LabeledContainer.tsx` line 13 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785#-NsE79iy84XrAChIr9wv:-NsE79iy84XrAChIr9ww:bb7phvt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/10ffdcf4c8b798c76cc642f16afef27e27b214b7/ui/src/components/forms/common/LabeledContainer.tsx#L13)):*
> ```XML
> }
> 
> // Classes that should be set to the child input element accordig to the `selected` value.
> ```

typo
___
*[`ui/src/components/forms/common/LabeledContainer.tsx` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785#-NsE7KK52Jev5Zr5UREx:-NsE7KK52Jev5Zr5UREy:b-i5on7x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/10ffdcf4c8b798c76cc642f16afef27e27b214b7/ui/src/components/forms/common/LabeledContainer.tsx#L23)):*
> ```XML
> };
> 
> export const LabeledContainer: React.FC<Props> = ({
> ```

Hmm, the naming feels a bit misleading, since it is named `Container`, but it returns a button. And also the button has "hardcoded" `<span>{label}</span>` in it.
Maybe something like LabeledButtonWrapper, LabeledButtonContainer, LabeledContainerButton etc.? Not that major though.
___
*[`ui/src/components/forms/common/LabeledRadioButton.tsx` line 11 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785#-NsEE_6f1ZyzVONaiZQO:-NsEE_6f1ZyzVONaiZQP:bse6fl6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/10ffdcf4c8b798c76cc642f16afef27e27b214b7/ui/src/components/forms/common/LabeledRadioButton.tsx#L11)):*
> ```XML
>   label: string;
>   onClick: () => void;
>   tooltip?: string;
> ```

NIT, optional `tooltip` could be grouped with the other optionals after the required ones. (It's an object, so doesn't matter much, but minor readability enhancement)

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`ui/src/components/forms/common/LabeledContainer.tsx` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785#-NsE7KK52Jev5Zr5UREx:-NsTAlTf-hrFOvBE5Ue2:b8q4evh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/10ffdcf4c8b798c76cc642f16afef27e27b214b7/ui/src/components/forms/common/LabeledContainer.tsx#L23)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, the naming feels a bit misleading, since it is named `Container`, but it returns a button. And also the button has "hardcoded" `<span>{label}</span>` in it.
Maybe something like LabeledButtonWrapper, LabeledButtonContainer, LabeledContainerButton etc.? Not that major though.
</blockquote></details>

I don't see a problem with this.
One reason not to name this `ButtonSomething` is that it would tie it too much to what the implementation is. Eg. I already changed this once when trying to get this work, from label -> button element.

Also this isn't really meant to be used on its own, is just a helper to share common parts for `LabeledCheckbox` and `LabeledRadioButton`.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 10 of 10 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 806 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785#-NsgwVQW8CYhYaOFYbKw:-NsgwVQX9YmkEiUIUzbm:b-5jfvdi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e163f684045149f63c48cd0ea6e29105fa079cc9/cypress/e2e/timetableImport.cy.ts#L806)):*
> ```XML
>           .getSpecialDayPriorityButton()
>           .should('be.visible')
>           .and('be.checked')
> ```

Hmm, the change feels OK, but started to wonder why the existing code had this "be.checked" and "be.disabled". Can't wrap my head around it, how does that make sense. 
___
*[`ui/src/components/forms/common/LabeledContainer.tsx` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785#-NsE7KK52Jev5Zr5UREx:-NshI9cu-BiBQYiklBdm:b6dun5s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/10ffdcf4c8b798c76cc642f16afef27e27b214b7/ui/src/components/forms/common/LabeledContainer.tsx#L23)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I don't see a problem with this.
One reason not to name this `ButtonSomething` is that it would tie it too much to what the implementation is. Eg. I already changed this once when trying to get this work, from label -> button element.

Also this isn't really meant to be used on its own, is just a helper to share common parts for `LabeledCheckbox` and `LabeledRadioButton`.
</blockquote></details>

Alright, understandable explanation :+1: thanks

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 806 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/785#-NsgwVQW8CYhYaOFYbKw:-NslCahqCHJoLemuqHap:b-jfxw6d) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e163f684045149f63c48cd0ea6e29105fa079cc9/cypress/e2e/timetableImport.cy.ts#L806)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, the change feels OK, but started to wonder why the existing code had this "be.checked" and "be.disabled". Can't wrap my head around it, how does that make sense.
</blockquote></details>

It was a checkbox, whose value was automatically selected when needed and couldn't/shouldn't be unchecked manually.

Now it's a radio button, with all other values disabled, so no need to disable the automatically selected special day option.

**Pull request merged**
