### PR TITLE
Create generic function to de/serializing values for redux store

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)

### CODE REVIEW

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`ui/src/redux/utils/mappers.ts` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9AR4efAuR0VTz34-RR:-N9AR4efAuR0VTz34-RS:b34eyti) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/58d501c9c52c427df41010f4aa76125d3c98099a/ui/src/redux/utils/mappers.ts#L11)):*
> ```XML
> export type StoreType<T extends PlainObject> = {
>   [Property in keyof T]: T[Property] extends PlainObject // object property -> recurse
>     ? StoreType<T[Property]>
> ```

Nested ternary operators are nasty to read :sweat: 
___
*[`ui/src/redux/utils/mappers.ts` line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9ARhJT2T870N2HpI1k:-N9ARhJT2T870N2HpI1l:b3ccxu7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/58d501c9c52c427df41010f4aa76125d3c98099a/ui/src/redux/utils/mappers.ts#L29)):*
> ```XML
> };
> 
> export function mapToStoreType<T extends PlainObject>(input: T): StoreType<T> {
> ```

Seems like something that could benefit from small test suite. Same for `mapFromStoreType`

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/redux/utils/mappers.ts` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9AR4efAuR0VTz34-RR:-N9A_F5G8-y0S1f-tTio:b-i9qzye) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/58d501c9c52c427df41010f4aa76125d3c98099a/ui/src/redux/utils/mappers.ts#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Nested ternary operators are nasty to read :sweat: 
</blockquote></details>

yeah, it was also super nasty to write ... tried to make the reviewers' life easier by at least commenting it
___
*[`ui/src/redux/utils/mappers.ts` line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9ARhJT2T870N2HpI1k:-N9A_RIY3dzVlkoR9nfg:bc663fi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/58d501c9c52c427df41010f4aa76125d3c98099a/ui/src/redux/utils/mappers.ts#L29)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems like something that could benefit from small test suite. Same for `mapFromStoreType`
</blockquote></details>

good point! Created some tests

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`ui/src/redux/utils/mappers.ts` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9AR4efAuR0VTz34-RR:-N9Bt1rhBc7vIXdO605-:b18xi0b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/58d501c9c52c427df41010f4aa76125d3c98099a/ui/src/redux/utils/mappers.ts#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yeah, it was also super nasty to write ... tried to make the reviewers' life easier by at least commenting it
</blockquote></details>

Was thinking that could we get rid of those by converting nested structures to explicit if-else blocks, or is TS making that impossible here? No need to spent more time here at this point if this is not easy to fix.
___
*[`ui/src/redux/utils/mappers.spec.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Bq8ow5Z9aGd4R1M96:-N9Bq8ow5Z9aGd4R1M97:b-mkiir9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L16)):*
> ```XML
>     },
>     // date as an object attribute
>     dat: DateTime.fromISO('2022-08-11T06:39:39.766Z'),
> ```

By using just one character more, you could call this property "date" and improve readability significantly. :wink: Same for "dat2"
___
*[`ui/src/redux/utils/mappers.spec.ts` line 49 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9BqLv10wMn-T3FqFV8:-N9BqLv10wMn-T3FqFV9:b-ijizsj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L49)):*
> ```XML
>   describe(`${mapToStoreType.name}`, () => {
>     it('should leave input intact if no fields are to be replaced', () => {
>       const customReplacer = () => [];
> ```

I was really confused when I read this for the first time, as this whole "custom replacer" concept does not actually replace anything and I didn't understood why one would even want to write custom replacer functions.

When I checked the implementation of the mapper function itself this I finally understood what this is about. Anyway, that was good indicator that maybe naming of this could be improved a bit. In the function implementation this was called "replacedFieldsFunc", so maybe this could be called the same here, or even something more descriptive like "getReplacedFieldNames" or "getFieldNamesToReplace" or something like that.
___
*[`ui/src/redux/utils/mappers.spec.ts` line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9BrC_B8TO_bwvYSK_e:-N9BrC_B8TO_bwvYSK_f:b-dx2g8b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L64)):*
> ```XML
>       // Note: jest matchers are not working well with DateTime objects, thus better to observe endresult from the snapshot
>       expect(output).toMatchSnapshot();
>       expect(typeof output.str).toEqual('string');
> ```

Shouldn't you check that `output.dat` field was replaced as expected? Something like: `expect(typeof output.dat).toEqual('string'); expect(output.dat).toEqual(inputDateTime.dat.toISOstring()); ` (did not checked the syntax)

If this test should also verify that recursive conversions work as its description suggests then we should also verify `inputDateTime.obj.dat` and `inputDateTime.arrOfObjects[0].dat`...

Or OK, was the reason for leaving those out to have snapshot that we can look at? As it is not inline snapshot it would make life much easier if these things could be read from this test already as I suggested, or then chancing snapshot to inline snapshot (assuming those work with our current setup...)
___
*[`ui/src/redux/utils/mappers.spec.ts` line 92 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Bppji3fBb1fdlWUyS:-N9BppjjAgxxb5K_A6L-:br4ps1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L92)):*
> ```XML
>   describe(`reversibility`, () => {
>     it('should be able to retrieve the same input object after serializing and deserializing', () => {
>       const customReplacer = () => ['dat'];
> ```

Why not to include all the fields here? The mapper function is quite complex with support for nested structures etc, but now we just verify that the most basic use case works. OK, seems like "dat2" field was left out for purpose, but maybe we could also check that we don't serialize and de-serialize strings, integers, functions etc. in unexpected ways.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/redux/utils/mappers.ts` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9AR4efAuR0VTz34-RR:-N9UyZVk6GurcL0Q4qZf:b-97aii8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/58d501c9c52c427df41010f4aa76125d3c98099a/ui/src/redux/utils/mappers.ts#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Was thinking that could we get rid of those by converting nested structures to explicit if-else blocks, or is TS making that impossible here? No need to spent more time here at this point if this is not easy to fix.
</blockquote></details>

typescript types can only use ternary types unfortunately, there's no if-else... also, as it's recursive, it needs to be in a single block instead of combining it from multiple type chunks :/
___
*[`ui/src/redux/utils/mappers.spec.ts` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Bq8ow5Z9aGd4R1M96:-N9VNQjJ38F2tgiLWX9v:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L16)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

By using just one character more, you could call this property "date" and improve readability significantly. :wink: Same for "dat2"
</blockquote></details>

Done.
___
*[`ui/src/redux/utils/mappers.spec.ts` line 49 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9BqLv10wMn-T3FqFV8:-N9VNEDi-PO81_Gsm0iv:b-bklp34) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L49)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I was really confused when I read this for the first time, as this whole "custom replacer" concept does not actually replace anything and I didn't understood why one would even want to write custom replacer functions.

When I checked the implementation of the mapper function itself this I finally understood what this is about. Anyway, that was good indicator that maybe naming of this could be improved a bit. In the function implementation this was called "replacedFieldsFunc", so maybe this could be called the same here, or even something more descriptive like "getReplacedFieldNames" or "getFieldNamesToReplace" or something like that.
</blockquote></details>

I ended up on rewriting this part to be even more generic and extract it as a serializer function
___
*[`ui/src/redux/utils/mappers.spec.ts` line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9BrC_B8TO_bwvYSK_e:-N9VNS4d1HJoVfBCwAl5:bv6skph) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L64)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Shouldn't you check that `output.dat` field was replaced as expected? Something like: `expect(typeof output.dat).toEqual('string'); expect(output.dat).toEqual(inputDateTime.dat.toISOstring()); ` (did not checked the syntax)

If this test should also verify that recursive conversions work as its description suggests then we should also verify `inputDateTime.obj.dat` and `inputDateTime.arrOfObjects[0].dat`...

Or OK, was the reason for leaving those out to have snapshot that we can look at? As it is not inline snapshot it would make life much easier if these things could be read from this test already as I suggested, or then chancing snapshot to inline snapshot (assuming those work with our current setup...)
</blockquote></details>

wrote wrappers for this
___
*[`ui/src/redux/utils/mappers.spec.ts` line 92 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Bppji3fBb1fdlWUyS:-N9VNZSX82fn7bRIXIMN:b-gjwu0w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c9d3c5557737dfdb938775c0cbba630f03fdd773/ui/src/redux/utils/mappers.spec.ts#L92)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why not to include all the fields here? The mapper function is quite complex with support for nested structures etc, but now we just verify that the most basic use case works. OK, seems like "dat2" field was left out for purpose, but maybe we could also check that we don't serialize and de-serialize strings, integers, functions etc. in unexpected ways.
</blockquote></details>

rewrote this part, now using custom serializer functions

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`ui/src/redux/utils/mappers.ts` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9AR4efAuR0VTz34-RR:-N9VjZI-0bm8SC17-zMw:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/58d501c9c52c427df41010f4aa76125d3c98099a/ui/src/redux/utils/mappers.ts#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

typescript types can only use ternary types unfortunately, there's no if-else... also, as it's recursive, it needs to be in a single block instead of combining it from multiple type chunks :/
</blockquote></details>

:+1: 
___
*[`ui/src/redux/utils/mappers.spec.ts` line 11 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9VmZ_f-STB2i2fiywj:-N9VmZ_f-STB2i2fiywk:bwxqdgj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/redux/utils/mappers.spec.ts#L11)):*
> ```XML
> } from './mappers';
> 
> const expectToBeSerialized = (input: unknown, output: unknown) => {
> ```

`expectDateTimeToBeSerialized`? This function won't work if we are serializing anything else than dates/timestamps
___
*[`ui/src/redux/utils/mappers.spec.ts` line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Vmj-W6LsZ3dXDWNjx:-N9Vmj-W6LsZ3dXDWNjy:b-ksgmnj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/redux/utils/mappers.spec.ts#L17)):*
> ```XML
> };
> 
> const expectToBeDeserialized = (input: unknown, output: unknown) => {
> ```

`expectDateTimeToBeDeserialized`?
___
*[`ui/src/redux/utils/mappers.spec.ts` line 199 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9VmNRl5Gjljbg-K81j:-N9VmNRl5Gjljbg-K81k:b-k6emra) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/redux/utils/mappers.spec.ts#L199)):*
> ```XML
>             toSerialize: DateTime.fromISO('2022-08-11T06:39:39.766+03:00'),
>           },
>         ],
> ```

Should we also test array of scalars, e.g. `arr: [ dateTime, dateTime ]`?
___
*[`ui/src/types/types.d.ts` line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Vm6Yn0MvWWEBCb_df:-N9Vm6Yn0MvWWEBCb_dg:bsx7vcv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/types/types.d.ts#L46)):*
> ```XML
> // by default keyof T can be string | number | symbol
> // but most times we know that the keys can only be strings
> type KeyOf<T> = Extract<keyof T, string>;
> ```

StringKeyOf?
___
*[`ui/src/utils/object.ts` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9VmEa11BkGLWdvskv5:-N9VmEa11BkGLWdvskv6:b-83sjoh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/utils/object.ts#L9)):*
> ```XML
> // the built-in Object.keys() method returns only a limited string[] type.
> // The actual return type should be KeyOf<T>[]
> export const getObjectKeys = <T extends PlainObject>(input: T) => {
> ```

Nice!

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/redux/utils/mappers.spec.ts` line 11 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9VmZ_f-STB2i2fiywj:-N9Vnr0pCNk7HsRa0B5W:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/redux/utils/mappers.spec.ts#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`expectDateTimeToBeSerialized`? This function won't work if we are serializing anything else than dates/timestamps
</blockquote></details>

Done.
___
*[`ui/src/redux/utils/mappers.spec.ts` line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Vmj-W6LsZ3dXDWNjx:-N9VnrGMCQZtj5vRN3yz:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/redux/utils/mappers.spec.ts#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`expectDateTimeToBeDeserialized`?
</blockquote></details>

Done.
___
*[`ui/src/redux/utils/mappers.spec.ts` line 199 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9VmNRl5Gjljbg-K81j:-N9VofplA7O0q8zr3i9i:bwfnlh9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/redux/utils/mappers.spec.ts#L199)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should we also test array of scalars, e.g. `arr: [ dateTime, dateTime ]`?
</blockquote></details>

added a test like this
___
*[`ui/src/types/types.d.ts` line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9Vm6Yn0MvWWEBCb_df:-N9Volmg3rfDF49rxVkw:b-up5iko) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/types/types.d.ts#L46)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

StringKeyOf?
</blockquote></details>

yeah, I was wondering about the same... I'll rename it
___
*[`ui/src/utils/object.ts` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/294#-N9VmEa11BkGLWdvskv5:-N9Vq2DR5G8kXGMSC86U:b-32hzwe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144b70b9eac11fe95a6490ba570c1d59428f9ad2/ui/src/utils/object.ts#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

yeah, but actually wasn't perfect enough, needed to create one more overload...

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/294)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

**Pull request merged**
