### PR TITLE
Fix line search results marker button

### PR DESCRIPTION
**Pull request by eleksi**
Resolves HSLdevcom/jore4#915

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/303)

### CODE REVIEW

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/303)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[`ui/src/hooks/search/useSearchResults.ts` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jirr0DSKkAoD76Rco:-N9jirr0DSKkAoD76Rcp:b2abkf2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/hooks/search/useSearchResults.ts#L32)):*
> ```XML
>   result: ReturnType<typeof useSearchLinesAndRoutesQuery>,
> ) => ({
>   lines: (result.data?.route_line || []) as LineTableRowFragment[],
> ```

you should not need this mapper anymore, just use the result.data directly in the consumers

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/303)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jgLxcEyBwWRy0C-CD:-N9jgLxcEyBwWRy0C-CE:bd3zj5o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L17)):*
> ```XML
> 
> const GQL_LINE_TABLE_ROW = gql`
>   fragment line_table_row on route_line {
> ```

I think this should be named `fragment line_table_row_fields` to match the other fragment names
___
*[`ui/src/hooks/search/useSearchResults.ts` line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jhX0M2g-V427LqZ-_:-N9jhX0M2g-V427LqZ-a:b-4xr1vw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/hooks/search/useSearchResults.ts#L38)):*
> ```XML
> export const useSearchResults = (): {
>   lines: LineTableRowFragment[];
>   routes: RouteAllFieldsFragment[];
> ```

Should we have fragment for RouteTableRow as well? (btw, just realised that the component should probably be called `RouteTableRow` instead of `RoutesTableRow` (plural)).

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/303)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jgLxcEyBwWRy0C-CD:-N9jqL4gBThBYUOshMZ0:biuvijs) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L17)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this should be named `fragment line_table_row_fields` to match the other fragment names
</blockquote></details>

Not all the fragments are named like that e.g. (`route_with_journey_pattern_stops`). I think the fields postfix is there to avoid having name like `route_all` when we literally mean route with all fields.

In my opinion I don't think we have to add "fields" to all fragments, as fragment-postfix is already added to typescript types and when using these inside graphql it is clear that those are fragments that contain fields.
___
*[`ui/src/hooks/search/useSearchResults.ts` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jirr0DSKkAoD76Rco:-N9jr9fh0Ipjh5AChGyG:b-uy4i1k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/hooks/search/useSearchResults.ts#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should not need this mapper anymore, just use the result.data directly in the consumers
</blockquote></details>

Yep maybe it is cleaner. Fixed.
___
*[`ui/src/hooks/search/useSearchResults.ts` line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jhX0M2g-V427LqZ-_:-N9jrG3y4xRo8BCBPyHN:b-nown5r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/hooks/search/useSearchResults.ts#L38)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should we have fragment for RouteTableRow as well? (btw, just realised that the component should probably be called `RouteTableRow` instead of `RoutesTableRow` (plural)).
</blockquote></details>

I was thinking of this as well, but now that it is same as `RouteAllFieldsFragment` I'm wondering if we really want to make a copy of that. 

`LineTableRowFragment` also has a dependency to `LineAllFieldsFragment`, it could be a bad thing but do we really want to start copying every single line and route field these types... Where is the optimal point..?

**Review by HenrikHartiala — APPROVED** [review]
Nice!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-:-N9k0yyl8miKyoVrw8Bs:b-83sjoh)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jgLxcEyBwWRy0C-CD:-N9jxth_3GRepiwApdlP:b5saakz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L17)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Not all the fragments are named like that e.g. (`route_with_journey_pattern_stops`). I think the fields postfix is there to avoid having name like `route_all` when we literally mean route with all fields.

In my opinion I don't think we have to add "fields" to all fragments, as fragment-postfix is already added to typescript types and when using these inside graphql it is clear that those are fragments that contain fields.

</blockquote></details>

Ah, my skim search did not spot that there were also fragments without the `fields` postfix. Also good point about the fragment-postfix. This is good then :+1: 
___
*[`ui/src/hooks/search/useSearchResults.ts` line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/303#-N9jhX0M2g-V427LqZ-_:-N9jyZQZ9iEYJpNDWrd9:b-f1ys4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/896cdc9575d3b7c4bd7d812aad6ad39f4afc53ef/ui/src/hooks/search/useSearchResults.ts#L38)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I was thinking of this as well, but now that it is same as `RouteAllFieldsFragment` I'm wondering if we really want to make a copy of that. 

`LineTableRowFragment` also has a dependency to `LineAllFieldsFragment`, it could be a bad thing but do we really want to start copying every single line and route field these types... Where is the optimal point..?
</blockquote></details>

But do we actually need *all* the fields? Hmm, as I checked: maybe we do :D. But yeah I only wondered if at some point we add fields to route that are not needed in this particular component, it wouldn't affect this if it had it's own fields. I think we also discussed that it is OK to have the same fields in different fragments. I think this is okay for now and up to you if you still want to change it.

What comes to the `LineAllFieldsFragment` dependency, it is still much easier to change to the desired fields when we already have this separated `LineTableRowFragment`. So I think it is okay to use the AllFields fragment as dependency as long as it uses all the fields :+1:

**Pull request merged**
