### PR TITLE
Add stop creation at point specified by % of viewport

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#969

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/342)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/342)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`cypress/pageObjects/MapItemCreator.ts` line 111 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/342#-NCTs5m_0PAil9UDr9CQ:-NCTs5m_0PAil9UDr9CR:b9rh4fu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/113da36ebd7af39c2b65ad281b346cbfa7f65b4b/cypress/pageObjects/MapItemCreator.ts#L111)):*
> ```XML
>    */
> 
>   createStopAtLocationByPercentages = ({
> ```

this is ~30 lines of copy-pasted code with only a tiny difference from the other function. You don't need the one with the coordinates anymore as it's not reliable. Just delete that and name this function as createStopAtLocation
___
*[`cypress/pageObjects/MapItemCreator.ts` line 131 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/342#-NCTsezZ-i1GIeGy-zSN:-NCTsezZ-i1GIeGy-zSO:b6rv68) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/113da36ebd7af39c2b65ad281b346cbfa7f65b4b/cypress/pageObjects/MapItemCreator.ts#L131)):*
> ```XML
>     );
> 
>     this.stopForm.fillStopForm(stopFormInfo);
> ```

not necessarily in the scope of this PR, but the responsibilities of these functions are defined wrong. These should be a function for the confirmSaveForm page object that fills in all the necessary information: priority, validityStart, validityEnd
The createStopAtLocation function should then just call: mapFooter.addStop, map.clickRelativePoint, stopForm.fillForm, confirmStopForm.fillForm

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/342)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`cypress/pageObjects/MapItemCreator.ts` line 111 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/342#-NCTs5m_0PAil9UDr9CQ:-NCULsYrEX9QqzLx9San:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/113da36ebd7af39c2b65ad281b346cbfa7f65b4b/cypress/pageObjects/MapItemCreator.ts#L111)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is ~30 lines of copy-pasted code with only a tiny difference from the other function. You don't need the one with the coordinates anymore as it's not reliable. Just delete that and name this function as createStopAtLocation
</blockquote></details>

Done.
___
*[`cypress/pageObjects/MapItemCreator.ts` line 131 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/342#-NCTsezZ-i1GIeGy-zSN:-NCULu-Z3-A3keBo-A7P:bg0hxm3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/113da36ebd7af39c2b65ad281b346cbfa7f65b4b/cypress/pageObjects/MapItemCreator.ts#L131)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

not necessarily in the scope of this PR, but the responsibilities of these functions are defined wrong. These should be a function for the confirmSaveForm page object that fills in all the necessary information: priority, validityStart, validityEnd
The createStopAtLocation function should then just call: mapFooter.addStop, map.clickRelativePoint, stopForm.fillForm, confirmStopForm.fillForm
</blockquote></details>

I can create a separate ticket for this.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/342)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`cypress/pageObjects/MapItemCreator.ts` line 131 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/342#-NCTsezZ-i1GIeGy-zSN:-NCUhWmuCm-pLjpDQNRE:bf79okf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/113da36ebd7af39c2b65ad281b346cbfa7f65b4b/cypress/pageObjects/MapItemCreator.ts#L131)):*
<details><summary><i>Previously, sr-vala wrote…</i></summary><blockquote>

I can create a separate ticket for this.
</blockquote></details>

Created https://github.com/HSLdevcom/jore4/issues/970

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/342)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
