### PR TITLE
Position map to route start

### PR DESCRIPTION
**Pull request by HenrikHartiala**
Set map position to route start when opening a route on map. This uses the first coordinate it can find from the route geometry `route_shape`. This is a temporary implementation for positioning the map, and can be changed after react-map-gl v7 is updated.

A minor change to route_shape calculation in hasura has to be updated first for this to work for some of the cases. (There are couple of routes which currently generates a MultiLineString and this is not wanted nor it is handled here)

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/311)

### CODE REVIEW

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/311)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 34 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NA9MEiF3g8DS7K3Ey22:-NA9MEiF3g8DS7K3Ey23:bs23d6w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a98d1e1d8373747332c5fbc36c2ada7e0a5a1a1/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L34)):*
> ```XML
>     const lineRouteIds = line.line_routes?.map((item) => item.route_id);
> 
>     // This is a temporary solution to position the map on opened route (or line)
> ```

Could majority of this function be in `useShowRoutesOnModal` hook, taking only the route as a parameter? There is some duplication now.
___
*[`ui/src/components/routes-and-lines/main/RoutesTableRow.tsx` line 26 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NA9L5n6-oljNhAngvnk:-NA9L5n6-oljNhAngvnl:b-c18app) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a98d1e1d8373747332c5fbc36c2ada7e0a5a1a1/ui/src/components/routes-and-lines/main/RoutesTableRow.tsx#L26)):*
> ```XML
>   const alertStyle = getAlertStyle(getAlertLevel(route));
> 
>   const onClickShowRouteOnMap = () => {
> ```

Could this entire function be in`useShowRoutesOnModal` hook, taking only the route as a parameter? There is some duplication now.
___
*[`ui/src/components/routes-and-lines/main/RoutesTableRow.tsx` line 70 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NA9MRsJ4F7VhTnLnwXC:-NA9MRsJ4F7VhTnLnwXD:b2a14fd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a98d1e1d8373747332c5fbc36c2ada7e0a5a1a1/ui/src/components/routes-and-lines/main/RoutesTableRow.tsx#L70)):*
> ```XML
>         <td className="w-20 p-6 align-middle">
>           <LocatorButton
>             onClick={onClickShowRouteOnMap}
> ```

Good that you got rid of the inline functions
___
*[`ui/src/hooks/urlQuery/useMapQueryParams.ts` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NA9IWSXEvgkmQg08eE2:-NA9IWSYAOK9NjTOfEqV:b-20h5b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a98d1e1d8373747332c5fbc36c2ada7e0a5a1a1/ui/src/hooks/urlQuery/useMapQueryParams.ts#L28)):*
> ```XML
>    * after react-map-gl v7 is updated.
>    */
>   const openMapAndSetMapPosition = (
> ```

I would name this something like `openMapInPosition`

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/311)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/routes-and-lines/main/LineTableRow.tsx` line 34 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NA9MEiF3g8DS7K3Ey22:-NADMVhN9f7JnlGatu6z:btsha2f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a98d1e1d8373747332c5fbc36c2ada7e0a5a1a1/ui/src/components/routes-and-lines/main/LineTableRow.tsx#L34)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Could majority of this function be in `useShowRoutesOnModal` hook, taking only the route as a parameter? There is some duplication now.
</blockquote></details>

Good one, bringing in the route information like discussed.
___
*[`ui/src/components/routes-and-lines/main/RoutesTableRow.tsx` line 26 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NA9L5n6-oljNhAngvnk:-NADMVH112SU0hH4i7uR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a98d1e1d8373747332c5fbc36c2ada7e0a5a1a1/ui/src/components/routes-and-lines/main/RoutesTableRow.tsx#L26)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Could this entire function be in`useShowRoutesOnModal` hook, taking only the route as a parameter? There is some duplication now.
</blockquote></details>

Done.
___
*[`ui/src/hooks/urlQuery/useMapQueryParams.ts` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NA9IWSXEvgkmQg08eE2:-NADMSZs7yhGdXBWUZ8Y:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2a98d1e1d8373747332c5fbc36c2ada7e0a5a1a1/ui/src/hooks/urlQuery/useMapQueryParams.ts#L28)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I would name this something like `openMapInPosition`
</blockquote></details>

Done.

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r3, 7 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/311)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`ui/src/hooks/urlQuery/useMapQueryParams.ts` line 36 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NADhPng4cx9RH_0hIyT:-NADhPnh8pr0soYi86ua:bgkaeje) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e58f7b1eceabb0a50a642c7ae9748bbaf7936b22/ui/src/hooks/urlQuery/useMapQueryParams.ts#L36)):*
> ```XML
>       parameters: [
>         {
>           paramName: 'lat',
> ```

Should probably use the constants defined on top of this file here.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/311)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/hooks/urlQuery/useMapQueryParams.ts` line 36 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/311#-NADhPng4cx9RH_0hIyT:-NAIe_I-A6sU1yYB90cN:bbfc5a1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e58f7b1eceabb0a50a642c7ae9748bbaf7936b22/ui/src/hooks/urlQuery/useMapQueryParams.ts#L36)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Should probably use the constants defined on top of this file here.
</blockquote></details>

:man_facepalming: yes definitely.

**Review by eleksi — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/311)* status: all files reviewed, 1 unresolved discussion (waiting on @eleksi)

**Pull request merged**
