### PR TITLE
Refactor draw route layer

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/111)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/111)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[src/hooks/useExtractRouteFromFeature.ts, line 108 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/111#-Mxd_7212Erz-qC3CdM_:-Mxd_7212Erz-qC3CdMa:b7chuy8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/687c7b0cfcd17a053e11cd48bafa8a9bfb57ed29/src/hooks/useExtractRouteFromFeature.ts#L108)):*
> ```XML
>         (link, index) => {
>           const isFirst = index === 0;
>           let linkCoordinates = link.shape.coordinates;
> ```

Variable naming should be improved, but this could be written somehow like this to avoid variable definition:

```
const tempCoordinates = link.shape.coordinates;
            const myCondition = tempCoordinates.length && !link.isTraversalForwards;
            const linkCoordinates = myCondition ? tempCoordinates : tempCoordinates.reverse();
```



_Code quote:_
```XML
          let linkCoordinates = link.shape.coordinates;

          // Order coordinates properly
          if (linkCoordinates.length > 0 && !link.isTraversalForwards) {
            // TODO: Could be optimized since only first and last coordinates are being used
            linkCoordinates = [...linkCoordinates].reverse();
          }
```
___
*[src/hooks/useExtractRouteFromFeature.ts, line 218 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/111#-MxdaIxV49P_4gT7lMRv:-MxdaIxV49P_4gT7lMRw:b-szn4p1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/687c7b0cfcd17a053e11cd48bafa8a9bfb57ed29/src/hooks/useExtractRouteFromFeature.ts#L218)):*
> ```XML
>         stateStops
>           .filter((item) => item.belongsToRoute)
>           ?.map((item) => item.id) || [];
> ```

Same thing about let statements and idiomatic JS that I commented on two previous pr's. :) Also seeing same `.filter().map()` pattern once again :)



_Code quote:_
```XML
      let oldStopIds =
        stateStops
          .filter((item) => item.belongsToRoute)
          ?.map((item) => item.id) || [];
      let oldInfraLinks = stateInfraLinks || [];
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/111)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[src/hooks/useExtractRouteFromFeature.ts, line 108 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/111#-Mxd_7212Erz-qC3CdM_:-MxhbCEM70F4_TI45WlM:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/687c7b0cfcd17a053e11cd48bafa8a9bfb57ed29/src/hooks/useExtractRouteFromFeature.ts#L108)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Variable naming should be improved, but this could be written somehow like this to avoid variable definition:

```
const tempCoordinates = link.shape.coordinates;
            const myCondition = tempCoordinates.length && !link.isTraversalForwards;
            const linkCoordinates = myCondition ? tempCoordinates : tempCoordinates.reverse();
```
</blockquote></details>

Done.
___
*[src/hooks/useExtractRouteFromFeature.ts, line 218 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/111#-MxdaIxV49P_4gT7lMRv:-Mxh_skw3DwJnFjBDaNM:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/687c7b0cfcd17a053e11cd48bafa8a9bfb57ed29/src/hooks/useExtractRouteFromFeature.ts#L218)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same thing about let statements and idiomatic JS that I commented on two previous pr's. :) Also seeing same `.filter().map()` pattern once again :)
</blockquote></details>

Done.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/111)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[src/hooks/useExtractRouteFromFeature.ts, line 205 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/111#-MxiMQJd6GjFedgEYFS_:-MxiMQJd6GjFedgEYFSa:b-jb9zix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7de425c2523163436791055285130508063f0aea/src/hooks/useExtractRouteFromFeature.ts#L205)):*
> ```XML
>   );
> 
>   const getRouteStops = useCallback(
> ```

Just wondering if there is any reason for pure functions like this to be inside this hook, or should/could these be plain utility functions. That way we also wouldn't need to wrap these inside useCallback hooks.

There seems to be couple of similar functions, like
`extractCoordinatesFromFeatures` or `getOldInfraLinksAndStops` or `mapInfraLinksToFeature`

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/111)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[src/hooks/useExtractRouteFromFeature.ts, line 205 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/111#-MxiMQJd6GjFedgEYFS_:-MxiUjKh5W0RGdFAC3eZ:btokwua) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7de425c2523163436791055285130508063f0aea/src/hooks/useExtractRouteFromFeature.ts#L205)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Just wondering if there is any reason for pure functions like this to be inside this hook, or should/could these be plain utility functions. That way we also wouldn't need to wrap these inside useCallback hooks.

There seems to be couple of similar functions, like
`extractCoordinatesFromFeatures` or `getOldInfraLinksAndStops` or `mapInfraLinksToFeature`
</blockquote></details>

We will discuss this later, left like this for now.

**Review by tk-vincit — APPROVED** [review]
> Reviewed 1 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/111)* status: 1 of 17 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[src/hooks/useExtractRouteFromFeature.ts, line 205 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/111#-MxiMQJd6GjFedgEYFS_:-MxidiYbDN943a_A9Hjz:b2nhb2c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7de425c2523163436791055285130508063f0aea/src/hooks/useExtractRouteFromFeature.ts#L205)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

We will discuss this later, left like this for now.
</blockquote></details>

Ack

**Pull request merged**
