### PR TITLE
Add maintainers for stop places

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889)* status: all files reviewed, 13 unresolved discussions (waiting on @Leitsi)

___
*[`test-db-manager/src/seedStopRegistry.ts` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5IgQkV0v0VCW5D1SKP:-O5IgQkV0v0VCW5D1SKQ:b-behsue) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/test-db-manager/src/seedStopRegistry.ts#L40)):*
> ```XML
>     )) as InsertOrganisationResult;
> 
>     if (returnValue.data == null) {
> ```

NIT,  double equals here



_Suggestion:_
```XML
    if (returnValue.data === null) {
```
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 39 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Ik-RL6qkCbdePnVIu:-O5Ik-RL6qkCbdePnVIv:b2fsknt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L39)):*
> ```XML
>     render: () => {
>       return (
>         <div className="cursor-default">
> ```

Could maybe use a single div and then padding? (Also the right margin probably does nothing here)



_Suggestion:_
```XML

        <div className="pl-4 cursor-default">{uiText}</div>
```
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 53 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Ixp1cEdeRhUa1Rr6x:-O5Ixp1cEdeRhUa1Rr6y:bcp1jrg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L53)):*
> ```XML
>       mapToOption(String(o.id ?? null), uiNameMapper(o) ?? ''),
>     ),
>     mapToOption(
> ```

This "create new" option would benefit from some kind of (green) '+' icon or something to distinguish it visually from the other options. But if this was the design for now then no need to do further changes in this PR. Not blocking.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerFormFields.tsx` line 87 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5IlLNqCczOW9yUtBfj:-O5IlLNr2Ll9pRpyPq-V:b-3sqa9s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerFormFields.tsx#L87)):*
> ```XML
>         />
>         <div className="text-sm">
>           <p>{selectedMaintainer?.privateContactDetails?.phone ?? ''}</p>
> ```

Even though a `<p>` element nicely handles the line breaks, I think `<span className="block">` would be semantically correct here, since these are not precisely paragraphs.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerViewCard.tsx` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5IoK__5Tl_sgdpDY1U:-O5IoK__5Tl_sgdpDY1V:b-4z7j8k) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerViewCard.tsx#L23)):*
> ```XML
>       {maintainer ? (
>         <>
>           <p data-testid={testIds.name}>{maintainer?.name ?? ''}</p>
> ```

Same goes here, so probably best to use `<span>`
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerViewCard.tsx` line 25 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Ip8N4EKOlmcSxtEN2:-O5Ip8N4EKOlmcSxtEN3:b-2h57cn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerViewCard.tsx#L25)):*
> ```XML
>           <p data-testid={testIds.name}>{maintainer?.name ?? ''}</p>
>           <p data-testid={testIds.phone}>
>             {maintainer?.privateContactDetails?.phone ?? ''}
> ```

maintainer can't be null so the first ? -operator can be removed from these



_Suggestion:_
```XML
            {maintainer.privateContactDetails?.phone ?? ''}
```
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceDetailsForm.tsx` line 71 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5IqMsPCIDCFw5GIEcQ:-O5IqMsPCIDCFw5GIEcR:b-ok15fj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceDetailsForm.tsx#L71)):*
> ```XML
>     setEditedOrganisation(org);
>     setEditedMaintainerType(relationshipType);
>   };
> ```

NIT, line breaks between  methods would be nice
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceDetailsForm.tsx` line 91 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Iq0IQ8So54p3Jj4vm:-O5Iq0IQ8So54p3Jj4vn:b-ktvyey) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceDetailsForm.tsx#L91)):*
> ```XML
>     <FormProvider {...methods}>
>       <form
>         className={`grid grid-cols-3 gap-x-4 gap-y-4 lg:grid-cols-5 ${className}`}
> ```

gaps can be be simplified



_Suggestion:_
```XML
        className={`grid grid-cols-3 gap-4 lg:grid-cols-5 ${className}`}
```
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceViewCard.tsx` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5IqfSZ2b7Vig8Y6puF:-O5IqfSZ2b7Vig8Y6puG:b-9jvc7q) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceViewCard.tsx#L26)):*
> ```XML
>   return (
>     <div data-testid={testIds.container}>
>       <div className="grid grid-cols-3 gap-x-4 gap-y-4 lg:grid-cols-5">
> ```

Same gap simplification can be applied here
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx` line 59 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5ItZRi1s6fhfI_5SpS:-O5ItZRi1s6fhfI_5SpT:b-ks5589) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx#L59)):*
> ```XML
>     <FormProvider {...methods}>
>       <form onSubmit={handleSubmit(onSubmit)} ref={formRef}>
>         <div className="space-y-2">
> ```

(continues from a comment below): So practically here. 



_Suggestion:_
```XML
        <div className="space-y-2 max-w-[400px]">
```
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx` line 85 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Is6EYDKbe-cmwU6lM:-O5Is6EYDKbe-cmwU6lN:b-o5w2ir) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx#L85)):*
> ```XML
>           </FormRow>
>           <Visible visible={!!defaultValues.id}>
>             <p className="max-w-[400px]">
> ```

I think the paragraph is correct here, but the width definition here is probably not in the correct place. I assume this max width is defined so that this paragraph won't stretch the modal that much, but I think it would be more clear to just restrict the whole modal to this width (or this form part). So would probably move this max-w-[400px] to the div containing all the form rows.

One reason for this is that if we now added something else to this modal that is wider than 400px, that would mean that the modal would still stretch, the inputs would still stretch, but this paragraph would not. 
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx` line 86 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5IvOG96_l_WXB6PApC:-O5IvOGA8a39AZM6veMK:b-8zmb84) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx#L86)):*
> ```XML
>           <Visible visible={!!defaultValues.id}>
>             <p className="max-w-[400px]">
>               {t('stopDetails.maintenance.organisation.modalEditDisclaimer')}
> ```

Eventually would highlight this somehow, since it is practically a warning. But this is how it is currently in the designs so no need to do anything in this PR.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx` line 92 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Ir9wMCYgAt0jC7ig6:-O5Ir9wMCYgAt0jC7ig7:b-cfe5yi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx#L92)):*
> ```XML
>         <Row className="mt-8 space-x-5">
>           <SimpleButton
>             containerClassName="ml-auto"
> ```

NIT,  would rather have `justify-end` with the parent than auto margin



_Suggestion:_
```XML
        <Row className="mt-8 space-x-5 justify-end">
          <SimpleButton
```
___
*[`ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts` line 33 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Iwoiw4kqEDB0gKUl0:-O5IwoixAgk-9YRwr_Fz:b-6uqimb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts#L33)):*
> ```XML
>       Object.entries(state.maintainers)
>         .map(([relationshipType, organisationId]) => {
>           if (organisationId === null || organisationId === 'null') {
> ```

Really? Is it actually possible to be the string 'null' :D

**Review by Huulivoide — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889)* status: 23 of 31 files reviewed, 13 unresolved discussions (waiting on @HenrikHartiala and @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 29 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N6izVEEhS4nCLdnUx:-O5N6izVEEhS4nCLdnUy:b-iro8zx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L29)):*
> ```XML
>   const selectedOrganisation = organisations.find((o) => o?.id === value);
> 
>   const uiNameMapper = (
> ```

Tän voi nostaa ulos erilliseks funktioks.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 43 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N765H1z4TnA3Zsw-z:-O5N765H1z4TnA3Zsw0-:bnt59uj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L43)):*
> ```XML
>   });
> 
>   const sortedOrganisations = sortBy(organisations, uiNameMapper);
> ```

Tän sorttauksen ja ton alemman toOptions mäppäyksen vois kanssa ottaa ulos erilliseks funktiks, niin pysyy komponentin body vähän puhtaampana.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 53 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N7IW18HtALd8-gsEZ:-O5N7IW18HtALd8-gsE_:b-lgfbkc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L53)):*
> ```XML
>       key: CREATE_NEW_ORGANISATION_OPTION,
>       value: CREATE_NEW_ORGANISATION_OPTION,
>       render: ({ active }: { active: boolean }) => {
> ```

`() => { return foo }` → `() => (foo)`
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 73 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N7kbJ-0BuRmjegJMY:-O5N7kbJ-0BuRmjegJMZ:bteze09) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L73)):*
> ```XML
>       testId={testId ?? testIds.dropdown}
>       buttonContent={
>         selectedOrganisation ? uiNameMapper(selectedOrganisation) : '-'
> ```

uiNameMapper osaa handlata undefined arvot → `uiNameMapper(selectedOrg) ?? '-'`
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceSection.tsx` line 46 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N9V6K22q7kPyRiNr4:-O5N9V6K22q7kPyRiNr5:bn6huic) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceSection.tsx#L46)):*
> ```XML
>     toggleEditMode();
>   };
>   const formRef = useRef<ExplicitAny>(null);
> ```

Voisko tähän kirjottaa oikeen tyypin?
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx` line 23 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N9mnw2HDuyd7shqv3:-O5N9mnw2HDuyd7shqv4:bb3bxtg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx#L23)):*
> ```XML
>   name: requiredString,
>   privateContactDetails: z.object({
>     email: z.string().optional().nullable(),
> ```

z.string().email()...
___
*[`ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts` line 24 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5NAZTZ3EMq_mf1GIMl:-O5NAZTZ3EMq_mf1GIMm:bhw4s0d) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts#L24)):*
> ```XML
>   const [updateStopPlaceMutation] = useUpdateStopPlaceMutation();
> 
>   const mapStopEditChangesToTiamatDbInput = ({
> ```

Tän voinee nostaa ulos ylemmälle tasolle

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889)* status: all files reviewed, 7 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 53 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Ixp1cEdeRhUa1Rr6x:-O5NEpEvD-01NaHeq9nw:bxl3koo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L53)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Checked this with Juha, now there's fancy different styles for this option :ok_hand:
</blockquote></details>

Thanks! is good :ok_hand: 
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerFormFields.tsx` line 87 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5IlLNqCczOW9yUtBfj:-O5NFBINEU7HhqVH1HN6:bdzc7f8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintainerFormFields.tsx#L87)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Changed these to divs instead.
</blockquote></details>

Good enough :+1: 
___
*[`ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts` line 33 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5Iwoiw4kqEDB0gKUl0:-O5NFhnb0_FnOuje3-K4:b4h2xfj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a939fd8985cbc1e7068ca888c8312a0eb59592ec/ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts#L33)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Yep, gets stringified when selecting this value. Happens with other dropdowns as well.
</blockquote></details>

Ah, it's a dropdown thing. Thought at first that the value in tiamat db can be 'null'.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889)* status: all files reviewed, 7 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 29 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N6izVEEhS4nCLdnUx:-O5NLtFb72Q8l-qAxwNO:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L29)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tän voi nostaa ulos erilliseks funktioks.
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 43 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N765H1z4TnA3Zsw-z:-O5NLtou2nvUbTrKUuOY:btu5i4u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L43)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tän sorttauksen ja ton alemman toOptions mäppäyksen vois kanssa ottaa ulos erilliseks funktiks, niin pysyy komponentin body vähän puhtaampana.
</blockquote></details>

Moved the mapper but left sorting oneliner here.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 53 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N7IW18HtALd8-gsEZ:-O5NJfv9DbpqAERlQdJe:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L53)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

`() => { return foo }` → `() => (foo)`
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx` line 73 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N7kbJ-0BuRmjegJMY:-O5NKGjg-pQLUyY44_Rd:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/ChooseOrganisationDropdown.tsx#L73)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

uiNameMapper osaa handlata undefined arvot → `uiNameMapper(selectedOrg) ?? '-'`
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceSection.tsx` line 46 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N9V6K22q7kPyRiNr4:-O5NNR__811KAXKk5cfu:b-321616) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/MaintenanceSection.tsx#L46)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Voisko tähän kirjottaa oikeen tyypin?
</blockquote></details>

We seem to be using `useRef<ExplicitAny>` consistently everywhere, not changing.
___
*[`ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx` line 23 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5N9mnw2HDuyd7shqv3:-O5NKx561pHRqvag9Juq:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/components/stop-registry/stops/stop-details/maintenance/OrganisationDetailsForm.tsx#L23)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

z.string().email()...
</blockquote></details>

:thumbsup: 
___
*[`ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts` line 24 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889#-O5NAZTZ3EMq_mf1GIMl:-O5NKyv43LikitDKFGIF:b1p40k4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eb780776ad30953a143848188289919277d8a71c/ui/src/hooks/stop-registry/useEditStopMaintenanceDetails.ts#L24)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tän voinee nostaa ulos ylemmälle tasolle
</blockquote></details>

Could, but other hooks here use similar structure so keeping it here.

**Review by Huulivoide — COMMENTED** [review]
> Reviewed 7 of 30 files at r1, 2 of 8 files at r2, 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889)* status: 28 of 32 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/889)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
