### PR TITLE
DB access in cypress e2e tests

### PR DESCRIPTION
**Pull request by tk-vincit**
Also updated cypress to latest version.

Related do HSLdevcom/jore4#776

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)* status: 0 of 23 files reviewed, 10 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`.prettierignore` line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLSdU51d76iSRVpi6:-N4WLSdU51d76iSRVpi7:b8qrjgd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/.prettierignore#L15)):*
> ```ignore
> !docker/2524600800000_seed-data
> 
> test-db-manager
> ```

wouldn't the same prettier rules also work for test-db-manager...?
___
*[`cypress.config.ts` line 3 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLKo2A46aXzVNkZTB:-N4WLKo2A46aXzVNkZTC:b2usjry) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress.config.ts#L3)):*
> ```XML
> import { defineConfig } from 'cypress'
> 
> export default defineConfig({
> ```

should this file be in the root of the repo? I think it should be moved to ./cypress as it rather belongs to the cypress module only
___
*[`package.json` line 87 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLiHF1Mw8bkC5Iq3R:-N4WLiHF1Mw8bkC5Iq3S:b3q6rzo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/package.json#L87)):*
> ```JSON
>     "autoprefixer": "^10.4.2",
>     "bufferutil": "^4.0.3",
>     "cypress": "^10.1.0",
> ```

as cypress is in its own yarn workspace, let's move its dependency packages also to that workspace
___
*[`package.json` line 113 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLxFJ4SiKLSrDE4Ul:-N4WLxFJ4SiKLSrDE4Um:brhd25m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/package.json#L113)):*
> ```JSON
>   },
>   "workspaces": [
>     "test-db-manager"
> ```

cypress should also be its own workspace with its own dependencies and stuff
___
*[`README.md` line 290 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WM9G3C9emmOOp4g0q:-N4WM9G3C9emmOOp4g0r:b-n6beqt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/README.md#L290)):*
> ```Markdown
> ## Yarn workspaces
> 
> Currently we have `test-db-manager` in separate yarn workspace and jore-ui in "workspace root".
> ```

thanks for the readme!
___
*[`cypress/plugins/index.js` line 14 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WMWGk7W9Ljw9qA80G:-N4WMWGk7W9Ljw9qA80H:b-2hhee4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress/plugins/index.js#L14)):*
> ```JavaScript
> // This file runs code in node.js environment.
> 
> // import statements are supported for some reason.
> ```

did you mean "unsupported"?
___
*[`cypress/plugins/index.js` line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WMiBh965YWx7Oy0NK:-N4WMiBh965YWx7Oy0NL:b-wdk6bc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress/plugins/index.js#L46)):*
> ```JavaScript
>           // eslint-disable-next-line no-console
>           console.error(e);
>           return e;
> ```

this should rather throw the error forward instead of returning it
___
*[`test-db-manager/package.json` line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WNDyFCnprll8v2dpv:-N4WNDyG7QmI6xBgHygs:b-rjssxl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/test-db-manager/package.json#L23)):*
> ```JSON
>     "@rollup/plugin-typescript": "^8.3.2",
>     "knex": "^2.1.0",
>     "node-postgres": "^0.6.2",
> ```

is this node-postgres package in use somewhere? Or is it a peer dependency for something?
___
*[`test-db-manager/src/DbManager.ts` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WNoFcDbsB38ptW-28:-N4WNoFcDbsB38ptW-29:by3tflr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/test-db-manager/src/DbManager.ts#L9)):*
> ```XML
> export const db = require('knex')({
>   client: 'pg',
>   connection: databaseConfig,
> ```

this should definitely be a function, currently without a parameter. This would enable us in the future to use multiple database instances in case we want to run multiple cypress instances in parallel
___
*[`test-db-manager/src/DbManager.ts` line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WOnIT9gPCCgnkr6XK:-N4WOnIT9gPCCgnkr6XL:b-yajr2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/test-db-manager/src/DbManager.ts#L12)):*
> ```XML
> });
> 
> export const truncateDb = async (knex: Knex) => {
> ```

I'd rather call this parameter `db` or `dbConnection` or `conn` to clarify that it's not the global knex instance that we are using here but a single db connection

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)* status: 0 of 27 files reviewed, 10 unresolved discussions (waiting on @pallost)

___
*[`.prettierignore` line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLSdU51d76iSRVpi6:-N4XCLEN7Cy5vdcH81x8:bth4an3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/.prettierignore#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

wouldn't the same prettier rules also work for test-db-manager...?
</blockquote></details>

Well, true. I was thinking that now this is more independent package and doesn't have prettier dependency from project root, but well, this was still using same eslint as project root so these weren't consistent together.

Removed prettier here from now.
___
*[`package.json` line 87 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLiHF1Mw8bkC5Iq3R:-N4XCbtF6vBVuwm0fzCi:bhaoiab) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/package.json#L87)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as cypress is in its own yarn workspace, let's move its dependency packages also to that workspace
</blockquote></details>

Moved cypress to own workspace. Now only eslint plugin dependency comes from here.
___
*[`package.json` line 113 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLxFJ4SiKLSrDE4Ul:-N4XChmQ9ANR_xyuG16E:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/package.json#L113)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

cypress should also be its own workspace with its own dependencies and stuff
</blockquote></details>

Done.
___
*[`README.md` line 290 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WM9G3C9emmOOp4g0q:-N4WVzIlEI-OiBrJefgI:b30los1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/README.md#L290)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

thanks for the readme!
</blockquote></details>

This is very limited MPV readme, good thing if it is good enough for now.
___
*[`cypress/plugins/index.js` line 14 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WMWGk7W9Ljw9qA80G:-N4WW2dqD9eWTTLTNeYi:bb77ufg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress/plugins/index.js#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

did you mean "unsupported"?
</blockquote></details>

Yes.
___
*[`cypress/plugins/index.js` line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WMiBh965YWx7Oy0NK:-N4WZ2gfCqA_zw8DG2bu:b4c0b8x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress/plugins/index.js#L46)):*
Good point. Tried to do that and noticed that it doesn't fail test in that case though. 

https://docs.cypress.io/api/commands/task#Usage
>The task plugin event handler can return a value or a promise. The command will fail if undefined is returned or if the promise is resolved with undefined. This helps catch typos or cases where the task event is not handled.

So seems like we have to `return undefined` in that case (checked that it correctly fails test as we want).
___
*[`test-db-manager/package.json` line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WNDyFCnprll8v2dpv:-N4W_5-VCI0_yHjeWjlb:b90x61k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/test-db-manager/package.json#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

is this node-postgres package in use somewhere? Or is it a peer dependency for something?
</blockquote></details>

Good question. It was needed at some point (and even then I didn't understood why), but seems like its not needed anymore. Will remove this dependency.
___
*[`test-db-manager/src/DbManager.ts` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WNoFcDbsB38ptW-28:-N4W__4O7tiDVcpGWUGX:b-42u1nz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/test-db-manager/src/DbManager.ts#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should definitely be a function, currently without a parameter. This would enable us in the future to use multiple database instances in case we want to run multiple cypress instances in parallel
</blockquote></details>

Ok. Now this was done similarly as in hasura repo.

Do we want to be able to pass db config outside of this module at this point, or is this OK now?
___
*[`test-db-manager/src/DbManager.ts` line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WOnIT9gPCCgnkr6XK:-N4W_z19CuBAYmJB0J1o:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/test-db-manager/src/DbManager.ts#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather call this parameter `db` or `dbConnection` or `conn` to clarify that it's not the global knex instance that we are using here but a single db connection
</blockquote></details>

Done.
___
*[`cypress.config.ts` line 3 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLKo2A46aXzVNkZTB:-N4XCm_SECERFceiCnsc:b-pv3xgp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress.config.ts#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should this file be in the root of the repo? I think it should be moved to ./cypress as it rather belongs to the cypress module only
</blockquote></details>

Moved to cypress foldet. That required a bit more cypress configuration as cypress was expeting to find plenty of stuff from /cypress path relative to this file...

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)* status: 0 of 29 files reviewed, 10 unresolved discussions (waiting on @pallost)

___
*[`.prettierignore` line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLSdU51d76iSRVpi6:-N4XIO4t3vC5YRhGyznl:b-ttt64z) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/.prettierignore#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, true. I was thinking that now this is more independent package and doesn't have prettier dependency from project root, but well, this was still using same eslint as project root so these weren't consistent together.

Removed prettier here from now.
</blockquote></details>

Ok, seems like we have small issue because `prettier` doesn't read nested `.prettierignore` files as e.g. git does.
Because of that we have to either:
- Duplicate this folder specific things to the root `.prettierignore` and `test-db-manager/.prettierignore`
- Remove `prettier:check` and `prettier:write` yarn scripts from package.json of test-db-manager

Gone now with the first option, but now as I wrote this the second one starts to feel more elegant...
___
*[`package.json` line 87 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLiHF1Mw8bkC5Iq3R:-N4XJ0ld98DMr_TRhaPo:bb9tlpq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/package.json#L87)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Moved cypress to own workspace. Now only eslint plugin dependency comes from here.
</blockquote></details>

Now also eslint cypress plugin dependency is moved to cypress workspace.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)* status: 0 of 28 files reviewed, 10 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`.prettierignore` line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLSdU51d76iSRVpi6:-N4a4LbP69VPP96dSHbS:blwq7x5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/.prettierignore#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Ok, seems like we have small issue because `prettier` doesn't read nested `.prettierignore` files as e.g. git does.
Because of that we have to either:
- Duplicate this folder specific things to the root `.prettierignore` and `test-db-manager/.prettierignore`
- Remove `prettier:check` and `prettier:write` yarn scripts from package.json of test-db-manager

Gone now with the first option, but now as I wrote this the second one starts to feel more elegant...
</blockquote></details>

yeah, let's rather go with the second one :)
___
*[`.eslintrc.js` line 16 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4a4h6NCw55E_4F6Chw:-N4a4h6NCw55E_4F6Chx:b-fl2vnr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bb2824d1217987e08f98241576529458a6219ae2/.eslintrc.js#L16)):*
> ```JavaScript
>     'plugin:eslint-comments/recommended',
>     'plugin:jest/recommended',
>     'plugin:cypress/recommended',
> ```

umm, are you sure this is working now? You moved the cypress plugin to under the cypress workspace, so I don't think that you have access to it from the root.
___
*[`cypress/.eslintrc.js` line 3 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4a570Q8wOo2tQm0WMH:-N4a570Q8wOo2tQm0WMI:b-6lmvbz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ae6fd72f76a167c2586d3f7e9ca85ab26b4cfab0/cypress/.eslintrc.js#L3)):*
> ```JavaScript
> module.exports = {
>   extends: ['plugin:cypress/recommended'],
>   overrides: [
> ```

you have the exact same settings in the root .eslintrc. Do you need both?
___
*[`cypress/plugins/index.js` line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WMiBh965YWx7Oy0NK:-N4a69o92aZXJK-CwP-f:b-5nb0vi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress/plugins/index.js#L46)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Good point. Tried to do that and noticed that it doesn't fail test in that case though. 

https://docs.cypress.io/api/commands/task#Usage
>The task plugin event handler can return a value or a promise. The command will fail if undefined is returned or if the promise is resolved with undefined. This helps catch typos or cases where the task event is not handled.

So seems like we have to `return undefined` in that case (checked that it correctly fails test as we want).

</blockquote></details>

weird... well, thanks for placing the comment about this!
___
*[`cypress/plugins/index.js` line 55 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4a5fa_8hGS0moNljQf:-N4a5fa_8hGS0moNljQg:b-s9yie8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ae6fd72f76a167c2586d3f7e9ca85ab26b4cfab0/cypress/plugins/index.js#L55)):*
> ```JavaScript
>     },
>     async executeRawDbQuery(query) {
>       return db.raw(query);
> ```

This should also accept an object with binding parameters: https://knexjs.org/guide/raw.html#raw-parameter-binding
___
*[`cypress/e2e/createLine.cy.ts` line 4 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4a5vbzEjezTnRcIRnR:-N4a5vbzEjezTnRcIRnS:bq8o6vx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ae6fd72f76a167c2586d3f7e9ca85ab26b4cfab0/cypress/e2e/createLine.cy.ts#L4)):*
> ```XML
> 
> const deleteLineByLabel = (label: string) => {
>   const query = `DELETE FROM "route"."line" WHERE label='${label}'`;
> ```

I know this is only our own test setup, but I still can't let this through :D
Let's use parameter binding here: https://knexjs.org/guide/raw.html#raw-parameter-binding

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)* status: 0 of 28 files reviewed, 9 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`test-db-manager/src/DbManager.ts` line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WNoFcDbsB38ptW-28:-N4a6uhGE3KfeffMBw7n:bs5u5u4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/test-db-manager/src/DbManager.ts#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Ok. Now this was done similarly as in hasura repo.

Do we want to be able to pass db config outside of this module at this point, or is this OK now?
</blockquote></details>

good point. Maybe the most flexible would be if it looked like this...?
```
export const getDbConnection = (knexConfig = getDbConfig()) => {
  const db = Knex({client: 'pg', connection: knexConfig});
  return db;
}
```

so instead of exporting a `db` instance, should export a `getDbConnection()` function

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)* status: 0 of 28 files reviewed, 9 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`.prettierignore` line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WLSdU51d76iSRVpi6:-N4aBORS-8d7MuSA6Xzv:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/.prettierignore#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yeah, let's rather go with the second one :)
</blockquote></details>

Done.
___
*[`.eslintrc.js` line 16 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4a4h6NCw55E_4F6Chw:-N4aAhgt2zSZ8cuhAyv-:b-y1ps1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bb2824d1217987e08f98241576529458a6219ae2/.eslintrc.js#L16)):*
> Are you looking at correct diff?
I don't understand this comment. Are you looking at correct diff?
___
*[`cypress/.eslintrc.js` line 3 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4a570Q8wOo2tQm0WMH:-N4aAfOg1kLKLASCdGUk:b-fj4qd0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ae6fd72f76a167c2586d3f7e9ca85ab26b4cfab0/cypress/.eslintrc.js#L3)):*
> you have the exact same settings in the root .eslintrc. Do you need both?
Are you looking at correct diff?
___
*[`cypress/plugins/index.js` line 46 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4WMiBh965YWx7Oy0NK:-N4aAwwnAEIvbtZ9yaZL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/abcd39f87ddf7bf91333ac00b75e529c37c207ae/cypress/plugins/index.js#L46)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

weird... well, thanks for placing the comment about this!
</blockquote></details>

Done.
___
*[`cypress/e2e/createLine.cy.ts` line 4 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/219#-N4a5vbzEjezTnRcIRnR:-N4aGCE59C-aboa3Pef5:bohbt75) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ae6fd72f76a167c2586d3f7e9ca85ab26b4cfab0/cypress/e2e/createLine.cy.ts#L4)):*
> export const getDbConnection = (knexConfig = getDbConfig()) => {
>   const db = Knex({client: 'pg', connection: knexConfig});
>   return db;
> }
Ok, done. Not sure if it improves security though as we user already has raw knex istance at hand. :) Also we can't force the user to use bindings. 

I could add some kind of comment about that if you have good suggestions about it.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/219)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
