### PR TITLE
Route drawing

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/33)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Did some minor remarks.

> Reviewed 1 of 5 files at r1, 10 of 11 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-:-Ml9MrQyBvNELDjoijTQ:b405obw)* status: all files reviewed, 6 unresolved discussions (waiting on @jschummer, @pallost, and @tk-vincit)

___
*[next.config.js, line 28 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvMfFR6JlwMdtqryN5:-MkvMfFR6JlwMdtqryN6:b-f6hita) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/next.config.js#L28)):*
> ```
> api/v1/route
> ```

This has changed to `api/route/v1` in the map-matching API repository.
___
*[src/api/routing.ts, line 4 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvNCE_7GzDF141M689:-MkvNCE_7GzDF141M68A:b-r8ash1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/api/routing.ts#L4)):*
> ```
> /api/v1/route
> ```

This should be changed to `api/route/v1` to reflect the changes made to map matching backend (`wip` branch).
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 36 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvNwl4BuGvzMsRKjGw:-MkvNwl4BuGvzMsRKjGx:bzdoo5n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L36)):*
> ```
> workconsole.log
> ```

Looks like a typo.
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 39 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvOLE--AjXQBc60r4v:-MkvOLE--AjXQBc60r4w:b4dfqxw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L39)):*
> ```
> but v0.21.1 seems to require to have `@turf/area`
> ```

Good clarification. Wondered why turf was present in `package.json` but here's the reason.
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 76 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvT1yq2xXQjq14zfU1:-MkvT1yq2xXQjq14zfU2:bjl7ae3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L76)):*
> ```
> lastFeature
> ```

Maybe `lastFeatureIndex` or `lastIndex` would be more descriptive.
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 122 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvUSZR3HIq-F2cVji5:-MkvUSZR3HIq-F2cVji6:b-yr013h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L122)):*
> ```
> This
> ```

Therefore/That's why/Hence

**Review by tk-vincit — COMMENTED** [review]
Thanks for the feedback! I think I fixed all the things that you pointed out.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-:-MlEr89g6SnBcAc6m7Il:b4wj0f6)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[next.config.js, line 28 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvMfFR6JlwMdtqryN5:-MlEpe7l56q7k5P1k39a:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/next.config.js#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> api/v1/route
> ```

This has changed to `api/route/v1` in the map-matching API repository.
</blockquote></details>

Done
___
*[src/api/routing.ts, line 4 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvNCE_7GzDF141M689:-MlEpgoo0L2-X6Y5AoeM:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/api/routing.ts#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> /api/v1/route
> ```

This should be changed to `api/route/v1` to reflect the changes made to map matching backend (`wip` branch).
</blockquote></details>

Done
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 36 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvNwl4BuGvzMsRKjGw:-MlEpu1-03mRmk1-_W5G:bsac2s1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L36)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> workconsole.log
> ```

Looks like a typo.
</blockquote></details>

Good catch. Done
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 39 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvOLE--AjXQBc60r4v:-MlEqMZV-GnEpQEsMASw:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L39)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> but v0.21.1 seems to require to have `@turf/area`
> ```

Good clarification. Wondered why turf was present in `package.json` but here's the reason.
</blockquote></details>

Done.
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 76 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvT1yq2xXQjq14zfU1:-MlEq_UPE9rpZrro9Ebz:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L76)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> lastFeature
> ```

Maybe `lastFeatureIndex` or `lastIndex` would be more descriptive.
</blockquote></details>

Done.
___
*[src/components/mapgl-map/DrawRouteLayer.tsx, line 122 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MkvUSZR3HIq-F2cVji5:-MlEqiTTBuMAIzUJkQrZ:b8731f7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/566b9f2bfc6592644a3af1ac449c8af91b3a11b1/src/components/mapgl-map/DrawRouteLayer.tsx#L122)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> This
> ```

Therefore/That's why/Hence
</blockquote></details>

I think I wanted to write "Thus" but made spelling error... Anyway, fixed as you suggested.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/33)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jschummer, and @tk-vincit)

___
*[src/components/mapgl-map/Maplibre.tsx, line 63 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MlK4wdTB8aYeJb1_SHX:-MlK4wdTB8aYeJb1_SHY:b-3uhmpx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/23fc495896706242dcce61fb47e3f0cfd7d764e1/src/components/mapgl-map/Maplibre.tsx#L63)):*
> ```XML
>       getCursor={getCursor}
>       transformRequest={(url: string) => {
>         if (url.startsWith('/')) {
> ```

this should be refactored to its own function instead of having it inline

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/33)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[src/components/mapgl-map/Maplibre.tsx, line 63 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/33#-MlK4wdTB8aYeJb1_SHX:-MlKAwNTAtiPaCKAYDs7:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/23fc495896706242dcce61fb47e3f0cfd7d764e1/src/components/mapgl-map/Maplibre.tsx#L63)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should be refactored to its own function instead of having it inline
</blockquote></details>

Done.

**Pull request merged**
