### PR TITLE
Add pagination component to search results

### PR DESCRIPTION
**Pull request by HenrikHartiala**
Resolves HSLdevcom/jore4#692

Introduces generic Pagination component and applies it to the search results page.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/166)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/166)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`src/components/routes-and-lines/search/SearchResultPage.tsx` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18mysA0-ocxJZbcZLb:-N18mysA0-ocxJZbcZLc:b6pmkiz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/components/routes-and-lines/search/SearchResultPage.tsx#L52)):*
> ```XML
>           contentPerPage={contentPerPage}
>           totalCount={
>             queryParameters.filter.displayRoutes ? routes.length : lines.length
> ```

When reading this change its not evident  why we have this kind of condition here. Perhaps well-named variable defined before return statement would make this more readable? Or do we need a comment here?
___
*[`src/hooks/usePagination.ts` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18rsPaDW4pWJxbQukv:-N18rsPaDW4pWJxbQukw:b-e632uw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L8)):*
> ```XML
> const ADDITIONAL_BUTTON_AMOUNT = 2;
> 
> export const usePagination = (): {
> ```

This looke like something that would
a) be pretty straighforward to test
b) benefit from tests

So would it be possible to get small test suite for this? I can help with it if needed. Most annoying thin will probably be mocking useHistory and useUrlQuery...
___
*[`src/hooks/usePagination.ts` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18nT4F9fIyRKFOXCdF:-N18nT4G1VhCLGh7zm6G:bhgirbr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L10)):*
> ```XML
> export const usePagination = (): {
>   currentPage: number;
>   getPaginatedData: <T>(data: Array<T>, contentPerPage: number) => Array<T>;
> ```

Nice that you have typed this! :+1: 
___
*[`src/hooks/usePagination.ts` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18nkBe5nERgeinjLgq:-N18nkBe5nERgeinjLgr:bakp7jc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L12)):*
> ```XML
>   getPaginatedData: <T>(data: Array<T>, contentPerPage: number) => Array<T>;
>   setPage: (page: number) => void;
>   getRenderedPageNumber: (page: number) => number | string;
> ```

Why `number | string`?
___
*[`src/hooks/usePagination.ts` line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18rHcr7yUU7UsP6dDG:-N18rHcr7yUU7UsP6dDH:bdb7ahl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L15)):*
> ```XML
>   getDisplayedPageNumberList: (
>     currentPage: number,
>     amountOfNeighbours: number,
> ```

What does Neighbour mean in this context? Do you mean total number of items in list or what?
___
*[`src/hooks/usePagination.ts` line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18uoCLAXZuN_x7z96T:-N18uoCLAXZuN_x7z96U:b-lt2ox3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L47)):*
> ```XML
>     totalPages: number,
>   ) => {
>     const nearStart =
> ```

What do these variable names mean?



_Code quote:_
```XML
    const nearStart =
      currentPage <= amountOfNeighbours + ADDITIONAL_BUTTON_AMOUNT;
    const nearEnd =
```
___
*[`src/hooks/usePagination.ts` line 85 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18yCCxCK-9LWH-iYOI:-N18yCCxCK-9LWH-iYOJ:bs8md2d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L85)):*
> ```XML
>       totalPages,
>     );
>     const pageNumbers = Array.from(Array(totalPages).keys()).map(
> ```

I have strong feeling this could be simplified, but don't have good suggestion right now.
___
*[`src/hooks/usePagination.ts` line 93 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18v9Q8141tdwH-WmxH:-N18v9Q8141tdwH-WmxI:bppfcaj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L93)):*
> ```XML
> 
>   /** Adds zero in front of 1-9 page numbers */
>   const getRenderedPageNumber = (page: number) =>
> ```

This seems to return string | number. Would it make more sense to keep return type always the same?
___
*[`src/uiComponents/Pagination.tsx` line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18wve4Eeu1MZR9-TOM:-N18wve4Eeu1MZR9-TON:b-659o4e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/uiComponents/Pagination.tsx#L55)):*
> ```XML
>   const currentPageClassName =
>     'rounded-full border border-brand bg-brand text-white';
>   const commonClassName = 'text-1xl px-4 py-2  w-14';
> ```

Trailing spaces.
Do we really have to define width of the componen? That easily causes problems if something is changed at some point.
___
*[`src/uiComponents/Pagination.tsx` line 96 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18xRQ-7T_V5yCRkYz9:-N18xRQ-7T_V5yCRkYzA:b-gt39pt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/uiComponents/Pagination.tsx#L96)):*
> ```XML
>       {showAdditionalElementsOnEnd && (
>         <>
>           {showDotsNearEnd && <span className={commonClassName}>...</span>}
> ```

This <span /> is defiend twice, so maybe it could be extracted to own variable just before return statement.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/166)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/search/SearchResultPage.tsx` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18mysA0-ocxJZbcZLb:-N1CkJjsCTTqX9kh1dg2:bigpv38) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/components/routes-and-lines/search/SearchResultPage.tsx#L52)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

When reading this change its not evident  why we have this kind of condition here. Perhaps well-named variable defined before return statement would make this more readable? Or do we need a comment here?
</blockquote></details>

True, I'll go with a variable and let's see if thats descriptive enough
___
*[`src/hooks/usePagination.ts` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18rsPaDW4pWJxbQukv:-N1CkYx4DwvzASoEv7tB:b7ch8of) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This looke like something that would
a) be pretty straighforward to test
b) benefit from tests

So would it be possible to get small test suite for this? I can help with it if needed. Most annoying thin will probably be mocking useHistory and useUrlQuery...
</blockquote></details>

Would be happy to do some tests!
___
*[`src/hooks/usePagination.ts` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18nkBe5nERgeinjLgq:-N1CgwNT3FHkeVHWNpXe:bwj8qrx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why `number | string`?
</blockquote></details>

When I did this, I wasn't sure if it mattered that much here, because they are just for rendering, but now that you ask about it as well, I do think that I should just go for one return type here and cast numbers over 9 to string.
___
*[`src/hooks/usePagination.ts` line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18rHcr7yUU7UsP6dDG:-N1Cm1DlAgs9tCcM6fsz:bovuue1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What does Neighbour mean in this context? Do you mean total number of items in list or what?
</blockquote></details>

The neighbour here means how many page numbers are shown next to the current page before the dots.
So for example, if we are at page 7 and the amount of neighbours is 2, we would render
... 5, 6, 7, 8, 9 ... so two on each side.
Im not sure if there is a better name for this variable, but at least I could give this method and the component JSDoc explanations for the variable to make it more clear.
___
*[`src/hooks/usePagination.ts` line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18uoCLAXZuN_x7z96T:-N1Ed6t26_haNnm31kt_:b-scfl0y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L47)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What do these variable names mean?
</blockquote></details>

They refer to the "place" of currentPage. Maybe they should be named `currentPageIsNear...`
___
*[`src/hooks/usePagination.ts` line 85 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18yCCxCK-9LWH-iYOI:-N1Cp3DZ6TcePFVkIpJU:bxfmyja) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L85)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I have strong feeling this could be simplified, but don't have good suggestion right now.
</blockquote></details>

Ah, actually lodash had this `range` method, nice
___
*[`src/uiComponents/Pagination.tsx` line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18wve4Eeu1MZR9-TOM:-N1CpXyo8cxLG-c-fIPQ:b-pm3tts) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/uiComponents/Pagination.tsx#L55)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Trailing spaces.
Do we really have to define width of the componen? That easily causes problems if something is changed at some point.
</blockquote></details>

The width here was defined because some of the number combinations will create different width elements (for example `20` is much more wider than `11` simply because the text in `11` takes less space) and the page numbers are jumping around a bit because of that. 
So that is the main reason why I added the width here. (At this point I remembered grid, but that is on hold for now)

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/166)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/hooks/usePagination.ts` line 2 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1gc8wK64oLGZuTGMkX:-N1gc8wK64oLGZuTGMkY:by5lan5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/hooks/usePagination.ts#L2)):*
> ```XML
> import produce from 'immer';
> import { range } from 'lodash';
> ```

Wrong import :disappointed: 
`from 'lodash/range'` :wink: 
___
*[`src/uiComponents/Pagination.tsx` line 17 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1hjieCAbs26toAEHg0:-N1hjieCAbs26toAEHg1:b-8bgxus) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L17)):*
> ```XML
> /**
>  * Pagination component
>  * @param amountOfNeighbours determines how many page numbers are rendered on
> ```

Excellent documentation! :+1: 
___
*[`src/uiComponents/Pagination.tsx` line 65 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1hk_v05sAzibEocizP:-N1hk_v05sAzibEocizQ:b-tz4atk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L65)):*
> ```XML
>   const commonClassName = `text-1xl px-4 py-2 text-center flex-1`;
> 
>   const DOTS = <span className={commonClassName}>...</span>;
> ```

This is probably first time I'm seeing component like this with ALLCAPS in this project, so maybe I'd just call this "dots" or "dotsElement" or something like that. :)
___
*[`src/uiComponents/Pagination.spec.tsx` line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1hN9DG0kam1GWfe9ts:-N1hN9DG0kam1GWfe9tt:be3d27o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.spec.tsx#L30)):*
> ```XML
>     const nextButton = await screen.findByTestId('nextPageButtonIcon');
> 
>     expect(prevButton).toBeDisabled();
> ```

Wondering if we want to show these as disabled or not at all in these cases... Do you have any good reference components to support either approach?

Anyway, this is just a small thing, no need to change anything at this point if you dont feel like it.
___
*[`src/uiComponents/Pagination.spec.tsx` line 68 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1hNZlJ-gp_aPQY9ZmC:-N1hNZlJ-gp_aPQY9ZmD:bcahgju) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.spec.tsx#L68)):*
> ```XML
>     expect(oneButton.nodeName).toBe('SPAN');
>     expect(twoButton.nodeName).toBe('BUTTON');
>     expect(threeButton.nodeName).toBe('BUTTON');
> ```

Having html tags in CAPS feels like 90's... But this is readable so OK for me. Is this something comig from findByText selectors?



_Code quote:_
```XML
    expect(oneButton.nodeName).toBe('SPAN');
    expect(twoButton.nodeName).toBe('BUTTON');
    expect(threeButton.nodeName).toBe('BUTTON');
    expect(fourButton.nodeName).toBe('BUTTON');
    expect(fiveButton.nodeName).toBe('BUTTON');
```
___
*[`src/uiComponents/Pagination.spec.tsx` line 73 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1hNipd95b7xzUtdQ1W:-N1hNipd95b7xzUtdQ1X:bicwrqv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.spec.tsx#L73)):*
> ```XML
>   });
> 
>   test('should render dots next to first page butotn', async () => {
> ```

typo: butotn

**Review by tk-vincit — CHANGES_REQUESTED** [review]
Nice tests!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-:-N1m2QRN1wWjc2sCrTcK:b10ca2m)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/search/SearchResultPage.tsx` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18mysA0-ocxJZbcZLb:-N1ldmw1-v82ylfs8d-o:bxx6oha) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/components/routes-and-lines/search/SearchResultPage.tsx#L52)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

True, I'll go with a variable and let's see if thats descriptive enough
</blockquote></details>

Let's continue discussion in another thread as this is now in misleading place.
___
*[`src/components/routes-and-lines/search/SearchResultPage.tsx` line 22 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1ldshB7hKZkVjX3j2d:-N1ldshB7hKZkVjX3j2e:b4rfudi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/components/routes-and-lines/search/SearchResultPage.tsx#L22)):*
> ```XML
>   const displayedRoutes = getPaginatedData(routes, contentPerPage);
> 
>   const totalCountOfDisplayedData = queryParameters.filter.displayRoutes
> ```

As discussed in slack this is still not optimal.
___
*[`src/hooks/usePagination.ts` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18rsPaDW4pWJxbQukv:-N1le38rEx-NcjAgWNZ4:btojbfd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L8)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Would be happy to do some tests!
</blockquote></details>

Great!
___
*[`src/hooks/usePagination.ts` line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18rHcr7yUU7UsP6dDG:-N1leBiY1hajiPjfSKPX:b-3xefuf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L15)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The neighbour here means how many page numbers are shown next to the current page before the dots.
So for example, if we are at page 7 and the amount of neighbours is 2, we would render
... 5, 6, 7, 8, 9 ... so two on each side.
Im not sure if there is a better name for this variable, but at least I could give this method and the component JSDoc explanations for the variable to make it more clear.
</blockquote></details>

Still a bit confused with the name, but as this is now documented and I don't have better suggestions let's decide this is fine. :smile: 
___
*[`src/hooks/usePagination.spec.tsx` line 17 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1lfU5i74iRP1I6Vbqy:-N1lfU5i74iRP1I6Vbqz:b-33b46s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/hooks/usePagination.spec.tsx#L17)):*
> ```XML
> 
> const urlQueryMock = useUrlQuery as jest.Mock;
> const hookForNames = renderHook(() => usePagination());
> ```

Btw, I guess all of these could be simplified like this:
`renderHook(() => myHook());` -> `renderHook(myHook);`
___
*[`src/uiComponents/Pagination.tsx` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1m01dGAv_anXi52io3:-N1m01dGAv_anXi52io4:bsyleut) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L27)):*
> ```XML
>   amountOfNeighbours = DEFAULT_AMOUNT_OF_NEIGHBOURS,
>   totalCount,
>   contentPerPage = DEFAULT_CONTENT_PER_PAGE,
> ```

itemsPerPage and DEFAULT_ITEMS_PER_PAGE could be a bit clearer

and if you change this, then totalCount -> totalItemsCount might be good idea too.
___
*[`src/uiComponents/Pagination.tsx` line 73 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1m0zje8vgDxRJo5Ogg:-N1m0zje8vgDxRJo5Ogh:b-xf4oh6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L73)):*
> ```XML
>         className="flex-1"
>         onClick={() => setPage(currentPage - 1)}
>         disabled={currentPage === 1}
> ```

Plase use same condition here and on ternary of `icon`, so `onFirstPage` or `currentPage === 1` on both places.
___
*[`src/uiComponents/Pagination.tsx` line 100 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1m1IBo1ZMecuVzMpCL:-N1m1IBo1ZMecuVzMpCM:b-l8i7gl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L100)):*
> ```XML
>             type="button"
>             key={pageNumber}
>             className={`${commonClassName}`}
> ```

Template string not needed :)

Also seems you have this button here couple of times so it could be extracted to local component, but not sure if that is worth it. Decide by yourself.
___
*[`src/uiComponents/Pagination.spec.tsx` line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1hN9DG0kam1GWfe9ts:-N1m1yWAAQopiaqOUuje:bevsic7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.spec.tsx#L30)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Figma had this one as `disabled`. And I personally do like it better when it is not hidden.
</blockquote></details>

:heavy_check_mark:

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/166)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/hooks/usePagination.ts` line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N18rHcr7yUU7UsP6dDG:-N1mbk41CIxz5F95psac:b-pgdm9b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/78517614c3de1668ac080d245577bef2f22c2c0d/src/hooks/usePagination.ts#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Still a bit confused with the name, but as this is now documented and I don't have better suggestions let's decide this is fine. :smile: 
</blockquote></details>

I've also seen "siblings" used in this context, since it is also used to indicate the HTML element which is next to another element. But not sure if it is any better name here. I think that even with "sibling" I would need to check the documentation.
___
*[`src/hooks/usePagination.spec.tsx` line 17 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1lfU5i74iRP1I6Vbqy:-N1meADs45zRdyQK_j52:b-1ujfa8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/hooks/usePagination.spec.tsx#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Btw, I guess all of these could be simplified like this:
`renderHook(() => myHook());` -> `renderHook(myHook);`
</blockquote></details>

Ah, true.
___
*[`src/uiComponents/Pagination.tsx` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1m01dGAv_anXi52io3:-N1mdrR5DK_M5otfb_UA:b-frcmt7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L27)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

itemsPerPage and DEFAULT_ITEMS_PER_PAGE could be a bit clearer

and if you change this, then totalCount -> totalItemsCount might be good idea too.
</blockquote></details>

Ah yes thank you! I was thinking that there must be a better word than 'content' :D 
___
*[`src/uiComponents/Pagination.tsx` line 73 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1m0zje8vgDxRJo5Ogg:-N1mgtW93mSNI8iKiahL:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L73)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Plase use same condition here and on ternary of `icon`, so `onFirstPage` or `currentPage === 1` on both places.
</blockquote></details>

:+1: 
___
*[`src/uiComponents/Pagination.tsx` line 100 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1m1IBo1ZMecuVzMpCL:-N1mjdwj-awEoJzIqHQS:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L100)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Template string not needed :)

Also seems you have this button here couple of times so it could be extracted to local component, but not sure if that is worth it. Decide by yourself.
</blockquote></details>

:+1:

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/166)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`src/components/routes-and-lines/search/SearchResultPage.tsx` line 22 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1mo8Ks9rkft3Gau6HA:-N1mo8Ks9rkft3Gau6HB:b6x1xi4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c3b8a9b58e514c5574269fb4a2fcf1a405cc2d40/src/components/routes-and-lines/search/SearchResultPage.tsx#L22)):*
> ```XML
>   const displayedRoutes = getPaginatedData(routes, itemsPerPage);
> 
>   const totalCountOfDisplayedData = queryParameters.filter.displayRoutes
> ```

For next PR: "totalItems" ?
___
*[`src/uiComponents/Pagination.tsx` line 65 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1hk_v05sAzibEocizP:-N1mnSGxAARFkkLmFiJO:b-obehqh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L65)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Clear solution :+1: 
___
*[`src/uiComponents/Pagination.tsx` line 100 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1m1IBo1ZMecuVzMpCL:-N1mnddMEFdby-E8zvL6:bcv502w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3769c4cd04389a30e2f6b06393d1c60e9f090591/src/uiComponents/Pagination.tsx#L100)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Nice :+1: 
___
*[`src/uiComponents/Pagination.tsx` line 22 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/166#-N1mnH378IQvY68ZdsVE:-N1mnH378IQvY68ZdsVF:bkcfk2k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c3b8a9b58e514c5574269fb4a2fcf1a405cc2d40/src/uiComponents/Pagination.tsx#L22)):*
> ```XML
>  * we render ... 6 7 8 ... (default = 2)
>  * @param totalItemsCount the total count of the data which is being paginated
>  * @param itemsPerPage how much items there is per page (default=10)
> ```

For the next pr: "much items" -> "many items" :wink: (and "there is per page" -> "there are in one page", right?)

**Pull request merged**
