### PR TITLE
Add arrows to drawn route on map

### PR DESCRIPTION
**Pull request by eleksi**
Resolves HSLdevcom/jore4#647
Resolves HSLdevcom/jore4#898

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/381)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/381)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`ui/src/components/map/Maplibre.tsx` line 99 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO2eMQDQfrFgqp-bgj:-NFO2eMQDQfrFgqp-bgk:b-rbwcxm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/Maplibre.tsx#L99)):*
> ```XML
> 
>   // Load arrow image
>   useEffect(() => {
> ```

let's not bloat the Maplibre component anymore with such stuff that does not strictly belong there. Would it be possible to add this image loading section within the LineArrowLayer?

Or would it be better to create a new layer for loading visual elements like this? Something like `components/map/VisualElements.tsx`. That component could get the map ref and do this image loading itself.

Anyhow, this clearly doesn't belong here, but I don't know enough about map handling to offer you a good solution of splitting such logic to a separate component

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/381)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/map/routes/LineArrowLayer.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO4CxcA-W01kxaCzPC:-NFO4CxcA-W01kxaCzPD:b-lln0ua) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/routes/LineArrowLayer.tsx#L35)):*
> ```XML
>         layout={{ ...defaultLayout, ...layout }}
>         beforeId={beforeId}
>         minzoom={12}
> ```

I don't think `minzoom` belongs to the generic component. This should be defined in the RouteGeometryLayer and propagated from there to this component
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 45 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO3leg1a_5cz3Lbf6G:-NFO3leg1a_5cz3Lbf6H:bjxdnh9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L45)):*
> ```XML
>     <>
>       <LinePolygonLayer
>         layerId={layerId}
> ```

`${layerId}_polygon`?
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO3bon-M0LU1pSG9nK:-NFO3bon-M0LU1pSG9nL:b-mxy61n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L51)):*
> ```XML
>       />
>       <LineArrowLayer
>         layerId={`arrows_for_${layerId}`}
> ```

`${layerId}_arrows`?

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/381)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 45 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO3leg1a_5cz3Lbf6G:-NGMPoth4OuJy6CesoJB:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L45)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`${layerId}_polygon`?
</blockquote></details>

Done.
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO3bon-M0LU1pSG9nK:-NGMPoUY40DIcmy_C2IJ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L51)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`${layerId}_arrows`?
</blockquote></details>

Done.
___
*[`ui/src/components/map/Maplibre.tsx` line 99 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO2eMQDQfrFgqp-bgj:-NGLdnyP4Br3J8EkGHdm:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/Maplibre.tsx#L99)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's not bloat the Maplibre component anymore with such stuff that does not strictly belong there. Would it be possible to add this image loading section within the LineArrowLayer?

Or would it be better to create a new layer for loading visual elements like this? Something like `components/map/VisualElements.tsx`. That component could get the map ref and do this image loading itself.

Anyhow, this clearly doesn't belong here, but I don't know enough about map handling to offer you a good solution of splitting such logic to a separate component
</blockquote></details>

Done.
___
*[`ui/src/components/map/routes/LineArrowLayer.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NFO4CxcA-W01kxaCzPC:-NGLe7_HDC7x43qd6eRM:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7417f5501aecb51cc61506ccaecbb265aeb7d05e/ui/src/components/map/routes/LineArrowLayer.tsx#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think `minzoom` belongs to the generic component. This should be defined in the RouteGeometryLayer and propagated from there to this component
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/381)* status: 2 of 10 files reviewed, 5 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/VisualElements.tsx` line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NHOK5yD6EJ9rUTovpyA:-NHOK5yD6EJ9rUTovpyB:bwxn9ky) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2af3f86803c820b1f60bb2a547c219e2c31154eb/ui/src/components/map/VisualElements.tsx#L4)):*
> ```XML
> import { MapContext } from 'react-map-gl';
> 
> export const VisualElements: React.FC = () => {
> ```

Not sure how to solve this, but now this is a component which always returns `null`. Is there another way to do this? Maybe move the logic in hook?
___
*[`ui/src/components/map/VisualElements.tsx` line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NHOJAzd2DSDgHQA7mnk:-NHOJAzd2DSDgHQA7mnl:b-kl7w9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2af3f86803c820b1f60bb2a547c219e2c31154eb/ui/src/components/map/VisualElements.tsx#L8)):*
> ```XML
> 
>   // Load arrow image
> ```

This newline could be removed. Now it kind of looks like that some code line has been removed but the comment is still remaining
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NHOZod2B95VUce_uxm-:-NHOZod2B95VUce_uxm0:bs01ysy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2af3f86803c820b1f60bb2a547c219e2c31154eb/ui/src/components/map/routes/RouteGeometryLayer.tsx#L30)):*
> ```XML
>   const linePaint: mapboxgl.LinePaint = {
>     'line-color': color,
>     'line-width': isHighlighted ? 9 : 8,
> ```

Not particularly this PR's scope, but the 9 and 8 could be constants. Something like `const IS_HILIGHTED_WIDTH`,` const DEFAULT_WIDTH` etc, but no changes required now here.

**Review by HenrikHartiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/381)* status: 1 of 11 files reviewed, 5 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/map/mapHelpers.tsx` line 3 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/381#-NHPJllp4ANdRYEClpVn:-NHPJllqD9HcsdCN9zsH:b57xhu1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ee43adad176c6b0e4777b3e248c25f77b562e346/ui/src/components/map/mapHelpers.tsx#L3)):*
> ```XML
> import { MapRef } from 'react-map-gl';
> 
> export const loadMapAssets = (mapRef: React.RefObject<MapRef>) => {
> ```

This should maybe be in `utils`

**Pull request merged**
