### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)

### CODE REVIEW

**Review by haphut — APPROVED** [review]
Thanks for doing this!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-:-M_V3JZC2d6Et02Bz4JY:bxgavm9)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @haphut)

___
*[.github/workflows/cd.yml, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-M_V33PE3uzGxySurIBP:-M_V33PE3uzGxySurIBQ:b-xt25an) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/93717ec98e7358f776477bda718249aa2ae9d4e5/.github/workflows/cd.yml#L20)):*
> ```YAML
> 
>       - name: Extract branch name to env variable
>         run: | # In pull requests
> ```

Maybe move the comment down to the next line to align with the other code.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @haphut)

___
*[.github/workflows/cd.yml, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-M_V33PE3uzGxySurIBP:-M_V9DRVC2mQglih9Uyw:b-80tlqx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/93717ec98e7358f776477bda718249aa2ae9d4e5/.github/workflows/cd.yml#L20)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Maybe move the comment down to the next line to align with the other code.
</blockquote></details>

Sure!

**Review by haphut — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tk-vincit)

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: all files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[.github/workflows/cd.yml, line 32 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-Ma2KaGH84hSI29cZoMQ:-Ma2KaGH84hSI29cZoMR:b1xlx2y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7ec9db3ee7f259f39daa2adc56d00c43930a3f99/.github/workflows/cd.yml#L32)):*
> ```YAML
>         run: |
>           # Docker Hub uses lowercase so use a bashism to convert.
>           echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
> ```

could you put a clarifying comment here that this will actually resolve to the `hsldevcom/jore4-ui` docker image name?

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: all files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[.github/workflows/cd.yml, line 32 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-Ma2KaGH84hSI29cZoMQ:-Ma8p0xs2o6ytpwxPkTr:b-lli14i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7ec9db3ee7f259f39daa2adc56d00c43930a3f99/.github/workflows/cd.yml#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you put a clarifying comment here that this will actually resolve to the `hsldevcom/jore4-ui` docker image name?
</blockquote></details>

Rather no. The whole idea behind this was to decouple ci pipeline definition from individual repository details, and that kind of comment would ruin that.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-MaDEdcn1uebEJzlqP62:b-ig0z7m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
> ```YAML
>           # In pull requests
>           BRANCH_NAME="${GITHUB_HEAD_REF}"
>           [ ${BRANCH_NAME} = "" ] && {
> ```

actually, this correct operator is `==`

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @haphut, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-MaDEr5M7HqR1uRGuM7N:b-vrsn42) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually, this correct operator is `==`
</blockquote></details>

...or maybe even that doesn't work... you should test this script from a separate branch, without a pull request

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[.github/workflows/cd.yml, line 32 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-Ma2KaGH84hSI29cZoMQ:-MaDFlaG7OopEx3PvCHI:b-cf4rc9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7ec9db3ee7f259f39daa2adc56d00c43930a3f99/.github/workflows/cd.yml#L32)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Rather no. The whole idea behind this was to decouple ci pipeline definition from individual repository details, and that kind of comment would ruin that.
</blockquote></details>

the github repository name does not necessarily match with the docker image name and it would not be useful to enforce that
___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-MaDG1X-DasNFi1p2iY6:b35e941) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

...or maybe even that doesn't work... you should test this script from a separate branch, without a pull request
</blockquote></details>

this seems to work in my own environment: `[[ ${BRANCH_NAME} == "" ]] && {`

**Review by haphut — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @haphut and @pallost)

___
*[.github/workflows/cd.yml, line 32 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-Ma2KaGH84hSI29cZoMQ:-MaTOn0u6QDe_AcTqxve:bxcs6p7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7ec9db3ee7f259f39daa2adc56d00c43930a3f99/.github/workflows/cd.yml#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the github repository name does not necessarily match with the docker image name and it would not be useful to enforce that
</blockquote></details>

I agree that the GitHub repository name does not have to match the Docker Hub repository name. I think using that flexibility hurts us, though.

I think we should have one GitHub repository per Docker Hub repository. And having to guess the name of the GitHub repository from the Docker Hub repository or vice versa wastes time. E.g. we have `jore4-backend` and `jore4-frontend` in Docker Hub with quite surprising origins. I think we should have neither of those Docker Hub repositories.

I would by default enforce a 1:1 mapping between the names and in special cases use a different yaml. That way we can reuse this same yaml in all jore4 component github repositories.
___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-MaTNmR9Ee3RkdrUN8eZ:b-h3c6fx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this seems to work in my own environment: `[[ ${BRANCH_NAME} == "" ]] && {`
</blockquote></details>

https://github.com/HSLdevcom/jore4-hasura/runs/2565173684?check_suite_focus=true#step:3:9 says `/home/runner/work/_temp/e237727c-4eb2-466c-9006-46d1b47eea7f.sh: line 2: [: ==: unary operator expected`

So the fix for this line could be the POSIX way:
`[ "${BRANCH_NAME}" = "" ] && {`
or the bash way as @pallost suggested:
`[[ ${BRANCH_NAME} = "" ]] && {`

Either is fine for me. But, once more due to my mistake, the current code is less robust because of the lack of quotes in the POSIX way.

Something else is likely wrong here as well. Check out: https://github.com/HSLdevcom/jore4-hasura/runs/2654304202?check_suite_focus=true#step:7:9 . It seems that the `tr` command later on outputs a single `-` when pushing to `main`. I did not yet figure out what's wrong.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

___
*[.github/workflows/cd.yml, line 32 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-Ma2KaGH84hSI29cZoMQ:-MaXA7l58fUBjYuIHLbs:b-yfhego) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7ec9db3ee7f259f39daa2adc56d00c43930a3f99/.github/workflows/cd.yml#L32)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I agree that the GitHub repository name does not have to match the Docker Hub repository name. I think using that flexibility hurts us, though.

I think we should have one GitHub repository per Docker Hub repository. And having to guess the name of the GitHub repository from the Docker Hub repository or vice versa wastes time. E.g. we have `jore4-backend` and `jore4-frontend` in Docker Hub with quite surprising origins. I think we should have neither of those Docker Hub repositories.

I would by default enforce a 1:1 mapping between the names and in special cases use a different yaml. That way we can reuse this same yaml in all jore4 component github repositories.
</blockquote></details>

OK, let's strive for 1:1 mapping between the github repo name and the docker image name and only deviate from that when absolutely necessary :+1:

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut)

___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-MaXAN3h6T85CuOUpwr_:b-3srf8f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

https://github.com/HSLdevcom/jore4-hasura/runs/2565173684?check_suite_focus=true#step:3:9 says `/home/runner/work/_temp/e237727c-4eb2-466c-9006-46d1b47eea7f.sh: line 2: [: ==: unary operator expected`

So the fix for this line could be the POSIX way:
`[ "${BRANCH_NAME}" = "" ] && {`
or the bash way as @pallost suggested:
`[[ ${BRANCH_NAME} = "" ]] && {`

Either is fine for me. But, once more due to my mistake, the current code is less robust because of the lack of quotes in the POSIX way.

Something else is likely wrong here as well. Check out: https://github.com/HSLdevcom/jore4-hasura/runs/2654304202?check_suite_focus=true#step:7:9 . It seems that the `tr` command later on outputs a single `-` when pushing to `main`. I did not yet figure out what's wrong.
</blockquote></details>

for me at least the POSIX way did not work at first or maybe I copy-pasted this wrong...? :)

**Review by haphut — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-MabqfuhBTO5mRoRezYL:b-5zi0xk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

for me at least the POSIX way did not work at first or maybe I copy-pasted this wrong...? :)
</blockquote></details>

I'm fine with either fix for the test. :)

This error in https://github.com/HSLdevcom/jore4-hasura/runs/2654304202?check_suite_focus=true#step:7:9 still needs figuring out.

(To check if I had misunderstood, I wrote a POSIX and a bash script. I got the same output from both when `sh` was implemented by `bash`. Also `ash` from busybox runs the POSIX one fine:)

```sh
#!/bin/sh

foo=""
[ "${foo}" = "" ] && {
  echo "test true 1"
}
echo "done 1"

bar=
[ "${bar}" = "" ] && {
  echo "test true 2"
}
echo "done 2"

[ "${baz}" = "" ] && {
  echo "test true 3"
}
echo "done 3"
```

```bash
#!/bin/bash

foo=""
[[ ${foo} = "" ]] && {
  echo "test true 1"
}
echo "done 1"

bar=
[[ ${bar} = "" ]] && {
  echo "test true 2"
}
echo "done 2"

[[ ${baz} = "" ]] && {
  echo "test true 3"
}
echo "done 3"
```

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-Maht9L95UZWyp6em7rS:b-ilm3xr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I'm fine with either fix for the test. :)

This error in https://github.com/HSLdevcom/jore4-hasura/runs/2654304202?check_suite_focus=true#step:7:9 still needs figuring out.

(To check if I had misunderstood, I wrote a POSIX and a bash script. I got the same output from both when `sh` was implemented by `bash`. Also `ash` from busybox runs the POSIX one fine:)

```sh
#!/bin/sh

foo=""
[ "${foo}" = "" ] && {
  echo "test true 1"
}
echo "done 1"

bar=
[ "${bar}" = "" ] && {
  echo "test true 2"
}
echo "done 2"

[ "${baz}" = "" ] && {
  echo "test true 3"
}
echo "done 3"
```

```bash
#!/bin/bash

foo=""
[[ ${foo} = "" ]] && {
  echo "test true 1"
}
echo "done 1"

bar=
[[ ${bar} = "" ]] && {
  echo "test true 2"
}
echo "done 2"

[[ ${baz} = "" ]] && {
  echo "test true 3"
}
echo "done 3"
```
</blockquote></details>

Don't know if choosing either one over another makes any difference, but changed this to bash way.

CI and CD pipelines seems to be passing now.

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-Mb5uPC06FZibx7toYky:bmvud7c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Don't know if choosing either one over another makes any difference, but changed this to bash way.

CI and CD pipelines seems to be passing now.
</blockquote></details>

I think this will break on the `main` push workflow run once merged but I don't mind merging first and debugging then.

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

___
*[.github/workflows/cd.yml, line 23 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-MaDEdcn1uebEJzlqP61:-Mb5v0ms3ccRzL25X8KZ:bb6ywmx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25d6c6c9073a89864095feced65603f32fe04583/.github/workflows/cd.yml#L23)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

I think this will break on the `main` push workflow run once merged but I don't mind merging first and debugging then.
</blockquote></details>

LGTM

**Review by haphut — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/10#-:-Mb5vIm5AQQrsF50feGX:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @haphut and @pallost)

**Pull request merged**
