### PR TITLE
Rename and refactor mapItemCreator

### PR DESCRIPTION
**Pull request by HenrikHartiala**
Resolves HSLdevcom/jore4#970
This pageObject is actually ModalMap's pageObject, because it includes all these actions. The responsibilites have been refactored as well, now for example ConfirmSaveForm is responsible for filling the form.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)

### CODE REVIEW

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`cypress/pageObjects/ModalMap.ts` line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkOAb64LgdpELcDtBm:-NIkOAb64LgdpELcDtBn:b51cu6a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fc0b9ba2d130c88412de7d76a147578b193907bd/cypress/pageObjects/ModalMap.ts#L55)):*
> ```XML
> 
>     this.stopForm.fillStopForm(stopFormInfo);
>     this.confirmSaveForm.fillConfirmSaveForm({
> ```

Could you use confirmSaveFormInfo instead of the separate arguments? The same way that stopFormInfo interface is used in fillStopForm? Applies to many other parts in the code as well.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @sr-vala)

___
*[`cypress/pageObjects/ModalMap.ts` line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkOAb64LgdpELcDtBm:-NIkaDI_42nSqUHjnwvz:bwt6tsb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fc0b9ba2d130c88412de7d76a147578b193907bd/cypress/pageObjects/ModalMap.ts#L55)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Could you use confirmSaveFormInfo instead of the separate arguments? The same way that stopFormInfo interface is used in fillStopForm? Applies to many other parts in the code as well.
</blockquote></details>

Ah yes, Good point!. I'll use confirmSaveFormInfo on the upper level.

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala and @sr-vala)

___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 67 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkpzNl5oT9-AAS3doL:-NIkpzNl5oT9-AAS3doM:b-2nznps) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L67)):*
> ```XML
>         this.setAsStandard();
>         break;
>       default:
> ```

This should never happen (unless new priority is added) and is error situation
-> I would throw new error here: 
`throw new Error('Unknown priority "${priority}"')`
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 71 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkp2FF4Rv0NuCSBLwa:-NIkp2FF4Rv0NuCSBLwb:bz178q7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L71)):*
> ```XML
>   };
> 
>   fillConfirmSaveForm(values: ConfirmSaveFormInfo) {
> ```

This is already inside "ConfirmSaveForm" page object, so does "ConfirmSaveForm" postfix offer any valuable info to the reader?
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 72 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkpX6P125nO0Wj4Upx:-NIkpX6P125nO0Wj4Upy:bo0mwxe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L72)):*
> ```XML
> 
>   fillConfirmSaveForm(values: ConfirmSaveFormInfo) {
>     this.setPriority(values.priority);
> ```

I was also thinking that should these be all optional and written like

```
if (priority) {
  this.setPriority(...)
}
```

but maybe supporting that is unnecessary as it doesn't make much sense to fill this form only partially. :thinking:

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 67 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkpzNl5oT9-AAS3doL:-NIkx0EoDF7cJeEG1DNn:b-thabms) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L67)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This should never happen (unless new priority is added) and is error situation
-> I would throw new error here: 
`throw new Error('Unknown priority "${priority}"')`
</blockquote></details>

Ah true! Did not think of throwing error, I'll add that thanks!
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 71 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkp2FF4Rv0NuCSBLwa:-NIkyMPbACq6IO5JOx8x:b-eaf835) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L71)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This is already inside "ConfirmSaveForm" page object, so does "ConfirmSaveForm" postfix offer any valuable info to the reader?
</blockquote></details>

Yeah maybe not. I'll also remove it from stopForm (fillStopForm) 
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 72 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkpX6P125nO0Wj4Upx:-NIkyce-53hOdnljRlbZ:bexgc8j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L72)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I was also thinking that should these be all optional and written like

```
if (priority) {
  this.setPriority(...)
}
```

but maybe supporting that is unnecessary as it doesn't make much sense to fill this form only partially. :thinking: 


</blockquote></details>

Maybe we would want to fill this form only partially, if we want to test form validity (informs user that some fields are not filled), but those can be done separately or modify this if needed.

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala and @sr-vala)

___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 67 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkpzNl5oT9-AAS3doL:-NIljcaa3bwbBvRAv727:bg40yko) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L67)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah true! Did not think of throwing error, I'll add that thanks!
</blockquote></details>

Missing trailing `"` :wink: 
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 72 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkpX6P125nO0Wj4Upx:-NIljm-WCzLQGFdgbvvj:b-6goikl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L72)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Maybe we would want to fill this form only partially, if we want to test form validity (informs user that some fields are not filled), but those can be done separately or modify this if needed.
</blockquote></details>

True that. But this is good enough for now. :+1: 
___
*[`cypress/pageObjects/ModalMap.ts` line 39 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIlkjkb8kDLhJWw4lm9:-NIlkjkb8kDLhJWw4lmA:bt0mure) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/55386be2da2d7b699f66e29893082abf46e1e5ff/cypress/pageObjects/ModalMap.ts#L39)):*
> ```XML
>     stopFormInfo,
>     stopPoint,
>     confirmSaveFormInfo,
> ```

Started to thin about ordering of these params (even though these are inside object, which is "unordered"): it would make more sense to define "formInfo" properties within each other, or even nested into e.g. "form" property, as they are logically coupled together. In the other hand "stopPoint" is no way related to form contents. Same applies also to `createStopAtLocation` function.



_Code quote:_
```XML
    stopFormInfo,
    stopPoint,
    confirmSaveFormInfo,
```

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/420)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @sr-vala and @tk-vincit)

___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 67 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIkpzNl5oT9-AAS3doL:-NIpkAsfEr8Tjy8tjlK2:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/35897a0db10adda0d0088b8b1cd3122200ca10ff/cypress/pageObjects/ConfirmSaveForm.ts#L67)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Missing trailing `"` :wink: 
</blockquote></details>

Done.
___
*[`cypress/pageObjects/ModalMap.ts` line 39 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/420#-NIlkjkb8kDLhJWw4lm9:-NIpkvyt2UMlG9HRAuM-:b3f4dph) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/55386be2da2d7b699f66e29893082abf46e1e5ff/cypress/pageObjects/ModalMap.ts#L39)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Started to thin about ordering of these params (even though these are inside object, which is "unordered"): it would make more sense to define "formInfo" properties within each other, or even nested into e.g. "form" property, as they are logically coupled together. In the other hand "stopPoint" is no way related to form contents. Same applies also to `createStopAtLocation` function.
</blockquote></details>

Like discussed, I will reorder these in this PR, and do a separate PR where these will be refactored in to a more sensible structure.

**Pull request merged**
