### PR TITLE
Move route create/edit/delete functionality to own component

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/177)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
It's a nice step forward. The MapFooter doesn't belong to the RouteEditor at all, but that can be the next step for the refactoring.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/177#-:-N1vwZHb5mOIiNeiD0Wk:b-rquy9x)* status: 0 of 2 files reviewed, all discussions resolved

**Review by pallost — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/177#-:-N1vwhrb4WUQa2Dvoogr:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/177)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/components/map/routes/RouteEditor.tsx` line 117 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/177#-N2G7_ag5A7SY7TNNEMa:-N2G7_ag5A7SY7TNNEMb:bjrzdlz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bb23ba2e3acb77a70b3a62687685a4903a59656f/src/components/map/routes/RouteEditor.tsx#L117)):*
> ```XML
> 
>     // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>     return response.data!.insert_route_route_one!;
> ```

should rather return `response.data?.insert_route_route_one;`
___
*[`src/components/map/routes/RouteEditor.tsx` line 217 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/177#-N2G8Wib1qHc0LI7LhQG:-N2G8Wib1qHc0LI7LhQH:b-2te89o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bb23ba2e3acb77a70b3a62687685a4903a59656f/src/components/map/routes/RouteEditor.tsx#L217)):*
> ```XML
>   };
> 
>   useImperativeHandle(externalRef, () => ({
> ```

you could simplify this as:
```
useImperativeHandle(externalRef, () => ({
onDrawRoute,
onEditRoute,
onDeleteRoute,
onCancel,
onSave,
}));
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/177)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`src/components/map/routes/RouteEditor.tsx` line 117 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/177#-N2G7_ag5A7SY7TNNEMa:-N2GJjZ70Nfadii1a6-j:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bb23ba2e3acb77a70b3a62687685a4903a59656f/src/components/map/routes/RouteEditor.tsx#L117)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should rather return `response.data?.insert_route_route_one;`
</blockquote></details>

Done.
___
*[`src/components/map/routes/RouteEditor.tsx` line 217 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/177#-N2G8Wib1qHc0LI7LhQG:-N2GJk4cA9ItqN4PrjJZ:b-3zplx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bb23ba2e3acb77a70b3a62687685a4903a59656f/src/components/map/routes/RouteEditor.tsx#L217)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could simplify this as:
```
useImperativeHandle(externalRef, () => ({
onDrawRoute,
onEditRoute,
onDeleteRoute,
onCancel,
onSave,
}));
```
</blockquote></details>

Oh, right. :D That is what you get when you just copy paste and don't think too much..

**Pull request merged**
