### PR TITLE
Extract business logics to hooks

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/hooks/useCreateLine.ts, line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZPypWE6jYPZWqH-xI:-MxZPypWE6jYPZWqH-xJ:b-6peaox) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L12)):*
> ```XML
> } from '../utils';
> 
> export const useCreateLine = () => {
> ```

I'd suggest we make a clear flow for these business logic hooks:
1. based on the inputs, let's create all the changes that will happen on the backend and validate them (e.g. will the validity periods collide)
2. map these changes to graphql mutation variables
3. execute these changes in the graphql mutation.
Here's an example of what I've been thinking: https://github.com/HSLdevcom/jore4-ui/blob/bus-stop-dragging/src/hooks/useEditStop.ts
___
*[src/hooks/useCreateLine.ts, line 17 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZPBIQ9-911XLlgWi9:-MxZPBIQ9-911XLlgWiA:b-xf7mot) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L17)):*
> ```XML
> 
>   const worker = async (state: FormState, onSuccess?: () => void) => {
>     const variables = mapToObject({
> ```

This should be a separate mapping function in itself. It can be reused both when creating or when editing an exiting line.



_Code quote:_
```XML
    const variables = mapToObject({
      label: state.label,
      name_i18n: state.finnishName,
      primary_vehicle_mode: state.primaryVehicleMode,
      priority: state.priority,
      validity_start: mapDateInputToValidityStart(state.validityStart),
      validity_end: mapDateInputToValidityEnd(
        state.validityEnd,
        state.indefinite,
      ),
    });
```
___
*[src/hooks/useCreateLine.ts, line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZPNqr5sCKHQ9UfXuu:-MxZPNqr5sCKHQ9UfXuv:bkpq2sp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L30)):*
> ```XML
> 
>     try {
>       const result = await mutateFunction(mapToVariables(variables));
> ```

I wouldn't show toast messages within the hook workers: I think it's rather the responsibility of the caller that how to react to success/error

In case of success, it should return with the result. In case of error it could throw an exception that could be caught and handled on the caller side.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/hooks/useCreateLine.ts, line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZSoGcBFqadsbQL5Pa:-MxZSoGcBFqadsbQL5Pb:b-axb9ke) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L16)):*
> ```XML
>   const [mutateFunction] = useInsertLineOneMutation();
> 
>   const worker = async (state: FormState, onSuccess?: () => void) => {
> ```

instead of callbacks, should rather return with results and throw error
___
*[src/hooks/useDeleteRoute.ts, line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZTJHQAbsSqUM4IiE_:-MxZTJHQAbsSqUM4IiEa:bxu90ih) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useDeleteRoute.ts#L12)):*
> ```XML
>     if (!routeId) return;
>     try {
>       await deleteRoute(mapToVariables({ route_id: routeId }));
> ```

deleteFromApolloCache
___
*[src/hooks/useEditLine.ts, line 42 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZSfvZBUxR0Fa9QCvd:-MxZSfvZBUxR0Fa9QCve:b-rtagwg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useEditLine.ts#L42)):*
> ```XML
>       showToast({ type: 'success', message: t('lines.saveSuccess') });
> 
>       // setHasFinishedEditing(true);
> ```

delete

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @pallost)

___
*[src/hooks/useCreateLine.ts, line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZPypWE6jYPZWqH-xI:-Mxd787H73vqjazGMvAy:bz9j1y0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd suggest we make a clear flow for these business logic hooks:
1. based on the inputs, let's create all the changes that will happen on the backend and validate them (e.g. will the validity periods collide)
2. map these changes to graphql mutation variables
3. execute these changes in the graphql mutation.
Here's an example of what I've been thinking: https://github.com/HSLdevcom/jore4-ui/blob/bus-stop-dragging/src/hooks/useEditStop.ts
</blockquote></details>

1. check for validity periods and priorities will be done later
2. mapping forms to mutation variables is now done in separated functions
3. Link gives 404 and I cant checkout `bus-stop-dragging` branch, so can't comment on that
___
*[src/hooks/useCreateLine.ts, line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZSoGcBFqadsbQL5Pa:-Mxd36FwEc87zUHsmqUe:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

instead of callbacks, should rather return with results and throw error
</blockquote></details>

Done.
___
*[src/hooks/useCreateLine.ts, line 17 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZPBIQ9-911XLlgWi9:-Mxd389-3FnrXS4U5piA:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This should be a separate mapping function in itself. It can be reused both when creating or when editing an exiting line.
</blockquote></details>

Done.
___
*[src/hooks/useCreateLine.ts, line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZPNqr5sCKHQ9UfXuu:-Mxd3Av3A3NxZOpD4XnH:b-267qum) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useCreateLine.ts#L30)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I wouldn't show toast messages within the hook workers: I think it's rather the responsibility of the caller that how to react to success/error

In case of success, it should return with the result. In case of error it could throw an exception that could be caught and handled on the caller side.
</blockquote></details>

As discussed f2f with the team, let's keep toast messages here. Showing those is not responsibility of the UI components triggering these mutations either, and this keeps those components cleaner.

Anyway, refactored all of these to either return the mutation result or throw expection.
___
*[src/hooks/useDeleteRoute.ts, line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZTJHQAbsSqUM4IiE_:-MxdA8KO2tSYM724EXVx:b-l8v7fl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useDeleteRoute.ts#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

deleteFromApolloCache
</blockquote></details>

I can't really verify this change as I'm getting
`"'Error: Foreign key violation. update or delete on table "route" violates foreign key constraint "journey_pattern_on_route_id_fkey" on table "journey_pattern"'"` error when trying to remove route. Let's maybe discuss about this in Slack....
___
*[src/hooks/useEditLine.ts, line 42 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZSfvZBUxR0Fa9QCvd:-Mxd3gOoAYYUqEK9eKoO:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useEditLine.ts#L42)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @pallost)

___
*[src/hooks/useDeleteRoute.ts, line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZTJHQAbsSqUM4IiE_:-MxiWGTb0HvZoqgVgXxO:bdv07qu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useDeleteRoute.ts#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I can't really verify this change as I'm getting
`"'Error: Foreign key violation. update or delete on table "route" violates foreign key constraint "journey_pattern_on_route_id_fkey" on table "journey_pattern"'"` error when trying to remove route. Let's maybe discuss about this in Slack....
</blockquote></details>

Or do this in another PR. Deleting from Apollo's cache is a new functionality, so it doesn't have to be in the scope of this PR.

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r3, 4 of 5 files at r4, 1 of 5 files at r5, 3 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)* status: 5 of 8 files reviewed, 11 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[src/components/routes-and-lines/EditLinePage.tsx, line 40 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiYrxzAGqoKOqaYM2R:-MxiYrxzAGqoKOqaYM2S:b-f7csgr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3732e6406a92833b4d8b6bacf2a4d4d40c1cccf3/src/components/routes-and-lines/EditLinePage.tsx#L40)):*
> ```XML
>       setHasFinishedEditing(true);
>     } catch (err) {
>       // noop
> ```

Trying with nothing in catch looks kind of weird, do we really want to both show the error toast and throw the error in the hook..? No need to fix this here and now but some solution in the future would be nice. In this PR alone there are 4 of these noops.
___
*[src/hooks/useCreateLine.ts, line 14 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiWXypDdBAATh7AoDw:-MxiWXypDdBAATh7AoDx:b-8eqbq5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ece44149224b15ee2dded53e537358208f1c31f3/src/hooks/useCreateLine.ts#L14)):*
> ```XML
> 
> export const mapFormToMutation = (state: FormState) =>
>   mapToObject({
> ```

It could be useful to first assign the mutation object to a typed variable and then map it to object and return.



_Code snippet:_
```XML
const variables: InsertLineOneMutationVariables = {
    label: state.label,
    name_i18n: state.finnishName,
    primary_vehicle_mode: state.primaryVehicleMode,
    priority: state.priority,
    validity_start: mapDateInputToValidityStart(state.validityStart),
    validity_end: mapDateInputToValidityEnd(
      state.validityEnd,
      state.indefinite,
    ),
  };
  
  return mapToObject(variables);
```
___
*[src/hooks/useCreateLine.ts, line 38 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiatBn6dpRvp8WyK3H:-MxiatBn6dpRvp8WyK3I:b-seg79k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ece44149224b15ee2dded53e537358208f1c31f3/src/hooks/useCreateLine.ts#L38)):*
> ```XML
>       showSuccessToast(t('routes.saveSuccess'));
>       // eslint-disable-next-line no-console
>       console.log('Line created successfully.', result);
> ```

Is this necessary, since the toast is shown and result can be seen from dev tools..?
___
*[src/hooks/useDeleteRoute.ts, line 12 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxZTJHQAbsSqUM4IiE_:-MxiXYwN7NhoJEyYHQh8:b32eu42) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67eae62f82dc3a3eab90b4abb84eca2210a5ef90/src/hooks/useDeleteRoute.ts#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Or do this in another PR. Deleting from Apollo's cache is a new functionality, so it doesn't have to be in the scope of this PR.
</blockquote></details>

If the Apollo cache deletion will be done soon in another PR I guess this is ok.
___
*[src/hooks/useEditRoute.ts, line 15 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiYXpn7KFhX80HKep4:-MxiYXpn7KFhX80HKep5:b-zakk82) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3732e6406a92833b4d8b6bacf2a4d4d40c1cccf3/src/hooks/useEditRoute.ts#L15)):*
> ```XML
> const mapFormToMutation = (state: FormState) => {
>   const { label, priority, validityStart, validityEnd, indefinite } = state;
>   return mapToObject({
> ```

Same here than above, maybe use typed variable.
___
*[src/hooks/useEditRoute.ts, line 25 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiaJtp4kzq6O_7yHv2:-MxiaJtp4kzq6O_7yHv3:b-540wb1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3732e6406a92833b4d8b6bacf2a4d4d40c1cccf3/src/hooks/useEditRoute.ts#L25)):*
> ```XML
> };
> 
> export const useEditRoute = () => {
> ```

Nice hooks, very easy to use :)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[src/components/routes-and-lines/EditLinePage.tsx, line 40 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiYrxzAGqoKOqaYM2R:-MxieGBcB_M0_mEyB9zx:b437o3k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3732e6406a92833b4d8b6bacf2a4d4d40c1cccf3/src/components/routes-and-lines/EditLinePage.tsx#L40)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Trying with nothing in catch looks kind of weird, do we really want to both show the error toast and throw the error in the hook..? No need to fix this here and now but some solution in the future would be nice. In this PR alone there are 4 of these noops.
</blockquote></details>

I agree with your point. Anyway, in previous version I didn't re-throw error and got feedback also from it. And we just decided together to show toast messages directly from the hook :man_shrugging: 
___
*[src/hooks/useCreateLine.ts, line 38 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiatBn6dpRvp8WyK3H:-MxifdTAC0zk2dN0-6i_:b2sbkuq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ece44149224b15ee2dded53e537358208f1c31f3/src/hooks/useCreateLine.ts#L38)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Is this necessary, since the toast is shown and result can be seen from dev tools..?
</blockquote></details>

Dunno, this was in the code before this PR and I decided to leave it as it :man_shrugging:  But OK, will remove it for now.
___
*[src/hooks/useEditRoute.ts, line 15 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/108#-MxiYXpn7KFhX80HKep4:-Mxigjp4AiJjVjRdsU4o:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3732e6406a92833b4d8b6bacf2a4d4d40c1cccf3/src/hooks/useEditRoute.ts#L15)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Same here than above, maybe use typed variable.
</blockquote></details>

Done.

**Review by eleksi — APPROVED** [review]
> Reviewed 1 of 8 files at r3, 6 of 6 files at r7, 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/108)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @eleksi and @pallost)

**Pull request merged**
