### PR TITLE
Allow inserting stop areas and organisations with E2E stop registry data insert task

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/utils/tasks.ts` line 142 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893#-O5XVjHk6oLVfIAdvU4_:-O5XVjHl7g9opNsbl_vF:bv3oemb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f7e1aab642ca772ac59c77d3e71523cf1322882/cypress/e2e/utils/tasks.ts#L142)):*
> ```XML
> }) => {
>   const organisationIdsByName = await insertOrganisations(organisations);
>   const stopPlaceIdsByLabel = await insertStopPlaces({
> ```

Would it be possible to set the organisations inside the stopPlaces already here?
So something like
```
const organisationIdsByName = await insertOrganisations(organisations);
const stopPlacesWithOrganisations = setOrganisationsToStopPlaces(stopPlaces, organisationIdsByName)
const stopPlaceIdsByLabel = await insertStopPlaces({
    stopPlacesWithOrganisations
  });
```
So that we wouldn't need to give the organisations through the rest of the functions. 

But if it has to be this way or if it is a big refactor, then probably not worth. 
___
*[`test-db-manager/src/graphql-helpers/stopRegistry.ts` line 260 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893#-O5XZGuPBWKvQZK1n1zp:-O5XZGuPBWKvQZK1n1zq:bo3vtk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f7e1aab642ca772ac59c77d3e71523cf1322882/test-db-manager/src/graphql-helpers/stopRegistry.ts#L260)):*
> ```XML
>       `Stop point ${stopPoint?.label}: stop place insert starting...`,
>     );
>     // eslint-disable-next-line no-await-in-loop
> ```

Btw, does everything explode if we try to insert simultaneously?

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`cypress/e2e/utils/tasks.ts` line 142 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893#-O5XVjHk6oLVfIAdvU4_:-O5YU2N48qXM-sgztZ7s:bz8kqce) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f7e1aab642ca772ac59c77d3e71523cf1322882/cypress/e2e/utils/tasks.ts#L142)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Would it be possible to set the organisations inside the stopPlaces already here?
So something like
```
const organisationIdsByName = await insertOrganisations(organisations);
const stopPlacesWithOrganisations = setOrganisationsToStopPlaces(stopPlaces, organisationIdsByName)
const stopPlaceIdsByLabel = await insertStopPlaces({
    stopPlacesWithOrganisations
  });
```
So that we wouldn't need to give the organisations through the rest of the functions. 

But if it has to be this way or if it is a big refactor, then probably not worth.
</blockquote></details>

Changed. Now does the relationship mapping with a helper and the id maps are not passed around. Slightly ugly types still, but definitely an improvement I think.
___
*[`test-db-manager/src/graphql-helpers/stopRegistry.ts` line 260 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893#-O5XZGuPBWKvQZK1n1zp:-O5Xb5-16YdYy2F4G3OH:b-k0sjrw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f7e1aab642ca772ac59c77d3e71523cf1322882/test-db-manager/src/graphql-helpers/stopRegistry.ts#L260)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Btw, does everything explode if we try to insert simultaneously?
</blockquote></details>

I think there was some problems yes.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893)* status: 16 of 17 files reviewed, all discussions resolved

___
*[`cypress/e2e/utils/tasks.ts` line 142 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893#-O5XVjHk6oLVfIAdvU4_:-O5lTfRr1xcBOjpDF5a8:bgoyz09) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2f7e1aab642ca772ac59c77d3e71523cf1322882/cypress/e2e/utils/tasks.ts#L142)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Changed. Now does the relationship mapping with a helper and the id maps are not passed around. Slightly ugly types still, but definitely an improvement I think.
</blockquote></details>

Yes, definitely better now with more clear responsibilities :ok_hand:  Thanks!
___
*[`test-db-manager/src/graphql-helpers/stopRegistry.ts` line 199 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893#-O5lTA0v6O_xii-4EYTx:-O5lTA0v6O_xii-4EYTy:ba0fwut) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c9d645b1ae53076dfbc154673c034d6a20ae105d/test-db-manager/src/graphql-helpers/stopRegistry.ts#L199)):*
> ```XML
>     console.log(`Stop point ${label}: stop place insert starting...`);
>     // eslint-disable-next-line no-await-in-loop
>     const netexRef = await insertStopPlace({ label, stopPlace });
> ```

Could probably just:



_Suggestion:_
```XML
    const netexRef = await insertStopPlace(stopPlaces[index]);
```

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893)* status: 15 of 17 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

___
*[`test-db-manager/src/graphql-helpers/stopRegistry.ts` line 199 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/893#-O5lTA0v6O_xii-4EYTx:-O5lhLIi91y29gzAM8SI:b-kywzrt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c9d645b1ae53076dfbc154673c034d6a20ae105d/test-db-manager/src/graphql-helpers/stopRegistry.ts#L199)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Could probably just:
</blockquote></details>

Changed :thumbsup:

**Pull request merged**
