### PR TITLE
Route datamodel

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/264)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/264)* status: all files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 138 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6gsDxy-mLiRXW6Xr-e:-N6gsDxy-mLiRXW6Xr-f:b-576g93) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/components/map/routes/DrawRouteLayer.tsx#L138)):*
> ```XML
> 
>       // retrieve infra links with stops for snapping line from mapmatching service
>       // AND all the related stops nearby
> ```

I guess the second comment line can be removed?
___
*[`ui/src/hooks/useExtractRouteFromFeature.ts` line 183 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6guuoF6u-U63yp447G:-N6guuoF6u-U63yp447H:bz13hka) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/hooks/useExtractRouteFromFeature.ts#L183)):*
> ```XML
>       // This will return the links in arbitrary order.
>       const infraLinksWithStopsResponse =
>         await mapExternalLinkIdsToInfraLinksWithStops({
> ```

Hmm, could we rethink this renaming? At least for me the `map` prefix is confusing when there really is a async query behind.
So I would rename the query rather than this function. 
What do you think?
___
*[`ui/src/hooks/useExtractRouteFromFeature.ts` line 204 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6h-D6n7iUxb5bz3XCw:-N6h-D6n7iUxb5bz3XCx:bezj8xh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/hooks/useExtractRouteFromFeature.ts#L204)):*
> ```XML
>   );
> 
>   const getInfraLinksWithStopsForCoordinates = useCallback(
> ```

This could benefit from JsDoc comment explaining the function.

Maybe also some comment to explain that the `coordinates` parameter includes all the snapping line points. (My brain first just thought that `coordinates` were longitude + latitude.) So actually should this variable also be renamed to `snappingLineCoordinateList` / `snappingPointCoordinateList` or something similar?
___
*[`ui/src/redux/slices/mapEditor.ts` line 208 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6h26zT2raGfVCdrgIh:-N6h26zT2raGfVCdrgIi:b-v9tc4k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/redux/slices/mapEditor.ts#L208)):*
> ```XML
>      * Store created / edited route geometry in state.
>      */
>     setDraftRouteGeometry: {
> ```

Also this naming is overlapping with Draft priority. Should this be renamed to setEditedRouteGeometry etc? This is out of the scope of this PR, but was just wondering.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/264)* status: all files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 138 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6gsDxy-mLiRXW6Xr-e:-N6h7v_632MWhxXToorZ:b7bz8x5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/components/map/routes/DrawRouteLayer.tsx#L138)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I guess the second comment line can be removed?
</blockquote></details>

no, we are still retrieving the nearby stops as well :)
___
*[`ui/src/hooks/useExtractRouteFromFeature.ts` line 183 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6guuoF6u-U63yp447G:-N6hABtE2SzGbLJ7ls04:b-ywoh2f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/hooks/useExtractRouteFromFeature.ts#L183)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, could we rethink this renaming? At least for me the `map` prefix is confusing when there really is a async query behind.
So I would rename the query rather than this function. 
What do you think?
</blockquote></details>

yeah, good point



_Code quote:_
```XML
await mapExternalLinkIdsToInfraLinksWithStops
```
___
*[`ui/src/hooks/useExtractRouteFromFeature.ts` line 204 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6h-D6n7iUxb5bz3XCw:-N6h8pPyBQdGmYhAvg3x:b-tkqpnh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/hooks/useExtractRouteFromFeature.ts#L204)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This could benefit from JsDoc comment explaining the function.

Maybe also some comment to explain that the `coordinates` parameter includes all the snapping line points. (My brain first just thought that `coordinates` were longitude + latitude.) So actually should this variable also be renamed to `snappingLineCoordinateList` / `snappingPointCoordinateList` or something similar?
</blockquote></details>

this is actually a bit more generic function, this could be used for other purposes as well, not just for the snapping line. But it's a good idea, I explain this in jsdoc
___
*[`ui/src/redux/slices/mapEditor.ts` line 208 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6h26zT2raGfVCdrgIh:-N6hAHn79etYWW16ZA_2:brg6k4t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/redux/slices/mapEditor.ts#L208)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Also this naming is overlapping with Draft priority. Should this be renamed to setEditedRouteGeometry etc? This is out of the scope of this PR, but was just wondering.
</blockquote></details>

yeah, you are right... on the other hand, I intend to refactor the whole data model at some point, so maybe would rather do the renaming when I figure out the new process

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/264)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 138 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6gsDxy-mLiRXW6Xr-e:-N6hD23I3OArMOraAlIw:b-9x69pk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/components/map/routes/DrawRouteLayer.tsx#L138)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

no, we are still retrieving the nearby stops as well :)
</blockquote></details>

ah, now I get it...

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/264)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/hooks/useExtractRouteFromFeature.ts` line 204 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6h-D6n7iUxb5bz3XCw:-N6hHXfO6ITwn0LJ7WWy:b-9na2g3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/hooks/useExtractRouteFromFeature.ts#L204)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is actually a bit more generic function, this could be used for other purposes as well, not just for the snapping line. But it's a good idea, I explain this in jsdoc
</blockquote></details>

Ah this is generic. Then what about `coordinateList`? Then it would be clear that it can contain more than one set of coordinates.
___
*[`ui/src/redux/slices/mapEditor.ts` line 208 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-N6h26zT2raGfVCdrgIh:-N6hHiNAAEIUk6TfrA_X:bbn4949) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/11ecb08ad5f9f68694c7daf425f96dec0538cf63/ui/src/redux/slices/mapEditor.ts#L208)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yeah, you are right... on the other hand, I intend to refactor the whole data model at some point, so maybe would rather do the renaming when I figure out the new process
</blockquote></details>

Alright, then this is absolutely fine and no need to do a temp fix here :+1:

**Review by HenrikHartiala — APPROVED** [review]
Great work!

> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/264#-:-N6hObUg0oB35zMg8RYK:b-9dwnzc)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

**Pull request merged**
