### PR TITLE
Add edit route properties page

### PR DESCRIPTION
**Pull request by eleksi**
- Add edit route page and edit page form with route deletion possibility
- Add confirmation dialog and use it in edit route page form

Depends on https://github.com/HSLdevcom/jore4-hasura/pull/53

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/forms/RoutePropertiesForm.tsx, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd-neY8Dzt4SwJRniA:-Mvd-neY8Dzt4SwJRniB:bdmvnk4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/forms/RoutePropertiesForm.tsx#L12)):*
> ```XML
>   finnishName: z.string().min(1),
>   label: z.string().min(1),
>   onLineId: z.string().uuid(),
> ```

the `onLineId` field is also required, so should put `.min(1)` here aswell
___
*[src/components/forms/RoutePropertiesForm.tsx, line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd07ub9oBmdpRKA0h-:-Mvd07ub9oBmdpRKA0h0:bvuzipf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/forms/RoutePropertiesForm.tsx#L25)):*
> ```XML
> }
> 
> const RoutePropertiesFormComponent = (
> ```

we already have a CreateRouteForm that looks and behaves pretty much the same if I'm not mistakes. Let's merge these two
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 90 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd0izQAwShyx0Xd_Hd:-Mvd0izQAwShyx0Xd_He:b-q8imvz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/routes-and-lines/EditRoutePage.tsx#L90)):*
> ```XML
>       <Container>
>         <Row className="mt-10">
>           <div className="w-full rounded-md border border-light-grey bg-background">
> ```

I think we have now a FormComponent component that could be used to wrap forms to look the same. Please look into it!
___
*[src/components/routes-and-lines/RouteStopsHeaderRow.tsx, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd1ACK-CKR-mcdD6g-:-Mvd1ACK-CKR-mcdD6g0:b-u2c5br) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/routes-and-lines/RouteStopsHeaderRow.tsx#L42)):*
> ```XML
>       <td className="flex items-center py-4 text-3xl">
>         {route.description_i18n}
>         <Link to={routes[Path.editRoute].getLink(route.route_id)}>
> ```

Can't the SimpleButton component be used here? It has props to make it behave like a Link

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/forms/RoutePropertiesForm.tsx, line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd07ub9oBmdpRKA0h-:-Mvd2cZD0x2naO9vUh9P:b-epcp8t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/forms/RoutePropertiesForm.tsx#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we already have a CreateRouteForm that looks and behaves pretty much the same if I'm not mistakes. Let's merge these two
</blockquote></details>

Actually, I just checked the Figma designs and they can't be 100% merged. But you should extract the common attributes to be reusable. E.g. the form schemas are the same for both, at least partially.

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 0 of 16 files reviewed, 12 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[src/components/forms/RoutePropertiesForm.tsx, line 26 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvr9Xb14gDu5RNSbgDD:-Mvr9Xb14gDu5RNSbgDE:b3vei1o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/components/forms/RoutePropertiesForm.tsx#L26)):*
> ```XML
> interface Props {
>   id?: string;
>   routeLabel: string | undefined | null;
> ```

`| undefined` part is not needed, should be defined like this:
`routeLabel?: string | null`.
___
*[src/components/forms/RoutePropertiesForm.tsx, line 27 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvr9l8bEHfd6dhzkEiK:-Mvr9l8bEHfd6dhzkEiL:buo9nmt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/components/forms/RoutePropertiesForm.tsx#L27)):*
> ```XML
>   id?: string;
>   routeLabel: string | undefined | null;
>   className: string | undefined;
> ```

Same here
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 90 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd0izQAwShyx0Xd_Hd:-MvrCwNQBSXOLA16D4om:b-lxvwkp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/routes-and-lines/EditRoutePage.tsx#L90)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think we have now a FormComponent component that could be used to wrap forms to look the same. Please look into it!
</blockquote></details>

`src/uiComponents/FormContainer.tsx`
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 15 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrAlwzA8FecmOau-g-:-MvrAlwzA8FecmOau-g0:ba3muca) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/components/routes-and-lines/EditRoutePage.tsx#L15)):*
> ```XML
> import { mapToISODate } from '../../time';
> import { SimpleButton } from '../../uiComponents';
> import { ConfirmationDialog } from '../../uiComponents/ComfirmationDialog';
> ```

ConfirmationDialog should be imported & exported from `src/uiComponents/index.ts`
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 30 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrAwCBAhSTvj63zZG-:-MvrAwCBAhSTvj63zZG0:b-p80g9g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/components/routes-and-lines/EditRoutePage.tsx#L30)):*
> ```XML
> export const EditRoutePage = (): JSX.Element => {
>   const [hasFinishedEditing, setHasFinishedEditing] = useState(false);
>   const [isDeleting, setDeleting] = useState(false);
> ```

React convention is to name these like `[myValue, setMyValue]` so these shold be called `[isDeleting, setIsDeleting]`
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 107 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrBtCU0j2ujYKDjpM8:-MvrBtCU0j2ujYKDjpM9:b-gp1dcx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/components/routes-and-lines/EditRoutePage.tsx#L107)):*
> ```XML
>   };
> 
>   if (hasFinishedEditing) {
> ```

I know what we have used this pattern in some current components, but I think that better way would be to use `history.push()` method for this:
https://stackoverflow.com/a/58218276
That way we would avoid needing to define ambiguous state variable and having conditional return statement from this component.

But it might be that I am missing something as e.g. https://stackoverflow.com/a/51116997 states that using <Redirect /> is "future proof" way to do things.

So, do this either way, but this is just something to consider.
___
*[src/graphql/mutations.ts, line 28 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrEfDe7-wBEfWHRgKU:-MvrEfDe7-wBEfWHRgKV:b-s7ffvd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/graphql/mutations.ts#L28)):*
> ```XML
>   mutation InsertRouteOne($object: route_route_insert_input!) {
>     insert_route_route_one(object: $object) {
>       route_id
> ```

How do we know route_id when inserting new route?
___
*[src/locales/fi-FI/common.json, line 75 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrF7M-8VwAgadxnO1b:-MvrF7M-8VwAgadxnO1c:b-dwx3yh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/locales/fi-FI/common.json#L75)):*
> ```JSON
>   },
>   "confirmDeleteRouteDialog": {
>     "title": "Poista reitti?",
> ```

Good names for translation keys! :+1: 
___
*[src/locales/fi-FI/common.json, line 78 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrEqzW4uhnNrhUtwZy:-MvrEqzW4uhnNrhUtwZz:bwuguyx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/locales/fi-FI/common.json#L78)):*
> ```JSON
>     "description": "Reitti poistetaan sille kuuluvalta linjalta.",
>     "confirmText": "Poista",
>     "cancelText": "Älä poista"
> ```

Haven't seen figma designs, but "Peruuta" sounds more sensible choice here. I think it would also be more clear to the user, since now both positive and negative actions have word "poista" in those...
___
*[src/uiComponents/ComfirmationDialog.tsx, line 31 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrG8ik9ghL3VX6N8qe:-MvrG8ik9ghL3VX6N8qf:b-f8vgq0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/uiComponents/ComfirmationDialog.tsx#L31)):*
> ```XML
>       open={isOpen}
>       onClose={onCancel}
>       className={`fixed inset-0 z-10 overflow-y-auto bg-[#00000050] ${className}`}
> ```

`bg-opacity-50` would avoud need for suspicous looking `bg-[#hexvalue]`?
___
*[src/utils/forms.ts, line 26 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrDVzy8FHa_wLda3SR:-MvrDVzy8FHa_wLda3SS:b-40ou1d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/utils/forms.ts#L26)):*
> ```XML
> // to validity end ISO date string and isIndefinite boolean
> export const mapValidityEndToFormState = (validityEnd: string | null) =>
>   validityEnd === null
> ```

What if validityEnd is `''` or `undefined`? Could you just write this like `validityEnd ? ...`

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 0 of 18 files reviewed, 7 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 134 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrpFt1AdB_hyn9OF_u:-MvrpFt1AdB_hyn9OF_v:b7q7h7j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f82da4f1cb7e56ec06d431d61845ceda977ef122/src/components/routes-and-lines/EditRoutePage.tsx#L134)):*
> ```XML
>                   priority: route.priority,
>                   validityStart: mapToISODate(route.validity_start),
>                   validityEnd: mapValidityEndToFormState(route.validity_end)
> ```

By the way, why not just to write these like this?
```
validityEnd: mapToISODate(line?.validity_end),
 indefinite: !line?.validity_end,
```

Seems to work at least in `src/components/routes-and-lines/EditLinePage.tsx`
___
*[src/components/routes-and-lines/RouteStopsHeaderRow.tsx, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd1ACK-CKR-mcdD6g-:-Mvrpa4kBhDntH_GbH32:b9bnknn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/routes-and-lines/RouteStopsHeaderRow.tsx#L42)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

SimpleButton has some default styling that does not match this component. Similar edit button is also in AdditionalInformation and it has been implemented this way.
</blockquote></details>

Your comment raises a question if this should then be extracted to own component and used in both places? :wink: But if they're still a bit different then it is OK for me to leave this like this for now.
___
*[src/graphql/mutations.ts, line 28 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrEfDe7-wBEfWHRgKU:-MvrpiEy0UOtmk9Hr2wW:b-oa9a5f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/graphql/mutations.ts#L28)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This is the return value, right?
</blockquote></details>

Sorry, my bad
___
*[src/utils/forms.ts, line 26 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrDVzy8FHa_wLda3SR:-MvrpxKX9Pc52ns-HCMH:b-ctwtwm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/c99b104aa8f18326fbc5cd8c2d3064acbab33453/src/utils/forms.ts#L26)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I was trusting it always being either null or a valid value since this function is called when mapping the value from backend to form value. If you see a case where it is  `''` or `undefined`, I can change it.
</blockquote></details>

If comparision to `null` doesn't give any additional benefits, I would just remove `=== null` part. In the real world backend might end up having inconsistent data at some point :sweat_smile:

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 0 of 20 files reviewed, 6 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 134 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-MvrpFt1AdB_hyn9OF_u:-Mvrstrn75JRQ2pkJioR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f82da4f1cb7e56ec06d431d61845ceda977ef122/src/components/routes-and-lines/EditRoutePage.tsx#L134)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

By the way, why not just to write these like this?
```
validityEnd: mapToISODate(line?.validity_end),
 indefinite: !line?.validity_end,
```

Seems to work at least in `src/components/routes-and-lines/EditLinePage.tsx`
</blockquote></details>

Done.
___
*[src/components/routes-and-lines/RouteStopsHeaderRow.tsx, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd1ACK-CKR-mcdD6g-:-Mvrvlu-50C0T3XyaAPQ:b1ujfx7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/routes-and-lines/RouteStopsHeaderRow.tsx#L42)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Your comment raises a question if this should then be extracted to own component and used in both places? :wink: But if they're still a bit different then it is OK for me to leave this like this for now.
</blockquote></details>

Right, I guess it could be a separate component.

**Review by tk-vincit — COMMENTED** [review]
> Reviewed 1 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 1 of 20 files reviewed, 4 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/forms/RoutePropertiesForm.tsx, line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd07ub9oBmdpRKA0h-:-Mvs3bvB8Sn4_KU3Zw3U:b4pj7wb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/forms/RoutePropertiesForm.tsx#L25)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Schemas merged.
</blockquote></details>

It still looks like this file is almost identical to `src/components/forms/CreateRouteForm.tsx`, just widths of certain Row elements are different.
My first option would be to ask from design team if these forms really have to look different to each other.
If yes, then at least all inputs could be extracted to shared components. Example implementation of LineInput:

`LineInput.tsx`:

```
import React from 'react';
import { Control, Controller, FieldError } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { ChooseLineDropdown } from '../components/forms/ChooseLineDropdown';
import { FormState } from '../components/forms/CreateRouteForm';

interface Props {
  error?: FieldError;
  control?: Control<FormState, object>;
}

export const LineInput: React.FC<Props> = ({ error, control }) => {
  const { t } = useTranslation();
  return (
    <>
      <label htmlFor="on_line_id">{t('routes.addToLine')}</label>
      <Controller
        name="on_line_id"
        control={control}
        render={({ field: { onChange, onBlur, value } }) => (
          <ChooseLineDropdown
            value={value}
            onChange={onChange}
            onBlur={onBlur}
          />
        )}
      />
      <p>{error?.type === 'invalid_type' && t('formValidation.required')}</p>
    </>
  );
};

```

Otherwise we'll end up forms that are difficult to maintain
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 41 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvs2riq1cfTtYDI6zEN:-Mvs2riq1cfTtYDI6zEO:b-a5d4h6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144291c28df9e0f8f4dc70d0104fff64ab903326/src/components/routes-and-lines/EditRoutePage.tsx#L41)):*
> ```XML
> 
>   const onCancel = () => {
>     history.goBack();
> ```

I know also this pattern has been previously used somewhere, but this won't work e.g. when user arrives to this page from another domain via direct link or when there is no history (e.g. browser is just started).

Better way would be to redirect user back to corresponding route's page.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 1 of 24 files reviewed, 4 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/forms/RoutePropertiesForm.tsx, line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd07ub9oBmdpRKA0h-:-MvsPbSr3BLQ8t8GAU2m:by8w3r4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/forms/RoutePropertiesForm.tsx#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

It still looks like this file is almost identical to `src/components/forms/CreateRouteForm.tsx`, just widths of certain Row elements are different.
My first option would be to ask from design team if these forms really have to look different to each other.
If yes, then at least all inputs could be extracted to shared components. Example implementation of LineInput:

`LineInput.tsx`:

```
import React from 'react';
import { Control, Controller, FieldError } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { ChooseLineDropdown } from '../components/forms/ChooseLineDropdown';
import { FormState } from '../components/forms/CreateRouteForm';

interface Props {
  error?: FieldError;
  control?: Control<FormState, object>;
}

export const LineInput: React.FC<Props> = ({ error, control }) => {
  const { t } = useTranslation();
  return (
    <>
      <label htmlFor="on_line_id">{t('routes.addToLine')}</label>
      <Controller
        name="on_line_id"
        control={control}
        render={({ field: { onChange, onBlur, value } }) => (
          <ChooseLineDropdown
            value={value}
            onChange={onChange}
            onBlur={onBlur}
          />
        )}
      />
      <p>{error?.type === 'invalid_type' && t('formValidation.required')}</p>
    </>
  );
};

```

Otherwise we'll end up forms that are difficult to maintain
</blockquote></details>

I merged the form components completely and adjusted styling to fit both contexts of use, modal and separate page. In the future there could be need for some customization.
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 41 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvs2riq1cfTtYDI6zEN:-MvsRk2WDc23vR3WxiDE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/144291c28df9e0f8f4dc70d0104fff64ab903326/src/components/routes-and-lines/EditRoutePage.tsx#L41)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I know also this pattern has been previously used somewhere, but this won't work e.g. when user arrives to this page from another domain via direct link or when there is no history (e.g. browser is just started).

Better way would be to redirect user back to corresponding route's page.
</blockquote></details>

Done.

**Review by tk-vincit — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 14 files at r1, 2 of 12 files at r9, 8 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-:-Mvwy9Wc5d0TQbB5w0fu:b593w57)* status: 10 of 24 files reviewed, 4 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/forms/RoutePropertiesForm.tsx, line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/91#-Mvd07ub9oBmdpRKA0h-:-MvwxIoh7z3KAy6gTAoS:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73542eb324a59c81d73da79505d68beb756de1d0/src/components/forms/RoutePropertiesForm.tsx#L25)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I merged the form components completely and adjusted styling to fit both contexts of use, modal and separate page. In the future there could be need for some customization.
</blockquote></details>

:+1:

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/91)* status: 10 of 24 files reviewed, all discussions resolved (waiting on @pallost and @tk-vincit)

**Pull request merged**
