### PR TITLE
GitHub e2e tests

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/280)

Closes https://github.com/HSLdevcom/jore4/issues/901

### CODE REVIEW

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/280)* status: 0 of 19 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`.dockerignore` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhhR3JCi_fd057wViA:-NAhhR3JCi_fd057wViB:bbiznzx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/03823d667070000560eaf72d1e796f3a3cd3e1ff/.dockerignore#L35)):*
> ```ignore
> Dockerfile
> 
> # non-related projects/workspaces
> ```

Are these now included to UI's docker image..?
___
*[`.github/workflows/run-cypress-tests.yml` line 70 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhgGAkAEHZgQKUk3oC:-NAhgGAkAEHZgQKUk3oD:b3kh3ny) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/.github/workflows/run-cypress-tests.yml#L70)):*
> ```YAML
> 
>   # Note: this is a temporary solution for now. Should replace this with image from docker hub
>   # when we have the jore4-cypress repository created
> ```

Do we really want to move cypress tests to a separate repository? Currently maintaining those is easy as you can make changes to code and fix tests in a single commit, so I would avoid having separate repositories as long as it is reasonably possible.
___
*[`cypress/support/commands.ts` line 39 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhdsvi2lYS_QK-wEL-:-NAhdsvi2lYS_QK-wEL0:bch5psa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/cypress/support/commands.ts#L39)):*
> ```XML
>     }).as('userInfo');
> 
>     // intercept calls to hasura and log in as admin (to avoid it going to auth backend)
> ```

This intercepts **all** requests and adds x-hasura-admin-secret header. Thus removed TODO comment is still relevant and shoul be kept.
___
*[`cypress/support/commands.ts` line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAheCwsCu9kNENWRiUJ:-NAheCwsCu9kNENWRiUK:bbh3lih) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/cypress/support/commands.ts#L48)):*
> ```XML
> 
> Cypress.Commands.add('setupTests', () => {
>   // no need to display map tiles
> ```

These make local test development more difficult. Maybe we want to do this only in CI?
___
*[`cypress/support/commands.ts` line 59 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhel6DAbQ_qtBIP26J:-NAhel6DAbQ_qtBIP26K:bhgeqj9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/cypress/support/commands.ts#L59)):*
> ```XML
> 
>   // label all graphql calls that they can be expected in tests
>   // e.g. GetAllLines query can be waited as cy.wait('@gqlGetAllLines')
> ```

Nice trick! Although not sure if we want to do this in real-life tests... (Ok, seems like we already did. Why waiting for toast is not realible?)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/280)* status: 0 of 19 files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

___
*[`.dockerignore` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhhR3JCi_fd057wViA:-NAsHwFB5gNCO1I-cOfw:b-pcwiiw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/03823d667070000560eaf72d1e796f3a3cd3e1ff/.dockerignore#L35)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Are these now included to UI's docker image..?
</blockquote></details>

Not in the image itself, but the docker context, yes. If we used `COPY . /app/` then these files would be added as well, but as we always use targeted COPY commands that anyway only copy the necessary files, this is not an issue. Just slowing docker image building a bit...

https://www.howtogeek.com/devops/understanding-the-docker-build-context-why-you-should-use-dockerignore/
___
*[`.github/workflows/run-cypress-tests.yml` line 70 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhgGAkAEHZgQKUk3oC:-NAsIL3KEhhCr4gp12oQ:b-gv6zpo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/.github/workflows/run-cypress-tests.yml#L70)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we really want to move cypress tests to a separate repository? Currently maintaining those is easy as you can make changes to code and fix tests in a single commit, so I would avoid having separate repositories as long as it is reasonably possible.
</blockquote></details>

*docker hub* repository, not github repository 
___
*[`cypress/support/commands.ts` line 39 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhdsvi2lYS_QK-wEL-:-NAsIk5j8Va0poJoEmkv:b-e8513l) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/cypress/support/commands.ts#L39)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This intercepts **all** requests and adds x-hasura-admin-secret header. Thus removed TODO comment is still relevant and shoul be kept.
</blockquote></details>

good point!
___
*[`cypress/support/commands.ts` line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAheCwsCu9kNENWRiUJ:-NAsIZPO6QXqbqtg79Px:b-pyusrg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/cypress/support/commands.ts#L48)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

These make local test development more difficult. Maybe we want to do this only in CI?
</blockquote></details>

At least for me, personally, the map tests had also sometimes randomly failed :/ This helped though... I will try to think of a way to make this stuff opt-in



_Code quote:_
```XML
  // TODO: we should match only '/api/graphql' requests, but for some
  // reason that doesn't seem to work. (Could be because our graphql
```
___
*[`cypress/support/commands.ts` line 59 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhel6DAbQ_qtBIP26J:-NAsM_Qq-WAY3_KBp8ef:b-qaqapc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/cypress/support/commands.ts#L59)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Nice trick! Although not sure if we want to do this in real-life tests... (Ok, seems like we already did. Why waiting for toast is not realible?)
</blockquote></details>

sometimes the toast message was already hidden by the time cypress started looking for it... :)

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/280)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @pallost and @tk-vincit)

___
*[`.dockerignore` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhhR3JCi_fd057wViA:-NAt5g9t8kUdc7cwC4_1:b-h2ots1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/03823d667070000560eaf72d1e796f3a3cd3e1ff/.dockerignore#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Not in the image itself, but the docker context, yes. If we used `COPY . /app/` then these files would be added as well, but as we always use targeted COPY commands that anyway only copy the necessary files, this is not an issue. Just slowing docker image building a bit...

https://www.howtogeek.com/devops/understanding-the-docker-build-context-why-you-should-use-dockerignore/
</blockquote></details>

ok, so I assume this is OK then
___
*[`.github/workflows/run-cypress-tests.yml` line 70 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAhgGAkAEHZgQKUk3oC:-NAt3NTmD8SFCbbXZkzT:boy3uq0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/768fd04949dad9a7924c34f367a47fb55af118f2/.github/workflows/run-cypress-tests.yml#L70)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

*docker hub* repository, not github repository 
</blockquote></details>

Ah :smile: 
___
*[`.github/workflows/run-cypress-tests.yml` line 72 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAt58CJ6JRdTI0TBZ-M:-NAt58CJ6JRdTI0TBZ-N:bdudddb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e10d99f3eb4071745a352bd7e599f47760ef115/.github/workflows/run-cypress-tests.yml#L72)):*
> ```YAML
>   # when we have the jore4-cypress repository created
>   run_cypress_docker:
>     name: Run cypress e2e tests locally with docker
> ```

So we are now running same tests twice, first locally and then in a docker container? Should we rather do it in paraller, or is that the case already?  Also seems like we now have lots of copypasta in this file, but if this is just temporary solution then this might be fine for now.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/280)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[`.github/workflows/run-cypress-tests.yml` line 72 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/280#-NAt58CJ6JRdTI0TBZ-M:-NAx5M3eAf4DrQfwZ2WN:b-63qbhf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0e10d99f3eb4071745a352bd7e599f47760ef115/.github/workflows/run-cypress-tests.yml#L72)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

So we are now running same tests twice, first locally and then in a docker container? Should we rather do it in paraller, or is that the case already?  Also seems like we now have lots of copypasta in this file, but if this is just temporary solution then this might be fine for now.
</blockquote></details>

this is just temporary, yeah... when we have a jore4-cypress github repo, we can get rid of both of these and just use that one

**Pull request merged**
