### PR TITLE
Display timetables API errors in a better way

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723)* status: all files reviewed, 6 unresolved discussions (waiting on @Leitsi)

___
*[`docker/docker-compose.custom.yml` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfcFLe9KGUXoN6K9Ri:-NjfcFLe9KGUXoN6K9Rj:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a61fa4441b428e0a0734f780040f9a9cae8d155f/docker/docker-compose.custom.yml#L18)):*
> ```YAML
>       jore4-testdb:
>         condition: service_healthy
>     # Uncomment the lines below to direct timetables-api actions from Hasura
> ```

:ok_hand: 
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 47 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfd2qu9MpfvQhpxymT:-Njfd2qu9MpfvQhpxymU:ba1843j) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L47)):*
> ```XML
>     }
> 
>     onClose();
> ```

You could also move the onClose inside try-block and then we have no need for `return` in the catch block (same for `onSubmit`), but I guess it makes no more difference than saving 1 line
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 22 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfh3D30YxLnsgyv4l6:-Njfh3D30YxLnsgyv4l7:b45h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L22)):*
> ```XML
>   const { setIsLoading } = useLoader(Operation.ConfirmTimetablesImport);
> 
>   const showConfirmFailedErrorDialog = (error: unknown) => {
> ```





_Suggestion:_
```XML
  const showConfirmFailedErrorToast = (error: unknown) => {
```
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 27 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfefLy-3WZ0DE5xg7H:-NjfefLy-3WZ0DE5xg7I:b-8zux56) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L27)):*
> ```XML
>     }
> 
>     const translateException = (type: TimetablesApiErrorType) => {
> ```

Should this be `translateError`?
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 49 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjffAhS5rwp278cfPhS:-NjffAhS5rwp278cfPhT:btnafob) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L49)):*
> ```XML
>     showDangerToastWithError(
>       translateException(extractErrorType(error)),
>       error,
> ```

Btw, does the `error.message` (added in the toast in`showDangerToastWithError`) provide some extra / helpful information for us after we have these types and translations?

Hmm, just realised that at least in the case of `unknown` it should add something extra. And maybe for the transactionSystemError?
___
*[`ui/src/locales/en-US/common.json` line 439 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfhU1o8kvIZyH5K8PW:-NjfhU1o8kvIZyH5K8PX:b-38us1k) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/locales/en-US/common.json#L439)):*
> ```JSON
>   "import": {
>     "errors": {
>       "unknown": "Saving imported timetables failed: unknown error.",
> ```

Should we add something like "please contact support/devteam/maintenance/foobar" to the unknown error message?
___
*[`ui/src/locales/en-US/common.json` line 441 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfidvC7IkYqOrOcRVC:-NjfidvC7IkYqOrOcRVD:undefined) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/locales/en-US/common.json#L441)):*
> ```JSON
>       "unknown": "Saving imported timetables failed: unknown error.",
>       "conflictingSchedules": "Saving imported timetables failed: overlapping vehicle schedule frames detected.",
>       "multipleTargetFramesFound": "Imported timetables could not be combined: many possible target timetables found.",
> ```





_Suggestion:_
```JSON
      "multipleTargetFramesFound": "Imported timetables could not be combined: multiple possible target timetables found.",
```
___
*[`ui/src/utils/timetablesApiErrors.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfk2-83r4bLctFDC1G:-Njfk2-83r4bLctFDC1H:b-fia278) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/utils/timetablesApiErrors.ts#L4)):*
> ```XML
> 
> // These error types originate from timetables-api, see `HasuraErrorType` there.
> const timetablesApiErrorTypes = <const>[
> ```

Could (should?) we use enum here?

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723)* status: all files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 47 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfd2qu9MpfvQhpxymT:-NjgGuuc8VrSFvcr-TfW:b-ef5d2x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L47)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You could also move the onClose inside try-block and then we have no need for `return` in the catch block (same for `onSubmit`), but I guess it makes no more difference than saving 1 line
</blockquote></details>

Changed, maybe it's clearer that way after all.
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 22 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfh3D30YxLnsgyv4l6:-NjfpnDy0T6eR9So5AS-:bewf9fx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L22)):*
> ```XML
>   const { setIsLoading } = useLoader(Operation.ConfirmTimetablesImport);
> 
>   const showConfirmFailedErrorDialog = (error: unknown) => {
> ```

I will change this to a dialog so maybe won't bother renaming in between.
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 27 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfefLy-3WZ0DE5xg7H:-NjgCrpIBRdKZn-YEjtl:b-4vl49v) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L27)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should this be `translateError`?
</blockquote></details>

Yep, fixed :ok_hand: 
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 49 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjffAhS5rwp278cfPhS:-NjfpwWq6TZyGSkPwhgZ:b2z9s5n) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L49)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Btw, does the `error.message` (added in the toast in`showDangerToastWithError`) provide some extra / helpful information for us after we have these types and translations?

Hmm, just realised that at least in the case of `unknown` it should add something extra. And maybe for the transactionSystemError?
</blockquote></details>

Sometimes it does. Depends on the case. In transaction system errors it is always "JDBC commit failed" and nothing else, but in some other cases it shows the actually useful SQL errror message. I think it might be easiest if we just show it always.

This part will change anyway once I get to switch this to the new error dialog.
___
*[`ui/src/locales/en-US/common.json` line 439 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfhU1o8kvIZyH5K8PW:-NjgC3yMCmtZV_AWNiDw:b4h6r5f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/locales/en-US/common.json#L439)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should we add something like "please contact support/devteam/maintenance/foobar" to the unknown error message?
</blockquote></details>

Discussed with Juha. Will leave like this for now. Might change at some point if we have a clear communication channel for this kind of technical support.
___
*[`ui/src/locales/en-US/common.json` line 441 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfidvC7IkYqOrOcRVC:-NjfqPx96zZOGElN1_YR:b4c9lyr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/locales/en-US/common.json#L441)):*
> ```JSON
>       "unknown": "Saving imported timetables failed: unknown error.",
>       "conflictingSchedules": "Saving imported timetables failed: overlapping vehicle schedule frames detected.",
>       "multipleTargetFramesFound": "Imported timetables could not be combined: many possible target timetables found.",
> ```

:thumbsup: 
___
*[`ui/src/utils/timetablesApiErrors.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfk2-83r4bLctFDC1G:-Njfqtql1ujo5Oxd_b52:b-v3cmjm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/utils/timetablesApiErrors.ts#L4)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Could (should?) we use enum here?
</blockquote></details>

I think my rationale was that I couldn't find an easy  / non-bloty / safe way to initialize the enum from these error type strings.

But found a working enum solution after all, so will switch this.

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 1 of 7 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`docker/docker-compose.custom.yml` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfcFLe9KGUXoN6K9Ri:-NjgJV0a9bhU3vPvzwK1:b-t9uswk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a61fa4441b428e0a0734f780040f9a9cae8d155f/docker/docker-compose.custom.yml#L18)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

:ok_hand:
</blockquote></details>

Whoops, was not supposed to be blocking comment :D 
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 47 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfd2qu9MpfvQhpxymT:-NjgJf647H1GcG4Hm0Hz:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L47)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Changed, maybe it's clearer that way after all.
</blockquote></details>

:+1: 
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 22 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfh3D30YxLnsgyv4l6:-NjgJyAC7dynTGJGWudM:bmd201g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L22)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I will change this to a dialog so maybe won't bother renaming in between.
</blockquote></details>

:+1:  Yeah, noticed only afterwards that you mentioned about the dialog in the first slack message. Is good
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 49 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjffAhS5rwp278cfPhS:-NjgJB1w0HN4jxRDTRQm:b-s8t86a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L49)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Sometimes it does. Depends on the case. In transaction system errors it is always "JDBC commit failed" and nothing else, but in some other cases it shows the actually useful SQL errror message. I think it might be easiest if we just show it always.

This part will change anyway once I get to switch this to the new error dialog.
</blockquote></details>

check!
___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 30 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjgKHk027Z6FH1GPzgq:-NjgKHk027Z6FH1GPzgr:bqwpuf1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/dabfc357e573e498a67f901946bd51d0b5012fda/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L30)):*
> ```XML
>       // Note: there are others, but only adding translations to those that can realistically occur here.
>       switch (type) {
>         case 'ConflictingSchedulesError':
> ```

You can now use the enum in these case's
___
*[`ui/src/locales/en-US/common.json` line 439 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjfhU1o8kvIZyH5K8PW:-NjgKa3ACtEWQTGRIKxn:b-4gpafr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/locales/en-US/common.json#L439)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Discussed with Juha. Will leave like this for now. Might change at some point if we have a clear communication channel for this kind of technical support.
</blockquote></details>

Check :+1: 
___
*[`ui/src/utils/timetablesApiErrors.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-Njfk2-83r4bLctFDC1G:-NjgKny53OVPFaHfTXuc:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f28195f97a685461b39e1080bbcd1caa90518ad/ui/src/utils/timetablesApiErrors.ts#L4)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think my rationale was that I couldn't find an easy  / non-bloty / safe way to initialize the enum from these error type strings.

But found a working enum solution after all, so will switch this.
</blockquote></details>

:ok_hand:

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts` line 30 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-NjgKHk027Z6FH1GPzgq:-NjgLgTsDcX5jHRRbGga:bt2vr0y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/dabfc357e573e498a67f901946bd51d0b5012fda/ui/src/hooks/timetables-import/useConfirmTimetablesImportUIAction.ts#L30)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You can now use the enum in these case's
</blockquote></details>

Fixed!

**Review by HenrikHartiala — APPROVED** [review]
:lgtm: Great!

> Reviewed 1 of 7 files at r9, 4 of 4 files at r12, 3 of 6 files at r13, 2 of 2 files at r14, 6 of 8 files at r15, 2 of 2 files at r16, 5 of 5 files at r20, 3 of 6 files at r21, 2 of 2 files at r22, 6 of 8 files at r23, 2 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/723#-:-NmAyg2_15fH3TbxaCoG:bioon7n)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
