### PR TITLE
Upgrade eslint

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480)* status: 0 of 29 files reviewed, all discussions resolved

___
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480#-NMgyODZCuTHh7iqbkpy:-NMgyODZCuTHh7iqbkpz:br1s230) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/878cb25c543ba45c4135b5897007222df766d0ed/ui/src/hooks/line-details/useGetLineDetails.ts#L43)):*
> ```XML
>   const routesGroupedByLabelAndVariant = groupBy(
>     routesFilteredByDirection,
>     (route) => `${route.label}${route?.variant}`,
> ```

If there is no variant, then this `groupBy` will add `null` to the key. 
This can be avoided with something like this:
```
route.variant ? `${route.label}${route.variant}` : route.label
```

But this same issue was already present with the existing code, so up to you if you want to fix it here.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480#-NMgyODZCuTHh7iqbkpy:-NMgzp7r7ziTerAtKlEd:b-7da6yb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/878cb25c543ba45c4135b5897007222df766d0ed/ui/src/hooks/line-details/useGetLineDetails.ts#L43)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

If there is no variant, then this `groupBy` will add `null` to the key. 
This can be avoided with something like this:
```
route.variant ? `${route.label}${route.variant}` : route.label
```

But this same issue was already present with the existing code, so up to you if you want to fix it here.

</blockquote></details>

We already have a function for this, if you want to use it:
`getRouteLabelVariantText`

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @eleksi)

___
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480#-NMgyODZCuTHh7iqbkpy:-NMh0H8C2qzb9ZigKjDX:b-1d52nx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/878cb25c543ba45c4135b5897007222df766d0ed/ui/src/hooks/line-details/useGetLineDetails.ts#L43)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

We already have a function for this, if you want to use it:
`getRouteLabelVariantText`
</blockquote></details>

Ah, nice :+1:

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @eleksi and @HenrikHartiala)

___
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480#-NMgyODZCuTHh7iqbkpy:-NMh1fqnANH-TRdyo-NG:bt4lcmq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/878cb25c543ba45c4135b5897007222df766d0ed/ui/src/hooks/line-details/useGetLineDetails.ts#L43)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah, nice :+1: 
</blockquote></details>

Updated this as eleksi suggested.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`ui/src/uiComponents/SearchableDropdown.tsx` line 25 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/480#-NN0nqmo71un_vLqc2Ic:-NN0nqmo71un_vLqc2Id:b6xpipr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4578727cea7a899e3fe1dc6cfcd09ac4229bc582/ui/src/uiComponents/SearchableDropdown.tsx#L25)):*
> ```XML
> // to arrow function component definition.
> // eslint-disable-next-line react/function-component-definition
> export function SearchableDropdown<T>({
> ```

see InputField component



_Code quote:_
```XML
// eslint disabled until someone figures syntax to pass generic type param
// to arrow function component definition.
```

**Pull request merged**
