### PR TITLE
Add support for hidden variants

### PR DESCRIPTION
**Pull request by eleksi**
- DIsplay hidden variant
- Allow editing hidden variant

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/418)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 9 of 12 files at r2, 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/418)* status: 24 of 29 files reviewed, 9 unresolved discussions (waiting on @eleksi)

___
*[`test-db-manager/src/generated/graphql.ts` line 1435 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAUskmCmIBbKN2uw6S:-NJAUsknAC-GgGkyKAFx:b433ro2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/test-db-manager/src/generated/graphql.ts#L1435)):*
> ```XML
>   /** The ID of the journey pattern. */
>   journey_pattern_id: Scalars['uuid'];
>   journey_pattern_refs: Array<TimetablesJourneyPatternJourneyPatternRef>;
> ```

This part might conflict after my PR is in main, since these are added there as well.
___
*[`ui/src/components/common/RouteLabel.tsx` line 5 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAcv_MBcisu7nuTblE:-NJAcv_MBcisu7nuTblF:b-jgkn1b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/common/RouteLabel.tsx#L5)):*
> ```XML
> import { Visible } from '../../layoutComponents';
> 
> const GQL_ROUTE_LABEL_FIELDS = gql`
> ```

This seems to be existing only to create the type, and I would not do that. I think that you should either use `Pick<RouteAllFields, 'label' | 'variant'>` OR modify the existing GQL's to include this fragment. For example currently it seems that RouteTableRowFragment does not include the 'variant' at all.
___
*[`ui/src/components/common/RouteLabel.tsx` line 19 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAZZT113TMGdeu78i4:-NJAZZT113TMGdeu78i5:b-u4x03d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/common/RouteLabel.tsx#L19)):*
> ```XML
>   Number.isInteger(route?.variant);
> 
> export const getRouteLabelText = (route: RouteLabelFragment) =>
> ```

Should this be `getRouteLabelWithVariantText` etc?  Because now the name implies that it returns the label text, even though it returns label + variant.
I mean I do understand that `label + variant = label fields`, but maybe the names should not overlap. `getRouteCombinedLabelText`? 

Hmm I don't know. What do you think?

Actually I just realised that is this the right place for this function? Because it is not used here, and it is used in somewhere unrelated to this component. 
___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 69 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAhZxU0Axc8OMzLfp-:-NJAhZxU0Axc8OMzLfp0:butl67f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/common/RouteLineTableRow.tsx#L69)):*
> ```XML
>             <Column className="w-1/2 font-bold">
>               <h2>
>                 {isRoute(rowItem) ? (
> ```

I'm not sure what or how this function works, but it seems to change the type of rowItem into `RouteRoute` and I think we do not want that.
___
*[`ui/src/components/forms/common/customZodSchemas.ts` line 40 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAhzEAAsuhq65hLLgR:-NJAhzEAAsuhq65hLLgS:b-5ehvwf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/forms/common/customZodSchemas.ts#L40)):*
> ```XML
> // "Expected number, received nan"
> // As a workaround just map all values that are not numbers to null
> export const nullableNumber = z.any().transform((value): number | null => {
> ```

I'm not very familiar with this part (usage of zod) so if you want to validate this part of the code, maybe someone else should check this :)
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 90 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAj4kI28xrulWf2V6c:-NJAj4kI28xrulWf2V6d:b-18o7f0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/map/RouteStopsOverlay.tsx#L90)):*
> ```XML
>         <div>
>           <h2 className="text-tweaked-brand">
>             <RouteLabel route={routeMetadata} />
> ```

RouteMetadataFragment does not include 'variant' attribute. So if the types are right, this will never show the variant. IF this was not intentional then this is a downside of using the GQL fragment instead of explicit 'label' and 'variant' parameters, because the 'variant' is optional, so eslinter does not give a warning about 'variant' missing. 
___
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 43 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAmUxDAxeFQ-F-ALeW:-NJAmUxDAxeFQ-F-ALeX:b-3x0xp8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/hooks/line-details/useGetLineDetails.ts#L43)):*
> ```XML
>   const routesGroupedByLabelAndVariant = groupBy(
>     routesFilteredByDirection,
>     (route) => route.label + route?.variant,
> ```

Ah, did not know that this works like this as well. Nice
___
*[`ui/src/hooks/stops/useCreateStop.ts` line 2 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAc7J91IA16Y_hFfPN:-NJAc7J91IA16Y_hFfPO:b-cedn31) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/hooks/stops/useCreateStop.ts#L2)):*
> ```XML
> import flow from 'lodash/flow';
> import { getRouteLabelText } from '../../components/common/RouteLabel';
> ```

Yeah, so I think this hook should not have a dependency to an unrelated visual component. I. would maybe extract that part to utils (?) and name it so that it is clear it returns the combination of the label & variant.
___
*[`ui/src/utils/gql.ts` line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAodQTDF0ws2OTrMCB:-NJAodQTDF0ws2OTrMCC:b-fyit9x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/utils/gql.ts#L60)):*
> ```XML
> /** Builds an object for gql to filter by variant */
> export const buildVariantGqlFilter = (variant?: number | null) => ({
>   variant: variant === null ? { _is_null: true } : { _eq: variant },
> ```

Won't this work with just `variant: { _eq: variant }`? Doesn't it consider `null` as the value?

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/418)* status: 14 of 31 files reviewed, 9 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test-db-manager/src/generated/graphql.ts` line 1435 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAUskmCmIBbKN2uw6S:-NJEgpPG8jYwGdEGwMwu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/test-db-manager/src/generated/graphql.ts#L1435)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This part might conflict after my PR is in main, since these are added there as well.
</blockquote></details>

Done.
___
*[`ui/src/components/common/RouteLabel.tsx` line 5 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAcv_MBcisu7nuTblE:-NJEhSDyAougb_MRQyLi:bv0fa9h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/common/RouteLabel.tsx#L5)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This seems to be existing only to create the type, and I would not do that. I think that you should either use `Pick<RouteAllFields, 'label' | 'variant'>` OR modify the existing GQL's to include this fragment. For example currently it seems that RouteTableRowFragment does not include the 'variant' at all.
</blockquote></details>

`Pick<RouteAllFields, 'label' | 'variant'>`produces se same thing as the Fragment. But yeah, unused fragments are probably not a good idea. It is just a nice way to create types that are used similarly to any other GQL types and imported from graphql.

I have no idea what happened to variant defined in `RouteTableRowFragment`, because I remember starting the addition of variant from the route table view and seeing variant in that list. :thinking: But I have now added it again.
___
*[`ui/src/components/common/RouteLabel.tsx` line 19 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAZZT113TMGdeu78i4:-NJEigIE1K4sKwQhkjbV:b-657poh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/common/RouteLabel.tsx#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should this be `getRouteLabelWithVariantText` etc?  Because now the name implies that it returns the label text, even though it returns label + variant.
I mean I do understand that `label + variant = label fields`, but maybe the names should not overlap. `getRouteCombinedLabelText`? 

Hmm I don't know. What do you think?

Actually I just realised that is this the right place for this function? Because it is not used here, and it is used in somewhere unrelated to this component. 
</blockquote></details>

Hmm yeah, the idea was that variant is kind of part of the label text but I try to figure something else out.
___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 69 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAhZxU0Axc8OMzLfp-:-NJEj3ySCSUkDA7b82Ug:bva8pl3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/common/RouteLineTableRow.tsx#L69)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I'm not sure what or how this function works, but it seems to change the type of rowItem into `RouteRoute` and I think we do not want that.
</blockquote></details>

Hmm I don't think it changes the type. Or well typescript does seem to think it is RouteRoute after this.

I made a little change to isRoute function. It looks kind of stupid, but at least in my IDE it seems to work perfectly at least in this case.
___
*[`ui/src/components/forms/common/customZodSchemas.ts` line 40 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAhzEAAsuhq65hLLgR:-NJEkwIq6FH8DpExNSTH:bb0be7v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/forms/common/customZodSchemas.ts#L40)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I'm not very familiar with this part (usage of zod) so if you want to validate this part of the code, maybe someone else should check this :)
</blockquote></details>

It is very annoying workaround and I hate it. I can ask someone else to check it.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 90 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAj4kI28xrulWf2V6c:-NJElMRKBECK44ZAyZNx:b-jmaq0d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/map/RouteStopsOverlay.tsx#L90)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

RouteMetadataFragment does not include 'variant' attribute. So if the types are right, this will never show the variant. IF this was not intentional then this is a downside of using the GQL fragment instead of explicit 'label' and 'variant' parameters, because the 'variant' is optional, so eslinter does not give a warning about 'variant' missing. 
</blockquote></details>

I have no idea what happened to variant defined in `RouteTableRowFragment`, because I remember starting the addition of variant from the route table view and seeing variant in that list. :thinking: But I have now added it again.

Btw, using pick works similarly, does not help with this.
___
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 43 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAmUxDAxeFQ-F-ALeW:-NJElbZZ2cQ6MALupY6u:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/hooks/line-details/useGetLineDetails.ts#L43)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah, did not know that this works like this as well. Nice
</blockquote></details>

Done.
___
*[`ui/src/hooks/stops/useCreateStop.ts` line 2 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAc7J91IA16Y_hFfPN:-NJElfA61ZwSZwLGJpwl:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/hooks/stops/useCreateStop.ts#L2)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah, so I think this hook should not have a dependency to an unrelated visual component. I. would maybe extract that part to utils (?) and name it so that it is clear it returns the combination of the label & variant.
</blockquote></details>

Done.
___
*[`ui/src/utils/gql.ts` line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAodQTDF0ws2OTrMCB:-NJElgT0-NU_NbrsWVCu:b-6isd85) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/utils/gql.ts#L60)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Won't this work with just `variant: { _eq: variant }`? Doesn't it consider `null` as the value?
</blockquote></details>

Nope, it does not. If i pass it like you suggested, the entire query part will be skipped.

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 2 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/418)* status: 14 of 31 files reviewed, 4 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 69 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAhZxU0Axc8OMzLfp-:-NJQ0PD35syXUrgWbUmy:b6zjyos) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/common/RouteLineTableRow.tsx#L69)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Hmm I don't think it changes the type. Or well typescript does seem to think it is RouteRoute after this.

I made a little change to isRoute function. It looks kind of stupid, but at least in my IDE it seems to work perfectly at least in this case.
</blockquote></details>

Not sure what was wrong, but at least now determines the type correctly as RouteTableRowFragment instead of RouteRoute. 
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 90 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAj4kI28xrulWf2V6c:-NJQ0tByCByXGrBmZABL:b-5nwdi4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/map/RouteStopsOverlay.tsx#L90)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I have no idea what happened to variant defined in `RouteTableRowFragment`, because I remember starting the addition of variant from the route table view and seeing variant in that list. :thinking: But I have now added it again.

Btw, using pick works similarly, does not help with this.
</blockquote></details>

As discussed in slack this might have been the correction where the GQL query used RouteAllFieldsFragment when querying the data, but this was fixed to RouteTableRowFragment, which was missing this variant info. But all good :+1: 
___
*[`ui/src/generated/graphql.tsx` line 12101 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJQ2V4jC3Z_ivkSfbFJ:-NJQ2V4jC3Z_ivkSfbFK:btnzctl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/614e076acb9007faced9da8bdaa652e13f96841d/ui/src/generated/graphql.tsx#L12101)):*
> ```XML
>   priority: number;
>   on_line_id: UUID;
>   variant?: number | null | undefined;
> ```

If this is already optional, do we still need the 'undefined'? 
___
*[`ui/src/utils/gql.ts` line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAodQTDF0ws2OTrMCB:-NJQ1Ucr8-sovENXWiWs:bb71kmx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/utils/gql.ts#L60)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Nope, it does not. If i pass it like you suggested, the entire query part will be skipped.
</blockquote></details>

Okay

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/418)* status: 14 of 31 files reviewed, 5 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 90 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAj4kI28xrulWf2V6c:-NJQ3nP-Cg88pm_52Y3y:bx9vvke) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/map/RouteStopsOverlay.tsx#L90)):*
> RouteMetadataFragment
Oh, btw the `variant` is still missing from this fragment, so the typing is wrong.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/418)* status: 14 of 32 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 90 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJAj4kI28xrulWf2V6c:-NJdvwkC0HnpZySMGbhb:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8a6200027fbdc9241aedea4d042b479e1a7ca835/ui/src/components/map/RouteStopsOverlay.tsx#L90)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

> RouteMetadataFragment
Oh, btw the `variant` is still missing from this fragment, so the typing is wrong.
</blockquote></details>

Done.
___
*[`ui/src/generated/graphql.tsx` line 12101 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJQ2V4jC3Z_ivkSfbFJ:-NJdw4PI1xm6gCaY_845:b-ku0i1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/614e076acb9007faced9da8bdaa652e13f96841d/ui/src/generated/graphql.tsx#L12101)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

If this is already optional, do we still need the 'undefined'? 
</blockquote></details>

This is generated code

**Review by HenrikHartiala — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/418)* status: 14 of 32 files reviewed, 2 unresolved discussions

___
*[`ui/src/generated/graphql.tsx` line 12101 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/418#-NJQ2V4jC3Z_ivkSfbFJ:-NJiYl0_CgsDxVfCuWKN:b-fn8mpi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/614e076acb9007faced9da8bdaa652e13f96841d/ui/src/generated/graphql.tsx#L12101)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This is generated code
</blockquote></details>

:facepalm:

**Pull request merged**
