### PR TITLE
Refactor state slices from Context to Redux

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/134)

Resolves HSLdevcom/jore4[#707](https://github.com/HSLdevcom/jore4-ui/issues/707)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/134)* status: 0 of 19 files reviewed, 7 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/routes-and-lines/LineDetailsPage.tsx, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU1e3O-PgP0PEqytZ2:-MzU1e3P--LVmuWOtGDo:bmtfbe5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/components/routes-and-lines/LineDetailsPage.tsx#L13)):*
> ```XML
> import { useAppDispatch } from '../../hooks';
> import { Column, Container, Row } from '../../layoutComponents';
> import { setIsOpenAction } from '../../redux';
> ```

this is a very generic name for an action. I'd say let's rather import this from `../../redux/slices/modalMap` to clarify the namespace that _where_ you'd like to open something :)
___
*[src/redux/index.ts, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU2Hmc9MORpjdoB7hT:-MzU2Hmc9MORpjdoB7hU:b-clqi66) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/redux/index.ts#L3)):*
> ```XML
> export * from './selectors';
> export * from './slices/map';
> export * from './slices/modalMap';
> ```

let's talk about this on Slack or somewhere... as we're gonna have TONS of actions and selectors (because having routes/timetables/etc modules on the UI), I'd suggest that we don't actually group these imports all under `../redux` but leave them as is, so the imports become "namespaced"
___
*[src/redux/rootReducer.ts, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU2dRi8h4QN56f_Qzd:-MzU2dRi8h4QN56f_Qze:b-3jy7cw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/redux/rootReducer.ts#L3)):*
> ```XML
> import { AnyAction, combineReducers } from '@reduxjs/toolkit';
> import { mapReducer } from './slices/map';
> import { modalMapReducer } from './slices/modalMap';
> ```

no issues with dependency cycles? Nice! :)
___
*[src/redux/selectors/index.ts, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU3R3n4us_5N490HJP:-MzU3R3n4us_5N490HJQ:bfte7tm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4b3c0eb1e6eb866ea6d8db36f96462ac5ae3b167/src/redux/selectors/index.ts#L14)):*
> ```XML
> export const selectSelectIsModalMapOpen = createSelector(
>   selectModalMap,
>   ({ isOpen }) => isOpen,
> ```

personal opinion: I think destructuring here is actually making the code harder to read/follow. I'd rather go with `(modalMap) => modalMap.isOpen`
___
*[src/redux/selectors/index.ts, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU2q4m0mQQl3Nlo5ZI:-MzU2q4m0mQQl3Nlo5ZJ:b-oa8c4t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/redux/selectors/index.ts#L4)):*
> ```XML
> import { RootState } from '../store';
> 
> export const selectMap = (state: RootState) => state.map;
> ```

maybe could comment here that slice selectors should not be memoized with `createSelector`?
___
*[src/components/UserProvider.tsx, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzTzdPMBFSxSx3tG1kr:-MzTzdPMBFSxSx3tG1ks:bkgj1zn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/components/UserProvider.tsx#L4)):*
> ```XML
> import { Api } from '../api';
> import { useAppDispatch } from '../hooks';
> import { loginFailed, loginSuccess } from '../redux/slices/user';
> ```

Shouldn't these be called loginFailedAction and loginSuccessAction, for clarity?
___
*[src/components/UserProvider.tsx, line 22 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU-2is1M7oZbw3bEeN:-MzTzyW9DCStQIvDDgm1:bwta6ep) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/components/UserProvider.tsx#L22)):*
> ```XML
>   }, [getUserInfo]);
> 
>   return null;
> ```

I'd rather return `<>{children}</>` so that this component could still be used as a wrapper around other providers

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/134)* status: 0 of 23 files reviewed, 7 unresolved discussions (waiting on @pallost)

___
*[src/components/routes-and-lines/LineDetailsPage.tsx, line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU1e3O-PgP0PEqytZ2:-MzUeKLT48sY_TDhC30a:br0bztg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/components/routes-and-lines/LineDetailsPage.tsx#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is a very generic name for an action. I'd say let's rather import this from `../../redux/slices/modalMap` to clarify the namespace that _where_ you'd like to open something :)
</blockquote></details>

Better now?
___
*[src/redux/index.ts, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU2Hmc9MORpjdoB7hT:-MzUeNTr1iMgBgowi85E:b-6jmrf1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/redux/index.ts#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's talk about this on Slack or somewhere... as we're gonna have TONS of actions and selectors (because having routes/timetables/etc modules on the UI), I'd suggest that we don't actually group these imports all under `../redux` but leave them as is, so the imports become "namespaced"
</blockquote></details>

Discussion had in Slack and seems like we can continue with this pattern.
___
*[src/redux/rootReducer.ts, line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU2dRi8h4QN56f_Qzd:-MzUN8Cj-je1CUDBw6lo:b-x03yqd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/redux/rootReducer.ts#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

no issues with dependency cycles? Nice! :)
</blockquote></details>

Yep, no cycles as slices don't have to know about other slices or other things around those :)
___
*[src/redux/selectors/index.ts, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU3R3n4us_5N490HJP:-MzUNfwV9ZxJBlYA1rRM:bkcqf1x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4b3c0eb1e6eb866ea6d8db36f96462ac5ae3b167/src/redux/selectors/index.ts#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

personal opinion: I think destructuring here is actually making the code harder to read/follow. I'd rather go with `(modalMap) => modalMap.isOpen`
</blockquote></details>

Ok, will change this
___
*[src/redux/selectors/index.ts, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU2q4m0mQQl3Nlo5ZI:-MzUeXF13TZiE-nEA5wc:b-6xn1g5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/redux/selectors/index.ts#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe could comment here that slice selectors should not be memoized with `createSelector`?
</blockquote></details>

Does it matter?
___
*[src/components/UserProvider.tsx, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzTzdPMBFSxSx3tG1kr:-MzUMp6Y-S_6lvMS18OP:b-qrjabz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/components/UserProvider.tsx#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Shouldn't these be called loginFailedAction and loginSuccessAction, for clarity?
</blockquote></details>

As you wish
___
*[src/components/UserProvider.tsx, line 22 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzU-2is1M7oZbw3bEeN:-MzUMqzU05EGu8NxhPQI:b-qrjabz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b7b8ab4c5992f00fb35f3ebc441d4143123e891d/src/components/UserProvider.tsx#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather return `<>{children}</>` so that this component could still be used as a wrapper around other providers
</blockquote></details>

As you wish

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/134)* status: 0 of 23 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/redux/selectors/index.ts, line 13 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/134#-MzUii8uCVExrnkXBJXd:-MzUlf-xCJcS3NtSNHrV:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/582f56a24c5fc2fcce86ad0f2f70d825ad1bc490/src/redux/selectors/index.ts#L13)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

selectSelect :)
</blockquote></details>

Done.

**Comment by tk-vincit** [comment]
E2e tests are currently broken due to reasons not related to this PR, so merging this anyway.

**Pull request merged**
