### PR TITLE
Use timetables data inserter in timetablesPassingTimes.cy.ts and time…

### PR DESCRIPTION
**Pull request by sr-vala**
…tableValidityPeriod.cy.ts

- Remove an unrelated assertion from the timetablesPassingTimes test
- Make the describe title of timetablePassingTimes more descriptive
- Add timetables test data and setups and teardowns to both specs

Resolves HSLdevcom/jore4#1434

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714)* status: all files reviewed, 13 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 210 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1ILqEyL8McVkVFLI:-NjH1ILqEyL8McVkVFLJ:b-w42cp8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L210)):*
> ```XML
>         {
>           scheduled_stop_point_sequence: 1,
>           scheduled_stop_point_label: 'H1231',
> ```

You should have `timing_place_label` set for the 1st, 3rd and 4th stop point.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 228 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1ck-ANA_ArWb-3-a:-NjH1ck-ANA_ArWb-3-b:bar4p2y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L228)):*
> ```XML
>   },
>   _vehicle_schedule_frames: {
>     spring2023: {
> ```

Rename `spring2023` to `year2023`
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 231 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1bcN7yDQTMFFdM50:-NjH1bcN7yDQTMFFdM51:b-7z69sv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L231)):*
> ```XML
>       validity_start: DateTime.fromISO('2023-01-01'),
>       validity_end: DateTime.fromISO('2023-12-31'),
>       name: 'Kevät 2023',
> ```

Vuosi
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 232 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1hFB8rD5y84kjwJ8:-NjH1hFB8rD5y84kjwJ9:bb4d1w1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L232)):*
> ```XML
>       validity_end: DateTime.fromISO('2023-12-31'),
>       name: 'Kevät 2023',
>       booking_label: 'Spring booking label',
> ```

Change "Spring" to some more descriptive e.g. "Year".
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 234 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1pi58kQJWKhnCtww:-NjH1pi58kQJWKhnCtwx:b4pxb6y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L234)):*
> ```XML
>       booking_label: 'Spring booking label',
>       _vehicle_services: {
>         monFri: {
> ```

Replace `monFri` with `sat` or `saturday`.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH25Cp-rR2tKFd_UE4:-NjH25Cp-rR2tKFd_UE5:b-nroag8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L249)):*
> ```XML
>                     {
>                       _scheduled_stop_point_label: 'H1232',
>                       arrival_time: Duration.fromISO('PT7H12M'),
> ```

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 275 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2KPe72GtGep-SnLk:-NjH2KPe72GtGep-SnLl:b-nroag8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L275)):*
> ```XML
>                       _scheduled_stop_point_label: 'H1232',
>                       arrival_time: Duration.fromISO('PT8H22M'),
>                       departure_time: Duration.fromISO('PT8H23M'),
> ```

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 213 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2mHL8Tdb7SWjzK0k:-NjH2mHL8Tdb7SWjzK0l:b-w42cp8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L213)):*
> ```XML
>         },
>         {
>           scheduled_stop_point_sequence: 2,
> ```

You should have `timing_place_label` set for the 1st, 3rd and 4th stop point.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 228 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH34LE9wMjYn91JWeg:-NjH34LE9wMjYn91JWeh:bar4p2y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L228)):*
> ```XML
>   },
>   _vehicle_schedule_frames: {
>     spring2023: {
> ```

Rename `spring2023` to `year2023`
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 231 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2yhz3yMW3lnZyupn:-NjH2yhz3yMW3lnZyupo:b-7z69sv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L231)):*
> ```XML
>       validity_start: DateTime.fromISO('2023-01-01'),
>       validity_end: DateTime.fromISO('2023-12-31'),
>       name: 'Kevät 2023',
> ```

Vuosi
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 232 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2xMhEmmDUMbZ9vcG:-NjH2xMhEmmDUMbZ9vcH:bb4d1w1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L232)):*
> ```XML
>       validity_end: DateTime.fromISO('2023-12-31'),
>       name: 'Kevät 2023',
>       booking_label: 'Spring booking label',
> ```

Change "Spring" to some more descriptive e.g. "Year".
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH3AUz-uS-5gKYT7t4:-NjH3AV-9TiH__gBTiWA:b-nroag8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L249)):*
> ```XML
>                     {
>                       _scheduled_stop_point_label: 'H1232',
>                       arrival_time: Duration.fromISO('PT7H12M'),
> ```

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 274 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH3Bvm62vWHqltBJ-B:-NjH3Bvm62vWHqltBJ-C:b-nroag8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L274)):*
> ```XML
>                     {
>                       _scheduled_stop_point_label: 'H1232',
>                       arrival_time: Duration.fromISO('PT8H22M'),
> ```

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714)* status: all files reviewed, 13 unresolved discussions (waiting on @jarkkoka and @sr-vala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH25Cp-rR2tKFd_UE4:-NjSOsTC0y6lLpa8Deo-:b-rsbwae) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L249)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.
</blockquote></details>

Our DB constraints require all stops to have both arrival and departure times though, unless they are first or last. See https://github.com/HSLdevcom/jore4-hasura/blob/5c29d7e8103145ac12554a01da6e04a9b08be784/migrations/timetablesdb-dump.sql#L1481C1-L1493C12

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714)* status: all files reviewed, 13 unresolved discussions (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH25Cp-rR2tKFd_UE4:-NjSVd1k4K4I0jtG-BZ7:b-vurqw4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L249)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Our DB constraints require all stops to have both arrival and departure times though, unless they are first or last. See https://github.com/HSLdevcom/jore4-hasura/blob/5c29d7e8103145ac12554a01da6e04a9b08be784/migrations/timetablesdb-dump.sql#L1481C1-L1493C12
</blockquote></details>

Actually, the problem is that arrival time should equal to departure time. Discussed in Slack.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714)* status: all files reviewed, 13 unresolved discussions (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH3AUz-uS-5gKYT7t4:-NjSW3uiC2aHfDD6-F6o:bdfcb3h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L249)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.
</blockquote></details>

Actually, the problem is that arrival time should equal to departure time when the stop point is not used as timing point. Discussed in Slack.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714)* status: all files reviewed, 13 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 210 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1ILqEyL8McVkVFLI:-NjptintEbGZErsfInXV:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L210)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You should have `timing_place_label` set for the 1st, 3rd and 4th stop point.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 228 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1ck-ANA_ArWb-3-a:-NjptiODADNiVzfZyfAJ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L228)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Rename `spring2023` to `year2023`
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 231 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1bcN7yDQTMFFdM50:-Njpthp_4I4YFjyzk4Pq:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L231)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Vuosi
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 232 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1hFB8rD5y84kjwJ8:-Njpthch9nNI7VdYo14x:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L232)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Change "Spring" to some more descriptive e.g. "Year".
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 234 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH1pi58kQJWKhnCtww:-NjpthF280FOnmjLB0eu:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L234)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Replace `monFri` with `sat` or `saturday`.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH25Cp-rR2tKFd_UE4:-NjptgSK5zDFiiNBY19x:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L249)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Actually, the problem is that arrival time should equal to departure time. Discussed in Slack.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 275 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2KPe72GtGep-SnLk:-Njptfbn3UayUmzkF9zY:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetablePassingTimes.cy.ts#L275)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 213 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2mHL8Tdb7SWjzK0k:-NjptesA0YIzHvu2_6iD:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L213)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You should have `timing_place_label` set for the 1st, 3rd and 4th stop point.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 228 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH34LE9wMjYn91JWeg:-NjpteKP7fB9aCTRSuN7:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L228)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Rename `spring2023` to `year2023`
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 231 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2yhz3yMW3lnZyupn:-NjpteAA5fFoRILnngMw:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L231)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Vuosi
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 232 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH2xMhEmmDUMbZ9vcG:-Njptdvw70SaX1uQmsbn:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L232)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Change "Spring" to some more descriptive e.g. "Year".
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH3AUz-uS-5gKYT7t4:-NjptdSU0ikMF9nTM-Dz:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L249)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Actually, the problem is that arrival time should equal to departure time when the stop point is not used as timing point. Discussed in Slack.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableValidityPeriod.cy.ts` line 274 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-NjH3Bvm62vWHqltBJ-B:-NjptdDZ1iqV46mjC8-D:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/73c5f844cb9eccffeb6822e654ed89bf8977986f/cypress/e2e/timetableValidityPeriod.cy.ts#L274)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In realistic data, since the 2nd stop is not a timing point, it should not have an arrival time property set.
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/714#-:-NjvhZVG47xU5HCueqnJ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
