### PR TITLE
Change validity time type to 'date'

### PR DESCRIPTION
**Pull request by jschummer**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/351)

### CODE REVIEW

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/351)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @jschummer)

___
*[`codegen/codegen.js` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_VfUP1RbvAqYwUx9D:-NE_VfUP1RbvAqYwUx9E:b90u6i2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/codegen/codegen.js#L10)):*
> ```JavaScript
>   geography_linestring: 'GeoJSON.LineString',
>   localized_string: 'LocalizedString',
>   date: 'luxon.DateTime',
> ```

Was a bit worried as now we are mapping field with only date to a DateTime object that also models time, but as discussed in slack, it might be that we don't have good alternatives :/ 
___
*[`ui/src/graphql/client.ts` line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_cdkT-R4ALOLSqk9e:-NE_cdkT-R4ALOLSqk9f:bd6zrrx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/ui/src/graphql/client.ts#L23)):*
> ```XML
>     date: {
>       serialize: (parsed: unknown) => {
>         // if it's a luxon DateTime, serialize it to ISO string
> ```

This comment is not valid anymore. "serialize it to ISO date string"?
___
*[`ui/src/graphql/client.ts` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_eNUK8Q_zbbVKv6Ad:-NE_eNULBOCMtY8Eyfbn:b-ldpi0n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/ui/src/graphql/client.ts#L25)):*
> ```XML
>         // if it's a luxon DateTime, serialize it to ISO string
>         if (DateTime.isDateTime(parsed)) {
>           return parsed.toFormat('yyyy-LL-dd');
> ```

LL format was confusing. Seems like you could replace it with `MM`, but that is still a bit confusing so not sure it is worth it to change this :shrug: 

https://moment.github.io/luxon/#/formatting?id=table-of-tokens

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/351)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[`codegen/codegen.js` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_VfUP1RbvAqYwUx9D:-NFi-OJkC2rIvKMvoI4p:bfnsjc8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/codegen/codegen.js#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Was a bit worried as now we are mapping field with only date to a DateTime object that also models time, but as discussed in slack, it might be that we don't have good alternatives :/ 
</blockquote></details>

Yes, it looks a bit strange, but maybe not bad after all. Just have to keep in mind that the resolution is "day"..
___
*[`ui/src/graphql/client.ts` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_eNUK8Q_zbbVKv6Ad:-NFi-YLJ9jwnMCDuGNFz:b-y0xl1o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/ui/src/graphql/client.ts#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

LL format was confusing. Seems like you could replace it with `MM`, but that is still a bit confusing so not sure it is worth it to change this :shrug: 

https://moment.github.io/luxon/#/formatting?id=table-of-tokens
</blockquote></details>

Like discussed elsewhere, MM seems to mean something else (minutes, I think).

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/351)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/graphql/client.ts` line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_cdkT-R4ALOLSqk9e:-NFi-vLg8S3Ijesr1dd_:b-fm2te8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/ui/src/graphql/client.ts#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This comment is not valid anymore. "serialize it to ISO date string"?
</blockquote></details>

True, fixed it.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/351)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[`ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx` line 43 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NFi1KGn5GO6sJj7cC-n:-NFi1KGn5GO6sJj7cC-o:b6bnue1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6a003114229b328b7135c3239f51a8eb3d3566cb/ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx#L43)):*
> ```XML
>     passingTime.timetabled_passing_time_id;
> 
>   // Display arrival time only if it differs from passing time (!== operator does not work in the expec)
> ```

What does "in the expec" mean?
___
*[`ui/src/graphql/client.ts` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_eNUK8Q_zbbVKv6Ad:-NFi1oUG3l976ZKTg8t-:btpy6b8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/ui/src/graphql/client.ts#L25)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Like discussed elsewhere, MM seems to mean something else (minutes, I think).
</blockquote></details>

`mm` is minutes, `MM` is month as a padded number.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/351)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx` line 43 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NFi1KGn5GO6sJj7cC-n:-NFi5v28ATsHXHqkofEx:b64apd7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6a003114229b328b7135c3239f51a8eb3d3566cb/ui/src/components/vehicle-service/passing-times-by-stop/PassingTimesByStopTableRowPassingMinute.tsx#L43)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What does "in the expec" mean?
</blockquote></details>

I blame my keyboard, it should have said "in the expected way". Fixed it.
___
*[`ui/src/graphql/client.ts` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/351#-NE_eNUK8Q_zbbVKv6Ad:-NFi5jW28wVGC03e_dwr:b-978uav) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afbcfc3460074711e1b12b984babacb14e92a5cc/ui/src/graphql/client.ts#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`mm` is minutes, `MM` is month as a padded number.
</blockquote></details>

Oh yes, I didn't notice the separate "standalone" and "format" token columns :+1:

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/351)* status: 0 of 16 files reviewed, all discussions resolved

**Pull request closed without merging**
