### PR TITLE
Add measurements and accessibility details to stop details page

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822)

### CODE REVIEW

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822)* status: 0 of 24 files reviewed, all discussions resolved

___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 287 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyJjv5B5QWcpY1gaaOV:-NyJjv5B5QWcpY1gaaOW:bpf2w1a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0f7a0ef1ed6f6c10e44e56269b15ead0cc633863/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L287)):*
> ```XML
>                 </div>
>               )}
>             />
> ```

Note: this part gets simplified in a further commit.



_Code quote:_
```XML
              inputElementRenderer={(props) => (
                <div className="inline-flex items-center">
                  <EnumDropdown<StopRegistryPedestrianCrossingRampType>
                    enumType={StopRegistryPedestrianCrossingRampType}
                    placeholder={t(
                      'stopDetails.measurements.pedestrianCrossingRampType',
                    )}
                    uiNameMapper={
                      mapStopRegistryPedestrianCrossingRampTypeToShortUiName
                    }
                    buttonClassNames="min-w-28"
                    // eslint-disable-next-line react/jsx-props-no-spreading
                    {...props}
                  />
                  <i
                    className="icon-info text-2xl text-brand"
                    title="Luiskaus info, TODO"
                  />
                </div>
              )}
            />
```

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 10 of 10 files at r3, 13 of 13 files at r5, 13 of 13 files at r6, 8 of 8 files at r7, 4 of 4 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822)* status: all files reviewed, 7 unresolved discussions (waiting on @Leitsi)

___
*[`test-db-manager/src/generated/graphql.ts` line 9665 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyJp1GA2YiLqY2EJoIR:-NyJp1GA2YiLqY2EJoIS:bqrviuo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e592170ad568daf8175dfc23973e21a3cc371b3f/test-db-manager/src/generated/graphql.ts#L9665)):*
> ```XML
> export type StopRegistryHslAccessibilityProperties = {
>   __typename?: 'stop_registry_HslAccessibilityProperties';
>   /** Reunakiven etäisyys kiskon selästä (cm) */
> ```

Not part of this UI PR, and since this uses main image of tiamat, this is a bit too late (would require another PR to tiamat), but I think these comments / descriptions should be in english, not in finnish.
___
*[`ui/src/components/forms/common/customZodSchemas.ts` line 47 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKYSa_8-AEwAFBPyPT:-NyKYSa_8-AEwAFBPyPU:b-542mkg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7642d9772e8b439dfd1c7d31f39286418d4f4344/ui/src/components/forms/common/customZodSchemas.ts#L47)):*
> ```XML
> // A helper to create zod enums for fields that accept booleans + null.
> // Intended to be used with `NullableBooleanDropdown`.
> export const nullableBoolean = z.any().transform((value): boolean | null => {
> ```

:ok_hand: nice
___
*[`ui/src/components/forms/common/EnumDropdown.tsx` line 20 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKHm-Z0YbIXu8v2pDO:-NyKHm-Z0YbIXu8v2pDP:b-lwbve1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/forms/common/EnumDropdown.tsx#L20)):*
> ```XML
>   uiNameMapper: (key: TEnum) => string;
>   placeholder: string;
>   buttonClassNames?: string;
> ```

NIT. I think the plural is redundant here



_Suggestion:_
```XML
  buttonClassName?: string;
```
___
*[`ui/src/components/forms/common/NullableBooleanDropdown.tsx` line 48 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKWvPO95OMH2s828NZ:-NyKWvPO95OMH2s828N_:bwmsdvm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7642d9772e8b439dfd1c7d31f39286418d4f4344/ui/src/components/forms/common/NullableBooleanDropdown.tsx#L48)):*
> ```XML
> 
>   const uiNameMapper = (val: string) => {
>     if (val === 'true')
> ```

I personally don't like one liner if's (or if's without a code block) , and would use curly brackets to make the code block explicit and more readable and debuggable. But you could also use switch case here. Doesn't matter that much so up to you.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 75 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKQiHU9SHVT3E4HwQ_:-NyKQiHU9SHVT3E4HwQa:byp99lz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L75)):*
> ```XML
>     <FormProvider {...methods}>
>       <form
>         className={twMerge('flex flex-col space-y-4', className)}
> ```

NIT, Could use <FormColumn> or <Column> component instead of giving these classNames to form, to separate the layout effects from <form> component.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 117 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKJyu0Dz3nguRJ7kSj:-NyKJyu0Dz3nguRJ7kSk:bgyzf3v) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L117)):*
> ```XML
>             fieldPath="shelterLaneDistance"
>             className="max-w-36"
>             inputClassName="w-20"
> ```

I'd still rather use CSS grid features in combination with relative widths for layout rather than explicit pixel widths, but that would minorly change the design also (which I would also do though) and I think we've had this discussion already, so not a blocking comment.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 147 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKL6UU7575Sxr0U2C3:-NyKL6UU7575Sxr0U2C4:b-p2kzt7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L147)):*
> ```XML
>           />
>         </Row>
>         <Row className="shrink flex-wrap items-end gap-4 md:flex-nowrap">
> ```

This `md:flex-nowrap` causes overflow with certain screen widths.

Also do we need this `shrink`? Feels extra
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx` line 206 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyK4YW51U-cA-CLdn5r:-NyK4YW51U-cA-CLdn5s:bh0emab) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/463b8ff6d3187efc7610eb6894abf660eeff03fd/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx#L206)):*
> ```XML
>         <LabeledDetail
>           title={t('stopDetails.measurements.stopAreaSurroundingsAccessible')}
>           detail={optionalBooleanToUiText(
> ```

This inline could also use a const.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/schema.ts` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKUXvY9vx4_8IFsS3O:-NyKUXvZEtqIVOwPJflh:b9zylf5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/schema.ts#L24)):*
> ```XML
>   serviceAreaWidth: nullableNumber,
>   serviceAreaLength: nullableNumber,
>   // TODO: make sure these can be nulled.
> ```

Is this still relevant TODO?

EDIT: oh, it was removed in another commit. Could've been a fixup commit as well, but all good :+1: 
___
*[`ui/src/locales/fi-FI/common.json` line 187 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyK2mve7GyfJ_O8Rhw5:-NyK2mve7GyfJ_O8Rhw6:b-lhc85s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/463b8ff6d3187efc7610eb6894abf660eeff03fd/ui/src/locales/fi-FI/common.json#L187)):*
> ```JSON
>       "curvedStop": "Kaareva",
>       "shelterType": "Katos",
>       "shelterLaneDistance": "Katoksen ja ajoradan välinen leveys\u00A0(cm)",
> ```

I checked the designs and noticed that the units (cm, m) are on the "label" line, and if this is not particular requirement, I would definitely drop the units on the same level as the actual values and also on edit side, next to the input fields. I think thats more readable and better UX.
This would require refactoring of LabeledDetail or probably better would be to just add another component for units.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822)* status: all files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test-db-manager/src/generated/graphql.ts` line 9665 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyJp1GA2YiLqY2EJoIR:-NyKmOdhAeY6-3uIwjwI:b-8a5jyn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e592170ad568daf8175dfc23973e21a3cc371b3f/test-db-manager/src/generated/graphql.ts#L9665)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Not part of this UI PR, and since this uses main image of tiamat, this is a bit too late (would require another PR to tiamat), but I think these comments / descriptions should be in english, not in finnish.
</blockquote></details>

Rationale (mine) for this was that the GraphQL API might eventually be accessed by someone else as well. HSL personnel is probably more familiar with Finnish terms (especially since some/most of these english terms have been made up by us), so providing some kind of English-Finnish mapping for them might be helpful. Thought that the GraphQL API comments might be the most accessible, no need to know where some wiki documentation resides etc.
Having these in English would be quite useless, since the property names already tell the same info (sans units of course).
Related Tiamat commit, though it doesn't really have any further info  https://github.com/HSLdevcom/jore4-tiamat/commit/c04f24435e307c6c85510f3460d617d38b2fdb87
___
*[`ui/src/components/forms/common/customZodSchemas.ts` line 47 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKYSa_8-AEwAFBPyPT:-NyKn8WV7GSDtBxRR_P0:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7642d9772e8b439dfd1c7d31f39286418d4f4344/ui/src/components/forms/common/customZodSchemas.ts#L47)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

:ok_hand: nice
</blockquote></details>

Done.
___
*[`ui/src/components/forms/common/EnumDropdown.tsx` line 20 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKHm-Z0YbIXu8v2pDO:-NyKnB4uCEeIfhD4hm7t:bi8swor) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/forms/common/EnumDropdown.tsx#L20)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT. I think the plural is redundant here
</blockquote></details>

Fixed. I blame the other component from which I copypasted this from. Considered fixing that as well but seemed like that would bloat this PR quite a bit, since there's several components with this issue. Not fixing those for now.
___
*[`ui/src/components/forms/common/NullableBooleanDropdown.tsx` line 48 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKWvPO95OMH2s828NZ:-NyKnlZ3BTDMQi--tZUn:bxy6r9b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7642d9772e8b439dfd1c7d31f39286418d4f4344/ui/src/components/forms/common/NullableBooleanDropdown.tsx#L48)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I personally don't like one liner if's (or if's without a code block) , and would use curly brackets to make the code block explicit and more readable and debuggable. But you could also use switch case here. Doesn't matter that much so up to you.
</blockquote></details>

Hmm, meant to have curly braces, weird that our linter even allows this.
Changed to switch case, less bloaty.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 75 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKQiHU9SHVT3E4HwQ_:-NyLRn7W3o_Vo7P5l18f:b2mpmzw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L75)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, Could use <FormColumn> or <Column> component instead of giving these classNames to form, to separate the layout effects from <form> component.
</blockquote></details>

Feels like some of your comment got lost, but added a `Column` here and moved the `space-y-4` there.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 117 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKJyu0Dz3nguRJ7kSj:-NyKo05v2zNNJrAlHMV2:bhowg66) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L117)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I'd still rather use CSS grid features in combination with relative widths for layout rather than explicit pixel widths, but that would minorly change the design also (which I would also do though) and I think we've had this discussion already, so not a blocking comment.
</blockquote></details>

Yep, would majorly change the design, and due to such big variance between input/label widths here I'd rather not do that. Even if we have to micromanage the widths now (which isn't too bad really).
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 147 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKL6UU7575Sxr0U2C3:-NyLQHt003WgsgcxJb1B:b-jrz3y2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L147)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This `md:flex-nowrap` causes overflow with certain screen widths.

Also do we need this `shrink`? Feels extra
</blockquote></details>

`shrink` not seeming to do anything indeed, leftover from some earlier attempt or something.

Changed the `md:` to `lg:` which solves the overflow issue, still works sensibly with normal screen sizes.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/schema.ts` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKUXvY9vx4_8IFsS3O:-NyLN-rWBWs80soIrOoX:bfz0o32) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/schema.ts#L24)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Is this still relevant TODO?

EDIT: oh, it was removed in another commit. Could've been a fixup commit as well, but all good :+1:
</blockquote></details>

Left as separate because there was quite a few details related to implementing the boolean selects.
___
*[`ui/src/locales/fi-FI/common.json` line 187 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyK2mve7GyfJ_O8Rhw5:-NyLNKOn4WJG4KGY6P8r:b-lob83l) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/463b8ff6d3187efc7610eb6894abf660eeff03fd/ui/src/locales/fi-FI/common.json#L187)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I checked the designs and noticed that the units (cm, m) are on the "label" line, and if this is not particular requirement, I would definitely drop the units on the same level as the actual values and also on edit side, next to the input fields. I think thats more readable and better UX.
This would require refactoring of LabeledDetail or probably better would be to just add another component for units.
</blockquote></details>

Perhaps, but this was a design decision. Also feels simpler that way. Not bothering to suggest changing at this point. Good point/idea though.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822)* status: 18 of 30 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx` line 206 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyK4YW51U-cA-CLdn5r:-NyLpyir4vaQIGm72RaF:bu5a1xd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/463b8ff6d3187efc7610eb6894abf660eeff03fd/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx#L206)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This inline could also use a const.
</blockquote></details>

Maybe, but that would move it quite far from where it's used, and I don't think it's too unclear here. If this is still acceptable(ish) then I would maybe leave it like this.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 12 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`test-db-manager/src/generated/graphql.ts` line 9665 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyJp1GA2YiLqY2EJoIR:-NyUNYMWAWkl_YXE8wpN:b-rz0ywh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e592170ad568daf8175dfc23973e21a3cc371b3f/test-db-manager/src/generated/graphql.ts#L9665)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Rationale (mine) for this was that the GraphQL API might eventually be accessed by someone else as well. HSL personnel is probably more familiar with Finnish terms (especially since some/most of these english terms have been made up by us), so providing some kind of English-Finnish mapping for them might be helpful. Thought that the GraphQL API comments might be the most accessible, no need to know where some wiki documentation resides etc.
Having these in English would be quite useless, since the property names already tell the same info (sans units of course).
Related Tiamat commit, though it doesn't really have any further info  https://github.com/HSLdevcom/jore4-tiamat/commit/c04f24435e307c6c85510f3460d617d38b2fdb87
</blockquote></details>

Yeah ok that is a good explanation. I think I just got caught up in the Finnish comments in the code provided by our graphQL generator, and also the Finnish explanations via intellisense when hovering. It just felt very odd, but it is true that the property name is probably good enough. For cosmetics I'd still add the comments in english as well, but probably not worth it.
___
*[`ui/src/components/forms/common/EnumDropdown.tsx` line 20 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKHm-Z0YbIXu8v2pDO:-NyUC9tMCTgGTnJInsG9:b-k4j1l4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/forms/common/EnumDropdown.tsx#L20)):*
Oh right, there are quite a few components using this as plural. 

> Fixed.

Still seems to be plural here
___
*[`ui/src/components/forms/common/NullableBooleanDropdown.tsx` line 48 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKWvPO95OMH2s828NZ:-NyUCxAtCQPQElFs6Ifm:b-8s5aon) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7642d9772e8b439dfd1c7d31f39286418d4f4344/ui/src/components/forms/common/NullableBooleanDropdown.tsx#L48)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Hmm, meant to have curly braces, weird that our linter even allows this.
Changed to switch case, less bloaty.
</blockquote></details>

Yeah, good one, could be a linting rule as well. I think at some point we had developers here who preferred if's without a code block for a reason or another, but probably not anymore so we could add the rule. https://eslint.org/docs/latest/rules/curly

I can add this rule and create a PR about it.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 75 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKQiHU9SHVT3E4HwQ_:-NyUFR7P6c9mkjNE6CJg:b-9xlpxr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L75)):*
Yes, my mistake :D AGAIN with the HTML element syntax that disappear in reviewable. Not the first time, probably not the last time :D 
> NIT, Could use `<FormColumn>` or `<Column>` ...

But anyway, thanks!
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 117 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKJyu0Dz3nguRJ7kSj:-NyUFul96gorlncIBnfW:bz0kq57) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L117)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Yep, would majorly change the design, and due to such big variance between input/label widths here I'd rather not do that. Even if we have to micromanage the widths now (which isn't too bad really).
</blockquote></details>

Well, not _majorly_. Even pretty much the same design should be achievable without the precise widths, although like said before, I would also change the design so that everything is more or less in line with each other, but thats another story so let's go with this one.
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx` line 147 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKL6UU7575Sxr0U2C3:-NyUKQF22BfThTztFfkV:b-ngmcvy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsForm.tsx#L147)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

`shrink` not seeming to do anything indeed, leftover from some earlier attempt or something.

Changed the `md:` to `lg:` which solves the overflow issue, still works sensibly with normal screen sizes.
</blockquote></details>

Thanks! this solved the issue as you said :ok_hand: 
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx` line 206 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyK4YW51U-cA-CLdn5r:-NyUL4mi7jnjA3c0SBVI:b-8jgc2e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/463b8ff6d3187efc7610eb6894abf660eeff03fd/ui/src/components/stop-registry/stops/stop-details/measurements/MeasurementsViewCard.tsx#L206)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Maybe, but that would move it quite far from where it's used, and I don't think it's too unclear here. If this is still acceptable(ish) then I would maybe leave it like this.
</blockquote></details>

Yeah, I was checking that some of the other details were put in a const, but it is true that this is very clear component otherwise so this is actually also clear like it is. So all good :+1: 
___
*[`ui/src/components/stop-registry/stops/stop-details/measurements/schema.ts` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyKUXvY9vx4_8IFsS3O:-NyULeIR18YyslK40brn:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bfa5afbe2993c1122ba4e55551c1e35314bf3cad/ui/src/components/stop-registry/stops/stop-details/measurements/schema.ts#L24)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Left as separate because there was quite a few details related to implementing the boolean selects.
</blockquote></details>

:+1: 
___
*[`ui/src/locales/fi-FI/common.json` line 187 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/822#-NyK2mve7GyfJ_O8Rhw5:-NyUNG4q0BHljIWG4WxF:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/463b8ff6d3187efc7610eb6894abf660eeff03fd/ui/src/locales/fi-FI/common.json#L187)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Perhaps, but this was a design decision. Also feels simpler that way. Not bothering to suggest changing at this point. Good point/idea though.
</blockquote></details>

:+1:

**Pull request merged**
