### PR TITLE
Frontend template

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/2)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/2)* status: 0 of 21 files reviewed, 7 unresolved discussions (waiting on @tk-vincit)

___
*[Dockerfile, line 7 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqVBFc-oxxsMXtmLQR:-MXqVBFdEIXdcv1r79em:b13khcm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/Dockerfile#L7)):*
> ```Dockerfile
> COPY ./src ./src
> COPY ./public ./public
> COPY tsconfig.json .prettierignore ./
> ```

you should not need the .prettierignore file to build the bundle
___
*[README.md, line 15 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqWsg222s5X3ZvhtbN:-MXqWsg222s5X3ZvhtbO:by078yp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/590a8fd329992c611cbc686287894a40a6a2388b/README.md#L15)):*
> ```Markdown
> Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.
> 
> You can start editing the page by modifying `pages/index.js`. The page auto-updates as you edit the file.
> ```

I think you should keep some introductory text about next.js or at least a link to its website
___
*[README.md, line 21 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqX5VB5xrzLK1AzmAC:-MXqX5VB5xrzLK1AzmAD:bx26beg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/README.md#L21)):*
> ```Markdown
> ```bash
> # build docker image
> docker build -t jore4-ui:temp --build-arg NEXT_PUBLIC_GIT_HASH=example-git-hash .
> ```

if you test it locally, you don't need to fill in the NEXT_PUBLIC_GIT_HASH variable
___
*[README.md, line 23 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqXACA6Qvw8Ut2uxOK:-MXqXACA6Qvw8Ut2uxOL:bslrpjh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/README.md#L23)):*
> ```Markdown
> docker build -t jore4-ui:temp --build-arg NEXT_PUBLIC_GIT_HASH=example-git-hash .
> # serve image in port 8080
> docker run -p 8080:80 jore4-ui:temp
> ```

as a courtesy, should also add `-d` parameter to this README about running your container, because it's pretty easy to get stuck into the attached container, not knowing what is the magical key combination to exit from it :D
___
*[src/locales/en-US/common.json, line 3 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqXwbW9WQO7cR3eJkG:-MXqXwbXAvlMKhnutFoi:b1nm9c4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/locales/en-US/common.json#L3)):*
> ```JSON
> {
>   "example": "Jore4 user interface",
>   "chooseLanguage": "Choose app's language",
> ```

should add a unit test which checks if all languages have all the same translation keys
___
*[src/pages/index.tsx, line 1 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqZ3UCEKM-PQiPzcI8:-MXqZ3UCEKM-PQiPzcI9:b-o5n727) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/pages/index.tsx#L1)):*
> ```XML
> import Head from 'next/head';
> ```

this file is actually defining a component call `Index`, so let's also rename the file to `Index.tsx`
___
*[src/styles/Home.module.css, line 1 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqYfgQ-gVfvQhSx9IK:-MXqYfgQ-gVfvQhSx9IL:b-tivrcf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/styles/Home.module.css#L1)):*
> ```CSS
> .footer {
> ```

this file should rather be named as `Index.module.css` as the referred component also has the name `Index`. Also, I'd prefer if the css files would be in the same folder as the component the are styling, so let's move this to `src/pages/Index.module.css`

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/2)* status: 0 of 21 files reviewed, 7 unresolved discussions (waiting on @pallost)

___
*[Dockerfile, line 7 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqVBFc-oxxsMXtmLQR:-MY3l0jw91SrXLPEXrco:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/Dockerfile#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should not need the .prettierignore file to build the bundle
</blockquote></details>

Done
___
*[README.md, line 15 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqWsg222s5X3ZvhtbN:-MY3l9Y874KDDoZT8t56:b-xi0yrr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/590a8fd329992c611cbc686287894a40a6a2388b/README.md#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think you should keep some introductory text about next.js or at least a link to its website
</blockquote></details>

Please see line 3 :wink: But I'll also add a little bit reasoning about it.
___
*[README.md, line 21 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqX5VB5xrzLK1AzmAC:-MY3lHrr5fN1he4nqmxZ:b-kutsfz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/README.md#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if you test it locally, you don't need to fill in the NEXT_PUBLIC_GIT_HASH variable
</blockquote></details>

Well, that's true, but I was also thinking that this might serve as an example about how to set it if you want to e.g. debug it... 
But OK, will remove that for now.
___
*[README.md, line 23 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqXACA6Qvw8Ut2uxOK:-MY44149CtM-MI7_sdYc:b-tq648q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/README.md#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as a courtesy, should also add `-d` parameter to this README about running your container, because it's pretty easy to get stuck into the attached container, not knowing what is the magical key combination to exit from it :D
</blockquote></details>

That's pretty much matter of opinion. Probably my workflow with docker is suboptimal, but I find it always a bit clumsy to figure out how to shut down containers started with `-d`. In the other hand it is very easy to shut down container with `ctrl + c` if it is not in detached mode. :smile: 
But as you wish...
___
*[src/locales/en-US/common.json, line 3 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqXwbW9WQO7cR3eJkG:-MY4Q5CVBJ0gJbFbrQgR:b-cwv2p8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/locales/en-US/common.json#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should add a unit test which checks if all languages have all the same translation keys
</blockquote></details>

Are we going to develop this app in two languages from day 0? I'll open discussion about this in slack.

Anyway, this PR doesn't yet have any test frameworks so I'll add possible unit tests in next pr.
___
*[src/pages/index.tsx, line 1 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqZ3UCEKM-PQiPzcI8:-MY4PBH32yP8TGsoCMpu:b-h3dc8i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/pages/index.tsx#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this file is actually defining a component call `Index`, so let's also rename the file to `Index.tsx`
</blockquote></details>

This comes from next's project template. This component doesn't make any _named_ export. I'll leave this like this.
___
*[src/styles/Home.module.css, line 1 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqYfgQ-gVfvQhSx9IK:-MY4P0_d3MMtTA8PpPTk:b6fx0zw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/styles/Home.module.css#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this file should rather be named as `Index.module.css` as the referred component also has the name `Index`. Also, I'd prefer if the css files would be in the same folder as the component the are styling, so let's move this to `src/pages/Index.module.css`
</blockquote></details>

This comes from next's project template. This is currently referenced in two files: 
- Main.tsx
- Index.tsx

I think that I'll leave this like this.

**Review by pallost — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 4 of 19 files at r11, 1 of 1 files at r12, 1 of 2 files at r13, 1 of 4 files at r14, 6 of 12 files at r16, 6 of 8 files at r17, 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/2)* status: all files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[README.md, line 15 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqWsg222s5X3ZvhtbN:-MY4RJkT5GaerpVjbSsU:b-v4n4py) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/590a8fd329992c611cbc686287894a40a6a2388b/README.md#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please see line 3 :wink: But I'll also add a little bit reasoning about it.
</blockquote></details>

Oh, didn't see the reference link there! Sry
___
*[src/locales/en-US/common.json, line 3 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqXwbW9WQO7cR3eJkG:-MY4RiJL6nRcKNu7omep:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/locales/en-US/common.json#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Are we going to develop this app in two languages from day 0? I'll open discussion about this in slack.

Anyway, this PR doesn't yet have any test frameworks so I'll add possible unit tests in next pr.
</blockquote></details>

OK
___
*[src/pages/index.tsx, line 1 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqZ3UCEKM-PQiPzcI8:-MY4RwPeBnpWBZygGUCf:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/pages/index.tsx#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This comes from next's project template. This component doesn't make any _named_ export. I'll leave this like this.
</blockquote></details>

OK
___
*[src/styles/Home.module.css, line 1 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqYfgQ-gVfvQhSx9IK:-MY4S-7_C3EhDdUyQBqG:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/73c77f2185f3dac12f3c371d7338094307a086a1/src/styles/Home.module.css#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This comes from next's project template. This is currently referenced in two files: 
- Main.tsx
- Index.tsx

I think that I'll leave this like this.
</blockquote></details>

OK

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/2)* status: all files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[README.md, line 15 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqWsg222s5X3ZvhtbN:-MY50IH90pninaEBYpcj:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/590a8fd329992c611cbc686287894a40a6a2388b/README.md#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Oh, didn't see the reference link there! Sry
</blockquote></details>

OK

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/2)* status: all files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[README.md, line 15 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/2#-MXqWsg222s5X3ZvhtbN:-MY50Lur8OL0L4bqxWp5:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/590a8fd329992c611cbc686287894a40a6a2388b/README.md#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

**Pull request merged**
