### PR TITLE
Add route tests related to stops

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#715

Toast checking should also work now.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/344)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/344)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @pallost and @sr-vala)

___
*[`cypress/e2e/createRoute.cy.ts` line 44 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxSgq6-g1NAVQr026y:-NCxSgq6-g1NAVQr026z:b-n0exds) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/e2e/createRoute.cy.ts#L44)):*
> ```XML
> 
>   beforeEach(() => {
>     deleteRouteByLabel(testRouteLabel1);
> ```

let's modify this to be `deleteRoutesByLabels` that takes an array of labels, instead of copy-pasting code
___
*[`cypress/pageObjects/RouteStopsOverlay.ts` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxV21K9RdXAy0FHRoO:-NCxV21K9RdXAy0FHRoP:b-cr55qz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/pageObjects/RouteStopsOverlay.ts#L8)):*
> ```XML
>   routeShouldExist(routeName: string) {
>     return cy
>       .getByTestId('RouteStopsOverlay::mapOverlayHeader')
> ```

let's split this into two functions: getHeader(), which then should be called by routeShouldExist()
___
*[`cypress/pageObjects/RouteStopsOverlay.ts` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxVdXICcTcg9Gm1hyn:-NCxVdXJETZkxjQ30i1H:b-brxtb9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/pageObjects/RouteStopsOverlay.ts#L16)):*
> ```XML
>   removeStopsFromRoute(stopLabels: string[]) {
>     stopLabels.forEach((element) => {
>       this.getRouteStop(element).find('button').click();
> ```

let's put a test id onto that button to make this test more reliable!
___
*[`cypress/pageObjects/Toast.ts` line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxVvYlCXRjDqXA9lxw:-NCxVvYlCXRjDqXA9lxx:b-1r84v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/pageObjects/Toast.ts#L27)):*
> ```XML
> 
>   checkRouteSubmitFailure() {
>     this.getDangerToast().contains('Tallennus epäonnistui');
> ```

this is not a good pattern, this should've been caught earlier. Let's rather create a function called

```
checkDangerToastHasMessage(message: string) {
  this.getDangerToast().contains(message);
}
```

and then create a function in some route related page object, like this:

```
checkRouteSubmitFailure() {
  toast.checkDangerToastHasMessage('Tallennus epäonnistui')
}
```

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/344)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[`cypress/e2e/createRoute.cy.ts` line 44 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxSgq6-g1NAVQr026y:-ND2b_gA9uRqVn-pOnlR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/e2e/createRoute.cy.ts#L44)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's modify this to be `deleteRoutesByLabels` that takes an array of labels, instead of copy-pasting code
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteStopsOverlay.ts` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxV21K9RdXAy0FHRoO:-ND2bcvaCdjmSPz9RK-g:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/pageObjects/RouteStopsOverlay.ts#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's split this into two functions: getHeader(), which then should be called by routeShouldExist()
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteStopsOverlay.ts` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxVdXICcTcg9Gm1hyn:-ND2bedUE3c39Quj42N3:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/pageObjects/RouteStopsOverlay.ts#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's put a test id onto that button to make this test more reliable!
</blockquote></details>

Done.
___
*[`cypress/pageObjects/Toast.ts` line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NCxVvYlCXRjDqXA9lxw:-ND2bgCqBS-k92QZpPBk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/112bb327da37b38a35acfbb1cc60e5df85404359/cypress/pageObjects/Toast.ts#L27)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is not a good pattern, this should've been caught earlier. Let's rather create a function called

```
checkDangerToastHasMessage(message: string) {
  this.getDangerToast().contains(message);
}
```

and then create a function in some route related page object, like this:

```
checkRouteSubmitFailure() {
  toast.checkDangerToastHasMessage('Tallennus epäonnistui')
}
```


</blockquote></details>

Done.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/344)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @pallost and @sr-vala)

___
*[`cypress/pageObjects/MapItemCreator.ts` line 175 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NDC0GPA6BzlmBY5lf7-:-NDC0GPA6BzlmBY5lf70:b-ukzep5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cd186781dec51bad0cd99197be0f08d2fa532479/cypress/pageObjects/MapItemCreator.ts#L175)):*
> ```XML
>   };
> 
>   gqlRouteShouldBeCreatedSuccessfully() {
> ```

these three functions (gqlRouteShouldBeCreatedSuccessfully, checkRouteSubmitSuccess, checkRouteSubmitFailure) don't direct belong to map item creation. If we keep adding these kind of functions to this page object, it will become more and more bloated.

In the UI, these stuff are handled by a component called RouteEditor. Let's move these three functions to a page object accordingly

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/344)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[`cypress/pageObjects/MapItemCreator.ts` line 175 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/344#-NDC0GPA6BzlmBY5lf7-:-NDCEcTL27yC6xThfceH:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cd186781dec51bad0cd99197be0f08d2fa532479/cypress/pageObjects/MapItemCreator.ts#L175)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

these three functions (gqlRouteShouldBeCreatedSuccessfully, checkRouteSubmitSuccess, checkRouteSubmitFailure) don't direct belong to map item creation. If we keep adding these kind of functions to this page object, it will become more and more bloated.

In the UI, these stuff are handled by a component called RouteEditor. Let's move these three functions to a page object accordingly
</blockquote></details>

Done.

**Pull request merged**
