### PR TITLE
Load initial stops properly and show loading spinner in map

### PR DESCRIPTION
**Pull request by eleksi**
- Fix bug where wrong stops were loaded on initial map load
- Display loading overlay when loading the map
- Display loading overlay when fetching stops in map
- Fine tune loading overlay styles

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[`ui/src/hooks/useLoader.ts` line 5 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9BpoH6BNe9EBXRJ8_K:-N9BpoH6BNe9EBXRJ8_L:b-22zfap) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e22743854ddd967f2079e7201b00c2ff467aba85/ui/src/hooks/useLoader.ts#L5)):*
> ```XML
> import { Operation, setLoadingAction } from '../redux';
> 
> export const useLoader = (operation: Operation) => {
> ```

this should also take an optional parameter that would immediately set the loading state on:

```
(operation: Operation, options?: LoaderOptions) => {
...

  useEffect(() => {
    setIsLoading(options.immediatelyOn || false);
  }, []);

}
```



_Code quote:_
```XML
(operation: Operation) 
```

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/hooks/useLoader.ts` line 5 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9BpoH6BNe9EBXRJ8_K:-N9BrK8t6TIciEw42Ifk:bv7jbi5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e22743854ddd967f2079e7201b00c2ff467aba85/ui/src/hooks/useLoader.ts#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should also take an optional parameter that would immediately set the loading state on:

```
(operation: Operation, options?: LoaderOptions) => {
...

  useEffect(() => {
    setIsLoading(options.immediatelyOn || false);
  }, []);

}
```
</blockquote></details>

those LoaderOptions should later on have some debounce parameters as well, but that's not in the scope of this PR. (It's a better UX if the loading overlay is shown only if the loading lasts for more than 500ms... otherwise the overlay would just flicker: quickly be shown and then disappearing)
___
*[`ui/src/redux/selectors/index.ts` line 74 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9BqtTmBWcLHNE6cY3z:-N9BqtTmBWcLHNE6cY4-:b7kfvu7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e22743854ddd967f2079e7201b00c2ff467aba85/ui/src/redux/selectors/index.ts#L74)):*
> ```XML
> );
> 
> export const selectIsLoading = createSelector(selectLoader, (loaders) =>
> ```

maybe `selectIsAnythingLoading` would be a better name. I'd expect `selectIsLoading` to have the operation as a parameter, like this: `const isMapLoading = useAppSelector(selectIdLoading(Operation.MapLoading))`
___
*[`ui/src/redux/slices/loader.ts` line 12 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9BqXQA6dQq8sjVxc5X:-N9BqXQA6dQq8sjVxc5Y:bgiildr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e22743854ddd967f2079e7201b00c2ff467aba85/ui/src/redux/slices/loader.ts#L12)):*
> ```XML
> }
> 
> interface IState {
> ```

type IState = {[key: Operation]: boolean};

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)* status: 0 of 19 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`ui/src/hooks/useLoader.ts` line 5 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9BpoH6BNe9EBXRJ8_K:-N9VDBlTAEQyRiFv_MZQ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e22743854ddd967f2079e7201b00c2ff467aba85/ui/src/hooks/useLoader.ts#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

those LoaderOptions should later on have some debounce parameters as well, but that's not in the scope of this PR. (It's a better UX if the loading overlay is shown only if the loading lasts for more than 500ms... otherwise the overlay would just flicker: quickly be shown and then disappearing)
</blockquote></details>

Done.
___
*[`ui/src/redux/selectors/index.ts` line 74 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9BqtTmBWcLHNE6cY3z:-N9VCguQ57uGvCOV7piP:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e22743854ddd967f2079e7201b00c2ff467aba85/ui/src/redux/selectors/index.ts#L74)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe `selectIsAnythingLoading` would be a better name. I'd expect `selectIsLoading` to have the operation as a parameter, like this: `const isMapLoading = useAppSelector(selectIdLoading(Operation.MapLoading))`
</blockquote></details>

Done.
___
*[`ui/src/redux/slices/loader.ts` line 12 at r7](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9BqXQA6dQq8sjVxc5X:-N9VCXVIDDVStyo9MG8J:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e22743854ddd967f2079e7201b00c2ff467aba85/ui/src/redux/slices/loader.ts#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

type IState = {[key: Operation]: boolean};
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/Map.tsx` line 54 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9VRzZ7A8UZFGnH4Ze0:-N9VRzZ7A8UZFGnH4Ze1:b-6n83xp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a22f82d2c36160854f1d09070867073ad7e633e/ui/src/components/map/Map.tsx#L54)):*
> ```XML
>   const { drawingMode, initiallyDisplayedRouteIds } =
>     useAppSelector(selectMapEditor);
>   const isLoading = useAppSelector(selectIsAnythingLoading);
> ```

right now you only have Operations that are related to map actions. However in the future this might not be the case, you might have operations like 'ExportTimeTables', 'ImportTimeTables', etc.

here, you don't want to subscribe for All of these, only for map-related Operations. You'll probably need a selector that only selects you map operation loaders, like 

```
export const selectMapOperationLoading = createSelector(selectLoader, (loaders) =>
  Object.values(loaders).filter((loader) => mapOperations.includes(loader)).some((loader) => loader),
);
```

___
*[`ui/src/components/map/stops/Stops.tsx` line 62 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9VRNE96-bh9BjKVWG6:-N9VRNE96-bh9BjKVWG7:b7sg0t8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a22f82d2c36160854f1d09070867073ad7e633e/ui/src/components/map/stops/Stops.tsx#L62)):*
> ```XML
> 
>   useEffect(() => {
>     setIsLoading(stopsResult.loading);
> ```

you should not need this useEffect anymore, the useLoader has the immediatelyOn parameter which does the same for you

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/map/Map.tsx` line 54 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9VRzZ7A8UZFGnH4Ze0:-N9VUmvRB1NYHOhXZ2Gr:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a22f82d2c36160854f1d09070867073ad7e633e/ui/src/components/map/Map.tsx#L54)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

right now you only have Operations that are related to map actions. However in the future this might not be the case, you might have operations like 'ExportTimeTables', 'ImportTimeTables', etc.

here, you don't want to subscribe for All of these, only for map-related Operations. You'll probably need a selector that only selects you map operation loaders, like 

```
export const selectMapOperationLoading = createSelector(selectLoader, (loaders) =>
  Object.values(loaders).filter((loader) => mapOperations.includes(loader)).some((loader) => loader),
);
```

</blockquote></details>

Done
___
*[`ui/src/components/map/stops/Stops.tsx` line 62 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9VRNE96-bh9BjKVWG6:-N9VUyrm2fw7NIfihiEN:b-6uvqnm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a22f82d2c36160854f1d09070867073ad7e633e/ui/src/components/map/stops/Stops.tsx#L62)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should not need this useEffect anymore, the useLoader has the immediatelyOn parameter which does the same for you
</blockquote></details>

Actually this is what we need. stopResults.loading will turn the loader on and off according to the status of getStopsByLocation query. This is not just setting it on on component load.

Added a comment to clarify.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/Maplibre.tsx` line 149 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9WBAOL45DsE2kOvE8n:-N9WBAOL45DsE2kOvE8o:bfq357g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fbdd00ed5e09fd37fc5016b3a741e9e1afb84dd3/ui/src/components/map/Maplibre.tsx#L149)):*
> ```XML
>       doubleClickZoom={false}
>       ref={mapRef}
>       onLoad={() => {
> ```

please refactor this to its own function, let's not put business logic to inline functions

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/295)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/map/Maplibre.tsx` line 149 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/295#-N9WBAOL45DsE2kOvE8n:-N9WQ661AIICV3XuMJsG:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fbdd00ed5e09fd37fc5016b3a741e9e1afb84dd3/ui/src/components/map/Maplibre.tsx#L149)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please refactor this to its own function, let's not put business logic to inline functions
</blockquote></details>

Done.

**Pull request merged**
