### PR TITLE
Timetables view

### PR DESCRIPTION
**Pull request by tk-vincit**
- Show timetables based on currrentyle selected line. (Previously we showed same data regardless line selection).
- Add observation date selection to timetables page.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)

Resolves HSLdevcom/jore4#1027

### CODE REVIEW

**Review by eleksi — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 72 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVlK9c0aTcWDjbq5MY:-NLVlK9d1i3wwCxYyOxk:b-z7alkl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L72)):*
> ```XML
>             <h1>{`${validityStartDate} - ${validityEndDate}`}</h1>
>           </Column>
>           <Column className="">
> ```

Empty className
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 73 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVohwcCk8mJPNNegOY:-NLVohwcCk8mJPNNegOZ:b-n711n3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L73)):*
> ```XML
>           </Column>
>           <Column className="">
>             <label htmlFor={dateInputId}>{t('filters.observationDate')}</label>
> ```

Should we create a component from this ObservationDatePicker already? It is used in quite many places..
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 104 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVp6rX7E5owZCnziFQ:-NLVp6rX7E5owZCnziFR:bgus691) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L104)):*
> ```XML
>     useState<VehicleServiceGroup[]>();
> 
>   // TODO: Lines may have multiple routes and those may have multiple journey patterns.
> ```

I don't think a route could have multiple journey patterns even though object relation allows it.
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVqq7hC1fi_UwFWPNM:-NLVqq7hC1fi_UwFWPNN:b-hy3e4y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L138)):*
> ```XML
>         // filter out services that are not active on selected observation date
>         services.filter((item) =>
>           vehicleServiceIdsOnObservationDate?.some(
> ```

Could we just use array includes?
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 143 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVrC_z-4vPkKaKpIKA:-NLVrC_z-4vPkKaKpIKB:b-vk9u1d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L143)):*
> ```XML
>         ),
>       (services) =>
>         services.reduce<VehicleServiceGroup[]>((groups, item) => {
> ```

Could we utilize lodash or remeda `groupBy` here?
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 171 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVt0KS3VvCr_tnE0X2:-NLVt0KS3VvCr_tnE0X3:b-aqbjkd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L171)):*
> ```XML
>   }, [getTimetables, observationDate]);
> 
>   return { timetables, vehicleServices };
> ```

I think it would be good if we could just export one object which contains everything we need. "timetables" is hard to understand what it means and at least to my understanding vehicleServices is something that could be included in "timetables". Maybe it could be naming issue as well, I don't know..

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 97 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVvIWV1KerDJ3AdJsp:-NLVvIWV1KerDJ3AdJsq:b-293zb8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L97)):*
> ```XML
>   // convert it to ISO date. That doesn't hurt performance here
>   // as we can pass that ISO date to dependency array to useCallback.
>   const observationISODate = observationDate.toISODate();
> ```

I don't think this actually is an issue. I doubted this happens and tested it and I didn't see any issue with memorization. So could you try and use observationDate straight away without this ISO variable?

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 73 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVohwcCk8mJPNNegOY:-NLa5WlSEZuA25XWv9qY:bgnwxc4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L73)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Should we create a component from this ObservationDatePicker already? It is used in quite many places..
</blockquote></details>

Started to think about this too. Well, made quick implementation about this, but didn't fixed all the existing observation date input instances as they require a bit more thinking & work.
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 97 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVvIWV1KerDJ3AdJsp:-NLa6AbL7m-Z1yiQwEv3:bmhb8og) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L97)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't think this actually is an issue. I doubted this happens and tested it and I didn't see any issue with memorization. So could you try and use observationDate straight away without this ISO variable?
</blockquote></details>

Hmm...  Weird, as I'm 100% sure that I had problem with this. I also noticed that  `ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` has `// eslint-disable-next-line react-hooks/exhaustive-deps` without explanation. Tried to fix dependency array so that we could rid of that eslint-disable, but it caused infinite loop or something else.

Anyway, seems like works now also without this hack so I can remove this. :shrug: 
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 104 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVp6rX7E5owZCnziFQ:-NLa1XFF5Au2rxGTAltt:b1s6wbv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L104)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't think a route could have multiple journey patterns even though object relation allows it.
</blockquote></details>

Yeah, I also realized that but forgot to fix the comment. Anyway, this is now fixed within this PR.
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVqq7hC1fi_UwFWPNM:-NLa944X3z7-uyyFfIxl:b-r0xake) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L138)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Could we just use array includes?
</blockquote></details>

Good point. :+1: 
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 143 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVrC_z-4vPkKaKpIKA:-NLaA0SB-B0FEa330nNU:b-5hh3t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L143)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Could we utilize lodash or remeda `groupBy` here?
</blockquote></details>

Well, maybe. But this is not implemented within this PR so didn't touched this at least on this iteration round. :)
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 171 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVt0KS3VvCr_tnE0X2:-NLaAWU7Df4KakdlM4xc:b7m9933) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L171)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I think it would be good if we could just export one object which contains everything we need. "timetables" is hard to understand what it means and at least to my understanding vehicleServices is something that could be included in "timetables". Maybe it could be naming issue as well, I don't know..
</blockquote></details>

This wasn't in fact in scope of this PR, but anyway it got updated within latest commits. Any better now?

Timetables data structure is pretty complex and probably we have to still iterate this later, but now we are returning just single array from here.

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuGZwN4UsHD913re2R:-NLuGZwP-E2Mz3_fCnV0:bac8dtf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx#L28)):*
> ```XML
>       <Row>
>         <div className="flex flex-1 items-center bg-background">
>           <h3 className="ml-14">!LINJA</h3>
> ```

I'm not sure if I understand this correctly, but isn't this supposed to contain route label?
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuKO-P-GY9jmcGUD4I:-NLuKO-P-GY9jmcGUD4J:b-zdy178) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L33)):*
> ```XML
>   const { line } = useGetLineDetails();
> 
>   const validity = timetables.length ? timetables[0].validity : undefined;
> ```

It is really hard for me to understand what is the validity period that we really want to show it this page, as at least to me it feels like there could possibly be multiple validity periods e.g. for different routes...

Anyway, could you add a comment to clarify why can we just take the validity period of the first array instance? Is there an assumption, that all the timetables for this line and all its routes are made for the same validity period?

Edit: After chatting with design at the office, I got an understanding that the validity period that should be displayed here would be the "tightest" validity period which the shown timetables make. Meaning that validity start date should be the latest start date that all the displayed timetables contain and validity end date should be the earliest end date that the displayed timetables have. What do you think?
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuHjv4-VUw57a_KHi2:-NLuHjv4-VUw57a_KHi3:b-ava654) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L44)):*
> ```XML
>       ?.timetables_vehicle_journey_vehicle_journey || [];
> 
>   const { observationDate, setObservationDateToUrl } =
> ```

The initial ObservationDateInput component is a step towards the right direction. Just wondering if we could actually put even more business logic to a reusable ObservationDatePicker component, including this row and the few rows below... Not necessarily in scope of this PR, just thinking out loud. Seems that observation date picker behaves the same way regardless of which component it is used in.
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 143 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVrC_z-4vPkKaKpIKA:-NLuPcg78__-lvwFwTWL:b-qezkk6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L143)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, maybe. But this is not implemented within this PR so didn't touched this at least on this iteration round. :)
</blockquote></details>

Ok, fair enough!
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 171 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVt0KS3VvCr_tnE0X2:-NLuQeAo-XLO3X4OfkVr:beqvcdb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L171)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This wasn't in fact in scope of this PR, but anyway it got updated within latest commits. Any better now?

Timetables data structure is pretty complex and probably we have to still iterate this later, but now we are returning just single array from here.
</blockquote></details>

I think it makes more sense now, even though the data structure is kind of complex and it is hard to know how this should be modeled in UI side. Especially I don't know if we can tie validity period together with all the vehicle services belonging to a specific route. :thinking: 
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 195 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuQPwNE5M9PA5ijLlq:-NLuQPwNE5M9PA5ijLlr:bseppc5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/hooks/vehicle-service/useGetTimetables.ts#L195)):*
> ```XML
>     const timetablesWithMetadata = [];
> 
>     // eslint-disable-next-line no-restricted-syntax
> ```

I think this could be done prettier and without having to disable eslint rules by using Promise.all.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuGZwN4UsHD913re2R:-NM2mtYYDv8P3VjVxrXa:b-k41i68) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx#L28)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I'm not sure if I understand this correctly, but isn't this supposed to contain route label?
</blockquote></details>

I guess you are right. This is just placeholder value for now, but uptaded this anyway.
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuKO-P-GY9jmcGUD4I:-NM2nEgg0eQKDQRSlWGA:b-c4frqu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L33)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

It is really hard for me to understand what is the validity period that we really want to show it this page, as at least to me it feels like there could possibly be multiple validity periods e.g. for different routes...

Anyway, could you add a comment to clarify why can we just take the validity period of the first array instance? Is there an assumption, that all the timetables for this line and all its routes are made for the same validity period?

Edit: After chatting with design at the office, I got an understanding that the validity period that should be displayed here would be the "tightest" validity period which the shown timetables make. Meaning that validity start date should be the latest start date that all the displayed timetables contain and validity end date should be the earliest end date that the displayed timetables have. What do you think?
</blockquote></details>

To be honest, I don't know which validity period we want to show here. Different timetables might have different validity periods, so IMO it doesnt' make sense to just pick one, but I don't know what else we can do. :shrug: 

But good that this came up, I'll extract this to own function & add comment about this.
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuHjv4-VUw57a_KHi2:-NM2osep79xOvn6IJjsh:b-stwa6m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L44)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

The initial ObservationDateInput component is a step towards the right direction. Just wondering if we could actually put even more business logic to a reusable ObservationDatePicker component, including this row and the few rows below... Not necessarily in scope of this PR, just thinking out loud. Seems that observation date picker behaves the same way regardless of which component it is used in.
</blockquote></details>

You mean that the input itself would also handle query params..? :thinking: Hmm, that doesn't sound like responsibility of the input component itself as it makes it more specific and harder to use in other places, but of course we could make component which could combine the input and the handling of query parameters.

The annoying thing is that observation date input is used in a bit different UI's, so as explained earlier, it would require at least some refactoring so that same input could be used everywhere.

In fact it might have been a bit suboptimal solution to include also label to the ObservationDateInput component.

But I'd rather keep this rabbit hole out of scope of this PR. :)
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 171 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLVt0KS3VvCr_tnE0X2:-NM2v78E9iHJvT6vfWgu:b78ggvm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6b6ce42d34330ddd64548330c1ffa63495db3133/ui/src/hooks/vehicle-service/useGetTimetables.ts#L171)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I think it makes more sense now, even though the data structure is kind of complex and it is hard to know how this should be modeled in UI side. Especially I don't know if we can tie validity period together with all the vehicle services belonging to a specific route. :thinking: 
</blockquote></details>

The response is now array of timetable data (= raw data from response + calculated fields to make using data easier in UI). The validity periods are calculated for each individual item.
Assuming we would know how to figure out "common" validity period for all items, we would still need to return it in its own property as current return value is array. But that is another discussion.

Anyway, made slight improvements to this file to reduce complexity a bit.
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 195 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuQPwNE5M9PA5ijLlq:-NM2utNv53LLhHP0zmhU:b-t34bso) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/hooks/vehicle-service/useGetTimetables.ts#L195)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I think this could be done prettier and without having to disable eslint rules by using Promise.all.
</blockquote></details>

Good ppoint. I guess the readability is in the eyes of the reader :wink: , but Promise.all is indeed the correct way to do this at it allows doing requests in parallel.

**Review by eleksi — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuKO-P-GY9jmcGUD4I:-NM3_LVpAs2wsMK6jF28:b-sr4kbe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L33)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

To be honest, I don't know which validity period we want to show here. Different timetables might have different validity periods, so IMO it doesnt' make sense to just pick one, but I don't know what else we can do. :shrug: 

But good that this came up, I'll extract this to own function & add comment about this.
</blockquote></details>

Good that there is the TODO comment which indicates that this probably is not how we ultimately want to determine validity period.
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuHjv4-VUw57a_KHi2:-NM3_qjZ4PjEo4nufDoK:bbe351x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L44)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You mean that the input itself would also handle query params..? :thinking: Hmm, that doesn't sound like responsibility of the input component itself as it makes it more specific and harder to use in other places, but of course we could make component which could combine the input and the handling of query parameters.

The annoying thing is that observation date input is used in a bit different UI's, so as explained earlier, it would require at least some refactoring so that same input could be used everywhere.

In fact it might have been a bit suboptimal solution to include also label to the ObservationDateInput component.

But I'd rather keep this rabbit hole out of scope of this PR. :)
</blockquote></details>

Yep, I didn't want the input to contain the logic but different component, as mentioned in the comment `ObservationDateInput` and `ObservationDatePicker` or something like that.

But this change will do for this PR's scope :+1: 
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 162 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NM3bTc2Bv4O8YNA0G9Z:-NM3bTc2Bv4O8YNA0G9_:b-1wt2z8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4e8e649a13122db2f4f123abd25fcba9eb9c2dd3/ui/src/hooks/vehicle-service/useGetTimetables.ts#L162)):*
> ```XML
>   // @ts-expect-error generated graphql types won't match even though
>   // these types should be compatible
>   return groupVehicleServices(scheduleFrames, vehicleServiceIds);
> ```

I think this could be avoided by creating a fragment for vehicle service frame (if it doesn't exist) and use it in function parameter types.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: 3 of 17 files reviewed, all discussions resolved (waiting on @eleksi)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NLuKO-P-GY9jmcGUD4I:-NMYOdhA21NpIBATnQTy:bv6w399) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a01c8dcaa20a32a11a5463d69086a167d3bd81c8/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L33)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Good that there is the TODO comment which indicates that this probably is not how we ultimately want to determine validity period.
</blockquote></details>

This is now updated according to latest slack discussions & design decisions. Let's start new thread if we have any new comments related to this as this thread is not anymore even at relevant location.
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 162 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NM3bTc2Bv4O8YNA0G9Z:-NMYOxXF4EnSRZD1rsOM:b7ezngw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4e8e649a13122db2f4f123abd25fcba9eb9c2dd3/ui/src/hooks/vehicle-service/useGetTimetables.ts#L162)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I think this could be avoided by creating a fragment for vehicle service frame (if it doesn't exist) and use it in function parameter types.
</blockquote></details>

This is fixed in latest revision.

**Review by eleksi — COMMENTED** [review]
> Reviewed 14 of 14 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: all files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/time.spec.ts` line 70 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYW8EC-Ts3a4ys5skG:-NMYW8EC-Ts3a4ys5skH:bdr3v1k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/time.spec.ts#L70)):*
> ```XML
>   });
> });
> ```

Nice to have unit tests for these :+1: 
___
*[`ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx` line 56 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYZeTr0lZ2kqODx3XZ:-NMYZeTr0lZ2kqODx3X_:b-un1m6f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx#L56)):*
> ```XML
>   };
> 
>   const passingTimesByHour = pipe(
> ```

To be exact, we are not talking about "passing times" here in this context, more line "departure times" or something like that.
___
*[`ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx` line 58 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYZtNSCJdvhpq6q0QB:-NMYZtNSCJdvhpq6q0QC:bp8um3i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx#L58)):*
> ```XML
>   const passingTimesByHour = pipe(
>     vehicleServices,
>     (services) => services.flatMap((item) => item.start_time),
> ```

:+1: Nice
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 24 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYa7Dm5y-gzPD-kA7h:-NMYa7Dm5y-gzPD-kA7i:bciuesc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/hooks/vehicle-service/useGetTimetables.ts#L24)):*
> ```XML
> `;
> 
> const GQL_VEHICLE_JOURNEYS_FRAGMENT = gql`
> ```

Could this be called `GQL_VEHICLE_JOURNEY_WITH_SERVICES_FRAGMENT` or rather `GQL_VEHICLE_JOURNEY_WITH_SERVICE_FRAGMENT` (see next comment)
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 25 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYahwJ33dIhKJebg8p:-NMYahwJ33dIhKJebg8q:bnnbg5j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/hooks/vehicle-service/useGetTimetables.ts#L25)):*
> ```XML
> 
> const GQL_VEHICLE_JOURNEYS_FRAGMENT = gql`
>   fragment vehicle_journey_with_services on timetables_vehicle_journey_vehicle_journey {
> ```

Maybe nitpicking, but now that I think about this relation, I don't think there are plural "services", just one service per vehicle journey. If you could rename this it could be more accurate.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/449)* status: all files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx` line 56 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYZeTr0lZ2kqODx3XZ:-NMYeVbWBN84FQj6u7ZY:bdcv6kv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx#L56)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

To be exact, we are not talking about "passing times" here in this context, more line "departure times" or something like that.
</blockquote></details>

Good point!
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 24 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYa7Dm5y-gzPD-kA7h:-NMYf-4z4c3qdt5CXwML:bb6mt9b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/hooks/vehicle-service/useGetTimetables.ts#L24)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Could this be called `GQL_VEHICLE_JOURNEY_WITH_SERVICES_FRAGMENT` or rather `GQL_VEHICLE_JOURNEY_WITH_SERVICE_FRAGMENT` (see next comment)
</blockquote></details>

:+1:
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 25 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/449#-NMYahwJ33dIhKJebg8p:-NMYf1dQ5RN0G2k09vdA:bb6mt9b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cc889fa128134290cb6cebd1fff6042eb635cba3/ui/src/hooks/vehicle-service/useGetTimetables.ts#L25)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Maybe nitpicking, but now that I think about this relation, I don't think there are plural "services", just one service per vehicle journey. If you could rename this it could be more accurate.
</blockquote></details>

:+1:

**Review by eleksi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/449#-:-NMZ0T7r2yKV6k22ydTn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
