### PR TITLE
Only show max 10 lines in ChooseLineDropdown

### PR DESCRIPTION
**Pull request by eleksi**
Resolves HSLdevcom/jore4#912

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fF0lV4bKb-BEj_cCQ:-N9fF0lV4bKb-BEj_cCR:b-8tihme) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L15)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> const GET_LINES_FOR_COMBOBOX = gql`
>   query GetLinesForCombobox($label: String!, $date: timestamptz!) {
> ```

let's maybe call this variable as `labelPattern` instead of just `label` so that we know that it's going to be fed to the ILIKE operator and `%` characters are allowed too
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fHmsz1KsCXnNUs0OD:-N9fHmt-6hxJTobm27B0:bh1m67r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L17)):*
> ```XML
>   query GetLinesForCombobox($label: String!, $date: timestamptz!) {
>     route_line(
>       limit: 10
> ```

also, let's combine this query that it also fetches the selected line's information:

```
query GetLinesForCombobox($labelPattern: String!, $date: timestamptz!, $selectedLineId: uuid) {
    route_line(
      limit: 10
      where: {
        _or: [
        {line_id: {_eq: $selectedLineId}}
        {
          label: { _ilike: $labelPattern }
          _or: [
            { validity_end: { _gte: $date } }
            { validity_end: { _is_null: true } }
          ]
        }]
      }
      order_by: [{ label: asc }, { validity_start: asc }]
    ) {
      ...line_for_combobox
    }
  }
`;
```
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 57 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fIMAP0rbrTIh44VHy:-N9fIMAP0rbrTIh44VHz:b-astb4j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L57)):*
> ```XML
>   );
> 
>   const selectedLineResult = useGetLineDetailsByIdQuery(
> ```

you should not need to do another backend query, you could just combine it with the GetLinesForCombobox query. I wrote a suggestion above
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 63 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fGcAS0Bk2KlRUKyzm:-N9fGcAS0Bk2KlRUKyzn:b-wf98vi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L63)):*
> ```XML
>   const selectedLine = mapLineDetailsResult(selectedLineResult);
> 
>   const queriedlines = (linesResult.data?.route_line ||
> ```

most of this logic is already implemented in the `<ChooseLineDropdown>` component itself. Let's merge this hook with that component, it does not make sense anymore to keep them separate

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 67 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fIvgN5Thegy33ia95:-N9fIvgN5Thegy33ia96:bytqos5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L67)):*
> ```XML
> 
>   // Make selected line always appear in the line list (first)
>   const allLines = [...(selectedLine ? [selectedLine] : []), ...queriedlines];
> ```

there's a simpler and faster way to do this, uniqBy is not really meant for this.
```
const selectedLineIndex = queriedLines.findIndex(item => item.line_id === lineId);
if (selectedLineIndex >= 0) {
  const selectedLine = queriedLines.splice(selectedLineIndex, 1);
  return [...selectedLine, ...queriesLines];
}
return queriesLines

```

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 69 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fqW1d6HuYB1y9JfBk:-N9fqW1d6HuYB1y9JfBl:bw0qu62) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L69)):*
> ```XML
>   const allLines = [...(selectedLine ? [selectedLine] : []), ...queriedlines];
> 
>   return uniqBy(allLines, 'line_id');
> ```

If we decide to keep this hook, then I would suggest to change this to return the value in object for easier extendability.
So for example:
`return { lines: uniqBy(allLines, 'line_id') };`

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fF0lV4bKb-BEj_cCQ:-N9fgBLk-CqNfINSbXwK:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's maybe call this variable as `labelPattern` instead of just `label` so that we know that it's going to be fed to the ILIKE operator and `%` characters are allowed too
</blockquote></details>

Done.
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fHmsz1KsCXnNUs0OD:-N9fgCHuDToj03TKYql_:ba6szi8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

also, let's combine this query that it also fetches the selected line's information:

```
query GetLinesForCombobox($labelPattern: String!, $date: timestamptz!, $selectedLineId: uuid) {
    route_line(
      limit: 10
      where: {
        _or: [
        {line_id: {_eq: $selectedLineId}}
        {
          label: { _ilike: $labelPattern }
          _or: [
            { validity_end: { _gte: $date } }
            { validity_end: { _is_null: true } }
          ]
        }]
      }
      order_by: [{ label: asc }, { validity_start: asc }]
    ) {
      ...line_for_combobox
    }
  }
`;
```
</blockquote></details>

It does not work in this case, as discussed in Slack.
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 57 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fIMAP0rbrTIh44VHy:-N9fgI-WCah34QgHlWS0:ba6szi8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L57)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should not need to do another backend query, you could just combine it with the GetLinesForCombobox query. I wrote a suggestion above
</blockquote></details>

It does not work in this case, as discussed in Slack.
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 63 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fGcAS0Bk2KlRUKyzm:-N9fx9_05WfDdFJUE-aV:b-ld04hy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L63)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

most of this logic is already implemented in the `<ChooseLineDropdown>` component itself. Let's merge this hook with that component, it does not make sense anymore to keep them separate
</blockquote></details>

This is not duplicate logic but true, this hook does not do much. But I don't know if we really add any value by moving all the contents in the combobox component though.
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 67 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fIvgN5Thegy33ia95:-N9fi1-r-jiKUYvJvtuz:byfdxbd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L67)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there's a simpler and faster way to do this, uniqBy is not really meant for this.
```
const selectedLineIndex = queriedLines.findIndex(item => item.line_id === lineId);
if (selectedLineIndex >= 0) {
  const selectedLine = queriedLines.splice(selectedLineIndex, 1);
  return [...selectedLine, ...queriesLines];
}
return queriesLines

```

</blockquote></details>

I know it is not very efficient under the hood to do it with uniqBy, but I thought it looked simpler.

I refactored it, but your suggestion does not work straight out of the box as we want selected line to always be there.
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 69 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9fqW1d6HuYB1y9JfBk:-N9fx7z-5mW7jvOwKjR-:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/666f1886d63b69afbb3de1d8276151ca77b7730b/ui/src/hooks/ui/useChooseLineDropdown.ts#L69)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

If we decide to keep this hook, then I would suggest to change this to return the value in object for easier extendability.
So for example:
`return { lines: uniqBy(allLines, 'line_id') };`
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9jk2Z34q9BedqKsSYH:-N9jk2Z34q9BedqKsSYI:b-qbqieu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/23048f4e08c1af8e66c56df0e4cd2bfb03e1b269/ui/src/hooks/ui/useChooseLineDropdown.ts#L64)):*
> ```XML
>   // fetch it separately by id here.
>   const selectedLineResult = useGetSelectedLineDetailsByIdQuery(
>     mapToVariables({ line_id: lineId }),
> ```

small optimization: 
```
useGetSelectedLineDetailsByIdQuery({
  skip: !lineId,
  variables: {line_id: lineId},
});
```

___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 79 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9jlyQD5UKWJw1m5vAJ:-N9jlyQD5UKWJw1m5vAK:b8ra7iq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/23048f4e08c1af8e66c56df0e4cd2bfb03e1b269/ui/src/hooks/ui/useChooseLineDropdown.ts#L79)):*
> ```XML
> 
>   // If no line is selected or selected line already is in the search results,
>   // just return the search results.
> ```

this will result in the selected line not being at the beginning of the list. Is this intended?

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @pallost)

___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9jk2Z34q9BedqKsSYH:-N9jmcrU-9letfpSmNx_:b-896fja) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/23048f4e08c1af8e66c56df0e4cd2bfb03e1b269/ui/src/hooks/ui/useChooseLineDropdown.ts#L64)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

small optimization: 
```
useGetSelectedLineDetailsByIdQuery({
  skip: !lineId,
  variables: {line_id: lineId},
});
```

</blockquote></details>

Done!
___
*[`ui/src/hooks/ui/useChooseLineDropdown.ts` line 79 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/302#-N9jlyQD5UKWJw1m5vAJ:-N9jme22-F7yrfj54E7f:b-org0jp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/23048f4e08c1af8e66c56df0e4cd2bfb03e1b269/ui/src/hooks/ui/useChooseLineDropdown.ts#L79)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this will result in the selected line not being at the beginning of the list. Is this intended?
</blockquote></details>

Yes it is intended, if the selected line is part of search results. I figured why should we change the order if the selected line is natural part of the listed lines. There will be a check mark that shows the line is selected.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/302)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @HenrikHartiala and @pallost)

**Pull request merged**
