### PR TITLE
Set first and last stops in test data as timing points

### PR DESCRIPTION
**Pull request by sr-vala**
Make test data a bit more realistic by setting the first and last stops on a route as timiing points.

Resolves HSLdevcom/jore4#1425

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655)* status: all files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/routeStops.cy.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-Ne8O-qZEjQqGHu_6q0K:-Ne8O-qZEjQqGHu_6q0L:b-8dbq3d) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3c42103d2705011a9f4c6150a1366c677b1a16f6/cypress/e2e/routeStops.cy.ts#L15)):*
> ```XML
>   extractInfrastructureLinkIdsFromResponse,
>   infrastructureLinkAlongRoute,
>   journeyPatterns,
> ```

Following the data creation is a bit tangled. E.g. you import here `journeyPatterns` (actually an array of single journey pattern) from another "package".

Then you later (below) create a route here with an ID that is referenced by this imported journey pattern. That journey pattern happens to have the same route ID that is re-used here (below). 
___
*[`cypress/e2e/routeStops.cy.ts` line 77 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-Ne8Oodr7r1nMXHmwmxc:-Ne8Oodr7r1nMXHmwmxd:b-5nstjc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3c42103d2705011a9f4c6150a1366c677b1a16f6/cypress/e2e/routeStops.cy.ts#L77)):*
> ```XML
>   {
>     ...buildRoute({ label: '1' }),
>     route_id: '61bef596-84a0-40ea-b818-423d6b9b1fcf',
> ```

The route is created here, but the journey pattern that depends on the route is created elsewhere. To me, this seems like an unintuitive (fragile) dependency graph. I'd prefer to create the journey pattern here as well.
___
*[`cypress/e2e/routeStops.cy.ts` line 145 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-Ne8PU6P-aqkft2y_9DL:-Ne8PU6P-aqkft2y_9DM:b-flj3tq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3c42103d2705011a9f4c6150a1366c677b1a16f6/cypress/e2e/routeStops.cy.ts#L145)):*
> ```XML
>         buildStopInJourneyPattern({
>           journeyPatternId: journeyPatterns[0].journey_pattern_id,
>           stopLabel: stopLabels[1],
> ```

Hmmm...I just couldn't figure out from reading the code whether this journey pattern ends up what you really meant as the last stop point (of 2 in the journey pattern), not used as a timing point. In the other modified test files, you marked the last stop point as being used as a timing point. So this is different from the other changes in this PR. Do you think this is this correct?

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`cypress/e2e/routeStops.cy.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-Ne8O-qZEjQqGHu_6q0K:-NeCIHk63-pvOqdDHa9K:bkh6nth) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3c42103d2705011a9f4c6150a1366c677b1a16f6/cypress/e2e/routeStops.cy.ts#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Following the data creation is a bit tangled. E.g. you import here `journeyPatterns` (actually an array of single journey pattern) from another "package".

Then you later (below) create a route here with an ID that is referenced by this imported journey pattern. That journey pattern happens to have the same route ID that is re-used here (below).
</blockquote></details>

This test data approach was from before my time in the project, but I added the journeyPattern creation to the test file now.
___
*[`cypress/e2e/routeStops.cy.ts` line 77 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-Ne8Oodr7r1nMXHmwmxc:-NeCK4nv675pODyxUOST:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3c42103d2705011a9f4c6150a1366c677b1a16f6/cypress/e2e/routeStops.cy.ts#L77)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The route is created here, but the journey pattern that depends on the route is created elsewhere. To me, this seems like an unintuitive (fragile) dependency graph. I'd prefer to create the journey pattern here as well.
</blockquote></details>

Done.
___
*[`cypress/e2e/routeStops.cy.ts` line 145 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-Ne8PU6P-aqkft2y_9DL:-NeCK7mP2xTpd87Dp9DU:bw7cj4a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3c42103d2705011a9f4c6150a1366c677b1a16f6/cypress/e2e/routeStops.cy.ts#L145)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Hmmm...I just couldn't figure out from reading the code whether this journey pattern ends up what you really meant as the last stop point (of 2 in the journey pattern), not used as a timing point. In the other modified test files, you marked the last stop point as being used as a timing point. So this is different from the other changes in this PR. Do you think this is this correct?
</blockquote></details>

I added another stop to the test data so we can cover all the test cases and still have the first and last stops as timing points.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Left one small remark. Otherwise it looks good to me.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-:-NeMRz5k0YLDg_n6mAbq:b-1btk7c)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/routeStops.cy.ts` line 204 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-NeMRVW--bikCRAbu7QI:-NeMRVW--bikCRAbu7QJ:b-1md7wa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eaab544db1b54e73b6c40d9edf19c40afbe2ec6f/cypress/e2e/routeStops.cy.ts#L204)):*
> ```XML
>       routeStopsTable.toggleRouteSection(routes[0].label);
> 
>       // verify that stops 0 and 1 are included on route
> ```

IMO you should verify that stop 3 is also included in route.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655)* status: all files reviewed, 1 unresolved discussion (waiting on @sr-vala)

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`cypress/e2e/routeStops.cy.ts` line 204 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-NeMRVW--bikCRAbu7QI:-NeNVSJ2DSrajyfqiyCX:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eaab544db1b54e73b6c40d9edf19c40afbe2ec6f/cypress/e2e/routeStops.cy.ts#L204)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO you should verify that stop 3 is also included in route.
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/655#-:-NeNdmDwAyoKz9MEYwcb:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sr-vala)

**Pull request merged**
