### PR TITLE
Add tests and resources for special day timetable import

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#1560

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetableImport.cy.ts` line 498 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk04nN5lYE_iLheDJ6:-Nhk04nN5lYE_iLheDJ7:b495x9n) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L498)):*
> ```XML
>         // Skip searching via UI
>         cy.visit('/routes/search?label=99&priorities=10&displayedType=routes');
>         // Export the route
> ```

Could this step be skipped? In the base data there is already the journey pattern ref for route 99, isn't that enough? AFAIK exporting the route just creates the journey pattern ref.
___
*[`cypress/e2e/timetableImport.cy.ts` line 534 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk0Vck0HOA9E00RMZj:-Nhk0Vck0HOA9E00RMZk:b-g5vnnp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L534)):*
> ```XML
>           .getSpecialDayPriorityCheckbox()
>           .should('be.visible')
>           .and('be.disabled');
> ```

Could add an assertion that this checkbox is checked as well.
___
*[`cypress/e2e/timetableImport.cy.ts` line 553 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk0YLSAOWmzhSX9DQQ:-Nhk0YLSAOWmzhSX9DQR:b-g5vnnp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L553)):*
> ```XML
>           .getSpecialDayPriorityCheckbox()
>           .should('be.visible')
>           .and('be.disabled');
> ```

Could add an assertion that this checkbox is checked as well.
___
*[`cypress/e2e/timetableImport.cy.ts` line 567 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk0grX9RzmaMDE8CzP:-Nhk0grX9RzmaMDE8CzQ:b9a4ijb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L567)):*
> ```XML
>           .and('contain', '6:16');
>         previewTimetablesPage.getSaveButton().click();
>         importTimetablesPage.toast.checkSuccessToastHasMessage(
> ```

I would adjust newlines a bit.



_Suggestion:_
```XML
        previewTimetablesPage.blockVehicleJourneysTable
          .getToggleShowTableButton()
          .click();
        previewTimetablesPage.blockVehicleJourneysTable
          .getTable()
          .should('contain', 'Kalustotyyppi 3 - Normaalibussi')
          .and('contain', '99')
          .and('contain', 'Sunnuntai')
          .and('contain', '6:10')
          .and('contain', '6:16');

        previewTimetablesPage.getSaveButton().click();
        importTimetablesPage.toast.checkSuccessToastHasMessage(
```
___
*[`cypress/e2e/timetableImport.cy.ts` line 577 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk11grDuAc9omD61ji:-Nhk11grDuAc9omD61jj:b-pl1b19) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L577)):*
> ```XML
>         route99InboundSundayPassingTimesSectionSpecial
>           .getDayTypeDropdownButton()
>           .should('contain', 'Sunnuntai');
> ```

There's no special logic for validity times in this case, but could maybe add assertions for them here as well. If there are some errors with the frames, those would be more easily spotted from validity start/end assert.
___
*[`cypress/e2e/timetableImport.cy.ts` line 628 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk1EI19OC6ZYIS2OIU:-Nhk1EI19OC6ZYIS2OIV:b-k4bbfe) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L628)):*
> ```XML
>         route99InboundSundayPassingTimesSectionStandard
>           .getDayTypeDropdownButton()
>           .should('contain', 'Sunnuntai');
> ```

Same here, could check validity times.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 498 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk04nN5lYE_iLheDJ6:-Nhk86vJ8kCz9iOI2Ki4:byq2cg3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L498)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could this step be skipped? In the base data there is already the journey pattern ref for route 99, isn't that enough? AFAIK exporting the route just creates the journey pattern ref.
</blockquote></details>

At least just removing the export step does not work. Hastus logs this error when trying to upload the special day file: 400 BAD_REQUEST "Could not find journey pattern reference for Hastus trips with the following route labels and directions: 99 (inbound)".
___
*[`cypress/e2e/timetableImport.cy.ts` line 534 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk0Vck0HOA9E00RMZj:-Nhk8gMV3aLzZcLCy5ZK:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L534)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could add an assertion that this checkbox is checked as well.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 553 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk0YLSAOWmzhSX9DQQ:-Nhk8rkI2Ruyy3f2NA-M:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L553)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could add an assertion that this checkbox is checked as well.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 567 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk0grX9RzmaMDE8CzP:-Nhk9-TM58PzeiB-3DiA:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L567)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I would adjust newlines a bit.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 577 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk11grDuAc9omD61ji:-NhkD6m3BM4VwkFtVUFN:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L577)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

There's no special logic for validity times in this case, but could maybe add assertions for them here as well. If there are some errors with the frames, those would be more easily spotted from validity start/end assert.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 628 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhk1EI19OC6ZYIS2OIU:-NhkD7ArBACGdmF3OD8l:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/53b517b50c532563a6605a590244dd927bdb7329/cypress/e2e/timetableImport.cy.ts#L628)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Same here, could check validity times.
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/timetableImport.cy.ts` line 216 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhl94Li0ps1Fmg54530:-Nhl94Li0ps1Fmg54531:bjxflcw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d28f137a1de3d20c2f42ca5c4595d166ded1f82d/cypress/e2e/timetableImport.cy.ts#L216)):*
> ```XML
>         {
>           scheduled_stop_point_sequence: 1,
>           scheduled_stop_point_label: 'H1231',
> ```

You should include timing places labels at least for the first and the last stop point.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 216 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Nhl94Li0ps1Fmg54530:-Nhz1VJy-ElsJQjdSTJk:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d28f137a1de3d20c2f42ca5c4595d166ded1f82d/cypress/e2e/timetableImport.cy.ts#L216)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You should include timing places labels at least for the first and the last stop point.
</blockquote></details>

Done.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/timetableImport.cy.ts` line 504 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-NhzFyLp4ZUVjQHMSF_c:-NhzFyLp4ZUVjQHMSF_d:bethnee) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/955cc61d02d3897d9ab23925e736aed27bee4181/cypress/e2e/timetableImport.cy.ts#L504)):*
> ```XML
>         routesAndLinesPage.routeLineTableRow
>           .getRouteLineTableRowCheckbox('99')
>           .check();
> ```

Now that you have added the timing place labels to the Data-Inserter input file, the route details in `hastusExport` file should be identical to the Data-Inserter input. For this reason, this export part should be removed.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 504 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-NhzFyLp4ZUVjQHMSF_c:-NhzIRUr-5098P1vh8fw:bnbes9y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/955cc61d02d3897d9ab23925e736aed27bee4181/cypress/e2e/timetableImport.cy.ts#L504)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Now that you have added the timing place labels to the Data-Inserter input file, the route details in `hastusExport` file should be identical to the Data-Inserter input. For this reason, this export part should be removed.
</blockquote></details>

Adding the timing place labels did not affect the need for exporting the route first.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/timetableImport.cy.ts` line 504 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-NhzFyLp4ZUVjQHMSF_c:-Ni-O-uK4btlhSlU6G4x:b-4wtxij) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/955cc61d02d3897d9ab23925e736aed27bee4181/cypress/e2e/timetableImport.cy.ts#L504)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Adding the timing place labels did not affect the need for exporting the route first.
</blockquote></details>

Setting correct route validity period for `journey_pattern_ref` fixed this.
___
*[`cypress/e2e/timetableImport.cy.ts` line 238 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni-PANVCmU5IbF-7zsO:-Ni-PANVCmU5IbF-7zsP:b-75kkeo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1063b20796ab01a4e4ebfe9cfacc080a8e52165b/cypress/e2e/timetableImport.cy.ts#L238)):*
> ```XML
>   },
>   _vehicle_schedule_frames: {
>     spring2023: {
> ```

`year2023` would be more descriptive (to correspond to the validity period).
___
*[`cypress/e2e/timetableImport.cy.ts` line 242 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni-PYuq6H9fWoxnYUcM:-Ni-PYuq6H9fWoxnYUcN:bo8p8pp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1063b20796ab01a4e4ebfe9cfacc080a8e52165b/cypress/e2e/timetableImport.cy.ts#L242)):*
> ```XML
>       validity_end: DateTime.fromISO('2023-12-31'),
>       name: '2023',
>       booking_label: 'Spring booking label',
> ```

This copy-pasted value should be changed to `Year 2023 booking label` or something similar because of the given validity period.
___
*[`cypress/e2e/timetableImport.cy.ts` line 244 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni-PLJUAhq9onDP_eq1:-Ni-PLJUAhq9onDP_eq2:bvl8kkr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1063b20796ab01a4e4ebfe9cfacc080a8e52165b/cypress/e2e/timetableImport.cy.ts#L244)):*
> ```XML
>       booking_label: 'Spring booking label',
>       _vehicle_services: {
>         monFri: {
> ```

Should be `sun` instead of `monFri` because of the value given for`day_type_id`.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 238 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni-PANVCmU5IbF-7zsO:-Ni-R0Xk46Aa2KyiGRjl:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1063b20796ab01a4e4ebfe9cfacc080a8e52165b/cypress/e2e/timetableImport.cy.ts#L238)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`year2023` would be more descriptive (to correspond to the validity period).
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 242 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni-PYuq6H9fWoxnYUcM:-Ni-R4CIDHlElsSoIv1-:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1063b20796ab01a4e4ebfe9cfacc080a8e52165b/cypress/e2e/timetableImport.cy.ts#L242)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This copy-pasted value should be changed to `Year 2023 booking label` or something similar because of the given validity period.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 244 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni-PLJUAhq9onDP_eq1:-Ni-R5OK0AAtTBNZPnn9:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1063b20796ab01a4e4ebfe9cfacc080a8e52165b/cypress/e2e/timetableImport.cy.ts#L244)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Should be `sun` instead of `monFri` because of the value given for`day_type_id`.
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-:-Ni-X3P3C_gH9g1bKkK9:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/timetableImport.cy.ts` line 207 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni3b3kK85b9dG5DCrqJ:-Ni3b3kK85b9dG5DCrqK:b-4im173) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3cb1475d44cf991a38b15f02f8fbd25cd8e09d67/cypress/e2e/timetableImport.cy.ts#L207)):*
> ```XML
> ];
> 
> const baseTimetableDataInput = {
> ```

I think this should be moved inside "Special days" context since it is used only there.

That would also signify to the code reader that not all tests are using this base data.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 207 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-Ni3b3kK85b9dG5DCrqJ:-Ni3jh4r9m_-pLqwXAke:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3cb1475d44cf991a38b15f02f8fbd25cd8e09d67/cypress/e2e/timetableImport.cy.ts#L207)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think this should be moved inside "Special days" context since it is used only there.

That would also signify to the code reader that not all tests are using this base data.
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/692#-:-Ni3mtqh0KstBaq7sofX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sr-vala)

**Pull request merged**
