### PR TITLE
Bus stop visual fixes

### PR DESCRIPTION
**Pull request by culka**
Fixes visuals mentioned in https://github.com/HSLdevcom/jore4/issues/803

This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @culka and @HenrikHartiala)

___
*[`ui/src/components/map/markers/Circle.tsx` line 38 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N82cpiu59dm3sEUFkcX:-N82cpiu59dm3sEUFkcY:b-7dtzx3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5a8cbef598f75a8ae0e0794c688141a614cf4f1/ui/src/components/map/markers/Circle.tsx#L38)):*
> ```XML
>         fill={fillColor}
>       />
>       <circle
> ```

This circle is now rendered always for each stop. I'm not completely sure if that is good or bad. Another way to approach this would be to give the svg `onMouseOver` and `onMouseLeave` attributes and save it to component state. Then use this state as addition to render the inner circle.
___
*[`ui/src/components/map/stops/StopPopup.tsx` line 62 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N82btdwEIR-4yMILPJA:-N82btdwEIR-4yMILPJB:b5ql0q0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81998389b86ce02a3567533039ca3c1f242b6b66/ui/src/components/map/stops/StopPopup.tsx#L62)):*
> ```XML
>       className="w-80"
>       tipSize={10}
>       offsetLeft={0}
> ```

The default seems to be 0, so I think you can just remove this line.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @culka and @HenrikHartiala)

___
*[`ui/src/components/map/markers/Circle.tsx` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N82fgl_EiXgYF9Xqo0o:-N82fgl_EiXgYF9Xqo0p:b-5iwc5l) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8f9dd069872a47f2ee399830fefb0f342e95dea3/ui/src/components/map/markers/Circle.tsx#L1)):*
> ```XML
> import * as React from 'react';
> ```

As you are working on this file, could you change this to use explicit import.
So `import { memo } from 'react;`

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/map/markers/Circle.tsx` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N82fgl_EiXgYF9Xqo0o:-N84Rvy_A1baMaRLaJH_:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8f9dd069872a47f2ee399830fefb0f342e95dea3/ui/src/components/map/markers/Circle.tsx#L1)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

As you are working on this file, could you change this to use explicit import.
So `import { memo } from 'react;`
</blockquote></details>

Done
___
*[`ui/src/components/map/markers/Circle.tsx` line 38 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N82cpiu59dm3sEUFkcX:-N84RpsN-9eymJAsBQZv:bixnbpv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5a8cbef598f75a8ae0e0794c688141a614cf4f1/ui/src/components/map/markers/Circle.tsx#L38)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This circle is now rendered always for each stop. I'm not completely sure if that is good or bad. Another way to approach this would be to give the svg `onMouseOver` and `onMouseLeave` attributes and save it to component state. Then use this state as addition to render the inner circle.
</blockquote></details>

Switched to using onMouse -events
___
*[`ui/src/components/map/stops/StopPopup.tsx` line 62 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N82btdwEIR-4yMILPJA:-N84VS-g7TAtp8TnBxKr:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/81998389b86ce02a3567533039ca3c1f242b6b66/ui/src/components/map/stops/StopPopup.tsx#L62)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The default seems to be 0, so I think you can just remove this line.
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @culka and @HenrikHartiala)

___
*[`ui/src/components/map/markers/Circle.tsx` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N82fgl_EiXgYF9Xqo0o:-N87bA4E35GkwITPXRsi:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8f9dd069872a47f2ee399830fefb0f342e95dea3/ui/src/components/map/markers/Circle.tsx#L1)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks!
___
*[`ui/src/components/map/markers/Circle.tsx` line 22 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N87bK9eCKnaVe9gr74P:-N87bK9eCKnaVe9gr74Q:b-7h1923) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9a271d3e8c79eef3761333e311af30ad49c67ded/ui/src/components/map/markers/Circle.tsx#L22)):*
> ```XML
>   onClick,
> }: Props): JSX.Element => {
>   const [hoverState, setMouseHover] = useState(false);
> ```

I would maybe name this like "isHovering", "isMouseHovering" etc. but up to you.
And also the the function name should usually be the same as the variable, but with `set` keyword in front. So in this case:
`hoverState, setHoverState`, `isMouseHovering, setIsMouseHovering`

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`ui/src/components/map/markers/Circle.tsx` line 22 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N87bK9eCKnaVe9gr74P:-N87ekIWCkJqzc3y60Oi:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/9a271d3e8c79eef3761333e311af30ad49c67ded/ui/src/components/map/markers/Circle.tsx#L22)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I would maybe name this like "isHovering", "isMouseHovering" etc. but up to you.
And also the the function name should usually be the same as the variable, but with `set` keyword in front. So in this case:
`hoverState, setHoverState`, `isMouseHovering, setIsMouseHovering`
</blockquote></details>

Done.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @culka and @HenrikHartiala)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-N87g53U-v9rvP-E15Kc):*
Ah, missed this one. You should use imperative mood on the subject. `Fix x and y` rather than `Fixed x and y` or `x and y fixes`. Here is a very good article about commit messages which I strongly suggest: https://cbea.ms/git-commit/

**Review by HenrikHartiala — APPROVED** [review]
:+1: 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/274#-:-N8SSOL92rewucjyD__L:b-8fx2u7)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @culka)

**Pull request merged**
