### PR TITLE
Add timetables search

### PR DESCRIPTION
**Pull request by HenrikHartiala**
- We use the same components for timetables- and routes and lines -search. The functionality will
be different depending on in which path we are ('/timetables' or '/routes').
- Change 'Path.lineTimetables' from '/lines/:id/timetables' to '/timetables/lines/:id'
- It is now RouteLineTableRow's responsibility to check if the basePath is 'timetable'. If it is
anything else, we render RoutesAndLines version of the line. This means that the main functionality
(click the row) will take the user to line details and the row will render button to tak the user
to line timetables.
-Rename queryparameter 'displayedData' to 'displayedType'

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/407)

### CODE REVIEW

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/407)* status: 0 of 25 files reviewed, 5 unresolved discussions

___
*[`ui/src/components/common/LineTableRow.tsx` line 96 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NH9HZPDDTJBRJOGcvxa:-NH9HZPDDTJBRJOGcvxb:b4uqo4k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/506fa88ece9c497f6137fb60f6bd327250352438/ui/src/components/common/LineTableRow.tsx#L96)):*
> ```XML
>       locatorButtonTestId="LineTableRow::showLineRoutes"
>       className={className}
>       lineId={line.line_id}
> ```

This is coming through rowItem, but it is not typed since it is not the same for both of the fragments. I do think that we should just spread the necessary attributes here, instead of the rowItem, but this is not the main focus yet.
___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 47 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NH9HpQJCEpjApJRO3ao:-NH9HpQJCEpjApJRO3ap:bll736o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/506fa88ece9c497f6137fb60f6bd327250352438/ui/src/components/common/RouteLineTableRow.tsx#L47)):*
> ```XML
>   const alertIcon = alertStyle.icon || 'icon-_-placeholder';
>   const history = useHistory();
>   const variant = history.location.pathname.split('/')[1];
> ```

This is something that I would like to hear alternative solutions. I don't like this, but could not think anymore of a better solution.
___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 94 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NH9I9Ez1y4L6SdsDqK1:-NH9I9Ez1y4L6SdsDqK2:bai367f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/506fa88ece9c497f6137fb60f6bd327250352438/ui/src/components/common/RouteLineTableRow.tsx#L94)):*
> ```XML
>         <Link
>           to={
>             variant === 'timetables'
> ```

Same goes for the whole 'variant' logic. I don't like that have to do this repeated ternaries in this Link, row Icon and alternativeRowActionButton. But like said, I got a bit overwhelmed by this and it would be better if fresh eyes could come up with a better solution.
___
*[`ui/src/components/routes-and-lines/search/SearchResultPage.tsx` line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NH9IsVi72z1Zu9hMygL:-NH9IsVi72z1Zu9hMygM:bklthqa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/506fa88ece9c497f6137fb60f6bd327250352438/ui/src/components/routes-and-lines/search/SearchResultPage.tsx#L14)):*
> ```XML
>   titleTranslationKey,
> }: {
>   titleTranslationKey: string;
> ```

Not sure if the combination of changes in Router.tsx and this translationKey is the right way.
___
*[`ui/src/hooks/search/useSearch.ts` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NH9JBMQ-MRsvn4i7I-D:-NH9JBMQ-MRsvn4i7I-E:bylme5u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/506fa88ece9c497f6137fb60f6bd327250352438/ui/src/hooks/search/useSearch.ts#L20)):*
> ```XML
>   // to the correct path, because we have different search result paths and we
>   // have the search component in multiple different pathed urls.
>   const basePath = history.location.pathname.split('/')[1];
> ```

Also not sure if this is the right way, but with this at least the responsibility to know the basePath is in useSearch and not for example in ResultSelector.

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 24 files at r1, 3 of 5 files at r2, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/407)* status: all files reviewed, 13 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 94 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NH9I9Ez1y4L6SdsDqK1:-NIgr0zt-aVYHJuJWwag:b-cktgxh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/506fa88ece9c497f6137fb60f6bd327250352438/ui/src/components/common/RouteLineTableRow.tsx#L94)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Check my comment above.
</blockquote></details>

This looks nice now! :+1: 
___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 27 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgr8fdE6j-1bVd4HJO:-NIgr8fdE6j-1bVd4HJP:b2blw2t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteLineTableRow.tsx#L27)):*
> ```XML
>   locatorButtonTestId: string;
>   rowItem: LineTableRowFragment | RouteTableRowFragment;
>   rowVariant: RouteLineTableRowVariant;
> ```

At least for now this looks like a nice solution! :+1: 
___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 117 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIglLiH09dXJzJMRWue:-NIglLiH09dXJzJMRWuf:b7t9i3w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteLineTableRow.tsx#L117)):*
> ```XML
>       </td>
>       <td className={`w-full py-4 ${yBorderClassnames}`}>
>         <Link
> ```

Just thinking out loud here, could be that I'm missing something but is this link actually now disabled or does it just look like it? If it isn't, is it in purpose?
___
*[`ui/src/components/common/RouteTableRow.tsx` line 74 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIglr8Z12P8ejjpP5gK:-NIglr8Z12P8ejjpP5gL:b-km3va7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteTableRow.tsx#L74)):*
> ```XML
>   // Check if the route has any vehicle_journey's existing, which means
>   // that the route has timetables.
>   const hasTimetables = route.route_journey_patterns.some(
> ```

Looks a lot like the check in LineTableRow, except there we do it from one level up. Anyway, maybe just check if we can make this code reusable..?
___
*[`ui/src/components/common/search/LinesList.tsx` line 20 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgmO_oA_GGDg2cUwEe:-NIgmO_oA_GGDg2cUwEf:btbkoyd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/search/LinesList.tsx#L20)):*
> ```XML
>   rowVariant,
> }: Props): JSX.Element => {
>   return (
> ```

I'm not sure what is the reason for this change, why is it now being explicitly returned. Maybe because something was done there but the change was reverted? Regardless, I guess it is ok
___
*[`ui/src/components/common/search/RoutesList.tsx` line 20 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgnEU-CSWJrlSeoq2c:-NIgnEU-CSWJrlSeoq2d:b-czzsan) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/search/RoutesList.tsx#L20)):*
> ```XML
>   rowVariant,
> }: Props): JSX.Element => {
>   return (
> ```

Same here as earlier but it's ok :smile: 
___
*[`ui/src/hooks/useBasePath.ts` line 11 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgoQ9QD5aT5-AXR6yL:-NIgoQ9QD5aT5-AXR6yM:b5y1fyw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/hooks/useBasePath.ts#L11)):*
> ```XML
> export const useBasePath = (): { basePath: Path } => {
>   const history = useHistory();
>   const basePath = `/${history.location.pathname.split('/')[1]}` as Path;
> ```

What if this hook is called from front page..? Will it crash? :thinking: 
___
*[`ui/src/hooks/search/useSearch.ts` line 15 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgodRq2loL1LqJ7IMh:-NIgodRrDgi42L6-n0OO:b8s6j7v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/hooks/search/useSearch.ts#L15)):*
> ```XML
> 
> export const useSearch = () => {
>   const { basePath } = useBasePath();
> ```

It is nice that basePath is not passed around anymore. :+1: 
___
*[`ui/src/hooks/search/useSearchQueryParser.ts` line 19 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgor5H8zXJg2rGUxGA:-NIgor5H8zXJg2rGUxGB:b-avcxyo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/hooks/search/useSearchQueryParser.ts#L19)):*
> ```XML
> 
> export type FilterConditions = {
>   displayedType: DisplayedSearchResultType;
> ```

I think this name is ok, but what do you think about it being something like `displayedEntityType` or something like that? Something that would indicate that we are talking about entity types here, not just different types of displays, if you get what i mean :smile: 

I don't think this needs to be changed further in this PR, just thinking about ways to make these `displayedType` and `rowVariant` stand out from each other.
___
*[`ui/src/uiComponents/LineDetailsButton.tsx` line 1 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgkEm203Tly_dPtyoq:-NIgkEm203Tly_dPtyor:blq8e0b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/uiComponents/LineDetailsButton.tsx#L1)):*
> ```XML
> import { useHistory } from 'react-router-dom';
> ```

I don't think this is "ui component". I would rather move it somewhere else, like "/components/common".

UI components are library like components that are not specific to this project or business context.
___
*[`ui/src/uiComponents/LineDetailsButton.tsx` line 28 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgpq_e3Wu8yMcm-g_O:-NIgpq_f5Ed9U2T7TtvL:b-4knzhi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/uiComponents/LineDetailsButton.tsx#L28)):*
> ```XML
>   };
>   return (
>     <IconButton
> ```

Can you think of any way to combine at least part of this component and LineTablesButton? Maybe even the style classes? Most code in these components is the same, what really differs is testid, onClick callback and the icon.

I wouldn't say this is something very high priority or even necessary, but this thought just came to my mind when I saw two of these similar components. And I know, we need to draw the line somewhere on how many layers of abstraction do we need for something as simple as a button :smile: 
___
*[`ui/src/uiComponents/LineTimetablesButton.tsx` line 1 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgkPeIALVDFlLVv8fd:-NIgkPeIALVDFlLVv8fe:b8k6rx1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/uiComponents/LineTimetablesButton.tsx#L1)):*
> ```XML
> import { useHistory } from 'react-router-dom';
> ```

I don't think this is "ui component". I would rather move it somewhere else, like "/components/common"

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/407)* status: all files reviewed, 10 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 117 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIglLiH09dXJzJMRWue:-NIlCEi-8K-l4MLNaeTR:bo3au51) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteLineTableRow.tsx#L117)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Just thinking out loud here, could be that I'm missing something but is this link actually now disabled or does it just look like it? If it isn't, is it in purpose?
</blockquote></details>

It is actually disabled. This `pointer-events-none` makes it non-clickable.
___
*[`ui/src/components/common/RouteTableRow.tsx` line 74 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIglr8Z12P8ejjpP5gK:-NIq-olu1vy4ak8LVquZ:be570nf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteTableRow.tsx#L74)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Looks a lot like the check in LineTableRow, except there we do it from one level up. Anyway, maybe just check if we can make this code reusable..?
</blockquote></details>

Yeah this part is the same in both of them. We could have some util function for this, but not sure what would be a sensible name for it. I think this part of the code is OK like it is. I also think that this code will not change (the determination if route has timetables), so it would be Ok that these are not sharing the code. 

But maybe if we need this code for the third time at some point, we could rethink of extracting it to a separate function. Or what do you think? If it would make the code more readable, then I could maybe do it here already.
___
*[`ui/src/components/common/search/LinesList.tsx` line 20 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgmO_oA_GGDg2cUwEe:-NIlmxT134mYYYm_sbuL:bx7ynsr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/search/LinesList.tsx#L20)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I'm not sure what is the reason for this change, why is it now being explicitly returned. Maybe because something was done there but the change was reverted? Regardless, I guess it is ok
</blockquote></details>

Good catch. Maybe I changed this for a temporary console.log etc. and then forgot, I'll revert this.
___
*[`ui/src/components/common/search/RoutesList.tsx` line 20 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgnEU-CSWJrlSeoq2c:-NIq1TDkDdwPQJlvOwNa:bfgjp9v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/search/RoutesList.tsx#L20)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Same here as earlier but it's ok :smile: 
</blockquote></details>

Reverting this as well. 
___
*[`ui/src/hooks/useBasePath.ts` line 11 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgoQ9QD5aT5-AXR6yL:-NIr02ZWE1cAIEk0Whss:b-fh1t9f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/hooks/useBasePath.ts#L11)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

What if this hook is called from front page..? Will it crash? :thinking: 
</blockquote></details>

Nope, it will return '/' (Path.root)
___
*[`ui/src/hooks/search/useSearchQueryParser.ts` line 19 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgor5H8zXJg2rGUxGA:-NIr0sl45V2E0xOSM2-M:b8fxcfd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/hooks/search/useSearchQueryParser.ts#L19)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I think this name is ok, but what do you think about it being something like `displayedEntityType` or something like that? Something that would indicate that we are talking about entity types here, not just different types of displays, if you get what i mean :smile: 

I don't think this needs to be changed further in this PR, just thinking about ways to make these `displayedType` and `rowVariant` stand out from each other.
</blockquote></details>

I agree that there might be a better name for this. I think that the`Entity` will solve this, but hmm. 

So this determines which type of results are displayed: Lines or Routes  (currently) . But maybe later it might have more options as well. `typeOfResults`, `typeOfDisplayedResults` ? I don't know, also need to remember that this will be in the queryParams, so preferably something short (but only preferably).
___
*[`ui/src/uiComponents/LineDetailsButton.tsx` line 1 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgkEm203Tly_dPtyoq:-NJ40VmOEGgO5C2jXvAN:b19ous2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/uiComponents/LineDetailsButton.tsx#L1)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't think this is "ui component". I would rather move it somewhere else, like "/components/common".

UI components are library like components that are not specific to this project or business context.
</blockquote></details>

:+1: Moved
___
*[`ui/src/uiComponents/LineDetailsButton.tsx` line 28 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgpq_e3Wu8yMcm-g_O:-NJ41IUB0dQiphYQUaPw:b4ktsrf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/uiComponents/LineDetailsButton.tsx#L28)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Can you think of any way to combine at least part of this component and LineTablesButton? Maybe even the style classes? Most code in these components is the same, what really differs is testid, onClick callback and the icon.

I wouldn't say this is something very high priority or even necessary, but this thought just came to my mind when I saw two of these similar components. And I know, we need to draw the line somewhere on how many layers of abstraction do we need for something as simple as a button :smile: 
</blockquote></details>

Yeah it's a good point to at least keep in mind. If we will have more of this kind of buttons, we could try another abstraction layer here. I think I will let this be as it is for now, but definitely keep in mind and do another iteration if necessary.
___
*[`ui/src/uiComponents/LineTimetablesButton.tsx` line 1 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgkPeIALVDFlLVv8fd:-NJ42K6GAg2VBMNVTnAd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/uiComponents/LineTimetablesButton.tsx#L1)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't think this is "ui component". I would rather move it somewhere else, like "/components/common"
</blockquote></details>

Done.

**Review by eleksi — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/407)* status: all files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/common/RouteLineTableRow.tsx` line 117 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIglLiH09dXJzJMRWue:-NJ4R2bU76m7hzARy3DS:b-6rw56m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteLineTableRow.tsx#L117)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

It is actually disabled. This `pointer-events-none` makes it non-clickable.
</blockquote></details>

Oh ok, somehow didn't think css class would affect functionality.
___
*[`ui/src/components/common/RouteTableRow.tsx` line 74 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIglr8Z12P8ejjpP5gK:-NJ4RcoB5TUfxKD5JQVo:bzbeb69) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteTableRow.tsx#L74)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah this part is the same in both of them. We could have some util function for this, but not sure what would be a sensible name for it. I think this part of the code is OK like it is. I also think that this code will not change (the determination if route has timetables), so it would be Ok that these are not sharing the code. 

But maybe if we need this code for the third time at some point, we could rethink of extracting it to a separate function. Or what do you think? If it would make the code more readable, then I could maybe do it here already.
</blockquote></details>

Do what you want to. 

If I created a function from this, I would probably name it something like `routeHasTimetables`, `doesRouteHaveTimetables` or something like that. But true, naming it would be challenging.. 
___
*[`ui/src/hooks/useBasePath.ts` line 11 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgoQ9QD5aT5-AXR6yL:-NJ4SfkzCNbX4hBEDEqs:b-shu5z1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/hooks/useBasePath.ts#L11)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Nope, it will return '/' (Path.root)
</blockquote></details>

Ok, good then.
___
*[`ui/src/hooks/search/useSearchQueryParser.ts` line 19 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIgor5H8zXJg2rGUxGA:-NJ5Q-f73SzcL-bSi1aT:b-i1rv8o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/hooks/search/useSearchQueryParser.ts#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I agree that there might be a better name for this. I think that the`Entity` will solve this, but hmm. 

So this determines which type of results are displayed: Lines or Routes  (currently) . But maybe later it might have more options as well. `typeOfResults`, `typeOfDisplayedResults` ? I don't know, also need to remember that this will be in the queryParams, so preferably something short (but only preferably).
</blockquote></details>

Let's keep this consideration in mind but at least for me this is ok as it is for now

**Review by eleksi — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/407)* status: all files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/407)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @HenrikHartiala)

___
*[`ui/src/components/common/RouteTableRow.tsx` line 74 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/407#-NIglr8Z12P8ejjpP5gK:-NJAtx3DDCfhhkQP8X1n:b-ty4tt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0cb8630d9877b1e65e0048bfa39a4600722b3b5d/ui/src/components/common/RouteTableRow.tsx#L74)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Do what you want to. 

If I created a function from this, I would probably name it something like `routeHasTimetables`, `doesRouteHaveTimetables` or something like that. But true, naming it would be challenging.. 
</blockquote></details>

Yep, in the end changed this as discussed, so thanks! This actually is much cleaner now.

**Pull request merged**
