### PR TITLE
Refactor route geometry layers

### PR DESCRIPTION
**Pull request by eleksi**
- Always use components for rendering route geometry
- Remove draft route rendering from DrawRouteLayer

- This refactoring helps adding arrow layer to route geometry later on

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/379)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/379)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 150 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNMu9r-C9xVCx5agW6:-NFNMu9r-C9xVCx5agW7:b4qy5y2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/DrawRouteLayer.tsx#L150)):*
> ```XML
>         !editedRouteData.metaData.priority
>       ) {
>         log.warn(
> ```

I don't understand why these are things which we want to log with some kind of "logger". I assume something like "console.log" would be sufficient, assuming that these are not "important" messages, as it seems.



_Code quote:_
```XML
 log.warn(
```
___
*[`ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNKMr95qYYaAqlqCPa:-NFNKMr95qYYaAqlqCPb:by4a0as) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx#L19)):*
> ```XML
>   layerId.substring(ROUTE_LAYER_ID_PREFIX.length) as UUID;
> 
> interface ExistingRouteGeometryLayerProps {
> ```

interface Props
___
*[`ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNKYRF-TiqnCcGMx8p:-NFNKYRG4oVqCVVOeRIi:b-dmc0ja) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx#L25)):*
> ```XML
> 
> // This layer fetches a single route's geometry and renders it as a line polygon
> export const ExistingRouteGeometryLayer = ({
> ```

What does "Existing" prefix mean here, does it add any value to the reader? How about just "RouteGeometryLayer"?
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNLH8r4SILgJtD304x:-NFNLH8r4SILgJtD304y:by4a0as) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L7)):*
> ```XML
> const { colors } = theme;
> 
> interface RouteGeometryLayerProps {
> ```

interface Props
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNLB98B9w4HytfxbWF:-NFNLB98B9w4HytfxbWG:b-zht65g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L14)):*
> ```XML
> }
> 
> // This layer fetches a single route's geometry and renders it as a line polygon
> ```

This doesn't seem to fetch anything anymore, so this comment is now outdated.
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNLRj81nUj1AV1qKcf:-NFNLRj81nUj1AV1qKcg:b-nchgj2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L16)):*
> ```XML
> // This layer fetches a single route's geometry and renders it as a line polygon
> export const RouteGeometryLayer = ({
>   layerId,
> ```

Seems like we are now mixing different abstractions here...
I guess this should now be just "GeometryLayer", as this doesn't have anything route-related anymore. But this still takes "vehicleMode" parameter, which is not really used here, it is just needed for determining line color!  (1)

Also we have `colors.routes[vehicleMode],`where vehicle mode enum is implicitly tied to the values of `colors.routes`, but if someone happens to edit `colors.routes` she has no way of knowing that something might accidentally break because of that here. (2)

We might tacke these issue somehow like this:
(1) pass `lineColor` on `unselectedLineColor` as prop to this component, instead of vehicleMode. Or re-think this component structure from scratch as I might be missing bigger picture here. Anyway, current implementation is definitely problematic.
(2) define `mapVehicleModeToColor` (or something like that) util function for determining color, e.g. based on this approach:

```
export const mapPriorityToUiName = (key: Priority) => {
  const uiStrings: Record<Priority, string> = {
    [Priority.Standard]: i18n.t('priority.standard'),
    [Priority.Temporary]: i18n.t('priority.temporary'),
    [Priority.Draft]: i18n.t('priority.draft'),
  };
  return uiStrings[key];
};

```
Then we get at least ts error if someone removes color that is used in the code.



_Code quote:_
```XML
export const RouteGeometryLayer = ({
  layerId,
  geometry,
  vehicleMode,
```
___
*[`ui/src/redux/slices/mapRouteEditor.ts` line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNM_ApAdWR3ruFXvAP:-NFNM_ApAdWR3ruFXvAQ:bi6ygsq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/redux/slices/mapRouteEditor.ts#L50)):*
> ```XML
>    * Draft route geometry
>    */
>   geometry?: GeoJSON.LineString;
> ```

draftGeometry? :shrug:

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/379)* status: 0 of 11 files reviewed, 7 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 150 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNMu9r-C9xVCx5agW6:-NFNlNkqEwMwJfoTBYCu:bj4y806) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/DrawRouteLayer.tsx#L150)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand why these are things which we want to log with some kind of "logger". I assume something like "console.log" would be sufficient, assuming that these are not "important" messages, as it seems.
</blockquote></details>

I really don't understand it either, but I have not added this. Let's remove it later if needed.
___
*[`ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNKMr95qYYaAqlqCPa:-NFNnAPFEmwlf9S1vpot:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

interface Props
</blockquote></details>

Done.
___
*[`ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNKYRF-TiqnCcGMx8p:-NFNnD9VDUq-6OPXRVgS:bjzax9x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/ExistingRouteGeometryLayer.tsx#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What does "Existing" prefix mean here, does it add any value to the reader? How about just "RouteGeometryLayer"?
</blockquote></details>

It is prefixed with existing as we want to emphasize the route already exist and we can get its geometry by id. The other option is that the route is draft and needs the geometry provided as it does not already exist. I was thinking about the naming as well, but this was the best one I could come up with for now. If we want to make this RouteGeometryLayer, the existing RouteGeometryLayer needs a new name, which it might receive soon.

 As discussed in slack, let's leave it like this for now.
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNLH8r4SILgJtD304x:-NFNn9YN9gzPrfszzB1R:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

interface Props
</blockquote></details>

Done.
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNLB98B9w4HytfxbWF:-NFNn9Ok45gnHl5tfaoy:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L14)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This doesn't seem to fetch anything anymore, so this comment is now outdated.
</blockquote></details>

Done.
___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNLRj81nUj1AV1qKcf:-NFNxN1v2svcxBsQWOwi:b-8it2pe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/components/map/routes/RouteGeometryLayer.tsx#L16)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems like we are now mixing different abstractions here...
I guess this should now be just "GeometryLayer", as this doesn't have anything route-related anymore. But this still takes "vehicleMode" parameter, which is not really used here, it is just needed for determining line color!  (1)

Also we have `colors.routes[vehicleMode],`where vehicle mode enum is implicitly tied to the values of `colors.routes`, but if someone happens to edit `colors.routes` she has no way of knowing that something might accidentally break because of that here. (2)

We might tacke these issue somehow like this:
(1) pass `lineColor` on `unselectedLineColor` as prop to this component, instead of vehicleMode. Or re-think this component structure from scratch as I might be missing bigger picture here. Anyway, current implementation is definitely problematic.
(2) define `mapVehicleModeToColor` (or something like that) util function for determining color, e.g. based on this approach:

```
export const mapPriorityToUiName = (key: Priority) => {
  const uiStrings: Record<Priority, string> = {
    [Priority.Standard]: i18n.t('priority.standard'),
    [Priority.Temporary]: i18n.t('priority.temporary'),
    [Priority.Draft]: i18n.t('priority.draft'),
  };
  return uiStrings[key];
};

```
Then we get at least ts error if someone removes color that is used in the code.
</blockquote></details>

Good point, also was thinking about this. Now it is changed.
___
*[`ui/src/redux/slices/mapRouteEditor.ts` line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFNM_ApAdWR3ruFXvAP:-NFNmnTZ5ewHj_IkYcPh:b-aruy7g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e5522f3650933f6ef7011cae9955d2dd333bac6e/ui/src/redux/slices/mapRouteEditor.ts#L50)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

draftGeometry? :shrug: 
</blockquote></details>

Well as it is already inside EditedRouteData, it should be clear that we are talking about geometry that is under editing (is a draft).

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/379)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFOMFpQ55hMp1aWmcyp:-NFOMFpQ55hMp1aWmcyq:b-77vmwh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7c6ae76906414a7028d38c6892a4c3ac7065e702/ui/src/components/map/routes/RouteGeometryLayer.tsx#L17)):*
> ```XML
>   layerId,
>   geometry,
>   defaultColor,
> ```

I guess it would make sense to define this as optinal parameter & give default value to it. 

Now we are calculating `defaultColor` in `ui/src/components/map/routes/DraftRouteGeometryLayer.tsx` with "unsafe" non-null assertion, and then just ignoring it anyway as we have hardcoded `isHighlighted` to `true` there.

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/379)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[`ui/src/components/map/routes/RouteGeometryLayer.tsx` line 17 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/379#-NFOMFpQ55hMp1aWmcyp:-NGLaM7X3tlZePN06JXw:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7c6ae76906414a7028d38c6892a4c3ac7065e702/ui/src/components/map/routes/RouteGeometryLayer.tsx#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I guess it would make sense to define this as optinal parameter & give default value to it. 

Now we are calculating `defaultColor` in `ui/src/components/map/routes/DraftRouteGeometryLayer.tsx` with "unsafe" non-null assertion, and then just ignoring it anyway as we have hardcoded `isHighlighted` to `true` there.
</blockquote></details>

Done.

**Review by tk-vincit — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 1 of 4 files at r2, 1 of 1 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eleksi)

**Pull request merged**
