### PR TITLE
Add translations for Hastus error messages

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/763)

### CODE REVIEW

**Comment by niknii-vincit** [comment]
*[`ui/src/locales/en-US/common.json` line 502 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/763#-NpYld_A9T2m0M8yKEVo:-NpYld_A9T2m0M8yKEVp:b-wj7m2g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/021ded5be265a0de8a24fe0fe62f4be402c5c157/ui/src/locales/en-US/common.json#L502)):*
> ```JSON
>     "cannotFindJourneyPatternRefByTimingPlaceLabelsError": "Could not find matching journey pattern reference whose timing place labels correspond to the Hastus trip. Check if the route has been modified but not yet exported to Hastus.",
>     "errorWhileProcessingHastusDataError": "Error while processing Hastus data.",
>     "firstStopNotTimingPointError": "The first stop point in the journey pattern is not a timing point.",
> ```

Super nitpick: all the other error messages refer Hastus, even the translation says it not being a "Hastus-paikka", so I just feel it's missing here, but maybe I'm looking into patterns too much and it doesn't give any value here :sweat_smile: Fine either way

**Review by niknii-vincit — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 12 of 12 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/763)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/763)* status: 10 of 14 files reviewed, all discussions resolved (waiting on @niknii-vincit)

___
*[`ui/src/locales/en-US/common.json` line 502 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/763#-NpYld_A9T2m0M8yKEVo:-NpZ6v8i5XHz7GvsZ9qF:b-vr50wc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/021ded5be265a0de8a24fe0fe62f4be402c5c157/ui/src/locales/en-US/common.json#L502)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Super nitpick: all the other error messages refer Hastus, even the translation says it not being a "Hastus-paikka", so I just feel it's missing here, but maybe I'm looking into patterns too much and it doesn't give any value here :sweat_smile: Fine either way
</blockquote></details>

https://github.com/HSLdevcom/jore4/wiki/Glossary#timing-place-not-in-transmodel

The English term for `Hastus-paikka` is `Timing Place`, so that's why there's no mention of Hastus here.

Though, this comment made me notice that the translations are incorrect in another way, on the Finnish side. Since these first/lastStopPoint errors don't deal with timing *places* but *points*, the correct translation is `ajoituspiste` and not `Hastus-paikka`.

**Comment by niknii-vincit** [comment]
*[`ui/src/locales/en-US/common.json` line 502 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/763#-NpYld_A9T2m0M8yKEVo:-NpZCptZCyjRUGB6Nlvf:b-cl04td) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/021ded5be265a0de8a24fe0fe62f4be402c5c157/ui/src/locales/en-US/common.json#L502)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

https://github.com/HSLdevcom/jore4/wiki/Glossary#timing-place-not-in-transmodel

The English term for `Hastus-paikka` is `Timing Place`, so that's why there's no mention of Hastus here.

Though, this comment made me notice that the translations are incorrect in another way, on the Finnish side. Since these first/lastStopPoint errors don't deal with timing *places* but *points*, the correct translation is `ajoituspiste` and not `Hastus-paikka`.
</blockquote></details>

That's even better then, great work :thumbsup:

**Review by niknii-vincit — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/763)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
