### PR TITLE
Add example e2e test with Cypress

### PR DESCRIPTION
**Pull request by tk-vincit**
Related to HSLdevcom/jore4#770

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/176)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/176)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @pallost and @tk-vincit)

___
*[`cypress/support/commands.ts` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/176#-N2BjgaoB_jzpRKI68Qq:-N2BjgaoB_jzpRKI68Qr:b-1f86l6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cbbbdce39f5680ae2931520b3080daa188ed022c/cypress/support/commands.ts#L28)):*
> ```XML
> 
> // @ts-expect-error not sure what is wrong here, something with cypress typings? "Argument of type '(this: Context, selector: string) => Chainable<JQuery<HTMLElement>>' is not assignable to parameter of type 'CommandFn<"getById">', ..."
> Cypress.Commands.add('getById', (selector, ...args) => {
> ```

let's rather call this `getByTestId` to avoid confusion with the built-in get(Element)ById function

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/176)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[`cypress/pageObjects/Navbar.ts` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/176#-N2BjKL37T5OUCfgHpm6:-N2GKAyiD0AD8umOHpyC:b-qvknl4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f85c8cd03181032486c90f2f2bc3da6c6b151535/cypress/pageObjects/Navbar.ts#L2)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I took a quick look at some examples using page objects and it seems there is no need to pass cy instance to each method as a parameter. It seems like there might be some magic involved but at least with right configuration cy could be used without passing the instance.
</blockquote></details>

You seem to be correct. One could argue that passing cy instance makes page objects more "pure", but maybe simplicity is better in this case.

Removed these for now.
___
*[`cypress/support/commands.ts` line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/176#-N2BiC3t9yKu2zB_-b42:-N2GIJmGCOfwZJgBtkBa:budy2ji) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f85c8cd03181032486c90f2f2bc3da6c6b151535/cypress/support/commands.ts#L28)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Should this be getByTestId as we probably have some elements that we select with id as well?
</blockquote></details>

Done.

Btw: elements with id can be selected with `cy.get('#myId'), no need for custom action for that.
___
*[`cypress/support/commands.ts` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/176#-N2BjgaoB_jzpRKI68Qq:-N2GIGVXCzJiHtlAEw6f:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cbbbdce39f5680ae2931520b3080daa188ed022c/cypress/support/commands.ts#L28)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's rather call this `getByTestId` to avoid confusion with the built-in get(Element)ById function
</blockquote></details>

Done.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/176)* status: 0 of 33 files reviewed, 3 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`README.md` line 47 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/176#-N2G_H8YA6iLvOevZVTB:-N2G_H8YA6iLvOevZVTC:bxhvdkr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/bc15349ed07ebbc541cfafb259d791f24a3daa39/README.md#L47)):*
> ```Markdown
> ### Cypress (e2e) tests
> 
> - To open cypress with browser for developing tests locally: `yarn test:e2e:open`
> ```

Could you add a sentence here that the developer should first
- start up all the dependencies with `./start-dependencies.sh`
- start up the UI itself via `yarn dev`
___
*[`cypress/fixtures/example.json` line 2 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/176#-N2G_viI8vyT1OQ4JBXi:-N2G_viI8vyT1OQ4JBXj:b-w4h262) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3915b6dc304938a826c4e951b5f298047c3fd6be/cypress/fixtures/example.json#L2)):*
> ```JSON
> {
>   "name": "Using fixtures to represent data",
> ```

we don't need this example as you've already defined the e2e user as a fixture below
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 26 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/176#-N2GaZ7x6vKrniA_x9Zn:-N2GaZ7x6vKrniA_x9Zo:bzhw0tm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3915b6dc304938a826c4e951b5f298047c3fd6be/cypress/pageObjects/ConfirmSaveForm.ts#L26)):*
> ```XML
>   }
> 
>   setAsIndefinite(indefinite = true) {
> ```

would be useful to have a helper function like this:
```
setValidityPeriod(startIsoDate: string, endIsoDate?: string) {
  this.setStartDate(startIsoDate);
  if (endIsoDate) {
    this.setAsIndefinite(false);
    this.setEndDate(endIsoDate);
  } else {
    this.setAsIndefinite(true);
  }
}
```

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/176)* status: 0 of 33 files reviewed, 2 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

**Pull request merged**
