### PR TITLE
Add missing readme instructions

### PR DESCRIPTION
**Pull request by HenrikHartiala**
Also minor update to old instruction order.

Resolves HSLdevcom/jore4#1571

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717)

### CODE REVIEW

**Review by niknii-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717#-NjH3YKW4Fte8wNx8CC4:-NjH3YKW4Fte8wNx8CC5:bvqvqw6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bdb51e4298d0c0fce7ee05a322d2d78ce59f0619/README.md#L26)):*
> ```Markdown
> ```
> 
> Then we need to isntall dependencies with
> ```

Typo, otherwise good add! 



_Code quote:_
```Markdown
isntall
```
___
*[`README.md` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717#-NjH3plm4nwOZ7iEAAqo:-NjH3plnBfMlG0za99pT:b-2y3v26) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bdb51e4298d0c0fce7ee05a322d2d78ce59f0619/README.md#L34)):*
> ```Markdown
> Then we can build the `test-db-manager` and `timetables-data-inserter`, but these build commands
> should also be included in the commands that require them to be built in `package.json`, e.g. `e2e:test`.
> But if for some reason still needed:
> ```

Ah, I was instructed to build test-db-manager manually before anything, so I blindly believed this and added it as a "missing step" :thinking:  Good to clarify that it's not needed. I rather have everything documented and not needed, than missing completely. 

If it's optional, should we add a controversial expandable section here? 

Like this:
 
<details>
<summary>Why is it controversial?</summary>

It's controversial because HTML tags in MD is smelly (so not "allowed") :sweat_smile:  

My personal opinion is that this expandable section helps so much with the final layout, that it's worth it. I think optional and extra details are good to hide, so that if you NEED something quickly, you don't need to read EVERYTHING.

</details>
<br>
What do you think?

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @niknii-vincit)

___
*[`README.md` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717#-NjH3plm4nwOZ7iEAAqo:-NjH75qe7lUN9giCY6bs:ba4ttf0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bdb51e4298d0c0fce7ee05a322d2d78ce59f0619/README.md#L34)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Ah, I was instructed to build test-db-manager manually before anything, so I blindly believed this and added it as a "missing step" :thinking:  Good to clarify that it's not needed. I rather have everything documented and not needed, than missing completely. 

If it's optional, should we add a controversial expandable section here? 

Like this:
 
<details>
<summary>Why is it controversial?</summary>

It's controversial because HTML tags in MD is smelly (so not "allowed") :sweat_smile:  

My personal opinion is that this expandable section helps so much with the final layout, that it's worth it. I think optional and extra details are good to hide, so that if you NEED something quickly, you don't need to read EVERYTHING.

</details>
<br>
What do you think?
</blockquote></details>

Yes, great suggestion! I did not know that this kind of feature existed.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @niknii-vincit)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717#-NjH3YKW4Fte8wNx8CC4:-NjHBL6V5mEaOCV-j3Fb:b-m78coo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bdb51e4298d0c0fce7ee05a322d2d78ce59f0619/README.md#L26)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Typo, otherwise good add!
</blockquote></details>

Fiexded

**Review by niknii-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`README.md` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717#-NjH3YKW4Fte8wNx8CC4:-NjHFSMU4cYwwSoN76Vz:bkkqlhh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bdb51e4298d0c0fce7ee05a322d2d78ce59f0619/README.md#L26)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Fiexded
</blockquote></details>

:suspect: 'd
___
*[`README.md` line 46 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717#-NjHFi9l3YJU91nQfi1s:-NjHFi9l3YJU91nQfi1t:b-p2z2tu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cb8f5f39caa5761f8e51e48f4ee10919551d9a74/README.md#L46)):*
> ```Markdown
> and **build** the timetables data inserter:
> 
> ```
> ```

You can add `sh` after the triple \` to get okayish syntax highlighting, but it doesn't add any value for short commands :man_shrugging: (and often they're just nonsense with such commands), just a fyi, no need to fix it :+1:

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @niknii-vincit)

___
*[`README.md` line 46 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/717#-NjHFi9l3YJU91nQfi1s:-NjHI5NUE5z5hEpLGMF6:b-5xoxxw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cb8f5f39caa5761f8e51e48f4ee10919551d9a74/README.md#L46)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

You can add `sh` after the triple \` to get okayish syntax highlighting, but it doesn't add any value for short commands :man_shrugging: (and often they're just nonsense with such commands), just a fyi, no need to fix it :+1:
</blockquote></details>

Yeah, there seems to be `bash` and `sh` used, but seems that neither of them is adding anything in these short commands like you said but good to keep in mind :+1:

**Pull request merged**
