### PR TITLE
Added job for running e2e tests to cd.yml

### PR DESCRIPTION
**Pull request by jpeuralinna**
Runs e2e smoke tests for new ui image, after it is pushed to docker hub.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jpeuralinna)

___
*[.github/workflows/cd.yml, line 72 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MciOs9u1pCs2xk34Xt8:-MciOs9u1pCs2xk34Xt9:bchs90j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L72)):*
This way of extracting the branch name does not work in every circumstance. You are using the generic solution already in your previous workflow :) 
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>       - name: Extract branch name to env variable
>         run: |
>           # In pull requests
>           BRANCH_NAME="${GITHUB_HEAD_REF}"
>           [[ ${BRANCH_NAME} = "" ]] && {
>             # In branch pushes
>             BRANCH_NAME="$(echo "${GITHUB_REF}" | cut -d '/' -f 3-)"
>           }
>           echo "BRANCH_NAME=${BRANCH_NAME}" >> "${GITHUB_ENV}"
> ```
</details>

___
*[.github/workflows/cd.yml, line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MciP9Zu9jm-5YJ_gNCa:-MciP9Zu9jm-5YJ_gNCb:b-da4mbt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L75)):*
Also, the COMMIT_ID was defined like this:
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>       - name: Set environment variables
>         run: |
>           # Docker Hub uses lowercase so use a bashism to convert.
>           echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
>           # Docker tags can use only some special characters.
>           echo "COMMIT_ID=$(echo "${BRANCH_NAME}" | tr -C '0-9a-zA-Z._' '-')-${GITHUB_SHA}" >> $GITHUB_ENV
> ```
</details>

___
*[.github/workflows/cd.yml, line 82 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MciPMQpAxT7Yu1gSfYx:-MciPMQpAxT7Yu1gSfYy:btppv8t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L82)):*
> ```YAML
>       - name: run e2e smoke tests
>         id: tests
>         uses: HSLdevcom/jore4-robot/.github/action@main
> ```

don't you have some versioning for this one? Something like `@v1` instead of `@main`?

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna and @pallost)

___
*[.github/workflows/cd.yml, line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-McrLv4hEDxiGiblYNQP:-McrLv4hEDxiGiblYNQQ:bcrdz9q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L68)):*
> ```YAML
> 
>   run_e2e_tests:
>     needs: push_to_registry
> ```

Should we rather run e2e tests _before_ pushing anything to docker hub?
___
*[.github/workflows/cd.yml, line 72 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MciOs9u1pCs2xk34Xt8:-McrLJiFEa8BW_TsQQ0k:bu6apn8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L72)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This way of extracting the branch name does not work in every circumstance. You are using the generic solution already in your previous workflow :) 

> ```
>       - name: Extract branch name to env variable
>         run: |
>           # In pull requests
>           BRANCH_NAME="${GITHUB_HEAD_REF}"
>           [[ ${BRANCH_NAME} = "" ]] && {
>             # In branch pushes
>             BRANCH_NAME="$(echo "${GITHUB_REF}" | cut -d '/' -f 3-)"
>           }
>           echo "BRANCH_NAME=${BRANCH_NAME}" >> "${GITHUB_ENV}"
> ```

</blockquote></details>

And that is also already defined above in this file.
Is `BRANCH_NAME` env variable already defined, or is it scoped to previous job? If possible, we should avoid defining same thing twice in this file.
___
*[.github/workflows/cd.yml, line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MciP9Zu9jm-5YJ_gNCa:-McrLdU39js-riylvwo6:b-o45cb7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L75)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Also, the COMMIT_ID was defined like this:

> ```
>       - name: Set environment variables
>         run: |
>           # Docker Hub uses lowercase so use a bashism to convert.
>           echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
>           # Docker tags can use only some special characters.
>           echo "COMMIT_ID=$(echo "${BRANCH_NAME}" | tr -C '0-9a-zA-Z._' '-')-${GITHUB_SHA}" >> $GITHUB_ENV
> ```

</blockquote></details>

Also COMMIT_ID is defined above.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-McrLv4hEDxiGiblYNQP:-Mcxjnuh6qQmdNR6uzU1:ber0j6g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L68)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should we rather run e2e tests _before_ pushing anything to docker hub?
</blockquote></details>

we need the docker images to be deployed to a Kind / docker-compose cluster in order to be able to run it in e2e tests. So we can't do e2e tests before images are in docker hub. At least with the current setup... later on we could try building the docker image locally and then locally deploy it to the e2e docker-compose cluster. But Kind cluster needs the image to be in a registry

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-McrLv4hEDxiGiblYNQP:-Mkpmod-3RVeE6wDoTf3:b10c6aq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L68)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we need the docker images to be deployed to a Kind / docker-compose cluster in order to be able to run it in e2e tests. So we can't do e2e tests before images are in docker hub. At least with the current setup... later on we could try building the docker image locally and then locally deploy it to the e2e docker-compose cluster. But Kind cluster needs the image to be in a registry
</blockquote></details>

actually, now that I think about it, we only need to build the docker images, we don't need to have them pushed to docker hub for e2e tests

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jpeuralinna, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 76 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MnUjcYEAM8N6EhHNtIv:-MnUjcYEAM8N6EhHNtIw:b-f60t4h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/581310a3cc19597b7da853751ece19a8185751de/.github/workflows/cd.yml#L76)):*
> ```YAML
>           e2e_password: ${{ secrets.ROBOT_HSLID_PASSWORD }}
> 
>       - name: Retrieve test results from docker container
> ```

The upload-artifact action already retrieves the test results within

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jpeuralinna, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-McrLv4hEDxiGiblYNQP:-MnUjxlrBSmx821k6yzg:bw48za3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d04ed98fbfd5292c33d4701c05565f75ea6ea559/.github/workflows/cd.yml#L68)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually, now that I think about it, we only need to build the docker images, we don't need to have them pushed to docker hub for e2e tests
</blockquote></details>

nevermind, this is fine

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jpeuralinna, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 66 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MnUk2OP7bsOGbcRtrz7:-MnUk2OP7bsOGbcRtrz8:b-lqyk15) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/581310a3cc19597b7da853751ece19a8185751de/.github/workflows/cd.yml#L66)):*
> ```YAML
> 
>       - name: Restart auth backend
>         run: docker-compose -f ${{ github.workspace }}/docker/docker-compose.yml restart jore4-auth
> ```

should not need to restart auth backend here

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jpeuralinna, @pallost, and @tk-vincit)

___
*[.github/workflows/cd.yml, line 82 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/15#-MnVavdV5uoXGPkSn03O:-MnVavdW40aMFm8vw3UE:b71j7b6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/581310a3cc19597b7da853751ece19a8185751de/.github/workflows/cd.yml#L82)):*
> ```YAML
>       - name: Expose test results as an artifact
>         if: always()
>         uses: actions/upload-artifact@v1
> ```

you made an upload-results github action, let's take that into use!

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/15)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pallost and @tk-vincit)

**Pull request merged**
