### PR TITLE
Use `react-hook-form` + `zod` instead for `formik` + `yup`

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/42)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/42)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[-- commits, line 16 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/42#-MnyDBoP5DWxRjxxY5NL):*
good! I've always wanted to try `zod`...
___
*[src/components/forms/StopForm.tsx, line 14 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/42#-MnyDZNh4fTFows578gR:-MnyDZNh4fTFows578gS:bx3ahm0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6f46efcf1f77276cbf55645ccfb09789c8664ba6/src/components/forms/StopForm.tsx#L14)):*
> ```XML
> });
> 
> export type FormState = z.infer<typeof schema>;
> ```

I don't think you need to export this as it's only used internally. However if you do want to use this FormState outside, let's give it some more unique naming, like StopFormState
___
*[src/components/forms/StopForm.tsx, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/42#-MnyE1-PBPWtWkJDQGZM:-MnyE1-PBPWtWkJDQGZN:b-nw6vqa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6f46efcf1f77276cbf55645ccfb09789c8664ba6/src/components/forms/StopForm.tsx#L35)):*
> ```XML
>   });
> 
>   const onSubmit = (data: FormState) =>
> ```

if it takes the values from outside, it should also outsource the output callbacks as well (like `onSubmit`, `onCancel`, etc). So either all form inputs and outputs are handled inside or all are handled outside.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/42)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/forms/StopForm.tsx, line 14 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/42#-MnyDZNh4fTFows578gR:-Mnyr1LY9VZ3FLSGsH7t:b-59gz2o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6f46efcf1f77276cbf55645ccfb09789c8664ba6/src/components/forms/StopForm.tsx#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think you need to export this as it's only used internally. However if you do want to use this FormState outside, let's give it some more unique naming, like StopFormState
</blockquote></details>

This is used also externally. Personally I prefer this kind of naming, as it makes easier to keep form implementations consistent (less likely to make errors if copypasting existing form definition as a base for new form). Also name collisions are unlikely as usually there is only one form in one view component, but if needed you can still rename export in the import phase: `import { FormState as StopFormState, StopForm } from '../forms/StopForm';`
___
*[src/components/forms/StopForm.tsx, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/42#-MnyE1-PBPWtWkJDQGZM:-MnyqX-h6pqeLqNRaFP7:bgak48q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6f46efcf1f77276cbf55645ccfb09789c8664ba6/src/components/forms/StopForm.tsx#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if it takes the values from outside, it should also outsource the output callbacks as well (like `onSubmit`, `onCancel`, etc). So either all form inputs and outputs are handled inside or all are handled outside.
</blockquote></details>

Not sure if I understand this comment completely. This form handles its own state completely. Just the initial values are passed from outside.

This kind of architechture (form handles all) seems to be the way to go with `react-hook-form`.

How would you want to get initial values here if not passed from outside?

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/42)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @pallost and @tk-vincit)

___
*[src/components/forms/StopForm.tsx, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/42#-MnyE1-PBPWtWkJDQGZM:-MnyzD_L15TeuqOQSMpM:b-hxlwyl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6f46efcf1f77276cbf55645ccfb09789c8664ba6/src/components/forms/StopForm.tsx#L35)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if I understand this comment completely. This form handles its own state completely. Just the initial values are passed from outside.

This kind of architechture (form handles all) seems to be the way to go with `react-hook-form`.

How would you want to get initial values here if not passed from outside?
</blockquote></details>

if not passed from outside, the values could be initialized by fetching them directly from the app store.
But well, the boundaries are not that strict... also I just remembered that we are using graphql in this project to the boundaries of responsibilities of components is blurred even more...

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/42)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[src/components/forms/StopForm.tsx, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/42#-MnyE1-PBPWtWkJDQGZM:-Mnz38PS0BzPnzLPtmKe:bwkzuid) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6f46efcf1f77276cbf55645ccfb09789c8664ba6/src/components/forms/StopForm.tsx#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if not passed from outside, the values could be initialized by fetching them directly from the app store.
But well, the boundaries are not that strict... also I just remembered that we are using graphql in this project to the boundaries of responsibilities of components is blurred even more... 
</blockquote></details>

At least in this case stop locations in map are not stored in global app state. Let's see how things are going to evolve in the future, but right now this is the way to go.

**Comment by tk-vincit** [comment]
E2e tests are broken for the reasons unrelated to this PR, so let's merge this now.

**Pull request merged**
