### PR TITLE
Allow route metadata edit when creating new route

### PR DESCRIPTION
**Pull request by eleksi**
Resolves HSLdevcom/jore4#734

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/199)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/199)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/components/map/RouteStopsOverlay.tsx` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2uk3Q77661cfEeb18g:-N2uk3Q77661cfEeb18h:bdog8sz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/components/map/RouteStopsOverlay.tsx#L138)):*
> ```XML
>           </div>
>         </div>
>         <Visible visible={creatingNewRoute}>
> ```

why do we only show the edit button for routes that are being newly created? Why not also showing it for existing routes to let them be edited afterwards?
___
*[`src/redux/slices/mapEditor.ts` line 97 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2ulOiCE0IQ6clQVxsi:-N2ulOiCE0IQ6clQVxsj:b46g0j5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/redux/slices/mapEditor.ts#L97)):*
> ```XML
>     },
>     startDrawRoute: (state) => {
>       state.isRouteMetadataFormOpen = true;
> ```

also here: instead of trying to implement business logic within the reducer, let's keep it in the event handler callbacks instead
___
*[`src/redux/slices/mapEditor.ts` line 148 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2ujU-6BBIY_Fbh_Dy2:-N2ujU-6BBIY_Fbh_Dy3:b-y08s5d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/redux/slices/mapEditor.ts#L148)):*
> ```XML
>       action: PayloadAction<Partial<RouteFormState>>,
>     ) => {
>       state.editedRouteData = {
> ```

it starts to be way too much business logic within the reducers for my taste. Let's do business logic in the event handler callbacks instead.

Also, when you finish metadata editing, why would you set creatingNewRoute flag to true? These two things have nothing in common
___
*[`src/uiComponents/EditButton.tsx` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2ui4c95peJqHEAugTH:-N2ui4c95peJqHEAugTI:b-4ht2w5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/uiComponents/EditButton.tsx#L5)):*
> ```XML
> import { Link } from 'react-router-dom';
> 
> // Only support href for now,
> ```

this comment is now obsolete

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/199)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[`src/components/map/RouteStopsOverlay.tsx` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2uk3Q77661cfEeb18g:-N33LCes1UA9N9D-UoVZ:btodgtc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/components/map/RouteStopsOverlay.tsx#L138)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

why do we only show the edit button for routes that are being newly created? Why not also showing it for existing routes to let them be edited afterwards?
</blockquote></details>

We agreed with design that editing route metadata when creating route is more important at this point. Editing existing route's data would require more code changes and design work (e.g. current route creation form is missing some fields).
___
*[`src/redux/slices/mapEditor.ts` line 97 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2ulOiCE0IQ6clQVxsi:-N33QZtZ6PUZOVD2AXkp:b5a0aoq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/redux/slices/mapEditor.ts#L97)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

also here: instead of trying to implement business logic within the reducer, let's keep it in the event handler callbacks instead
</blockquote></details>

I don't get what exactly here is too much business logic. There are certain things that need to change in our state when user starts to draw a new route, don't we want them to be happening in the reducer?
___
*[`src/redux/slices/mapEditor.ts` line 148 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2ujU-6BBIY_Fbh_Dy2:-N33Lh4X1P6Di8j0QqZi:b-roygqk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/redux/slices/mapEditor.ts#L148)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it starts to be way too much business logic within the reducers for my taste. Let's do business logic in the event handler callbacks instead.

Also, when you finish metadata editing, why would you set creatingNewRoute flag to true? These two things have nothing in common
</blockquote></details>

For the first point, I'm not sure if you want me to split this into multiple actions or what. How I thought about this: user finishes route metadata editing in route editor -> route metadata form data is saved in the state, form is closed and draw / edit mode entered.

`createNewRoute` flag change was unnecessary here, and `selectedRouteId` was also moved to other action.
___
*[`src/uiComponents/EditButton.tsx` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2ui4c95peJqHEAugTH:-N33QqCWBv3_vzFvpQ9i:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/uiComponents/EditButton.tsx#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this comment is now obsolete
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
Apparently it is actually suggested that we put business logic into reducers... Removed those comments that were against this idea. https://redux.js.org/faq/code-structure#how-should-i-split-my-logic-between-reducers-and-action-creators-where-should-my-business-logic-go

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-:-N3JJgnXDa2xGWJfJgav:bgyawyf)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/components/map/RouteStopsOverlay.tsx` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N2uk3Q77661cfEeb18g:-N3JJfot-0csjgJKtrO8:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7db07f740c55f97f0511303c367138c07b169165/src/components/map/RouteStopsOverlay.tsx#L138)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

We agreed with design that editing route metadata when creating route is more important at this point. Editing existing route's data would require more code changes and design work (e.g. current route creation form is missing some fields).
</blockquote></details>

OK
___
*[`src/components/map/RouteStopsOverlay.tsx` line 22 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JJu2k9DzqYDY95smy:-N3JJu2k9DzqYDY95smz:brz8mqm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/RouteStopsOverlay.tsx#L22)):*
> ```XML
> } from '../../redux';
> import { EditButton } from '../../uiComponents';
> import { SimpleDropdownMenu } from '../../uiComponents/SimpleDropdownMenu';
> ```

should import SimpleDropdownMenu from the default uiComponents namespace
___
*[`src/components/map/routes/Routes.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JS4JN9c9PdIrfGBuh:-N3JS4JN9c9PdIrfGBui:b-1xva30) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L15)):*
> ```XML
> import { CreateRouteModal } from './CreateRouteModal';
> 
> export const Routes: React.FC = () => {
> ```

The name `Routes` for this layer is not really fitting anymore, it is closer to `EditRouteMetadataLayer` or something similar.
___
*[`src/components/map/routes/Routes.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JT6qu6rST5w2pdHr9:-N3JT6qu6rST5w2pdHrA:bb3ikzp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L25)):*
> ```XML
>     dispatch(setRouteMetadataFormOpenAction(false));
> 
>     const hasFormBeenSubmitted =
> ```

you should refactor this to its own function:
const areFormValuesValid = (formData: RouteFormState) => routeFormSchema.safeParse(formData).success;
___
*[`src/components/map/routes/Routes.tsx` line 26 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JPSqI6IKRqJ-4ix3T:-N3JPSqI6IKRqJ-4ix3U:b-8f6zy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L26)):*
> ```XML
> 
>     const hasFormBeenSubmitted =
>       routeFormSchema.safeParse(routeDetails).success;
> ```

It took me more than half an hour to decypher why you are checking if the editedRouteData.metadata is valid here. So your idea is that
1. if the modal was closed before the values were filled in, cancel the whole route drawing
2. if the modal was already filled once but the user chose to edit it afterwards, no need to cancel the route drawing, only close the modal

- Please do comment the interaction here because it's far from obvious!
- Also please fix the variable names: instead of `hasFormBeenSubmitted`, should rather have something like `alreadyHaveValidFormValues` or something similar
___
*[`src/components/map/routes/Routes.tsx` line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JTt2gE7oxxZG9VSmI:-N3JTt2gE7oxxZG9VSmJ:bgyg0kg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L30)):*
> ```XML
>     // Only clear route creation state is there the form has not been submitted
>     if (!hasFormBeenSubmitted) {
>       dispatch(stopDrawRouteAction());
> ```

the name `stopDrawRouteAction` is misleading here. You're not only stopping the drawing but also resetting the whole process. Maybe the name `resetRouteMetadataEditingAction` would be better?
___
*[`src/components/map/routes/Routes.tsx` line 49 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JRnYnA-ky1DgcyBjR:-N3JRnYnA-ky1DgcyBjS:b-lipmo6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L49)):*
> ```XML
> 
>   return (
>     <CreateRouteModal
> ```

This should be renamed rather to `EditRouteModal`, because it's doing much more nowadays then just creating
___
*[`src/redux/slices/mapEditor.ts` line 151 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JIsEQALqIetXraTWV:-N3JIsEQALqIetXraTWW:b-ghb3v5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/redux/slices/mapEditor.ts#L151)):*
> ```XML
>       state.editedRouteData = {
>         metaData: action.payload,
>         stops: state.editedRouteData.stops,
> ```

you should rather use the spread operator here, so if the editedRouteData contents change, this will follow...

```
state.editedRouteData = {
  ...state.editedRouteData,
  metaData: action.payload  
}
```
___
*[`src/uiComponents/EditButton.tsx` line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JGC3q7NXIvB9WkHyY:-N3JGC3q7NXIvB9WkHyZ:b-p3axvl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/uiComponents/EditButton.tsx#L23)):*
> ```XML
>   const onClick = (props as ButtonProps)?.onClick;
> 
>   const ButtonContent = () => (
> ```

let's not have inline components unless it's a must. Please move it outside of the EditButton component

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/199)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @pallost)

___
*[`src/components/map/RouteStopsOverlay.tsx` line 22 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JJu2k9DzqYDY95smy:-N3JabsI-zBJuSWQBOcl:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/RouteStopsOverlay.tsx#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should import SimpleDropdownMenu from the default uiComponents namespace
</blockquote></details>

Done.
___
*[`src/components/map/routes/Routes.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JS4JN9c9PdIrfGBuh:-N3JamtS4Qt_gx1T6q7a:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

The name `Routes` for this layer is not really fitting anymore, it is closer to `EditRouteMetadataLayer` or something similar.
</blockquote></details>

Done.
___
*[`src/components/map/routes/Routes.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JT6qu6rST5w2pdHr9:-N3Jb70X1M8bEr016YJe:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should refactor this to its own function:
const areFormValuesValid = (formData: RouteFormState) => routeFormSchema.safeParse(formData).success;
</blockquote></details>

Done.
___
*[`src/components/map/routes/Routes.tsx` line 26 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JPSqI6IKRqJ-4ix3T:-N3JcRSB2_yWw5nuoQvY:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

It took me more than half an hour to decypher why you are checking if the editedRouteData.metadata is valid here. So your idea is that
1. if the modal was closed before the values were filled in, cancel the whole route drawing
2. if the modal was already filled once but the user chose to edit it afterwards, no need to cancel the route drawing, only close the modal

- Please do comment the interaction here because it's far from obvious!
- Also please fix the variable names: instead of `hasFormBeenSubmitted`, should rather have something like `alreadyHaveValidFormValues` or something similar
</blockquote></details>

Done.
___
*[`src/components/map/routes/Routes.tsx` line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JTt2gE7oxxZG9VSmI:-N3JggGg-ck3xeAlqQIB:b-pbq3l4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L30)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the name `stopDrawRouteAction` is misleading here. You're not only stopping the drawing but also resetting the whole process. Maybe the name `resetRouteMetadataEditingAction` would be better?
</blockquote></details>

I don't think name `resetRouteMetadataEditingAction` really represents what this action does.

There are two "opposite" actions, `startDrawRoute` and `stopDrawRoute`, and their role is to manipulate store when user starts to draw (create) a new route, or when they finish drawing (creating) a new route by saving the route or cancelling the creation. Stop means that they completely stop (quit), not pause.

I could rename these actions to `startCreateRoute` and `stopCreateRoute`, if it seems better. But I wouldn't want to mix metadata word with these actions, as the state they manipulate is not only related to metadata, but also draw modes etc. I didn't change anything yet, waiting for your opinion.
___
*[`src/components/map/routes/Routes.tsx` line 49 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JRnYnA-ky1DgcyBjR:-N3JiFTR4sMatYGl3tKd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L49)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This should be renamed rather to `EditRouteModal`, because it's doing much more nowadays then just creating
</blockquote></details>

Done.
___
*[`src/redux/slices/mapEditor.ts` line 151 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JIsEQALqIetXraTWV:-N3JiWdsDXKgsO4zwDZB:b-la7je5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/redux/slices/mapEditor.ts#L151)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should rather use the spread operator here, so if the editedRouteData contents change, this will follow...

```
state.editedRouteData = {
  ...state.editedRouteData,
  metaData: action.payload  
}
```
</blockquote></details>

Sure! Done.
___
*[`src/uiComponents/EditButton.tsx` line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JGC3q7NXIvB9WkHyY:-N3Jl0WW1K9prBancWR-:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/uiComponents/EditButton.tsx#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's not have inline components unless it's a must. Please move it outside of the EditButton component
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/199)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/components/map/routes/EditRouteMetadataLayer.tsx` line 40 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3Sk8z-CNa7vRVtxn95:-N3Sk8z-CNa7vRVtxn96:b-n6w3wq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0463776dab72b9f25578c3790fb51ee4964db458/src/components/map/routes/EditRouteMetadataLayer.tsx#L40)):*
> ```XML
> 
>   const onSuccess = (data: RouteFormState) => {
>     const readyToSubmit = areFormValuesValid(data);
> ```

just came to my mind... are there actually any cases where the form could be submitted but the values in it are not valid? I yes, could you please comment it here? If not, let's just remove the validity check...
___
*[`src/components/map/routes/Routes.tsx` line 26 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JPSqI6IKRqJ-4ix3T:-N3SkOdZ7T3c7DxQrh4m:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L26)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`src/components/map/routes/Routes.tsx` line 30 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/199#-N3JTt2gE7oxxZG9VSmI:-N3Sl3pV0d7rCkw3cHV_:b-tfrp49) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/50c20509e464f42ed41004981651cd0686be84c1/src/components/map/routes/Routes.tsx#L30)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't think name `resetRouteMetadataEditingAction` really represents what this action does.

There are two "opposite" actions, `startDrawRoute` and `stopDrawRoute`, and their role is to manipulate store when user starts to draw (create) a new route, or when they finish drawing (creating) a new route by saving the route or cancelling the creation. Stop means that they completely stop (quit), not pause.

I could rename these actions to `startCreateRoute` and `stopCreateRoute`, if it seems better. But I wouldn't want to mix metadata word with these actions, as the state they manipulate is not only related to metadata, but also draw modes etc. I didn't change anything yet, waiting for your opinion.
</blockquote></details>

Yeah, until this point, `startDrawRoute` and `stopDrawRoute` were actually handling the drawing, but with this PR it has been changed.

- `startDrawRoute` -> `startCreateRoute` is a good idea, the name is actually telling what's happening within
- `stopDrawRoute` should rather still be called something like `resetRouteEditing` as it's resetting both the drawing and the metadata editing state
- you could actually probably just combine the `stopDrawRoute` and `stopEditRoute` into a single `resetRouteEditing` reducer that is doing all the resetting. Setting the `creatingNewRoute` to proper values could happen within `startCreateRoute` and `startEditRoute`. But as you are calling these `stopXXRoute` functions from all over the codebase, this refactor might be a bit too much for now

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/199)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
