### PR TITLE
Add editing of stop location details

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/hooks/stop-registry/useEditStopLocationDetails.ts` line 61 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809#-NvfXorACTWei1rynFKW:-NvfXorACTWei1rynFKX:b-8ieprd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84633f507031f2d098d520ed4b24db6d28d6c236/ui/src/hooks/stop-registry/useEditStopLocationDetails.ts#L61)):*
> ```XML
>       // Note: this can't be modified (at the moment at least), but currently this is the only place where it is synced to timetables DB.
>       geometry: {
>         coordinates: [[state.latitude, state.longitude]],
> ```

This axis order is (again) confusing to me since GeoJSON format specifies that the axis order is always **longitude-latitude**

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`ui/src/hooks/stop-registry/useEditStopLocationDetails.ts` line 61 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809#-NvfXorACTWei1rynFKW:-NvfpV8T1_soVuBa2qQP:btwhnfg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84633f507031f2d098d520ed4b24db6d28d6c236/ui/src/hooks/stop-registry/useEditStopLocationDetails.ts#L61)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This axis order is (again) confusing to me since GeoJSON format specifies that the axis order is always **longitude-latitude**
</blockquote></details>

Good catch. This was also wrong in our seed data and wiki documentation. Those have now been fixed as well.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)* status: 2 of 16 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/hooks/stop-registry/useEditStopLocationDetails.ts` line 61 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809#-NvfXorACTWei1rynFKW:-NvfuBg57d-DRwhKGrR_:b8tkyo4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84633f507031f2d098d520ed4b24db6d28d6c236/ui/src/hooks/stop-registry/useEditStopLocationDetails.ts#L61)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Good catch. This was also wrong in our seed data and wiki documentation. Those have now been fixed as well.
</blockquote></details>

Great! I'll leave the reviewing for other parts to the other team members.
___
*[`ui/src/hooks/stop-registry/useEditStopLocationDetails.ts` line 26 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809#-NvgXOah1ysMWsU3ZpGi:-NvgXOah1ysMWsU3ZpGj:bsf1k0w) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cab1f115f4fbb9b685acaf39778e90ba45bd23bc/ui/src/hooks/stop-registry/useEditStopLocationDetails.ts#L26)):*
> ```XML
>     stop,
>   }: EditTiamatParams) => {
>     // TODO: These maps and typanem omits can be avoided completely by using
> ```

`typename`

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)* status: 2 of 16 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`ui/src/hooks/stop-registry/useEditStopLocationDetails.ts` line 26 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809#-NvgXOah1ysMWsU3ZpGi:-NvpAHwwD7KvTF_2KxW-:b-eqs2e6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cab1f115f4fbb9b685acaf39778e90ba45bd23bc/ui/src/hooks/stop-registry/useEditStopLocationDetails.ts#L26)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`typename`
</blockquote></details>

:heavy_check_mark:  Copypasted this from elsewhere and didn't notice.

This typo and its other manifestations get fixed in next PR when I move them elsewhere, so not bothering to touch it here.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 7 of 8 files at r3, 2 of 4 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)* status: all files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`ui/src/components/stop-registry/stops/stop-details/location-details/schema.ts` line 11 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809#-NvpEQhi6j-mIUZ4rI15:-NvpEQhj9f7-w1BBCzxO:b-ayttcs) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cab1f115f4fbb9b685acaf39778e90ba45bd23bc/ui/src/components/stop-registry/stops/stop-details/location-details/schema.ts#L11)):*
> ```XML
>   functionalArea: z
>     .union([z.number().min(0), z.nan(), z.undefined(), z.null()])
>     .transform((fa) => (Number.isNaN(fa) ? undefined : fa)),
> ```

Not sure if this is working as intended, because it seems that tiamat does not accept undefined. (Saving an empty field does not modify the actual value at all). So if this is the case, I would let the form validation warn the user about a required field.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`ui/src/components/stop-registry/stops/stop-details/location-details/schema.ts` line 11 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/809#-NvpEQhi6j-mIUZ4rI15:-Nvpdr0P7aBiUBty5gM5:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cab1f115f4fbb9b685acaf39778e90ba45bd23bc/ui/src/components/stop-registry/stops/stop-details/location-details/schema.ts#L11)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Good catch, this was working incorrectly. Or, the schema was fine, but due to the logic in mutation input creation the value wasn't actually resetted.
Made this required instead.
</blockquote></details>

:ok_hand:

**Pull request merged**
