### PR TITLE
Move map filter to redux

### PR DESCRIPTION
**Pull request by eleksi**
- Remove React context completely by converting map filter context to redux store
- Also suppress Redux's non-serializable warning in set edited stop data action by converting DateTime to ISO string in action creator and converting it back to DateTime in selector.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/redux/actions/mapFilter.ts` line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2PvWdk2gmpC2tU9Qbu:-N2PvWdk2gmpC2tU9Qbv:b-x1fdof) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/685df43ac9caa2ca0671774c312e779d4f946fc0/src/redux/actions/mapFilter.ts#L4)):*
> ```XML
> import { DateTime } from 'luxon';
> 
> export const setMapObservationDateAction = createAction(
> ```

Instead of creating this as a separate action, let's just add it to the slice directly: https://redux-toolkit.js.org/api/createSlice#customizing-generated-action-creators
___
*[`src/redux/slices/mapFilter.ts` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2Pw-Hq7iKnUljQfDaL:-N2Pw-Hr4lR0wxb6-Xo4:b-wqszys) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/685df43ac9caa2ca0671774c312e779d4f946fc0/src/redux/slices/mapFilter.ts#L25)):*
> ```XML
>   showStopFilterOverlay: false,
>   stopFilters: [
>     {
> ```

this data structure makes it a bit complicated to access the individual filters. You've built quite some tooling in useFilterStops to access and to set individual filters... Instead of just moving this structure to redux as is, let's refactor it a tiny bit so that it's more usable:

```
export interface IState {
...
  stopFilters: {
    [key in FilterType]: boolean
  }
}

...

initialState = {
  ...
  stopFilters: {
    FilterType.ShowPastStops: false,
    FilterType.ShowCurrentStops: true,
    FilterType.ShowFutureStops: false,
  }
  ...
}
```

Also the reducer should be simplified:

```
setStopFilter: (state, action: PayloadAction<{filterType: FilterType, enabled: boolean}>) => {
  const {filterType, enabled} = action.payload;
  state.stopFilters[filterType] = enabled;
}
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`src/redux/slices/mapFilter.ts` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2Pw-Hq7iKnUljQfDaL:-N2QfB1hEHHZADLoUnqY:b-cbz9ef) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/685df43ac9caa2ca0671774c312e779d4f946fc0/src/redux/slices/mapFilter.ts#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this data structure makes it a bit complicated to access the individual filters. You've built quite some tooling in useFilterStops to access and to set individual filters... Instead of just moving this structure to redux as is, let's refactor it a tiny bit so that it's more usable:

```
export interface IState {
...
  stopFilters: {
    [key in FilterType]: boolean
  }
}

...

initialState = {
  ...
  stopFilters: {
    FilterType.ShowPastStops: false,
    FilterType.ShowCurrentStops: true,
    FilterType.ShowFutureStops: false,
  }
  ...
}
```

Also the reducer should be simplified:

```
setStopFilter: (state, action: PayloadAction<{filterType: FilterType, enabled: boolean}>) => {
  const {filterType, enabled} = action.payload;
  state.stopFilters[filterType] = enabled;
}
```
</blockquote></details>

Yep, I acknowledged that this is overly complicated way to store these with the current filters. When doing this, I was expecting some more complicated filters that on/off filters to be created as well. For example some filters that would include a payload, which could be saved inside that `Filter` object. But now it seems these are all the filters this view will get and we only have to save one primitive type boolean value in redux, there is no need to have an object for each filter.

Done.
___
*[`src/redux/actions/mapFilter.ts` line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2PvWdk2gmpC2tU9Qbu:-N2Qf9fEDeuEg7ap_if6:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/685df43ac9caa2ca0671774c312e779d4f946fc0/src/redux/actions/mapFilter.ts#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Instead of creating this as a separate action, let's just add it to the slice directly: https://redux-toolkit.js.org/api/createSlice#customizing-generated-action-creators
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/graphql/servicePattern.ts` line 215 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2jgyNL0koYVfmyAfXc:-N2jgyNL0koYVfmyAfXd:b-vz4vvg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b6a8abb86afa978ea1532b54da15f3ee00cc48c5/src/graphql/servicePattern.ts#L215)):*
> ```XML
>     | undefined;
> 
> export interface StoreStop
> ```

I'd like to see a more generic solution for this datetime mapping issue, because this is also going to be an issue with many other entities.

1. Let's create a generic type for converting an object's DateTime fields to string. Something like:
```
export type StoreType<T extends object> = {
  [Property in keyof T]: T[Property] extends DateTime ? string : T[Property];
}
```

2. Let's create mapping functions that are generic, something like:
```
export const mapToStoreType<T extends object> = (input?: T, replaceFields: keyof T): StoreType<T> {
  if (!input) {
    return input;
  }
  return input.reduce((result, current, key) => {
    return replaceFields.includes(key) ? current.toISO() : current;
  }, {})
}
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 27 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`src/graphql/servicePattern.ts` line 215 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2jgyNL0koYVfmyAfXc:-N2p2VgC1MbH97QKWk9K:b-yr9oie) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b6a8abb86afa978ea1532b54da15f3ee00cc48c5/src/graphql/servicePattern.ts#L215)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd like to see a more generic solution for this datetime mapping issue, because this is also going to be an issue with many other entities.

1. Let's create a generic type for converting an object's DateTime fields to string. Something like:
```
export type StoreType<T extends object> = {
  [Property in keyof T]: T[Property] extends DateTime ? string : T[Property];
}
```

2. Let's create mapping functions that are generic, something like:
```
export const mapToStoreType<T extends object> = (input?: T, replaceFields: keyof T): StoreType<T> {
  if (!input) {
    return input;
  }
  return input.reduce((result, current, key) => {
    return replaceFields.includes(key) ? current.toISO() : current;
  }, {})
}
```
</blockquote></details>

I did something like this.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 27 files reviewed, 6 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/graphql/types.ts` line 18 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2p5CZ54ZvN2kNv4Hy9:-N2p5CZ54ZvN2kNv4HyA:b5oo3jq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/39df21cb199991066581dbc9148070be1bb482aa/src/graphql/types.ts#L18)):*
> ```XML
> };
> 
> // eslint-disable-next-line @typescript-eslint/ban-types
> ```

I think these functions rather belong to redux. Could you move these rather to some file called `src/redux/utils/mappers.ts`?
___
*[`src/graphql/types.ts` line 29 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2p3zCq6cofLrTF6P6h:-N2p3zCq6cofLrTF6P6i:b-7c4y61) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/39df21cb199991066581dbc9148070be1bb482aa/src/graphql/types.ts#L29)):*
> ```XML
>       ...result,
>       [key]:
>         replaceFields.includes(key) && input[key]
> ```

```
const value = replaceFields.includes(key) && DateTime.isDateTime(input[key]) ? input[key].toISO() : input[key];
return {
  ...result,
  [key]: value,
};
```
___
*[`src/graphql/types.ts` line 43 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2p4IYV40b89wqrl5Ij:-N2p4IYV40b89wqrl5Ik:bag2d3u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/39df21cb199991066581dbc9148070be1bb482aa/src/graphql/types.ts#L43)):*
> ```XML
>   return Object.keys(input).reduce((result, objectKey) => {
>     const key = objectKey as keyof StoreType<T>;
> ```

```
const value = replaceFields.includes(key) && isDateLike(input[key]) ? parseDate(input[key]) : input[key];
return {
  ...result,
  [key]: value,
}
```

___
*[`src/redux/slices/mapFilter.ts` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2Pw-Hq7iKnUljQfDaL:-N2p5mRh8blRVx0ZBcm5:bvx32y2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/685df43ac9caa2ca0671774c312e779d4f946fc0/src/redux/slices/mapFilter.ts#L25)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Yep, I acknowledged that this is overly complicated way to store these with the current filters. When doing this, I was expecting some more complicated filters that on/off filters to be created as well. For example some filters that would include a payload, which could be saved inside that `Filter` object. But now it seems these are all the filters this view will get and we only have to save one primitive type boolean value in redux, there is no need to have an object for each filter.

Done.
</blockquote></details>

That's very true... now I hope that the filters will stay simple in the future as well :D
___
*[`src/redux/slices/mapFilter.ts` line 15 at r8](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2p4yGs36t5C1qU41QE:-N2p4yGs36t5C1qU41QF:b-yfcgmp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/39df21cb199991066581dbc9148070be1bb482aa/src/redux/slices/mapFilter.ts#L15)):*
> ```XML
>     [key in FilterType]: boolean;
>   };
>   observationDate: string;
> ```

shouldn't this rather be `observationDate?: string`, doesn't this have to allow undefined values?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 27 files reviewed, 6 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/graphql/servicePattern.ts` line 215 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N2jgyNL0koYVfmyAfXc:-N2p67Gp8ISlMCtxavBT:bbqsx5y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b6a8abb86afa978ea1532b54da15f3ee00cc48c5/src/graphql/servicePattern.ts#L215)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I did something like this.
</blockquote></details>

Nice! Good job!

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 28 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`src/components/map/ObservationDateOverlay.tsx` line 36 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33v1wE1jGrq6CoD1l3:-N33v1wE1jGrq6CoD1l4:b-sfe5fy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/components/map/ObservationDateOverlay.tsx#L36)):*
> ```XML
>             value={observationDate.toISODate()}
>             onChange={(e) => {
>               const { value } = e.target;
> ```

please don't write logic inline. Create a new callback for this.
___
*[`src/graphql/types.ts` line 14 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33vJZg9m8gkhP18z2a:-N33vJZg9m8gkhP18z2b:bt8lwhn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/graphql/types.ts#L14)):*
> ```XML
> 
> // eslint-disable-next-line @typescript-eslint/ban-types
> export type StoreType<T extends object> = {
> ```

this doesn't belong to graphql. This belongs to redux, let's move it to a suitable file in the redux folder. Like the new mapper.ts file that you just created
___
*[`src/redux/utils/mappers.ts` line 22 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33wIYbDc2UtrOSt9_f:-N33wIYbDc2UtrOSt9_g:b-3diria) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/redux/utils/mappers.ts#L22)):*
> ```XML
>       [key]: value,
>     };
>   }, {}) as StoreType<T>;
> ```

reduce has a generic overload, so you shouldn't need to use the type casting here

`return Object.keys(input).reduce<T>(...`

the only trick is that you don't put the `{}` value as the last parameter as an initializer
___
*[`src/redux/utils/mappers.ts` line 42 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33wSUbBa0qQBuXSYMx:-N33wSUbBa0qQBuXSYMy:b-3diria) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/redux/utils/mappers.ts#L42)):*
> ```XML
>       [key]: value,
>     };
>   }, {}) as T;
> ```

reduce has a generic overload, so you shouldn't need to use the type casting here

`return Object.keys(input).reduce<T>(...`

the only trick is that you don't put the `{}` value as the last parameter as an initializer

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 28 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[`src/components/map/ObservationDateOverlay.tsx` line 36 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33v1wE1jGrq6CoD1l3:-N3Igesi06BVhDGaZvQs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/components/map/ObservationDateOverlay.tsx#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please don't write logic inline. Create a new callback for this.
</blockquote></details>

Done.
___
*[`src/redux/utils/mappers.ts` line 22 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33wIYbDc2UtrOSt9_f:-N3ImYdnDsrPGDTGVFxl:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/redux/utils/mappers.ts#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

reduce has a generic overload, so you shouldn't need to use the type casting here

`return Object.keys(input).reduce<T>(...`

the only trick is that you don't put the `{}` value as the last parameter as an initializer
</blockquote></details>

Done.
___
*[`src/redux/utils/mappers.ts` line 42 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33wSUbBa0qQBuXSYMx:-N3ImZ-v90J88fYWeO4S:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/redux/utils/mappers.ts#L42)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

reduce has a generic overload, so you shouldn't need to use the type casting here

`return Object.keys(input).reduce<T>(...`

the only trick is that you don't put the `{}` value as the last parameter as an initializer
</blockquote></details>

Done.
___
*[`src/graphql/types.ts` line 14 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/190#-N33vJZg9m8gkhP18z2a:-N3IhG6J9djokmY0NtE3:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/28fd129939bf6ea57d137f89bce14a64b5ee8be8/src/graphql/types.ts#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this doesn't belong to graphql. This belongs to redux, let's move it to a suitable file in the redux folder. Like the new mapper.ts file that you just created
</blockquote></details>

Done.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/190)* status: 0 of 28 files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
