### PR TITLE
Add Via info test

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#1118

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)

### CODE REVIEW

**Review by eleksi — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/routeStops.cy.ts` line 205 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN62Da9EN9XuTn9knC-:-NN62Da9EN9XuTn9knC0:b-x3s6ad) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L205)):*
> ```XML
>     routeStopsTable.toggleRouteSection(routes[0].label);
>     routeStopsTable.createViaPoint(stops[0].label);
>     routeStopsTable.viaForm.getViaFinnishNameInput().clear().type('Via-piste');
> ```

Do these fields really have to be cleared? Are they not empty as we are creating a new via point here?
___
*[`cypress/e2e/routeStops.cy.ts` line 218 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN63Gny9swERTLa-vfw:-NN63Gnz202n-aZ0hYD2:bm2j4fg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L218)):*
> ```XML
>     routeStopsTable.viaForm.getRemoveButton().click();
>     cy.wait('@gqlRemoveScheduledStopPointViaInfo');
>     // Verify that createViaPoint selection is available instead of editViaPoint
> ```

This comment is nice and makes it easier to understand what is happening in the test. It wouldn't be bad to actually add more of these, e.g. in this test, see suggestion below.

I'm not sure if this is something that is really necessary, but at least it would give this test nice "sections" by grouping code rows related to an action and one could easily see what is happening in the test in different parts of the code. Now we have quite a many rows one after another with no spaces between, so it is a bit hard to see the structure, and adding these comments is not very laborsome. 



_Code snippet:_
```XML
// Open via point creation modal 
...
// Input via info to form
...
// Save via info form
...
// Delete via info
```

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)* status: all files reviewed, 4 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/pageObjects/RouteStopsTable.ts` line 52 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN69nc2DH2tMfjp5eHl:-NN69nc2DH2tMfjp5eHm:bmfzu0l) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/pageObjects/RouteStopsTable.ts#L52)):*
> ```XML
>   }
> 
>   createViaPoint(stopLabel: string) {
> ```

I was wondering if more descriptive name would be something like `openCreateViaPointModal`? Or at least something that is more clear about which stage of via point creation we are doing, because opening the modal is just first step to it.

This came to my mind from your other PR where similar action is named `openTimingSettingsForm`
___
*[`cypress/pageObjects/RouteStopsTable.ts` line 57 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN69tjkBD_vov1SB3GM:-NN69tjkBD_vov1SB3GN:b-aeqsl6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/pageObjects/RouteStopsTable.ts#L57)):*
> ```XML
>   }
> 
>   editViaPoint(stopLabel: string) {
> ```

I was wondering if more descriptive name would be something like openEditViaPointModal? 

See previous comment for more explanation.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @eleksi)

___
*[`cypress/e2e/routeStops.cy.ts` line 205 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN62Da9EN9XuTn9knC-:-NN6QfDzCJZSVrhG4jny:b-i00j9x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L205)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Do these fields really have to be cleared? Are they not empty as we are creating a new via point here?
</blockquote></details>

True, in the test scope this is not necessary. Added these clears out of habit, since they are useful in page objects where the methods might be used in situations where the input fields already have some text in them to begin with.
___
*[`cypress/e2e/routeStops.cy.ts` line 218 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN63Gny9swERTLa-vfw:-NN6RtmB1_c2rAQnl3GG:b-eb19fz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L218)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This comment is nice and makes it easier to understand what is happening in the test. It wouldn't be bad to actually add more of these, e.g. in this test, see suggestion below.

I'm not sure if this is something that is really necessary, but at least it would give this test nice "sections" by grouping code rows related to an action and one could easily see what is happening in the test in different parts of the code. Now we have quite a many rows one after another with no spaces between, so it is a bit hard to see the structure, and adding these comments is not very laborsome. 
</blockquote></details>

I added these, but I think this discussion should be had on a higher level - do we want commented tests or do we want to abstract the code a bit more to make it more readable. Until now the comments in PRs have been very conflicting regarding this.

**Review by eleksi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/routeStops.cy.ts` line 205 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN62Da9EN9XuTn9knC-:-NN6_BkI0OIWmGA9SkAC:b9smbwr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L205)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

True, in the test scope this is not necessary. Added these clears out of habit, since they are useful in page objects where the methods might be used in situations where the input fields already have some text in them to begin with.
</blockquote></details>

Thanks! There is one more clear :smile: 
___
*[`cypress/e2e/routeStops.cy.ts` line 209 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN6_FgLDXNhlHTCrEJM:-NN6_FgLDXNhlHTCrEJN:bf5zsyz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L209)):*
> ```XML
>     routeStopsTable.viaForm
>       .getViaFinnishShortNameInput()
>       .clear()
> ```

Please remove this as well. :smile: 
___
*[`cypress/e2e/routeStops.cy.ts` line 218 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN63Gny9swERTLa-vfw:-NN6_SGGElO0-IxzZYKm:b-bcdhfx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L218)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I added these, but I think this discussion should be had on a higher level - do we want commented tests or do we want to abstract the code a bit more to make it more readable. Until now the comments in PRs have been very conflicting regarding this.
</blockquote></details>

Yeah, more abstraction could also work. But the comments help also. I'm not an expert on this topic and have not been involved with tests that much so maybe someone else has more insight. Thanks!

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`cypress/e2e/routeStops.cy.ts` line 209 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN6_FgLDXNhlHTCrEJM:-NN6duo6CsAnz6gLprqf:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/124498266ba99efa02381976de365ebbe1ed1633/cypress/e2e/routeStops.cy.ts#L209)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Please remove this as well. :smile: 
</blockquote></details>

Done.

**Review by eleksi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/routeStops.cy.ts` line 216 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-NN6kslo2gznU9sk2oW9:-NN6kslp0426NZ-Kdrl2:bnypcen) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/0fe1ae52119e6bfaa7954549a37c1a7c5b775a77/cypress/e2e/routeStops.cy.ts#L216)):*
> ```XML
>     toast.checkSuccessToastHasMessage('Via-tieto asetettu');
>     // Delete via info
>     routeStopsTable.openEditViaPointModal(stops[0].label);
> ```

Just came to my mind, should we also check here the fields' contents to make sure they actually are inserted to the db?

**Review by eleksi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/472#-:-NNB3KM23lEuK1MOL8iZ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @sr-vala)

**Pull request merged**
