### PR TITLE
Add --skip-e2e flag to UI dependency start

### PR DESCRIPTION
**Pull request by Leitsi**
Mostly as a possible ram saving measure.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653)

### CODE REVIEW

**Review by culka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`scripts/start-dependencies.sh` line 70 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653#-Nd9ipkr8-ONfk_2J2MY:-Nd9ipkr8-ONfk_2J2MZ:b7k8tl0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8b36094a686af7567a77809b77a7a5384904b748/scripts/start-dependencies.sh#L70)):*
> ```Shell
>   e2eServices=""
>   if [ "$INCLUDE_E2E" = true ]; then
>     e2eServices="jore4-testdb-e2e1 jore4-testdb-e2e2 jore4-testdb-e2e3 jore4-hasura-e2e1 jore4-hasura-e2e2 jore4-hasura-e2e3"
> ```

Since `--volume` and `--skip-e2e` are incompatible. Add a check here if `USE_VOLUME` is true and exit with an error if it is.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`scripts/start-dependencies.sh` line 70 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653#-Nd9ipkr8-ONfk_2J2MY:-NdAWL6o4f1Naoul-nSR:b-wxwssy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8b36094a686af7567a77809b77a7a5384904b748/scripts/start-dependencies.sh#L70)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Since `--volume` and `--skip-e2e` are incompatible. Add a check here if `USE_VOLUME` is true and exit with an error if it is.
</blockquote></details>

Only reason they are "incompatible" is how the command line parameters are handled. That is, only first argument is checked. Didn't seem worth it at the moment to try to add more complex logic for flag parsing to get them both working.
Nothing would actually prevent this code from running with using volumes and skipping e2e containers otherwise.

So, won't be adding the check. But will change the wording on README a bit.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`scripts/start-dependencies.sh` line 70 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653#-Nd9ipkr8-ONfk_2J2MY:-NdENFnF4D_egNoqc2wk:bdupkay) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8b36094a686af7567a77809b77a7a5384904b748/scripts/start-dependencies.sh#L70)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Only reason they are "incompatible" is how the command line parameters are handled. That is, only first argument is checked. Didn't seem worth it at the moment to try to add more complex logic for flag parsing to get them both working.
Nothing would actually prevent this code from running with using volumes and skipping e2e containers otherwise.

So, won't be adding the check. But will change the wording on README a bit.
</blockquote></details>

Adopted your suggestion from Slack so now these can both be used freely.

**Review by culka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/653)* status: 0 of 3 files reviewed, all discussions resolved

**Pull request merged**
