### PR TITLE
Add e2e import tests for temporary and draft timetables

### PR DESCRIPTION
**Pull request by sr-vala**
Resolves HSLdevcom/jore4#1535

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetableImport.cy.ts` line 472 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-Ni8oYA9-6-DOsrBYp-f:-Ni8oYA9-6-DOsrBYp-g:bbotizv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d06ab071bc3bfd71a27f3fb85826a6ac2d15114d/cypress/e2e/timetableImport.cy.ts#L472)):*
> ```XML
>   context('Temporary timetables', () => {
>     beforeEach(() => {
>       cy.task('insertHslTimetablesDatasetToDb', baseTimetableDataInput);
> ```

Makes me think is there a reason why this is done here but not on the draft suite?
___
*[`cypress/e2e/timetableImport.cy.ts` line 601 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-Ni8o9ZK2IMUAJvcoHeM:-Ni8o9ZK2IMUAJvcoHeN:b-84fk4o) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d06ab071bc3bfd71a27f3fb85826a6ac2d15114d/cypress/e2e/timetableImport.cy.ts#L601)):*
> ```XML
>           .getValidityTimeRange()
>           .should('contain', '1.1.2023 - 31.12.2023');
>         route99InboundSundayPassingTimesSectionStandard.assertStopTimes({
> ```

These Sunday schedule assertions are copypasted from special day suite. Could either refactor to a helper function to share those assertions, or maybe consider do we really need to check them twice in such detail in the first place. Would eg. just checking the validity time range be enough? That already should tell us that some other timetable than the one we just improted is active on this observation date.
___
*[`cypress/uploads/hastusImportSaturday.exp` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-Ni8pJjy-0B0VByvCEB0:-Ni8pJjy-0B0VByvCEB1:b-q71soq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d06ab071bc3bfd71a27f3fb85826a6ac2d15114d/cypress/uploads/hastusImportSaturday.exp#L1)):*
> ```
> 1;HASTUS;HSL;1.04;20230501;070707
> ```

Since the timetable DB is truncated between tests, we could just use the same `hastusImport.exp` import file for temporary and draft priorities as well. Guess it's more realistic to have different timetables = different hastus files, sure, but it introduces additional test resources. I would consider deleting these, would require some minor adjusting of dates in the new tests.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 472 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-Ni8oYA9-6-DOsrBYp-f:-Ni8sKeyC5NYWHPFeGlG:bmk4q0s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d06ab071bc3bfd71a27f3fb85826a6ac2d15114d/cypress/e2e/timetableImport.cy.ts#L472)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Makes me think is there a reason why this is done here but not on the draft suite?
</blockquote></details>

Extracted the base timetable data to a helper function, removed the timetable check and left the day type and validity time range check. Added the base timetable check to the draft case as well.
___
*[`cypress/e2e/timetableImport.cy.ts` line 601 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-Ni8o9ZK2IMUAJvcoHeM:-NiDsCtU2E4f4I8VZMsO:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d06ab071bc3bfd71a27f3fb85826a6ac2d15114d/cypress/e2e/timetableImport.cy.ts#L601)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

These Sunday schedule assertions are copypasted from special day suite. Could either refactor to a helper function to share those assertions, or maybe consider do we really need to check them twice in such detail in the first place. Would eg. just checking the validity time range be enough? That already should tell us that some other timetable than the one we just improted is active on this observation date.
</blockquote></details>

Done.
___
*[`cypress/uploads/hastusImportSaturday.exp` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-Ni8pJjy-0B0VByvCEB0:-NiDsLQPEqsmthPiFWMy:bcsyfqr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d06ab071bc3bfd71a27f3fb85826a6ac2d15114d/cypress/uploads/hastusImportSaturday.exp#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Since the timetable DB is truncated between tests, we could just use the same `hastusImport.exp` import file for temporary and draft priorities as well. Guess it's more realistic to have different timetables = different hastus files, sure, but it introduces additional test resources. I would consider deleting these, would require some minor adjusting of dates in the new tests.
</blockquote></details>

I have noticed that it is easy to break tests if one file is used in multiple tests. I would rather use up some bit space than use time in modifying test assertions every time a test needs a change.  In this case: change the export file to hastusImport.exp in the temporary case -> day types don't match between the base data and import data -> one or the other needs to be changed -> other tests need to be changed.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/timetableImport.cy.ts` line 616 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-NiEUvBHBTf89nZU4PcV:-NiEUvBHBTf89nZU4PcW:b-l0en7i) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a91f568941bdc2e53404b9bb7f5fb3736866e3bc/cypress/e2e/timetableImport.cy.ts#L616)):*
> ```XML
>         timetableVersionsPage = new TimetableVersionsPage();
> 
>         const IMPORT_FILENAME = 'hastusImportSundayTemporary.exp';
> ```

Should this be `hastusImportSaturday.exp`? That file is now unused.
___
*[`cypress/e2e/timetableImport.cy.ts` line 652 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-NiEVVVl-N5q9pmKOY40:-NiEVMbGAPdxH0Od0wiH:bh9xa8t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a91f568941bdc2e53404b9bb7f5fb3736866e3bc/cypress/e2e/timetableImport.cy.ts#L652)):*
> ```XML
>         );
> 
>         // Check the Sunday timetable within time range of the temporary timetable
> ```

Temporary -> draft I suppose, since we just imported a draft timetable.
___
*[`cypress/uploads/hastusImportSaturday.exp` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-Ni8pJjy-0B0VByvCEB0:-NiED-XZ9m1C-XhzufJ1:bysyaov) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d06ab071bc3bfd71a27f3fb85826a6ac2d15114d/cypress/uploads/hastusImportSaturday.exp#L1)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I have noticed that it is easy to break tests if one file is used in multiple tests. I would rather use up some bit space than use time in modifying test assertions every time a test needs a change.  In this case: change the export file to hastusImport.exp in the temporary case -> day types don't match between the base data and import data -> one or the other needs to be changed -> other tests need to be changed.
</blockquote></details>

Fair enough :thumbsup:

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/timetableImport.cy.ts` line 616 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-NiEUvBHBTf89nZU4PcV:-NiEg-FqAClBl8R9wZ_x:b-84fp4a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a91f568941bdc2e53404b9bb7f5fb3736866e3bc/cypress/e2e/timetableImport.cy.ts#L616)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should this be `hastusImportSaturday.exp`? That file is now unused.
</blockquote></details>

I deleted hastusImportSaturday.exp and renamed hastusImportSundayTemporary.exp to hastusImportSundayJune2023.exp, since the file itself has no information about being temporary.
___
*[`cypress/e2e/timetableImport.cy.ts` line 652 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/697#-NiEVVVl-N5q9pmKOY40:-NiEgb080Dx68py4vHPz:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a91f568941bdc2e53404b9bb7f5fb3736866e3bc/cypress/e2e/timetableImport.cy.ts#L652)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Temporary -> draft I suppose, since we just imported a draft timetable.
</blockquote></details>

Done.

**Pull request merged**
