### PR TITLE
Adjust map editor

### PR DESCRIPTION
**Pull request by eleksi**
- Upgrade react-map-gl-draw version (Note: this is not the upgrade we have been waiting for!)
- Adjust route draw styling, make lines wider and center handle to the line
- Fix stops showing on top of overlays

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/189)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/189)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`src/components/map/routes/CreateRouteModal.tsx` line 31 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LlmNY122Sg4447FQ6:-N2LlmNY122Sg4447FQ7:bk27tel) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/CreateRouteModal.tsx#L31)):*
> ```XML
>   return (
>     <HTMLOverlay
>       style={{ zIndex: 20 }}
> ```

Does this have to have higher zIndex than HTMLOverlays in Map.tsx?  Do we really have to give zIndes to all of these? Mainaining multiple elements with zIndex properties becomes difficult quite fast.
___
*[`src/components/map/routes/editorStyles.ts` line 56 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LmOKtAdOhEB83TqbD:-N2LmOKtAdOhEB83TqbE:b-la6eu0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/editorStyles.ts#L56)):*
> ```XML
> };
> 
> const INACTIVE_STYLE = UNCOMMITTED_STYLE;
> ```

Please be consistent with these definitions, either define also HOVERED_STYLE like this: `const HOVERED_STYLE = SELECTED_STYLE;`, or copy UNCOMMITTED_STYLE definition also here.

And do we really want to copy just object reference, or should we rather make deep copy of object or at least copy it with spread notation (`const INACTIVE_STYLE = { ...UNCOMMITTED_STYLE };`?
___
*[`src/components/map/routes/editorStyles.ts` line 59 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LnsxZ50l03Ibo2kAb:-N2LnsxZ50l03Ibo2kAc:b-duods) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/editorStyles.ts#L59)):*
> ```XML
> 
> const DEFAULT_STYLE = {
>   stroke: '#000000',
> ```

'red' and 'green' have been used as values for "store" above, so maybe we could just call this "black" for readability and consistency.
___
*[`src/components/map/routes/editorStyles.ts` line 63 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LnRvY7BD6J3ZfBQMu:-N2LnRvY7BD6J3ZfBQMv:bq9r6s8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/editorStyles.ts#L63)):*
> ```XML
> 
> export const featureStyle = ({ state }: { state: RENDER_STATE }) => {
>   let style = null;
> ```

Could be also written without variable... But well, whatever. :smile:

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/189)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`src/components/map/routes/editorStyles.ts` line 56 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LmOKtAdOhEB83TqbD:-N2QWcS93bcbWI6qrDA7:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/editorStyles.ts#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please be consistent with these definitions, either define also HOVERED_STYLE like this: `const HOVERED_STYLE = SELECTED_STYLE;`, or copy UNCOMMITTED_STYLE definition also here.

And do we really want to copy just object reference, or should we rather make deep copy of object or at least copy it with spread notation (`const INACTIVE_STYLE = { ...UNCOMMITTED_STYLE };`?
</blockquote></details>

Done.
___
*[`src/components/map/routes/editorStyles.ts` line 59 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LnsxZ50l03Ibo2kAb:-N2QWdvVAXaM9J1WcAnH:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/editorStyles.ts#L59)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

'red' and 'green' have been used as values for "store" above, so maybe we could just call this "black" for readability and consistency.
</blockquote></details>

Done.
___
*[`src/components/map/routes/editorStyles.ts` line 63 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LnRvY7BD6J3ZfBQMu:-N2QWnGfARA2pwcYvw3z:b-34h1ed) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/editorStyles.ts#L63)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Could be also written without variable... But well, whatever. :smile: 
</blockquote></details>

I think merging state specific style with base feature style is nicer when using a variable.
___
*[`src/components/map/routes/CreateRouteModal.tsx` line 31 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LlmNY122Sg4447FQ6:-N2QVoWW89SFZSHOD3bT:b-1nx6nj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/CreateRouteModal.tsx#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Does this have to have higher zIndex than HTMLOverlays in Map.tsx?  Do we really have to give zIndes to all of these? Mainaining multiple elements with zIndex properties becomes difficult quite fast.
</blockquote></details>

You are right, zIndex is annoying solution. Found a better, simpler one.

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/189)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[`src/components/map/routes/CreateRouteModal.tsx` line 31 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2LlmNY122Sg4447FQ6:-N2QjdO_7u2s8irhzL1H:btojbfd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/4274f2b6472bed193711af71bb6896edf1d1f8e7/src/components/map/routes/CreateRouteModal.tsx#L31)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

You are right, zIndex is annoying solution. Found a better, simpler one.
</blockquote></details>

Great!

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/189)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @eleksi and @tk-vincit)

___
*[`src/components/map/routes/editorStyles.ts` line 35 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/189#-N2Qkaz1DuI4Ej2veybO:-N2Qkaz1DuI4Ej2veybP:b-g4ns02) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/41eab23bb49946456e00f8dbd271f0f2f5fd50f2/src/components/map/routes/editorStyles.ts#L35)):*
> ```XML
> // Feature styles
> 
> const FEATURE_ACTIVE_COLOR = 'rgb(38,181,242)';
> ```

By the way, why these are defined with rgb() and not hex values?



_Code quote:_
```XML
const FEATURE_ACTIVE_COLOR = 'rgb(38,181,242)';
const FEATURE_INACTIVE_COLOR = 'rgb(189,189,189)';
```

**Review by tk-vincit — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/189)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @eleksi and @tk-vincit)

**Pull request merged**
