### PR TITLE
Refactor chooselinedropdown to combobox

### PR DESCRIPTION
**Pull request by HenrikHartiala**
This PR changes the "Connect to line" dropdown menu when creating a route from `<ListBox>` to `<Combobox>` component. This search will not show lines which has the validity_end in the past in the result set. This search also supports `*` character as "any".

`ChooseRouteDropdown` was also changed to support the star character in this PR, and also a minor cosmetic fix when typing the search words. (There was this minor bug that when you typed characters that were already in the selected route, the texts overlapped because it rendered the selected route text on top of the search word

Both Dropdowns are now also sorted alphabetically. There will be many sorting functions in the future and we should have utils for the sorting functions, but for now this should be enough.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/225)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/225)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4ftj436TAFTVWJHvds:-N4ftj444s7Id39VZHDn:b21h6ol) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L23)):*
> ```XML
>   <div>
>     <span>
>       {item.label} ({item.name_i18n.fi_FI})
> ```

let's keep using a template string here - this kind of plain text notation that you used tends to break
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 53 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fw67x23SjlkGQvSom:-N4fw67x23SjlkGQvSon:b-4k2arx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L53)):*
> ```XML
>   const [today] = useState(DateTime.now());
> 
>   const { data: lines } = useGetCurrentOrFutureLinesByLabelQuery(
> ```

please move all this logic to a separate hook. It should take observationDate (default: today) and query (with the original '*' characters) as hook parameters and call useGetCurrentOrFutureLinesByLabelQuery within. All the input and output transformations should happen within this new hook.
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 58 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxt5h6WVCdWaULdf4:-N4fxt5h6WVCdWaULdf5:bp2iyjg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L58)):*
> ```XML
> 
>   const sortedLines = lines?.route_line
>     ?.slice()
> ```

please do the sorting within the graphql query
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 83 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxQZQAGH0R2DfeskK:-N4fxQZQAGH0R2DfeskL:b31ip) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L83)):*
> ```XML
>   };
> 
>   const onSelect = (e: { target: { value: string } }) => {
> ```

isn't this a `ComboboxEvent`?
Also, wouldn't `onItemSelected` be a better name?
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 97 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fwraR13gRIrtBrIXp:-N4fwraR13gRIrtBrIXq:b-im33ev) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L97)):*
> ```XML
>       onChange={onSelect}
>       onBlur={onBlur}
>       onQueryChange={(str) => setQuery(replaceStarCharacter(str))}
> ```

please move this to its own function. Remember throttling so that we don't start a new search on every keyboard button press
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxfrr2GnYWMIaPN8F:-N4fxfrr2GnYWMIaPN8G:b-qi5mq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L68)):*
> ```XML
>   const routes = mapRoutesDetailsResult(routesResult);
> 
>   const sortedRoutes = routes
> ```

as mentioned before, all this business logic should go to its own hook where all the input and output transformations can happen
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 70 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxw6u94zsf8BhoXI2:-N4fxw6u94zsf8BhoXI3:bp2iyjg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L70)):*
> ```XML
>   const sortedRoutes = routes
>     ?.slice()
>     .sort((a, b) => (a.label > b.label ? 1 : -1));
> ```

please do the sorting within the graphql query
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 94 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxdS36P-5VPLOaz8f:-N4fxdS36P-5VPLOaz8g:bkuiqag) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L94)):*
> ```XML
>   };
> 
>   const onSelect = (e: ComboboxEvent) => {
> ```

onItemSelected would be a better name
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 108 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxy8r45lZVUr2lyXx:-N4fxy8r45lZVUr2lyXy:b-63c3a2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L108)):*
> ```XML
>       onChange={onSelect}
>       onBlur={onBlur}
>       onQueryChange={(str) => setQuery(replaceStarCharacter(str))}
> ```

please move this to its own function. Don't forget to throttle it so that a new search wouldn't be initiated on every keyboard button press
___
*[`src/utils/search.ts` line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fyFRoD81W5qsrdumT:-N4fyFRoD81W5qsrdumU:b-jrbyxx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/utils/search.ts#L47)):*
> ```XML
> };
> 
> export const replaceStarCharacter = (str: string) => {
> ```

if you called this function as `mapToSqlLikeValue` or similar then you could get away with exporting and reusing this as a utility function, even look smart while doing so.

Otherwise it looks pretty stupid that you are just doing a string replace within and the name of the function is longer than the code itself :D

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/225)* status: 0 of 12 files reviewed, 11 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4ftj436TAFTVWJHvds:-N4gQTtVCFzYiStDgjKB:brmux6m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's keep using a template string here - this kind of plain text notation that you used tends to break
</blockquote></details>

Check!
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 53 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fw67x23SjlkGQvSom:-N4kUTWE1l8SUO3jWhCA:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L53)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please move all this logic to a separate hook. It should take observationDate (default: today) and query (with the original '*' characters) as hook parameters and call useGetCurrentOrFutureLinesByLabelQuery within. All the input and output transformations should happen within this new hook.
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 58 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxt5h6WVCdWaULdf4:-N4gRtSrC6IgpljSfdxF:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L58)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please do the sorting within the graphql query
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 83 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxQZQAGH0R2DfeskK:-N4kPYPoCPCZDJ_uawsW:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L83)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

isn't this a `ComboboxEvent`?
Also, wouldn't `onItemSelected` be a better name?
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 97 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fwraR13gRIrtBrIXp:-N4xcUkcEjZI4NhjUZZR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/components/forms/route/ChooseLineDropdown.tsx#L97)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please move this to its own function. Remember throttling so that we don't start a new search on every keyboard button press
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxfrr2GnYWMIaPN8F:-N4kxVzOER1is2xtuL9R:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L68)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as mentioned before, all this business logic should go to its own hook where all the input and output transformations can happen
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 70 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxw6u94zsf8BhoXI2:-N4kxWSqCp6NOuodqHPk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L70)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please do the sorting within the graphql query
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 94 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxdS36P-5VPLOaz8f:-N4kxXALEQ615giN2W3r:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L94)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

onItemSelected would be a better name
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 108 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fxy8r45lZVUr2lyXx:-N4kxYAl2qYDe4mdRJa6:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/components/forms/route/ChooseRouteDropdown.tsx#L108)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please move this to its own function. Don't forget to throttle it so that a new search wouldn't be initiated on every keyboard button press
</blockquote></details>

Done.
___
*[`src/graphql/route.ts` line 339 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fzfFuCWJ-VUUOZTG1:-N4kxZLY5ojlVprvETFS:b-ul4ih3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3ba6b4dacd8477ab31ddde0a656d9119c92f1965/src/graphql/route.ts#L339)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think we need the ListAllLines query anymore, you could delete that
</blockquote></details>

Good one!
___
*[`src/utils/search.ts` line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4fyFRoD81W5qsrdumT:-N4x65Mr2t8TOAwvJR4P:btfny9v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a4a7c076ddafc8e168be13f8c337a183a6dc7fa6/src/utils/search.ts#L47)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

if you called this function as `mapToSqlLikeValue` or similar then you could get away with exporting and reusing this as a utility function, even look smart while doing so.

Otherwise it looks pretty stupid that you are just doing a string replace within and the name of the function is longer than the code itself :D
</blockquote></details>

I can change the name to that as well (although it then hides what it actually does and as oppose it gives the information why we do it, which might be more valuable name here) but I do think that it does not matter if the function name is longer than the code if it makes it easier to use / more readable otherwise.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/225)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 49 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zkuMVDolgCPSIv7d6:-N4zkuMVDolgCPSIv7d7:b-jxx8gp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseLineDropdown.tsx#L49)):*
> ```XML
>   const [showButtonContent, setShowButtonContent] = useState(true);
> 
>   const lines = useChooseLineDropdown(query);
> ```

oh, moving it to a hook didn't actually help much with removing much of the clutter... well, you can bring it back here to the component if you want to leave it in the hook: up to you. Sorry, I thought much more of the logic could be moved there...
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 56 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zlTwkEDw7pxafWYnf:-N4zlTwkEDw7pxafWYng:b-7n93e8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseLineDropdown.tsx#L56)):*
> ```XML
> 
>   const mapToButtonContent = (displayedLine?: RouteLine) => {
>     if (!showButtonContent) {
> ```

mapper functions should aim to be pure to be reusable. Here you are using an external state variable, showButtonContent, making it unpure.

I'd just move this to the render:
```
buttonContent={showbuttonContent ? mapToButtonContent(selectedLine) : null}
```
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 60 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zlBOh65Q-HW8Uutos:-N4zlBOh65Q-HW8Uutot:b-jxx8gp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseRouteDropdown.tsx#L60)):*
> ```XML
>   // But we want to hide it when typing new search
>   const [showButtonContent, setShowButtonContent] = useState(true);
>   const routes = useChooseRouteDropdown(query, date, priorities);
> ```

oh, moving it to a hook didn't actually help much with removing much of the clutter... well, you can bring it back here to the component if you want to leave it in the hook: up to you. Sorry, I thought much more of the logic could be moved there...
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 67 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zlvuhD8ifCV1t1LA2:-N4zlvuhD8ifCV1t1LA3:bnr455d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseRouteDropdown.tsx#L67)):*
> ```XML
> 
>   const mapToButtonContent = (displayedRoute?: RouteRoute) => {
>     if (!showButtonContent) {
> ```

mapper functions should aim to be pure to be reusable. Here you are using an external state variable, showButtonContent, making it unpure.

I'd just move this to the render:
```
buttonContent={showbuttonContent ? mapToButtonContent(selectedRoute) : null}
```
___
*[`src/graphql/route.ts` line 334 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zj71J17BYiWx-2N9H:-N4zj71J17BYiWx-2N9I:b-r918za) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/graphql/route.ts#L334)):*
> ```XML
> 
> const GET_CURRENT_OR_FUTURE_LINES_BY_LABEL = gql`
>   query GetCurrentOrFutureLinesByLabel($label: String!, $date: timestamptz) {
> ```

maybe the $date should also be a mandatory parameter, we can always just default it to "NOW" from the caller
___
*[`src/graphql/route.ts` line 345 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zj_Eh24KNd-K9REiT:-N4zj_Eh24KNd-K9REiU:bloj122) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/graphql/route.ts#L345)):*
> ```XML
>       order_by: [{ label: asc }, { validity_start: asc }]
>     ) {
>       ...line_default_fields
> ```

let's retrieve ...line_all_fields here. I'm pretty sure that at some point we'll have to show the lines' priorities as well in the combobox. E.g. when we have overlapping draft, basic and temporary versions as well...

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/225)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 49 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zkuMVDolgCPSIv7d6:-N4zn9Lg4W01MYG2W5mn:bn6121g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseLineDropdown.tsx#L49)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

oh, moving it to a hook didn't actually help much with removing much of the clutter... well, you can bring it back here to the component if you want to leave it in the hook: up to you. Sorry, I thought much more of the logic could be moved there...
</blockquote></details>

Yeah, well the hook is already there and it's nicer that way so I'll keep em. And no problem, at first I also thought that more could be moved there.
___
*[`src/components/forms/route/ChooseLineDropdown.tsx` line 56 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zlTwkEDw7pxafWYnf:-N4znTDt8e6DHp-36SoM:b-qlcfa3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseLineDropdown.tsx#L56)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

mapper functions should aim to be pure to be reusable. Here you are using an external state variable, showButtonContent, making it unpure.

I'd just move this to the render:
```
buttonContent={showbuttonContent ? mapToButtonContent(selectedLine) : null}
```
</blockquote></details>

Thats is nice solution :+1: 
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 60 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zlBOh65Q-HW8Uutos:-N4znorv5HxzcwgiJLvs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseRouteDropdown.tsx#L60)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

oh, moving it to a hook didn't actually help much with removing much of the clutter... well, you can bring it back here to the component if you want to leave it in the hook: up to you. Sorry, I thought much more of the logic could be moved there...
</blockquote></details>

Done.
___
*[`src/components/forms/route/ChooseRouteDropdown.tsx` line 67 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zlvuhD8ifCV1t1LA2:-N4znpG86A1gQmau1d-x:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/components/forms/route/ChooseRouteDropdown.tsx#L67)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

mapper functions should aim to be pure to be reusable. Here you are using an external state variable, showButtonContent, making it unpure.

I'd just move this to the render:
```
buttonContent={showbuttonContent ? mapToButtonContent(selectedRoute) : null}
```
</blockquote></details>

Done.
___
*[`src/graphql/route.ts` line 334 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zj71J17BYiWx-2N9H:-N4znxB65h2de1Y7WvfR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/graphql/route.ts#L334)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe the $date should also be a mandatory parameter, we can always just default it to "NOW" from the caller
</blockquote></details>

Done.
___
*[`src/graphql/route.ts` line 345 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/225#-N4zj_Eh24KNd-K9REiT:-N4zpW_pBY8VUgP7LXiV:b4639rc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/130110f08dce5eab31ac0fec8a10f7fb15884679/src/graphql/route.ts#L345)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's retrieve ...line_all_fields here. I'm pretty sure that at some point we'll have to show the lines' priorities as well in the combobox. E.g. when we have overlapping draft, basic and temporary versions as well...
</blockquote></details>

I can change this to line_all_fields because of the naming of this query, but otherwise I would not fetch information that is not used / needed that comes with the `line_all_fields`.

**Pull request merged**
