### PR TITLE
Seed data from dumps

### PR DESCRIPTION
**Pull request by eleksi**
In this PR we get rid of hasura-seed image. Instead we start seeding needed data in UI repository.

Infrastructure links are seeded using SQL dump which is located in this repository. This PR also makes test not depend on infrastructure link ids, as those are generated UUIDs that will change every time new dump is generated. Now we use external ids, which stay the same.

Routes and lines data is also seeded from dump, but that dump is downloaded from Azure through ./scripts/development.sh script and also imported using the same script.

Resolves https://github.com/HSLdevcom/jore4/issues/1188

This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575)

### CODE REVIEW

**Review by culka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575)* status: 4 of 21 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`start-dependencies.sh` line 72 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSpwjTs20JYOxkGHB65:-NSpwjTs20JYOxkGHB66:bhvvfv8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e2e038ab3ee0fc45517ae14fde0742f959adc9ae/start-dependencies.sh#L72)):*
> ```Shell
>   while ! $SUCCESS; do
>     echo "Checking if infrstructure link schema exists..."
>     if [[ $(psql postgresql://dbadmin:adminpassword@localhost:6432/jore4e2e -AXqtc "SELECT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'infrastructure_network' AND tablename = 'infrastructure_link');") = "t" ]]; then
> ```

Please add the connection string as a `VARIABLE=postrgresql://...` in the beginning of the file, it would look a lot cleaner

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575)* status: 2 of 24 files reviewed, 2 unresolved discussions (waiting on @culka and @eleksi)

___
*[`docker/docker-compose.custom.yml` line 7 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSy1yIUDBP3UZvvYOAD:-NSy1yIUDBP3UZvvYOAE:b-newzg1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/docker/docker-compose.custom.yml#L7)):*
> ```YAML
>     # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
>     # The :seed-data tag contains the latest main-build image with seed data.
>     image: &hasura-image 'hsldevcom/jore4-hasura:hsl-add-created-at-to-vehicle-schedule-frame--20230330-c7f02b6826dab0b6ebea13cd90b15ef275f9b35b'
> ```

If this file is now identical to docker-compose.e2e.yml I think it would make sense to delete the docker-compose.e2e.yml file and remove the related --e2e flag checking logic from start-dependencies.sh. The 'seed-data tag' comment in this compose file can be fixed also.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
This is a big change, this PR could benefit from a little bit detailed description. Maybe a description of what/why something is done in the commit body's as well. Up to you if you want to add them now (not required) , but maybe in the future PR's :+1: 

> Reviewed 3 of 3 files at r3, 1 of 2 files at r4, 9 of 10 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-:-NSyeKBF6ta6V73_Zn7t:b-z0t1a)* status: 23 of 24 files reviewed, 9 unresolved discussions (waiting on @culka, @eleksi, and @sr-vala)

___
*[`.gitignore` line 24 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSydM2V7cEBlqpREHt6:-NSydM2V7cEBlqpREHt7:b-1om7rf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/.gitignore#L24)):*
> ```ignore
> 
> dump.sql
> jore4dump.pgdump
> ```

newline missing
___
*[`cypress/e2e/createRoute.cy.ts` line 44 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyi-suDk58A9HSJVY5:-NSyi-suDk58A9HSJVY6:bb1q3sk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/createRoute.cy.ts#L44)):*
> ```XML
> const testInfraLinks = [
>   {
>     externalId: '445156',
> ```

Btw, how can one find the correct externalIds? Is there some simple way?
___
*[`cypress/e2e/createRoute.cy.ts` line 182 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyormrBescfsm7cpvm:-NSyormrBescfsm7cpvn:b-a4rhkd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/createRoute.cy.ts#L182)):*
> ```XML
> 
>   before(() => {
>     cy.task(
> ```

There is a way to give this task a type with `cy.task<Type>(...)`, but is there a way of getting the right type here? These unknown and any -types are a bit problematic.
___
*[`cypress/e2e/routeStops.cy.ts` line 36 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyvqZX4bIPz2zHwFqM:-NSyvqZX4bIPz2zHwFqN:bd3nep4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/routeStops.cy.ts#L36)):*
> ```XML
> ];
> 
> const buildStops = (infrastructureLinkIds: UUID[]): StopInsertInput[] => [
> ```

Now that this takes infralinkId's as parameter, should we rename this function to "buildStopsToInfralinks". Because I think it is not clear why we need infralinkIds as parameter here. or what do you think?
___
*[`cypress/utils/db.ts` line 84 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSywVJq6_6LON2UwRRt:-NSywVJq6_6LON2UwRRu:b7id6go) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/72b5a8b5c29f8450c58b56c53be0856db342a93b/cypress/utils/db.ts#L84)):*
> ```XML
>   stopsInJourneyPattern,
> }: SupportedResources) => {
>   if (infraLinks) {
> ```

So nice to get rid of these
___
*[`test-db-manager/src/queries/infrastructure.ts` line 15 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSykPlJ28KICg90H6aI:-NSykPlJ28KICg90H6aJ:bmso659) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/test-db-manager/src/queries/infrastructure.ts#L15)):*
> ```XML
> `;
> 
> export const mapToGetInfralinksQuery = (externalIds: string[]) => {
> ```

Should this name be "getInfralinksByExternalIds"? This current name is somehow confusing.

No wait. It took me a while but I just now saw that this just returns an object. And I also see that all the other functions have been named the same way. Oh boy..
So this function returns the requestQueryObject I think?  Bah.. Not sure now how should these be renamed, but currently I can't figure out what `mapToGetFooQuery` would do.

Maybe at least add the whole query name there. So `mapToGetInfrastructureLinksByExternalIdsQuery` etc. Still feels confusing :D 
I dont know.. What do you think?
___
*[`test-db-manager/src/queries/infrastructure.ts` line 22 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyky4_EF9J-kwL-RJd:-NSyky4_EF9J-kwL-RJe:b-pvdrv1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/test-db-manager/src/queries/infrastructure.ts#L22)):*
> ```XML
> };
> 
> export const mapInfraLinkToIds = (res: ExplicitAny) => {
> ```

I think this should be more like "extractInfralinkIdsFromResponse" etc. 
If there is no way to get rid of this ExplicitAny, then maybe add JSDoc comments for it.

Could you also add the correct return type for this (now it is `any`)? I believe it is `UUID[]`

**Review by culka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575)* status: 23 of 24 files reviewed, 10 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @sr-vala)

___
*[`scripts/seed-infrastructure-links.sh` line 12 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSz6ZxS4FxbMI6NpIq4:-NSz6ZxS4FxbMI6NpIq5:bmrid57) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/scripts/seed-infrastructure-links.sh#L12)):*
> ```Shell
>   if [[ $(psql $DB_CONNECTION_STRING -AXqtc "SELECT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'infrastructure_network' AND tablename = 'infrastructure_link');") = "t" ]]; then
>     echo "Schema found! Seeding infrastructure links..."
>       psql $DB_CONNECTION_STRING < test-db-manager/src/dumps/infraLinks/infraLinks.sql; 
> ```

Same comment as in the `start-dependencies.sh` file in regards to relative file paths.

Add a `cd $(dirname "$0")/..` somewhere in the beginning of this file to make all paths relative to the jore4-ui directory or the infraLinks.sql will not be found if the script is ran from other location.
___
*[`start-dependencies.sh` line 72 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSpwjTs20JYOxkGHB65:-NSz2nXv2PrV84c-8-Mt:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e2e038ab3ee0fc45517ae14fde0742f959adc9ae/start-dependencies.sh#L72)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Please add the connection string as a `VARIABLE=postrgresql://...` in the beginning of the file, it would look a lot cleaner
</blockquote></details>

:+1: 
___
*[`scripts/start-dependencies.sh` line 69 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSz2s1uCsz8-4bxKjRX:-NSz2s1uCsz8-4bxKjRY:b-nc3nyu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/scripts/start-dependencies.sh#L69)):*
> ```Shell
> check_pinned_hasura
> start_docker_bundle "${1:-x}"
> sh ./scripts/seed-infrastructure-links.sh
> ```

When referencing other scripts you should use a path relative to the .sh file instead of trusting the user to run it from a expected location. This call will fail if you run it form the `scripts/` path

Actually this seems to be a problem in this whole file, the docker calls use `./docker`

Add a `cd $(dirname "$0")/..` somewhere in the beginning of this file to make all paths relative to the jore4-ui directory.

**Review by eleksi — COMMENTED** [review]
Good point. Added some description. I also had forgot to link the PR which would explain something.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-:-NSz1QyI9qCxH-Eyz8q9:b-hc9wnn)* status: 10 of 25 files reviewed, 9 unresolved discussions (waiting on @culka, @HenrikHartiala, and @sr-vala)

___
*[`.gitignore` line 24 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSydM2V7cEBlqpREHt6:-NSz1fLyCegYIxR3UaNS:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/.gitignore#L24)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

newline missing
</blockquote></details>

Done.
___
*[`cypress/e2e/createRoute.cy.ts` line 44 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyi-suDk58A9HSJVY5:-NSz1gbl-2wKfslK_SVU:bo95eya) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/createRoute.cy.ts#L44)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Btw, how can one find the correct externalIds? Is there some simple way?
</blockquote></details>

I don't think there is any more simple way than there was with ids.

If there is a simple way to find the id, we can find the id first and then check from db which externalId it has.
___
*[`cypress/e2e/createRoute.cy.ts` line 182 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyormrBescfsm7cpvm:-NSz4Jj1AHZae9njN6Zt:b-rgubsc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/createRoute.cy.ts#L182)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

There is a way to give this task a type with `cy.task<Type>(...)`, but is there a way of getting the right type here? These unknown and any -types are a bit problematic.
</blockquote></details>

Great! This helped a lot!
___
*[`cypress/e2e/routeStops.cy.ts` line 36 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyvqZX4bIPz2zHwFqM:-NSz4ruI6fmJdWlcQ5Ml:bu6lr2u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/routeStops.cy.ts#L36)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Now that this takes infralinkId's as parameter, should we rename this function to "buildStopsToInfralinks". Because I think it is not clear why we need infralinkIds as parameter here. or what do you think?
</blockquote></details>

I don't think "buildStopsToInfralinks" works either, it took me very long to realize what this name means. First I thought we are taking stops as a parameter and turning them to infra links :smile: 

Maybe buildStopsOnInfralinks :thinking: 
___
*[`cypress/utils/db.ts` line 84 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSywVJq6_6LON2UwRRt:-NSz4IBiEvZUovBvC1k-:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/72b5a8b5c29f8450c58b56c53be0856db342a93b/cypress/utils/db.ts#L84)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

So nice to get rid of these
</blockquote></details>

Done.
___
*[`docker/docker-compose.custom.yml` line 7 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSy1yIUDBP3UZvvYOAD:-NSzvdWc82sI1rW2MJ8q:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/docker/docker-compose.custom.yml#L7)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

If this file is now identical to docker-compose.e2e.yml I think it would make sense to delete the docker-compose.e2e.yml file and remove the related --e2e flag checking logic from start-dependencies.sh. The 'seed-data tag' comment in this compose file can be fixed also.
</blockquote></details>

Done.
___
*[`scripts/seed-infrastructure-links.sh` line 12 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSz6ZxS4FxbMI6NpIq4:-NSzDPjX6Yz_ZgGwpNO4:b-dw7ral) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/scripts/seed-infrastructure-links.sh#L12)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Same comment as in the `start-dependencies.sh` file in regards to relative file paths.

Add a `cd $(dirname "$0")/..` somewhere in the beginning of this file to make all paths relative to the jore4-ui directory or the infraLinks.sql will not be found if the script is ran from other location.
</blockquote></details>

Good point! Done
___
*[`test-db-manager/src/queries/infrastructure.ts` line 15 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSykPlJ28KICg90H6aI:-NSz2TExEwOarQi_AQGI:bnkltms) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/test-db-manager/src/queries/infrastructure.ts#L15)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should this name be "getInfralinksByExternalIds"? This current name is somehow confusing.

No wait. It took me a while but I just now saw that this just returns an object. And I also see that all the other functions have been named the same way. Oh boy..
So this function returns the requestQueryObject I think?  Bah.. Not sure now how should these be renamed, but currently I can't figure out what `mapToGetFooQuery` would do.

Maybe at least add the whole query name there. So `mapToGetInfrastructureLinksByExternalIdsQuery` etc. Still feels confusing :D 
I dont know.. What do you think?
</blockquote></details>

I didn't want to dive into this naming rabbit hole and just copied the naming schema used previously. Definitely not the best naming, but consistent with previous ones (after including full query).
___
*[`test-db-manager/src/queries/infrastructure.ts` line 22 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyky4_EF9J-kwL-RJd:-NSz4DJR50nDUUOljY73:b-6ydz6t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/test-db-manager/src/queries/infrastructure.ts#L22)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this should be more like "extractInfralinkIdsFromResponse" etc. 
If there is no way to get rid of this ExplicitAny, then maybe add JSDoc comments for it.

Could you also add the correct return type for this (now it is `any`)? I believe it is `UUID[]`

</blockquote></details>

You are right. Changed it.
___
*[`start-dependencies.sh` line 72 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSpwjTs20JYOxkGHB65:-NSz4GtyDqHWxgy7CM8z:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e2e038ab3ee0fc45517ae14fde0742f959adc9ae/start-dependencies.sh#L72)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Please add the connection string as a `VARIABLE=postrgresql://...` in the beginning of the file, it would look a lot cleaner
</blockquote></details>

Done.
___
*[`scripts/start-dependencies.sh` line 69 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSz2s1uCsz8-4bxKjRX:-NSzDTs5-So_FCKs6Cqn:b-dw7ral) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/scripts/start-dependencies.sh#L69)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

When referencing other scripts you should use a path relative to the .sh file instead of trusting the user to run it from a expected location. This call will fail if you run it form the `scripts/` path

Actually this seems to be a problem in this whole file, the docker calls use `./docker`

Add a `cd $(dirname "$0")/..` somewhere in the beginning of this file to make all paths relative to the jore4-ui directory.
</blockquote></details>

Good point! Done

**Review by HenrikHartiala — APPROVED** [review]
Thanks, Great work! All my comments are fixed / noted :+1: 

> Reviewed 1 of 10 files at r5, 14 of 14 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-:-NTCuSYt6TsM1w1BrC6u:b-oipzn1)* status: all files reviewed, 4 unresolved discussions (waiting on @culka and @eleksi)

___
*[`cypress/e2e/createRoute.cy.ts` line 44 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyi-suDk58A9HSJVY5:-NTCuxepC5SWyhlnxo6w:b-kphel5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/createRoute.cy.ts#L44)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't think there is any more simple way than there was with ids.

If there is a simple way to find the id, we can find the id first and then check from db which externalId it has.
</blockquote></details>

Yeah, don't think there was any. So currently the way is to add a somewhere and then just follow database to find the external ID?
___
*[`cypress/e2e/createRoute.cy.ts` line 182 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyormrBescfsm7cpvm:-NTCwCL7Dgb4GNd7qsIv:b-83sjoh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/createRoute.cy.ts#L182)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Great! This helped a lot!
</blockquote></details>

Nice!
___
*[`cypress/e2e/routeStops.cy.ts` line 36 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSyvqZX4bIPz2zHwFqM:-NTCvrut-hGSH4YC4T-J:b-qhjy86) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/cypress/e2e/routeStops.cy.ts#L36)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't think "buildStopsToInfralinks" works either, it took me very long to realize what this name means. First I thought we are taking stops as a parameter and turning them to infra links :smile: 

Maybe buildStopsOnInfralinks :thinking: 
</blockquote></details>

Sounds good :+1: 
___
*[`test-db-manager/src/queries/infrastructure.ts` line 15 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575#-NSykPlJ28KICg90H6aI:-NTCy6MnCatsHTf9Awuk:b-8f6ylu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/aa44c03e2cc59f2d58d971394c9f748d82af9294/test-db-manager/src/queries/infrastructure.ts#L15)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I didn't want to dive into this naming rabbit hole and just copied the naming schema used previously. Definitely not the best naming, but consistent with previous ones (after including full query).
</blockquote></details>

Yeah I totally understand. Maybe if we have time at some point, these could be renamed in one separate PR.

**Review by culka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/575)* status: all files reviewed, 2 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

**Pull request merged**
