### PR TITLE
Show possible conflicts in table (modal) when saving line

### PR DESCRIPTION
**Pull request by tk-vincit**
Related to https://github.com/HSLdevcom/jore4/issues/636

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/123)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/123)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/ConflictResolverModal.tsx, line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq1Nml1YA8_rAiFsaN:-Myq1Nmm6ePHPJfgKw-Z:b-k1l2jc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/components/ConflictResolverModal.tsx#L37)):*
> ```XML
> 
> export const mapLinesToCommonConflictItems = (
>   lines: GetLinesByValidityQuery['route_line'],
> ```

mapping functions are more reusable if they map a single item instead of the whole array.

Also, the input parameter should rather be `RouteLine` instead of `GetLinesByValidityQuery` to make it more reusable
___
*[src/components/ConflictResolverModal.tsx, line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq1lqC6KAy1z_Ds3MT:-Myq1lqC6KAy1z_Ds3MU:b33mnz3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/components/ConflictResolverModal.tsx#L56)):*
> ```XML
>   const isOpen = !!conflicts.length;
> 
>   const renderConflictRow = (item: CommonConflictItem) => (
> ```

Let's rather separate this as its own component instead of embedding it into the ConflictResolverModal thus making them tightly coupled
___
*[src/components/CreateNewLinePage.tsx, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq2Hcl4NkbDDx9rlt3:-Myq2Hcl4NkbDDx9rlt4:bhubawq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/components/CreateNewLinePage.tsx#L27)):*
> ```XML
>   } = useCreateLine();
>   const [conflicts, setConflicts] = useState<
>     GetLinesByValidityQuery['route_line']
> ```

This could be just simply `RouteLine[]`
___
*[src/graphql/route.ts, line 157 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq2id30TKbfVxjNlVu:-Myq2id4CL-EHp9MBaDH:bubeleg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/graphql/route.ts#L157)):*
> ```XML
>   query GetLinesByValidity($filter: route_line_bool_exp) {
>     route_line(where: $filter) {
>       line_id
> ```

`...route_line_default_fields`? Or `...route_line_all_fields`?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/123)* status: 0 of 18 files reviewed, 14 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 80 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDDAeAhdZondbwVYg:-MyqDDAeAhdZondbwVYh:bg0e9hi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/hooks/useCheckValidityAndPriorityConflicts.ts#L80)):*
> ```XML
>   >(GetLinesByValidityDocument);
> 
>   const checkLineValidity = async (params: CommonParams, lineId?: UUID) => {
> ```

I wonder, should we rename this function to "getConflictingLines" or something...? It's not only validating anymore but also returning some results...
___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 95 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqCq1EDzYa3xcAj2ET:-MyqCq1F64Ii36KjIumX:b8a3gi0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/hooks/useCheckValidityAndPriorityConflicts.ts#L95)):*
> ```XML
>     });
> 
>     if (data.route_line.length >= 1) {
> ```

For clarity, instead of directly returning the results, let's place it into a variable with a descriptive name, e.g.:
```
const conflictingLines = data.route_line;
return conflictingLines;
```
___
*[src/hooks/useCreateLine.ts, line 60 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDTqEEjNd_ece9e9l:-MyqDTqEEjNd_ece9e9m:b7jee5b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/hooks/useCreateLine.ts#L60)):*
> ```XML
>     const changes: CreateChanges = {
>       input,
>       conflicts,
> ```

see? useful to have CreateParams and CreateChanges separated ;)
___
*[src/hooks/useEditLine.ts, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDZj9CDtBEdaToltT:-MyqDZj9CDtBEdaToltU:b-k2diql) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/hooks/useEditLine.ts#L21)):*
> ```XML
>   lineId: UUID;
>   patch: RouteLineSetInput;
>   conflicts?: GetLinesByValidityQuery['route_line'];
> ```

`RouteLine[]`?
___
*[src/locales/en-US/common.json, line 82 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDlqK7567G5HikvY-:-MyqDlqK7567G5HikvY0:b-ruhp06) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/locales/en-US/common.json#L82)):*
> ```JSON
>     "validityEnd": "Ends",
>     "indefinite": "Valid indefinitely",
>     "validityConflictTitle": "Change conflicts with existing data",
> ```

"Check" conflicts? The verb "change" doesn't work here
___
*[src/locales/en-US/common.json, line 113 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDuki9IstJ6rwDvE0:-MyqDuki9IstJ6rwDvE1:b-jujtwd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/locales/en-US/common.json#L113)):*
> ```JSON
>   "errors": {
>     "saveFailed": "Something went wrong",
>     "validityConflict": "Priority and validity period is overlapping with existing resource.",
> ```

I'd rather say something like:
"Existing resources were found with overlapping priority and validity period."
___
*[src/locales/fi-FI/common.json, line 82 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqEdF20nfrqLahYLgc:-MyqEdF20nfrqLahYLgd:b-xzhtkn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/locales/fi-FI/common.json#L82)):*
> ```JSON
>     "validityEnd": "Päättyy",
>     "indefinite": "Voimassa toistaiseksi",
>     "validityConflictTitle": "Tallennus sisältää päällekkäisyyksiä",
> ```

technically, it's not the "save" that has conflicts but the "resource" you are trying to save
___
*[src/locales/fi-FI/common.json, line 113 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqEWN_4dflJt40OWMF:-MyqEWN_4dflJt40OWMG:b-r4lbar) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/locales/fi-FI/common.json#L113)):*
> ```JSON
>   "errors": {
>     "saveFailed": "Tallennus epäonnistui",
>     "validityConflict": "Samalla prioriteetilla ja voimassaoloajalla on jo olemassa vastaava resurssi.",
> ```

I'd put this sentence to passive
___
*[src/uiComponents/Modal.tsx, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqEtu1Di7MBZp5jNEq:-MyqEtu1Di7MBZp5jNEr:b-43ple0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/uiComponents/Modal.tsx#L20)):*
> ```XML
>       open={isOpen}
>       onClose={onClose}
>       className={`bg-white ${className || ''}`}
> ```

this will affect all the other components that are using a Modal within. Have you checked if all their designs are still correct?
___
*[src/utils/i18n.ts, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqFGlO-tCs8d5VDez6:-MyqFGlO-tCs8d5VDez7:bha7ml4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/utils/i18n.ts#L4)):*
> ```XML
> import { Priority } from '../types/Priority';
> 
> export const mapPriorityToUiName = (key: Priority) => {
> ```

it doesn't feel right to make this into a util. How would it sound if we moved all i18n related stuff to their own folder, like this:
```
src/i18n
- /locales/en-US/common.json
- /locales/fi-FI/common.json
- /i18n.ts
- /uiNames.ts? (this file)
```

for the scope of this PR, what if you just moved this to a file called `./src/i18n/uiNames.ts` or something similar and in later PRs we could move the other resources here too not to have all this stuff scattered around...

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/123)* status: 0 of 18 files reviewed, 14 unresolved discussions (waiting on @pallost)

___
*[src/components/ConflictResolverModal.tsx, line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq1Nml1YA8_rAiFsaN:-MyqV3h0COctVVt-3LgA:bg172g1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/components/ConflictResolverModal.tsx#L37)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

mapping functions are more reusable if they map a single item instead of the whole array.

Also, the input parameter should rather be `RouteLine` instead of `GetLinesByValidityQuery` to make it more reusable
</blockquote></details>

Good point about input type, don't know why I missed that.

This is easier to use if this maps whole array at once, but as you wish...
___
*[src/components/ConflictResolverModal.tsx, line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq1lqC6KAy1z_Ds3MT:-MyqdTDL86HnZZ1bjw_O:b-5grz1w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/components/ConflictResolverModal.tsx#L56)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Let's rather separate this as its own component instead of embedding it into the ConflictResolverModal thus making them tightly coupled
</blockquote></details>

Does it make any difference as this is (and will be) used only in this component? Then we have to also move `CommonConflictItem` interface definition to new file which will just make thins to scatter all over. Could also inline this with existing JSX if you prefer that way.
___
*[src/components/CreateNewLinePage.tsx, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq2Hcl4NkbDDx9rlt3:-Myq_cDi2lLvZmXPByiF:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/components/CreateNewLinePage.tsx#L27)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This could be just simply `RouteLine[]`
</blockquote></details>

Done.



_Code quote:_
```XML
   GetLinesByValidityQuery['route_line']
```
___
*[src/graphql/route.ts, line 157 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq2id30TKbfVxjNlVu:-MyqXKEd0dZn5oVhUdPC:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/graphql/route.ts#L157)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`...route_line_default_fields`? Or `...route_line_all_fields`? 
</blockquote></details>

Done.
___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 80 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDDAeAhdZondbwVYg:-MyqX_Ra980tNja_7Ezf:bb74ce2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/hooks/useCheckValidityAndPriorityConflicts.ts#L80)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I wonder, should we rename this function to "getConflictingLines" or something...? It's not only validating anymore but also returning some results...
</blockquote></details>

Sure
___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 95 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqCq1EDzYa3xcAj2ET:-Myq_GvL9uMwcKrziJZY:b-eny17q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/hooks/useCheckValidityAndPriorityConflicts.ts#L95)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

For clarity, instead of directly returning the results, let's place it into a variable with a descriptive name, e.g.:
```
const conflictingLines = data.route_line;
return conflictingLines;
```
</blockquote></details>

This "descriptive name" is lost as soon as we return from this function so not sure about that. Anyway, renamed this function so maybe this is easier to read now.
___
*[src/hooks/useEditLine.ts, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDZj9CDtBEdaToltT:-MyqYJBh1I1QrqK6riKZ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/hooks/useEditLine.ts#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`RouteLine[]`?
</blockquote></details>

Done.
___
*[src/locales/en-US/common.json, line 82 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDlqK7567G5HikvY-:-MyqYNnS4Y6gbfQ_u6qH:bdcv6l8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/locales/en-US/common.json#L82)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

"Check" conflicts? The verb "change" doesn't work here
</blockquote></details>

Good point.
___
*[src/locales/en-US/common.json, line 113 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDuki9IstJ6rwDvE0:-MyqYXGC1-ShW1aYQtRG:b-7f2vct) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/locales/en-US/common.json#L113)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather say something like:
"Existing resources were found with overlapping priority and validity period."
</blockquote></details>

You are commenting about line that was deleted so I don't understand what I should do here.
___
*[src/locales/fi-FI/common.json, line 82 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqEdF20nfrqLahYLgc:-MyqYhQf0zkal9XGLVbD:b-vvxmfz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/locales/fi-FI/common.json#L82)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

technically, it's not the "save" that has conflicts but the "resource" you are trying to save
</blockquote></details>

This is according to Figma, but if you have better suggestions I'm listening :shrug: 
___
*[src/locales/fi-FI/common.json, line 113 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqEWN_4dflJt40OWMF:-MyqYodn88G1TKW3nf8T:b5njg82) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/locales/fi-FI/common.json#L113)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd put this sentence to passive
</blockquote></details>

You are commenting about line that was deleted so I don't understand what should be done here
___
*[src/uiComponents/Modal.tsx, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqEtu1Di7MBZp5jNEq:-MyqYw5k2uxH1joy0gQ9:bgjxkfm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/uiComponents/Modal.tsx#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this will affect all the other components that are using a Modal within. Have you checked if all their designs are still correct?
</blockquote></details>

Yes, I checked all other (=all ONE) place where this was previously used and moved class name definitions from there.

Ok, now I realised that maybe `bg-background` class there should rather be `!bg-background` but it didn't seem to have any visible differences. Not sure if bg color definition should be removed from here at some point, but only time will tell.
___
*[src/utils/i18n.ts, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqFGlO-tCs8d5VDez6:-MyqZegpCNGCpt-Wh0jb:b-war9l4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/utils/i18n.ts#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it doesn't feel right to make this into a util. How would it sound if we moved all i18n related stuff to their own folder, like this:
```
src/i18n
- /locales/en-US/common.json
- /locales/fi-FI/common.json
- /i18n.ts
- /uiNames.ts? (this file)
```

for the scope of this PR, what if you just moved this to a file called `./src/i18n/uiNames.ts` or something similar and in later PRs we could move the other resources here too not to have all this stuff scattered around...
</blockquote></details>

:shrug: as you wish.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/123)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[src/components/ConflictResolverModal.tsx, line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-Myq1lqC6KAy1z_Ds3MT:-MyqgxRc1zHjkpreYmv4:b-okudvx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/44f2f416dded69dfdeb0eeed49b23db2e42042a4/src/components/ConflictResolverModal.tsx#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Does it make any difference as this is (and will be) used only in this component? Then we have to also move `CommonConflictItem` interface definition to new file which will just make thins to scatter all over. Could also inline this with existing JSX if you prefer that way.
</blockquote></details>

you could leave it in this file just as a separate component, would that be a good compromise?
___
*[src/hooks/useCheckValidityAndPriorityConflicts.ts, line 95 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqCq1EDzYa3xcAj2ET:-MyqhDCf1IaWm5tYpB_K:b-93zcga) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/hooks/useCheckValidityAndPriorityConflicts.ts#L95)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This "descriptive name" is lost as soon as we return from this function so not sure about that. Anyway, renamed this function so maybe this is easier to read now.
</blockquote></details>

yes, that's enough, now it's clear that what value do we return
___
*[src/locales/en-US/common.json, line 113 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/123#-MyqDuki9IstJ6rwDvE0:-MyqhYyo1lOpNOgqxF9R:becbp47) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68d7c91de4d40c3bee34bbc52f31b5ddd868f0d8/src/locales/en-US/common.json#L113)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You are commenting about line that was deleted so I don't understand what I should do here.
</blockquote></details>

oops :)

**Pull request merged**
