### PR TITLE
Add stop signage editing

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803)

### CODE REVIEW

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803)* status: 2 of 18 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx` line 68 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvGbiRi-J2yN1FL-K0q:-NvHlSAd90-QXn55rfh9:b-fqj8yw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33463b42fbf1f967b5fd5ac260e8fbe547c42d96/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx#L68)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, I would probably rather use a relative width here. But doesn't matter that much here, since these are probably not re-used anyway :D 
Probably these could be also achieved by using rows and columns (grid-cols). So that the layout comes from parent and not needed to explicitly give widths to single elements.
</blockquote></details>

The point here was to limit the width, since wide single-double digit number input looked weird. `w-1/2` is close enough so changed to that.
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx` line 43 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvGgY0HBjfQnIKDScm_:-NvHMalk6ti6G6LSM9KW:bt2vr1b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/568703fb0b42fa51b8effb90247938ee1a001580/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx#L43)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

One thing I noticed, was that the form (and the text area) are not responsive to screen width changes.
text area stretches out of the card, instead it should jump underneath other fields ( you can check the behaviour from basic details form when narrowing down the screen)
</blockquote></details>

Fixed.
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx` line 109 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvGjNwX3FVlYn2faQTL:-NvHMKQa1zrswha-JAs6:b7bweed) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/568703fb0b42fa51b8effb90247938ee1a001580/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx#L109)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Would prefer not to give columns explicit widths. Rather use the row's & formRows and use mdColumns (grid-cols) and structure the layout with them.
</blockquote></details>

Removed, now fills the whole row.

Grid didn't work nicely here, but managed with flex.
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvGd58F0nCsyQ-oXhB-:-NvHNLDn4ap8B6SEva47:bq8ddxr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33463b42fbf1f967b5fd5ac260e8fbe547c42d96/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx#L23)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Out of curiosity, Are these done so that the scheme can have less those ".nullable()" / ".optional()"  definitions?
</blockquote></details>

Something like that.
Though, since Tiamat seems to be fine with null/undefined values for everything here, adjusted the form schema and removed these.
Except for that signType, had to leave that here like this despite adding optionality to schema.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 235 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvVVhnw3MI0IBObt75H:-NvVVhnw3MI0IBObt75I:bckbtsx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b53806dd7ee9ff1c95a876c5b5058c273548bee6/cypress/e2e/stop-registry/stopDetails.cy.ts#L235)):*
> ```XML
>         bdForm.getElyNumberInput().clearAndType('1234568');
> 
>         stopDetailsPage.basicDetails.getSaveButton().click();
> ```

This is more clear, nice! When I wrote this, I did notice that it's kind of confusing to use the bdView, but could not think of a solution. This is nice
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx` line 109 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvGjNwX3FVlYn2faQTL:-NvVYirM9HPVkXyhkToB:b-vfharz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/568703fb0b42fa51b8effb90247938ee1a001580/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx#L109)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Removed, now fills the whole row.

Grid didn't work nicely here, but managed with flex.
</blockquote></details>

I really think that this could be achieved with using simpler combination of classNames
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx` line 49 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvVZ7G_1CILKpEubN5n:-NvVZ7G_1CILKpEubN5o:b-dllcf4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b53806dd7ee9ff1c95a876c5b5058c273548bee6/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx#L49)):*
> ```XML
>         <Row className="flex-wrap gap-10">
>           <Column className="shrink gap-y-5">
>             <Row className="flex flex-wrap gap-8">
> ```

Row already has "flex"
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvGd58F0nCsyQ-oXhB-:-NvVbrTS6Ngk0pTuaIXa:bdqiim2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/33463b42fbf1f967b5fd5ac260e8fbe547c42d96/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsSection.tsx#L23)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Something like that.
Though, since Tiamat seems to be fine with null/undefined values for everything here, adjusted the form schema and removed these.
Except for that signType, had to leave that here like this despite adding optionality to schema.
</blockquote></details>

Yeah, that is kind of why I asked (had to use those in schema) and if this were a better answer, I could've adjusted the basic details schema as well. 
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/schema.ts` line 7 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvVcBp8DeRHWX25mh7t:-NvVcBp8DeRHWX25mh7u:bliwm9e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b53806dd7ee9ff1c95a876c5b5058c273548bee6/ui/src/components/stop-registry/stops/stop-details/signage-details/schema.ts#L7)):*
> ```XML
>   signType: z.nativeEnum(StopPlaceSignType).optional().nullable(),
>   numberOfFrames: z
>     .union([z.number().min(0), z.nan(), z.undefined(), z.null()])
> ```

We could have this change squashed in to the original commit where we create this file, since we are still within the same PR.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803)* status: 16 of 18 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx` line 109 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvGjNwX3FVlYn2faQTL:-NvVf6k-105NH7xpdCRj:bapt1kb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/568703fb0b42fa51b8effb90247938ee1a001580/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx#L109)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I really think that this could be achieved with using simpler combination of classNames
</blockquote></details>

Discussed in slack. Leaving as is. FormRows aka css grid didn't really help, had its own problems.
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx` line 49 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvVZ7G_1CILKpEubN5n:-NvVen3o4XtQox0S02G7:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b53806dd7ee9ff1c95a876c5b5058c273548bee6/ui/src/components/stop-registry/stops/stop-details/signage-details/SignageDetailsForm.tsx#L49)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Row already has "flex"
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/signage-details/schema.ts` line 7 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803#-NvVcBp8DeRHWX25mh7t:-NvVeyIX3tEvU_1vHqx3:brwwuvr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b53806dd7ee9ff1c95a876c5b5058c273548bee6/ui/src/components/stop-registry/stops/stop-details/signage-details/schema.ts#L7)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

We could have this change squashed in to the original commit where we create this file, since we are still within the same PR.
</blockquote></details>

Leaving as separate commit as a means to "document" why this was done.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/803)* status: all files reviewed, 1 unresolved discussion (waiting on @Leitsi)

**Pull request merged**
