### PR TITLE
Update journey pattern ids when seeding database

### PR DESCRIPTION
**Pull request by culka**
Fetch the jourey pattern ids of the two routes used when running dump update script.
Update seed2.ts to read the journey pattern ids from an external file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-NU5XaWt9k24BU0yrzjw):*
Minor typo
___
*[`scripts/extract-seed-route-ids.sh` line 39 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-NU5XpTm1MXY3iqeb5zD:-NU5XpTm1MXY3iqeb5zE:blro4zf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2b2e90b628e7eb4a735f4777653fd17b523d9e4e/scripts/extract-seed-route-ids.sh#L39)):*
> ```Shell
> fi
> 
> echo "// Generated from dump ids
> ```

Nice to have this comment, but it could be a bit more specific even. So something like `Auto-generated from dump ids when running the extract-seed-route-ids.sh or setup-dependencies-and-seed.sh`
___
*[`scripts/extract-seed-route-ids.sh` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-NU5ZFbZ2NKvcuiWdU1e:-NU5ZFbZ2NKvcuiWdU1f:b55a7xf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2b2e90b628e7eb4a735f4777653fd17b523d9e4e/scripts/extract-seed-route-ids.sh#L40)):*
> ```Shell
> 
> echo "// Generated from dump ids
> export const JOURNEY_PATTERN_IDS = {
> ```

Is this actually the right usage of screaming snake case? I am really debating even with myself on this so just wanted to say it out loud. They are constants that won't change during the programs life time, but on the other hand they do change when the script is run :D.
Also in this case this variable name does stand out pretty nicely so I guess I'm just mumbling here with myself :D

**Review by eleksi — COMMENTED** [review]
Nice! Please update (remove) also README section `Fixing timetables seed data` so it does not contain old informatio.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-:-NU5glJvBkRReyUL9euE:bh4ri3b)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @culka and @HenrikHartiala)

**Review by culka — COMMENTED** [review]
Updated

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-:-NU6T2Tg1U6MUn--sRLl:b-bu91xm)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`scripts/extract-seed-route-ids.sh` line 39 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-NU5XpTm1MXY3iqeb5zD:-NU6D-jM14Z3SAQawUu6:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2b2e90b628e7eb4a735f4777653fd17b523d9e4e/scripts/extract-seed-route-ids.sh#L39)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Nice to have this comment, but it could be a bit more specific even. So something like `Auto-generated from dump ids when running the extract-seed-route-ids.sh or setup-dependencies-and-seed.sh`
</blockquote></details>

Done.
___
*[`scripts/extract-seed-route-ids.sh` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-NU5ZFbZ2NKvcuiWdU1e:-NU6DC_A-94ZFUSKSQJP:bi2y4km) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/2b2e90b628e7eb4a735f4777653fd17b523d9e4e/scripts/extract-seed-route-ids.sh#L40)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Is this actually the right usage of screaming snake case? I am really debating even with myself on this so just wanted to say it out loud. They are constants that won't change during the programs life time, but on the other hand they do change when the script is run :D.
Also in this case this variable name does stand out pretty nicely so I guess I'm just mumbling here with myself :D 
</blockquote></details>

Also they won't change unless there's a new dump. :slightly_smiling_face:

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @culka and @HenrikHartiala)

___
*[`test-db-manager/src/seed2.ts` line 37 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-NW1px6y9KbnH7pcD4G5:-NW1px6y9KbnH7pcD4G6:b2y51pk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ec6b67a8b47614880237ef8b5ee9b12c7bf4035c/test-db-manager/src/seed2.ts#L37)):*
> ```XML
>     vehicleTypesResult.data.timetables.timetables_vehicle_type_vehicle_type;
> 
>   // route 641, direction 1
> ```

It seems like this hard-coded comment should be removed or moved to `seed2-ids.ts`.
___
*[`test-db-manager/src/seed2.ts` line 45 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/589#-NW1q0e65bETkHU4iZvu:-NW1q0e65bETkHU4iZvv:b2y51pk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ec6b67a8b47614880237ef8b5ee9b12c7bf4035c/test-db-manager/src/seed2.ts#L45)):*
> ```XML
>   });
> 
>   // route 641, direction 2
> ```

It seems like this hard-coded comment should be removed or moved to `seed2-ids.ts`.

**Pull request closed without merging**
