### PR TITLE
Listbox

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/49)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/49)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[.prettierignore, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiAHHA7cVCFvNSnz3e:-MoiAHHBDx-esPQJx9Ex:b-jsdp8y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/.prettierignore#L11)):*
> ```ignore
> 
> # external docker dependencies
> docker
> ```

I was actually doing the same...
Maybe you could still unignore our custom files, which are stored in git:
```
!docker/docker-compose.custom.yml
!docker/2524600800000_seed-data
```
___
*[src/uiComponents/Listbox.tsx, line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiAsZH6mtQ1gDByGnK:-MoiAsZI9Q5TiY2I5F1t:b-osvsqa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L41)):*
> ```XML
>   onBlur,
> }: Props): JSX.Element => {
>   const addClassName = (child: ReactElement, newClassName: string) => {
> ```

This seems to be copypasta from `src/components/navbar/DropdownMenu.tsx`? I think this should rather be extracted to some util file that could be used from both places.
___
*[src/uiComponents/Listbox.tsx, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiB725-XsEDHRzowG7:-MoiB725-XsEDHRzowG8:b-rqeclk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L53)):*
> ```XML
>   };
> 
>   const onItemSelected = (val: string) => {
> ```

Why not just call this "value"? That would also make next line shorter & prettier.
___
*[src/uiComponents/Listbox.tsx, line 69 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiBKTHCn3Ncczafx0Q:-MoiBKTHCn3Ncczafx0R:b-sw0bh2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L69)):*
> ```XML
>         <>
>           <HUIListbox.Button
>             className="flex items-center w-full h-10 h-full border border-grey rounded focus:outline-none"
> ```

`h-10` and `h-full` are conflicting, right? Either one could and should be removed.
___
*[src/uiComponents/Listbox.tsx, line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiBWBH00VnliO1RiKO:-MoiBWBH00VnliO1RiKP:blg4xe1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L80)):*
> ```XML
>             />
>           </HUIListbox.Button>
>           <Transition
> ```

Copypasta from `src/components/navbar/DropdownMenu.tsx`? Maybe we should extract that to own component.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/49)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @tk-vincit)

___
*[.prettierignore, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiAHHA7cVCFvNSnz3e:-MorRcgb-OtnVb_HpukX:b-8a3jsk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/.prettierignore#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I was actually doing the same...
Maybe you could still unignore our custom files, which are stored in git:
```
!docker/docker-compose.custom.yml
!docker/2524600800000_seed-data
```
</blockquote></details>

ok, miksi ei :thumbsup: 
___
*[src/uiComponents/Listbox.tsx, line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiAsZH6mtQ1gDByGnK:-MorT9a2B8X2ewPiaJus:bb7f2mf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L41)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This seems to be copypasta from `src/components/navbar/DropdownMenu.tsx`? I think this should rather be extracted to some util file that could be used from both places.
</blockquote></details>

done
___
*[src/uiComponents/Listbox.tsx, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiB725-XsEDHRzowG7:-MorTIPhA7ltk8ZVkwlN:bl35ndx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L53)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why not just call this "value"? That would also make next line shorter & prettier.
</blockquote></details>

that would conflict with the property name defined in the upper scope (which is also "value)
___
*[src/uiComponents/Listbox.tsx, line 69 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiBKTHCn3Ncczafx0Q:-MorTb4fBUCGQbjMHHHk:b-eh30q5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L69)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`h-10` and `h-full` are conflicting, right? Either one could and should be removed.
</blockquote></details>

Done. Didn't notice this...
___
*[src/uiComponents/Listbox.tsx, line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiBWBH00VnliO1RiKO:-MorWrlY2P78Gdm7w37U:b-95hqqw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L80)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Copypasta from `src/components/navbar/DropdownMenu.tsx`? Maybe we should extract that to own component.
</blockquote></details>

I extracted it as a prop list as I believe it's more reusable that way. So instead of having DropdownTransition, ButtonTransition, CheckboxTransition, etc components, just having them as props that could be applied as <Transition {...dropdownTransition}>... maybe even mix and match them in the future?

**Review by tk-vincit — APPROVED** [review]
This brand new listbox component wasn't used in this PR yet, right? Generally it would make more sense to intoduce new components within commits that actually use those. Otherwise this PR looks good.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-:-MpBw-0x7u3rWnRAEF1j:bgcnav7)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[src/uiComponents/Listbox.tsx, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiB725-XsEDHRzowG7:-MpBvHr25Al88NXhaoqE:b-7a1zh2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L53)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

that would conflict with the property name defined in the upper scope (which is also "value)
</blockquote></details>

ok, didn't noticed that
___
*[src/uiComponents/Listbox.tsx, line 69 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiBKTHCn3Ncczafx0Q:-MpBvteh2XOqQehaFbwq:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L69)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Done. Didn't notice this...
</blockquote></details>

Thanks!
___
*[src/uiComponents/Listbox.tsx, line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/49#-MoiBWBH00VnliO1RiKO:-MpBvOgTE7bQ8171-64v:b-we71cx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/736ebf3b3f484d20be26613ac8ce126695edc9de/src/uiComponents/Listbox.tsx#L80)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I extracted it as a prop list as I believe it's more reusable that way. So instead of having DropdownTransition, ButtonTransition, CheckboxTransition, etc components, just having them as props that could be applied as <Transition {...dropdownTransition}>... maybe even mix and match them in the future?
</blockquote></details>

That works for me. Maybe its a bit unlogical to have it in this component, but this is good enought for now. :)

**Comment by tk-vincit** [comment]
Changes included & merged in https://github.com/HSLdevcom/jore4-ui/pull/52

**Pull request closed without merging**
