### PR TITLE
Use `jore4-mbtiles-server` as primary source for road network + stops data

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/28)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 4 of 5 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/28)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @tk-vincit)

___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8IzSI2EStJym6pqlh):*
> ```
> MapGL
> ```

MapLibre
___
*[README.md, line 97 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8J72O9ye_CUo0JlNP:-Mj8J72O9ye_CUo0JlNQ:bfrnwv4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L97)):*
> ```
> Experiementing
> ```

Experimenting
___
*[README.md, line 107 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8JMm3-QhKdsJ_2aRp:-Mj8JMm3-QhKdsJ_2aRq:bfrnwv4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L107)):*
> ```
> Experiementing
> ```

Experimenting
___
*[README.md, line 110 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8JVEJDacRWtmjP8sP:-Mj8JVEJDacRWtmjP8sQ:b-7onwyo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L110)):*
> ```
> experiementing
> ```

experimenting
___
*[README.md, line 115 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8JgU42J-xExAhBfvS:-Mj8JgU42J-xExAhBfvT:by7snkg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L115)):*
> ```
> k_material
> ```

Under current circumstances `r_material` is the proper one to use.
___
*[README.md, line 115 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8Jk9g8QrmPcxd0xDU:-Mj8Jk9g8QrmPcxd0xDV:b-t1et8q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L115)):*
> ```
> k_material
> ```

r_material
___
*[README.md, line 147 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8KXIw5KBol7ERXa8Y:-Mj8KXIw5KBol7ERXa8Z:b1tk5um) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L147)):*
> ```
> MapGL
> ```

MapLibre
___
*[src/components/map/Filters.tsx, line 38 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8K48FA02D_LdrD8tB:-Mj8K48FA02D_LdrD8tC:b-frdg9p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/src/components/map/Filters.tsx#L38)):*
> ```
> digiroad.dr_linkki_k
> ```

`digiroad.dr_linkki` when switching from R material to K variant.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/28)* status: 7 of 8 files reviewed, 14 unresolved discussions (waiting on @jarkkoka and @tk-vincit)

___
*[README.md, line 100 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8R6MYDWL7Nc_BW43Y:-Mj8R6MYDWL7Nc_BW43Z:bfc1x3q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L100)):*
> ```Markdown
> 
> Primary way of presenting vector tiles in UI will be using pre-calculated vector tiles.
> They offer much better performance compared to dynamically calculating those on-demand.
> ```

pre-rendered.. rendering those on-demand
___
*[README.md, line 102 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8RH6xA_I1vX2Q-PYA:-Mj8RH6xA_I1vX2Q-PYB:burar1t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L102)):*
> ```
>UI UI,
> ```
UI
___
*[README.md, line 109 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8RSATDTd_ktNCssvr:-Mj8RSATDTd_ktNCssvs:b-em2t8g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L109)):*
> ```
> worflow
> ```
workflow
___
*[README.md, line 110 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8JVEJDacRWtmjP8sP:-Mj8RY9T2hEdGbv6XPRI:bg8v7mc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L110)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> experiementing
> ```

experimenting
</blockquote></details>

experimenting *with* something
___
*[src/components/map/Filters.tsx, line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8Ry4n5iKCLQL6Xzsy:-Mj8Ry4n5iKCLQL6Xzsz:bjg11h7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/src/components/map/Filters.tsx#L23)):*
> ```XML
>   'http://localhost:3200/services/dr_pysakki/tiles/{z}/{x}/{y}.pbf';
> const drDynamicStopsUrl =
>   'http://localhost:3100/digiroad.dr_pysakki/{z}/{x}/{y}.pbf';
> ```

all these urls are now static, so they won't work in a Kubernetes context. You should rather use dynamic absolute urls (e.g. `/services/dr_pysakki...` or `/digiroad.dr_pysakki` and then do the routing to the actual localhost:**** urls in your dev server
___
*[src/components/mapgl-map/DynamicStopVectorLayer.tsx, line 11 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8SUkLBuxzbzPcdZTz:-Mj8SUkLBuxzbzPcdZU-:b-cnogdr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/src/components/mapgl-map/DynamicStopVectorLayer.tsx#L11)):*
> ```XML
>     <Source
>       type="vector"
>       tiles={['http://localhost:3100/digiroad.dr_pysakki/{z}/{x}/{y}.pbf']}
> ```

should not use static urls, because they won't work in Kubernetes
___
*[src/components/mapgl-map/StopVectorLayer.tsx, line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8S_d64mSLkDqSMwfY:-Mj8S_d64mSLkDqSMwfZ:b-cnogdr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/src/components/mapgl-map/StopVectorLayer.tsx#L12)):*
> ```XML
>       type="vector"
>       tiles={[
>         'http://localhost:3200/services/dr_pysakki/tiles/{z}/{x}/{y}.pbf',
> ```

should not use static urls, because they won't work in Kubernetes

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/28)* status: 7 of 8 files reviewed, 14 unresolved discussions (waiting on @jarkkoka, @pallost, and @tk-vincit)

___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8IzSI2EStJym6pqlh):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> MapGL
> ```

MapLibre
</blockquote></details>

Opened discussion about this in Slack, but I think that MapGL is correct term for now.
___
*[README.md, line 97 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8J72O9ye_CUo0JlNP:-Mj9Wn7eAqYPvioms_Dh:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L97)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Experiementing
> ```

Experimenting
</blockquote></details>

Done.
___
*[README.md, line 100 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8R6MYDWL7Nc_BW43Y:-Mj9XHn60quF6SVqwz-3:brpsfqx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L100)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

pre-rendered.. rendering those on-demand
</blockquote></details>

Are you 100% sure?
https://reviewable.io/reviews/hsldevcom/jore4-ui/24#-Mi0YVi43pe7dpmg1G5Q
___
*[README.md, line 102 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8RH6xA_I1vX2Q-PYA:-Mj9XNbN1YOo2pkpuECG:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L102)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

> ```
>UI UI,
> ```
UI
</blockquote></details>

Done.
___
*[README.md, line 109 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8RSATDTd_ktNCssvr:-Mj9XW5Q6t4lugr8T0P-:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L109)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

> ```
> worflow
> ```
workflow
</blockquote></details>

Done.
___
*[README.md, line 110 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8JVEJDacRWtmjP8sP:-Mj9X_CK-Fgun8W13e55:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L110)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

experimenting *with* something
</blockquote></details>

Done.
___
*[README.md, line 115 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8JgU42J-xExAhBfvS:-MjDLl9DDwQIjV3dSM-Q:b7j58zr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L115)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> k_material
> ```

Under current circumstances `r_material` is the proper one to use.
</blockquote></details>

Ok. Updated also sql statements below and verified locally that they still work.
___
*[README.md, line 115 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8Jk9g8QrmPcxd0xDU:-MjDLsgX6tiUopDD_npT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L115)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> k_material
> ```

r_material
</blockquote></details>

Done.
___
*[README.md, line 147 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8KXIw5KBol7ERXa8Y:-MjDDx1P9gS4TMLW7ylW:b-hz9ayx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L147)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> MapGL
> ```

MapLibre
</blockquote></details>

Let's continue discussion on previous comment about this.
___
*[src/components/map/Filters.tsx, line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8Ry4n5iKCLQL6Xzsy:-MjDFLWi-f9wGaI7IIau:b87fszv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/src/components/map/Filters.tsx#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

all these urls are now static, so they won't work in a Kubernetes context. You should rather use dynamic absolute urls (e.g. `/services/dr_pysakki...` or `/digiroad.dr_pysakki` and then do the routing to the actual localhost:**** urls in your dev server
</blockquote></details>

This is nothing new and not in scope of this PR. This is larger issue and affects also e.g. hasura-related things. 

We have card about this in backlog: https://github.com/HSLdevcom/jore4/issues/474
I suggest we fix this in another PR.
___
*[src/components/mapgl-map/DynamicStopVectorLayer.tsx, line 11 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8SUkLBuxzbzPcdZTz:-MjDE7-ME5Hoh6_IXcui:b-2s3nhq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/src/components/mapgl-map/DynamicStopVectorLayer.tsx#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should not use static urls, because they won't work in Kubernetes
</blockquote></details>

Let's continue discussion in previous thread about this.
___
*[src/components/mapgl-map/StopVectorLayer.tsx, line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8S_d64mSLkDqSMwfY:-MjDECr36bIEOW0u7JET:b-zg4etn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/src/components/mapgl-map/StopVectorLayer.tsx#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should not use static urls, because they won't work in Kubernetes
</blockquote></details>

Let's continue discussion in first thread about this.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/28)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @jarkkoka, @pallost, and @tk-vincit)

___
*[-- commits, line 4 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8IzSI2EStJym6pqlh):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Opened discussion about this in Slack, but I think that MapGL is correct term for now.
</blockquote></details>

Fine by me ;)
___
*[README.md, line 100 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/28#-Mj8R6MYDWL7Nc_BW43Y:-MjDN8EXEqwU606k8f0D:b-ra74yo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5a457a34256edc3ec7819ec8e710f7401a9a8c54/README.md#L100)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Are you 100% sure?
https://reviewable.io/reviews/hsldevcom/jore4-ui/24#-Mi0YVi43pe7dpmg1G5Q
</blockquote></details>

Fine by me

**Pull request merged**
