### PR TITLE
Stop using seed data in tests

### PR DESCRIPTION
**Pull request by sr-vala**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/406)

### CODE REVIEW

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/406)* status: all files reviewed, 5 unresolved discussions (waiting on @sr-vala)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9_zxI95Lh7ef-3doD):*
Both commit messages declare to resolve jore4#1020, should it only be in the latter?
___
*[`cypress/e2e/createRoute.cy.ts` line 121 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9UvfP2VSLJHzYOBVx:-NH9UvfP2VSLJHzYOBVy:b-eq6os2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e13979d985bcee7ce43895cd3ac29e69fcc2da30/cypress/e2e/createRoute.cy.ts#L121)):*
> ```XML
>     cy.mockLogin();
> 
>     const mapLocation = [24.929689228090112, 60.16495016651525];
> ```

I would prefer this as an object:
```
const mapLocation = {
   latitude: 60.16....,
   longitude: 24.92... 
}
```
Or the short versions, `lat` and `lng`

This way it can't be accidentally initialized/used in the wrong order. And it will be easier to read: `mapLocation[0]` vs `mapLocation.lng`
___
*[`cypress/e2e/createRoute.cy.ts` line 163 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9YoFV-3SJFfZVNjw2:-NH9YoFV-3SJFfZVNjw3:b-1gg5zm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e13979d985bcee7ce43895cd3ac29e69fcc2da30/cypress/e2e/createRoute.cy.ts#L163)):*
> ```XML
>             rightOffset: 35,
>             downOffset: -20,
>             mapMarkerTestId: stopTestIds.testStop3,
> ```

Just making sure, was this intentional to be testStop3 instead of testStop2?
___
*[`cypress/e2e/createRoute.cy.ts` line 200 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9Z4ZU7WfepgSS-NjA:-NH9Z4ZU7WfepgSS-NjB:b-n4w04m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e13979d985bcee7ce43895cd3ac29e69fcc2da30/cypress/e2e/createRoute.cy.ts#L200)):*
> ```XML
>             rightOffset: 35,
>             downOffset: -20,
>             mapMarkerTestId: stopTestIds.testStop3,
> ```

Same question as above.
___
*[`cypress/e2e/stops.cy.ts` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9i9rL-1vzt0HxDM8I:-NH9i9rM2fCWT_2umSsT:b23vhx9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6be26f01133985020e37e6f7e369f6b8268ad2f8/cypress/e2e/stops.cy.ts#L50)):*
> ```XML
>   before(() => {
>     cy.fixture('infraLinks/infraLinks.sql').then((infraLinks) => {
>       cy.task('executeRawDbQueryWithoutBindings', infraLinks);
> ```

I'm not completely sure how the bindings work, but you _could_ also just call the `executeRawDbQuery` and not give the bindings:
`cy.task('executeRawDbQuery', {query: infraLinks })` <- And also maybe rename the `infraLinks` to `infraLinksQuery` etc.
___
*[`cypress/e2e/stops.cy.ts` line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9bxOHCpVerHYxyoag:-NH9bxOHCpVerHYxyoah:b9okvp7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6be26f01133985020e37e6f7e369f6b8268ad2f8/cypress/e2e/stops.cy.ts#L56)):*
> ```XML
>   beforeEach(() => {
>     clearDatabase();
>     deleteCreatedResources();
> ```

I think this should be inside `clearDatabase()`
___
*[`cypress/plugins/index.js` line 58 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9cxPE2C5SZSjC_16d:-NH9cxPE2C5SZSjC_16e:b72u9uc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6be26f01133985020e37e6f7e369f6b8268ad2f8/cypress/plugins/index.js#L58)):*
> ```JavaScript
>         });
>     },
> ```

This is an object, so not sure if these added newlines help the readability or mislead from it being an object.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/406)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9_zxI95Lh7ef-3doD):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Both commit messages declare to resolve jore4#1020, should it only be in the latter?
</blockquote></details>

Done.
___
*[`cypress/e2e/createRoute.cy.ts` line 121 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9UvfP2VSLJHzYOBVx:-NHACLFF3331WO3EDjOs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e13979d985bcee7ce43895cd3ac29e69fcc2da30/cypress/e2e/createRoute.cy.ts#L121)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I would prefer this as an object:
```
const mapLocation = {
   latitude: 60.16....,
   longitude: 24.92... 
}
```
Or the short versions, `lat` and `lng`

This way it can't be accidentally initialized/used in the wrong order. And it will be easier to read: `mapLocation[0]` vs `mapLocation.lng`
</blockquote></details>

Done.
___
*[`cypress/e2e/createRoute.cy.ts` line 163 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9YoFV-3SJFfZVNjw2:-NHACM_-Dw5Q4naH0rWi:bqyvd2r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e13979d985bcee7ce43895cd3ac29e69fcc2da30/cypress/e2e/createRoute.cy.ts#L163)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Just making sure, was this intentional to be testStop3 instead of testStop2?
</blockquote></details>

Yes. This way the route is longer and covers all three stops.
___
*[`cypress/e2e/createRoute.cy.ts` line 200 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9Z4ZU7WfepgSS-NjA:-NHACTFW7ii8s2N7pEQM:bs4q9op) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e13979d985bcee7ce43895cd3ac29e69fcc2da30/cypress/e2e/createRoute.cy.ts#L200)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Same question as above.
</blockquote></details>

Ditto.
___
*[`cypress/e2e/stops.cy.ts` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9i9rL-1vzt0HxDM8I:-NHACYuJBo07iyrjQ5r0:b5k3jz3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6be26f01133985020e37e6f7e369f6b8268ad2f8/cypress/e2e/stops.cy.ts#L50)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I'm not completely sure how the bindings work, but you _could_ also just call the `executeRawDbQuery` and not give the bindings:
`cy.task('executeRawDbQuery', {query: infraLinks })` <- And also maybe rename the `infraLinks` to `infraLinksQuery` etc.
</blockquote></details>

Changed this.
___
*[`cypress/e2e/stops.cy.ts` line 56 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9bxOHCpVerHYxyoag:-NHACdrQ9eBpZxItuh85:b-pg0mn5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6be26f01133985020e37e6f7e369f6b8268ad2f8/cypress/e2e/stops.cy.ts#L56)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this should be inside `clearDatabase()`
</blockquote></details>

Refactored this also.
___
*[`cypress/plugins/index.js` line 58 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9cxPE2C5SZSjC_16d:-NHAChUrAh4JwbgzWEG3:bva0ue8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6be26f01133985020e37e6f7e369f6b8268ad2f8/cypress/plugins/index.js#L58)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is an object, so not sure if these added newlines help the readability or mislead from it being an object.
</blockquote></details>

To me it looked crowded but we can keep it as it was.

**Review by HenrikHartiala — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/406)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @sr-vala)

___
*[`.github/workflows/run-cypress-tests.yml` line 23 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTsgHIBPWjs_uKCoJ-:-NHTsgHIBPWjs_uKCoJ0:bogaiiq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/.github/workflows/run-cypress-tests.yml#L23)):*
> ```YAML
> 
>       - name: start e2e env
>         uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1
> ```

Was this change related to this PR? Or was this originally part of some other PR? Just checking if this is supposed to be here.
___
*[`cypress/e2e/createRoute.cy.ts` line 163 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NH9YoFV-3SJFfZVNjw2:-NHTtKox3aQSdQdIjQsK:b-rcqfvl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e13979d985bcee7ce43895cd3ac29e69fcc2da30/cypress/e2e/createRoute.cy.ts#L163)):*
<details><summary><i>Previously, sr-vala wrote…</i></summary><blockquote>

Yes. This way the route is longer and covers all three stops.
</blockquote></details>

Okay :+1: 
___
*[`cypress/e2e/utils/db-utils.ts` line 14 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTw79r77WpxexCwina:-NHTw79r77WpxexCwinb:bnwrf55) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/cypress/e2e/utils/db-utils.ts#L14)):*
> ```XML
> 
> export const deleteStopsByLabel = (labels: string[]) => {
>   labels.forEach((label) => {
> ```

No need to do anything about this in this PR, since it is also used in `deleteRoutes`, but I wonder if this could be done in a single SQL query.
___
*[`cypress/pageObjects/RouteStopsOverlay.ts` line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTwfm9-nSZw-BFRDoj:-NHTwfm9-nSZw-BFRDok:bmt9tdb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/cypress/pageObjects/RouteStopsOverlay.ts#L29)):*
> ```XML
>   removeStopsFromRoute(stopLabels: string[]) {
>     stopLabels.forEach((label) => {
>       this.getRouteStopRowMenu(label).should('exist');
> ```

If these extra assertions did not fix the problem (and if we know that the chained click also does this assertion), then maybe we should remove these lines. Also this is still really confusing why this suddenly stopped working, even though the video shows that nothing is wrong.

**Review by sr-vala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/406)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`.github/workflows/run-cypress-tests.yml` line 23 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTsgHIBPWjs_uKCoJ-:-NHXZFxX3FpCkV3bUVEw:bodeqxa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/.github/workflows/run-cypress-tests.yml#L23)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Was this change related to this PR? Or was this originally part of some other PR? Just checking if this is supposed to be here.
</blockquote></details>

Originally the test setup used docker-compose.custom.yml here, which in turn used the hasura seed image. I first created the docker-compose.e2e.yml to start the dependencies with the hasura hsl image, but Tamas informed me of this setup action which is a better way to start the dependencies in the CI. docker-compose.e2e.yml can be used when developing or running tests locally.
___
*[`cypress/e2e/utils/db-utils.ts` line 14 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTw79r77WpxexCwina:-NHX_bBW9J7VihN7q2mH:b-8m74n5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/cypress/e2e/utils/db-utils.ts#L14)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

No need to do anything about this in this PR, since it is also used in `deleteRoutes`, but I wonder if this could be done in a single SQL query.
</blockquote></details>

Wondered about that as well at some point but haven't spent time on it.
___
*[`cypress/pageObjects/RouteStopsOverlay.ts` line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTwfm9-nSZw-BFRDoj:-NHX_xgKAY_ilON2eODf:b3slolj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/cypress/pageObjects/RouteStopsOverlay.ts#L29)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

If these extra assertions did not fix the problem (and if we know that the chained click also does this assertion), then maybe we should remove these lines. Also this is still really confusing why this suddenly stopped working, even though the video shows that nothing is wrong.
</blockquote></details>

Test is now passing after adding some 'exist' and 'be.visible' checks, but I guess we need to keep an eye on this.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/406)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @sr-vala)

___
*[`.github/workflows/run-cypress-tests.yml` line 23 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTsgHIBPWjs_uKCoJ-:-NHYOdFt7YNV17OSFhlK:b-92hdbr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/.github/workflows/run-cypress-tests.yml#L23)):*
<details><summary><i>Previously, sr-vala wrote…</i></summary><blockquote>

Originally the test setup used docker-compose.custom.yml here, which in turn used the hasura seed image. I first created the docker-compose.e2e.yml to start the dependencies with the hasura hsl image, but Tamas informed me of this setup action which is a better way to start the dependencies in the CI. docker-compose.e2e.yml can be used when developing or running tests locally.
</blockquote></details>

Ah okay, thanks for the explanation!
___
*[`cypress/pageObjects/RouteStopsOverlay.ts` line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/406#-NHTwfm9-nSZw-BFRDoj:-NHYOyWq2wr660Eiqz2A:b-sv1al8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/18fe4aa25f8f6419a24c74ac0559e6b4f8c45185/cypress/pageObjects/RouteStopsOverlay.ts#L29)):*
<details><summary><i>Previously, sr-vala wrote…</i></summary><blockquote>

Test is now passing after adding some 'exist' and 'be.visible' checks, but I guess we need to keep an eye on this.
</blockquote></details>

You should remove the `exist` assertion, because the `be.visible`covers it already.

**Review by HenrikHartiala — APPROVED** [review]
> Reviewed 1 of 7 files at r3, 1 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/406)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sr-vala)

**Pull request merged**
