### PR TITLE
Map modal

### PR DESCRIPTION
**Pull request by tk-vincit**
Fixes https://github.com/HSLdevcom/jore4/issues/442

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/29)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/29)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[src/components/RoutesAndLinesPage.tsx, line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/29#-MjZ5REp5dMkXi0lMobw:-MjZ5REp5dMkXi0lMobx:btbtjhs) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ccf179ebfca0b81c86b80324671a25bee02d225f/src/components/RoutesAndLinesPage.tsx#L23)):*
> ```XML
>       <Row className="mt-2">
>         <SimpleButton className="ml-auto" onClick={() => setIsOpen(true)}>
>           Avaa modaalissa
> ```

this would need a translation
___
*[src/components/RoutesAndLinesPage.tsx, line 26 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/29#-MjZ5XAF-TRniv6rkXzE:-MjZ5XAG8QdvRqxyg9xz:btbtjhs) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ccf179ebfca0b81c86b80324671a25bee02d225f/src/components/RoutesAndLinesPage.tsx#L26)):*
> ```XML
>         </SimpleButton>
>       </Row>
>       <h2 className="text-bold mb-14 mt-12 text-4xl">Esimerkkireitit</h2>
> ```

this would need a translation
___
*[src/components/mapgl-map/Map.tsx, line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/29#-MjZ5dbbA-IJT7mrylrV:-MjZ5dbbA-IJT7mrylrW:b-8hd4i5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ccf179ebfca0b81c86b80324671a25bee02d225f/src/components/mapgl-map/Map.tsx#L15)):*
> ```XML
> interface Props {
>   className?: string;
>   // width and height are passed as params to `react-map-gl`.
> ```

can it be that somehow its `position` attribute is messed up? There was something that for `position: absolute` elements you cannot set percentual heights, only absolute heights? Should check in the DOM inspector...

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/29)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

**Review by pallost — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/29#-:-MjZM74A-WO1b-XuhbZP:bnfp4nl)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/29)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[src/components/RoutesAndLinesPage.tsx, line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/29#-MjZ5REp5dMkXi0lMobw:-MjZB-TO6fXEQqXDAuxk:b-wi5r63) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ccf179ebfca0b81c86b80324671a25bee02d225f/src/components/RoutesAndLinesPage.tsx#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this would need a translation
</blockquote></details>

This is just temporary string that won't end up in final product.
___
*[src/components/RoutesAndLinesPage.tsx, line 26 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/29#-MjZ5XAF-TRniv6rkXzE:-MjZBCyc4To3ovCI8Pwm:b-wi5r63) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ccf179ebfca0b81c86b80324671a25bee02d225f/src/components/RoutesAndLinesPage.tsx#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this would need a translation
</blockquote></details>

This is just temporary string that won't end up in final product.
___
*[src/components/mapgl-map/Map.tsx, line 15 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/29#-MjZ5dbbA-IJT7mrylrV:-MjZBEsW0-uc7ZojcBS5:b-gh8aop) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ccf179ebfca0b81c86b80324671a25bee02d225f/src/components/mapgl-map/Map.tsx#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

can it be that somehow its `position` attribute is messed up? There was something that for `position: absolute` elements you cannot set percentual heights, only absolute heights? Should check in the DOM inspector...
</blockquote></details>

I spent too much time on devtools already playing around with this, and just couldn't get `height: 100%` working.

Anyway, find out ugly hack which seems to work perfectly, so should we just go with it then?

**Pull request merged**
