### PR TITLE
#650: Refactor stop deletion to use hooks

### PR DESCRIPTION
**Pull request by pallost**
Closes HSLdevcom/jore4#650

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)

### CODE REVIEW

**Review by eleksi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)* status: all files reviewed, 6 unresolved discussions (waiting on @pallost)

___
*[src/components/map/Stops.tsx, line 211 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-mqI11G3E2XbfdP4l:-Mz-mqI11G3E2XbfdP4m:b-xxvxix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L211)):*
> ```XML
>   const buildDeleteConfirmationText = (changes: DeleteChanges) => {
>     const deletedStopText = t('confirmDeleteStopDialog.description', {
>       stopLabel: changes.deletedStop?.label || '',
> ```

Can label really be null/undefined? That would really mess with our logic where all stops with the same label are different versions of the same stop.
___
*[src/components/map/Stops.tsx, line 226 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-nT0ZEa2aZ6tTXkIp:-Mz-nT0ZEa2aZ6tTXkIq:b-gjdpmo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L226)):*
> ```XML
>     }
> 
>     return confirmationTextParts.join('\n');
> ```

\n probably has no effect in the UI, but I guess this confirmation text part will be iterated soon anyway so I don't know if it really matters.
___
*[src/components/map/Stops.tsx, line 234 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-o5ax3Aj63MQ2ivu5:-Mz-o5ax3Aj63MQ2ivu6:b-iwlnt1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L234)):*
> ```XML
>     setSelectedStopId(undefined);
>     // the newly created stop should become a regular stop from a draft
>     await stopsResult.refetch();
> ```

Good to have this annoying bug finally fixed.
___
*[src/hooks/useDeleteStop.ts, line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-onxn8qXqrHb5K3SN:-Mz-onxn8qXqrHb5K3SO:bokga6t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L44)):*
> ```XML
>   >(GetStopWithRouteGraphDataByIdDocument);
> 
>   // find all journey patterns from which this stop will been removed
> ```

typo? in `will been`
___
*[src/hooks/useDeleteStop.ts, line 84 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-pyDjDO0ngA3C9xQy:-Mz-pyDjDO0ngA3C9xQz:bbawi7g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L84)):*
> ```XML
>       deletedStop: stopWithRouteGraphData,
>       deleteStopFromRoutes,
>       deleteStopFromJourneyPatterns,
> ```

I expect returning this is for the future if a route might have multiple journey patterns?
___
*[src/hooks/useDeleteStop.ts, line 112 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-l5DJ1KjtCUc0e52k:-Mz-l5DJ1KjtCUc0e52l:b-ubgdql) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L112)):*
> ```XML
>   // default handler that can be used to show error messages as toast
>   // in case an exception is thrown
>   const defaultErrorHandler = (err: Error) => {
> ```

Will we have multiple error handlers for the same hook in some cases or why is this called defaultErrorHandler?

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)* status: all files reviewed, 11 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/Stops.tsx, line 153 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzE9oZPEMgJsDwnlsRN:-MzE9oZPEMgJsDwnlsRO:br7cwzs) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L153)):*
> ```XML
> 
>       try {
>         const changes = await prepareDelete({
> ```

We already have `deleteChanges` on local state, do we want to calculate those again?
___
*[src/components/map/Stops.tsx, line 215 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEAIXb-e7ZvqgQ1NM6:-MzEAIXb-e7ZvqgQ1NM7:b-fnfsmg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L215)):*
> ```XML
>     const confirmationTextParts: string[] = [deletedStopText];
> 
>     // if stop is deleted from a route, also list
> ```

"also list" what? Is something missing from there?
___
*[src/components/map/Stops.tsx, line 234 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-o5ax3Aj63MQ2ivu5:-MzE6qMs-1HVyw8-kljv:bvleif) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L234)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Good to have this annoying bug finally fixed.
</blockquote></details>

:+1: 

The comment is only about created stops but I assume this also affects edited stops?
___
*[src/components/map/Stops.tsx, line 290 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEAdF-DNajGBZ6mLsL:-MzEAdF-DNajGBZ6mLsM:b-78on5d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L290)):*
> ```XML
>         <EditStopModal
>           defaultValues={mapStopDataToFormState(popupInfo)}
>           onCancel={() => setShowEditForm(false)}
> ```

Is is correct that onCancel and onClose do now different things? Usually they should do the same thing.
___
*[src/hooks/useDeleteStop.ts, line 68 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEBU9J4c5xpVT7j8mq:-MzEBU9K0eDlsmxh4FsO:b8or7fh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L68)):*
> ```XML
>     if (isStartingOrEndingStopOfAnyRoute(stopId, stopWithRouteGraphData)) {
>       throw new EditRouteTerminalStopsError(
>         'Cannot delete the starting and ending stops of a route',
> ```

Idea: if we know which route(s) are causing conflict then maybe we should list + mention those (at least at some point)?
___
*[src/hooks/useDeleteStop.ts, line 99 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEBvQo2E5gVg6jfsw1:-MzEBvQo2E5gVg6jfsw2:bdexudn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L99)):*
> ```XML
>   const removeStop = (variables: RemoveStopMutationVariables) => {
>     removeStopMutation({
>       ...mapToVariables(variables),
> ```

Isn't `... { variables: variables }` same as just `variables: variables` that can even to shortened to `variables`?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)* status: 8 of 9 files reviewed, 11 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[src/components/map/Stops.tsx, line 153 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzE9oZPEMgJsDwnlsRN:-MzEicO25cSB6FDI0WM4:b-ioc5ju) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L153)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We already have `deleteChanges` on local state, do we want to calculate those again?
</blockquote></details>

true! I fixed it now but at some later point the whole interaction should be rethought and refactored
___
*[src/components/map/Stops.tsx, line 211 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-mqI11G3E2XbfdP4l:-MzEil2ODnOJlgidsXNQ:bsf1t5o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L211)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Can label really be null/undefined? That would really mess with our logic where all stops with the same label are different versions of the same stop.
</blockquote></details>

no, but the deletedStop can be undefined... actually, I just put a `!` operator there because at that point we know that the stop must exist, so it's pointless to allow it even being undefined... so this is now fixed as well
___
*[src/components/map/Stops.tsx, line 215 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEAIXb-e7ZvqgQ1NM6:-MzEjibC3o5ivy8MwUvx:bdap3iy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L215)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"also list" what? Is something missing from there?
</blockquote></details>

whoops, fixed!
___
*[src/components/map/Stops.tsx, line 226 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-nT0ZEa2aZ6tTXkIp:-MzEm8Qg4fyi_eb6IGwO:b-7ql1td) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L226)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

\n probably has no effect in the UI, but I guess this confirmation text part will be iterated soon anyway so I don't know if it really matters.
</blockquote></details>

fixed
___
*[src/components/map/Stops.tsx, line 234 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-o5ax3Aj63MQ2ivu5:-MzEmOMm7DsBVBnVUVda:b-r3ukfu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L234)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

:+1: 

The comment is only about created stops but I assume this also affects edited stops?
</blockquote></details>

edited stops' data is automatically updated in the apollo cache after the mutation... but I could write that into the comment
___
*[src/components/map/Stops.tsx, line 290 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEAdF-DNajGBZ6mLsL:-MzEoEJ13hgrFbqfrdAb:b-kl8g4c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/components/map/Stops.tsx#L290)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is is correct that onCancel and onClose do now different things? Usually they should do the same thing.
</blockquote></details>

good catch!
___
*[src/hooks/useDeleteStop.ts, line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-onxn8qXqrHb5K3SN:-MzEo2yF-M0thpyooOj7:b-7ql1td) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L44)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

typo? in `will been`
</blockquote></details>

fixed
___
*[src/hooks/useDeleteStop.ts, line 68 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEBU9J4c5xpVT7j8mq:-MzEnyWA8MtolGdsZie9:bh3jb9r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L68)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Idea: if we know which route(s) are causing conflict then maybe we should list + mention those (at least at some point)?
</blockquote></details>

good point! I added a //TODO comment about it!
___
*[src/hooks/useDeleteStop.ts, line 84 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-pyDjDO0ngA3C9xQy:-MzEnHChDZNYHha88ZlX:b-i51neg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L84)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I expect returning this is for the future if a route might have multiple journey patterns?
</blockquote></details>

yes, indeed. Well, stops are technically only removed from journey patterns but they don't have enough metadata that we could show to the user that "hey! the stop is removed from journey pattern XYZ". So the second best we can do is show the affected route...
___
*[src/hooks/useDeleteStop.ts, line 99 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEBvQo2E5gVg6jfsw1:-MzEn85s4kfsLx9W0doc:bwluhsf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L99)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Isn't `... { variables: variables }` same as just `variables: variables` that can even to shortened to `variables`?
</blockquote></details>

it wasn't me who created the mapToVariables function ;) but I can just remove it if you'd like me to 
___
*[src/hooks/useDeleteStop.ts, line 112 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-Mz-l5DJ1KjtCUc0e52k:-MzEmmukE71wR4UD-KDQ:b-ds377m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L112)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Will we have multiple error handlers for the same hook in some cases or why is this called defaultErrorHandler?
</blockquote></details>

this is default, because you can use it as default or you can make your own in case you didn't like it :)

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[src/components/map/Stops.tsx, line 152 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEzEmsEDp6wznwZXfE:-MzEzEmsEDp6wznwZXfF:b-nnsqu3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/014dd20194d02f6b6ada016308e19b479eb90d66/src/components/map/Stops.tsx#L152)):*
> ```XML
>   const onRemoveDraftStop = async () => {
>     setDraftStop(undefined);
>     await onStopEditingFinished();
> ```

There's no need to referch stop results when removing draft stop. But it doens't do any harm neither, so this is ok for me.
___
*[src/hooks/useDeleteStop.ts, line 99 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEBvQo2E5gVg6jfsw1:-MzEymZl2gZU00TIpdVE:bubthsx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L99)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it wasn't me who created the mapToVariables function ;) but I can just remove it if you'd like me to 
</blockquote></details>

You didn't understood what I meant.
You could still replace `...{ variables }` with just `variables`

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[src/components/map/Stops.tsx, line 152 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEzEmsEDp6wznwZXfE:-MzFSjXo9J_0SiVkOmZi:b3cqu81) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/014dd20194d02f6b6ada016308e19b479eb90d66/src/components/map/Stops.tsx#L152)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

There's no need to referch stop results when removing draft stop. But it doens't do any harm neither, so this is ok for me.
</blockquote></details>

sure, I made a flag parameter for this :+1: 
___
*[src/hooks/useDeleteStop.ts, line 99 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/125#-MzEBvQo2E5gVg6jfsw1:-MzFS1nlEdlZT8Hp5cB-:b-r6spwl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408f838027835a1bad36bbbd249141f7dfdb86d9/src/hooks/useDeleteStop.ts#L99)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You didn't understood what I meant.
You could still replace `...{ variables }` with just `variables`
</blockquote></details>

jepp, now I got it... thanks :D

**Review by tk-vincit — APPROVED** [review]
> Reviewed 2 of 8 files at r2, 2 of 5 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/125)* status: all files reviewed, 6 unresolved discussions (waiting on @eleksi and @tk-vincit)

**Pull request merged**
